import type { BlogPost } from '../types';

export const compressingPosts: BlogPost[] = [
  {
    slug: 'how-to-compress-a-pdf-without-losing-quality',
    title: 'How to Compress a PDF Without Losing Quality',
    description: 'Shrink a PDF while keeping it readable. What compression actually removes, how far you can push it, and how to check the result before you send it.',
    keyword: 'compress pdf without losing quality',
    category: 'Compressing',
    published: '2026-02-14',
    updated: '2026-08-18',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: '"Without losing quality" needs a small correction: compression that makes a real difference to file size does discard something. The useful question is whether it discards anything you can see.' },
      { type: 'p', text: 'On a scanned document, the answer is usually no — you can cut 80% of the size with the text still perfectly crisp. On a photographic brochure, the answer is yes, and you need to be more careful.' },
      { type: 'h2', text: 'Compress a PDF' },
      { type: 'steps', items: [
        'Open the Compress PDF tool and add your file.',
        'Pick a level. Start conservative; you can always go further.',
        'Compare the result with the original at 100% zoom before you use it.',
        'If it is still too large, step up one level rather than jumping to maximum.',
      ] },
      { type: 'h2', text: 'What compression actually does' },
      { type: 'p', text: 'Nearly all of the size in a large PDF is images, so nearly all of compression is about images. Three things happen:' },
      { type: 'list', items: [
        'Downsampling: a 600 DPI image is reduced to 150 DPI, throwing away pixels you were never going to see on screen.',
        'Re-encoding: images are recompressed as JPEG at a lower quality setting.',
        'Structural clean-up: duplicate resources merged, unused objects dropped, fonts subset to the characters actually used.',
      ] },
      { type: 'p', text: 'The last of these is genuinely lossless and sometimes recovers a surprising amount on files that have been edited repeatedly.' },
      { type: 'callout', title: 'Text is never the problem', text: 'A hundred pages of text is a few hundred kilobytes. If your PDF is 40 MB, it is images — or one image, repeated on every page as a background or a scanned letterhead.' },
      { type: 'h2', text: 'What you can expect' },
      { type: 'table', head: ['Document type', 'Typical reduction', 'Risk'], rows: [
        ['Scanned text pages', '70–90%', 'Very low — text stays legible'],
        ['Report with a few photos', '40–70%', 'Low at moderate settings'],
        ['Photo-heavy brochure', '30–60%', 'Visible softening if pushed'],
        ['Pure text document', '5–15%', 'None, but little to gain'],
        ['Already-compressed file', 'Almost nothing', 'You are re-compressing damage'],
      ] },
      { type: 'h2', text: 'Check it properly' },
      { type: 'steps', items: [
        'Open the compressed file next to the original at 100% zoom.',
        'Look at the smallest text on the busiest page — that is where damage appears first.',
        'Check any photographs for blocky artefacts in smooth areas like skies and skin.',
        'If it will be printed, print one page. Screen quality and print quality are not the same test.',
        'Confirm the text is still selectable — if it is not, the tool rasterised your pages.',
      ] },
      { type: 'h2', text: 'Never compress twice' },
      { type: 'p', text: 'JPEG damage accumulates. Compressing an already-compressed file re-encodes artefacts as if they were detail, so you lose quality for very little size. If the result is not small enough, go back to the original and compress it harder in one pass.' },
    ],
    faqs: [
      { q: 'Is PDF compression lossless?', a: 'The structural part is. The part that produces real savings — downsampling and re-encoding images — is lossy by design.' },
      { q: 'How much smaller can a PDF get?', a: 'Scanned documents routinely lose 70–90%. Text-only files barely move, because they were already small.' },
      { q: 'Will compression make my text blurry?', a: 'Not if the text is real text — it is not an image and is untouched. In a scan, the text is part of the image, which is why heavy settings can soften it.' },
      { q: 'Can I undo compression?', a: 'No. Keep the original.' },
      { q: 'Why did my file barely shrink?', a: 'Either it was already optimised, or it is genuinely mostly text. There is nothing to remove.' },
    ],
    related: ['why-is-my-pdf-so-large', 'how-to-compress-a-scanned-pdf', 'how-to-compress-pdf-for-email-attachment'],
  },

  {
    slug: 'why-is-my-pdf-so-large',
    title: 'Why Is My PDF So Large? (And How to Fix It)',
    description: 'A three-page PDF should not be 45 MB. Here are the six things that actually bloat a PDF, how to identify which one you have, and what to do.',
    keyword: 'why is my pdf so large',
    category: 'Compressing',
    published: '2026-03-08',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: 'PDF file sizes are wildly inconsistent. A 200-page book can be 2 MB and a three-page scan can be 45 MB. The difference is almost never the amount of content — it is what the content is made of.' },
      { type: 'h2', text: 'The six usual causes' },
      { type: 'h3', text: '1. It is a scan' },
      { type: 'p', text: 'Every page is a full-page photograph. At 300 DPI in colour, one A4 page is roughly 25 megapixels of data before compression. This accounts for the majority of oversized PDFs, and it compresses extremely well.' },
      { type: 'h3', text: '2. Images at print resolution used at thumbnail size' },
      { type: 'p', text: 'Someone dropped a 12-megapixel photo into a document and scaled it to a 5 cm square. The page shows a thumbnail; the file still contains all 12 megapixels. Downsampling fixes it entirely.' },
      { type: 'h3', text: '3. Embedded fonts, in full' },
      { type: 'p', text: 'A complete font family can be several megabytes, and a document using six of them carries all six. Subsetting keeps only the characters actually used and typically recovers most of that.' },
      { type: 'h3', text: '4. A background on every page' },
      { type: 'p', text: 'A scanned letterhead or watermark image placed on all forty pages can be stored forty times over. De-duplication collapses it to one copy.' },
      { type: 'h3', text: '5. Edit history' },
      { type: 'p', text: 'PDFs support incremental saving: each edit appends to the file rather than rewriting it. A document edited twenty times can carry twenty layers of superseded objects. Rewriting the file discards them.' },
      { type: 'h3', text: '6. Embedded attachments' },
      { type: 'p', text: 'PDFs can carry other files inside them — spreadsheets, images, whole documents. They are invisible in the reader and count fully towards the size.' },
      { type: 'callout', title: 'Diagnose in ten seconds', text: 'Try to select text on a page. If you cannot, it is a scan and compression will help enormously. If you can, and the file is still huge, look for large photographs or a repeated background image.' },
      { type: 'h2', text: 'What to do about it' },
      { type: 'table', head: ['Cause', 'Fix', 'Typical saving'], rows: [
        ['Scan', 'Compress with downsampling', '70–90%'],
        ['Oversized images', 'Downsample to 150–200 DPI', '50–80%'],
        ['Full embedded fonts', 'Subset fonts', '10–40%'],
        ['Repeated background', 'De-duplicate resources', 'Varies, sometimes dramatic'],
        ['Edit history', 'Rewrite the file', '10–50%'],
        ['Attachments', 'Remove them if not needed', 'Whatever they weigh'],
      ] },
      { type: 'p', text: 'A general-purpose optimiser addresses most of these in one pass, which is why "compress" fixes so many oversized PDFs even when the cause is not obviously an image.' },
      { type: 'h2', text: 'Avoiding it next time' },
      { type: 'list', items: [
        'Scan at 300 DPI greyscale, not 600 DPI colour, for ordinary text.',
        'Resize images before placing them in a document, not after.',
        'Export to PDF once at the end rather than saving repeatedly.',
        'Use two or three typefaces, not eight.',
      ] },
    ],
    faqs: [
      { q: 'Why is my scanned PDF 50 MB?', a: 'Because it contains a photograph of every page. Compression typically brings it under 5 MB with no visible change to printed text.' },
      { q: 'Does the page count determine file size?', a: 'Barely. What the pages contain matters far more — a 500-page text document can be smaller than a three-page scan.' },
      { q: 'Can I see what is taking up the space?', a: 'Some desktop tools report space by object type. In practice, the text-selection test tells you what you need to know in a few seconds.' },
      { q: 'Is a large PDF a problem?', a: 'Only when it hits a limit or a slow connection. If it sends and opens fine, leave it alone.' },
    ],
    related: ['how-to-compress-a-pdf-without-losing-quality', 'how-to-compress-a-scanned-pdf', 'how-to-optimize-a-pdf-for-the-web'],
  },

  {
    slug: 'how-to-compress-pdf-for-email-attachment',
    title: 'How to Compress a PDF for an Email Attachment',
    description: 'Get a PDF under the 25 MB email limit — or the 10 MB one your recipient never mentioned. Practical targets and what to do when compression is not enough.',
    keyword: 'compress pdf for email',
    category: 'Compressing',
    published: '2026-03-24',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: 'The bounce message arrives a minute after you thought the email had gone. Attachment limits are the most common reason anyone compresses a PDF at all.' },
      { type: 'h2', text: 'What the limits actually are' },
      { type: 'table', head: ['Service', 'Limit'], rows: [
        ['Gmail', '25 MB'],
        ['Outlook.com', '20–25 MB'],
        ['Yahoo Mail', '25 MB'],
        ['Corporate Exchange servers', 'Often 10 MB, sometimes less'],
        ['Government and legal portals', 'Frequently 5–10 MB'],
      ] },
      { type: 'callout', title: 'Aim for 60% of the stated limit', text: 'Attachments are encoded for transmission, which inflates them by roughly a third. A 24 MB file can be rejected by a 25 MB limit. And the binding limit is the receiving server\'s, which you cannot see — target 10 MB unless you know better.' },
      { type: 'h2', text: 'Getting under the line' },
      { type: 'steps', items: [
        'Compress the PDF at a moderate setting first.',
        'Check the size and the readability at 100% zoom.',
        'If still over, step up the compression once.',
        'If still over, remove pages the recipient does not need — this is often the real answer.',
        'If still over, split into parts or send a link instead.',
      ] },
      { type: 'h2', text: 'Send less rather than compressing harder' },
      { type: 'p', text: 'People compress a 90-page pack into illegibility when the recipient asked for one section. Extracting the pages they need produces a small, readable file and a better answer to their question. It is worth asking yourself what they actually requested before you reach for a heavier setting.' },
      { type: 'h2', text: 'When compression is not enough' },
      { type: 'list', items: [
        'Share a cloud link — no size limit and the recipient always has the current version.',
        'Split into numbered parts, clearly labelled, and say how many there are.',
        'Send the section that was asked for rather than the whole pack.',
        'Ask whether they can accept a link; most people can, and most people prefer it.',
      ] },
      { type: 'h2', text: 'A note on confidential attachments' },
      { type: 'p', text: 'If the document is sensitive, compressing it in a tool that uploads means sending it to a third party in order to email it to one person. Browser-based compression avoids that entirely — the file never leaves your machine on the way to being made smaller.' },
    ],
    faqs: [
      { q: 'What size should a PDF be for email?', a: 'Under 10 MB is safe almost everywhere. Under 25 MB works for consumer mail but not for many corporate servers.' },
      { q: 'Why was my 24 MB attachment rejected by a 25 MB limit?', a: 'Encoding for transmission inflates attachments by roughly a third, and the limit applies after that.' },
      { q: 'Is a cloud link better than an attachment?', a: 'Usually — no size limit, and the recipient sees the current version. Attachments are better when the recipient must keep a fixed copy.' },
      { q: 'Can I zip a PDF to make it smaller?', a: 'Barely. A PDF is already compressed internally; zipping typically saves a percent or two and adds a step for the recipient.' },
    ],
    related: ['how-to-compress-a-pdf-without-losing-quality', 'how-to-split-a-pdf-by-file-size', 'extract-pages-from-pdf'],
  },

  {
    slug: 'how-to-compress-a-scanned-pdf',
    title: 'How to Compress a Scanned PDF',
    description: 'Scanned PDFs are the easiest kind to shrink — 80% reductions are normal. Here is how to get them without making the text unreadable.',
    keyword: 'compress scanned pdf',
    category: 'Compressing',
    published: '2026-04-06',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: 'Scanned documents are enormous and they compress beautifully. A 60 MB scan coming out at 4 MB with the text still perfectly crisp is an ordinary result, not a lucky one.' },
      { type: 'h2', text: 'Why the savings are so large' },
      { type: 'p', text: 'Scanners are set conservatively — 600 DPI, full colour, minimal compression — because they cannot know what the document will be used for. For a page of black text on white paper, almost all of that data is describing nothing. Colour information for a monochrome page, and resolution far beyond what any screen will show, are both pure overhead.' },
      { type: 'h2', text: 'Compress a scan' },
      { type: 'steps', items: [
        'Run OCR first if you want the document searchable — OCR reads the image better before it is degraded.',
        'Open the Compress PDF tool and add the file.',
        'Choose a moderate setting to start with.',
        'Check the smallest text on the busiest page at 100% zoom.',
        'Step up the compression if you need more and the text is still comfortable.',
      ] },
      { type: 'callout', title: 'OCR before compressing', text: 'Recognition accuracy depends on image quality. OCR the clean scan, then compress — the text layer is unaffected by image compression because it is text, not picture.' },
      { type: 'h2', text: 'How far you can push it' },
      { type: 'table', head: ['Target resolution', 'Result'], rows: [
        ['300 DPI', 'Print quality retained; modest savings'],
        ['200 DPI', 'Excellent on screen, fine for most printing'],
        ['150 DPI', 'Good on screen; small print starts to soften'],
        ['100 DPI', 'Body text readable, fine detail lost'],
        ['72 DPI', 'Too far for documents — noticeably degraded'],
      ] },
      { type: 'p', text: '150–200 DPI is the sweet spot for a document that will be read on screen and occasionally printed. It is where the file becomes manageable and nothing important disappears.' },
      { type: 'h2', text: 'Greyscale and black-and-white' },
      { type: 'p', text: 'Converting a colour scan of a black-and-white document to greyscale removes roughly two thirds of the data before any other compression is applied. Going further to pure black-and-white is smaller still, but it destroys signatures, stamps and anything faint — worth it for a clean printed form, risky for anything handwritten.' },
      { type: 'h2', text: 'Do it right at the scanner' },
      { type: 'p', text: 'The best compression is the data you never capture. Setting the scanner to 300 DPI greyscale for ordinary text produces files a fraction of the size with no meaningful loss, and saves you this step entirely.' },
    ],
    faqs: [
      { q: 'How small can a scanned PDF get?', a: 'Reductions of 70–90% are routine. A 60 MB scan at 4–8 MB with readable text is a normal outcome.' },
      { q: 'Will compression break my OCR text layer?', a: 'No. The text layer is text and survives image compression untouched — which is why OCR should come first.' },
      { q: 'Should I use black-and-white mode?', a: 'Only for clean printed documents. It destroys signatures, stamps and faint marks.' },
      { q: 'My scan barely compressed. Why?', a: 'It may already be at a low resolution, or it may have been compressed before. Compressing an already-compressed image costs quality and saves little.' },
    ],
    related: ['how-to-compress-a-pdf-without-losing-quality', 'how-to-make-a-scanned-pdf-searchable', 'why-is-my-pdf-so-large'],
  },

  {
    slug: 'how-to-reduce-pdf-file-size-to-100kb',
    title: 'How to Reduce a PDF to 100KB (Or Any Exact Size)',
    description: 'Upload forms that demand 100KB, 500KB or 2MB exactly. How to hit a hard target without ending up with a document nobody can read.',
    keyword: 'reduce pdf file size to 100kb',
    category: 'Compressing',
    published: '2026-04-19',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: 'Government portals, university applications and job sites frequently insist on limits that were set when broadband was new. 100KB for a scanned certificate is a demanding target, and hitting it needs a strategy rather than a slider.' },
      { type: 'h2', text: 'Work out whether it is achievable' },
      { type: 'p', text: 'Divide the target by the page count. 100KB over one page is tight but possible for a scan. 100KB over ten pages means 10KB a page, which for scanned images is not realistic at any readable quality.' },
      { type: 'p', text: 'If the maths says no, the answer is fewer pages, not more compression.' },
      { type: 'h2', text: 'The sequence that works' },
      { type: 'steps', items: [
        'Remove every page the form does not require. This is by far the largest single saving.',
        'Convert colour scans to greyscale — roughly a third of the data disappears.',
        'Compress at a moderate setting and check the size.',
        'Step the compression up gradually, checking readability at each step.',
        'If you are still over, reduce the resolution rather than the JPEG quality — downsampling degrades text more gracefully than heavy re-encoding.',
        'Verify the document is still legible at 100% zoom before uploading.',
      ] },
      { type: 'callout', title: 'One page, one photo, one target', text: 'For a single ID document, crop tightly to the document itself before converting. Cropping out the desk around it can halve the file before compression starts.' },
      { type: 'h2', text: 'Realistic targets' },
      { type: 'table', head: ['Content', 'Achievable at readable quality'], rows: [
        ['One page of text (not scanned)', 'Well under 100KB'],
        ['One scanned page, greyscale', '80–150KB'],
        ['One scanned page, colour', '150–400KB'],
        ['One photograph', '100–300KB'],
        ['Ten scanned pages', '800KB–2MB'],
      ] },
      { type: 'h2', text: 'If it will not go small enough' },
      { type: 'p', text: 'Rescan rather than recompress. A document scanned at 150 DPI greyscale from the start is dramatically smaller than the same document scanned at 600 DPI colour and then crushed — and it looks considerably better, because you are not compressing detail you captured only to destroy.' },
      { type: 'h2', text: 'Check before you submit' },
      { type: 'p', text: 'Open the finished file at 100% and read the smallest text on it — a reference number, a date of issue, a signature. Forms are rejected for illegibility as readily as for size, and a resubmission costs far more than the extra minute.' },
    ],
    faqs: [
      { q: 'Can any PDF be reduced to 100KB?', a: 'No. A ten-page colour scan cannot reach 100KB and stay readable. Reduce the page count or rescan at a lower setting.' },
      { q: 'Why does the form insist on such a small file?', a: 'Usually an old limit that nobody has revisited. It is rarely negotiable, so work within it.' },
      { q: 'Is it better to lower resolution or JPEG quality?', a: 'Lower the resolution. Text degrades more gracefully when downsampled than when heavily re-encoded.' },
      { q: 'How do I check the exact file size?', a: 'Your file manager shows it. Watch the units — some tools report MB where the form means MiB, which is a 5% difference at the boundary.' },
    ],
    related: ['how-to-compress-a-scanned-pdf', 'how-to-compress-pdf-for-email-attachment', 'how-to-compress-a-pdf-without-losing-quality'],
  },

  {
    slug: 'how-to-optimize-a-pdf-for-the-web',
    title: 'How to Optimize a PDF for the Web',
    description: 'Make a PDF that loads fast in a browser — linearisation, sensible image resolution, and the structural clean-up that matters for online documents.',
    keyword: 'optimize pdf for web',
    category: 'Compressing',
    published: '2026-05-02',
    tool: 'optimize-pdf',
    blocks: [
      { type: 'p', text: 'A PDF on a website has a different job from one attached to an email. It has to start rendering before it has finished downloading, and it has to do that on a phone connection.' },
      { type: 'h2', text: 'Optimise a PDF' },
      { type: 'steps', items: [
        'Open the Optimize PDF tool and add your file.',
        'Run it — the structure is cleaned up and the file is linearised for progressive loading.',
        'Compress separately if images are still making it heavy.',
      ] },
      { type: 'h2', text: 'What linearisation does' },
      { type: 'p', text: 'An ordinary PDF keeps its index at the end of the file, so a reader must download the whole thing before it can display anything. A linearised — "fast web view" — PDF puts the first page and a hint table at the front, so a browser can render page one while the rest is still arriving.' },
      { type: 'p', text: 'On a 30 MB report over a mobile connection, that is the difference between an instant first page and forty seconds of blank screen.' },
      { type: 'callout', title: 'Target 150 DPI for screen documents', text: 'Web PDFs are read on screens, where 150 DPI is indistinguishable from 300. Halving the resolution roughly quarters the image data, which is the biggest lever you have.' },
      { type: 'h2', text: 'The other structural wins' },
      { type: 'list', items: [
        'Subset fonts to the characters actually used, rather than embedding whole families.',
        'De-duplicate resources — the same logo stored once instead of on every page.',
        'Drop unused objects left behind by editing.',
        'Rewrite the file to discard incremental save history.',
        'Remove embedded attachments that do not need to be there.',
      ] },
      { type: 'h2', text: 'Also do these' },
      { type: 'table', head: ['Action', 'Why'], rows: [
        ['Set a document title', 'Browsers show it in the tab; search engines use it'],
        ['Give the file a descriptive name', 'The URL is a ranking and usability signal'],
        ['Check the metadata', 'Author and producer fields are published with the file'],
        ['Serve it with gzip', 'Helps the text portions, though images are already compressed'],
      ] },
      { type: 'h2', text: 'Consider whether it should be a PDF at all' },
      { type: 'p', text: 'PDFs on the web are worse than HTML pages for almost everything: they do not reflow on a phone, they are slower to load, they are harder for screen readers, and they rank less well. Publish as a page and offer the PDF as a download for people who want to print or file it.' },
    ],
    faqs: [
      { q: 'What is fast web view?', a: 'Another name for linearisation — the file is restructured so a browser can display page one before the download finishes.' },
      { q: 'What size should a web PDF be?', a: 'Under 5 MB where you can manage it. Above 10 MB, most mobile visitors give up.' },
      { q: 'Does optimising change how the document looks?', a: 'The structural clean-up does not. Reducing image resolution does, though at 150 DPI the difference on screen is not visible.' },
      { q: 'Do PDFs rank in search results?', a: 'Yes, they are indexed. An HTML page on the same content will normally outrank them.' },
    ],
    related: ['how-to-compress-a-pdf-without-losing-quality', 'why-is-my-pdf-so-large', 'how-to-flatten-a-pdf'],
  },
];
