import type { BlogPost } from '../types';

export const compressingPosts2: BlogPost[] = [

  {
    slug: 'how-to-flatten-a-pdf',
    title: 'How to Flatten a PDF (And When You Should)',
    description: 'Flattening merges form fields, annotations and layers into the page itself. Here is what it fixes, what it costs, and when to avoid it.',
    keyword: 'how to flatten a pdf',
    category: 'Compressing',
    published: '2026-05-30',
    tool: 'optimize-pdf',
    blocks: [
      { type: 'p', text: 'Flattening takes everything sitting on top of a PDF page — filled form fields, comments, highlights, stamps, layers — and bakes it into the page content itself.' },
      { type: 'h2', text: 'What flattening solves' },
      { type: 'list', items: [
        'Form data that shows on your screen but prints blank, or vanishes in another reader.',
        'Annotations that a recipient can drag around or delete.',
        'Layers that display differently depending on the viewer.',
        'Files bloated by a large annotation history.',
        'Documents that must look identical everywhere, with no interactive parts.',
      ] },
      { type: 'p', text: 'The classic case is a filled-in form: you complete it, send it, and the recipient sees an empty form. Flattening fixes that permanently, because the values become part of the page rather than the contents of a field.' },
      { type: 'h2', text: 'How to flatten' },
      { type: 'steps', items: [
        'Open the Optimize PDF tool and add your file.',
        'Run it with flattening enabled.',
        'Check that everything you expected to see is still visible on the page.',
        'Keep the unflattened original if the form might need editing again.',
      ] },
      { type: 'callout', title: 'Flattening is one-way', text: 'Once a field is drawn into the page it is no longer a field. There is no unflatten. Keep the editable version if there is any chance you will need to change an answer.' },
      { type: 'h2', text: 'What you give up' },
      { type: 'table', head: ['Before', 'After'], rows: [
        ['Editable form fields', 'Fixed text on the page'],
        ['Comments you can reply to', 'Marks drawn into the page'],
        ['Toggleable layers', 'Whatever was visible when you flattened'],
        ['Extractable form data', 'Nothing to extract'],
      ] },
      { type: 'h2', text: 'Flattening and redaction are not the same' },
      { type: 'p', text: 'This misunderstanding causes real leaks. Drawing a black rectangle over some text and flattening does merge the rectangle into the page — but the text underneath is still in the page content, and copy-paste retrieves it. Proper redaction removes the underlying content. If information must be unreadable, redact; do not flatten a box over it and hope.' },
      { type: 'h2', text: 'Does it reduce file size?' },
      { type: 'p', text: 'Sometimes substantially, if the document carried a lot of annotations or a large form definition. On a document with a few filled fields, the difference is negligible — flatten for reliability, not for size.' },
      { type: 'h2', text: 'When to flatten in a workflow' },
      { type: 'p', text: 'Flatten at the point the document stops being worked on and starts being distributed. Before that, the interactive parts are doing useful work — fields can be corrected, comments can be replied to. After it, they are a liability, because they can change or fail to render for someone else.' },
      { type: 'p', text: 'For a form you complete and return, flatten immediately before sending. For a document under review, flatten only when the review closes. Keeping an unflattened copy in both cases costs nothing and saves the re-do when something needs changing.' },
      { type: 'h2', text: 'Flattening a batch' },
      { type: 'p', text: 'Flattening applies the same treatment to every page, so it batches well — a folder of completed forms can be flattened in one pass. Check one output before running the rest, particularly if the forms came from different sources and may not all render their fields the same way.' },
    ],
    faqs: [
      { q: 'Can I unflatten a PDF?', a: 'No. Keep the original if you may need to edit it again.' },
      { q: 'Why does my filled form print blank?', a: 'Field appearances were not generated. Flattening draws the values into the page and fixes it everywhere.' },
      { q: 'Does flattening make redaction safe?', a: 'No. A flattened black box still has readable text beneath it. Use a redaction tool that removes the content.' },
      { q: 'Will flattening change how the document looks?', a: 'It should not. What was visible stays visible; it simply stops being interactive.' },
    ],
    related: ['how-to-redact-a-pdf-properly', 'how-to-fill-out-a-pdf-form', 'how-to-optimize-a-pdf-for-the-web'],
  },

  {
    slug: 'how-to-reduce-pdf-size-without-adobe',
    title: 'How to Reduce PDF Size Without Adobe Acrobat',
    description: 'Compress a PDF to a smaller size without Acrobat — set a target size in your browser, or use macOS, Windows or the command line. The trade-offs.',
    keyword: 'reduce pdf size without adobe',
    category: 'Compressing',
    published: '2026-06-27',
    updated: '2026-10-04',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: 'Acrobat is not required to compress a PDF, and for a one-off job it is the slowest option available — you have to install it and sign in before it will do anything. Below are four free ways to reduce PDF size without Adobe, starting with the quickest: compressing the PDF to a smaller size in your browser.' },
      { type: 'h2', text: 'Compress a PDF to a smaller size in the browser' },
      { type: 'p', text: 'To compress a PDF to a smaller size, open it in a browser-based compressor, enter the size the file has to fit under — in MB or KB — run the compression and download the result. Naming the limit you are up against is faster than guessing at a vague "medium" setting and checking whether it was enough.' },
      { type: 'steps', items: [
        'Open the Compress PDF tool and add your file — the original size is shown straight away. Nothing is uploaded.',
        'Enter a target size in MB or KB, or pick a quick preset: 50%, 25%, 10% or 5% of the original.',
        'Check the planned reduction and the quality warning, which gets stronger the further you push.',
        'Compress and download. If the target cannot be reached, the tool tells you the smallest size it managed.',
      ] },
      { type: 'p', text: 'The trade-off is memory: very large files are processed on your own machine, so a 300 MB scan will be slower than it would be on a server. For everything short of that, it is the quickest route there is, and it needs no install and no account.' },
      { type: 'h3', text: 'What happens to the file on the way down' },
      { type: 'p', text: 'The compressor tries a lossless pass first, which tidies the file\'s internal structure without touching what is on the page — if that alone reaches your target, text, links and quality are untouched. If it does not, the pages are re-rendered as images at progressively lower quality until the file fits. That last step is where the savings come from, and also where the cost is: the PDF becomes image-based, an invisible text layer keeps it searchable, but links and form fields do not survive and text loses its vector crispness.' },
      { type: 'callout', title: 'Aim for the largest target that still fits', text: 'Every file has a point of diminishing returns, and the further below it you push, the softer the pages get. If a portal accepts 5 MB, ask for 4.5 MB, not 1 MB. Targets below about 50 KB are refused outright — there is not enough room left for a legible page.' },
      { type: 'h3', text: 'Choosing the right target' },
      { type: 'list', items: [
        'Email: many services cap attachments at around 20–25 MB, and encoding adds overhead, so aim a few MB below the stated limit.',
        'Upload portals: use the limit printed on the form, minus a small margin. Job and government portals commonly sit between 2 and 10 MB.',
        'Reading on a phone: a few hundred KB opens almost instantly.',
      ] },
      { type: 'h3', text: 'Scans and text-only PDFs behave differently' },
      { type: 'p', text: 'Scanned PDFs are usually the biggest wins: every page is already a full-page image, often stored at far more resolution than a screen or office printer needs. A text-only PDF exported from Word is already small. The lossless pass may be all it needs — and forcing it far lower means rasterising crisp text, which makes the document worse for a few kilobytes.' },
      { type: 'h2', text: 'On macOS with Preview' },
      { type: 'steps', items: [
        'Open the PDF in Preview.',
        'File → Export.',
        'Set Quartz Filter to Reduce File Size.',
        'Save as a new file.',
      ] },
      { type: 'p', text: 'Free and built in, but the filter is aggressive and offers no settings — it frequently produces something noticeably worse than you wanted, with no way to ask for less.' },
      { type: 'h2', text: 'On Windows' },
      { type: 'p', text: 'There is no built-in compressor. Printing to the Microsoft Print to PDF driver re-renders the document and sometimes produces a smaller file, but it also flattens everything, drops links and can rasterise text. It is a last resort rather than a method.' },
      { type: 'h2', text: 'From the command line' },
      { type: 'p', text: 'Ghostscript gives you complete control and is the right answer for repeated or scripted work:' },
      { type: 'list', items: [
        'It exposes the actual downsampling resolutions rather than vague quality presets.',
        'It handles hundreds of files unattended.',
        'It runs entirely locally.',
        'It has a genuinely unfriendly syntax and takes an afternoon to learn.',
      ] },
      { type: 'callout', title: 'Choose by frequency', text: 'Doing this once: use a browser tool. Doing it every week: learn the command line. Installing a subscription desktop suite to compress one file is the option that makes least sense.' },
      { type: 'h2', text: 'What not to do' },
      { type: 'p', text: 'Do not print to PDF as a general compression method — it discards text, links and structure. Do not zip the file, which saves almost nothing. And do not upload a confidential document to an unknown compressor just to make it smaller; that is a large privacy cost for a small convenience.' },
    ],
    faqs: [
      { q: 'Can I compress a PDF to a specific size, like 5 MB?', a: 'Yes. Enter the target in MB or KB and the compressor works down to it. If the file cannot get that small, it tells you the smallest size it reached.' },
      { q: 'How small can I compress a PDF?', a: 'It depends on the content. Scans usually shrink a long way; text-only files have little to lose. Below about 50 KB there is not enough room for a legible page.' },
      { q: 'Does Windows have a built-in PDF compressor?', a: 'No. Print to PDF sometimes reduces size but degrades the document in the process.' },
      { q: 'Is Preview on Mac good enough?', a: 'It works and it is free. The compression is aggressive and unadjustable, so check the result.' },
      { q: 'Is a browser tool as good as Acrobat?', a: 'For ordinary compression, yes. Acrobat earns its price on preflight, colour management and prepress work, not on making files smaller.' },
      { q: 'What is the safest option for confidential files?', a: 'One that processes locally — a browser tool that does not upload, or a command-line tool on your own machine.' },
    ],
    related: ['how-to-compress-a-pdf-without-losing-quality', 'does-compressing-a-pdf-reduce-quality', 'how-to-compress-a-pdf-for-whatsapp', 'how-to-edit-a-pdf-without-adobe', 'is-it-safe-to-use-online-pdf-tools'],
  },
];
