import type { BlogPost } from '../types';

export const compressingPosts2: BlogPost[] = [
  {
    slug: 'how-to-compress-a-pdf-under-1mb',
    title: 'How to Get a PDF Under 1MB',
    description: 'A practical route to the 1MB mark — what to remove first, how far to compress, and when the target simply is not reachable.',
    keyword: 'compress pdf under 1mb',
    category: 'Compressing',
    published: '2026-05-16',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: '1MB is the most common hard limit on the web — application portals, ticketing systems, older content management systems. It is comfortably achievable for most documents and impossible for a few, and knowing which you have saves a lot of frustration.' },
      { type: 'h2', text: 'Is 1MB realistic for your file?' },
      { type: 'table', head: ['Document', 'Under 1MB?'], rows: [
        ['Text document, any length', 'Easily — often under 200KB already'],
        ['1–5 scanned pages, greyscale', 'Yes, with moderate compression'],
        ['10–20 scanned pages', 'Usually, at 150 DPI'],
        ['50+ scanned pages', 'Only by cutting pages'],
        ['Photo brochure', 'Only at quality nobody would accept'],
      ] },
      { type: 'h2', text: 'The order to try things' },
      { type: 'steps', items: [
        'Remove pages the recipient does not need. Nothing else saves as much.',
        'Convert colour scans to greyscale.',
        'Compress at a moderate setting and check the size.',
        'Increase compression a step at a time, checking readability as you go.',
        'Reduce the resolution to 150 DPI if you still need more.',
        'Stop and reconsider if the text is becoming hard to read — an illegible document under the limit is still a failure.',
      ] },
      { type: 'callout', title: 'Crop before you compress', text: 'Photographed documents usually include a margin of desk, hand or floor. Cropping to the page itself can halve the file before any compression, and it looks better too.' },
      { type: 'h2', text: 'What to do when you cannot get there' },
      { type: 'list', items: [
        'Split into parts if the system accepts multiple uploads.',
        'Rescan at 200 DPI greyscale rather than crushing a 600 DPI colour scan.',
        'Upload only the pages that were actually asked for.',
        'Ask whether a link is acceptable — surprisingly often it is.',
      ] },
      { type: 'h2', text: 'Check the units' },
      { type: 'p', text: 'Some systems mean 1,000,000 bytes and some mean 1,048,576. If your 1.0MB file is being rejected, aim for 950KB and the ambiguity stops mattering.' },
      { type: 'h2', text: 'Where the size actually is' },
      { type: 'p', text: 'Before compressing, work out what is heavy. Try to select text: if you cannot, the document is scanned images and compression will do most of the work for you. If you can, and it is still large, look for photographs — a single high-resolution image can account for most of a file, and replacing it with a smaller version beats compressing the whole document.' },
      { type: 'p', text: 'A repeated background, such as a scanned letterhead placed on every page, is the other common culprit. It compresses well but the real fix is removing the repetition.' },
      { type: 'h2', text: 'Getting it right at capture' },
      { type: 'p', text: 'If you are producing the document rather than receiving it, capture at the size you need. A page scanned at 200 DPI greyscale arrives under the limit without any compression at all, and it looks better than the same page scanned at 600 DPI colour and then crushed to fit.' },
    ],
    faqs: [
      { q: 'What is the fastest way to get under 1MB?', a: 'Remove pages that are not needed, then compress. Page count is the biggest single factor in a scanned document.' },
      { q: 'Will my scan still be readable at 1MB?', a: 'For a handful of pages, yes. Across fifty pages you are down to 20KB a page, which is not enough for legible scanned text.' },
      { q: 'Does zipping help?', a: 'Almost never. PDFs are already compressed internally.' },
      { q: 'My file says 1.0MB and is still rejected. Why?', a: 'Rounding, or a difference between MB and MiB. Target 950KB.' },
    ],
    related: ['how-to-reduce-pdf-file-size-to-100kb', 'how-to-compress-a-scanned-pdf', 'how-to-compress-a-pdf-without-losing-quality'],
  },

  {
    slug: 'how-to-flatten-a-pdf',
    title: 'How to Flatten a PDF (And When You Should)',
    description: 'Flattening merges form fields, annotations and layers into the page itself. Here is what it fixes, what it costs, and when to avoid it.',
    keyword: 'how to flatten a pdf',
    category: 'Compressing',
    published: '2026-05-30',
    tool: 'optimize-pdf',
    blocks: [
      { type: 'p', text: 'Flattening takes everything sitting on top of a PDF page — filled form fields, comments, highlights, stamps, layers — and bakes it into the page content itself.' },
      { type: 'h2', text: 'What flattening solves' },
      { type: 'list', items: [
        'Form data that shows on your screen but prints blank, or vanishes in another reader.',
        'Annotations that a recipient can drag around or delete.',
        'Layers that display differently depending on the viewer.',
        'Files bloated by a large annotation history.',
        'Documents that must look identical everywhere, with no interactive parts.',
      ] },
      { type: 'p', text: 'The classic case is a filled-in form: you complete it, send it, and the recipient sees an empty form. Flattening fixes that permanently, because the values become part of the page rather than the contents of a field.' },
      { type: 'h2', text: 'How to flatten' },
      { type: 'steps', items: [
        'Open the Optimize PDF tool and add your file.',
        'Run it with flattening enabled.',
        'Check that everything you expected to see is still visible on the page.',
        'Keep the unflattened original if the form might need editing again.',
      ] },
      { type: 'callout', title: 'Flattening is one-way', text: 'Once a field is drawn into the page it is no longer a field. There is no unflatten. Keep the editable version if there is any chance you will need to change an answer.' },
      { type: 'h2', text: 'What you give up' },
      { type: 'table', head: ['Before', 'After'], rows: [
        ['Editable form fields', 'Fixed text on the page'],
        ['Comments you can reply to', 'Marks drawn into the page'],
        ['Toggleable layers', 'Whatever was visible when you flattened'],
        ['Extractable form data', 'Nothing to extract'],
      ] },
      { type: 'h2', text: 'Flattening and redaction are not the same' },
      { type: 'p', text: 'This misunderstanding causes real leaks. Drawing a black rectangle over some text and flattening does merge the rectangle into the page — but the text underneath is still in the page content, and copy-paste retrieves it. Proper redaction removes the underlying content. If information must be unreadable, redact; do not flatten a box over it and hope.' },
      { type: 'h2', text: 'Does it reduce file size?' },
      { type: 'p', text: 'Sometimes substantially, if the document carried a lot of annotations or a large form definition. On a document with a few filled fields, the difference is negligible — flatten for reliability, not for size.' },
      { type: 'h2', text: 'When to flatten in a workflow' },
      { type: 'p', text: 'Flatten at the point the document stops being worked on and starts being distributed. Before that, the interactive parts are doing useful work — fields can be corrected, comments can be replied to. After it, they are a liability, because they can change or fail to render for someone else.' },
      { type: 'p', text: 'For a form you complete and return, flatten immediately before sending. For a document under review, flatten only when the review closes. Keeping an unflattened copy in both cases costs nothing and saves the re-do when something needs changing.' },
      { type: 'h2', text: 'Flattening a batch' },
      { type: 'p', text: 'Flattening applies the same treatment to every page, so it batches well — a folder of completed forms can be flattened in one pass. Check one output before running the rest, particularly if the forms came from different sources and may not all render their fields the same way.' },
    ],
    faqs: [
      { q: 'Can I unflatten a PDF?', a: 'No. Keep the original if you may need to edit it again.' },
      { q: 'Why does my filled form print blank?', a: 'Field appearances were not generated. Flattening draws the values into the page and fixes it everywhere.' },
      { q: 'Does flattening make redaction safe?', a: 'No. A flattened black box still has readable text beneath it. Use a redaction tool that removes the content.' },
      { q: 'Will flattening change how the document looks?', a: 'It should not. What was visible stays visible; it simply stops being interactive.' },
    ],
    related: ['how-to-redact-a-pdf-properly', 'how-to-fill-out-a-pdf-form', 'how-to-optimize-a-pdf-for-the-web'],
  },

  {
    slug: 'pdf-file-size-limits-explained',
    title: 'PDF File Size Limits: What They Are and How to Work Within Them',
    description: 'Email caps, upload forms, portals and messaging apps all impose different limits. Here they are in one place, with the sizes to actually target.',
    keyword: 'pdf file size limit',
    category: 'Compressing',
    published: '2026-06-13',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: 'PDF itself has no meaningful size limit. Every limit you hit was set by something else — a mail server, an upload form, a messaging app — and each one is different.' },
      { type: 'h2', text: 'The limits you will meet' },
      { type: 'table', head: ['Where', 'Limit', 'What to target'], rows: [
        ['Gmail, Outlook.com, Yahoo', '20–25 MB', 'Under 15 MB'],
        ['Corporate mail servers', 'Often 10 MB', 'Under 8 MB'],
        ['Government and legal portals', '2–10 MB', 'Whatever they state, minus 20%'],
        ['Job application sites', '1–5 MB', 'Under 1 MB where possible'],
        ['WhatsApp', '100 MB', 'Rarely an issue'],
        ['Contact forms', '1–2 MB', 'Under 1 MB'],
      ] },
      { type: 'callout', title: 'The receiving limit is the one that counts', text: 'Your provider may accept 25 MB and the recipient\'s server may reject anything over 10. You cannot see their limit, and the bounce comes back after you thought it had sent. Under 10 MB is the number that works nearly everywhere.' },
      { type: 'h2', text: 'Why attachments are bigger than the file' },
      { type: 'p', text: 'Email cannot carry raw binary data, so attachments are encoded in a text-safe format that inflates them by roughly a third. A 20 MB PDF becomes about 27 MB in transit, and the limit applies to the encoded size. This is why a file comfortably under the stated cap is sometimes rejected.' },
      { type: 'h2', text: 'Reasonable sizes by document type' },
      { type: 'list', items: [
        'Text document: 100KB to 2 MB — anything larger deserves investigation.',
        'Report with images: 2–10 MB.',
        'Scanned document, compressed: 100–300KB per page.',
        'Scanned document, uncompressed: 1–5 MB per page.',
        'Photo brochure: 5–50 MB.',
      ] },
      { type: 'p', text: 'If your file is far outside its bracket, something specific is wrong — usually an oversized image or an uncompressed scan — and it is worth finding out what.' },
      { type: 'h2', text: 'Working within a limit' },
      { type: 'steps', items: [
        'Compress the file.',
        'Remove pages nobody asked for.',
        'Split into parts if the system accepts several uploads.',
        'Send a link instead, when the recipient can accept one.',
      ] },
      { type: 'h2', text: 'Why the limits exist at all' },
      { type: 'p', text: 'Mail servers cap attachments because every message is stored, replicated and backed up, sometimes for every recipient. Upload forms cap files because the receiving system has to hold and scan them. Neither limit is arbitrary, and neither is usually negotiable by the person you are emailing.' },
      { type: 'p', text: 'They also tend to be older than the documents they now receive. A 2 MB cap set when a document meant a few pages of text now meets a phone photograph of a passport, and the limit has not moved.' },
      { type: 'h2', text: 'A sensible default' },
      { type: 'p', text: 'If you do not know the recipient\'s limit, aim for under 10 MB and you will clear almost everything. For upload forms, read the stated limit and target 20% below it — rounding, encoding and the difference between MB and MiB all sit in that margin.' },
    ],
    faqs: [
      { q: 'Is there a maximum PDF size?', a: 'Not practically. The format allows enormous files; the limits come from whatever is transporting or accepting them.' },
      { q: 'What is a safe size for email?', a: 'Under 10 MB. It clears both consumer and most corporate limits.' },
      { q: 'Why do limits vary so much?', a: 'Each system sets its own, often years ago, and rarely revisits them.' },
      { q: 'Does compressing affect quality?', a: 'The structural part does not. The image part does, though usually invisibly on scanned text.' },
    ],
    related: ['how-to-compress-pdf-for-email-attachment', 'how-to-compress-a-pdf-under-1mb', 'why-is-my-pdf-so-large'],
  },

  {
    slug: 'how-to-reduce-pdf-size-without-adobe',
    title: 'How to Reduce PDF Size Without Adobe Acrobat',
    description: 'Compress a PDF without a subscription — in your browser, on macOS, on Windows, or from the command line. Four routes, with the trade-offs.',
    keyword: 'reduce pdf size without adobe',
    category: 'Compressing',
    published: '2026-06-27',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: 'Acrobat is not required to compress a PDF, and for a one-off job it is the slowest option available — you have to install it and sign in before it will do anything.' },
      { type: 'h2', text: 'In the browser' },
      { type: 'p', text: 'A browser-based compressor needs no install and no account, and one that works locally never uploads your document. Open it, add the file, choose a level, download the result.' },
      { type: 'p', text: 'The trade-off is memory: very large files are processed on your own machine, so a 300 MB scan will be slower than it would be on a server. For everything short of that, it is the quickest route there is.' },
      { type: 'h2', text: 'On macOS with Preview' },
      { type: 'steps', items: [
        'Open the PDF in Preview.',
        'File → Export.',
        'Set Quartz Filter to Reduce File Size.',
        'Save as a new file.',
      ] },
      { type: 'p', text: 'Free and built in, but the filter is aggressive and offers no settings — it frequently produces something noticeably worse than you wanted, with no way to ask for less.' },
      { type: 'h2', text: 'On Windows' },
      { type: 'p', text: 'There is no built-in compressor. Printing to the Microsoft Print to PDF driver re-renders the document and sometimes produces a smaller file, but it also flattens everything, drops links and can rasterise text. It is a last resort rather than a method.' },
      { type: 'h2', text: 'From the command line' },
      { type: 'p', text: 'Ghostscript gives you complete control and is the right answer for repeated or scripted work:' },
      { type: 'list', items: [
        'It exposes the actual downsampling resolutions rather than vague quality presets.',
        'It handles hundreds of files unattended.',
        'It runs entirely locally.',
        'It has a genuinely unfriendly syntax and takes an afternoon to learn.',
      ] },
      { type: 'callout', title: 'Choose by frequency', text: 'Doing this once: use a browser tool. Doing it every week: learn the command line. Installing a subscription desktop suite to compress one file is the option that makes least sense.' },
      { type: 'h2', text: 'What not to do' },
      { type: 'p', text: 'Do not print to PDF as a general compression method — it discards text, links and structure. Do not zip the file, which saves almost nothing. And do not upload a confidential document to an unknown compressor just to make it smaller; that is a large privacy cost for a small convenience.' },
    ],
    faqs: [
      { q: 'Does Windows have a built-in PDF compressor?', a: 'No. Print to PDF sometimes reduces size but degrades the document in the process.' },
      { q: 'Is Preview on Mac good enough?', a: 'It works and it is free. The compression is aggressive and unadjustable, so check the result.' },
      { q: 'Is a browser tool as good as Acrobat?', a: 'For ordinary compression, yes. Acrobat earns its price on preflight, colour management and prepress work, not on making files smaller.' },
      { q: 'What is the safest option for confidential files?', a: 'One that processes locally — a browser tool that does not upload, or a command-line tool on your own machine.' },
    ],
    related: ['how-to-compress-a-pdf-without-losing-quality', 'how-to-edit-a-pdf-without-adobe', 'is-it-safe-to-use-online-pdf-tools'],
  },
];
