import type { BlogPost } from '../types';

export const compressingPosts2: BlogPost[] = [

  {
    slug: 'how-to-flatten-a-pdf',
    title: 'How to Flatten a PDF (And When You Should)',
    description: 'Flattening merges form fields, annotations and layers into the page itself. Here is what it fixes, what it costs, and when to avoid it.',
    keyword: 'how to flatten a pdf',
    category: 'Compressing',
    published: '2026-05-30',
    tool: 'optimize-pdf',
    blocks: [
      { type: 'p', text: 'Flattening takes everything sitting on top of a PDF page — filled form fields, comments, highlights, stamps, layers — and bakes it into the page content itself.' },
      { type: 'h2', text: 'What flattening solves' },
      { type: 'list', items: [
        'Form data that shows on your screen but prints blank, or vanishes in another reader.',
        'Annotations that a recipient can drag around or delete.',
        'Layers that display differently depending on the viewer.',
        'Files bloated by a large annotation history.',
        'Documents that must look identical everywhere, with no interactive parts.',
      ] },
      { type: 'p', text: 'The classic case is a filled-in form: you complete it, send it, and the recipient sees an empty form. Flattening fixes that permanently, because the values become part of the page rather than the contents of a field.' },
      { type: 'h2', text: 'How to flatten' },
      { type: 'steps', items: [
        'Open the Optimize PDF tool and add your file.',
        'Run it with flattening enabled.',
        'Check that everything you expected to see is still visible on the page.',
        'Keep the unflattened original if the form might need editing again.',
      ] },
      { type: 'callout', title: 'Flattening is one-way', text: 'Once a field is drawn into the page it is no longer a field. There is no unflatten. Keep the editable version if there is any chance you will need to change an answer.' },
      { type: 'h2', text: 'What you give up' },
      { type: 'table', head: ['Before', 'After'], rows: [
        ['Editable form fields', 'Fixed text on the page'],
        ['Comments you can reply to', 'Marks drawn into the page'],
        ['Toggleable layers', 'Whatever was visible when you flattened'],
        ['Extractable form data', 'Nothing to extract'],
      ] },
      { type: 'h2', text: 'Flattening and redaction are not the same' },
      { type: 'p', text: 'This misunderstanding causes real leaks. Drawing a black rectangle over some text and flattening does merge the rectangle into the page — but the text underneath is still in the page content, and copy-paste retrieves it. Proper redaction removes the underlying content. If information must be unreadable, redact; do not flatten a box over it and hope.' },
      { type: 'h2', text: 'Does it reduce file size?' },
      { type: 'p', text: 'Sometimes substantially, if the document carried a lot of annotations or a large form definition. On a document with a few filled fields, the difference is negligible — flatten for reliability, not for size.' },
      { type: 'h2', text: 'When to flatten in a workflow' },
      { type: 'p', text: 'Flatten at the point the document stops being worked on and starts being distributed. Before that, the interactive parts are doing useful work — fields can be corrected, comments can be replied to. After it, they are a liability, because they can change or fail to render for someone else.' },
      { type: 'p', text: 'For a form you complete and return, flatten immediately before sending. For a document under review, flatten only when the review closes. Keeping an unflattened copy in both cases costs nothing and saves the re-do when something needs changing.' },
      { type: 'h2', text: 'Flattening a batch' },
      { type: 'p', text: 'Flattening applies the same treatment to every page, so it batches well — a folder of completed forms can be flattened in one pass. Check one output before running the rest, particularly if the forms came from different sources and may not all render their fields the same way.' },
    ],
    faqs: [
      { q: 'Can I unflatten a PDF?', a: 'No. Keep the original if you may need to edit it again.' },
      { q: 'Why does my filled form print blank?', a: 'Field appearances were not generated. Flattening draws the values into the page and fixes it everywhere.' },
      { q: 'Does flattening make redaction safe?', a: 'No. A flattened black box still has readable text beneath it. Use a redaction tool that removes the content.' },
      { q: 'Will flattening change how the document looks?', a: 'It should not. What was visible stays visible; it simply stops being interactive.' },
    ],
    related: ['how-to-redact-a-pdf-properly', 'how-to-fill-out-a-pdf-form', 'how-to-optimize-a-pdf-for-the-web'],
  },

  {
    slug: 'how-to-reduce-pdf-size-without-adobe',
    title: 'How to Reduce PDF Size Without Adobe Acrobat',
    description: 'Compress a PDF without a subscription — in your browser, on macOS, on Windows, or from the command line. Four routes, with the trade-offs.',
    keyword: 'reduce pdf size without adobe',
    category: 'Compressing',
    published: '2026-06-27',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: 'Acrobat is not required to compress a PDF, and for a one-off job it is the slowest option available — you have to install it and sign in before it will do anything.' },
      { type: 'h2', text: 'In the browser' },
      { type: 'p', text: 'A browser-based compressor needs no install and no account, and one that works locally never uploads your document. Open it, add the file, choose a level, download the result.' },
      { type: 'p', text: 'The trade-off is memory: very large files are processed on your own machine, so a 300 MB scan will be slower than it would be on a server. For everything short of that, it is the quickest route there is.' },
      { type: 'h2', text: 'On macOS with Preview' },
      { type: 'steps', items: [
        'Open the PDF in Preview.',
        'File → Export.',
        'Set Quartz Filter to Reduce File Size.',
        'Save as a new file.',
      ] },
      { type: 'p', text: 'Free and built in, but the filter is aggressive and offers no settings — it frequently produces something noticeably worse than you wanted, with no way to ask for less.' },
      { type: 'h2', text: 'On Windows' },
      { type: 'p', text: 'There is no built-in compressor. Printing to the Microsoft Print to PDF driver re-renders the document and sometimes produces a smaller file, but it also flattens everything, drops links and can rasterise text. It is a last resort rather than a method.' },
      { type: 'h2', text: 'From the command line' },
      { type: 'p', text: 'Ghostscript gives you complete control and is the right answer for repeated or scripted work:' },
      { type: 'list', items: [
        'It exposes the actual downsampling resolutions rather than vague quality presets.',
        'It handles hundreds of files unattended.',
        'It runs entirely locally.',
        'It has a genuinely unfriendly syntax and takes an afternoon to learn.',
      ] },
      { type: 'callout', title: 'Choose by frequency', text: 'Doing this once: use a browser tool. Doing it every week: learn the command line. Installing a subscription desktop suite to compress one file is the option that makes least sense.' },
      { type: 'h2', text: 'What not to do' },
      { type: 'p', text: 'Do not print to PDF as a general compression method — it discards text, links and structure. Do not zip the file, which saves almost nothing. And do not upload a confidential document to an unknown compressor just to make it smaller; that is a large privacy cost for a small convenience.' },
    ],
    faqs: [
      { q: 'Does Windows have a built-in PDF compressor?', a: 'No. Print to PDF sometimes reduces size but degrades the document in the process.' },
      { q: 'Is Preview on Mac good enough?', a: 'It works and it is free. The compression is aggressive and unadjustable, so check the result.' },
      { q: 'Is a browser tool as good as Acrobat?', a: 'For ordinary compression, yes. Acrobat earns its price on preflight, colour management and prepress work, not on making files smaller.' },
      { q: 'What is the safest option for confidential files?', a: 'One that processes locally — a browser tool that does not upload, or a command-line tool on your own machine.' },
    ],
    related: ['how-to-compress-a-pdf-without-losing-quality', 'how-to-edit-a-pdf-without-adobe', 'is-it-safe-to-use-online-pdf-tools'],
  },
];
