import type { BlogPost } from '../types';

export const convertingFromPdfPosts: BlogPost[] = [
  {
    slug: 'how-to-convert-pdf-to-word-without-losing-formatting',
    title: 'How to Convert PDF to Word Without Losing Formatting',
    description: 'Turn a PDF into an editable DOCX and understand what survives the trip. Which PDFs convert cleanly, which do not, and how to get the best result.',
    keyword: 'convert pdf to word without losing formatting',
    category: 'Converting',
    published: '2026-03-04',
    updated: '2026-08-08',
    tool: 'pdf-to-word',
    blocks: [
      { type: 'p', text: 'Converting PDF to Word is not really a conversion — it is a reconstruction. Understanding why explains everything about what you get back, and stops you expecting something no tool can deliver.' },
      { type: 'h2', text: 'Convert a PDF to Word' },
      { type: 'steps', items: [
        'Open the PDF to Word tool and add your file.',
        'Convert. The text and structure are read out and rebuilt as a .docx.',
        'Open the result in Word and check headings, lists and tables before you start editing.',
      ] },
      { type: 'h2', text: 'Why the result is an approximation' },
      { type: 'p', text: 'A Word document stores meaning: this is a Heading 2, this is a bulleted list, this paragraph is justified. A PDF stores geometry: draw this glyph at this coordinate in this font at this size. The paragraph structure was used to compute those coordinates and then discarded.' },
      { type: 'p', text: 'Converting back means inferring the structure from the positions — deciding that large bold text at the top of a block was probably a heading, that lines starting with a bullet character are probably a list, that text arranged in a grid is probably a table. Good tools infer well. Nothing recovers information the file does not contain.' },
      { type: 'h2', text: 'What usually converts well' },
      { type: 'table', head: ['Content', 'Typical result'], rows: [
        ['Body text and paragraphs', 'Very good — this is the strong case'],
        ['Headings', 'Usually detected from size and weight'],
        ['Simple bulleted and numbered lists', 'Usually preserved'],
        ['Plain tables with ruled lines', 'Often reconstructed as real tables'],
        ['Multi-column layouts', 'Mixed — columns can interleave'],
        ['Text wrapped around images', 'Rarely preserved'],
        ['Complex tables with merged cells', 'Frequently flattened into a grid of text'],
        ['Scanned pages', 'Nothing at all without OCR first'],
      ] },
      { type: 'callout', title: 'Scanned PDFs need OCR first', text: 'If the pages are images, there is no text to extract and you will get a document of pictures. Run OCR before converting, and the recognised text becomes editable.' },
      { type: 'h2', text: 'Getting a better result' },
      { type: 'list', items: [
        'Convert the whole document rather than page ranges, so structure detection has full context.',
        'Extract only the section you need if you only intend to edit part of it — less to clean up.',
        'Expect to fix headings and spacing; budget a few minutes rather than assuming none.',
        'Apply Word\'s own styles to the converted headings so the document behaves properly from then on.',
      ] },
      { type: 'h2', text: 'When you should not convert' },
      { type: 'p', text: 'If you only need to add a signature, fill a form, black out a paragraph or drop a page, do that to the PDF directly. Round-tripping through Word to make a small change costs you the layout and gains you nothing.' },
      { type: 'p', text: 'And if the original Word document still exists somewhere, edit that. A reconstruction is never better than the file it was reconstructed from.' },
    ],
    faqs: [
      { q: 'Will my PDF convert to Word perfectly?', a: 'Simple text documents convert very well. Anything with a designed layout — columns, wrapped images, complex tables — comes back as a close approximation that needs tidying.' },
      { q: 'Why is my converted Word file full of text boxes?', a: 'Some converters position each block absolutely to preserve appearance. It looks right and edits terribly. A converter that produces flowing paragraphs is more useful even if it matches the original slightly less exactly.' },
      { q: 'Can I convert a scanned PDF to Word?', a: 'Only after OCR. Without it, the pages are images and there is no text to extract.' },
      { q: 'Do images come across?', a: 'Yes, images are extracted and placed. Their exact position relative to the text is the part that commonly shifts.' },
    ],
    related: ['how-to-convert-word-to-pdf-without-losing-formatting', 'how-to-convert-a-pdf-into-editable-text', 'how-to-make-a-scanned-pdf-searchable'],
  },

  {
    slug: 'how-to-convert-pdf-to-excel-with-tables',
    title: 'How to Convert PDF to Excel and Keep the Table Structure',
    description: 'Get tables out of a PDF and into real spreadsheet cells. What makes a table convert cleanly, and how to fix the ones that do not.',
    keyword: 'convert pdf to excel with tables',
    category: 'Converting',
    published: '2026-03-26',
    tool: 'pdf-to-excel',
    blocks: [
      { type: 'p', text: 'The reason this is hard is that a PDF has no idea it contains a table. It contains text at coordinates. The table you can see is a pattern your eye assembles from alignment and ruled lines — and the converter has to assemble the same pattern from the same clues.' },
      { type: 'h2', text: 'Convert a PDF table to a spreadsheet' },
      { type: 'steps', items: [
        'Open the PDF to Excel tool and add your file.',
        'Convert. Text is grouped into rows and columns by position and by any ruled lines present.',
        'Open the workbook and check the column boundaries before you rely on any of it.',
      ] },
      { type: 'h2', text: 'What makes a table convert well' },
      { type: 'table', head: ['Feature', 'Effect on accuracy'], rows: [
        ['Ruled lines around every cell', 'Best case — the boundaries are explicit'],
        ['Consistent column alignment', 'Good — columns can be inferred from spacing'],
        ['One line of text per cell', 'Good — row boundaries are unambiguous'],
        ['Wrapped text inside cells', 'Harder — one row can look like several'],
        ['Merged or spanning cells', 'Hard — the grid is no longer regular'],
        ['No lines and irregular spacing', 'Poor — column edges have to be guessed'],
        ['Scanned table without OCR', 'Impossible — there is no text to read'],
      ] },
      { type: 'callout', title: 'Check the numbers, not the layout', text: 'The dangerous failure is not a table that looks wrong — you will spot that. It is a column boundary landing one character off, so 1,234.56 becomes 1 and 234.56 in adjacent cells. Total a column in the spreadsheet and compare it against the PDF before you use the data.' },
      { type: 'h2', text: 'Fixing what comes back' },
      { type: 'list', items: [
        'Use Text to Columns when several values have landed in one cell.',
        'Check for numbers stored as text — they will not sum, and Excel flags them with a green corner.',
        'Watch for currency symbols and thousands separators pulled into the value.',
        'Re-join rows that were split because a cell wrapped onto a second line.',
        'Check dates, which are the most commonly mangled field of all.',
      ] },
      { type: 'h2', text: 'If the source data still exists, ask for it' },
      { type: 'p', text: 'A PDF is a printout. Someone generated it from a spreadsheet, a database or a report tool, and that source is authoritative in a way that any extraction is not. For a one-off table, converting is quicker than asking. For anything recurring or financially material, asking for a CSV is worth the email.' },
      { type: 'h2', text: 'Scanned tables' },
      { type: 'p', text: 'Run OCR first, then convert. Recognition will be imperfect on faint scans, and columns of digits are exactly where an OCR error is hardest to spot — a 6 read as an 8 looks entirely plausible. Verify totals against the original page.' },
    ],
    faqs: [
      { q: 'Why did my columns merge into one?', a: 'The spacing between them was not wide enough to be read as a boundary. Fix it with Text to Columns in the spreadsheet.' },
      { q: 'Can I convert a scanned table?', a: 'Only after OCR, and you should check the figures carefully — digit recognition errors are easy to miss.' },
      { q: 'Why are my numbers stored as text?', a: 'Extra characters came across with them — a currency symbol, a space, a non-breaking space. Clean the column and Excel will treat the values as numbers.' },
      { q: 'What about tables that span several pages?', a: 'Each page is usually converted separately, and repeated headers appear again mid-data. Delete the duplicate header rows after converting.' },
    ],
    related: ['how-to-export-pdf-tables-to-csv', 'how-to-convert-excel-to-pdf-without-cutting-off-columns', 'how-to-make-a-scanned-pdf-searchable'],
  },

  {
    slug: 'how-to-convert-pdf-to-powerpoint',
    title: 'How to Convert a PDF to PowerPoint Slides',
    description: 'Turn a PDF back into editable slides — what gets rebuilt, what does not, and how to prepare a document so the conversion produces usable slides.',
    keyword: 'how to convert pdf to powerpoint',
    category: 'Converting',
    published: '2026-04-10',
    tool: 'pdf-to-powerpoint',
    blocks: [
      { type: 'p', text: 'This comes up when the deck is gone and only the PDF remains: someone sent a printout, the original is on a laptop nobody has, and you need to change one number before a meeting.' },
      { type: 'h2', text: 'Convert a PDF into slides' },
      { type: 'steps', items: [
        'Open the PDF to PowerPoint tool and add your file.',
        'Convert. The text on each page is read and rebuilt as editable slide content.',
        'Open the .pptx and check the slides against the PDF before presenting from it.',
      ] },
      { type: 'h2', text: 'What comes back' },
      { type: 'p', text: 'Text is the part that reconstructs well. Headings are detected from size and position, body text is grouped into blocks, and bullet lists usually survive as lists. You get slides you can actually edit, rather than pictures of slides.' },
      { type: 'p', text: 'What does not come back is everything that was never in the PDF: animations, transitions, speaker notes, the slide master, theme colours and layout placeholders. Those live in the PPTX and were discarded when it was exported.' },
      { type: 'callout', title: 'The other kind of conversion', text: 'Some tools produce a deck where each slide is a full-page image of the PDF page. It looks perfect and cannot be edited at all — which defeats the purpose. If you cannot click into the text and type, you have that kind.' },
      { type: 'h2', text: 'Documents versus decks' },
      { type: 'p', text: 'The tool works best on a PDF that was a deck: one idea per page, short lines, generous spacing. Feeding it a dense report produces slides with far too much text on them, because that is faithfully what the page contained.' },
      { type: 'p', text: 'If the source is a report and you want a presentation, converting is the wrong first move. Decide what the slides should say, then build them — the conversion can supply the raw text, not the editorial judgement.' },
      { type: 'h2', text: 'Cleaning up afterwards' },
      { type: 'list', items: [
        'Apply your theme so the slides pick up the right fonts and colours.',
        'Re-align the text blocks to the layout placeholders instead of leaving them floating.',
        'Split any slide that came back overloaded.',
        'Re-add the animation the original had, if it mattered.',
        'Check headings did not import as body text with manual formatting.',
      ] },
    ],
    faqs: [
      { q: 'Can I edit the text after converting?', a: 'Yes — that is the point of a structural conversion. If the text is not editable, your tool produced image slides instead.' },
      { q: 'Do animations come back?', a: 'No. They were never in the PDF and cannot be recovered.' },
      { q: 'Will each PDF page become one slide?', a: 'Yes, one page to one slide, in order.' },
      { q: 'Why do my slides have too much text?', a: 'Because the PDF pages did. The conversion is faithful; the editing is yours to do.' },
    ],
    related: ['how-to-convert-powerpoint-to-pdf', 'how-to-convert-pdf-to-word-without-losing-formatting', 'how-to-summarize-a-long-pdf'],
  },

  {
    slug: 'how-to-convert-pdf-to-jpg-high-quality',
    title: 'How to Convert PDF to JPG in High Quality',
    description: 'Turn PDF pages into images at the resolution you actually need — for print, for the web, or for a thumbnail. Including the DPI maths.',
    keyword: 'convert pdf to jpg high quality',
    category: 'Converting',
    published: '2026-04-24',
    tool: 'pdf-to-jpg',
    blocks: [
      { type: 'p', text: 'Turning a PDF page into an image means choosing a resolution, because a PDF page has no pixels — it is a set of drawing instructions that can be rendered at any size. Get the resolution wrong and you have either a blurry image or a 40 MB one.' },
      { type: 'h2', text: 'Convert pages to images' },
      { type: 'steps', items: [
        'Open the PDF to JPG tool and add your file.',
        'Choose the resolution — this is the decision that matters.',
        'Convert. Every page becomes an image, delivered as a ZIP when there are several.',
      ] },
      { type: 'h2', text: 'Choosing a resolution' },
      { type: 'table', head: ['Use', 'DPI', 'A4 page becomes'], rows: [
        ['Web page or email', '96–150', 'about 800 × 1100 to 1240 × 1750'],
        ['On-screen reading, retina displays', '200', 'about 1650 × 2340'],
        ['Printing', '300', 'about 2480 × 3500'],
        ['Archival or large-format print', '600', 'about 4960 × 7000'],
      ] },
      { type: 'p', text: 'The rule of thumb: 150 DPI for screens, 300 DPI for anything that will be printed. Above 300 the file size climbs quickly and the improvement is invisible unless the output is genuinely large.' },
      { type: 'callout', title: 'JPG or PNG?', text: 'JPG for pages that are mostly photographs. PNG for pages that are mostly text, diagrams or screenshots — JPEG compression puts grey fringes around sharp black-on-white edges, which is exactly what a text page is made of.' },
      { type: 'h2', text: 'Why your converted pages look blurry' },
      { type: 'list', items: [
        'The resolution was too low. Convert again at 300 DPI.',
        'The image was enlarged after conversion — scaling up cannot invent detail.',
        'The PDF was itself a low-resolution scan, so there was never any detail to render.',
        'Heavy JPEG compression was applied on export.',
      ] },
      { type: 'h2', text: 'What you give up' },
      { type: 'p', text: 'Converting a page to an image destroys everything that made it a document. Text becomes pixels: not searchable, not selectable, not readable by a screen reader, and not reflowable. File size usually grows, sometimes enormously.' },
      { type: 'p', text: 'That is a fine trade when you need an image — a thumbnail, a figure for a slide, a preview. It is the wrong move if you are just trying to stop someone editing the document; protect it instead, and keep it a document.' },
    ],
    faqs: [
      { q: 'What DPI should I use for printing?', a: '300. It is the standard for print and the point past which higher settings stop being visible.' },
      { q: 'How do I convert only one page?', a: 'Extract that page into its own PDF first, then convert it. That way you get one image rather than a ZIP of forty.' },
      { q: 'Why is my JPG bigger than the PDF?', a: 'Because a page of text stored as vector instructions is tiny, and the same page stored as millions of pixels is not. This is normal.' },
      { q: 'Can I get a transparent background?', a: 'Not with JPG, which has no transparency. Export PNG if you need it — though PDF pages are opaque anyway, so the background will be white.' },
    ],
    related: ['how-to-extract-images-from-a-pdf', 'why-is-my-pdf-blurry', 'how-to-convert-pdf-to-image-for-printing'],
  },

  {
    slug: 'how-to-extract-images-from-a-pdf',
    title: 'How to Extract Images From a PDF',
    description: 'Pull the original pictures out of a PDF at full resolution, and understand why that is different from screenshotting the page.',
    keyword: 'extract images from pdf',
    category: 'Converting',
    published: '2026-05-08',
    tool: 'pdf-to-jpg',
    blocks: [
      { type: 'p', text: 'There are two different jobs here and it is worth knowing which you want. Extracting images pulls out the embedded picture files themselves. Converting pages to images renders whole pages, text and all, as pictures.' },
      { type: 'h2', text: 'Which one you need' },
      { type: 'table', head: ['You want', 'Do this'], rows: [
        ['A photograph that appears in a report', 'Extract the embedded image'],
        ['A whole page as a picture', 'Convert the page to JPG or PNG'],
        ['A chart drawn as vectors', 'Convert the page — there is no image file to extract'],
        ['Every picture from a catalogue', 'Extract images'],
      ] },
      { type: 'h2', text: 'How to do it' },
      { type: 'steps', items: [
        'Open the PDF to JPG tool and add your document.',
        'Choose whether you want the embedded images or full-page renders.',
        'Run it — several files come back as a single ZIP.',
      ] },
      { type: 'h2', text: 'You get what was embedded, not what you saw' },
      { type: 'p', text: 'An extracted image comes out at the resolution it was stored at, which is often not the size it appeared on the page. A photo placed small in a report may have been embedded at full camera resolution — extraction gives you all of it. Equally, an image that was downsampled when the PDF was made comes out small, and no amount of extraction recovers what was thrown away.' },
      { type: 'callout', title: 'Vector graphics cannot be extracted as images', text: 'Charts, logos and diagrams are frequently drawn as vector paths rather than stored as pictures. There is no image file inside the PDF to pull out. Rendering the page — or the region — is the only way to get one.' },
      { type: 'h2', text: 'When a single picture is split into several' },
      { type: 'p', text: 'Some producers slice a large image into tiles, and some build a photograph from a base image plus a separate transparency mask. Extraction returns exactly what is stored, so you may get fragments or a strange-looking greyscale alongside the picture. When that happens, render the page at 300 DPI and crop instead — less pure, more useful.' },
      { type: 'h2', text: 'Rights' },
      { type: 'p', text: 'Being able to extract an image says nothing about whether you may use it. Photographs in reports, brochures and articles are usually licensed to the publisher for that use only. Extracting for personal reference is one thing; republishing is another, and the licence does not travel with the file.' },
    ],
    faqs: [
      { q: 'Why are my extracted images low resolution?', a: 'Because that is how they were embedded. Many PDFs downsample images to keep the file small, and the discarded detail is gone.' },
      { q: 'Why did one picture come out as several files?', a: 'It was stored as tiles, or as an image plus a separate transparency mask. Rendering the page and cropping is the practical alternative.' },
      { q: 'Can I extract a logo?', a: 'Only if it is stored as an image. Logos are usually vector artwork, so render the page at high DPI and crop instead.' },
      { q: 'Does extracting change the images?', a: 'No — you get the stored data as it is. Rendering a page, by contrast, produces a new image at whatever resolution you choose.' },
    ],
    related: ['how-to-convert-pdf-to-jpg-high-quality', 'why-is-my-pdf-so-large', 'how-to-convert-pdf-to-image-for-printing'],
  },

  {
    slug: 'how-to-convert-a-pdf-into-editable-text',
    title: 'How to Convert a PDF Into Editable Text',
    description: 'Get the words out of a PDF so you can edit them — the three different situations you might be in, and the right approach for each.',
    keyword: 'convert pdf to editable text',
    category: 'Converting',
    published: '2026-05-22',
    tool: 'pdf-to-markdown',
    blocks: [
      { type: 'p', text: '"Make this PDF editable" means three quite different things depending on what is inside the file. Working out which situation you are in takes about five seconds and saves a lot of wasted effort.' },
      { type: 'h2', text: 'Work out what you have' },
      { type: 'p', text: 'Open the PDF and try to select a sentence with your cursor.' },
      { type: 'table', head: ['What happens', 'What you have', 'What to do'], rows: [
        ['Text highlights normally', 'A digital PDF with real text', 'Convert straight to Word, Markdown or plain text'],
        ['A rectangle is drawn over an image', 'A scan', 'Run OCR first, then convert'],
        ['Nothing selects and nothing happens', 'Possibly protected', 'Remove the restriction if you are entitled to, then convert'],
      ] },
      { type: 'h2', text: 'Choosing an output format' },
      { type: 'list', items: [
        'Word (.docx) — for documents that need to keep headings, tables and styling and be edited by other people.',
        'Markdown — for text destined for a website, a wiki, a README or an AI tool. Clean, structural and diff-friendly.',
        'Plain text — when you want the words and nothing else, for search, analysis or pasting elsewhere.',
      ] },
      { type: 'p', text: 'Markdown is underrated here. It keeps heading levels and lists as structure without dragging along any of the formatting baggage of a word processor, which makes it the best format when the text is going somewhere other than back into a document.' },
      { type: 'callout', title: 'Reading order is not always visual order', text: 'Text is extracted in the order it was drawn, which is usually — but not always — the order you read it. Multi-column layouts and pages assembled by a design tool can interleave. Check the beginning of the output before assuming the whole thing is in sequence.' },
      { type: 'h2', text: 'Scanned documents' },
      { type: 'p', text: 'There is no text to extract from a scan; there are pictures of text. OCR reads the pictures and produces characters. Recognition of clean printed text at 300 DPI is very good, but proofread anything that matters — names, figures and dates are exactly where an error costs you.' },
      { type: 'h2', text: 'Do you need to convert at all?' },
      { type: 'p', text: 'If the edit is small — a signature, a form field, a redaction, a page removed — do it to the PDF directly. Converting out and back in for a two-word change costs you the layout and gains nothing.' },
    ],
    faqs: [
      { q: 'How can I tell if my PDF is scanned?', a: 'Try to select a line of text. If your cursor draws a box instead of highlighting words, it is a scan.' },
      { q: 'Which format keeps the most formatting?', a: 'Word. Markdown keeps structure without styling; plain text keeps neither.' },
      { q: 'Why is my extracted text jumbled?', a: 'The drawing order differs from the reading order, which is common in multi-column and design-tool layouts.' },
      { q: 'Can I edit a PDF without converting it?', a: 'For adding signatures, filling forms, redacting, rotating or removing pages — yes, and you should. Rewriting body text is where conversion becomes necessary.' },
    ],
    related: ['how-to-convert-pdf-to-word-without-losing-formatting', 'how-to-copy-text-from-a-scanned-pdf', 'how-to-convert-pdf-to-markdown'],
  },

  {
    slug: 'how-to-convert-pdf-to-markdown',
    title: 'How to Convert a PDF to Markdown',
    description: 'Extract clean, structured Markdown from a PDF — for documentation, static sites, wikis, or feeding a document to an AI tool.',
    keyword: 'convert pdf to markdown',
    category: 'Converting',
    published: '2026-06-05',
    tool: 'pdf-to-markdown',
    blocks: [
      { type: 'p', text: 'Markdown has quietly become the format text goes to when it needs to live somewhere other than a word processor: documentation, static sites, wikis, issue trackers, and the context window of an AI assistant.' },
      { type: 'h2', text: 'Convert a PDF to Markdown' },
      { type: 'steps', items: [
        'Open the PDF to Markdown tool and add your file.',
        'Convert. Headings, paragraphs and lists are reconstructed as Markdown syntax.',
        'Review the output, particularly the heading levels.',
      ] },
      { type: 'h2', text: 'Why Markdown rather than Word' },
      { type: 'list', items: [
        'It is plain text, so it diffs cleanly in version control.',
        'It carries structure — heading levels, lists, emphasis — without any styling to fight.',
        'Every static site generator and documentation platform reads it natively.',
        'It is compact, which matters when you are pasting a document into a tool with a size limit.',
      ] },
      { type: 'h2', text: 'What converts, and how well' },
      { type: 'table', head: ['In the PDF', 'In the Markdown'], rows: [
        ['Headings', '#, ## and ### by detected size and weight'],
        ['Paragraphs', 'Blank-line separated blocks'],
        ['Bulleted lists', 'Hyphen lists'],
        ['Numbered lists', 'Numbered lists'],
        ['Simple tables', 'Pipe tables, when the columns are clean'],
        ['Images', 'A reference — extract the files separately'],
        ['Two-column layout', 'Flattened into one column, sometimes interleaved'],
      ] },
      { type: 'callout', title: 'Check the heading levels first', text: 'Heading depth is inferred from font size, so a document with subtle typography can produce every heading at the same level. Fixing the hierarchy is usually the only clean-up a converted file needs.' },
      { type: 'h2', text: 'Feeding documents to AI tools' },
      { type: 'p', text: 'This is now one of the main reasons people convert. A PDF pasted into a chat tool arrives as an unstructured wall of text; the same document as Markdown arrives with its headings and lists intact, and models use that structure to answer questions about specific sections.' },
      { type: 'p', text: 'If the document is confidential, note that converting it locally keeps it on your machine — but pasting the result into a hosted AI service does not. That is a separate decision from the conversion.' },
      { type: 'h2', text: 'Scanned documents' },
      { type: 'p', text: 'Run OCR first. Without it there is no text to convert and you will get an empty file — which is at least an unambiguous signal about what you are holding.' },
    ],
    faqs: [
      { q: 'Do images come across?', a: 'Not as files. You get a reference where the image was; extract the pictures separately and put them alongside.' },
      { q: 'Why is everything one heading level?', a: 'Detection works from font size. If the source used similar sizes for several levels, the distinction was not there to detect.' },
      { q: 'Do tables convert?', a: 'Simple ones do, as pipe tables. Merged cells and irregular grids do not translate — Markdown tables are strictly rectangular.' },
      { q: 'Is Markdown better than plain text for AI tools?', a: 'Generally yes. The heading and list structure gives a model something to navigate by.' },
    ],
    related: ['how-to-convert-a-pdf-into-editable-text', 'how-to-summarize-a-long-pdf', 'how-to-convert-pdf-to-word-without-losing-formatting'],
  },
];
