import type { BlogPost } from '../types';

export const convertingFromPdfPosts2: BlogPost[] = [
  {
    slug: 'how-to-copy-text-from-a-scanned-pdf',
    title: 'How to Copy Text From a Scanned PDF',
    description: 'You cannot select text in a scan because there is none. Here is how OCR turns the picture into characters you can copy, search and edit.',
    keyword: 'copy text from scanned pdf',
    category: 'Converting',
    published: '2026-06-19',
    tool: 'ocr-pdf',
    blocks: [
      { type: 'p', text: 'You open a PDF, try to select a paragraph, and your cursor draws a rectangle instead of highlighting words. Nothing is broken — the file simply has no text in it. What you are looking at is a photograph of a page.' },
      { type: 'h2', text: 'Make the text selectable' },
      { type: 'steps', items: [
        'Open the OCR tool and add your scanned PDF.',
        'Run it. Every page image is read and an invisible text layer is written over it.',
        'Download the result and try selecting a paragraph — it should now highlight.',
        'Search for a word you know is in the document to confirm the layer is there.',
      ] },
      { type: 'h2', text: 'What OCR does to the file' },
      { type: 'p', text: 'Nothing you can see. The scanned image stays exactly as it was, and the recognised characters are placed invisibly on top, each positioned over the word it came from. That is why selecting text in an OCRed scan highlights in the right place even though the words you see are still part of the picture.' },
      { type: 'callout', title: 'Proofread anything that matters', text: 'OCR on clean 300 DPI print is very accurate but never perfect. Names, reference numbers, dates and amounts are exactly where an error is both most likely and most costly. Check them against the image rather than trusting the copy.' },
      { type: 'h2', text: 'What hurts accuracy' },
      { type: 'table', head: ['Problem', 'Effect'], rows: [
        ['Low resolution (under 200 DPI)', 'Characters blur together; accuracy drops sharply'],
        ['Skewed pages', 'Lines are hard to segment — the biggest single factor'],
        ['Faint or faxed originals', 'Thin strokes disappear entirely'],
        ['Handwriting', 'Generally not recognised at all'],
        ['Unusual or decorative fonts', 'Higher error rates than plain text faces'],
        ['Dense tables with faint rules', 'Column boundaries confuse the layout analysis'],
      ] },
      { type: 'p', text: 'If the result is poor, the fix is almost always at the scanner rather than in the software: rescan at 300 DPI, straight, in greyscale.' },
      { type: 'h2', text: 'The quick alternative for one paragraph' },
      { type: 'p', text: 'If you only need a few lines and OCR feels like overkill, most phones will now read text out of a photograph directly — point the camera at the screen, select the text, copy. It is crude, and for a couple of sentences it is faster than anything else.' },
      { type: 'h2', text: 'After OCR' },
      { type: 'p', text: 'Once there is a text layer, the whole toolkit opens up: the document is searchable, convertible to Word or Markdown, and readable by screen readers. It is worth running on anything going into long-term storage, because a scan you cannot search is a scan you will never find again.' },
    ],
    faqs: [
      { q: 'Why can I not select text in my PDF?', a: 'Because it is a scan — an image of a page rather than text. Run OCR to add a text layer.' },
      { q: 'Does OCR change how the page looks?', a: 'No. The image is untouched and the recognised text is invisible.' },
      { q: 'How accurate is OCR?', a: 'On clean printed text at 300 DPI, very. On faint, skewed or handwritten material, unreliable enough that you must check.' },
      { q: 'Can I OCR a photo I took of a page?', a: 'Yes. Convert it to PDF first, and use your phone\'s scanner mode when capturing so the page is cropped and squared.' },
    ],
    related: ['how-to-make-a-scanned-pdf-searchable', 'what-is-ocr-and-how-does-it-work', 'how-to-convert-a-pdf-into-editable-text'],
  },

  {
    slug: 'how-to-convert-pdf-to-pdfa-for-archiving',
    title: 'How to Convert a PDF to PDF/A for Long-Term Archiving',
    description: 'PDF/A is the format archives and courts ask for. Here is what makes it different, when you need it, and how to convert.',
    keyword: 'convert pdf to pdfa',
    category: 'Converting',
    published: '2026-07-03',
    tool: 'pdf-to-pdfa',
    blocks: [
      { type: 'p', text: 'PDF/A is a restricted version of PDF designed so that a file opened in fifty years looks the way it does today. Courts, national archives, universities and regulators increasingly require it.' },
      { type: 'h2', text: 'Convert to PDF/A' },
      { type: 'steps', items: [
        'Open the PDF to PDF/A tool and add your document.',
        'Convert. Fonts are embedded, the colour handling is made explicit, and the archival metadata is written in.',
        'Keep the original alongside the archival copy — conversion is one-way in spirit.',
      ] },
      { type: 'h2', text: 'What makes a PDF archival' },
      { type: 'p', text: 'The core idea is self-containment: everything needed to render the page must be inside the file, and nothing may depend on the outside world.' },
      { type: 'list', items: [
        'Fonts must be embedded, so the document does not depend on what is installed later.',
        'Colour must be unambiguous, with an explicit colour space rather than "whatever the device does".',
        'No external references — no linked images, no fetched content.',
        'No encryption, because a future reader must be able to open it.',
        'No JavaScript, no audio, no video, no executable content.',
        'Structured XMP metadata declaring the conformance level.',
      ] },
      { type: 'h2', text: 'The conformance levels' },
      { type: 'table', head: ['Level', 'Guarantees'], rows: [
        ['PDF/A-1b', 'Visual appearance is preserved. The common baseline.'],
        ['PDF/A-1a', 'Appearance plus tagged structure and reading order, for accessibility.'],
        ['PDF/A-2', 'Adds JPEG 2000, transparency and embedded PDF/A attachments.'],
        ['PDF/A-3', 'Adds arbitrary attachments — used for e-invoicing formats such as ZUGFeRD.'],
      ] },
      { type: 'p', text: 'If a requirement just says "PDF/A", level 1b or 2b is what is normally meant. Ask if the answer determines whether a filing is accepted.' },
      { type: 'callout', title: 'PDF/A cannot rescue a scan', text: 'Converting an image-only scan to PDF/A produces an archival file containing an unsearchable picture. Run OCR first — an archive you cannot search is barely an archive.' },
      { type: 'h2', text: 'What conversion changes' },
      { type: 'p', text: 'Expect the file to grow, because fonts that were previously referenced now have to be carried inside it. Expect encryption and interactive content to be stripped, since neither is permitted. And expect transparency effects to be flattened when converting to the older levels — which is why you keep the original.' },
      { type: 'h2', text: 'Validate before you rely on it' },
      { type: 'p', text: 'A file can declare PDF/A conformance and still fail validation — usually because the converting tool wrote the metadata without enforcing every rule. If acceptance by a court, a registry or an archive depends on conformance, run a validator rather than trusting the declaration.' },
      { type: 'h2', text: 'What to archive alongside the file' },
      { type: 'list', items: [
        'The original PDF, which is smaller and unconstrained.',
        'A note of the conformance level, so future readers know what was claimed.',
        'The date of conversion and the tool used.',
        'A checksum, so future corruption can be detected rather than guessed at.',
      ] },
      { type: 'p', text: 'An archive is a system rather than a file format. PDF/A guarantees the document will render; the surrounding records are what let anyone verify it is the document that was deposited.' },
    ],
    faqs: [
      { q: 'Is PDF/A just a normal PDF?', a: 'A PDF/A file opens in any reader like any other PDF. The difference is the constraints it satisfies, recorded in its metadata.' },
      { q: 'Which level do I need?', a: 'Whatever the receiving body specifies. Where nothing is specified, 1b or 2b is the safe default.' },
      { q: 'Can I password-protect a PDF/A?', a: 'No. Encryption is forbidden precisely because it could make the file unreadable in the future.' },
      { q: 'Why did my file get bigger?', a: 'Because fonts are now embedded rather than assumed. That is the point of the format.' },
    ],
    related: ['pdf-vs-pdfa-what-is-the-difference', 'how-to-make-a-scanned-pdf-searchable', 'how-to-remove-metadata-from-a-pdf'],
  },

  {
    slug: 'how-to-export-pdf-tables-to-csv',
    title: 'How to Export Tables From a PDF to CSV',
    description: 'Get tabular data out of a PDF and into a CSV you can actually work with — and how to check the extraction before you trust the numbers.',
    keyword: 'export pdf table to csv',
    category: 'Converting',
    published: '2026-07-17',
    tool: 'pdf-to-excel',
    blocks: [
      { type: 'p', text: 'CSV is the format data goes to when it needs to be processed rather than read: imported into a database, loaded into a script, opened in any spreadsheet on any platform.' },
      { type: 'h2', text: 'Get the table out' },
      { type: 'steps', items: [
        'Open the PDF to Excel tool and add your document.',
        'Convert. Text is grouped into rows and columns using position and any ruled lines.',
        'Open the result in a spreadsheet and check the column boundaries.',
        'Save as CSV once you are satisfied the grid is right.',
      ] },
      { type: 'h2', text: 'Verify before you trust it' },
      { type: 'p', text: 'Table extraction fails quietly, which is what makes it dangerous. Four checks catch nearly everything:' },
      { type: 'list', items: [
        'Count the rows. A mismatch usually means wrapped cells were split into extra rows.',
        'Total a numeric column and compare it with the total printed in the PDF.',
        'Look for cells containing what should be two values — a column boundary that was missed.',
        'Check the first and last rows, where headers and totals get mixed into the data.',
      ] },
      { type: 'callout', title: 'One decimal in the wrong cell', text: 'The failure that costs money is not a wrecked layout you can see. It is a boundary landing mid-number so 1,234.56 becomes two cells. Always reconcile a total against the source page.' },
      { type: 'h2', text: 'Cleaning the data' },
      { type: 'table', head: ['Symptom', 'Fix'], rows: [
        ['Numbers will not sum', 'They are text — strip currency symbols, spaces and stray characters'],
        ['Two values in one cell', 'Text to Columns with the right delimiter'],
        ['Header repeated through the data', 'The table spanned pages; delete the repeats'],
        ['Rows split in two', 'A cell wrapped onto a second line; re-join them'],
        ['Dates read as text or as the wrong day', 'Reformat the column explicitly'],
      ] },
      { type: 'h2', text: 'Ask for the source first' },
      { type: 'p', text: 'Every PDF table was generated from something — a spreadsheet, a database, a report tool. That source is authoritative and requires no verification. For a one-off table, extraction is quicker than an email; for anything recurring or financially material, the email is worth sending.' },
      { type: 'h2', text: 'Scanned tables' },
      { type: 'p', text: 'OCR first, then extract, then verify twice. A digit misrecognised in a column of figures is invisible in the output and entirely plausible in the data — this is the highest-risk extraction there is.' },
    ],
    faqs: [
      { q: 'Can I go straight from PDF to CSV?', a: 'Convert to a spreadsheet first. That is where you can see and correct the column boundaries before committing to a flat file.' },
      { q: 'Why is my data all in one column?', a: 'The spacing between columns was not read as a boundary. Use Text to Columns to split it.' },
      { q: 'Can I extract a table that spans several pages?', a: 'Yes, but each page is handled separately and repeated headers land in the middle of your data. Delete them afterwards.' },
      { q: 'How accurate is table extraction?', a: 'Very good on ruled, regular tables. Poor on borderless layouts with merged cells — and always worth verifying against a printed total.' },
    ],
    related: ['how-to-convert-pdf-to-excel-with-tables', 'how-to-convert-csv-to-pdf', 'how-to-copy-text-from-a-scanned-pdf'],
  },

  {
    slug: 'how-to-convert-pdf-to-image-for-printing',
    title: 'How to Convert a PDF to an Image for Printing',
    description: 'Render PDF pages as print-ready images at the right resolution — and why sending the PDF itself is usually the better option.',
    keyword: 'convert pdf to image for printing',
    category: 'Converting',
    published: '2026-07-31',
    tool: 'pdf-to-jpg',
    blocks: [
      { type: 'p', text: 'Print shops sometimes ask for images rather than PDFs, and some large-format workflows only accept them. When that happens, resolution is the only setting that really matters.' },
      { type: 'h2', text: 'Render pages at print resolution' },
      { type: 'steps', items: [
        'Open the PDF to JPG tool and add your document.',
        'Set 300 DPI for normal printing.',
        'Convert, and check one page at 100% zoom to confirm the text is crisp.',
      ] },
      { type: 'h2', text: 'The resolution maths' },
      { type: 'p', text: 'DPI describes dots per printed inch, so the pixel size you need follows from the physical size of the output.' },
      { type: 'table', head: ['Output', 'DPI', 'Pixels for A4'], rows: [
        ['Office document', '300', '2480 × 3508'],
        ['High-quality brochure', '400–600', '3300 × 4700 and up'],
        ['Poster viewed at arm\'s length', '150–200', 'Scaled to the poster size'],
        ['Billboard viewed from far away', '30–72', 'Much lower is genuinely fine'],
      ] },
      { type: 'p', text: 'Large-format work needs less DPI than people expect, because viewing distance grows with the print. A billboard at 300 DPI would be an unmanageable file for no visible gain.' },
      { type: 'callout', title: 'Rendering cannot add detail', text: 'Exporting a 72 DPI scan at 600 DPI produces a large file containing the same blur, enlarged. Resolution is limited by what is in the PDF, not by the setting you choose on the way out.' },
      { type: 'h2', text: 'Colour' },
      { type: 'p', text: 'PDFs for print are often authored in CMYK. Rendering to JPG or PNG converts to RGB, and saturated colours will shift — a deep print blue is the classic casualty. For colour-critical work, keep the PDF as a PDF and let the print shop handle the separation.' },
      { type: 'h2', text: 'Why the PDF is usually better' },
      { type: 'p', text: 'PDF is the native format of professional printing. Text stays as vectors and prints at the device\'s full resolution rather than at whatever DPI you chose; fonts are embedded; colour profiles are preserved; trim and bleed boxes survive. Rendering to an image throws all of that away.' },
      { type: 'p', text: 'Convert when the workflow demands images. Otherwise send the PDF and let the RIP do its job.' },
      { type: 'h2', text: 'Preparing the files for the print shop' },
      { type: 'steps', items: [
        'Ask what they want before you export — format, resolution, colour mode and bleed.',
        'Export one page first and send it for approval rather than the whole job.',
        'Name the files in page order with zero padding, so 10 does not sort before 2.',
        'Send them as a single archive rather than thirty attachments.',
        'Include a PDF of the document as well, in case they would rather use it.',
      ] },
      { type: 'p', text: 'That last point saves more jobs than anything else on the list. Print operators generally prefer a PDF, and a request for images is often a default rather than a requirement — asking takes one message and frequently removes the whole problem.' },
    ],
    faqs: [
      { q: 'What DPI does a print shop need?', a: '300 for ordinary print. Ask for large-format work — the answer is usually lower than you would guess.' },
      { q: 'JPG or PNG for print?', a: 'PNG for pages with text or line art, since JPEG artefacts show around sharp edges. JPG is acceptable for photographic pages at high quality.' },
      { q: 'Why do my colours look different after converting?', a: 'The document was CMYK and the image is RGB. Send the PDF instead if the colour matters.' },
      { q: 'Should I convert at 600 DPI to be safe?', a: 'Only if the source has that detail. Otherwise you get a much larger file and no improvement.' },
    ],
    related: ['how-to-convert-pdf-to-jpg-high-quality', 'why-is-my-pdf-blurry', 'how-to-print-a-pdf-correctly'],
  },

  {
    slug: 'how-to-convert-a-pdf-to-google-docs',
    title: 'How to Convert a PDF to Google Docs',
    description: 'Open and edit a PDF in Google Docs, what the import mangles, and when converting to Word first gives you a much cleaner result.',
    keyword: 'convert pdf to google docs',
    category: 'Converting',
    published: '2026-08-04',
    tool: 'pdf-to-word',
    blocks: [
      { type: 'p', text: 'Google Docs will open a PDF, and the result is frequently disappointing. Knowing why lets you pick the route that produces something editable rather than something you have to rebuild.' },
      { type: 'h2', text: 'The direct route' },
      { type: 'steps', items: [
        'Upload the PDF to Google Drive.',
        'Right-click it and choose Open with → Google Docs.',
        'Drive converts it and opens an editable document.',
      ] },
      { type: 'p', text: 'This is free, built in, and adequate for a plain text document. It struggles with anything designed.' },
      { type: 'h2', text: 'What the import loses' },
      { type: 'list', items: [
        'Multi-column layouts are flattened into one column, sometimes out of order.',
        'Tables often arrive as loose text rather than tables.',
        'Images are placed inline and rarely where they were.',
        'Headers, footers and page numbers are usually dropped.',
        'Fonts are substituted for whatever Google has.',
        'Precise spacing and alignment are approximated.',
      ] },
      { type: 'callout', title: 'Drive runs OCR on scans automatically', text: 'Opening a scanned PDF in Google Docs triggers OCR without asking. That is genuinely useful — and worth knowing, because it means the document was processed on Google\'s servers rather than on your machine.' },
      { type: 'h2', text: 'The cleaner route' },
      { type: 'p', text: 'Convert the PDF to Word first, then open the .docx in Google Docs. A dedicated converter usually reconstructs headings, lists and tables more faithfully than Drive\'s import, and Docs opens Word files with high fidelity. It is one extra step for a noticeably better starting point on any document with structure.' },
      { type: 'h2', text: 'Privacy' },
      { type: 'p', text: 'Uploading to Drive puts the document on Google\'s servers and, for a scan, runs recognition there too. For a newsletter that is irrelevant; for a client contract or a medical letter it may not be. Converting locally and uploading only the finished editable file keeps the original off the network.' },
      { type: 'h2', text: 'Working with the converted document' },
      { type: 'p', text: 'Whichever route you take, spend the first two minutes fixing structure rather than content. Apply real Google Docs heading styles to the headings — the import usually leaves them as body text with manual formatting, which means the outline pane is empty and the document cannot be navigated.' },
      { type: 'p', text: 'Then check the tables. If a table arrived as loose lines of text, it is faster to insert a proper table and paste the values in than to fight the imported version into shape.' },
      { type: 'h2', text: 'Going back to PDF' },
      { type: 'p', text: 'Google Docs exports to PDF directly through File → Download. The result reflects the Docs layout rather than your original, so if the design mattered, compare the two before circulating the new version — a round trip through any editor is a redesign, not a copy.' },
    ],
    faqs: [
      { q: 'Can Google Docs edit a PDF directly?', a: 'No. It converts the PDF into a Docs document, and you edit that. The PDF in Drive is unchanged.' },
      { q: 'Why does my layout fall apart?', a: 'Because a PDF stores positioned text, not paragraph structure, and Docs has to guess. Designed layouts are where the guessing shows.' },
      { q: 'Does Google Docs OCR scanned PDFs?', a: 'Yes, automatically on import — which also means the scan was processed on Google\'s infrastructure.' },
      { q: 'What is the best way to edit a PDF in Google Docs?', a: 'Convert to Word with a dedicated tool first, then open that .docx in Docs.' },
    ],
    related: ['how-to-convert-pdf-to-word-without-losing-formatting', 'is-it-safe-to-use-online-pdf-tools', 'how-to-convert-a-pdf-into-editable-text'],
  },
];
