import type { BlogPost } from '../types';

export const convertingToPdfPosts: BlogPost[] = [
  {
    slug: 'how-to-convert-jpg-to-pdf',
    title: 'How to Convert JPG to PDF (Free, In Your Browser)',
    description: 'Turn photos and scans into a PDF — one image or a hundred — with control over page size, orientation and quality. Nothing is uploaded.',
    keyword: 'how to convert jpg to pdf',
    category: 'Converting',
    published: '2026-02-26',
    updated: '2026-08-06',
    tool: 'jpg-to-pdf',
    blocks: [
      { type: 'p', text: 'Converting images to PDF is how a folder of photographs becomes a document you can send. It matters because a PDF has a fixed page order and opens the same way everywhere, which a pile of JPGs does not.' },
      { type: 'h2', text: 'Convert JPG to PDF' },
      { type: 'steps', items: [
        'Open the JPG to PDF tool and add your images. Drop in as many as you like.',
        'Drag them into the order you want the pages to appear.',
        'Choose page size and orientation, or let each page match its image.',
        'Convert, and the PDF downloads to your device.',
      ] },
      { type: 'h2', text: 'One page per image, or all of them in one file' },
      { type: 'p', text: 'Both are useful and they solve different problems. One PDF containing every image is what you want for a scanned document, a receipts pack or a photo report — it stays together and reads in order. Separate PDFs make sense when the images are unrelated and will be sent to different people.' },
      { type: 'h2', text: 'Choosing a page size' },
      { type: 'table', head: ['Option', 'Best for'], rows: [
        ['Fit page to image', 'Screenshots and mixed sizes — no white margins, no cropping'],
        ['A4 or US Letter', 'Anything that will be printed or filed alongside other documents'],
        ['Auto orientation', 'Mixed portrait and landscape photos in one document'],
      ] },
      { type: 'p', text: 'The trap is forcing a landscape photo onto a portrait page: you either get a small image floating in white space, or a crop that removes part of the picture. Auto orientation avoids the choice.' },
      { type: 'callout', title: 'Convert does not mean compress', text: 'A 5 MB photo is still roughly 5 MB inside the PDF. Twenty of them make a 100 MB file. If size matters, compress the PDF after converting rather than expecting the conversion to shrink anything.' },
      { type: 'h2', text: 'Does converting reduce image quality?' },
      { type: 'p', text: 'It should not. A JPG can be embedded into a PDF exactly as it is, with the same pixels and the same compression it already had. Quality only drops if the tool re-encodes the image — which some do in order to hit a size target, usually without saying so. The test is simple: if the PDF is dramatically smaller than the sum of your images, something was re-compressed.' },
      { type: 'h2', text: 'PNG, HEIC and other formats' },
      { type: 'p', text: 'PNG converts the same way and is the better choice for screenshots, where its lossless compression keeps text edges crisp. HEIC — the default on modern iPhones — is not universally supported, so tools generally decode it and re-encode as JPEG or PNG on the way in. That single re-encode is invisible in practice, but it is worth knowing it happened.' },
      { type: 'h2', text: 'Making the result searchable' },
      { type: 'p', text: 'A PDF made from photos contains no text, only pictures of text. Nothing in it can be searched or copied. Run OCR over the converted file and an invisible text layer is added beneath the images, so the document looks identical but becomes searchable.' },
    ],
    faqs: [
      { q: 'How do I convert multiple JPGs into one PDF?', a: 'Add them all to the converter and choose the single-document option. Order them before converting — the sequence in the list becomes the page order.' },
      { q: 'Does converting JPG to PDF lose quality?', a: 'Not if the image is embedded as-is. Be suspicious of any conversion that produces a PDF far smaller than the images that went into it.' },
      { q: 'Can I convert HEIC photos from my iPhone?', a: 'Yes. They are decoded and re-encoded to a format PDF supports, which is a single lossy step you will not see at normal viewing sizes.' },
      { q: 'What page size should I use for scanned documents?', a: 'A4 or US Letter, matching your originals, so the pages print at the right size and file neatly with everything else.' },
      { q: 'Why is my converted PDF so large?', a: 'Because it contains your full-resolution photos. Compress it afterwards — image-heavy PDFs typically shrink dramatically with no visible difference.' },
    ],
    related: ['how-to-convert-png-to-pdf', 'how-to-convert-a-photo-to-pdf-on-your-phone', 'how-to-compress-a-pdf-without-losing-quality'],
  },

  {
    slug: 'how-to-convert-png-to-pdf',
    title: 'How to Convert PNG to PDF Without Losing Sharpness',
    description: 'PNG screenshots and diagrams turn into PDFs cleanly if you avoid one mistake. Here is how to keep text edges crisp and transparency under control.',
    keyword: 'how to convert png to pdf',
    category: 'Converting',
    published: '2026-03-10',
    tool: 'jpg-to-pdf',
    blocks: [
      { type: 'p', text: 'PNG is the right format for screenshots, diagrams and anything with sharp edges, because its compression is lossless. Converting to PDF should preserve that — and usually does, unless the tool quietly re-encodes your image as a JPEG.' },
      { type: 'h2', text: 'Convert a PNG to PDF' },
      { type: 'steps', items: [
        'Open the image-to-PDF tool and add your PNG files.',
        'Set the page size — fit-to-image is usually right for screenshots.',
        'Order the pages if you are converting several.',
        'Convert and download.',
      ] },
      { type: 'h2', text: 'The mistake that ruins screenshots' },
      { type: 'p', text: 'JPEG compression works by discarding detail the eye is unlikely to miss in a photograph. It is a poor fit for a screenshot: the sharp boundary between black text and white background is exactly what it throws away, producing a grey halo around every letter. Once a PNG has been through a JPEG round trip, those artefacts are permanent.' },
      { type: 'p', text: 'A converter that keeps your PNG as a PNG inside the PDF avoids this entirely. If your converted screenshots look slightly muddy at 200% zoom, the tool re-encoded them.' },
      { type: 'callout', title: 'Transparency has to go somewhere', text: 'PDF pages are opaque. A PNG with a transparent background gets composited onto white during conversion. That is fine for a diagram, but a white logo on transparency becomes a white logo on white — invisible.' },
      { type: 'h2', text: 'Getting screenshots to look right' },
      { type: 'list', items: [
        'Capture at the display resolution you will read at — enlarging a small screenshot afterwards cannot add detail.',
        'On a high-DPI screen, capture the full retina resolution rather than a downscaled copy.',
        'Use fit-to-image page sizing so the screenshot is not scaled to fit A4.',
        'Keep PNG for interfaces and text; JPEG is only better for photographs.',
      ] },
      { type: 'h2', text: 'When file size becomes a problem' },
      { type: 'p', text: 'PNG is lossless, which makes it large. A dozen full-screen captures can easily produce a 40 MB PDF. If that is too big, the honest trade is to compress the finished PDF and accept some softening — or to crop each screenshot to the part that matters, which usually cuts more size than compression and improves the document at the same time.' },
    ],
    faqs: [
      { q: 'Does PNG to PDF lose quality?', a: 'Not if the PNG is embedded as-is. It does if the converter re-encodes to JPEG — visible as grey fringing around text.' },
      { q: 'What happens to transparent backgrounds?', a: 'They are flattened onto white, because PDF pages are opaque. Check that nothing white in your image has just disappeared.' },
      { q: 'Can I put several PNGs in one PDF?', a: 'Yes — add them all and choose the single-document option. They become pages in the order you list them.' },
      { q: 'Why is my PNG-based PDF so much larger than a JPG one?', a: 'Because PNG stores every pixel exactly. That is the point of it, and it is the price of keeping text sharp.' },
    ],
    related: ['how-to-convert-jpg-to-pdf', 'how-to-compress-a-pdf-without-losing-quality', 'why-is-my-pdf-blurry'],
  },

  {
    slug: 'how-to-convert-word-to-pdf-without-losing-formatting',
    title: 'How to Convert Word to PDF Without Losing Formatting',
    description: 'Convert DOCX to PDF and keep the layout you designed. What actually breaks in conversion, why it happens, and how to check before you send.',
    keyword: 'convert word to pdf without losing formatting',
    category: 'Converting',
    published: '2026-03-18',
    updated: '2026-08-01',
    tool: 'word-to-pdf',
    blocks: [
      { type: 'p', text: 'Sending a Word file means trusting that the recipient\'s copy of Word, on their operating system, with their fonts installed, will lay the document out the way you did. Frequently it will not. Converting to PDF freezes the layout so everyone sees the same pages.' },
      { type: 'h2', text: 'Convert a DOCX to PDF' },
      { type: 'steps', items: [
        'Open the Word to PDF tool and add your .docx file.',
        'Convert. The document is laid out and written as a PDF.',
        'Open the result and page through it before sending — especially the page breaks.',
      ] },
      { type: 'h2', text: 'What usually shifts, and why' },
      { type: 'table', head: ['Symptom', 'Cause'], rows: [
        ['Text in a different typeface', 'The font was not embedded and is not available to the converter'],
        ['Lines wrapping differently', 'A substituted font has different letter widths'],
        ['Page breaks in new places', 'Different line wrapping pushes content onto the next page'],
        ['Tables spilling off the edge', 'The table was wider than the printable area to begin with'],
        ['Headers or footers missing', 'Section-specific headers that the converter did not carry over'],
      ] },
      { type: 'p', text: 'Almost all of it comes back to fonts. A DOCX does not necessarily contain the fonts it uses — it names them and assumes they are installed. When they are not, something has to be substituted, and every substitution changes the metrics that the layout depends on.' },
      { type: 'callout', title: 'Stick to fonts everyone has', text: 'For documents that must convert predictably, use widely available families — Arial, Times New Roman, Calibri, Georgia. A distinctive font is worth it for a designed brochure; it is rarely worth it for a contract.' },
      { type: 'h2', text: 'Check the conversion properly' },
      { type: 'steps', items: [
        'Compare the page count with the original. A difference means the reflow changed.',
        'Look at the last line of every page — that is where a shift shows first.',
        'Check tables end where they should and have not lost a column off the right edge.',
        'Confirm headers, footers and page numbers appear on every page.',
        'Check any embedded images have not moved relative to the text around them.',
      ] },
      { type: 'h2', text: 'Complex layouts need realistic expectations' },
      { type: 'p', text: 'A plain report converts perfectly. A newsletter with floating text boxes, overlapping images, wrapped captions and multi-column sections is a different proposition — those constructs are laid out by Word\'s own engine, and any other engine will approximate them.' },
      { type: 'p', text: 'If the document is design-critical and you have Word available, exporting to PDF from Word itself will always be the most faithful route, because it is the same engine that composed the document. Converters are for when you do not have that option — which is most of the time.' },
      { type: 'h2', text: 'Why convert at all' },
      { type: 'list', items: [
        'The recipient sees the pages you saw, regardless of their software.',
        'It cannot be casually edited, so what you sent is what exists.',
        'It prints predictably, with page breaks where you put them.',
        'It opens on any device without a word processor installed.',
      ] },
    ],
    faqs: [
      { q: 'Why does my font change when I convert Word to PDF?', a: 'Because the font is named in the document rather than embedded, and the converter does not have it. Use a common font, or embed fonts in the DOCX before converting.' },
      { q: 'Will my page count stay the same?', a: 'It should, if the fonts match. A changed page count is the clearest sign that text reflowed during conversion.' },
      { q: 'Can I convert back from PDF to Word afterwards?', a: 'Yes, but expect an approximation. PDF stores positioned text rather than paragraph structure, so the reconstruction rebuilds a document that looks similar rather than one that is identical.' },
      { q: 'Do tracked changes and comments come across?', a: 'No. Conversion produces the document as it currently reads. Accept or reject changes before converting so nothing is silently included.' },
    ],
    related: ['how-to-convert-pdf-to-word-without-losing-formatting', 'how-to-convert-excel-to-pdf-without-cutting-off-columns', 'how-to-fix-fonts-not-displaying-in-a-pdf'],
  },

  {
    slug: 'how-to-convert-excel-to-pdf-without-cutting-off-columns',
    title: 'How to Convert Excel to PDF Without Cutting Off Columns',
    description: 'Wide spreadsheets get sliced in half by default. Here is how to convert XLSX to PDF so every column stays on the page and stays readable.',
    keyword: 'convert excel to pdf without cutting off columns',
    category: 'Converting',
    published: '2026-04-02',
    updated: '2026-08-15',
    tool: 'excel-to-pdf',
    blocks: [
      { type: 'p', text: 'Spreadsheets are the hardest thing to put on a page. A sheet is an unbounded grid; a page is 21 centimetres wide. Something has to give, and by default what gives is the right-hand half of your table.' },
      { type: 'h2', text: 'Convert a spreadsheet to PDF' },
      { type: 'steps', items: [
        'Open the Excel to PDF tool and add your .xlsx or .csv file.',
        'Let it find the used range — the block of cells that actually contains data.',
        'Choose orientation. Landscape fits noticeably more columns.',
        'Convert, then check the far-right column is present in the output.',
      ] },
      { type: 'h2', text: 'Why columns disappear' },
      { type: 'p', text: 'When the table is wider than the page, a converter has three choices: cut it off, scale it down until it fits, or spill the overflow onto extra pages. Cutting is the worst outcome and the most common default, because it is the simplest to implement. The reader has no way of knowing anything is missing.' },
      { type: 'p', text: 'Scaling is usually the right answer, up to a point — past roughly half size, the text stops being readable and you have traded a missing column for an illegible one.' },
      { type: 'h2', text: 'Getting a wide table onto a page' },
      { type: 'list', items: [
        'Switch to landscape. It is the single biggest win and costs nothing.',
        'Hide columns the reader does not need — working columns, internal IDs, scratch calculations.',
        'Narrow the columns that are padded with whitespace before you convert.',
        'Shorten header text; "Qty" carries the same meaning as "Quantity Ordered".',
        'Split genuinely wide tables across two sheets and convert both.',
      ] },
      { type: 'callout', title: 'Empty cells are not free', text: 'A stray value in cell BZ400 makes the used range four hundred rows deep and seventy columns wide, and the whole grid is scaled to fit that. Delete stray cells outside your real data before converting — it is the most common cause of a comically small table on a huge page.' },
      { type: 'h2', text: 'What carries over from the spreadsheet' },
      { type: 'table', head: ['Element', 'Result'], rows: [
        ['Cell values and number formats', 'Preserved — currency, dates and decimals keep their formatting'],
        ['Fills, borders and font styling', 'Preserved'],
        ['Merged cells', 'Preserved as merged blocks'],
        ['Formulas', 'The computed value appears, not the formula'],
        ['Charts and images', 'Support varies by tool — check the output'],
        ['Multiple sheets', 'Usually one section per sheet, in sheet order'],
      ] },
      { type: 'h2', text: 'Check the conversion' },
      { type: 'p', text: 'Two checks catch nearly every problem. First, find the last column of your data in the PDF and confirm it is there. Second, read a row of numbers at 100% zoom — if you are squinting, the scale-to-fit went too far and the document needs landscape or fewer columns rather than more shrinking.' },
    ],
    faqs: [
      { q: 'Why is my Excel PDF cut off on the right?', a: 'The sheet is wider than the page and the converter cropped rather than scaled. Switch to landscape, hide unnecessary columns, or use a tool that scales the table to fit.' },
      { q: 'Why is my table tiny on a huge white page?', a: 'The used range is much bigger than your data, usually because of a stray value far down or across the sheet. Delete it and convert again.' },
      { q: 'Do formulas convert to PDF?', a: 'Their results do. A PDF shows values, not the formulas behind them.' },
      { q: 'Can I convert only one sheet?', a: 'Copy the sheet you need into a new workbook and convert that. It also removes anything on the other sheets that you did not intend to share.' },
      { q: 'Does CSV convert the same way?', a: 'Yes, though a CSV has no formatting to preserve — you get a plain table, which is often exactly what is wanted.' },
    ],
    related: ['how-to-convert-csv-to-pdf', 'how-to-convert-pdf-to-excel-with-tables', 'how-to-convert-word-to-pdf-without-losing-formatting'],
  },

  {
    slug: 'how-to-convert-powerpoint-to-pdf',
    title: 'How to Convert PowerPoint to PDF (One Slide Per Page)',
    description: 'Turn a PPTX deck into a PDF that keeps every slide, in order, on its own page — and decide what to do about animations and speaker notes.',
    keyword: 'how to convert powerpoint to pdf',
    category: 'Converting',
    published: '2026-04-15',
    tool: 'powerpoint-to-pdf',
    blocks: [
      { type: 'p', text: 'Sending a deck as PDF is usually the right call. It opens everywhere, the fonts cannot substitute themselves, nobody can edit it by accident, and it prints as handouts without a fight.' },
      { type: 'h2', text: 'Convert a deck to PDF' },
      { type: 'steps', items: [
        'Open the PowerPoint to PDF tool and add your .pptx file.',
        'Convert. Each slide is drawn onto its own page at the deck\'s aspect ratio.',
        'Page through the result — check the title slide, a text-heavy slide, and any slide with a table.',
      ] },
      { type: 'h2', text: 'What happens to animations and transitions' },
      { type: 'p', text: 'They are gone, and there is no way around it — a PDF page does not move. What matters is what a converter does with the end state of an animated slide. Content that builds up in five clicks should appear complete on the page; content set to fade out should not vanish.' },
      { type: 'p', text: 'If a slide relies on animation to make sense — a sequence that only reads in order — it will not survive as a static page. Split it into several slides before converting.' },
      { type: 'callout', title: 'Speaker notes are not included', text: 'Notes stay in the PPTX. That is usually what you want when sending a deck externally, and a nasty surprise when you meant to send handouts with notes. Check before assuming either way.' },
      { type: 'h2', text: 'Aspect ratio and paper' },
      { type: 'p', text: 'Modern decks are 16:9, which is nothing like A4. A converter that keeps the slide shape produces wide, short pages — right on screen, and fine to print with margins. A converter that forces A4 either adds thick white bands or crops the slide edges.' },
      { type: 'p', text: 'For screen reading, keep the slide aspect ratio. For printed handouts, expect white space above and below, which is normal and not a fault.' },
      { type: 'h2', text: 'Fonts, again' },
      { type: 'p', text: 'A deck built with a brand font that the converter does not have will substitute something, and substituted fonts have different widths — so a heading that fitted on one line may wrap onto two and overlap the content beneath it. Decks are more vulnerable to this than documents, because slide text is positioned in fixed boxes rather than reflowing.' },
      { type: 'p', text: 'Check every slide with a long title. That is where it shows.' },
      { type: 'h2', text: 'Going the other way' },
      { type: 'p', text: 'If you have a PDF and need editable slides, that is the PDF to PowerPoint tool instead — it reads the text and structure out of the pages and builds slides from them. The two tools are opposites and picking the wrong one produces a file in the format you already had.' },
    ],
    faqs: [
      { q: 'Does converting PowerPoint to PDF keep the animations?', a: 'No. A PDF is static. Slides that depend on a build sequence should be split into separate slides first.' },
      { q: 'Will each slide be its own page?', a: 'Yes — one slide, one page, in deck order.' },
      { q: 'Are speaker notes included?', a: 'No. They remain in the PowerPoint file and do not appear in the PDF.' },
      { q: 'Why did my text overlap after converting?', a: 'A substituted font is wider than the original, so text that fitted its box no longer does. Use a common font or shorten the text.' },
      { q: 'Can I convert a PDF back into a PowerPoint deck?', a: 'Yes, with the PDF to PowerPoint tool. It rebuilds editable slides from the page content, which is an approximation rather than your original file.' },
    ],
    related: ['how-to-convert-pdf-to-powerpoint', 'how-to-convert-word-to-pdf-without-losing-formatting', 'how-to-fix-fonts-not-displaying-in-a-pdf'],
  },

  {
    slug: 'how-to-convert-html-to-pdf',
    title: 'How to Convert HTML to PDF (With the Design Intact)',
    description: 'Render HTML and CSS to a PDF that looks like the page rather than a wall of unstyled text — including how to control page breaks.',
    keyword: 'how to convert html to pdf',
    category: 'Converting',
    published: '2026-04-29',
    tool: 'html-to-pdf',
    blocks: [
      { type: 'p', text: 'Converting HTML to PDF means one thing: the design has to be built first, then captured. A converter that reads your markup as text and prints it produces something technically correct and visually useless.' },
      { type: 'h2', text: 'Convert HTML to PDF' },
      { type: 'steps', items: [
        'Open the HTML to PDF tool and paste your markup, or upload the .html file.',
        'Watch the live preview — that rendered view is what the PDF will contain.',
        'Adjust the markup or CSS until the preview looks right.',
        'Convert and download.',
      ] },
      { type: 'h2', text: 'Rendering, not printing the source' },
      { type: 'p', text: 'A good converter runs your HTML through a real layout engine: CSS is applied, boxes are laid out, fonts are measured, and the finished page is captured. That is why the preview matters — if it looks right in the preview, it will look right in the PDF, because they are the same render.' },
      { type: 'h2', text: 'What does not survive' },
      { type: 'table', head: ['Feature', 'In the PDF'], rows: [
        ['CSS layout, colours, typography', 'Rendered as designed'],
        ['Images referenced by URL', 'Included if reachable; inline data URIs are safest'],
        ['Web fonts', 'Applied if they load — embed or fall back to system fonts'],
        ['JavaScript-generated content', 'Only if the script has run before capture'],
        ['Hover and focus states', 'Not applicable — a page has no cursor'],
        ['Video and interactive embeds', 'Reduced to a still frame or blank space'],
      ] },
      { type: 'callout', title: 'Inline your assets', text: 'The most reliable HTML-to-PDF input is a single self-contained file: CSS in a style tag, images as data URIs. Anything fetched from elsewhere can fail to arrive before the capture, and a missing stylesheet turns your design into unstyled text.' },
      { type: 'h2', text: 'Controlling page breaks' },
      { type: 'p', text: 'A web page scrolls forever; a PDF has pages. Where the cut lands is decided by CSS, and a few properties give you control:' },
      { type: 'list', items: [
        'break-inside: avoid on a card or table row keeps it from being split down the middle.',
        'break-before: page forces a new page — useful before each section heading.',
        'Print styles in an @media print block let you hide navigation and adjust margins.',
        'A repeating table header via thead makes long tables readable across pages.',
      ] },
      { type: 'h2', text: 'Common uses' },
      { type: 'p', text: 'Invoices, certificates, reports and tickets are all HTML-to-PDF jobs: you build a template, fill it with data, and render. Doing the layout in HTML and CSS means the design lives in a language you already know rather than in a PDF drawing API.' },
    ],
    faqs: [
      { q: 'Why does my PDF look unstyled?', a: 'The CSS did not reach the renderer. External stylesheets can fail to load — inline the styles in a style tag and convert again.' },
      { q: 'Can I convert a live website URL to PDF?', a: 'This tool converts markup you provide. For a live page, use your browser\'s own Print to PDF, which renders the page exactly as you are seeing it.' },
      { q: 'How do I stop a table splitting across pages?', a: 'Apply break-inside: avoid to the rows or to the table, and put the header in a thead so it repeats on each page.' },
      { q: 'Do web fonts work?', a: 'If they load before capture. Safest is a system font stack, or the font embedded as a data URI in your CSS.' },
    ],
    related: ['how-to-convert-a-web-page-to-pdf', 'how-to-convert-word-to-pdf-without-losing-formatting', 'how-to-optimize-a-pdf-for-the-web'],
  },

  {
    slug: 'how-to-convert-a-web-page-to-pdf',
    title: 'How to Save a Web Page as a PDF',
    description: 'Capture an article, receipt or booking confirmation as a clean PDF — without the navigation, cookie banners and ads that usually come with it.',
    keyword: 'save web page as pdf',
    category: 'Converting',
    published: '2026-05-12',
    tool: 'html-to-pdf',
    blocks: [
      { type: 'p', text: 'Saving a page as PDF is how you keep a receipt, an order confirmation, a booking, or an article that might not be there next year. The difficulty is that a modern page carries a great deal you do not want to keep.' },
      { type: 'h2', text: 'The quickest route' },
      { type: 'steps', items: [
        'Open the page and press Ctrl+P, or Cmd+P on a Mac.',
        'Set the destination to Save as PDF.',
        'Dismiss cookie banners and pop-ups first — they print exactly as they appear.',
        'Check the preview, adjust margins or scale if content is being cut off, and save.',
      ] },
      { type: 'p', text: 'This works in every desktop browser, needs nothing installed, and renders the page as you are seeing it.' },
      { type: 'h2', text: 'Getting rid of the clutter' },
      { type: 'p', text: 'Print output on most sites is an afterthought, so you get the header, the sidebar, the newsletter prompt and a page of footer links. Two things help a great deal:' },
      { type: 'list', items: [
        'Reader mode — available in Safari, Firefox and Edge — strips a page down to the article text and images, and printing from it produces a genuinely clean document.',
        'Dismiss every overlay before printing. A cookie banner covering the first paragraph will cover it in the PDF too.',
      ] },
      { type: 'callout', title: 'Background colours are off by default', text: 'If your saved page has lost its dark theme or its coloured table rows, enable background graphics in the print dialogue. It is off by default to save ink, and it changes the result substantially.' },
      { type: 'h2', text: 'Pages that will not print properly' },
      { type: 'table', head: ['Problem', 'What to do'], rows: [
        ['Only the first page saves', 'Content is in a fixed-height scrolling box; try reader mode'],
        ['Images missing', 'They load lazily — scroll the whole page first so everything loads'],
        ['Text cut off at the right', 'Switch to landscape or reduce the print scale'],
        ['Endless blank pages', 'A tall empty element; reader mode usually removes it'],
      ] },
      { type: 'h2', text: 'When you need it to look like your own design' },
      { type: 'p', text: 'If you control the markup — an invoice template, a certificate, a report you generate — you get a far better result by rendering your own HTML to PDF rather than printing someone\'s page. You choose the page size, the margins and where the breaks fall, instead of negotiating with a stylesheet written for screens.' },
      { type: 'h2', text: 'Make the archive worth having' },
      { type: 'p', text: 'A saved page is only useful if you can find it again. Give the file a name that says what it is and when — "flight-booking-2026-09-14.pdf" rather than "document.pdf" — and run OCR if what you saved turned out to be an image rather than text.' },
    ],
    faqs: [
      { q: 'How do I save a web page as a PDF on my phone?', a: 'In Safari, use the share sheet and pick Options → PDF before saving to Files. In Chrome on Android, use Share → Print and choose Save as PDF.' },
      { q: 'Why is my saved page missing its colours?', a: 'Background graphics are disabled by default in the print dialogue. Turn them on.' },
      { q: 'Can I save a page that needs a login?', a: 'Yes — print while you are logged in. The browser prints what you can see.' },
      { q: 'How do I remove ads from the saved PDF?', a: 'Print from reader mode, which strips the page to its article content before rendering.' },
    ],
    related: ['how-to-convert-html-to-pdf', 'how-to-convert-an-email-to-pdf', 'how-to-compress-a-pdf-without-losing-quality'],
  },
];
