import type { BlogPost } from '../types';

export const convertingToPdfPosts2: BlogPost[] = [
  {
    slug: 'how-to-convert-a-photo-to-pdf-on-your-phone',
    title: 'How to Convert a Photo to PDF on Your Phone',
    description: 'Turn a photographed document into a proper PDF from an iPhone or Android — including how to make it look scanned rather than snapped.',
    keyword: 'convert photo to pdf on phone',
    category: 'Converting',
    published: '2026-05-26',
    tool: 'jpg-to-pdf',
    blocks: [
      { type: 'p', text: 'Photographing a document and sending the picture is fine between friends and unacceptable almost everywhere else. Landlords, employers, banks and schools all want a PDF, and a photo of a page is not one.' },
      { type: 'h2', text: 'Convert a photo to PDF' },
      { type: 'steps', items: [
        'Open the JPG to PDF tool in your phone browser.',
        'Tap the upload area and choose the photos from your camera roll.',
        'Order them if you have several — they become pages in that order.',
        'Convert. The PDF saves to Files on iOS, or Downloads on Android.',
      ] },
      { type: 'p', text: 'Because the conversion runs in the browser, the photo never leaves your phone. Given that the photos people convert are usually passports, payslips and bank statements, that is worth caring about.' },
      { type: 'h2', text: 'Capture it properly first' },
      { type: 'p', text: 'No converter can fix a bad photograph, so spend the extra ten seconds at the capture stage:' },
      { type: 'list', items: [
        'Use your phone\'s document scanner rather than the plain camera — Notes on iPhone, Google Drive on Android. Both crop to the page and correct the perspective.',
        'Put the page on a dark surface so the edges are detected cleanly.',
        'Get light from the side rather than overhead, so your own shadow is not across the page.',
        'Hold the phone parallel to the page, not tilted over it.',
        'Fill the frame with the document; cropping later throws away resolution.',
      ] },
      { type: 'callout', title: 'Scanner mode is the whole trick', text: 'The difference between a photo of a page and a scan of a page is perspective correction and contrast. Both built-in scanners do it automatically and export a PDF directly — often you will not need a converter at all.' },
      { type: 'h2', text: 'Several photos, one document' },
      { type: 'p', text: 'A three-page tenancy agreement should arrive as one three-page PDF, not three attachments. Add all the images at once and choose the single-document option; check the page order before you convert, because the phone gallery does not always hand them over in the order you took them.' },
      { type: 'h2', text: 'Getting the size down' },
      { type: 'p', text: 'A modern phone camera produces 3–5 MB per photo, so a five-page document arrives at 20 MB and bounces off half the upload forms it is aimed at. Compress the finished PDF — for a photographed document the reduction is dramatic and the text stays perfectly readable.' },
      { type: 'h2', text: 'Make it searchable' },
      { type: 'p', text: 'A photographed page contains no text as far as any computer is concerned. Run OCR over the finished PDF and it becomes searchable and copyable while looking identical — which is what turns a snapshot into an archive you can use.' },
    ],
    faqs: [
      { q: 'How do I scan a document with my phone?', a: 'iPhone: Notes → new note → camera icon → Scan Documents. Android: Google Drive → + → Scan. Both crop, square up the page and export a PDF.' },
      { q: 'Can I put several photos into one PDF?', a: 'Yes. Add them all to the converter and pick the single-document option, checking the page order first.' },
      { q: 'Why is my photo PDF so large?', a: 'Phone cameras produce large images and conversion embeds them at full resolution. Compress the PDF afterwards.' },
      { q: 'Do HEIC photos work?', a: 'Yes — they are decoded during conversion. The one re-encode involved is not visible at normal sizes.' },
    ],
    related: ['how-to-convert-jpg-to-pdf', 'how-to-convert-a-scanned-document-to-pdf', 'how-to-make-a-scanned-pdf-searchable'],
  },

  {
    slug: 'how-to-convert-a-scanned-document-to-pdf',
    title: 'How to Convert a Scanned Document to a Searchable PDF',
    description: 'Take scans or images of paper and produce a PDF you can search, copy from and file — with the right settings at every step.',
    keyword: 'convert scanned document to pdf',
    category: 'Converting',
    published: '2026-06-09',
    tool: 'ocr-pdf',
    blocks: [
      { type: 'p', text: 'A scan is a photograph of a page. It looks like a document and behaves like a picture: you cannot search it, you cannot copy a line out of it, and a screen reader finds nothing on it. OCR is what closes that gap.' },
      { type: 'h2', text: 'From paper to searchable PDF' },
      { type: 'steps', items: [
        'Scan or photograph the pages. 300 DPI greyscale is right for ordinary printed text.',
        'Convert images to PDF if your scanner produced JPGs rather than a PDF.',
        'Merge the pages into one document if they came out separately.',
        'Remove blank pages and rotate anything sideways.',
        'Run OCR to add a text layer.',
        'Compress last, once everything else is settled.',
      ] },
      { type: 'h2', text: 'Scanner settings that matter' },
      { type: 'table', head: ['Setting', 'Recommended', 'Why'], rows: [
        ['Resolution', '300 DPI', 'Below 200 the OCR accuracy falls away; above 400 adds size, not accuracy'],
        ['Colour mode', 'Greyscale', 'Roughly a third the size of colour with no loss on black-and-white originals'],
        ['Format', 'PDF or JPEG', 'TIFF is enormous and rarely needed'],
        ['Straightening', 'On', 'Skewed text is the single biggest cause of OCR errors'],
      ] },
      { type: 'callout', title: 'Colour only when the colour means something', text: 'Scan in colour for a document with a coloured logo, a highlighted clause or a signature in blue ink you need to prove was ink. For plain printed text it triples the file size and improves nothing.' },
      { type: 'h2', text: 'What OCR actually does' },
      { type: 'p', text: 'OCR reads the picture, recognises the shapes as characters, and writes an invisible text layer positioned exactly over the visible image. The page still looks like the scan — the original picture is untouched — but a search now finds words, and selecting text copies real characters.' },
      { type: 'p', text: 'It is not perfect. Clean printed text at 300 DPI is recognised extremely well; a faint fax, a handwritten note or a dense table with faint rules will produce errors. Always spot-check by searching for a word you know appears in the document.' },
      { type: 'h2', text: 'Why the order matters' },
      { type: 'p', text: 'OCR reads the image as it is at the time you run it. Compress first and you have OCR reading a degraded picture, which produces more mistakes than necessary. Do every lossless step first, run OCR, then compress — the text layer is unaffected by compression because it is text, not image.' },
    ],
    faqs: [
      { q: 'What DPI should I scan at?', a: '300 DPI for text. Higher adds file size without helping recognition; lower starts to cost you accuracy.' },
      { q: 'Can OCR read handwriting?', a: 'Not reliably. It is built for printed characters. Neat block capitals sometimes work; ordinary cursive does not.' },
      { q: 'Does OCR change how my scan looks?', a: 'No. The text layer is invisible and sits behind the image. The page looks exactly the same.' },
      { q: 'Should I OCR before or after compressing?', a: 'Before. OCR on a compressed image makes more mistakes, and compressing afterwards does not damage the text layer.' },
    ],
    related: ['how-to-make-a-scanned-pdf-searchable', 'how-to-combine-scanned-documents-into-one-pdf', 'how-to-compress-a-scanned-pdf'],
  },

  {
    slug: 'how-to-convert-csv-to-pdf',
    title: 'How to Convert a CSV to PDF',
    description: 'Turn raw comma-separated data into a readable PDF table — handling wide files, long files, and the formatting a CSV does not carry.',
    keyword: 'how to convert csv to pdf',
    category: 'Converting',
    published: '2026-06-23',
    tool: 'excel-to-pdf',
    blocks: [
      { type: 'p', text: 'A CSV is data with no opinions about presentation. Converting it to PDF means someone has to decide the column widths, the page breaks and where the header goes — and if nobody decides deliberately, the defaults will decide badly.' },
      { type: 'h2', text: 'Convert a CSV' },
      { type: 'steps', items: [
        'Open the Excel to PDF tool — it reads CSV as well as XLSX.',
        'Add your file. The rows and columns are laid out as a table.',
        'Choose landscape if you have more than about eight columns.',
        'Convert, and check the last column made it onto the page.',
      ] },
      { type: 'h2', text: 'What a CSV does not contain' },
      { type: 'p', text: 'It is worth being clear about this, because people are often surprised by the plainness of the output. A CSV has no fonts, no colours, no column widths, no number formats and no notion of a header row. It is text separated by commas. Everything about how the PDF looks is added during conversion.' },
      { type: 'p', text: 'That is also why dates and long numbers sometimes come out oddly: 0044 loses its leading zeros unless the field was quoted, and 03/04 is ambiguous between March and April. Both are properties of the CSV, not faults in the conversion.' },
      { type: 'h2', text: 'Wide files' },
      { type: 'list', items: [
        'Use landscape orientation before anything else.',
        'Drop columns the reader does not need — a CSV export usually carries internal IDs nobody wants.',
        'Shorten headers; the column name is often longer than any value beneath it.',
        'If it is still too wide, split it into two logical tables rather than shrinking the type until it cannot be read.',
      ] },
      { type: 'callout', title: 'Repeat the header row', text: 'A long table across twelve pages is unreadable if the column names only appear on page one. Make sure the header repeats — it is the single biggest improvement you can make to a converted data table.' },
      { type: 'h2', text: 'Format it before converting, if it matters' },
      { type: 'p', text: 'For anything going to a client or a regulator, open the CSV in a spreadsheet first, format it properly — bold the header, set number formats, widen the columns to fit — and convert the spreadsheet instead. Thirty seconds of formatting is the difference between a data dump and a document.' },
      { type: 'h2', text: 'The opposite direction' },
      { type: 'p', text: 'If you have a PDF containing a table and you need the data, that is PDF to Excel, which reads the table structure back out into cells you can work with. Converting a CSV to PDF and back is lossy in both directions and should be avoided when you still have the original data.' },
    ],
    faqs: [
      { q: 'Why do my leading zeros disappear?', a: 'They were read as numbers. Quote those fields in the CSV, or format the column as text in a spreadsheet before converting.' },
      { q: 'Can I convert a very large CSV?', a: 'Yes, but a hundred-thousand-row PDF is not a useful document. Filter or summarise the data first — a PDF is for reading, not for storage.' },
      { q: 'How do I keep the table on one page?', a: 'Reduce the number of columns and rows. Scaling a large table down to fit usually makes it illegible rather than compact.' },
      { q: 'Does the CSV delimiter matter?', a: 'Yes. Files exported in some European locales use semicolons. If every row lands in a single column, that is why.' },
    ],
    related: ['how-to-convert-excel-to-pdf-without-cutting-off-columns', 'how-to-convert-pdf-to-excel-with-tables', 'how-to-export-pdf-tables-to-csv'],
  },

  {
    slug: 'how-to-convert-an-email-to-pdf',
    title: 'How to Convert an Email to PDF',
    description: 'Save an email as a PDF that works as a record — with the sender, recipients, full timestamp and its attachments included rather than left behind.',
    keyword: 'how to convert email to pdf',
    category: 'Converting',
    published: '2026-07-07',
    tool: 'merge-pdf',
    blocks: [
      { type: 'p', text: 'Emails get saved as PDFs for a reason: a record of what was agreed, a receipt for an expense claim, evidence for a dispute. Which means the details around the message matter as much as the message.' },
      { type: 'h2', text: 'The direct route' },
      { type: 'steps', items: [
        'Open the email in your mail client or webmail.',
        'Press Ctrl+P, or Cmd+P on a Mac.',
        'Set the destination to Save as PDF.',
        'Check the preview shows the sender, recipients, subject and full date before you save.',
      ] },
      { type: 'p', text: 'Gmail, Outlook on the web and Apple Mail all support this, and printing from the message view rather than the inbox list is what gets you the headers.' },
      { type: 'h2', text: 'Keep the details that make it evidence' },
      { type: 'p', text: 'A PDF containing only the body text proves very little. What gives an email record weight is the metadata printed alongside it:' },
      { type: 'list', items: [
        'From and To addresses in full, not just display names.',
        'The complete date and time, including the year.',
        'The subject line.',
        'CC recipients, where they are relevant to who knew what.',
        'The quoted thread beneath, if the context depends on it.',
      ] },
      { type: 'callout', title: 'Expand the thread first', text: 'Mail clients collapse quoted replies to a "..." button. Printed, that is what you get — a dash where the history should be. Expand every collapsed section before printing.' },
      { type: 'h2', text: 'Attachments' },
      { type: 'p', text: 'Printing an email does not include what was attached to it; you get a filename at best. Save the attachments separately, convert any that are not already PDFs, and merge them onto the end of the email PDF. That produces one file containing the message and everything it carried — which is what an auditor or a solicitor actually wants.' },
      { type: 'h2', text: 'Saving a whole thread' },
      { type: 'p', text: 'For a long exchange, print each message separately and merge them in date order. It is more work than printing the collapsed thread view, but the result reads cleanly and nothing is hidden behind an expander. Number the pages afterwards so the sequence can be referred to.' },
      { type: 'h2', text: 'On a phone' },
      { type: 'p', text: 'In the iOS Mail app, use the share sheet, choose Print, then pinch outwards on the print preview — that gesture turns the preview into a PDF you can save or share. On Android, Gmail\'s overflow menu has a Print option that offers Save as PDF.' },
    ],
    faqs: [
      { q: 'Does printing an email to PDF include the attachments?', a: 'No. Save and convert them separately, then merge them onto the end of the email PDF.' },
      { q: 'How do I include the full headers?', a: 'Print from the open message rather than the list view. For technical headers such as message IDs, use your client\'s "show original" view and print that as well.' },
      { q: 'Can a PDF of an email be used as evidence?', a: 'It is commonly accepted as a record, and its weight depends on completeness — full headers, full timestamps, unedited content. For formal proceedings, ask what format is required.' },
      { q: 'How do I save a whole conversation?', a: 'Print each message, then merge them in date order and add page numbers.' },
    ],
    related: ['how-to-convert-a-web-page-to-pdf', 'how-to-merge-pdf-files', 'how-to-add-page-numbers-to-a-pdf'],
  },

  {
    slug: 'how-to-create-a-pdf-from-multiple-file-types',
    title: 'How to Create One PDF From Word, Excel, Images and Slides',
    description: 'Build a single PDF pack from mixed file types — the order of operations that avoids re-doing work and keeps every document readable.',
    keyword: 'create pdf from multiple file types',
    category: 'Converting',
    published: '2026-07-21',
    tool: 'merge-pdf',
    blocks: [
      { type: 'p', text: 'Application packs, tender submissions and case files are always a mix: a Word cover letter, a spreadsheet of figures, a scanned certificate, a few photos, a deck. The recipient wants one PDF.' },
      { type: 'h2', text: 'The order that saves you work' },
      { type: 'steps', items: [
        'Convert every non-PDF file to PDF individually, so everything is the same format.',
        'Fix each converted file before merging — rotate, remove blanks, check nothing was cut off.',
        'Decide the reading order and rename the files with a numeric prefix so the order is obvious.',
        'Merge them all in that order.',
        'Add page numbers across the combined document.',
        'Compress once, at the end.',
      ] },
      { type: 'p', text: 'The instinct is to merge first and fix afterwards. Resist it: a problem inside a 90-page merged pack is much harder to correct than the same problem in the 4-page file it came from.' },
      { type: 'h2', text: 'Which converter for which file' },
      { type: 'table', head: ['You have', 'Use', 'Watch for'], rows: [
        ['.docx', 'Word to PDF', 'Font substitution shifting the page breaks'],
        ['.xlsx or .csv', 'Excel to PDF', 'Wide tables losing their right-hand columns'],
        ['.pptx', 'PowerPoint to PDF', 'Long titles overlapping after a font substitution'],
        ['.jpg, .png, .heic', 'JPG to PDF', 'Page size and orientation'],
        ['Scans', 'JPG to PDF, then OCR', 'Sideways pages and blank versos'],
        ['A web page', 'Print to PDF from the browser', 'Cookie banners printing with the content'],
      ] },
      { type: 'callout', title: 'Number the files before you merge', text: 'Prefix them 01-, 02-, 03-. It takes a minute, it makes the correct order self-evident when you add them to the merge tool, and it is the difference between a pack in the right sequence and a re-do.' },
      { type: 'h2', text: 'Making the pack navigable' },
      { type: 'p', text: 'A 90-page combined document with no signposts is hard to use. Two additions do most of the work: page numbers running across the whole pack, so anyone can refer to "page 47", and a contents page listing each section and where it starts, created after the merge when you know the real page numbers.' },
      { type: 'h2', text: 'Before you send it' },
      { type: 'list', items: [
        'Check the page count matches the sum of the parts.',
        'Confirm every section is present and in the right order.',
        'Check the file size against the recipient\'s limit — compress if it is close.',
        'Look for anything internal that should not be in there: draft watermarks, comment boxes, working columns.',
        'Give the file a name that identifies it: applicant, subject and date, not "merged.pdf".',
      ] },
    ],
    faqs: [
      { q: 'Can I merge a Word file directly into a PDF?', a: 'No. Convert it to PDF first; merging only works between PDFs.' },
      { q: 'What order should the pack be in?', a: 'Whatever the recipient specified, exactly. If nothing was specified, cover letter first, then the main documents, then appendices and supporting evidence.' },
      { q: 'Should I compress before or after merging?', a: 'After. One compression pass on the finished pack, so nothing is degraded twice.' },
      { q: 'How do I add a table of contents?', a: 'Build it after merging, when the page numbers are settled, and merge it onto the front as a single page.' },
    ],
    related: ['how-to-merge-pdf-files', 'how-to-add-page-numbers-to-a-pdf', 'how-to-convert-word-to-pdf-without-losing-formatting'],
  },
];
