import type { BlogPost } from '../types';

export const editingPosts2: BlogPost[] = [
  {
    slug: 'how-to-add-page-numbers-to-a-pdf',
    title: 'How to Add Page Numbers to a PDF',
    description: 'Number the pages of a merged pack or a scanned bundle — where to put them, what format to use, and how to handle documents that are already numbered.',
    keyword: 'how to add page numbers to a pdf',
    category: 'Editing & Signing',
    published: '2026-03-22',
    tool: 'add-page-numbers',
    blocks: [
      { type: 'p', text: 'Page numbers are what let anyone refer to "page 47" and have everyone find the same page. On a merged pack assembled from a dozen sources, they are the difference between a usable bundle and a pile of paper.' },
      { type: 'h2', text: 'Add page numbers' },
      { type: 'steps', items: [
        'Open the Add Page Numbers tool and add your PDF.',
        'Choose the position — bottom centre or bottom right are the conventions.',
        'Choose the format: plain numbers, or "Page 3 of 60".',
        'Set the starting number if the document has front matter that should not count.',
        'Apply and check a few pages across the document.',
      ] },
      { type: 'h2', text: 'Where to put them' },
      { type: 'table', head: ['Position', 'Suits'], rows: [
        ['Bottom centre', 'Reports and anything read on screen — the default for a reason'],
        ['Bottom right', 'Single-sided printing; the eye lands there when turning'],
        ['Bottom outer', 'Double-sided printing, alternating left and right'],
        ['Top right', 'Legal bundles and documents with footnotes at the foot'],
      ] },
      { type: 'callout', title: 'Check the margins first', text: 'A scanned document with almost no bottom margin will have its page numbers landing on the text. Page through the file and look at the bottom edge before choosing a position.' },
      { type: 'h2', text: 'Documents that are already numbered' },
      { type: 'p', text: 'This is the awkward case. A merged pack where each source document carries its own numbering ends up with two sets of numbers, which is worse than none. Two ways out:' },
      { type: 'list', items: [
        'Place the new numbers somewhere the old ones are not — top right, when the originals are at the foot. Label them clearly, as legal bundles do.',
        'Cover the old numbers before adding new ones, if the layout allows it.',
      ] },
      { type: 'p', text: 'For a court bundle or a tender submission, continuous numbering across the whole pack is usually required regardless of what the individual documents say.' },
      { type: 'h2', text: 'Starting from a different number' },
      { type: 'p', text: 'A cover page and a contents page normally should not be numbered, or should be numbered separately. Set the numbering to begin on the first page of the body, so that printed page 1 is the page a reader would call page 1.' },
      { type: 'h2', text: 'Numbers are drawn onto the page' },
      { type: 'p', text: 'They become part of the page content, which means reordering or deleting pages afterwards leaves the numbering wrong. Get the document into its final order first, then number it — that sequence saves re-doing the work.' },
    ],
    faqs: [
      { q: 'Can I skip numbering the cover page?', a: 'Yes. Set the numbering to start on a later page, and choose whether the skipped pages still count towards the total.' },
      { q: 'What if pages are already numbered?', a: 'Place the new numbers elsewhere on the page and label them, or cover the originals. Two competing sets of numbers is the outcome to avoid.' },
      { q: 'Will the numbers print?', a: 'Yes — they are part of the page content, not an annotation.' },
      { q: 'Can I number only some pages?', a: 'Yes, by specifying a range. Useful when appendices are numbered separately.' },
    ],
    related: ['how-to-add-a-header-and-footer-to-a-pdf', 'how-to-merge-pdf-files', 'how-to-create-a-pdf-from-multiple-file-types'],
  },

  {
    slug: 'how-to-crop-a-pdf',
    title: 'How to Crop a PDF',
    description: 'Trim margins, remove scanner edges or cut a page down to one region — and understand why cropping hides content rather than deleting it.',
    keyword: 'how to crop a pdf',
    category: 'Editing & Signing',
    published: '2026-04-14',
    tool: 'crop-pdf',
    blocks: [
      { type: 'p', text: 'Cropping changes the visible area of a page. It is the fix for scanner shadows, oversized margins and pages that carry a strip of the next document down one side.' },
      { type: 'h2', text: 'Crop a PDF' },
      { type: 'steps', items: [
        'Open the Crop PDF tool and add your document.',
        'Drag the crop boundary on the page preview.',
        'Apply the same crop to every page, or crop individually where pages differ.',
        'Check the result, then download.',
      ] },
      { type: 'h2', text: 'What cropping actually does' },
      { type: 'p', text: 'A PDF page has several boxes, and cropping sets the CropBox — the region a reader displays. The content outside it is still in the file, untouched. Changing the CropBox back reveals it again.' },
      { type: 'callout', title: 'Cropping is not redaction', text: 'Anything cropped away is still in the document and can be recovered by anyone who resets the crop. If information must be gone, redact it.' },
      { type: 'h2', text: 'When cropping is the right tool' },
      { type: 'list', items: [
        'Removing the black or grey border a scanner adds around a page.',
        'Trimming excessive white margins so a document reads better on a phone.',
        'Cutting a page down to a single chart or table for reuse.',
        'Removing a strip of an adjacent page captured in a book scan.',
        'Standardising a mixed batch to a consistent visible size.',
      ] },
      { type: 'h2', text: 'Cropping for phone reading' },
      { type: 'p', text: 'A4 pages with generous margins are unpleasant on a phone, because the text column ends up small. Cropping the margins away can increase the effective text size by a third without changing the document at all — one of the more satisfying small improvements you can make to a document you have to read on the move.' },
      { type: 'h2', text: 'Pages that are not all the same' },
      { type: 'p', text: 'A single crop applied to a mixed document will cut into some pages and leave borders on others. Where pages differ — a landscape chart among portrait text, or a scan where the paper moved — crop those pages individually. It is slower and it is the only way to get a clean result.' },
      { type: 'h2', text: 'Printing a cropped document' },
      { type: 'p', text: 'A cropped page prints at its cropped size, which may not match the paper. Scale to fit in the print dialogue, or expect a smaller image centred on the sheet.' },
    ],
    faqs: [
      { q: 'Does cropping reduce file size?', a: 'Barely. The content is still there; only the visible area changed.' },
      { q: 'Can cropping be undone?', a: 'Yes — the crop can be reset, which is exactly why it is not a privacy control.' },
      { q: 'Can I crop pages differently?', a: 'Yes. Apply per-page crops where the pages are not consistent.' },
      { q: 'Will a cropped PDF print correctly?', a: 'It prints at the cropped size. Use scale-to-fit if you want it to fill the paper.' },
    ],
    related: ['how-to-permanently-remove-text-from-a-pdf', 'how-to-rotate-a-pdf-and-save-it', 'how-to-compress-a-scanned-pdf'],
  },

  {
    slug: 'how-to-edit-a-pdf-without-adobe',
    title: 'How to Edit a PDF Without Adobe Acrobat',
    description: 'Most PDF edits do not need a subscription. Which jobs a browser tool handles, which need a word processor, and which genuinely need Acrobat.',
    keyword: 'how to edit a pdf without adobe',
    category: 'Editing & Signing',
    published: '2026-05-06',
    tool: 'organize-pdf',
    blocks: [
      { type: 'p', text: '"Editing a PDF" covers a dozen unrelated tasks. Most of them are straightforward with free tools; a couple genuinely need professional software; and one — rewriting body text — is difficult by the nature of the format rather than by anyone\'s choice.' },
      { type: 'h2', text: 'What you can do in a browser, free' },
      { type: 'table', head: ['Task', 'Tool'], rows: [
        ['Merge or split', 'Merge PDF, Split PDF'],
        ['Delete, extract or reorder pages', 'Remove Pages, Extract Pages, Organize PDF'],
        ['Rotate pages', 'Rotate PDF'],
        ['Add a signature', 'Sign PDF'],
        ['Add page numbers or a watermark', 'Add Page Numbers, Add Watermark'],
        ['Redact', 'Redact PDF'],
        ['Compress or optimise', 'Compress PDF, Optimize PDF'],
        ['Convert to and from other formats', 'The conversion tools'],
        ['Add or remove a password', 'Protect PDF, Unlock PDF'],
        ['Crop pages', 'Crop PDF'],
      ] },
      { type: 'p', text: 'That is the great majority of what people mean when they ask to edit a PDF, and none of it requires a subscription.' },
      { type: 'h2', text: 'Rewriting the text itself' },
      { type: 'p', text: 'This is the genuinely hard one, and it is hard because of the format. A PDF stores glyphs at coordinates, not paragraphs. Changing a word means the line no longer fits, and nothing in the file describes how the text should re-wrap.' },
      { type: 'p', text: 'Your options, in order of preference:' },
      { type: 'steps', items: [
        'Edit the original document — the Word file, the InDesign file — and export again. Always the best answer when it exists.',
        'Convert to Word, edit there, and export back to PDF. Good for text-led documents; expect layout drift on designed ones.',
        'Use a PDF editor with direct text editing. Works for short changes within a line; longer edits break the layout.',
        'Cover and replace: white box over the old text, new text on top. Crude, effective for a single figure, and it leaves the original text underneath — which matters if the content is sensitive.',
      ] },
      { type: 'callout', title: 'Look for the source first', text: 'The fastest way to edit a PDF is usually to not edit the PDF. Someone generated it from something, and that something is far easier to change.' },
      { type: 'h2', text: 'What Acrobat is genuinely for' },
      { type: 'p', text: 'Preflight for commercial printing, colour separation and profile management, accessibility tagging and remediation, building complex interactive forms with validation, and certificate-based digital signatures at scale. If your work involves those, it earns its price. If you are merging two files and adding a signature, it does not.' },
      { type: 'h2', text: 'Free desktop options' },
      { type: 'list', items: [
        'Preview on macOS — pages, annotations, signatures, basic compression.',
        'LibreOffice Draw — opens PDFs for direct editing, with layout results that vary.',
        'Firefox\'s built-in viewer — filling forms and adding signatures.',
        'Command-line tools — powerful, scriptable, and a learning curve.',
      ] },
    ],
    faqs: [
      { q: 'Can I edit a PDF for free?', a: 'Most editing tasks, yes. Rewriting body text is the hard case and is difficult in any tool.' },
      { q: 'Why is editing PDF text so awkward?', a: 'Because a PDF stores positioned glyphs rather than paragraphs. There is no text flow to re-wrap.' },
      { q: 'Is Acrobat worth the subscription?', a: 'For prepress, accessibility remediation and complex forms, yes. For everyday page-level work, no.' },
      { q: 'What is the best free PDF editor?', a: 'It depends on the task. Browser tools for page operations and signing; a word processor round trip for text-heavy rewriting.' },
    ],
    related: ['how-to-add-text-to-a-pdf', 'how-to-convert-pdf-to-word-without-losing-formatting', 'how-to-reduce-pdf-size-without-adobe'],
  },

  {
    slug: 'how-to-add-text-to-a-pdf',
    title: 'How to Add Text to a PDF',
    description: 'Write on a PDF — filling a flat form, annotating a drawing, correcting a figure — and make it look like it belongs on the page.',
    keyword: 'how to add text to a pdf',
    category: 'Editing & Signing',
    published: '2026-05-20',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'Adding text to a PDF means placing new text on top of the existing page. It is a different operation from editing the text that is already there, and it is far more reliable.' },
      { type: 'h2', text: 'When adding text is the right approach' },
      { type: 'list', items: [
        'Completing a flat form that has no interactive fields.',
        'Writing a date beside a signature.',
        'Annotating a drawing or a plan with measurements.',
        'Adding a reference number or a file marker.',
        'Correcting a single figure by covering it and writing over.',
      ] },
      { type: 'h2', text: 'Making it look right' },
      { type: 'table', head: ['Setting', 'Guidance'], rows: [
        ['Font', 'Match the document, or use a plain sans-serif for annotation'],
        ['Size', 'Match the body text; 10–12pt on an A4 document'],
        ['Colour', 'Black to blend in, blue or red to stand out as an annotation'],
        ['Alignment', 'Sit on the line, not above or below it'],
        ['Spacing', 'Leave clear space around it, as the printed text has'],
      ] },
      { type: 'p', text: 'Deciding whether the addition should blend in or stand out is the first question. Form answers should look like they belong. Review comments should be obviously additions.' },
      { type: 'callout', title: 'Covered text is still readable', text: 'Putting a white box over a figure and typing a new one leaves the old value in the file. Anyone can copy it out. For a correction that is often fine; for anything sensitive, redact instead.' },
      { type: 'h2', text: 'Getting alignment right' },
      { type: 'p', text: 'Text that sits slightly above or below the line it belongs on is the tell that a form was completed digitally by someone in a hurry. Zoom in to 200% before placing, use any snapping the tool offers, and check the whole page at 100% afterwards — errors that are invisible zoomed in are obvious zoomed out.' },
      { type: 'h2', text: 'Flatten it before sending' },
      { type: 'p', text: 'Text added as an annotation can be moved or deleted by the recipient, and in some readers it does not print. Flattening draws it permanently into the page, which is what you want for anything being submitted.' },
      { type: 'h2', text: 'When to rewrite instead' },
      { type: 'p', text: 'If you are adding more than a few lines, or replacing a paragraph, you are past what layering text sensibly handles. Convert to Word, edit properly, and export — the result reads as a document rather than as a patched one.' },
    ],
    faqs: [
      { q: 'Can I change existing text in a PDF?', a: 'Not easily. Adding new text on top is reliable; editing the original requires a PDF editor or a round trip through Word.' },
      { q: 'Why does my added text not print?', a: 'It is an annotation rather than page content. Flatten the document and it will print everywhere.' },
      { q: 'How do I match the document font?', a: 'Check the document properties for the fonts it uses, or pick a close standard face. An exact match is not usually necessary for annotations.' },
      { q: 'Can the recipient delete my added text?', a: 'If it is an annotation, yes. Flatten it first.' },
    ],
    related: ['how-to-fill-out-a-pdf-form', 'how-to-flatten-a-pdf', 'how-to-edit-a-pdf-without-adobe'],
  },

  {
    slug: 'how-to-add-a-header-and-footer-to-a-pdf',
    title: 'How to Add a Header and Footer to a PDF',
    description: 'Stamp a document title, reference number, date or confidentiality notice across every page — without covering the content underneath.',
    keyword: 'add header and footer to pdf',
    category: 'Editing & Signing',
    published: '2026-06-11',
    tool: 'add-watermark',
    blocks: [
      { type: 'p', text: 'Headers and footers carry the information that has to be on every page: what the document is, which version, which matter, who it belongs to. On a merged pack they are often the only thing tying the pages together.' },
      { type: 'h2', text: 'What to put there' },
      { type: 'table', head: ['Position', 'Typical content'], rows: [
        ['Header left', 'Document title or matter name'],
        ['Header right', 'Version, date or reference number'],
        ['Footer left', 'Confidentiality notice'],
        ['Footer centre', 'Page numbers'],
        ['Footer right', 'Filename or document ID'],
      ] },
      { type: 'p', text: 'Resist filling all five. Two or three pieces of information read as professional; five read as clutter and get ignored.' },
      { type: 'h2', text: 'Adding them' },
      { type: 'steps', items: [
        'Open the Add Watermark tool and add your PDF — header and footer text is placed the same way.',
        'Position the text at the top or bottom margin.',
        'Set the size small — 8 to 9pt, smaller than the body text.',
        'Apply, then check pages with content close to the edge.',
      ] },
      { type: 'callout', title: 'Check the margins on every kind of page', text: 'Scans, landscape pages and full-bleed images all have less margin than a typical text page. A header that sits neatly on page 1 can land on a chart on page 30.' },
      { type: 'h2', text: 'Documents that already have them' },
      { type: 'p', text: 'A merged pack from several sources usually arrives with several different headers already in place. Adding another produces a stack. Either place yours where the existing ones are not, or accept the originals and add only a page number — on a bundle, continuous numbering is what actually gets used.' },
      { type: 'h2', text: 'Confidentiality notices' },
      { type: 'p', text: 'A footer saying "Confidential — not for distribution" sets expectations and supports a later argument that the recipient knew. It does not restrict anything technically. Pair it with actual controls — encryption, a per-recipient watermark — if the content warrants them.' },
      { type: 'h2', text: 'Get the document final first' },
      { type: 'p', text: 'Headers and footers become part of the page. Reordering or deleting pages afterwards leaves them saying the wrong things, particularly where they carry section names. Finalise the document, then stamp it.' },
      { type: 'h2', text: 'Keeping it consistent across a pack' },
      { type: 'p', text: 'On a merged bundle assembled from several sources, consistency is the point. One header format, one footer format, applied to the whole document after merging, is what makes a pack read as a single document rather than as a stack of other people\'s files.' },
      { type: 'p', text: 'Apply it last, after the pages are in final order, and use the same wording throughout — including on the pages that already had their own headers, where yours will simply sit in a different position.' },
      { type: 'h2', text: 'Legal and formal bundles' },
      { type: 'p', text: 'Court bundles and tender submissions usually specify exactly what must appear and where: a bundle reference, continuous pagination, sometimes a tab number. Where a specification exists, follow it precisely rather than applying house style — non-compliant pagination is a common reason for a bundle to be sent back.' },
    ],
    faqs: [
      { q: 'Can I add different headers to different pages?', a: 'Yes, by applying to page ranges — useful when appendices need their own label.' },
      { q: 'What size should header text be?', a: '8–9pt. Smaller than the body text, so it reads as furniture rather than content.' },
      { q: 'Will it overlap my content?', a: 'It can, on pages with narrow margins. Check the whole document, not just the first page.' },
      { q: 'Is a confidentiality footer legally meaningful?', a: 'It evidences that the recipient was told. It does not prevent anything on its own.' },
    ],
    related: ['how-to-add-page-numbers-to-a-pdf', 'how-to-add-a-watermark-to-a-pdf', 'how-to-create-a-pdf-from-multiple-file-types'],
  },

  {
    slug: 'how-to-annotate-a-pdf',
    title: 'How to Annotate a PDF',
    description: 'Highlight, comment and mark up a PDF for review — and know which annotations survive when the file reaches someone else.',
    keyword: 'how to annotate a pdf',
    category: 'Editing & Signing',
    published: '2026-06-25',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'Annotating is how documents get reviewed: a highlight on a clause, a note asking a question, a strike-through on a paragraph that should go. The annotations sit on top of the page rather than in it, which explains most of their behaviour.' },
      { type: 'h2', text: 'The annotation types' },
      { type: 'table', head: ['Type', 'Use it for'], rows: [
        ['Highlight', 'Marking text that matters without saying anything about it'],
        ['Sticky note', 'A comment attached to a point on the page'],
        ['Text box', 'A comment that should be visible without clicking'],
        ['Strike-through', 'Marking text for deletion'],
        ['Underline', 'Emphasis, where a highlight would be too loud'],
        ['Drawing', 'Circling a figure, pointing at a region of a diagram'],
        ['Stamp', 'APPROVED, DRAFT and similar'],
      ] },
      { type: 'h2', text: 'Annotations are separate from the page' },
      { type: 'p', text: 'This is the property that surprises people. Because annotations are objects layered over the content, they can be moved, edited or deleted by anyone who opens the file — and some of them do not print by default. A reviewer\'s carefully placed comments can vanish from a printout entirely.' },
      { type: 'callout', title: 'Flatten before sending outside the review', text: 'If the marked-up document is going to someone who must see the annotations exactly as you left them, flatten it. If it is going back to the author to act on, leave the annotations live so they can be replied to and resolved.' },
      { type: 'h2', text: 'Reviewing well' },
      { type: 'list', items: [
        'Say what you want changed, not just that something is wrong. "Unclear" is not actionable; "does this cover renewals?" is.',
        'Use one comment per issue, so each can be resolved independently.',
        'Highlight the exact text your comment refers to.',
        'Sign your comments if several people are reviewing the same file.',
        'Keep drawings for things text cannot express — a region of a plan, a direction on a diagram.',
      ] },
      { type: 'h2', text: 'When several people review at once' },
      { type: 'p', text: 'Circulating one PDF to five reviewers produces five annotated files, and merging their comments is manual work. If that is your situation, either collect the reviews in sequence on one file, or move the review to a platform built for it. PDF annotation is excellent for one reviewer and awkward for many.' },
      { type: 'h2', text: 'Before the document is published' },
      { type: 'p', text: 'Annotations are invisible in a casual read but present in the file. A published document still carrying internal review comments is a common and entirely avoidable disclosure. Remove annotations as part of finalising anything that leaves the organisation.' },
    ],
    faqs: [
      { q: 'Will my highlights show for the recipient?', a: 'In most readers, yes. Whether they print depends on the reader\'s settings — flatten if it matters.' },
      { q: 'Can annotations be edited by others?', a: 'Yes, unless the document is flattened. They are objects on the page.' },
      { q: 'Do annotations increase file size?', a: 'Slightly. Heavy freehand drawing adds more than text comments.' },
      { q: 'How do I remove all annotations?', a: 'Run an optimisation pass with annotation removal, or flatten them into the page if they should stay visible.' },
    ],
    related: ['how-to-flatten-a-pdf', 'what-personal-data-is-hidden-in-your-pdf', 'how-to-compare-two-pdfs'],
  },

  {
    slug: 'how-to-add-a-cover-page-to-a-pdf',
    title: 'How to Add a Cover Page to a PDF',
    description: 'Put a title page, contents page or fax cover on the front of an existing PDF — and make it match the document behind it.',
    keyword: 'add cover page to pdf',
    category: 'Editing & Signing',
    published: '2026-07-09',
    tool: 'merge-pdf',
    blocks: [
      { type: 'p', text: 'A cover page tells the reader what they are holding before they read a word of it. On a merged pack, a bundle or a submission it is the difference between a document and a stack of pages.' },
      { type: 'h2', text: 'Add one' },
      { type: 'steps', items: [
        'Create the cover page — in Word, or as HTML rendered to PDF for full control of the layout.',
        'Convert it to PDF if it is not one already.',
        'Merge it in front of your document, with the cover first in the list.',
        'Add page numbers afterwards, starting from the page after the cover.',
      ] },
      { type: 'h2', text: 'What belongs on it' },
      { type: 'list', items: [
        'The document title, large enough to read at a glance.',
        'Who it is from and who it is for.',
        'The date, and a version marker if there will be more than one.',
        'A reference number, matter number or case number.',
        'A confidentiality notice, if the content warrants one.',
        'A contents list, if the pack has distinct sections.',
      ] },
      { type: 'callout', title: 'Match the page size', text: 'An A4 cover on a US Letter document — or the reverse — makes the whole file look wrong and prints badly. Check the size of the document before you build the cover.' },
      { type: 'h2', text: 'Adding a contents page' },
      { type: 'p', text: 'Build it after the merge, not before. You cannot list the page each section starts on until the document exists in its final order. Merge everything, note the starting pages, create the contents page, then merge that onto the front.' },
      { type: 'p', text: 'That does shift every page by one, so build the contents with that offset in mind — or add page numbers after the contents page is in place and read the real numbers off the finished document.' },
      { type: 'h2', text: 'Keeping the cover out of the numbering' },
      { type: 'p', text: 'A cover page is conventionally unnumbered. Set the page numbering to begin on the following page, so the reader\'s page 1 is the first page of actual content.' },
      { type: 'h2', text: 'Replacing an existing cover' },
      { type: 'p', text: 'Remove the old page first, then merge the new one in front. Merging without removing leaves you with two covers, which is the most common version of getting this wrong.' },
    ],
    faqs: [
      { q: 'How do I put a page at the front of a PDF?', a: 'Merge it, with the cover file listed first. Order in the merge list is page order in the result.' },
      { q: 'Should the cover page be numbered?', a: 'Conventionally not. Start the numbering on the following page.' },
      { q: 'How do I make a contents page?', a: 'After merging, note where each section starts, build the page, and merge it in front. Then number the document.' },
      { q: 'What if my cover is a different size?', a: 'It will sit at its own size in the merged file, which looks wrong and prints badly. Match the sizes first.' },
    ],
    related: ['how-to-merge-pdf-files', 'how-to-add-page-numbers-to-a-pdf', 'how-to-create-a-pdf-from-multiple-file-types'],
  },
];
