import type { BlogPost } from '../types';

export const editingPosts: BlogPost[] = [
  {
    slug: 'how-to-sign-a-pdf-electronically',
    title: 'How to Sign a PDF Electronically',
    description: 'Sign a PDF without printing it — draw it, type it, or upload a signature image. What counts as a signature, and how to place it properly.',
    keyword: 'how to sign a pdf electronically',
    category: 'Editing & Signing',
    published: '2026-02-08',
    updated: '2026-08-22',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'Printing a document, signing it, scanning it back and emailing the result is a ritual that survives out of habit. Signing the PDF directly takes about thirty seconds and produces a cleaner document.' },
      { type: 'h2', text: 'Sign a PDF' },
      { type: 'steps', items: [
        'Open the Sign PDF tool and add your document.',
        'Choose the page to sign — the tool shows you where there is room.',
        'Draw your signature, type your name, or upload an image of your signature.',
        'If you type it, choose whether it should be rendered as handwriting.',
        'Preview the signed page, then download.',
      ] },
      { type: 'h2', text: 'The three ways to produce a signature' },
      { type: 'table', head: ['Method', 'Looks like', 'Best for'], rows: [
        ['Drawn', 'Your actual signature, roughly', 'Anything that should look hand-signed'],
        ['Typed', 'Your name in handwriting or a clean serif', 'Routine forms and approvals'],
        ['Uploaded image', 'Your real signature exactly', 'Documents where consistency matters'],
      ] },
      { type: 'p', text: 'Drawing with a mouse produces something wobblier than your real signature; a trackpad is better and a touchscreen with a stylus is best. If you sign a lot of documents, photographing your signature once on white paper and reusing the image gives the most consistent result.' },
      { type: 'callout', title: 'Preview before downloading', text: 'A signature placed slightly off, at the wrong scale, or over the text beneath it is the most common problem. Look at the signed page as a whole before you send it.' },
      { type: 'h2', text: 'Signing it locally' },
      { type: 'p', text: 'A signature is a piece of personal data and the documents you sign are usually contracts. A signing tool that uploads sends both to a third party. One that works in the browser keeps the document and the signature on your own machine — worth caring about for exactly the documents that most often get signed.' },
      { type: 'h2', text: 'Adding a date' },
      { type: 'p', text: 'Many agreements need a date beside the signature. Type it as text next to the signature rather than assuming a timestamp elsewhere in the file will do — metadata dates are not what a counterparty reads, and they are trivially changed.' },
      { type: 'h2', text: 'Signature or digital signature?' },
      { type: 'p', text: 'Placing an image of a signature is an electronic signature: it shows intent to agree, and it is what almost every commercial agreement uses. A digital signature is different — a cryptographic seal that proves the document has not changed since signing. Both are valid; they do different jobs, and the second is only required where a specific regulation says so.' },
    ],
    faqs: [
      { q: 'Is an electronic signature legally valid?', a: 'In most jurisdictions, yes, for most kinds of agreement. Some documents — certain wills, property deeds and court filings — have specific requirements. Check for those categories.' },
      { q: 'Do I need to print and scan?', a: 'No, and the printed-and-scanned version is usually worse: larger, blurrier and harder to read.' },
      { q: 'Can I reuse the same signature image?', a: 'Yes, and it is the most consistent approach. Keep the file somewhere private, since it is a copy of your signature.' },
      { q: 'Will the recipient be able to remove my signature?', a: 'A placed signature is an object on the page and can be removed by someone determined. A digital signature makes any alteration detectable.' },
      { q: 'Does signing upload my contract?', a: 'Not with a tool that works in the browser. Check the network activity if you want to be sure.' },
    ],
    related: ['how-to-add-a-handwritten-signature-to-a-pdf', 'electronic-signature-vs-digital-signature', 'are-electronic-signatures-legally-binding'],
  },

  {
    slug: 'how-to-add-a-handwritten-signature-to-a-pdf',
    title: 'How to Add a Handwritten Signature to a PDF',
    description: 'Get a real handwritten signature onto a PDF — draw it, photograph your own, or have a typed name rendered as handwriting.',
    keyword: 'add handwritten signature to pdf',
    category: 'Editing & Signing',
    published: '2026-03-16',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'A handwritten signature on a document signals that a person considered it and agreed. Getting one onto a PDF without a printer takes one of three routes, each suited to a different situation.' },
      { type: 'h2', text: 'Draw it' },
      { type: 'p', text: 'Best on a touchscreen, acceptable on a trackpad, poor with a mouse. Draw slowly and larger than you would on paper — the signature is scaled down when it is placed, and scaling down hides unsteadiness while scaling up exposes it.' },
      { type: 'h2', text: 'Photograph your real signature' },
      { type: 'steps', items: [
        'Sign a clean sheet of white paper with a black pen. Sign several times and pick the best.',
        'Photograph it straight on, in even daylight, with no shadow across the page.',
        'Crop tightly to the signature.',
        'Upload it as your signature image.',
      ] },
      { type: 'p', text: 'This gives the most faithful result and is reusable indefinitely. Keep the file somewhere private — it is a copy of your signature, and it can be lifted from any document you send.' },
      { type: 'h2', text: 'Have your typed name rendered as handwriting' },
      { type: 'p', text: 'You type your name and it is drawn in a handwriting face rather than a block font. It is quick, it is legible, and for routine internal approvals it is entirely adequate. It is not your handwriting, and for a document that may be scrutinised a drawn or photographed signature carries more weight.' },
      { type: 'callout', title: 'Preview before you send', text: 'Check the size, the position and that the signature is not sitting across the printed text beneath it. A signature that overlaps a clause reads as careless on a contract.' },
      { type: 'h2', text: 'Placing it well' },
      { type: 'list', items: [
        'Sit it on the signature line, not floating above or crossing it.',
        'Scale it to roughly the height of two lines of body text — larger reads as shouting.',
        'Keep it in black. Blue is common on paper and can look like a scanning artefact on screen.',
        'Add the date beside it if the document has a date field.',
        'Leave clear space around it so it does not collide with anything.',
      ] },
      { type: 'h2', text: 'Keep the signature image safe' },
      { type: 'p', text: 'Anyone who receives a signed PDF can crop your signature out of it and place it on another document. That is true of paper too, and it is a reason to sign only what you have read, and to prefer a digital signature where the integrity of the document genuinely matters.' },
    ],
    faqs: [
      { q: 'How do I get my real signature into a PDF?', a: 'Sign white paper, photograph it straight on in good light, crop it tightly and upload it as your signature image.' },
      { q: 'Should the background be transparent?', a: 'Ideally. A white box around the signature looks obvious over shaded or ruled areas.' },
      { q: 'Is a typed handwriting-style signature acceptable?', a: 'For routine approvals, generally yes. For anything likely to be scrutinised, draw or photograph a real one.' },
      { q: 'Can someone copy my signature from a signed PDF?', a: 'Yes, by cropping the image out. It is the same exposure as sending a signed paper document.' },
    ],
    related: ['how-to-sign-a-pdf-electronically', 'how-to-sign-a-pdf-on-iphone', 'how-to-sign-a-contract-and-send-it-back'],
  },

  {
    slug: 'electronic-signature-vs-digital-signature',
    title: 'Electronic Signature vs Digital Signature: The Difference',
    description: 'The two terms are used interchangeably and mean different things. What each one actually proves, and which one your document needs.',
    keyword: 'electronic signature vs digital signature',
    category: 'Editing & Signing',
    published: '2026-04-04',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'The confusion is genuine and it matters, because the two things prove different facts about a document.' },
      { type: 'h2', text: 'Electronic signature' },
      { type: 'p', text: 'Any electronic mark made with the intent to sign. A drawn signature on a PDF, a typed name, a clicked "I agree", an email saying "yes, approved". It demonstrates intent, and intent is what most contract law asks for.' },
      { type: 'p', text: 'What it does not do is prove the document is unchanged. A signature image can be moved to another document, and the page beneath it can be edited afterwards.' },
      { type: 'h2', text: 'Digital signature' },
      { type: 'p', text: 'A cryptographic operation. The document is hashed, the hash is encrypted with the signer\'s private key, and the result is stored with the file alongside a certificate identifying the signer. Any subsequent change to any byte of the document invalidates it, and every mainstream reader will say so.' },
      { type: 'p', text: 'It proves two things at once: who signed, and that nothing has changed since.' },
      { type: 'table', head: ['', 'Electronic', 'Digital'], rows: [
        ['Shows intent to sign', 'Yes', 'Yes'],
        ['Proves the signer\'s identity', 'No', 'Yes, via a certificate'],
        ['Detects later alteration', 'No', 'Yes'],
        ['Needs a certificate', 'No', 'Yes'],
        ['Effort to produce', 'Seconds', 'Setup required'],
        ['Typical use', 'Most commercial agreements', 'Regulated filings, high-value contracts'],
      ] },
      { type: 'callout', title: 'A digital signature is a kind of electronic signature', text: 'The categories nest: every digital signature is an electronic signature, and most electronic signatures are not digital. That is why the terms get used loosely.' },
      { type: 'h2', text: 'Which one do you need?' },
      { type: 'p', text: 'For the overwhelming majority of business documents — engagement letters, NDAs, purchase orders, internal approvals — an electronic signature is what is used and what is expected. It is quick, it is accepted, and it does not require anyone to obtain a certificate.' },
      { type: 'p', text: 'You need a digital signature when a regulator or counterparty specifies one, when the document is high-value enough that repudiation is a live risk, or when you must be able to prove the version signed is the version held. Qualified electronic signatures under eIDAS are the strongest form and carry specific legal weight in the EU.' },
      { type: 'h2', text: 'A practical middle ground' },
      { type: 'p', text: 'For an ordinary agreement, an electronic signature plus a clear audit trail — dated emails, an agreed final version, both parties holding the same file — covers most of what a digital signature would give you, without the setup. Escalate when the value or the regulation justifies it.' },
    ],
    faqs: [
      { q: 'Is a drawn signature on a PDF a digital signature?', a: 'No, it is an electronic signature. Digital signatures are cryptographic and require a certificate.' },
      { q: 'Which is more legally binding?', a: 'Both can be binding. A digital signature is easier to prove in a dispute because it evidences integrity as well as intent.' },
      { q: 'Do I need a certificate?', a: 'Only for a digital signature. Certificates come from certificate authorities and usually cost money.' },
      { q: 'What does the "signature invalid" warning mean?', a: 'The document changed after signing, or the certificate cannot be validated. Either way, do not rely on it without checking.' },
    ],
    related: ['are-electronic-signatures-legally-binding', 'how-to-sign-a-pdf-electronically', 'how-to-tell-if-a-pdf-has-been-edited'],
  },

  {
    slug: 'are-electronic-signatures-legally-binding',
    title: 'Are Electronic Signatures Legally Binding?',
    description: 'A plain-English look at where electronic signatures are recognised, what makes one hold up, and the documents that still need ink.',
    keyword: 'are electronic signatures legally binding',
    category: 'Editing & Signing',
    published: '2026-04-18',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'In most of the world, yes — electronic signatures have been recognised in law for over two decades. The interesting questions are which documents are excluded, and what makes a particular signature defensible if it is ever challenged.' },
      { type: 'p', text: 'This is general information rather than legal advice. For a specific transaction, ask a lawyer in the relevant jurisdiction.' },
      { type: 'h2', text: 'The main legal frameworks' },
      { type: 'table', head: ['Region', 'Law', 'Position'], rows: [
        ['United States', 'ESIGN Act (2000) and UETA', 'Electronic signatures have the same effect as handwritten ones'],
        ['European Union', 'eIDAS Regulation', 'Recognised, with three tiers of increasing assurance'],
        ['United Kingdom', 'Electronic Communications Act and UK eIDAS', 'Valid for most contracts'],
        ['Canada', 'PIPEDA and provincial acts', 'Recognised'],
        ['Australia', 'Electronic Transactions Act', 'Recognised'],
        ['India', 'Information Technology Act', 'Recognised, with requirements for certain classes'],
      ] },
      { type: 'h2', text: 'What usually still needs ink' },
      { type: 'list', items: [
        'Wills and testamentary documents in many jurisdictions.',
        'Some property transfers and deeds.',
        'Certain court filings and notarised instruments.',
        'Some family law documents — adoption, divorce papers.',
        'Specific regulated forms that name a wet signature explicitly.',
      ] },
      { type: 'p', text: 'These exclusions vary considerably by jurisdiction and change over time. Where a document falls into one of these categories, check rather than assume.' },
      { type: 'callout', title: 'Enforceability turns on evidence', text: 'A challenged signature comes down to what you can show: that this person signed, that they intended to, and that the document has not changed. The stronger your record of those three things, the stronger your position.' },
      { type: 'h2', text: 'Making a signature defensible' },
      { type: 'steps', items: [
        'Keep the email trail showing the document was sent and returned.',
        'Record the date on the document itself, next to the signature.',
        'Make sure both parties hold the identical final file.',
        'Use a digital signature where the value or the risk justifies it.',
        'Do not alter the document after signing — any change undermines the record.',
      ] },
      { type: 'h2', text: 'The tiers under eIDAS' },
      { type: 'p', text: 'EU law distinguishes simple electronic signatures, advanced ones (uniquely linked to the signer and capable of detecting change), and qualified ones (advanced, plus a qualified certificate from an accredited provider). Only qualified signatures are automatically equivalent to handwritten across all member states; the others are admissible and their weight is assessed on the evidence.' },
    ],
    faqs: [
      { q: 'Is a typed name a legal signature?', a: 'It can be, where intent to sign is evident. It carries less evidential weight than a drawn signature or a digital one.' },
      { q: 'Does a PDF signature hold up in court?', a: 'Electronic signatures are admissible in most jurisdictions. How much weight one carries depends on the surrounding evidence.' },
      { q: 'Do both parties have to sign electronically?', a: 'No. Mixed signing is common and does not invalidate an agreement.' },
      { q: 'Which documents cannot be signed electronically?', a: 'Commonly wills, some deeds and certain court documents — but the list varies by jurisdiction, so check for your specific case.' },
    ],
    related: ['electronic-signature-vs-digital-signature', 'how-to-sign-a-pdf-electronically', 'how-to-sign-a-contract-and-send-it-back'],
  },

  {
    slug: 'how-to-sign-a-pdf-on-iphone',
    title: 'How to Sign a PDF on iPhone or iPad',
    description: 'Sign a document on iOS with your finger — using Markup, or a browser tool when you need more control over placement.',
    keyword: 'how to sign a pdf on iphone',
    category: 'Editing & Signing',
    published: '2026-05-04',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'A phone is the best device for signing, because you can actually write on the screen. A finger beats a mouse comfortably, and an Apple Pencil produces a signature indistinguishable from ink.' },
      { type: 'h2', text: 'Using Markup, built into iOS' },
      { type: 'steps', items: [
        'Open the PDF in Files, Mail or Safari.',
        'Tap the Markup icon — the pen tip in a circle.',
        'Tap +, then Signature.',
        'Draw your signature, or pick one you saved earlier.',
        'Drag and resize it into position, then tap Done.',
        'Share the signed file from the share sheet.',
      ] },
      { type: 'p', text: 'iOS stores your saved signature for reuse, so after the first time signing takes about ten seconds.' },
      { type: 'h2', text: 'Using a browser tool instead' },
      { type: 'p', text: 'Markup is quick but rough: placement is by eye, sizing is a pinch, and there is no preview of the finished page other than what you are looking at. A browser-based signing tool gives you a proper preview of the signed document and a choice between drawing, typing and uploading a signature — and it works the same on the phone as on a laptop.' },
      { type: 'p', text: 'Both keep the document on the device. Neither uploads your contract, which for signed documents is the property that matters.' },
      { type: 'h2', text: 'Signing well on a small screen' },
      { type: 'list', items: [
        'Turn the phone to landscape — a wider canvas produces a better signature.',
        'Zoom into the signature area before positioning, so you can see the line you are signing on.',
        'Draw larger than needed; it scales down cleanly and the wobble disappears.',
        'Use an Apple Pencil if you have one. The difference is substantial.',
        'Check the whole page afterwards, not just the signature.',
      ] },
      { type: 'callout', title: 'Save the signature once', text: 'Both Markup and a browser tool let you reuse a stored signature. Drawing it once properly and reusing it beats drawing a fresh approximation every time.' },
      { type: 'h2', text: 'Sending it back' },
      { type: 'p', text: 'Reply to the original email and attach the signed PDF rather than starting a new thread — it keeps the record together. Say in the message that the signed copy is attached and note the date. If it is going to a portal, check the size limit first; a signed document is rarely large, but a scanned one can be.' },
    ],
    faqs: [
      { q: 'Can I sign a PDF on iPhone without an app?', a: 'Yes. Markup is built into iOS, and browser-based signing tools work in Safari with nothing installed.' },
      { q: 'Where is my saved signature stored?', a: 'On the device, in the Markup settings. It is reused across apps.' },
      { q: 'Can I sign with my finger?', a: 'Yes, and it works well. An Apple Pencil is better if you have one.' },
      { q: 'Does signing on iPhone upload the document?', a: 'Markup works locally, and a browser tool that processes in the tab does too. Neither transmits the file.' },
    ],
    related: ['how-to-sign-a-pdf-electronically', 'how-to-add-a-handwritten-signature-to-a-pdf', 'how-to-merge-pdf-files-on-iphone'],
  },

  {
    slug: 'how-to-sign-a-contract-and-send-it-back',
    title: 'How to Sign a Contract and Send It Back Properly',
    description: 'The full sequence for signing a contract received by email — reading it, signing it, dating it, and returning it so the record holds up.',
    keyword: 'how to sign a contract and send it back',
    category: 'Editing & Signing',
    published: '2026-05-18',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'Signing is the easy part. The things that cause problems later are the ones around it: signing a version that was superseded, returning a file the other side cannot open, or leaving no record of what was agreed and when.' },
      { type: 'h2', text: 'Before you sign' },
      { type: 'steps', items: [
        'Read it. All of it, including the schedules, which is where the commercial terms usually live.',
        'Confirm this is the final version — check the filename, the date and any version marker against the last email.',
        'Check the parties, the dates, the amounts and any blanks that were left to be filled.',
        'Raise anything you disagree with before signing, not after.',
      ] },
      { type: 'h2', text: 'Signing it' },
      { type: 'steps', items: [
        'Open the PDF in a signing tool.',
        'Place your signature on the signature line, sized to about two lines of text.',
        'Add the date beside it if there is a date field, and fill in any name or title blocks.',
        'Preview the signed page and check nothing overlaps the printed text.',
        'Download the signed file.',
      ] },
      { type: 'callout', title: 'Sign the PDF, do not print it', text: 'A printed-and-scanned contract is larger, harder to read, no longer searchable, and no more binding. Signing the PDF directly produces a better document and a cleaner record.' },
      { type: 'h2', text: 'Sending it back' },
      { type: 'list', items: [
        'Reply on the original email thread so the exchange stays together.',
        'Name the file clearly: "agreement-acme-signed-2026-08-23.pdf".',
        'Say in the message what you have signed and on what date.',
        'Note any pages you have initialled, if the document asks for initials.',
        'Ask for a fully executed copy once the other side has signed.',
      ] },
      { type: 'h2', text: 'Afterwards' },
      { type: 'p', text: 'Keep the signed PDF, the email you sent it with, and the countersigned version when it arrives. Those three items together are the record: what was signed, when it went, and that both parties hold the same document.' },
      { type: 'p', text: 'File it somewhere you will find it in three years — not in a downloads folder. A contract you cannot locate is a contract you cannot rely on.' },
      { type: 'h2', text: 'If you need to sign several pages' },
      { type: 'p', text: 'Some agreements require initials on each page as well as a signature at the end. Do that in one pass rather than page by page across several sessions, and check every page before sending — a missed initial usually means the whole document comes back.' },
    ],
    faqs: [
      { q: 'Should I print and scan the contract?', a: 'No. Signing the PDF directly gives a better-quality document and the same legal effect.' },
      { q: 'What should I name the file?', a: 'Something that identifies the agreement, the party and the date. Filenames are how documents are found later.' },
      { q: 'Do I need to initial every page?', a: 'Only if the document asks for it. Where it does, missing one usually means signing again.' },
      { q: 'What if the version I was sent is out of date?', a: 'Ask for the current one before signing. Signing a superseded draft creates a dispute rather than an agreement.' },
    ],
    related: ['how-to-sign-a-pdf-electronically', 'are-electronic-signatures-legally-binding', 'how-to-merge-pdf-files'],
  },

  {
    slug: 'how-to-fill-out-a-pdf-form',
    title: 'How to Fill Out a PDF Form',
    description: 'Complete a PDF form — whether it has real fields or is a flat scan — and make sure your answers survive the trip to the recipient.',
    keyword: 'how to fill out a pdf form',
    category: 'Editing & Signing',
    published: '2026-06-01',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'There are two completely different kinds of PDF form, and the first thing to do is work out which one you are holding.' },
      { type: 'h2', text: 'Which kind is it?' },
      { type: 'p', text: 'Click where an answer should go. If a cursor appears and you can type, it is an interactive form with real fields. If nothing happens, it is a flat form — a picture of a form, with nowhere to type.' },
      { type: 'table', head: ['', 'Interactive form', 'Flat form'], rows: [
        ['Clicking a box', 'Cursor appears', 'Nothing happens'],
        ['How to complete it', 'Type into the fields', 'Add text on top of the page'],
        ['Risk', 'Values not displaying for the recipient', 'Text landing slightly off the line'],
        ['Fix before sending', 'Flatten the form', 'Check alignment'],
      ] },
      { type: 'h2', text: 'Filling an interactive form' },
      { type: 'steps', items: [
        'Open it in any reader and click into the first field.',
        'Tab between fields — it is faster and it stops you missing one.',
        'Complete every required field; blanks are the main reason forms are returned.',
        'Sign it if a signature is required.',
        'Flatten the document before sending.',
      ] },
      { type: 'callout', title: 'Flatten before you send', text: 'The classic failure is a form that shows your answers on your screen and arrives blank. Field values sometimes fail to render in another reader or in print. Flattening draws them permanently into the page and eliminates the problem.' },
      { type: 'h2', text: 'Filling a flat form' },
      { type: 'p', text: 'A flat form has no fields, so you add text on top of it. Place each answer on the line, match the size to the printed text around it, and keep to black. Take particular care with boxes intended for one character per box — spacing them by eye is fiddly and a misaligned answer can invalidate the form.' },
      { type: 'p', text: 'Alternatively, print it, complete it by hand, and scan it back. For a form with awkward character boxes that is often genuinely faster.' },
      { type: 'h2', text: 'Before you submit' },
      { type: 'list', items: [
        'Read every field back — a typo in a reference number costs you a resubmission.',
        'Confirm every required field is complete.',
        'Check the signature and date are present.',
        'Open the finished file in a different reader to confirm the answers appear.',
        'Check the file size against any limit the portal states.',
      ] },
    ],
    faqs: [
      { q: 'Why can I not type in this PDF form?', a: 'It is a flat form with no interactive fields. Add text on top of the page instead.' },
      { q: 'Why did my completed form arrive blank?', a: 'Field appearances did not render for the recipient. Flatten the form before sending and it cannot happen.' },
      { q: 'Can I save a partly completed form?', a: 'Usually yes in a modern reader. Some older forms only allow printing, in which case complete it in one sitting.' },
      { q: 'How do I fill a form on a phone?', a: 'Interactive forms work in most mobile readers. Flat forms are easier on a larger screen, where alignment is easier to judge.' },
    ],
    related: ['how-to-flatten-a-pdf', 'how-to-add-text-to-a-pdf', 'how-to-sign-a-pdf-electronically'],
  },
];
