import type { BlogPost } from '../types';

export const editingPosts: BlogPost[] = [
  {
    slug: 'how-to-sign-a-pdf-electronically',
    title: 'How to Sign a PDF Electronically',
    description: 'Sign a PDF without printing it — draw it, type it, or upload a signature image. What counts as a signature, and how to place it properly.',
    keyword: 'how to sign a pdf electronically',
    category: 'Editing & Signing',
    published: '2026-02-08',
    updated: '2026-08-22',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'Printing a document, signing it, scanning it back and emailing the result is a ritual that survives out of habit. Signing the PDF directly takes about thirty seconds and produces a cleaner document.' },
      { type: 'h2', text: 'Sign a PDF' },
      { type: 'steps', items: [
        'Open the Sign PDF tool and add your document.',
        'Choose the page to sign — the tool shows you where there is room.',
        'Draw your signature, type your name, or upload an image of your signature.',
        'If you type it, choose whether it should be rendered as handwriting.',
        'Preview the signed page, then download.',
      ] },
      { type: 'h2', text: 'The three ways to produce a signature' },
      { type: 'table', head: ['Method', 'Looks like', 'Best for'], rows: [
        ['Drawn', 'Your actual signature, roughly', 'Anything that should look hand-signed'],
        ['Typed', 'Your name in handwriting or a clean serif', 'Routine forms and approvals'],
        ['Uploaded image', 'Your real signature exactly', 'Documents where consistency matters'],
      ] },
      { type: 'p', text: 'Drawing with a mouse produces something wobblier than your real signature; a trackpad is better and a touchscreen with a stylus is best. If you sign a lot of documents, photographing your signature once on white paper and reusing the image gives the most consistent result.' },
      { type: 'callout', title: 'Preview before downloading', text: 'A signature placed slightly off, at the wrong scale, or over the text beneath it is the most common problem. Look at the signed page as a whole before you send it.' },
      { type: 'h2', text: 'Signing it locally' },
      { type: 'p', text: 'A signature is a piece of personal data and the documents you sign are usually contracts. A signing tool that uploads sends both to a third party. One that works in the browser keeps the document and the signature on your own machine — worth caring about for exactly the documents that most often get signed.' },
      { type: 'h2', text: 'Adding a date' },
      { type: 'p', text: 'Many agreements need a date beside the signature. Type it as text next to the signature rather than assuming a timestamp elsewhere in the file will do — metadata dates are not what a counterparty reads, and they are trivially changed.' },
      { type: 'h2', text: 'Signature or digital signature?' },
      { type: 'p', text: 'Placing an image of a signature is an electronic signature: it shows intent to agree, and it is what almost every commercial agreement uses. A digital signature is different — a cryptographic seal that proves the document has not changed since signing. Both are valid; they do different jobs, and the second is only required where a specific regulation says so.' },
    ],
    faqs: [
      { q: 'Is an electronic signature legally valid?', a: 'In most jurisdictions, yes, for most kinds of agreement. Some documents — certain wills, property deeds and court filings — have specific requirements. Check for those categories.' },
      { q: 'Do I need to print and scan?', a: 'No, and the printed-and-scanned version is usually worse: larger, blurrier and harder to read.' },
      { q: 'Can I reuse the same signature image?', a: 'Yes, and it is the most consistent approach. Keep the file somewhere private, since it is a copy of your signature.' },
      { q: 'Will the recipient be able to remove my signature?', a: 'A placed signature is an object on the page and can be removed by someone determined. A digital signature makes any alteration detectable.' },
      { q: 'Does signing upload my contract?', a: 'Not with a tool that works in the browser. Check the network activity if you want to be sure.' },
    ],
    related: ['how-to-add-a-handwritten-signature-to-a-pdf', 'electronic-signature-vs-digital-signature', 'are-electronic-signatures-legally-binding'],
  },

  {
    slug: 'how-to-add-a-handwritten-signature-to-a-pdf',
    title: 'How to Add a Handwritten Signature to a PDF',
    description: 'Get a real handwritten signature onto a PDF — draw it, photograph your own, or have a typed name rendered as handwriting.',
    keyword: 'add handwritten signature to pdf',
    category: 'Editing & Signing',
    published: '2026-03-16',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'A handwritten signature on a document signals that a person considered it and agreed. Getting one onto a PDF without a printer takes one of three routes, each suited to a different situation.' },
      { type: 'h2', text: 'Draw it' },
      { type: 'p', text: 'Best on a touchscreen, acceptable on a trackpad, poor with a mouse. Draw slowly and larger than you would on paper — the signature is scaled down when it is placed, and scaling down hides unsteadiness while scaling up exposes it.' },
      { type: 'h2', text: 'Photograph your real signature' },
      { type: 'steps', items: [
        'Sign a clean sheet of white paper with a black pen. Sign several times and pick the best.',
        'Photograph it straight on, in even daylight, with no shadow across the page.',
        'Crop tightly to the signature.',
        'Upload it as your signature image.',
      ] },
      { type: 'p', text: 'This gives the most faithful result and is reusable indefinitely. Keep the file somewhere private — it is a copy of your signature, and it can be lifted from any document you send.' },
      { type: 'h2', text: 'Have your typed name rendered as handwriting' },
      { type: 'p', text: 'You type your name and it is drawn in a handwriting face rather than a block font. It is quick, it is legible, and for routine internal approvals it is entirely adequate. It is not your handwriting, and for a document that may be scrutinised a drawn or photographed signature carries more weight.' },
      { type: 'callout', title: 'Preview before you send', text: 'Check the size, the position and that the signature is not sitting across the printed text beneath it. A signature that overlaps a clause reads as careless on a contract.' },
      { type: 'h2', text: 'Placing it well' },
      { type: 'list', items: [
        'Sit it on the signature line, not floating above or crossing it.',
        'Scale it to roughly the height of two lines of body text — larger reads as shouting.',
        'Keep it in black. Blue is common on paper and can look like a scanning artefact on screen.',
        'Add the date beside it if the document has a date field.',
        'Leave clear space around it so it does not collide with anything.',
      ] },
      { type: 'h2', text: 'Keep the signature image safe' },
      { type: 'p', text: 'Anyone who receives a signed PDF can crop your signature out of it and place it on another document. That is true of paper too, and it is a reason to sign only what you have read, and to prefer a digital signature where the integrity of the document genuinely matters.' },
    ],
    faqs: [
      { q: 'How do I get my real signature into a PDF?', a: 'Sign white paper, photograph it straight on in good light, crop it tightly and upload it as your signature image.' },
      { q: 'Should the background be transparent?', a: 'Ideally. A white box around the signature looks obvious over shaded or ruled areas.' },
      { q: 'Is a typed handwriting-style signature acceptable?', a: 'For routine approvals, generally yes. For anything likely to be scrutinised, draw or photograph a real one.' },
      { q: 'Can someone copy my signature from a signed PDF?', a: 'Yes, by cropping the image out. It is the same exposure as sending a signed paper document.' },
    ],
    related: ['how-to-sign-a-pdf-electronically', 'how-to-sign-a-pdf-on-iphone', 'how-to-sign-a-contract-and-send-it-back'],
  },

  {
    slug: 'how-to-sign-a-contract-and-send-it-back',
    title: 'How to Sign a Contract and Send It Back Properly',
    description: 'The full sequence for signing a contract received by email — reading it, signing it, dating it, and returning it so the record holds up.',
    keyword: 'how to sign a contract and send it back',
    category: 'Editing & Signing',
    published: '2026-05-18',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'Signing is the easy part. The things that cause problems later are the ones around it: signing a version that was superseded, returning a file the other side cannot open, or leaving no record of what was agreed and when.' },
      { type: 'h2', text: 'Before you sign' },
      { type: 'steps', items: [
        'Read it. All of it, including the schedules, which is where the commercial terms usually live.',
        'Confirm this is the final version — check the filename, the date and any version marker against the last email.',
        'Check the parties, the dates, the amounts and any blanks that were left to be filled.',
        'Raise anything you disagree with before signing, not after.',
      ] },
      { type: 'h2', text: 'Signing it' },
      { type: 'steps', items: [
        'Open the PDF in a signing tool.',
        'Place your signature on the signature line, sized to about two lines of text.',
        'Add the date beside it if there is a date field, and fill in any name or title blocks.',
        'Preview the signed page and check nothing overlaps the printed text.',
        'Download the signed file.',
      ] },
      { type: 'callout', title: 'Sign the PDF, do not print it', text: 'A printed-and-scanned contract is larger, harder to read, no longer searchable, and no more binding. Signing the PDF directly produces a better document and a cleaner record.' },
      { type: 'h2', text: 'Sending it back' },
      { type: 'list', items: [
        'Reply on the original email thread so the exchange stays together.',
        'Name the file clearly: "agreement-acme-signed-2026-08-23.pdf".',
        'Say in the message what you have signed and on what date.',
        'Note any pages you have initialled, if the document asks for initials.',
        'Ask for a fully executed copy once the other side has signed.',
      ] },
      { type: 'h2', text: 'Afterwards' },
      { type: 'p', text: 'Keep the signed PDF, the email you sent it with, and the countersigned version when it arrives. Those three items together are the record: what was signed, when it went, and that both parties hold the same document.' },
      { type: 'p', text: 'File it somewhere you will find it in three years — not in a downloads folder. A contract you cannot locate is a contract you cannot rely on.' },
      { type: 'h2', text: 'If you need to sign several pages' },
      { type: 'p', text: 'Some agreements require initials on each page as well as a signature at the end. Do that in one pass rather than page by page across several sessions, and check every page before sending — a missed initial usually means the whole document comes back.' },
    ],
    faqs: [
      { q: 'Should I print and scan the contract?', a: 'No. Signing the PDF directly gives a better-quality document and the same legal effect.' },
      { q: 'What should I name the file?', a: 'Something that identifies the agreement, the party and the date. Filenames are how documents are found later.' },
      { q: 'Do I need to initial every page?', a: 'Only if the document asks for it. Where it does, missing one usually means signing again.' },
      { q: 'What if the version I was sent is out of date?', a: 'Ask for the current one before signing. Signing a superseded draft creates a dispute rather than an agreement.' },
    ],
    related: ['how-to-sign-a-pdf-electronically', 'are-electronic-signatures-legally-binding', 'how-to-merge-pdf-files'],
  },

  {
    slug: 'how-to-fill-out-a-pdf-form',
    title: 'How to Fill Out a PDF Form',
    description: 'Complete a PDF form — whether it has real fields or is a flat scan — and make sure your answers survive the trip to the recipient.',
    keyword: 'how to fill out a pdf form',
    category: 'Editing & Signing',
    published: '2026-06-01',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'There are two completely different kinds of PDF form, and the first thing to do is work out which one you are holding.' },
      { type: 'h2', text: 'Which kind is it?' },
      { type: 'p', text: 'Click where an answer should go. If a cursor appears and you can type, it is an interactive form with real fields. If nothing happens, it is a flat form — a picture of a form, with nowhere to type.' },
      { type: 'table', head: ['', 'Interactive form', 'Flat form'], rows: [
        ['Clicking a box', 'Cursor appears', 'Nothing happens'],
        ['How to complete it', 'Type into the fields', 'Add text on top of the page'],
        ['Risk', 'Values not displaying for the recipient', 'Text landing slightly off the line'],
        ['Fix before sending', 'Flatten the form', 'Check alignment'],
      ] },
      { type: 'h2', text: 'Filling an interactive form' },
      { type: 'steps', items: [
        'Open it in any reader and click into the first field.',
        'Tab between fields — it is faster and it stops you missing one.',
        'Complete every required field; blanks are the main reason forms are returned.',
        'Sign it if a signature is required.',
        'Flatten the document before sending.',
      ] },
      { type: 'callout', title: 'Flatten before you send', text: 'The classic failure is a form that shows your answers on your screen and arrives blank. Field values sometimes fail to render in another reader or in print. Flattening draws them permanently into the page and eliminates the problem.' },
      { type: 'h2', text: 'Filling a flat form' },
      { type: 'p', text: 'A flat form has no fields, so you add text on top of it. Place each answer on the line, match the size to the printed text around it, and keep to black. Take particular care with boxes intended for one character per box — spacing them by eye is fiddly and a misaligned answer can invalidate the form.' },
      { type: 'p', text: 'Alternatively, print it, complete it by hand, and scan it back. For a form with awkward character boxes that is often genuinely faster.' },
      { type: 'h2', text: 'Before you submit' },
      { type: 'list', items: [
        'Read every field back — a typo in a reference number costs you a resubmission.',
        'Confirm every required field is complete.',
        'Check the signature and date are present.',
        'Open the finished file in a different reader to confirm the answers appear.',
        'Check the file size against any limit the portal states.',
      ] },
    ],
    faqs: [
      { q: 'Why can I not type in this PDF form?', a: 'It is a flat form with no interactive fields. Add text on top of the page instead.' },
      { q: 'Why did my completed form arrive blank?', a: 'Field appearances did not render for the recipient. Flatten the form before sending and it cannot happen.' },
      { q: 'Can I save a partly completed form?', a: 'Usually yes in a modern reader. Some older forms only allow printing, in which case complete it in one sitting.' },
      { q: 'How do I fill a form on a phone?', a: 'Interactive forms work in most mobile readers. Flat forms are easier on a larger screen, where alignment is easier to judge.' },
    ],
    related: ['how-to-flatten-a-pdf', 'how-to-add-text-to-a-pdf', 'how-to-sign-a-pdf-electronically'],
  },
];
