import type { BlogPost } from '../types';

export const mergingPosts: BlogPost[] = [
  {
    slug: 'how-to-merge-pdf-files',
    title: 'How to Merge PDF Files (Free, No Sign-Up, No Upload)',
    description: 'Combine two or more PDFs into a single document in your browser. Step-by-step instructions, page-order tips, and answers to the questions people ask most.',
    keyword: 'how to merge pdf files',
    category: 'Merging & Organizing',
    published: '2026-02-04',
    updated: '2026-08-12',
    tool: 'merge-pdf',
    blocks: [
      { type: 'p', text: 'Merging PDFs means taking two or more separate files and producing one document whose pages run in the order you choose. It is the most common thing people need to do with a PDF, and it should take about fifteen seconds.' },
      { type: 'p', text: 'This guide covers the fastest way to do it, how to control the order the pages end up in, and what to check before you send the merged file to anyone.' },
      { type: 'h2', text: 'Merge PDF files in four steps' },
      { type: 'steps', items: [
        'Open the Merge PDF tool. Nothing is uploaded — the page does the work on your own machine.',
        'Drag in every PDF you want to combine. You can add them all at once or a few at a time.',
        'Drag the files into the order you want them to appear. The first file in the list becomes page one of the result.',
        'Press Merge and the combined PDF downloads straight to your device.',
      ] },
      { type: 'callout', title: 'Check the order before you merge', text: 'The single most common mistake is merging in the order the files happened to be selected rather than the order you want to read them. Use the live preview to page through the result before you download it.' },
      { type: 'h2', text: 'Does merging reduce the quality of a PDF?' },
      { type: 'p', text: 'It should not. A correct merge copies each page object across into a new document without touching the images, fonts or vector artwork on it. The pages in the merged file are byte-for-byte the pages you started with.' },
      { type: 'p', text: 'Quality loss creeps in when a tool rasterises your pages — converting each one to a flat image and pasting that into a new PDF. You can spot it immediately: text stops being selectable, and zooming in produces soft, fuzzy letters instead of crisp ones. If that happens, the tool re-rendered your document rather than merging it.' },
      { type: 'h2', text: 'What happens to bookmarks, links and form fields' },
      { type: 'p', text: 'This is where merging gets genuinely tricky, and it is worth knowing what to expect.' },
      { type: 'table', head: ['Element', 'What usually survives a merge'], rows: [
        ['Page content (text, images, vectors)', 'Preserved exactly'],
        ['Page size and rotation', 'Preserved per page — pages of different sizes can coexist'],
        ['Internal links', 'Often preserved, but links pointing to a page number can shift'],
        ['Bookmarks / outline', 'Frequently dropped, since two outlines have to be reconciled'],
        ['Form fields', 'Risky — two files with a field of the same name will collide'],
        ['Digital signatures', 'Always invalidated; a signature covers one specific file'],
      ] },
      { type: 'p', text: 'If your documents are signed contracts, merge the unsigned versions and sign the combined file once at the end. A signature applied before a merge certifies a document that no longer exists.' },
      { type: 'h2', text: 'Merging files that are not PDFs yet' },
      { type: 'p', text: 'You cannot merge a Word file directly into a PDF — everything has to be a PDF first. Convert each piece, then merge:' },
      { type: 'list', items: [
        'Photos and scans: convert them with JPG to PDF, which will also put several images into one file for you.',
        'Word documents: run them through Word to PDF first.',
        'Spreadsheets: Excel to PDF, checking that wide tables have not been cut off at the page edge.',
        'Slides: PowerPoint to PDF turns each slide into a page.',
      ] },
      { type: 'h2', text: 'Merging on a phone' },
      { type: 'p', text: 'Browser-based merging works the same on a phone as on a laptop, which is the advantage of a tool that does the work locally rather than in an app you have to install. Open the tool in Safari or Chrome, tap the upload area, and pick the files from Files or Drive. The merged PDF lands in your downloads folder.' },
      { type: 'p', text: 'The one practical limit is memory. A phone browser handles a handful of ordinary documents comfortably; merging fifty scanned files of forty pages each is a job for a laptop.' },
      { type: 'h2', text: 'Why merging in the browser matters for confidential files' },
      { type: 'p', text: 'Most merge tools upload your documents to a server, combine them there, and send the result back. For a restaurant menu that is fine. For a signed lease, a medical record or a due-diligence pack, it means handing a third party a copy of a document you were trusted with.' },
      { type: 'p', text: 'A tool that runs entirely in the browser never transmits the file at all. You can confirm this yourself: open your browser developer tools, switch to the Network tab, and merge a file. If nothing leaves, the list stays empty.' },
    ],
    faqs: [
      { q: 'How many PDFs can I merge at once?', a: 'There is no fixed limit when the merge happens in your browser — the practical ceiling is your device memory. Dozens of ordinary documents are routine; hundreds of large scans are better done in a few batches.' },
      { q: 'Can I merge PDFs of different page sizes?', a: 'Yes. PDF stores a size per page, so an A4 report and a US Letter invoice can sit in the same file. Some readers will shift between sizes as you scroll, which looks odd but is not an error.' },
      { q: 'Does merging remove a password?', a: 'No. You need to unlock a password-protected PDF before it can be merged, because the merge has to read the page content. Remove the password first, merge, then re-protect the combined file if it needs it.' },
      { q: 'Will merging break my digital signature?', a: 'Yes, always. A digital signature is a cryptographic seal over one exact file. Producing a new file breaks the seal by definition. Merge first, then sign the result.' },
      { q: 'Is merging PDFs free?', a: 'It is here, with no account, no watermark on the output and no page cap. The work runs on your own computer, so there is no server cost to pass on.' },
    ],
    related: ['combine-pdf-files-without-losing-quality', 'how-to-rearrange-pages-in-a-pdf', 'how-to-split-a-pdf-into-separate-pages'],
  },

  {
    slug: 'combine-pdf-files-without-losing-quality',
    title: 'How to Combine PDF Files Without Losing Quality',
    description: 'Merged PDFs should look identical to the originals. Here is what causes quality loss when combining files, how to spot it, and how to avoid it entirely.',
    keyword: 'combine pdf files without losing quality',
    category: 'Merging & Organizing',
    published: '2026-02-19',
    tool: 'merge-pdf',
    blocks: [
      { type: 'p', text: 'A merge should be lossless. If your combined file looks worse than the documents that went into it, the tool did something it did not need to do.' },
      { type: 'p', text: 'Here is what actually happens inside a merge, why some tools degrade your pages, and how to check your result in under a minute.' },
      { type: 'h2', text: 'What a lossless merge does' },
      { type: 'p', text: 'A PDF is a collection of objects: page descriptions, embedded fonts, image streams, vector paths. A correct merge copies those objects from each source document into a new one and builds a fresh page tree pointing at them. Nothing is re-encoded. The image that was 300 DPI is still 300 DPI, the text is still text, and the file size of the result is roughly the sum of the inputs.' },
      { type: 'h2', text: 'What lossy tools do instead' },
      { type: 'p', text: 'Some tools take a shortcut: render every page to a bitmap, then assemble the bitmaps into a new PDF. It is far easier to implement and it works on anything, which is why it survives. The cost is severe:' },
      { type: 'list', items: [
        'Text stops being text. You cannot search it, select it, or copy from it.',
        'Screen readers can no longer read the document, so it fails accessibility requirements.',
        'Letters go soft as soon as anyone zooms in, because they are now pixels rather than outlines.',
        'File size often balloons, since a page of vector text becomes a full-page image.',
        'Links, bookmarks and form fields disappear entirely.',
      ] },
      { type: 'callout', title: 'The thirty-second test', text: 'Open your merged PDF and try to select a line of text with your cursor. If the text highlights, the merge was lossless. If your cursor draws a rectangle over an image instead, your pages were rasterised.' },
      { type: 'h2', text: 'Checks to run on the merged file' },
      { type: 'steps', items: [
        'Select some text on a page from each source document. It should highlight as text.',
        'Zoom to 400% on a heading. The edges should stay sharp, not pixelated.',
        'Compare the file size to the sum of the originals. Wildly larger means rasterisation; wildly smaller means recompression.',
        'Check the page count matches what you expect — a missing page is easier to catch now than after you send it.',
        'Page through the whole thing in a preview rather than trusting the first page.',
      ] },
      { type: 'h2', text: 'When your source files are already low quality' },
      { type: 'p', text: 'Merging cannot improve pages that were poor to begin with. If a scan went in at 72 DPI, it comes out at 72 DPI. People often blame the merge for softness that was already in the original — worth checking the source before assuming the tool is at fault.' },
      { type: 'p', text: 'If the underlying scans genuinely are poor, running them through OCR at least makes the text searchable, even though the image itself stays as it is.' },
      { type: 'h2', text: 'Merging and compressing are different jobs' },
      { type: 'p', text: 'If your merged file is too large to email, compress it as a separate, deliberate step rather than hoping the merge shrinks it. That way you choose the trade-off — how much image quality you are willing to give up — instead of having it chosen for you silently.' },
    ],
    faqs: [
      { q: 'Why is my merged PDF so much bigger than the originals?', a: 'Usually because each source file embedded its own copy of the same fonts, and the merge kept all of them. Running the result through an optimiser that de-duplicates shared resources typically recovers most of the difference.' },
      { q: 'Does merging compress images?', a: 'A lossless merge does not touch image data at all. If your images look worse afterwards, the tool re-encoded them, which is compression rather than merging.' },
      { q: 'Can I merge a scanned PDF with a digital one?', a: 'Yes, and the result keeps both as they were: the scanned pages stay images, the digital pages stay selectable text. The mix is completely normal in contracts where a signature page was printed and scanned back in.' },
      { q: 'Will the merged file open on every device?', a: 'Yes. A merged PDF is an ordinary PDF. As long as your source files opened, the combined one will too.' },
    ],
    related: ['how-to-merge-pdf-files', 'why-is-my-pdf-so-large', 'how-to-compress-a-pdf-without-losing-quality'],
  },

  {
    slug: 'how-to-split-a-pdf-into-separate-pages',
    title: 'How to Split a PDF Into Separate Pages',
    description: 'Break a PDF into single pages or custom ranges without installing anything. Covers page ranges, splitting scanned batches, and keeping quality intact.',
    keyword: 'how to split a pdf into separate pages',
    category: 'Merging & Organizing',
    published: '2026-02-11',
    updated: '2026-07-30',
    tool: 'split-pdf',
    blocks: [
      { type: 'p', text: 'Splitting a PDF turns one file into several. You might need every page as its own file, or you might need three specific chunks — a cover letter, a report and an appendix — pulled out of a single scanned batch.' },
      { type: 'p', text: 'Both are the same operation with different settings, and neither needs software installed.' },
      { type: 'h2', text: 'Split a PDF in three steps' },
      { type: 'steps', items: [
        'Open the Split PDF tool and drop your file in.',
        'Choose how to split: every page as its own file, or specific ranges such as 1-4, 5, 6-12.',
        'Run it. Multiple files come back as a ZIP so you get everything in one download.',
      ] },
      { type: 'h2', text: 'Page ranges, written correctly' },
      { type: 'p', text: 'Range syntax is where most people trip. The rules are simple once you have seen them:' },
      { type: 'table', head: ['You type', 'You get'], rows: [
        ['5', 'Just page 5'],
        ['1-10', 'Pages 1 through 10, inclusive of both ends'],
        ['1-3, 7, 10-12', 'Three separate chunks'],
        ['2-', 'Page 2 to the end of the document'],
      ] },
      { type: 'p', text: 'Page numbers here mean the position in the file, not whatever is printed on the page. A report whose body starts at printed page 1 but which has four pages of front matter has its printed page 1 at position 5.' },
      { type: 'h2', text: 'Splitting a scanned batch back into documents' },
      { type: 'p', text: 'The classic case: someone fed twenty separate letters through a sheet feeder and produced one sixty-page PDF. To recover the individual documents:' },
      { type: 'steps', items: [
        'Page through the scan and note where each document starts.',
        'Write those as ranges — 1-3, 4-4, 5-9 and so on.',
        'Split by ranges, and you get one file per document in a single ZIP.',
        'Rename the extracted files as you unpack them, while you still remember which is which.',
      ] },
      { type: 'callout', title: 'Watch for blank separator pages', text: 'Duplex scanners produce a blank back side for every single-sided sheet. Check whether your ranges include those blanks — and if the whole document is padded with them, remove the blank pages first and then split.' },
      { type: 'h2', text: 'Does splitting reduce quality?' },
      { type: 'p', text: 'No. Splitting copies whole page objects into new documents; the content is untouched. Selectable text stays selectable and images keep their original resolution.' },
      { type: 'p', text: 'One thing does change: file size does not divide evenly. Each output file has to carry a copy of every font used on its pages, so ten one-page files can add up to noticeably more than the ten-page original. That is expected, not a fault.' },
      { type: 'h2', text: 'Split, extract or remove?' },
      { type: 'table', head: ['Goal', 'Use'], rows: [
        ['Turn one file into many', 'Split PDF'],
        ['Pull a few pages out into one new file', 'Extract Pages'],
        ['Throw some pages away and keep the rest as one file', 'Remove Pages'],
        ['Change the order of pages', 'Organize PDF'],
      ] },
    ],
    faqs: [
      { q: 'Can I split a PDF into two halves?', a: 'Yes — give two ranges, such as 1-25 and 26-50 for a fifty-page file. If you do not know the page count, the tool shows it once your file is loaded.' },
      { q: 'How do I split a PDF without Adobe Acrobat?', a: 'Any browser-based split tool does it without installing anything. Acrobat is not required, and for a straightforward split it is considerably slower to open than a web page.' },
      { q: 'Will the split files keep the original password?', a: 'No. Unlock the document first, split it, and apply protection to the resulting files if they need it.' },
      { q: 'Can I split a PDF by bookmarks or chapters?', a: 'Not directly, but the outline tells you where each chapter starts. Read the starting pages off the bookmarks, then enter them as ranges.' },
      { q: 'Why is my split file bigger than a fair share of the original?', a: 'Because each new file embeds the fonts its pages need. Shared resources that were stored once in the original are now stored in every file that uses them.' },
    ],
    related: ['how-to-merge-pdf-files', 'extract-pages-from-pdf', 'how-to-delete-pages-from-a-pdf'],
  },

  {
    slug: 'extract-pages-from-pdf',
    title: 'How to Extract Pages From a PDF',
    description: 'Pull specific pages out of a PDF into a new file — one page, a range, or a scattered selection — without changing the original document.',
    keyword: 'extract pages from pdf',
    category: 'Merging & Organizing',
    published: '2026-03-14',
    tool: 'extract-pages',
    blocks: [
      { type: 'p', text: 'Extracting pages copies the pages you name into a new PDF and leaves the original exactly as it was. It is what you want when someone asks for "just the invoice" out of a forty-page pack.' },
      { type: 'h2', text: 'How to extract pages' },
      { type: 'steps', items: [
        'Open Extract Pages and add your PDF.',
        'Type the pages you want: a single number, a range like 12-18, or a mix such as 3, 9, 14-16.',
        'Extract. You get one new PDF containing those pages in the order you listed them.',
      ] },
      { type: 'p', text: 'The original file on your disk is never modified. If you want the pages gone from the source as well, that is a separate Remove Pages step afterwards.' },
      { type: 'h2', text: 'Extract, or split, or remove?' },
      { type: 'p', text: 'These three tools overlap enough to be confusing, so here is the distinction in one line each.' },
      { type: 'list', items: [
        'Extract Pages: keep some pages, get one new file, original untouched.',
        'Split PDF: break the whole document into several files at once.',
        'Remove Pages: keep the document but delete pages you do not want.',
      ] },
      { type: 'h2', text: 'Common reasons to extract' },
      { type: 'table', head: ['Situation', 'What to extract'], rows: [
        ['Sending one invoice from a monthly statement pack', 'The two or three pages of that invoice'],
        ['Sharing a single chapter of a report', 'The chapter\'s page range'],
        ['Submitting one form page from a long application', 'The single signed page'],
        ['Pulling the appendix out for a separate reviewer', 'The tail range, e.g. 40-'],
      ] },
      { type: 'callout', title: 'Extraction is not redaction', text: 'Pulling out page 12 removes the other pages, but anything sensitive printed on page 12 itself is still there. If the page contains details the recipient should not see, redact them properly before you send it.' },
      { type: 'h2', text: 'Getting the page numbers right' },
      { type: 'p', text: 'Extract by position in the file, not by the number printed on the page. Cover pages, blank versos and unnumbered front matter all shift the two apart. Open the file, scroll to the page you want, and read the position from your reader\'s page counter rather than the footer.' },
      { type: 'p', text: 'When in doubt, extract a wider range than you need and check the result before sending it. It is much cheaper than sending the wrong page.' },
    ],
    faqs: [
      { q: 'Does extracting pages change the original PDF?', a: 'No. Extraction reads the source and writes a new file. Your original is untouched on disk.' },
      { q: 'Can I extract pages in a different order than they appear?', a: 'Yes — list them in the order you want. Entering 9, 3, 5 produces a file whose pages run in that sequence.' },
      { q: 'Do extracted pages keep their form fields and links?', a: 'Page content always comes across. Links that pointed to pages you did not extract have nowhere to go and will stop working, and form fields can lose behaviour that depended on the rest of the document.' },
      { q: 'How do I extract every page as a separate file?', a: 'That is a split rather than an extract. Use Split PDF with the one-file-per-page option.' },
    ],
    related: ['how-to-split-a-pdf-into-separate-pages', 'how-to-delete-pages-from-a-pdf', 'how-to-redact-a-pdf-properly'],
  },
];
