import type { BlogPost } from '../types';

export const mobilePdfGuidesPosts: BlogPost[] = [
  // Article 1: How to Convert PDF to Word on iPhone
  {
    slug: 'how-to-convert-pdf-to-word-on-iphone',
    title: 'How to Convert PDF to Word on iPhone (Free, No App)',
    description: 'Turn a PDF into an editable Word document on your iPhone for free. Convert in your browser, no app install or account needed.',
    keyword: 'how to convert pdf to word on iphone',
    category: 'Converting',
    published: '2026-08-31',
    tool: 'pdf-to-word',
    blocks: [
      { type: 'p', text: 'A contract, a study guide, or a form arrives as a PDF on your iPhone and you need to edit the text in Word. The iPhone does not include a built-in PDF to Word converter, and many apps bury the feature behind a subscription or a watermark. You do not need to install anything to get an editable Word file.' },
      { type: 'p', text: 'Here is how to convert a PDF to Word on your iPhone for free, right in your browser.' },
      { type: 'h2', text: 'Your options on an iPhone' },
      { type: 'list', items: [
        'Microsoft Word for iOS can open a text-based PDF and convert it, but it works best on simple documents and struggles with scanned pages',
        'Many \"free\" PDF apps limit Word conversion behind paywalls or add watermarks',
        'A browser-based converter runs in Safari with no app download, no account, and no upload',
      ] },
      { type: 'callout', title: 'Browser conversion is the no-install route', text: 'A browser-based PDF to Word tool works in Safari on your iPhone, so there is nothing to download from the App Store. Your file is processed locally, which keeps a sensitive contract on your device.' },
      { type: 'h2', text: 'Convert a PDF to Word on iPhone in Safari' },
      { type: 'p', text: 'Open a browser-based converter and you can turn your PDF into an editable DOCX in under a minute:' },
      { type: 'steps', items: [
        'Open the PDF to Word tool in Safari on your iPhone.',
        'Tap to choose a file, then select your PDF from the Files app, iCloud Drive, or your cloud storage.',
        'Select Word as the output format and tap convert.',
        'When it finishes, download the DOCX back to your device.',
        'Open the Word file in Word, Pages, or Google Docs to edit it.',
      ] },
      { type: 'p', text: 'The converted Word document keeps your text, headings, and basic layout so you can make changes instead of retyping the whole thing.' },
      { type: 'h2', text: 'Converting scanned PDFs from your iPhone' },
      { type: 'p', text: 'If your PDF is a scanned page or a photo of a printed document, its text is stored as an image, not as selectable text. A standard converter can only embed that image. For a scanned file you first need to run OCR to extract the text, then convert the result to Word — a separate OCR tool handles that step.' },
      { type: 'h2', text: 'What to do after converting' },
      { type: 'p', text: 'Once you have the editable Word file, review the layout before sharing it — conversions can occasionally shift a table or heading. If you need the final document back as a PDF, convert the edited Word file the other way when you are ready to send it.' },
    ],
    faqs: [
      { q: 'Can I convert a PDF to Word on my iPhone for free?', a: 'Yes. A browser-based PDF to Word converter runs in Safari with no app to install and no account, letting you download an editable Word file.' },
      { q: 'Does the iPhone have a built-in PDF to Word converter?', a: 'No. You can open a text-based PDF in the Word app for a conversion, but a browser-based tool works with no download and no sign-up.' },
      { q: 'Why does my converted Word file show a scanned image instead of text?', a: 'If the PDF is a scan or photo, the text is an image. Run OCR first to extract the text, then convert the result to Word.' },
      { q: 'Is my PDF uploaded to a server when I convert it?', a: 'No. When the conversion runs in your browser, your document is processed locally on your iPhone and never leaves your device.' },
      { q: 'Can I convert a Word file back to PDF on my iPhone?', a: 'Yes. Once you have finished editing the Word document, you can convert it back to PDF when you are ready to share the final version.' },
    ],
    related: ['how-to-convert-pdf-to-word-without-losing-formatting', 'how-to-convert-a-pdf-into-editable-text', 'how-to-convert-word-to-pdf-without-losing-formatting', 'how-to-make-a-pdf-on-iphone'],
  },

  // Article 2: How to Compress a PDF on iPhone
  {
    slug: 'how-to-compress-a-pdf-on-iphone',
    title: 'How to Compress a PDF on iPhone (Free, No App)',
    description: 'Shrink a large PDF on your iPhone for free without installing an app. Reduce email and upload size right in Safari.',
    keyword: 'how to compress a pdf on iphone',
    category: 'Compressing',
    published: '2026-08-31',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: 'A PDF that is too large to attach, upload, or share stops you cold on an iPhone — an email bounces, a portal rejects the file, or it fills your iCloud storage. Fortunately you do not need to download a compressor app to fix it.' },
      { type: 'p', text: 'Here is how to compress a PDF on your iPhone for free, without installing anything.' },
      { type: 'h2', text: 'Your compression options on iPhone' },
      { type: 'list', items: [
        'The Files app has a Quick Action called Optimize File Size that compresses a PDF with one tap',
        'A browser-based compressor in Safari gives you control over how much to shrink the file',
        'Many App Store compressors hide the useful features behind subscriptions or add watermarks',
      ] },
      { type: 'callout', title: 'Browser compression keeps quality control', text: 'The Files Quick Action applies a fixed level of compression with no settings. A browser-based tool lets you choose how aggressively to compress and preserves the original file, so you can compare before sharing.' },
      { type: 'h2', text: 'Compress a PDF on iPhone in Safari' },
      { type: 'p', text: 'Open a browser-based compressor and shrink the file in seconds — your document is processed on your phone, so it never has to be uploaded anywhere:' },
      { type: 'steps', items: [
        'Open the Compress PDF tool in Safari on your iPhone.',
        'Tap to choose a file, then select your PDF from the Files app or iCloud Drive.',
        'Pick a compression level — light keeps text and images crisp, while heavier compression makes the smallest file.',
        'Tap compress and review the new file size.',
        'Download the smaller PDF back to your device and share it from the Files app.',
      ] },
      { type: 'p', text: 'This works even for a document that arrived as an email attachment: save it to Files first, then open it in the compressor.' },
      { type: 'h2', text: 'Using the built-in Files Quick Action' },
      { type: 'p', text: 'For a very quick fix with no quality options, open the Files app, long-press the PDF, tap Quick Actions, then Optimize File Size. It replaces the file with a smaller version and needs no app at all. Because it overwrites the original, duplicate the PDF first if you want to keep the uncompressed copy.' },
      { type: 'h2', text: 'Start small at the source' },
      { type: 'p', text: 'If even strong compression will not get the file small enough, re-scan or re-save it with less detail — lower resolution and grayscale for a scan cuts size dramatically. Compressing then becomes a final polish instead of a battle, and the result stays readable.' },
    ],
    faqs: [
      { q: 'How do I make a PDF smaller on my iPhone for free?', a: 'Open a browser-based compressor in Safari, upload the PDF, choose a compression level, and download the smaller file. No app installation needed.' },
      { q: 'Does the iPhone have a built-in PDF compressor?', a: 'The Files app includes an Optimize File Size Quick Action that compresses a PDF, though it provides no quality control and overwrites the original.' },
      { q: 'Does compressing a PDF on iPhone lose quality?', a: 'Light compression keeps text and images crisp. Heavier compression can soften scanned images, so preview the result before sending it.' },
      { q: 'Can I compress a PDF that arrived as an email attachment?', a: 'Yes. Save the attachment to the Files app first, then open it in a browser-based compressor to shrink it.' },
      { q: 'Is my PDF uploaded to a server when I compress it?', a: 'No. When the compression runs in your browser, your document is processed locally on your iPhone and never leaves your device.' },
    ],
    related: ['how-to-compress-a-pdf-without-losing-quality', 'how-to-compress-a-pdf-under-1mb', 'how-to-reduce-pdf-file-size-to-100kb', 'how-to-reduce-pdf-size-without-adobe'],
  },

  // Article 3: How to Sign a PDF on Mac
  {
    slug: 'how-to-sign-a-pdf-on-mac',
    title: 'How to Sign a PDF on Mac (Free, No Adobe)',
    description: 'Sign a PDF on a Mac for free with Preview or a browser tool. Draw, type, or upload your signature in seconds without Adobe.',
    keyword: 'how to sign a pdf on mac',
    category: 'Editing & Signing',
    published: '2026-08-31',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'A contract, a consent form, or a permission slip arrives as a PDF and needs your signature. On a Mac you do not need Adobe or a printing-and-scanning trip — the built-in Preview app lets you create and place an electronic signature for free.' },
      { type: 'p', text: 'Here is how to sign a PDF on a Mac with Preview, plus a browser-based option when you want more control.' },
      { type: 'h2', text: 'Sign a PDF with Preview (built into every Mac)' },
      { type: 'p', text: 'Preview ships with every Mac and includes a signature tool that captures, stores, and places your signature:' },
      { type: 'steps', items: [
        'Open the PDF in Preview (double-click the file, or right-click and choose Open With > Preview).',
        'Click the Markup toolbar icon (the pen-tip button), then click the Signature icon.',
        'Choose Create Signature, then pick how to capture it — draw with your finger on the trackpad, hold a signed paper sheet up to the camera, or sign on a nearby iPhone or iPad.',
        'Click your saved signature to place it on the page, then drag it into position and resize with the handles.',
        'Press Command + S to save the signed PDF.',
      ] },
      { type: 'callout', title: 'Preview remembers your signature', text: 'Once you create a signature in Preview, it is saved and available for future documents — you can place it on any PDF with one click instead of redrawing it each time.' },
      { type: 'h2', text: 'Signing with a browser tool for more control' },
      { type: 'p', text: 'Preview is excellent on your own Mac, but it only lets you draw a freehand signature — there is no typed option and no way to reuse a saved signature image outside Preview. A browser-based signer gives you draw, type, and upload options, and it runs entirely in the browser tab with nothing stored on the machine.' },
      { type: 'steps', items: [
        'Open the Sign PDF tool in Safari or Chrome on your Mac.',
        'Drag your PDF from Finder into the upload area, or click to browse and select it.',
        'Choose to draw, type, or upload an image of your signature.',
        'Drag the signature into place on the signature line.',
        'Download the signed PDF.',
      ] },
      { type: 'h2', text: 'Is a Mac electronic signature legally binding?' },
      { type: 'p', text: 'In most countries an electronic signature is just as binding as a handwritten one as long as it identifies you and shows you agreed to the content. What matters is your intent to sign, not the exact shape of the mark. If a document explicitly requires a physical signature, confirm with the other party first.' },
      { type: 'h2', text: 'More signing tasks on a Mac' },
      { type: 'p', text: 'Beyond adding a signature you might need to add initials, fill in form fields, or protect a signed document from edits. Preview handles basic signing and form filling, and a browser tool covers the rest without installing a heavyweight PDF editor.' },
    ],
    faqs: [
      { q: 'Can I sign a PDF on a Mac for free?', a: 'Yes. Preview, included with every Mac, has a built-in signature tool — draw on the trackpad, use the camera, or sign on a nearby iPhone, then place and save it.' },
      { q: 'Does Preview store my signature?', a: 'Yes. Preview saves your signature and makes it available for future documents, so you can place it on any PDF with one click.' },
      { q: 'Do I need Adobe to sign a PDF on a Mac?', a: 'No. Preview covers free signing, and a browser-based signer adds draw, type, and upload options without installing anything.' },
      { q: 'Is signing a PDF on a Mac legally binding?', a: 'Electronic signatures are generally as binding as handwritten ones when they identify you and show your intent. Confirm with the other party if the document demands a physical signature.' },
      { q: 'Can I sign multiple pages or add initials?' , a: 'Yes. Place your saved signature on each page you need, and use a filling tool to add initials or additional text as required.' },
    ],
    related: ['how-to-sign-a-pdf-electronically', 'how-to-sign-a-pdf-on-iphone', 'how-to-add-a-handwritten-signature-to-a-pdf', 'how-to-sign-a-pdf-electronically-for-free'],
  },

  // Article 4: How to Edit a PDF on iPhone
  {
    slug: 'how-to-edit-a-pdf-on-iphone',
    title: 'How to Edit a PDF on iPhone (Free, In-Browser)',
    description: 'Edit a PDF on your iPhone for free in Safari. Add text, annotations, and signatures without installing an app.',
    keyword: 'how to edit a pdf on iphone',
    category: 'Editing & Signing',
    published: '2026-08-31',
    tool: 'edit-pdf',
    blocks: [
      { type: 'p', text: 'A form, contract, or report arrives as a PDF on your iPhone and you need to fill it in, correct a detail, or add notes before sending it back. Many people assume this needs a paid app, but you can edit a PDF on an iPhone for free without installing anything.' },
      { type: 'p', text: 'Here is what you can edit with the built-in tools, and how to do more in your browser.' },
      { type: 'h2', text: 'What the built-in iPhone tools can do' },
      { type: 'list', items: [
        'The Files app opens a PDF and gives you Markup tools to add text, signatures, highlights, and drawings',
        'You can fill in blank form fields by tapping and typing',
        'Rotate, delete, and reorder pages inside the PDF viewer',
        'Notes can embed a PDF for basic mark-up alongside your own notes',
      ] },
      { type: 'callout', title: 'The built-in tools do not rewrite text', text: 'Apple\u2019s native tools overlay new text and annotations, but they cannot change the original text inside a PDF. For that you need a browser-based editor that processes the document on your device.' },
      { type: 'h2', text: 'Add text, highlights, and a signature with Files' },
      { type: 'steps', items: [
        'Open the Files app and tap the PDF you want to edit.',
        'Tap the Markup (pen-tip) icon to open the editing toolbar.',
        'Tap the + button to add a text box, then drag and resize it on the page.',
        'Use the highlighter or pen to mark sections, or insert your signature.',
        'Tap Done to save your edited PDF.',
      ] },
      { type: 'p', text: 'These built-in tools are perfect for filling out forms, signing documents, and adding quick notes — all without downloading anything.' },
      { type: 'h2', text: 'Edit PDF text on iPhone in your browser' },
      { type: 'p', text: 'When you need to change the actual content of the document, a browser-based editor gives you more control. It runs in Safari, requires no app, and processes the file locally so a sensitive document stays on your phone:' },
      { type: 'steps', items: [
        'Open the Edit PDF tool in Safari on your iPhone.',
        'Tap to choose a file, then select your PDF from the Files app.',
        'Select the text or area you want to change and type the new content, or add annotations as needed.',
        'Download the edited PDF and share it.',
      ] },
      { type: 'h2', text: 'Keep a copy before you edit' },
      { type: 'p', text: 'Edits made in the Files app overwrite the original PDF, so duplicate the file first (long-press it and choose Duplicate) if you might need the unedited version. Save a copy before making bigger changes in an editor, and share the finished file only after you have checked it.' },
    ],
    faqs: [
      { q: 'Can I edit a PDF on my iPhone for free?', a: 'Yes. The built-in Files app lets you add text, highlights, drawings, and signatures for free, and a browser-based tool handles text edits without installing an app.' },
      { q: 'Does the iPhone have a built-in PDF editor?', a: 'Yes. The Files app includes Markup tools for adding text boxes, signatures, highlights, and drawings, plus page rotation and page management.' },
      { q: 'Can I change the original text inside a PDF on iPhone?', a: 'The native tools only add new content on top. To edit the existing text, use a browser-based PDF editor that processes the document on your device.' },
      { q: 'Is my PDF uploaded to a server when I edit it?', a: 'No. When the editing runs in your browser, your document is processed locally on your iPhone and never leaves your device.' },
      { q: 'How do I keep the original PDF when editing?', a: 'Duplicate the file in the Files app before editing, so you can always recover the unedited version.' },
    ],
    related: ['how-to-make-a-pdf-on-iphone', 'how-to-sign-a-pdf-on-iphone', 'how-to-fill-out-a-pdf-form', 'how-to-add-text-to-a-pdf'],
  },

  // Article 5: How to Convert Word to PDF on iPhone
  {
    slug: 'how-to-convert-word-to-pdf-on-iphone',
    title: 'How to Convert Word to PDF on iPhone (Free, No App)',
    description: 'Turn a Word document into a PDF on your iPhone for free. Convert in your browser or with the Pages app, no install needed.',
    keyword: 'how to convert word to pdf on iphone',
    category: 'Converting',
    published: '2026-08-31',
    tool: 'word-to-pdf',
    blocks: [
      { type: 'p', text: 'You wrote a document, maybe a resume, a report, or a final essay, and now you need to send it as a PDF because PDFs open with the layout intact on any device. On an iPhone you have a couple of quick, free ways to convert a Word document to PDF without installing a new app.' },
      { type: 'p', text: 'Here is how to convert Word to PDF on an iPhone for free.' },
      { type: 'h2', text: 'Convert a Word document in the Pages app' },
      { type: 'p', text: 'If the document is a .docx file, the free Pages app that comes with your iPhone can open and export it as a PDF:' },
      { type: 'steps', items: [
        'Open the Pages app on your iPhone, or open the .docx file from the Files app.',
        'Tap Export in the Share menu once the document is open.',
        'Choose PDF as the export format.',
        'Save the PDF to the Files app or share it directly by email or message.',
      ] },
      { type: 'p', text: 'Pages preserves headings, images, and formatting well, making it a dependable choice for documents you already have on your iPhone.' },
      { type: 'h2', text: 'Convert Word to PDF in Safari (any .docx)' },
      { type: 'p', text: 'If you would rather not open Pages, a browser-based converter converts many Word documents to PDF in one step. It runs in Safari, needs no app download, and processes the file locally so your document stays on your phone:' },
      { type: 'steps', items: [
        'Open the Word to PDF tool in Safari on your iPhone.',
        'Tap to choose a file, then select your .docx document from the Files app or iCloud Drive.',
        'Confirm Word as the input format and tap convert.',
        'Download the finished PDF back to your device.',
      ] },
      { type: 'p', text: 'This is especially handy when a document arrives in Mail or Messages and you want to forward it as a PDF — save the attachment to Files, then convert it in your browser.' },
      { type: 'h2', text: 'What about a PDF, Excel, or PowerPoint file?' },
      { type: 'p', text: 'The same approach works for other file types. You can convert a PDF back to Word to edit it, or turn spreadsheets and slide decks into PDF so they open cleanly anywhere. Each format has its own dedicated browser tool, so you can handle them all from your iPhone without installing apps.' },
      { type: 'h2', text: 'Check the layout before you send it' },
      { type: 'p', text: 'After converting, open the PDF once and check that images, tables, and headings landed where you expect. PDF is meant to look identical everywhere, but a quick review catches any surprise before it reaches the recipient.' },
    ],
    faqs: [
      { q: 'Can I convert a Word document to PDF on my iPhone for free?', a: 'Yes. The built-in Pages app exports a .docx as a PDF, and a browser-based converter handles it too — neither needs a new app or an account.' },
      { q: 'Does the iPhone come with a Word to PDF converter?', a: 'The Pages app, included free with iOS, opens Word documents and exports them as PDFs with your layout intact.' },
      { q: 'Can I convert a Word file that arrived as an email attachment?', a: 'Yes. Save the attachment to the Files app first, then open it in Pages or a browser-based converter to turn it into a PDF.' },
      { q: 'Is my Word document uploaded to a server when I convert it?', a: 'No. Pages works entirely on your device, and a browser-based converter processes the file locally so it never leaves your iPhone.' },
      { q: 'Can I convert other file types to PDF on iPhone?', a: 'Yes. Excel and PowerPoint files can also be turned into PDF, so they open with the same layout on any device.' },
    ],
    related: ['how-to-convert-word-to-pdf-without-losing-formatting', 'how-to-convert-pdf-to-word-without-losing-formatting', 'how-to-make-a-pdf-on-iphone', 'how-to-convert-a-web-page-to-pdf'],
  },
];
