import type { BlogPost } from '../types';

export const newPosts14: BlogPost[] = [
  // Article 1: Scan documents to PDF with your phone
  {
    slug: 'how-to-scan-documents-to-pdf-with-your-phone',
    title: 'How to Scan Documents to PDF With Your Phone (Free)',
    description: 'Scan documents to PDF with your phone for free, right in your browser — auto-detects each page, straightens it, and saves a multi-page PDF on your device.',
    keyword: 'how to scan documents to pdf with your phone',
    category: 'Converting',
    published: '2026-09-19',
    tool: 'scan-pdf',
    experience: 'I scan contracts, receipts, and signed pages into PDFs from my phone several times a week. The camera tool that auto-detects and straightens the page before it captures is what turned scanning from a chore into a two-second habit for me.',
    blocks: [
      { type: 'p', text: "A document needs to become a PDF and the only thing near you is a phone. That is enough — a modern phone camera produces a perfectly adequate scan, and you can do the whole job free inside a browser without installing a scanner app or signing up anywhere." },
      { type: 'p', text: "Here is how to scan documents to PDF with your phone, step by step." },
      { type: 'h2', text: 'What a good phone scan needs' },
      { type: 'p', text: 'A scanner app does two useful things: it detects the edges of the page so the photo is cropped tight, and it straightens the perspective so a photo taken at an angle becomes a flat, square document. Without those two steps, scanning on a phone produces photos, not documents.' },
      { type: 'steps', items: [
        'Open the Scan PDF tool in your phone’s browser.',
        'Allow camera access when the browser asks — permission is granted once and reused next time.',
        'Hold the phone above the page, roughly parallel to it, and centre it in the frame.',
        'Let the detector outline the page; it turns green when it is stable and captures automatically (or use the shutter button).',
        'Rotate, switch filters, or retake on the review screen, then tap Save.',
        'Scan the rest of the pages the same way, then hit Done and download the PDF.',
      ] },
      { type: 'callout', title: 'Nothing leaves your phone', text: 'When the scanner runs in your browser, the camera feed and the finished pages are processed on the device. Your contract or receipt never crosses the network, so there is no upload to worry about even for sensitive documents.' },
      { type: 'h2', text: 'Tips that make auto-detection work first time' },
      { type: 'list', items: [
        'Put the page on a desk rather than holding it in your hand — steadying the shoot is half the battle',
        'Keep the whole page inside the frame with a small margin around the edges',
        'Use even lighting; a page in strong shadows or with a glare stripe slows detection down',
        'Press the shutter yourself when the outline wobbles — you can still proceed and straighten in the review step',
      ] },
      { type: 'h2', text: 'Scanning several pages into one PDF' },
      { type: 'p', text: 'Do not create a PDF per page. Leave the camera open after saving a page, hold the next one in view, and let it capture again. Every saved page is added to the same document, and the counter and thumbnail strip up top show your progress. Tap Done once the stack is complete and you get a single multi-page PDF.' },
      { type: 'h2', text: 'Straighten what the detector misses' },
      { type: 'p', text: 'If a page is captured at an angle or the edges are slightly off, rotate it on the review screen before saving. For pages that come out too dark or too light, the Magic and B&W filters clean them up without needing a photo editor afterwards.' },
      { type: 'h2', text: 'After the scan' },
      { type: 'p', text: 'The finished PDF is ready to email, upload to a portal, or store in cloud storage straight from your phone. If the file comes out large — a scan of a photo-heavy page — run it through a compressor to shave the size before sending.' },
    ],
    faqs: [
      { q: 'How do I scan a document to PDF with my phone for free?', a: 'Open a browser-based scanner on your phone, allow camera access, frame the page, and let it auto-capture after detecting the edges. Review and save each page, then download the finished PDF — no app and no sign-up needed.' },
      { q: 'Is phone scanning good enough for official documents?', a: 'Yes for most purposes, if the photo is sharp, evenly lit, and straightened. The detector crops and perspective-corrects the page so the result reads like a flat scan rather than a photo.' },
      { q: 'Can I scan several pages into one PDF?', a: 'Yes. Keep the camera open after saving a page and scan the rest; every page is added to the same PDF, which you download as one multi-page file.' },
      { q: 'Do I have to install a scanner app?', a: 'No. The scanning runs in your phone’s browser. The camera feed and images are processed on the device, so nothing is uploaded.' },
      { q: 'Why does the scanner sometimes not detect my page?', a: 'Low light, glare, or extra objects in the frame can confuse detection. Put the page on a flat surface in even light, fill the frame, and hold still — or tap the shutter to capture manually and straighten in the review step.' },
    ],
    related: ['how-to-scan-a-document-to-pdf-on-iphone', 'how-to-scan-multiple-pages-into-one-pdf', 'how-to-make-a-scanned-pdf-searchable', 'how-to-compress-a-scanned-pdf'],
  },

  // Article 2: Scan a document to PDF on iPhone
  {
    slug: 'how-to-scan-a-document-to-pdf-on-iphone',
    title: 'How to Scan a Document to PDF on iPhone (Free)',
    description: 'Scan a document to PDF on your iPhone for free without an app — use the built-in Notes scanner, or an in-browser scanner with auto page detection that runs on your device.',
    keyword: 'how to scan a document to pdf on iphone',
    category: 'Converting',
    published: '2026-09-19',
    tool: 'scan-pdf',
    experience: 'I scan documents to PDF on my iPhone when forms and contracts arrive on paper. The built-in Notes scanner handles quick jobs, and I use an in-browser scanner with auto page detection when I want fine control over filters, rotation, and multiple pages in one file.',
    blocks: [
      { type: 'p', text: 'A paper document needs to become a PDF and you have an iPhone in your pocket — that is a complete workflow by itself. iPhone can scan documents to PDF for free in two ways: the scanner built into the Notes app, and a browser-based scanner with auto-detection that runs entirely on the device.' },
      { type: 'p', text: 'Here is how to scan a document to PDF on your iPhone, both ways.' },
      { type: 'h2', text: 'Scan with the built-in Notes app' },
      { type: 'p', text: 'Every iPhone ships with a document scanner hidden inside Notes. It needs no download and produces a PDF you can share anywhere:' },
      { type: 'steps', items: [
        'Open Notes and start a new note (or reuse an existing one).',
        'Tap the camera icon in the toolbar, then tap Scan Documents.',
        'Hold the iPhone over the page — the yellow auto-detector frames it and captures when it focuses.',
        'Keep scanning pages; each is added to the same document.',
        'Tap Save, then tap the document thumbnail and choose Export as PDF (or long-press it and pick Share).',
        'Share to Files for a permanent copy, or AirDrop/email the PDF.',
      ] },
      { type: 'p', text: 'The Notes scanner is quick and automatic, and it is the best zero-setup option for a document staying inside Apple’s ecosystem.' },
      { type: 'h2', text: 'Scan in Safari with auto page detection' },
      { type: 'p', text: 'For more control — filters, rotation before saving, and a review step before each page is locked in — a browser-based scanner runs in Safari:' },
      { type: 'steps', items: [
        'Open the Scan PDF tool in Safari on your iPhone.',
        'Tap Open camera and allow camera access when prompted.',
        'Centre the page in the frame and hold steady while the detector outlines it.',
        'The outline turns green when stable and captures automatically, or tap the shutter for a manual shot.',
        'On the adjust screen, rotate or apply a filter, then tap Save; keep going for more pages.',
        'Tap Done and download the finished PDF to Files.',
      ] },
      { type: 'callout', title: 'Everything happens on your iPhone', text: 'A browser-based scanner processes the camera feed and pages locally on the device — the document is never uploaded to a server. That keeps sensitive scans private by default.' },
      { type: 'h2', text: 'Which scanner should you use?' },
      { type: 'table', head: ['Need', 'Use', 'Why'], rows: [
        ['Quick scan into iCloud', 'Notes app', 'Zero setup and keeps a copy in your notes'],
        ['Multiple pages + one PDF', 'Browser scanner', 'Builds the whole multi-page file before you download'],
        ['Filters and rotation before saving', 'Browser scanner', 'Adjust each page on a review screen first'],
        ['Sharing as a clean PDF file', 'Either', 'Both export a standard PDF that opens anywhere'],
      ] },
      { type: 'h2', text: 'Make the result smaller if needed' },
      { type: 'p', text: 'A scan of a dense page can land at a few megabytes, which is over some email limits. Compress the finished PDF in your browser afterwards to bring it under the limit without visibly hurting text.' },
    ],
    faqs: [
      { q: 'How do I scan a document to PDF with an iPhone for free?', a: 'Open the Notes app, tap the camera icon, and choose Scan Documents. Scan the pages, then use Share to save the document as a PDF. Safari-based scanners do the same with more control.' },
      { q: 'Where does the Notes scanner save scans?', a: 'Inside the note you scanned them into. Export the document with Share to save it as a standalone PDF in Files, or send it directly.' },
      { q: 'Can I scan multiple pages into one PDF on iPhone?', a: 'Yes. Continue scanning in the Notes app and every page joins the same document; a browser-based scanner does the same and delivers one multi-page PDF.' },
      { q: 'Do I need a scanner app?', a: 'No. The Notes app has scanning built in, and browser-based scanners run in Safari with no install.' },
      { q: 'Is my scan uploaded anywhere?', a: 'The Notes scanner stores scans in your iCloud account. A browser-based scanner processes the document on your iPhone with no upload to a server.' },
    ],
    related: ['how-to-scan-documents-to-pdf-with-your-phone', 'how-to-make-a-scanned-pdf-searchable', 'how-to-reduce-pdf-file-size-on-iphone', 'how-to-compress-a-scanned-pdf'],
  },

  // Article 3: Scan multiple pages into one PDF
  {
    slug: 'how-to-scan-multiple-pages-into-one-pdf',
    title: 'How to Scan Multiple Pages Into One PDF (Free)',
    description: 'Scan multiple pages into one PDF for free — auto-capture each page, review and adjust on the fly, and download a single multi-page PDF from your phone or computer.',
    keyword: 'how to scan multiple pages into one pdf',
    category: 'Converting',
    published: '2026-09-19',
    tool: 'scan-pdf',
    experience: 'I scan multi-page agreements and book chapters to PDF from my phone rather than walking to a copier. Keeping the camera open and letting the tool auto-capture page after page into a single file is the workflow I actually use week in, week out.',
    blocks: [
      { type: 'p', text: 'A contract is twenty pages. A mortgage file is forty. Creating a separate PDF for each page defeats the whole point — a multi-page document should come out as a single PDF you can email, file, or sign as one object. Your phone can produce exactly that, for free, without extra apps.' },
      { type: 'p', text: 'Here is how to scan multiple pages into one PDF in a single pass.' },
      { type: 'h2', text: 'Scan all pages before downloading' },
      { type: 'p', text: 'The trick is not to download after every page. A scanner that keeps the camera open between captures adds each page to the same working document, so the whole stack becomes one file at the end:' },
      { type: 'steps', items: [
        'Open the Scan PDF tool on your phone — the camera stays live the whole time.',
        'Frame the first page, let auto-detection outline it, and save it from the review screen.',
        'Turn to the next page and repeat; the counter up top shows the growing page count.',
        'If a page is sideways or the lighting is bad, fix it with rotate or a filter before saving.',
        'When every page is in, tap Done.',
        'Download the finished PDF — it contains all the pages as one document.',
      ] },
      { type: 'list', items: [
        'Tap the thumbnail strip to jump back and check pages you already scanned',
        'Rework a page any time by rescanning and saving again',
        'The order you save pages in becomes the order in the PDF',
      ] },
      { type: 'callout', title: 'One pass, one file', text: 'Because each page is captured into the same browser session, there is no separate merging step afterwards. Long documents stay together from the first frame to the final PDF.' },
      { type: 'h2', text: 'Two ways to capture each page' },
      { type: 'p', text: 'For speed, leave auto-scan on and simply hold the page steady — the detector waits for the frame to settle, then captures on its own. For tricky pages with glare or clutter, switch auto-scan off and tap the shutter instead; you still get the review screen either way.' },
      { type: 'h2', text: 'Keep the file size in check' },
      { type: 'p', text: 'A thirty-page scan adds up quickly, especially when pages are photo-heavy. Run the finished PDF through a compressor and pick the Recommended level — text usually stays sharp while the file shrinks by over half, which also makes it easy to email as one attachment.' },
    ],
    faqs: [
      { q: 'How do I scan multiple pages into one PDF?', a: 'Open a browser-based scanner, keep the camera open, and save each page as you go. Every saved page joins the same document, which you download once as a single multi-page PDF.' },
      { q: 'Can I scan a 20-page document as one PDF on my phone?', a: 'Yes. As long as you leave the camera open between pages, the tool adds each capture to the same file — there is no practical limit on page count.' },
      { q: 'Do I need to merge the pages afterwards?', a: 'No. Pages scanned in the same session are already one PDF; the separate merge step only exists when you have a collection of single-page files to combine.' },
      { q: 'How do I make sure pages are the right way up?', a: 'Rotate each page on the review screen before saving it. Pages that land sideways in the camera can be corrected there instead of later in a separate tool.' },
      { q: 'Why is my multi-page PDF so large?', a: 'Each page is a full-quality image. Run the finished file through a compressor and choose the Recommended level to shrink it without obviously reducing text quality.' },
    ],
    related: ['how-to-merge-pdf-files', 'how-to-combine-scanned-documents-into-one-pdf', 'how-to-scan-documents-to-pdf-with-your-phone', 'how-to-reverse-page-order-in-a-pdf'],
  },

  // Article 4: Scan a receipt to PDF
  {
    slug: 'how-to-scan-a-receipt-to-pdf',
    title: 'How to Scan a Receipt to PDF (Free)',
    description: 'Scan a receipt to PDF for free on your phone — snap it, let auto-detection crop the edges, apply a B&W filter for clean copy, and keep your expenses in one file.',
    keyword: 'how to scan a receipt to pdf',
    category: 'Converting',
    published: '2026-09-19',
    tool: 'scan-pdf',
    experience: 'I scan receipts to PDF for expense claims and tax files instead of hoarding paper. Thermal receipts fade within months, so turning them into a PDF the day you get them is the only copy that actually survives.',
    blocks: [
      { type: 'p', text: 'Receipts are the paper documents most likely to be lost — and the most likely to fade, thanks to thermal printing. Scanning them to PDF the day you get them produces a permanent, legible copy that survives in your filing system, your email, or your expenses tool.' },
      { type: 'p', text: 'Here is how to scan a receipt to PDF for free from your phone.' },
      { type: 'h2', text: 'Snap and straighten in one take' },
      { type: 'steps', items: [
        'Lay the receipt flat on a contrasting surface — a dark desk under a white receipt works well.',
        'Open the Scan PDF tool on your phone and point the camera at the receipt.',
        'Position the camera so the whole receipt is inside the frame, then let it auto-capture.',
        'On the review screen, rotate it if it came in sideways.',
        'Try the B&W filter — it turns a washed-out thermal print into crisp black text on white.',
        'Save and download a single-page PDF.',
      ] },
      { type: 'p', text: 'Receipts are long and narrow, which is exactly what page detection is for: it crops away the desk around the paper and returns a tight, straight document instead of a photo of a crumpled strip.' },
      { type: 'h2', text: 'A dark filter is a receipt’s best friend' },
      { type: 'p', text: 'Thermal receipt paper is glossy and often prints grey-on-grey. The B&W filter on the adjust screen re-thresholds the image into black text on white, which keeps small print like card numbers and line items readable even under hard light.' },
      { type: 'callout', title: 'Batch a whole week of receipts', text: 'Scan several receipts one after the other into the same document: leave the camera open, snap each receipt, and save. A weekly expense claim becomes a single multi-page PDF instead of a folder of photos.' },
      { type: 'h2', text: 'Keep the PDF legible for the accountant' },
      { type: 'list', items: [
        'Check the date, total, and last-four digits of the card are readable before saving',
        'Photograph the receipt flat — curling edges cast shadows that hide the printed amount',
        'For very long receipts, capture the full strip or split it into two pages rather than cropping',
      ] },
      { type: 'h2', text: 'Even faded receipts can be rescued' },
      { type: 'p', text: 'Fluorescent light often brings back text that has faded almost to nothing; hold the receipt under a bright lamp and use the Magic filter rather than plain photo. Combined with the B&W pass, a receipt you thought was dead usually survives.' },
    ],
    faqs: [
      { q: 'How do I scan a receipt to PDF with my phone?', a: 'Open a browser-based scanner, point the camera at the flat receipt, and let it auto-capture after detecting the edges. Rotate and apply the B&W filter on the review screen, then save and download the PDF.' },
      { q: 'Why do thermal receipts fade and how does PDF help?', a: 'Thermal printers use heat-sensitive coating that darkens over time. Scanning the receipt on the day you receive it captures the legible text permanently as a PDF, safe from fading.' },
      { q: 'Can I scan multiple receipts into one PDF?', a: 'Yes. Leave the camera open and save each receipt in turn; they all land in the same document, perfect for weekly expenses.' },
      { q: 'How do I make a faint receipt readable?', a: 'Scan under bright fluorescent light and apply the Magic or B&W filter on the adjust screen to boost the text before saving.' },
      { q: 'Are my receipts uploaded anywhere?', a: 'No, when the scanner runs in your browser the images are processed on your device. Sensitive receipts stay local.' },
    ],
    related: ['how-to-scan-documents-to-pdf-with-your-phone', 'how-to-convert-a-photo-to-pdf-on-your-phone', 'how-to-compress-a-scanned-pdf', 'how-to-combine-scanned-documents-into-one-pdf'],
  },

  // Article 5: Straighten a crooked scan or photo
  {
    slug: 'how-to-straighten-a-crooked-scan-or-photo',
    title: 'How to Straighten a Crooked Scan or Photo of a Document',
    description: 'Straighten a crooked scan or photo of a document for free — auto-detected edges and perspective correction flatten angled pages into clean, square PDFs.',
    keyword: 'how to straighten a crooked scan or photo',
    category: 'Troubleshooting',
    published: '2026-09-19',
    tool: 'scan-pdf',
    experience: 'I rarely take a photo of a document perfectly square. Straightening used to mean a manual transform in a photo editor; now a scanner’s edge detection crops and perspective-corrects the page in one step, and I know the common reasons why that step sometimes fails.',
    blocks: [
      { type: 'p', text: 'You photographed a document at an angle because desks and hands are rarely square. The photo shows a trapezoid — edges lean, text tapers, and it does not read like a document. A scanner that detects the page edges and applies a perspective correction turns that slanted photo into a flat, square page automatically.' },
      { type: 'p', text: 'Here is how to straighten a crooked scan or photo for free, and how to help the detector when it struggles.' },
      { type: 'h2', text: 'Let edge detection do the straightening' },
      { type: 'steps', items: [
        'Open the Scan PDF tool and point the camera at the angled page.',
        'Wait for the detector to draw a quadrilateral around the page — it follows the true paper edges, not the frame.',
        'Hold still until the outline locks (green), and capture.',
        'Check the review screen: the page is now cropped to those edges and perspective-corrected to a flat rectangle.',
        'Rotate if it needs a final nudge, then save.',
      ] },
      { type: 'p', text: 'The warp is not just a crop. The scanner remaps the page using the four detected corners, so text that leans away from you is rebuilt as if the page were flat on a scanner bed.' },
      { type: 'h2', text: 'When detection fails, do this' },
      { type: 'table', head: ['Problem', 'Cause', 'Fix'], rows: [
        ['No outline appears', 'Low light hides the page edges', 'Add light from the side so the page edges contrast with the desk'],
        ['Outline grabs the table too', 'Page blends into a white background', 'Slip a dark sheet behind the page before scanning'],
        ['Outline keeps wobbling', 'Hand-held camera shake', 'Lay the phone down, or lean it against something and use the shutter'],
        ['Corners are cut off', 'Page extends past the frame', 'Pull back until a clear margin surrounds all four corners'],
        ['The result looks skewed anyway', 'Page was very angled', 'Move closer and shoot from above the page rather than from the side'],
      ] },
      { type: 'callout', title: 'The "Magic" filter is not straightening', text: 'Filters change tone, not geometry. Straightening comes from the detected page edges; apply a filter afterwards to improve contrast, not to fix a slanted page.' },
      { type: 'h2', text: 'Straighten photos you already took' },
      { type: 'p', text: 'If the crooked photo is already in your camera roll, you can still fix it: add the photo into the Scan tool as a page and the same edge detection and perspective correction applies. Pages taken with decent lighting and a clear margin around the paper warp cleanly even when they were never "scanned".' },
      { type: 'h2', text: 'Why steady beats clever' },
      { type: 'p', text: 'The correction is dramatic when the page is close and only slightly tilted, and weakest when the photo is taken from a grazing angle. A phone held roughly parallel to the page almost always produces a PDF that looks like it came off a flatbed.' },
    ],
    faqs: [
      { q: 'How do I straighten a scanned or photographed page for free?', a: 'Use a scanner that detects the page edges and applies perspective correction. It crops to the detected quadrilateral and warps it into a flat rectangle, all in the browser with no app.' },
      { q: 'What does perspective correction actually do?', a: 'It remaps the page from the four detected corners so the angled photo is rebuilt as if the document were facing the camera straight on — text and geometry stop leaning.' },
      { q: 'Why does the detector sometimes not find the page?', a: 'Low light, low contrast against the desk, glare, or corners outside the frame. Even light, a contrasting background, and a clear margin around the page fix most cases.' },
      { q: 'Can I straighten a photo I already took?', a: 'Yes. Add the existing photo as a page in the scanner and it runs the same edge detection and perspective correction over it.' },
      { q: 'Does the B&W filter straighten my page?', a: 'No. Filters change tone and contrast only; straightening comes from the detected edges. Apply filters after the page is warped.' },
    ],
    related: ['how-to-rotate-a-pdf-and-save-it', 'how-to-scan-documents-to-pdf-with-your-phone', 'how-to-crop-a-pdf', 'how-to-tell-if-a-pdf-has-been-edited'],
  },
];