import type { BlogPost } from '../types';

export const newPosts10: BlogPost[] = [
  // Article 1: How to Edit a PDF on Windows
  {
    slug: 'how-to-edit-a-pdf-on-windows',
    title: 'How to Edit a PDF on Windows (Free, No Adobe)',
    description: 'Edit text and images in a PDF on Windows for free. Change words in any PDF right in your browser — no Adobe Acrobat or install needed.',
    keyword: 'how to edit a pdf on windows',
    category: 'Editing & Signing',
    published: '2026-09-10',
    tool: 'edit-pdf',
    experience: 'I edit PDFs on Windows regularly — fixing typos in contracts, updating prices in quotes, and correcting dates on forms. A browser-based editor is the fastest option because Microsoft Print to PDF cannot change text inside a file.',
    blocks: [
      { type: 'p', text: 'A PDF on your Windows PC needs a date corrected, a price updated, or a paragraph replaced. Adobe Acrobat can do it, but the subscription costs $20 a month. Microsoft Edge and the built-in Print to PDF feature can view and export documents but cannot change the text inside them. A browser-based editor edits PDFs for free, right on your machine.' },
      { type: 'p', text: 'Here is how to edit a PDF on Windows without Adobe, entirely in your browser.' },
      { type: 'h2', text: 'Why Windows has no built-in PDF editor' },
      { type: 'p', text: 'Windows offers a few PDF tools, but none of them edit content:' },
      { type: 'list', items: [
        'Microsoft Edge views and annotates PDFs but cannot change existing text',
        'The Microsoft Print to PDF printer only creates new PDFs from other documents',
        'Word can open simple PDFs but distorts complex layouts when it converts them',
        'Paint and Photos cannot open PDF files at all',
      ] },
      { type: 'p', text: 'Because of these gaps, most Windows users either pay for Adobe or search for an alternative. A browser-based PDF editor fills the gap without any installation.' },
      { type: 'h2', text: 'Edit a PDF on Windows in your browser' },
      { type: 'steps', items: [
        'Open the Edit PDF tool in Chrome or Edge on your Windows PC.',
        'Drag your PDF into the tool, or click to browse and select it.',
        'Click a text block to retype the words — fix typos, change dates, update prices.',
        'Move or resize images by selecting them and dragging.',
        'For structure, delete, rotate, or reorder pages as needed.',
        'Click Save and download the edited PDF.',
      ] },
      { type: 'p', text: 'The editing runs in your browser, so the file is processed on your Windows PC and never uploaded to a server.' },
      { type: 'callout', title: 'Scanned PDFs must be OCRed first', text: 'If your PDF came from a scanner, the text is stored as an image and cannot be edited directly. Run OCR first to convert the pixels into real characters, then edit the text.' },
      { type: 'h2', text: 'Editing text vs. adding text' },
      { type: 'p', text: 'There is an important difference between the two. Editing text changes words that already exist in the document — they stay in place and flow with the layout. Adding text drops a new text box wherever you place it, which is useful for filling gaps or adding comments. For a typo or an outdated price, edit the existing text; for a missing field or a note, add new text.' },
      { type: 'h2', text: 'What you can and cannot edit' },
      { type: 'table', head: ['Action', 'Works?', 'Notes'], rows: [
        ['Fix a typo in a digital PDF', 'Yes', 'Text is real characters, click and retype'],
        ['Update a logo or image', 'Yes', 'Select the image, move, resize, or replace'],
        ['Change page order', 'Yes', 'Delete, rotate, or reorder pages'],
        ['Edit a scanned page', 'No', 'Run OCR first to make it editable'],
        ['Change form field values', 'Partly', 'Form fields fill in; edit as text if needed'],
      ] },
      { type: 'h2', text: 'Tips for clean edits' },
      { type: 'list', items: [
        'Save a copy of the original before major edits',
        'Keep replacement text similar in length so the layout does not shift',
        'Check neighbouring pages after editing — reflowed text can push a table off a page',
        'Open the saved file in Edge to confirm every change looks correct',
      ] },
      { type: 'p', text: 'Editing a PDF on Windows does not require Adobe or any software install. The browser handles everything locally, which also means sensitive documents — a contract, a payslip, a tax form — never leave your computer.' },
    ],
    faqs: [
      { q: 'Can I edit a PDF on Windows for free?', a: 'Yes. A browser-based Edit PDF tool runs in Chrome or Edge and lets you change text, images, and pages. No Adobe subscription or software install required.' },
      { q: 'Does Windows have a built-in PDF editor?', a: 'No. Edge can view and annotate PDFs, and the Print to PDF printer creates files, but neither can change the text inside an existing PDF.' },
      { q: 'Why can\u2019t I edit the text in my PDF?', a: 'If the PDF is a scan or photo, the text is stored as an image. Run OCR first to convert the pixels into editable characters, then edit normally.' },
      { q: 'Will editing change the rest of my document?', a: 'Editing reflows the affected text, which can shift other elements on the page. Save a copy before major edits and check neighbouring pages afterward.' },
      { q: 'Is my document uploaded when I edit it?', a: 'No. The editing runs in your browser tab. Your PDF is processed on your Windows PC and never leaves your device.' },
    ],
    related: ['how-to-edit-a-pdf-without-adobe', 'how-to-edit-pdf-text-without-acrobat', 'how-to-edit-a-pdf-on-mac', 'how-to-edit-a-pdf-on-a-chromebook'],
  },

  // Article 2: How to Password Protect a PDF on Mac
  {
    slug: 'how-to-password-protect-a-pdf-on-mac',
    title: 'How to Password Protect a PDF on Mac (Free)',
    description: 'Lock a PDF with a password on your Mac for free. Use Preview or a browser tool to encrypt any PDF — no software install required.',
    keyword: 'how to password protect a pdf on mac',
    category: 'Security & Privacy',
    published: '2026-09-10',
    tool: 'protect-pdf',
    experience: 'I password-protect PDFs on my Mac before sending contracts and financial statements. Preview can encrypt a file with a couple of clicks, and a browser tool adds protection when I need more control.',
    blocks: [
      { type: 'p', text: 'A contract, a bank statement, or a private report needs to stay readable only by the person you send it to. Locking the PDF with a password is the simplest way to make sure of that. On a Mac, you have two good free options: the built-in Preview app, and a browser-based protect tool for more control.' },
      { type: 'p', text: 'Here is how to password protect a PDF on a Mac for free.' },
      { type: 'h2', text: 'Protect a PDF with Preview (built in)' },
      { type: 'steps', items: [
        'Open the PDF in Preview on your Mac.',
        'Choose File > Export.',
        'Tick the Encrypt checkbox near the bottom of the export window.',
        'Enter a strong password and verify it.',
        'Click Export — the saved copy is now password-protected.',
      ] },
      { type: 'p', text: 'Preview\u2019s built-in encryption is free and needs no extra software. The exported file requires the password every time it is opened.' },
      { type: 'callout', title: 'Export creates a new file', text: 'File > Export keeps your original PDF unchanged and creates a new encrypted copy. Delete the unprotected original once you are sure the encrypted one opens correctly.' },
      { type: 'h2', text: 'Protect a PDF in your browser (more controls)' },
      { type: 'p', text: 'Preview is quick, but a browser-based protect tool gives you additional options, such as processing a file that will not open in Preview or keeping everything locally with clear feedback:' },
      { type: 'steps', items: [
        'Open the Protect PDF tool in Safari or Chrome on your Mac.',
        'Drag the PDF into the tool, or click to browse for it.',
        'Enter a strong password — at least 12 characters, ideally a short phrase.',
        'Confirm the password and click protect.',
        'Download the encrypted PDF back to your Mac.',
      ] },
      { type: 'p', text: 'The tool runs in your browser tab, so the document is processed on your Mac and not uploaded anywhere.' },
      { type: 'h2', text: 'What password protection actually does' },
      { type: 'list', items: [
        'It encrypts the document with AES so a password is needed to open it',
        'It stops casual access — a stolen file without the password is useless',
        'It is not the same as editing restrictions, which only limit changes',
      ] },
      { type: 'p', text: 'Modern encryption has no backdoor, so forgetting the password means losing access to the file. Store it in a password manager, or keep an unprotected backup copy somewhere safe.' },
      { type: 'h2', text: 'Choosing a password that survives' },
      { type: 'table', head: ['Do', 'Avoid'], rows: [
        ['Use a phrase of 4–6 unrelated words', 'Single dictionary words'],
        ['Add numbers or symbols', 'Name, birthday, or simple patterns'],
        ['Reuse a system you already use', 'Reusing an email password'],
        ['Store it in a password manager', 'Writing it in the same email as the file'],
      ] },
      { type: 'h2', text: 'Sharing the protected PDF' },
      { type: 'p', text: 'Send the file one way and the password another — an encrypted file delivered in the same email as its password is not protected. Send the PDF by email and share the password by text, call, or a messaging app. If the document is urgent, call the recipient and read the password aloud.' },
      { type: 'p', text: 'Preview and a browser tool both encrypt your PDF on a Mac without costing anything. Pick Preview for a quick lock, or a browser tool when you want a simple step-by-step flow for multiple files.' },
    ],
    faqs: [
      { q: 'Can I password protect a PDF on Mac for free?', a: 'Yes. Preview can encrypt any PDF via File > Export > Encrypt, and a browser-based Protect PDF tool adds a password with no install. Both are free.' },
      { q: 'How do I password protect a PDF with Preview?', a: 'Open the PDF in Preview, choose File > Export, tick Encrypt, enter a password twice, and click Export. The new file requires the password to open.' },
      { q: 'Does password protection reduce PDF quality?', a: 'No. Encryption only wraps the file so a password is required. The pages, text, and images are unchanged.' },
      { q: 'Can the password be recovered if I forget it?', a: 'No. Modern PDF encryption has no backdoor. Keep an unprotected backup copy or store the password in a password manager.' },
      { q: 'Are my files uploaded when I protect them?', a: 'No. Preview works locally, and a browser-based tool processes the file in your browser tab. Your PDF never leaves your Mac.' },
    ],
    related: ['how-to-password-protect-a-pdf', 'how-to-password-protect-a-pdf-on-windows', 'how-to-password-protect-a-pdf-without-adobe', 'how-to-remove-a-password-from-a-pdf'],
  },

  // Article 3: How to Rotate a PDF on Windows
  {
    slug: 'how-to-rotate-a-pdf-on-windows',
    title: 'How to Rotate a PDF on Windows and Save (Free)',
    description: 'Rotate pages in a PDF on Windows for free and save the changes. Fix sideways or upside-down pages in your browser — no Adobe needed.',
    keyword: 'how to rotate a pdf on windows',
    category: 'Merging & Organizing',
    published: '2026-09-10',
    tool: 'rotate-pdf',
    experience: 'I rotate PDFs on Windows when scans come out sideways or when pages are mixed between landscape and portrait. The browser approach saves the rotation permanently, which the viewer in Edge cannot do.',
    blocks: [
      { type: 'p', text: 'A PDF opens with every page sideways, or a scan came out upside-down, and printing it means wasting paper. Edge and the default Windows viewer can rotate a page on screen, but the change disappears the moment you close the file. To rotate a PDF and actually save the result, you need a tool that rewrites the file with the new orientation.' },
      { type: 'p', text: 'Here is how to rotate a PDF on Windows for free and keep the rotation.' },
      { type: 'h2', text: 'Why the Windows viewer does not save rotation' },
      { type: 'list', items: [
        'Microsoft Edge rotates pages for viewing only — it never edits the file',
        'Photos and Paint cannot open PDFs',
        'The Print to PDF printer cannot rotate existing pages',
        'Most free "PDF editors" rotate on screen but fail to write the change to disk',
      ] },
      { type: 'p', text: 'A dedicated rotate tool reads the pages, turns them, and writes a new file with the rotation permanently applied.' },
      { type: 'h2', text: 'Rotate and save a PDF on Windows in your browser' },
      { type: 'steps', items: [
        'Open the Rotate PDF tool in Chrome or Edge on your Windows PC.',
        'Drag your PDF into the tool, or click to browse and select it.',
        'Choose the rotation — 90° clockwise, 90° counter-clockwise, or 180°.',
        'Apply it to all pages or just the ones you select.',
        'Click rotate and download the corrected PDF.',
      ] },
      { type: 'p', text: 'The rotation runs in your browser, so the file is processed on your Windows PC and never uploaded to a server.' },
      { type: 'callout', title: 'Choose which pages to rotate', text: 'If only some pages are sideways, rotate just those pages instead of the whole document. This keeps correctly-oriented pages untouched.' },
      { type: 'h2', text: 'Common rotation fixes' },
      { type: 'table', head: ['Symptom', 'Fix', 'Result'], rows: [
        ['Every page sideways 90°', 'Rotate all pages 90° clockwise', 'Whole document upright'],
        ['Every page upside-down', 'Rotate all pages 180°', 'Whole document upright'],
        ['One scanned page sideways', 'Rotate only that page', 'Mixed-orientation document fixed'],
        ['Portrait and landscape mixed', 'Rotate matching pages to unify', 'Consistent readable layout'],
      ] },
      { type: 'h2', text: 'Rotating before printing' },
      { type: 'p', text: 'When you need to print a rotated PDF, always rotate and save the file first, then print the saved copy. Printing directly from the Windows viewer with rotation applied on screen does not reliably carry the rotation to the printed page — the printer driver may output the original orientation.' },
      { type: 'h2', text: 'Tips for a clean result' },
      { type: 'list', items: [
        'Open the rotated PDF in Edge to confirm every page looks right',
        'Rotate one test page first on large documents, then apply to the rest',
        'Keep the original until you have verified the rotated copy',
        'For scanned books, rotate all pages at once then re-select any stragglers',
      ] },
      { type: 'p', text: 'A browser-based rotate tool is the reliable way to fix page orientation on Windows. The rotation is written into the file, so the corrected PDF prints, shares, and archives at the right angle.' },
    ],
    faqs: [
      { q: 'How do I rotate a PDF on Windows for free?', a: 'Open a browser-based Rotate PDF tool in Chrome or Edge, choose the rotation angle and pages, and download the corrected file. The rotation is saved permanently.' },
      { q: 'Why does the rotation disappear when I close the file in Edge?', a: 'Edge only rotates pages for on-screen viewing. It never writes the change to the file. A rotate tool saves the new orientation to disk.' },
      { q: 'Can I rotate only some pages?', a: 'Yes. Select the specific pages that are sideways and rotate just those, leaving correctly-oriented pages unchanged.' },
      { q: 'Do I need Adobe Acrobat to rotate a PDF?', a: 'No. Any modern browser can run a rotate tool that writes the change to the file. Adobe is a paid alternative but not required.' },
      { q: 'Are my files uploaded when I rotate them?', a: 'No. The rotation runs in your browser tab. Your PDF is processed on your Windows PC and never leaves your device.' },
    ],
    related: ['how-to-rotate-a-pdf-and-save-it', 'how-to-rotate-a-pdf-on-android', 'how-to-rotate-a-pdf-on-iphone', 'how-to-reverse-page-order-in-a-pdf'],
  },

  // Article 4: How to Convert JPG to PDF on iPhone
  {
    slug: 'how-to-convert-jpg-to-pdf-on-iphone',
    title: 'How to Convert JPG to PDF on iPhone (Free)',
    description: 'Turn JPG photos into a PDF on your iPhone for free. Convert one image or many into a single PDF in Safari — no app install required.',
    keyword: 'how to convert jpg to pdf on iphone',
    category: 'Converting',
    published: '2026-09-10',
    tool: 'jpg-to-pdf',
    experience: 'I convert JPG photos to PDF on my iPhone when sending receipts, signed pages, and photo documents. Apple\u2019s built-in Print-to-PDF trick works for one image, and a browser tool makes a single PDF from many photos at once.',
    blocks: [
      { type: 'p', text: 'A photo needs to become a PDF — a receipt for an expense claim, a scanned signature, or a group of photos to send as one document. Your iPhone can do this without any app install. For a single image, the built-in Print trick works. For several photos combined into one PDF, a browser-based converter is faster and more controllable.' },
      { type: 'p', text: 'Here is how to convert JPG to PDF on an iPhone for free.' },
      { type: 'h2', text: 'Convert one photo using the built-in trick' },
      { type: 'steps', items: [
        'Open the photo in the Photos app on your iPhone.',
        'Tap the Share button, then choose Print.',
        'Pinch outwards on the photo preview to open the full page.',
        'Tap Share in the print preview and choose Save to Files.',
        'Rename the PDF and save it.',
      ] },
      { type: 'p', text: 'This creates a single-page PDF from that one photo and needs no apps or accounts. It is the fastest option when you only need one image converted.' },
      { type: 'h2', text: 'Combine several JPGs into one PDF in Safari' },
      { type: 'p', text: 'When you need a contract, a set of receipts, or several photos as a single multi-page PDF, a browser-based JPG to PDF tool is the cleanest approach:' },
      { type: 'steps', items: [
        'Open the JPG to PDF tool in the Safari browser on your iPhone.',
        'Tap to choose files and pick the JPG photos from your library.',
        'Arrange the images in the order you want before converting.',
        'Choose the page size and orientation.',
        'Tap convert and download the resulting PDF.',
      ] },
      { type: 'p', text: 'The conversion runs in your browser. The photos are processed on your iPhone and never uploaded to a server.' },
      { type: 'callout', title: 'Keep the order you want', text: 'Arrange images before converting — the app follows your ordering, so put the first document first. You can typically reorder photos with a drag before you convert.' },
      { type: 'h2', text: 'Photo vs. PDF: when to convert' },
      { type: 'table', head: ['Use a JPG when', 'Use a PDF when'], rows: [
        ['You need a single photo for social media', 'The document needs to open identically for everyone'],
        ['File size matters more than layout', 'You need several images as one file'],
        ['The image will be edited again', 'It is a record you do not want altered'],
        ['A form accepts image uploads', 'A form or system requires PDF'],
      ] },
      { type: 'h2', text: 'Choosing page size and quality' },
      { type: 'p', text: 'For receipts and documents, portrait A4 or Letter pages keep things readable. For wide photos, landscape orientation avoids ugly cropping. Higher image quality makes larger PDFs but keeps printed text sharp; if the PDF is only for email or records, a standard quality setting keeps the file size small.' },
      { type: 'h2', text: 'What to check before you send' },
      { type: 'list', items: [
        'Open the converted PDF and flip through every page',
        'Confirm the order matches the original photos',
        'Check images are not rotated or cut off at the edges',
        'Rename the PDF clearly before sending it',
      ] },
      { type: 'p', text: 'Converting JPGs to PDF on an iPhone is quick with either the built-in print trick or a Safari-based converter. For a single image, the Photos app handles it; for combining many photos, a browser tool does the job in one pass.' },
    ],
    faqs: [
      { q: 'Can I convert JPG to PDF on iPhone for free?', a: 'Yes. The built-in Print-to-PDF trick in the Photos app converts one image, and a browser-based JPG to PDF tool converts many photos in Safari. No install required.' },
      { q: 'How do I convert one JPG to PDF without an app?', a: 'Open the photo, tap Share, choose Print, pinch out on the preview, then tap Share in the print preview and Save to Files as PDF.' },
      { q: 'How do I combine several JPGs into one PDF?', a: 'Use a browser-based JPG to PDF tool in Safari. Select all the photos, arrange them, and convert — you get one multi-page PDF.' },
      { q: 'What page size should I use?', a: 'Portrait A4 or Letter suits receipts and documents. Use landscape for wide photos so they are not cropped.' },
      { q: 'Are my photos uploaded during conversion?', a: 'No. The conversion runs in your browser tab. Your images are processed on your iPhone and never leave your device.' },
    ],
    related: ['how-to-convert-jpg-to-pdf', 'how-to-convert-jpg-to-pdf-on-windows', 'how-to-make-a-pdf-on-iphone', 'how-to-convert-a-photo-to-pdf-on-your-phone'],
  },

  // Article 5: How to Split a PDF on Android
  {
    slug: 'how-to-split-a-pdf-on-android',
    title: 'How to Split a PDF on Android (Free, No App)',
    description: 'Split a PDF into separate pages or page ranges on your Android phone for free. Extract pages in Chrome — no app install or uploads.',
    keyword: 'how to split a pdf on android',
    category: 'Merging & Organizing',
    published: '2026-09-10',
    tool: 'split-pdf',
    experience: 'I split PDFs on Android to extract chapters from ebooks and pull specific pages out of contracts. The Chrome-based approach avoids the Play Store apps that hide splitting behind a subscription.',
    blocks: [
      { type: 'p', text: 'You need a few pages out of a PDF, but only the whole file is on your phone. Splitting extracts the pages you want into a new PDF — a chapter from a book, the signed page of a contract, or a single receipt from a long statement. Android has no built-in splitter, and many Play Store apps charge for the feature, so a browser-based tool is the free path.' },
      { type: 'p', text: 'Here is how to split a PDF on Android for free, right in Chrome.' },
      { type: 'h2', text: 'What splitting gets you on Android' },
      { type: 'list', items: [
        'Extract a single page into its own PDF',
        'Pull a range of pages out of a long document',
        'Split a whole PDF into one file per page',
        'Send only what is needed instead of the full file',
      ] },
      { type: 'p', text: 'The original file is left untouched — splitting creates new files from the source, so you can split again with different settings at any time.' },
      { type: 'h2', text: 'Split a PDF on Android in Chrome' },
      { type: 'steps', items: [
        'Open the Split PDF tool in the Chrome browser on your Android phone.',
        'Tap to choose a file and pick your PDF from Downloads, Google Drive, or phone storage.',
        'Choose how to split — by page range, every page, or selected pages.',
        'Enter the pages you want (for example, 3–7).',
        'Tap split and download the extracted PDF(s).',
      ] },
      { type: 'p', text: 'The splitting runs in your browser. Your PDF is processed on your Android phone and never uploaded to a server.' },
      { type: 'callout', title: 'Name files clearly', text: 'If you split a whole document into many files, download them with page numbers in the name (page-1, page-2) so they stay in order when you share or recombine them.' },
      { type: 'h2', text: 'Splitting options explained' },
      { type: 'table', head: ['Option', 'What it does', 'When to use it'], rows: [
        ['Page range', 'Extracts specific pages, e.g. 3–7', 'You know exactly which pages you need'],
        ['Every page', 'One PDF per page', 'Each page must be its own file'],
        ['Selected pages', 'Extracts non-contiguous pages, e.g. 2, 5, 9', 'You need scattered pages'],
        ['Multiple ranges', 'Several sets from one document', 'Sections going to different people'],
      ] },
      { type: 'h2', text: 'Separate splitting from removing pages' },
      { type: 'p', text: 'Splitting is different from deleting pages. Splitting copies pages into new files and leaves the original intact. Removing pages deletes pages from the source document. Use splitting when you want to preserve the original, and removal when you want a trimmed version added back over the file.' },
      { type: 'h2', text: 'Check the result before sharing' },
      { type: 'list', items: [
        'Open each split file and confirm the right pages are inside',
        'Verify the last page of each file is complete and not cut off',
        'Confirm page order when you split into multiple files',
        'Delete the temporary files you no longer need from Downloads',
      ] },
      { type: 'p', text: 'Browser-based splitting is the fastest free way to split a PDF on Android. There is nothing to install, no account to create, and the file stays on your phone the entire time.' },
    ],
    faqs: [
      { q: 'Can I split a PDF on Android for free?', a: 'Yes. Open a browser-based Split PDF tool in Chrome, select your PDF, choose the pages or ranges, and download the extracted files. No app install needed.' },
      { q: 'Does Android have a built-in PDF splitter?', a: 'No. Android\u2019s built-in viewers display PDFs but cannot split them. A browser-based tool adds splitting with nothing to install.' },
      { q: 'Does splitting change my original PDF?', a: 'No. Splitting creates new files from the original. The source PDF is always left unchanged.' },
      { q: 'Can I extract just a few pages instead of the whole file?', a: 'Yes. Choose the page-range or selected-pages option and enter the page numbers you need.' },
      { q: 'Are my files uploaded when I split them?', a: 'No. The splitting runs in your Chrome browser on your phone. Your PDF is processed locally and never leaves your device.' },
    ],
    related: ['how-to-split-a-pdf-into-separate-pages', 'how-to-split-a-pdf-on-iphone', 'how-to-split-a-pdf-on-mac', 'how-to-merge-pdf-files-on-android'],
  },
];