import type { BlogPost } from '../types';

export const newPosts16: BlogPost[] = [
  {
    slug: 'how-to-remove-a-signature-from-a-pdf',
    title: 'How to Remove a Signature From a PDF (Free)',
    description: 'Remove a signature from a PDF for free in your browser — delete a signature image, redact a flattened one, and know when a digital signature cannot be removed.',
    keyword: 'how to remove a signature from a pdf',
    category: 'Editing & Signing',
    published: '2026-09-22',
    tool: 'edit-pdf',
    experience: 'I keep a signed template in rotation, and one version got saved with an old signature baked on. The difference between a one-click delete and a redaction comes down to one question — is the signature an object on the page or part of the page — so that question is the whole article.',
    blocks: [
      { type: 'p', text: 'Removing a signature from a PDF is only complicated until you know what kind of signature it is. Some are images sitting on top of the page — select, delete, done. Others are ink baked into a scanned page and need redaction. And a digital signature is a cryptographic seal around the entire file, which is a different animal. Here is how to tell the three apart and remove the ones you are entitled to.' },
      { type: 'h2', text: 'Work out what kind of signature it is first' },
      { type: 'p', text: 'The removal method is decided by the signature itself, not by preference. A two-second check points you at the right tool.' },
      { type: 'table', head: ['Kind of signature', 'How to spot it', 'Can it be removed?'], rows: [
        ['Electronic signature (image or drawing)', 'Click it and it highlights or shows handles', 'Yes — select it and delete'],
        ['Scanned or flattened signature', 'The page behaves like one picture; clicking does nothing', 'Only by redaction, which takes whatever is underneath too'],
        ['Digital signature (certificate seal)', 'The reader shows a blue ribbon or certificate badge', 'No — editing breaks the seal; ask the sender for an unsigned copy'],
        ['Empty signature field on a form', 'A boxed area that is waiting for a signature', 'Usually yes, treated like an ordinary object'],
      ] },
      { type: 'h2', text: 'Remove a signature that is an object' },
      { type: 'p', text: 'If the signature highlights when you click it, it lives in its own layer. Deleting it removes just the signature, and everything underneath — the signature line, the printed name, the date — stays exactly where it is. This is the only removal that is genuinely lossless.' },
      { type: 'steps', items: [
        'Open the Edit PDF tool and add your PDF.',
        'Go to the page with the signature.',
        'Click the signature — if it registers as an object, a small toolbar appears.',
        'Choose Delete, then save and download the clean PDF.',
      ] },
      { type: 'callout', title: 'If you can click it, it is an object', text: 'An image on its own layer can be deleted without touching the rest of the page. If clicking does nothing, skip to the redaction method below — the ink is part of the page itself.' },
      { type: 'h2', text: 'Remove a signature that is part of the page' },
      { type: 'p', text: 'When the document is a scan, or was flattened on export, the signature is the same pixels as the paper around it. There is nothing to select, so the only honest removal is a redaction: cover the area and let the tool burn it out of the file so it cannot be recovered.' },
      { type: 'steps', items: [
        'Open the Redact PDF tool and add the document.',
        'Draw a box tightly around the signature.',
        'Apply the redaction, then verify by copying from the area — nothing should come back.',
        'Download the clean file.',
      ] },
      { type: 'callout', title: 'Redaction covers everything under the box', text: 'A redaction removes the entire region it is drawn over, not just the signature ink. Keep the box tight around the signature so the printed name or date line beside it is not erased with it.' },
      { type: 'h2', text: 'Digital signatures are the exception' },
      { type: 'p', text: 'A digital signature is not a picture — it is a cryptographic seal that certifies the exact bytes of the file. The moment anything changes, the seal is invalid and every PDF reader flags the document as modified. There is no way to keep the seal and change the file, and stripping someone else\'s seal so that an executed document can be altered is document tampering, not cleanup. If a certified file genuinely needs to return to unsigned form, ask whoever signed it for an unsigned copy. If the file is simply locked by a permissions password you hold, unlock it first and the delete-or-redact methods above apply.' },
      { type: 'h2', text: 'Remove signatures only where you have the right' },
      { type: 'p', text: 'Removing a signature from a document you own — a template signed too early, a draft under revision, your own earlier version — is routine and legal. Removing someone else\'s signature from a signed agreement to change its terms is tampering. Decide which of the two you are doing before you start, and when in doubt, clear it with the other party in writing.' },
    ],
    faqs: [
      { q: 'Can I remove a signature from a scanned PDF?', a: 'Only by redaction. Because the signature is part of the page image, covering it with a redaction box is the one reliable method — but it also removes anything else inside the box, so keep it tight.' },
      { q: 'Does removing a signature break a digital signature?', a: 'Yes, and that is the point of the seal. A certified document modified after signing is flagged as invalid by every reader. No tool can keep the seal while changing the contents.' },
      { q: 'Can I unlock a signed PDF and then edit it?', a: 'If the lock is a permissions password you have, unlock it first and then delete or redact the signature like any other content. A certification seal is not a password and cannot be removed this way.' },
      { q: 'Is removing a signature from my own PDF legal?', a: 'Generally yes, for documents you own or have the right to modify. Removing someone else\'s signature from an executed agreement can amount to tampering or fraud — get permission first.' },
      { q: 'How do I know whether my signature is an object or part of the scan?', a: 'Click it. If it highlights or shows handles, it is an object you can delete. If nothing happens and the whole page behaves like one image, it is flattened and redaction is the only route.' },
    ],
    related: ['how-to-sign-a-pdf-electronically', 'how-to-redact-a-pdf-properly', 'how-to-edit-a-pdf-without-adobe', 'how-to-remove-a-password-from-a-pdf'],
  },

  {
    slug: 'how-to-combine-a-photo-and-a-pdf',
    title: 'How to Combine a Photo and a PDF Into One File',
    description: 'Combine a photo and a PDF into one file for free — convert the photo to a PDF page, then merge the two in order, all in your browser with no upload.',
    keyword: 'how to combine a photo and a pdf into one file',
    category: 'Merging & Organizing',
    published: '2026-09-22',
    updated: '2026-10-04',
    tool: 'merge-pdf',
    blocks: [
      { type: 'p', text: 'A photo and a PDF are different formats, so they will not merge directly — but converting the photo into a PDF page and then merging the two takes about a minute, entirely in your browser. The case comes up constantly: a signed form joined with a photo ID, an invoice with a delivery photo, a contract with a scanned passport page, meeting minutes with a picture of the whiteboard.' },
      { type: 'p', text: 'Here is exactly how to combine a photo and a PDF into one file.' },
      { type: 'h2', text: 'The one rule: everything must be a PDF first' },
      { type: 'p', text: 'A merge tool only combines PDFs. A JPG, PNG or WebP photo has to become a page before it can join the document, and the JPG to PDF tool does that step in seconds. iPhone HEIC photos go through HEIC to PDF instead.' },
      { type: 'h2', text: 'JPG and PDF to PDF: the two-step method' },
      { type: 'steps', items: [
        'Open the JPG to PDF tool and add your photo — or several photos, in the order you want them as pages.',
        'Convert. Each photo becomes its own A4 page in a new PDF.',
        'Open the Merge PDF tool and add the files in reading order — for example the original PDF first, then the photo PDF. Pages follow the order of the file list.',
        'Merge, check the live preview, and download the combined file.',
      ] },
      { type: 'p', text: 'The first tool turns pictures into pages; the second stacks those pages before or after the existing document. To put a photo in the middle of a document instead, merge first and then move the photo page into place with Organize PDF.' },
      { type: 'h2', text: 'Which end does the photo go?' },
      { type: 'p', text: 'There is no universal answer — it depends on which part the recipient reads first. A sensible default is the document that identifies or proves something first, with the photo as supporting evidence after it.' },
      { type: 'table', head: ['Combination', 'Sensible order', 'Why'], rows: [
        ['Signed form + photo ID', 'Form first, photo after', 'The proof document leads; the photo supports it'],
        ['Invoice + delivery or repair photo', 'Invoice first, photo after', 'The photo is evidence attached to the invoice'],
        ['Booking confirmation + ticket QR code', 'Photo first, form after', 'The photo page is the usable part; the terms can trail'],
      ] },
      { type: 'h2', text: 'How the photo page is sized' },
      { type: 'p', text: 'JPG to PDF does not offer page-size options. Every photo is centred on a portrait A4 page with a small margin, scaled down to fit if it is larger than the page and never stretched — the aspect ratio is always kept. A landscape photo therefore sits across the width of the page with white space above and below.' },
      { type: 'list', items: [
        'If the other PDF is A4, the combined file is uniform with no extra work',
        'If it is US Letter, the photo page will be slightly narrower and taller — PDF handles mixed sizes fine, and most recipients will not notice',
        'Crop the photo close to the document edges before converting, so the subject fills more of the page',
        'If a phone photo comes out sideways, turn that page upright with Rotate PDF before you merge',
        'Compress the merged file once, at the end, since photo pages inflate file size',
        'Rename the result with date and subject, not "merged.pdf"',
      ] },
      { type: 'h2', text: 'Several photos and one document' },
      { type: 'p', text: 'A whole set of photos converts in one pass: add them all to JPG to PDF and each becomes a page, in the order they appear in the file list. If they land out of sequence, remove the stray file and add it again — it moves to the end of the list — or fix the page order afterwards in Organize PDF. Then merge that single photo PDF with the document as above.' },
      { type: 'callout', title: 'Quality and privacy both stay intact', text: 'JPG photos are embedded as they are, without re-compressing them, and Merge PDF copies existing pages through untouched, so neither half loses sharpness. Both steps run in the browser, so your photo and your PDF never leave your device — which matters when the combination is a signed form plus ID, exactly the file you do not want on a stranger\'s server.' },
      { type: 'h2', text: 'When a different route fits better' },
      { type: 'p', text: 'If there is no existing document and you only want several photos in one PDF, JPG to PDF on its own does the whole job — no merge needed. And if the pack is mixed beyond one photo — Word pages, a spreadsheet, a deck — the multiple-file-types walkthrough covers the full order of operations.' },
    ],
    faqs: [
      { q: 'Can I merge a JPG directly into a PDF?', a: 'No — merge tools work between PDFs only. Convert the photo to a PDF page first with a JPG to PDF tool, then merge it with the existing document.' },
      { q: 'Will the photo be stretched or distorted?', a: 'No. The photo keeps its aspect ratio and is centred on an A4 page, scaled down only if it is larger than the page. The trade-off is white space around photos whose shape differs from A4.' },
      { q: 'Will combining reduce the quality of my photo?', a: 'No. JPG photos are embedded without re-compression and the merge copies pages through unchanged. Large photos are displayed smaller to fit the page, but the full-resolution image is kept inside the PDF.' },
      { q: 'Can I use PNG, WebP or iPhone HEIC photos?', a: 'PNG and WebP work in JPG to PDF directly. HEIC photos need the HEIC to PDF tool for the first step; the merge afterwards is the same.' },
      { q: 'Photos make the file huge — what do I do?', a: 'Photo pages are large. Compress the finished merged PDF once at the end; one pass avoids degrading the document twice.' },
      { q: 'Can I change the order after merging?', a: 'Yes — open the combined file in Organize PDF and type the page order you want, which moves the photo page anywhere in the document.' },
    ],
    related: ['how-to-combine-images-into-one-pdf', 'how-to-merge-pdf-files', 'how-to-convert-jpg-to-pdf', 'how-to-convert-a-photo-to-pdf-on-your-phone', 'how-to-create-a-pdf-from-multiple-file-types'],
  },

  {
    slug: 'how-to-change-the-page-size-of-a-pdf',
    title: 'How to Change the Page Size of a PDF (A4 to Letter)',
    description: 'Change a PDF from A4 to Letter or Letter to A4 for free — set the paper size in your browser\'s print dialog, or trim custom sizes with a crop tool.',
    keyword: 'how to change the page size of a pdf from a4 to letter',
    category: 'Editing & Signing',
    published: '2026-09-22',
    tool: 'crop-pdf',
    blocks: [
      { type: 'p', text: 'A PDF keeps the page size it was created with, but that size is not fixed forever — you can change it afterwards. Around half the people asking how to change the page size actually mean one of two different things: matching a PDF to a standard paper size (A4 to Letter, Letter to A4), or trimming a PDF down to a custom size. The fix differs, so check which one you need first.' },
      { type: 'h2', text: 'Which method is yours?' },
      { type: 'table', head: ['What you want', 'Fastest method', 'Where it runs'], rows: [
        ['A4 to Letter, or any two standard sizes', 'Browser print dialog, paper-size setting', 'Built into Chrome, Edge, Safari'],
        ['Trim margins or shrink an irregular page', 'Crop the page edges', 'Crop PDF tool'],
        ['Every page the same size in a mixed document', 'Print the whole file to one standard size', 'Built into your browser'],
      ] },
      { type: 'h2', text: 'Change A4 to Letter (or back) with the print dialog' },
      { type: 'p', text: 'Every browser can save a PDF to a chosen paper size, and most operating systems can too. In Chrome and Edge the setting sits in the print dialog, and it re-sizes the actual PDF file, not just the printout.' },
      { type: 'steps', items: [
        'Open the PDF in your browser.',
        'Press Ctrl+P on Windows or Cmd+P on Mac.',
        'Set the destination to "Save as PDF".',
        'In More settings, choose the paper size — Letter, A4, or another standard.',
        'Choose Scale: Fit to page so content re-flows to the new size, then Save.',
        'Open the new file to confirm the pages are the size you chose.',
      ] },
      { type: 'callout', title: 'Printing to PDF re-renders the page', text: 'The print pipeline re-typesets text and layout, so check pages with tables, forms, or images afterwards. Fillable form fields are flattened to their saved values, and hyperlinks are usually kept — worth a click-through in the new file.' },
      { type: 'h2', text: 'Trim a page to a custom size with the crop tool' },
      { type: 'p', text: 'When the goal is removing an uneven white border — a scanned page with ragged edges, or a slide exported with a wide frame — the Crop PDF tool adjusts the margins directly, shrinking the page to the content you want to keep.' },
      { type: 'steps', items: [
        'Open the Crop PDF tool and add your file.',
        'Adjust the margins on each side until the page is the size you want.',
        'Apply the crop and download the trimmed PDF.',
      ] },
      { type: 'list', items: [
        'Crop trims inward only — it never grows a page, so use the print dialog when you need to scale content up',
        'For a book-style scan, crop the outer edges first, then unify the odd page with a print pass',
        'Keep the original if you might need the un-trimmed version later',
      ] },
      { type: 'h2', text: 'Standard sizes by region' },
      { type: 'table', head: ['Size', 'Dimensions', 'Where it dominates'], rows: [
        ['A4', '210 × 297 mm', 'Most of the world outside North America'],
        ['Letter', '8.5 × 11 in (216 × 279 mm)', 'US and Canada'],
        ['Legal', '8.5 × 14 in (216 × 356 mm)', 'US legal documents'],
      ] },
      { type: 'h2', text: 'Fixing mixed-size documents' },
      { type: 'p', text: 'A file where a few pages differ from the rest — common after scanning a document that combined two paper stocks — is best handled in one pass: print the whole PDF to the single target size so every page standardizes together, rather than cropping page by page.' },
    ],
    faqs: [
      { q: 'Can I change a PDF to A4 without installing software?', a: 'Yes. Open the PDF in a browser, use the print dialog with the destination set to "Save as PDF", pick A4 from the paper-size options, and save — no software to install.' },
      { q: 'Does changing the page size shrink the text?', a: 'The "Fit to page" scale option resizes content to fill the new page, so an A4-to-Letter change re-flows text rather than cropping it. Check tables and images after saving.' },
      { q: 'Can I make a PDF page larger than its content?', a: 'Yes, with the print dialog — choose a larger paper size and a scale above 100%. The crop tool only trims inward, so it cannot grow a page.' },
      { q: 'What if my PDF has pages of different sizes?', a: 'Print the whole file to one target standard size so all pages normalize together. Cropping outliers one at a time leaves the document inconsistent.' },
      { q: 'Do form fields survive a page-size change?', a: 'Usually not — printing to PDF flattens fillable fields to their current values. Keep the original if you still need an editable form.' },
    ],
    related: ['how-to-crop-a-pdf', 'how-to-print-a-pdf-correctly', 'how-to-fix-a-pdf-that-wont-print', 'how-to-rotate-a-pdf-and-save-it'],
  },

  {
    slug: 'how-to-scan-a-book-into-a-pdf',
    title: 'How to Scan a Book Into a PDF (Free)',
    description: 'Scan a book into a PDF for free with your phone: Book mode splits each open spread into two straight pages, cleaned up in your browser with nothing uploaded.',
    keyword: 'how to scan a book into a pdf',
    category: 'Converting',
    published: '2026-09-22',
    updated: '2026-10-04',
    tool: 'scan-pdf',
    experience: 'Whenever I reference a physical textbook at my desk, I photograph the spreads with my phone instead of dragging out a scanner. The reliable part is the setup — flat pages and even light — and everything else is edge detection, page splitting and cleanup the browser does for me.',
    blocks: [
      { type: 'p', text: 'Scanning a book into a PDF means photographing the pages cleanly and letting a document scanner turn the shots into straight, evenly lit pages. You do not need a book scanner, a flatbed or desktop software. A phone and a browser scanner with a book mode are enough, and the whole book stays on your device.' },
      { type: 'h2', text: 'How do I scan a book into a PDF with my phone?' },
      { type: 'p', text: 'Open the Scan PDF tool on your phone, choose Book mode and line the spine up with the dashed centre line. Each shot of an open spread is split into a left page and a right page. Turn the page, capture the next spread, and save all the pages as one PDF.' },
      { type: 'steps', items: [
        'Open Scan PDF and tap Open camera.',
        'Choose Book in the mode bar.',
        'Line up the spine with the centre line.',
        'Capture, turn the page, capture again.',
        'Review, then Save PDF.',
      ] },
      { type: 'h2', text: 'Set the book up before you shoot' },
      { type: 'p', text: 'The quality of a book scan is decided before the shutter fires. A few minutes of setup saves every later fix.' },
      { type: 'list', items: [
        'Put the book on a table, spine towards you or away from you, and open it as flat as it will comfortably go',
        'Use a darker surface than the pages so the outer edges of the spread stand out',
        'Press the pages down at the outer margins with your fingertips, not over the text, and never force the spine past its comfortable opening',
        'Light the book evenly; a lamp from the side reduces the shadow in the gutter, but avoid reflections on glossy pages',
        'Hold the phone parallel to the open book, high enough that both pages fit with a small margin',
      ] },
      { type: 'h2', text: 'Scan the book, spread by spread' },
      { type: 'steps', items: [
        'Open the Scan PDF tool in your phone’s browser and tap Open camera. Allow camera access when asked.',
        'Tap Book in the mode bar above the shutter. A dashed vertical line appears in the middle of the screen.',
        'Position the phone so the spine sits on that line and the outline covers the whole spread. When it turns green, the spread is captured automatically, or tap the shutter.',
        'The shot is cut down the middle into two pages, left first, then right, each straightened on its own.',
        'Turn the page and hold the phone in the same position. The scanner sees that the view has changed and captures the next spread when it is steady.',
        'For the cover, a single page or a fold-out, switch back to Document mode for that shot.',
        'Tap the thumbnail at the bottom left to review all the pages, then Save PDF.',
      ] },
      { type: 'callout', title: 'Fingers in the shot? Erase them', text: 'Holding a stiff book open almost always puts a fingertip in the margin. On the review screen, open Cleanup and brush over the finger: it is painted out to match the page. Keep your fingers in the outer margins and this takes seconds.' },
      { type: 'h2', text: 'Fix the split and the gutter' },
      { type: 'p', text: 'The split follows the middle of the detected spread, so if the book sat off-centre a page can lose a strip of text near the spine or gain a strip from its neighbour. Open Crop on that page and drag the inner edge; a magnifier shows exactly where it lands. For a thick book whose pages curve sharply into the spine, the straightening flattens the page outline but cannot fully unbend curved lines of text near the gutter. Pressing the book flatter, or shooting one page at a time in Document mode, is the fix for the worst cases.' },
      { type: 'h2', text: 'Pick the right filter for the book' },
      { type: 'table', head: ['Kind of book', 'Filter', 'Why'], rows: [
        ['Novel, manual, printed notes', 'B&W or Grayscale', 'Crisp text, smaller file'],
        ['Old book with yellowed paper', 'Auto color', 'Whitens the paper, keeps any colour'],
        ['Pencil annotations or faded print', 'Light text', 'Darkens faint marks without blowing out the paper'],
        ['Photo or art book', 'Original or Auto color', 'Keeps the images natural'],
      ] },
      { type: 'p', text: 'Pick a filter on one page, check it, then tap “Apply this filter to all” pages so the whole book looks consistent.' },
      { type: 'callout', title: 'A book is a lot of pages — nothing uploads', text: 'The camera work, the page splitting and the cleanup all run in the browser on your device. For a whole book that privacy matters: every page stays local, there is no account and no upload limit. The session is stored on your phone as you go, so a reload or a dead battery break does not lose the chapters already scanned.' },
      { type: 'h2', text: 'Save it searchable and small enough to keep' },
      { type: 'p', text: 'When you tap Save PDF, leave Recognize text (OCR) on and choose the book’s language. Text recognition runs on the phone and adds a hidden text layer, so you can search the book and copy quotes out of it. For size, a text book at the Small or Medium file size stays very readable; keep High for art books. Choose A4 or Letter if you want every page the same size, or Fit page to keep the book’s own proportions.' },
      { type: 'h2', text: 'Check the order before you close the book' },
      { type: 'p', text: 'Skim the thumbnails in Reorder before saving: a skipped spread is easy to fix while the book is still open on the table and painful later. If two pages are swapped, drag them into place by their handles. Then save, and spot-check one page from the middle of the book by searching for a word you know is on it.' },
    ],
    faqs: [
      { q: 'Do I need a book scanner to scan a book into a PDF?', a: 'No. A phone camera and a browser scanner with a book mode produce a clean multi-page PDF. A dedicated book scanner mainly helps if you digitise books every day.' },
      { q: 'Can I photograph two pages at once?', a: 'Yes. In Book mode, each shot of an open spread is split into separate left and right pages. For thick books with strongly curved pages, scanning one page at a time in Document mode gives flatter text near the spine.' },
      { q: 'How do I get the text to look crisp?', a: 'Even light, a steady phone and the B&W or Grayscale filter. Apply the filter to all pages so the book looks consistent.' },
      { q: 'Can I search the text of the scanned book?', a: 'Yes. Leave Recognize text (OCR) on when saving and choose the language. That adds a text layer so search and copy work.' },
      { q: 'How big will the file be?', a: 'Every page is an image, so a long book can be large. Save with File size set to Medium or Small for text books; it stays readable at a fraction of the size.' },
    ],
    related: ['how-to-scan-documents-to-pdf-with-your-phone', 'how-to-scan-multiple-pages-into-one-pdf', 'how-to-straighten-a-crooked-scan-or-photo', 'how-to-compress-a-scanned-pdf'],
  },

  {
    slug: 'how-to-replace-an-image-in-a-pdf',
    title: 'How to Replace an Image in a PDF (Free)',
    description: 'Replace an image in a PDF for free — swap an old logo, photo or headshot for a new one in the same spot, in your browser, with no upload and no account.',
    keyword: 'how to replace an image in a pdf',
    category: 'Editing & Signing',
    published: '2026-09-22',
    tool: 'edit-pdf',
    experience: 'I update a dated supplier logo that sits on every quote template. Clicking the old image, swapping in the new file, and keeping the same frame has saved me from re-exporting a whole document more times than I can count.',
    blocks: [
      { type: 'p', text: 'Replacing an image in a PDF — a stale logo, the wrong product photo, an outdated headshot — means selecting the old picture and swapping in a new file. The replacement takes over the original frame, so the page layout does not move, the text stays put, and the rest of the document is untouched.' },
      { type: 'h2', text: 'When to replace instead of rebuild' },
      { type: 'p', text: 'Swap-in is the right move when exactly one image is wrong and everything around it is correct. The old image is detected as its own object, the new one lands in the same position and size, and the surrounding content is written back unchanged. If half the page needs changing, that is a rebuild — but a single bad image usually is not.' },
      { type: 'h2', text: 'Replace an image' },
      { type: 'steps', items: [
        'Open the Edit PDF tool and add your PDF.',
        'Go to the page that holds the image.',
        'Click the image — when it is detected as an object, a small toolbar appears.',
        'Choose Replace and pick the new image from your device (PNG or JPEG).',
        'The new image lands in the original frame — drag and resize it if the fit needs tuning.',
        'Save and download the updated PDF.',
      ] },
      { type: 'callout', title: 'PNG or JPEG only', text: 'Replacement images must be PNG or JPEG. For a logo that sits on a coloured or shaded area, a PNG with a transparent background stops the new image from arriving with a white box around it.' },
      { type: 'h2', text: 'Match the frame or the swap looks amateur' },
      { type: 'table', head: ['What to match', 'Why it matters'], rows: [
        ['Aspect ratio', 'Prevents the image from being stretched or squashed inside the existing frame'],
        ['Resolution', 'A low-resolution image dropped into a large frame looks soft — match or exceed the original\'s pixels'],
        ['Background and style', 'A white-background replacement on a shaded page is instantly visible'],
      ] },
      { type: 'h2', text: 'When a replacement is not possible' },
      { type: 'p', text: 'If clicking the image does nothing, the PDF is scanned or flattened and the picture is part of the page — there is no separate object to swap. The honest answer is to correct the image in its source file and export the PDF again. A redaction box can cover an unwanted graphic and the crop tool can trim one near the margin, but neither is a real replacement, and neither reads well on a printed document.' },
      { type: 'h2', text: 'Delete instead of replace' },
      { type: 'p', text: 'When the image should not be there at all — a duplicated headshot, a graphic from a rejected draft — the same toolbar offers Delete. Removing it entirely is cleaner than replacing it with something patchy, and it frees the space for the layout that was always meant to be there.' },
      { type: 'h2', text: 'Verify the result in a fresh viewer' },
      { type: 'p', text: 'After downloading, open the file in another reader and check the replaced image against the caption, the text wrapping around it, and any border. Image swaps are the kind of change that looks fine in the tool that made it and wrong in the one it was made for.' },
    ],
    faqs: [
      { q: 'Can I replace an image in a scanned PDF?', a: 'No — in a scanned or flattened file the image is fused into the page, so there is no object to replace. Correct the image in its source and export the PDF again.' },
      { q: 'What formats can the replacement be?', a: 'PNG or JPEG. PNG is the right choice for a logo with transparency; JPEG is fine for photographs.' },
      { q: 'Will the replacement keep the original size and position?', a: 'Yes — the new image inherits the original frame. Use the drag and resize controls to fine-tune the fit, and match the aspect ratio to avoid distortion.' },
      { q: 'Does replacing an image move the text around it?', a: 'No. Only the image object is rewritten; the surrounding text and layout are exported exactly as they were.' },
      { q: 'Can I just delete the image instead?', a: 'Yes. Select the image and choose Delete to remove it entirely, which is the right move when the picture is no longer wanted at all.' },
    ],
    related: ['how-to-extract-images-from-a-pdf', 'why-are-my-pdf-images-not-showing', 'how-to-edit-a-pdf-without-adobe'],
  },
];