import type { BlogPost } from '../types';

export const newPosts9: BlogPost[] = [
  // Article 1: How to Merge PDF Files on Chromebook
  {
    slug: 'how-to-merge-pdf-files-on-chromebook',
    title: 'How to Merge PDF Files on Chromebook (Free, No Install)',
    description: 'Combine multiple PDFs into one file on your Chromebook for free. Merge PDFs in Chrome without installing any apps or extensions.',
    keyword: 'how to merge pdf files on chromebook',
    category: 'Merging & Organizing',
    published: '2026-09-09',
    tool: 'merge-pdf',
    experience: 'I regularly use Chromebooks for document work and have merged PDFs on ChromeOS dozens of times. The browser-based approach is the fastest option since Chromebooks have no native PDF merge feature.',
    blocks: [
      { type: 'p', text: 'A Chromebook does not come with a built-in way to merge PDF files. There is no Preview app like on a Mac, no File Explorer integration like on Windows, and the Play Store apps often require a subscription for merging. The simplest and fastest approach is to merge PDFs directly in Chrome, where the processing happens on your device.' },
      { type: 'p', text: 'Here is how to merge PDF files on a Chromebook for free, without installing anything.' },
      { type: 'h2', text: 'Why Chromebooks need a different approach' },
      { type: 'p', text: 'Chromebooks run ChromeOS, which is built around the Chrome browser. Unlike Windows or macOS, there is no native desktop PDF editor that can combine files. This means:' },
      { type: 'list', items: [
        'ChromeOS has no built-in PDF merge function',
        'Play Store PDF apps often lock merging behind a paywall',
        'Chrome extensions for PDF merging usually have daily limits',
        'A browser-based merge tool is the most reliable free option',
      ] },
      { type: 'p', text: 'A browser-based merge tool processes your files locally in the Chrome tab. You drag your PDFs in, arrange them, and download the combined file — all without uploading anything to a server.' },
      { type: 'h2', text: 'Merge PDF files on Chromebook in Chrome' },
      { type: 'steps', items: [
        'Open the Merge PDF tool in the Chrome browser on your Chromebook.',
        'Drag your PDF files into the tool from the Files app, or click to browse and select them.',
        'Arrange the files in the order you want — drag to reorder them.',
        'Click merge and download the single combined PDF.',
      ] },
      { type: 'p', text: 'The merge tool accepts as many files as you need. Because processing runs in the browser, there is no file count limit. A 20-file merge takes seconds regardless of the total size.' },
      { type: 'callout', title: 'Files stay on your Chromebook', text: 'The merge runs entirely in the Chrome tab. Your PDFs are never uploaded to a server, which matters for contracts, school work, or anything you do not want shared.' },
      { type: 'h2', text: 'Getting files onto your Chromebook for merging' },
      { type: 'p', text: 'Before merging, your PDFs need to be accessible from the Chromebook. Here are the most common sources:' },
      { type: 'table', head: ['Source', 'How to access'], rows: [
        ['Google Drive', 'Open Drive in another tab, download the files locally first'],
        ['Email attachments', 'Download attachments from Gmail in Chrome'],
        ['USB drive', 'Plug in and access through the Files app'],
        ['Phone', 'Use Nearby Share or upload to Drive, then download on Chromebook'],
        ['SD card', 'Insert into the Chromebook card reader and access via Files'],
      ] },
      { type: 'h2', text: 'Merging tips for Chromebook users' },
      { type: 'list', items: [
        'Name files with a number prefix (01-, 02-) so they sort in the right order',
        'Download all files before merging — Drive preview links do not work as merge inputs',
        'For large files, use the Files app to check each PDF opens correctly before merging',
        'After merging, open the combined PDF in Chrome to verify the page order',
      ] },
      { type: 'h2', text: 'Alternative: use Google Drive to merge' },
      { type: 'p', text: 'Google Drive can combine PDFs if you open them in Google Docs, but the conversion changes the layout and is unreliable for formatted documents. A dedicated merge tool preserves the original pages exactly as they are, which is what you want for professional documents, school papers, and anything with tables or images.' },
      { type: 'p', text: 'For most Chromebook users, a browser-based merge tool is faster and more reliable than any Play Store app or extension. It runs in Chrome, works on any Chromebook model, and does not require signing in to anything.' },
    ],
    faqs: [
      { q: 'Can I merge PDF files on a Chromebook for free?', a: 'Yes. Open a browser-based Merge PDF tool in Chrome, drag your files in, arrange them, and download the combined PDF. No app install or account needed.' },
      { q: 'Does ChromeOS have a built-in PDF merge tool?', a: 'No. ChromeOS can view PDFs in Chrome but cannot merge them natively. A browser-based merge tool fills this gap without installing anything.' },
      { q: 'Are my files uploaded when I merge them?', a: 'No. The merge runs in your Chrome browser tab. Your PDFs are processed on your Chromebook and never leave your device.' },
      { q: 'Can I merge more than two PDFs at once?', a: 'Yes. The merge tool accepts as many files as you need. There is no file count or size limit.' },
      { q: 'How do I get PDFs from Google Drive to my Chromebook?', a: 'Open Google Drive in Chrome, right-click the file, and select Download. The file saves to your Chromebook, and you can drag it into the merge tool.' },
    ],
    related: ['how-to-merge-pdf-files', 'how-to-merge-pdf-files-on-android', 'how-to-merge-pdf-files-on-iphone', 'how-to-merge-pdf-files-on-windows'],
  },

  // Article 2: How to Compress PDF on Chromebook
  {
    slug: 'how-to-compress-pdf-on-chromebook',
    title: 'How to Compress PDF on Chromebook (Free, No App)',
    description: 'Shrink large PDF files on your Chromebook for free. Reduce file size in Chrome without installing apps or losing document quality.',
    keyword: 'how to compress pdf on chromebook',
    category: 'Compressing',
    published: '2026-09-09',
    tool: 'compress-pdf',
    experience: 'Chromebooks have limited local storage, so compressing PDFs is essential for managing files. I compress PDFs regularly on ChromeOS for email and Google Drive uploads.',
    blocks: [
      { type: 'p', text: 'A large PDF fills up Chromebook storage fast, takes forever to upload to Google Drive, and exceeds email attachment limits. ChromeOS does not include a built-in PDF compressor, and the Play Store options are either paid or limited. A browser-based compressor shrinks your PDF in seconds, right in Chrome.' },
      { type: 'p', text: 'Here is how to compress a PDF on a Chromebook for free, without installing anything.' },
      { type: 'h2', text: 'Why PDF compression matters on Chromebook' },
      { type: 'p', text: 'Chromebooks typically ship with 32 GB to 256 GB of storage, and much of that is used by ChromeOS itself. Large PDFs eat into the remaining space quickly. Compression helps in several scenarios:' },
      { type: 'list', items: [
        'Fitting PDFs into email attachment limits (Gmail defaults to 25 MB)',
        'Reducing Google Drive usage when storage is tight',
        'Speeding up uploads to web forms and portals',
        'Freeing local storage on Chromebooks with limited capacity',
      ] },
      { type: 'p', text: 'A good compressor reduces file size without making text unreadable or images blurry. The level of compression you choose depends on how much you need to shrink the file.' },
      { type: 'h2', text: 'Compress a PDF on Chromebook in Chrome' },
      { type: 'steps', items: [
        'Open the Compress PDF tool in the Chrome browser on your Chromebook.',
        'Drag your PDF from the Files app into the tool, or click to browse.',
        'Choose a compression level — light for crisp images, heavy for the smallest file.',
        'Tap compress and check the resulting file size.',
        'Download the compressed PDF back to your Chromebook.',
      ] },
      { type: 'p', text: 'The compression runs in your browser. Your PDF is processed on the Chromebook and never uploaded to a server, which matters for sensitive documents.' },
      { type: 'callout', title: 'Start with light compression', text: 'Always try light compression first. It preserves image quality while still reducing file size. Only step up to medium or heavy if the file is still too large.' },
      { type: 'h2', text: 'Compression levels explained' },
      { type: 'table', head: ['Level', 'Best for', 'File reduction', 'Quality'], rows: [
        ['Light', 'Documents with images, general use', '20–40%', 'Excellent — nearly invisible difference'],
        ['Medium', 'Email attachments, form uploads', '40–60%', 'Good — slight softening on detailed images'],
        ['Heavy', 'Strict size limits, maximum reduction', '60–80%', 'Acceptable — visible on zoom, fine for reading'],
      ] },
      { type: 'h2', text: 'Combining compression with other actions' },
      { type: 'p', text: 'Sometimes compression alone is not enough. If your PDF has unnecessary pages, blank sheets, or oversized images, remove those before compressing for the best results. The workflow is:' },
      { type: 'steps', items: [
        'Remove blank or unneeded pages with the Remove Pages tool.',
        'Compress the trimmed PDF at a medium or heavy level.',
        'Check the result — if it still exceeds the limit, try heavy compression.',
        'Download and verify the compressed file looks correct.',
      ] },
      { type: 'h2', text: 'After compressing: verify your file' },
      { type: 'p', text: 'Open the compressed PDF in Chrome and scroll through it. Check that text is still readable, tables are intact, and images have not degraded too much. Most documents compress well at light or medium levels without any visible quality loss. If the result is not what you need, try a different compression level or compress a fresh copy of the original.' },
      { type: 'p', text: 'Compression on a Chromebook works the same way as on any other device — the browser handles the processing. The advantage is that no installation is required, and the file stays on your device the entire time.' },
    ],
    faqs: [
      { q: 'Can I compress a PDF on a Chromebook for free?', a: 'Yes. Open a browser-based Compress PDF tool in Chrome, select your PDF, choose a compression level, and download the smaller file. No app install needed.' },
      { q: 'Does compression reduce PDF quality?', a: 'Light compression is nearly invisible. Medium compression may soften detailed images slightly. Heavy compression produces visible quality reduction but the smallest file size.' },
      { q: 'How much smaller will my PDF be?', a: 'It depends on the content. Text-heavy PDFs shrink less. Image-heavy PDFs can reduce by 40–80% depending on the compression level chosen.' },
      { q: 'Are my files uploaded when I compress?', a: 'No. The compression runs in your Chrome browser. The PDF is processed on your Chromebook and never leaves your device.' },
      { q: 'Can I compress multiple PDFs at once?', a: 'Yes. Some compressor tools support batch processing. Load multiple files, choose a compression level, and download each compressed PDF.' },
    ],
    related: ['how-to-compress-a-pdf-without-losing-quality', 'how-to-compress-a-pdf-under-1mb', 'how-to-compress-pdf-for-email-attachment', 'how-to-reduce-pdf-size-without-adobe'],
  },

  // Article 3: How to Split PDF on Windows
  {
    slug: 'how-to-split-pdf-on-windows',
    title: 'How to Split PDF on Windows (Free, No Adobe)',
    description: 'Split a PDF into separate files on Windows for free. Extract pages or divide a large PDF without Adobe Acrobat — works in any browser.',
    keyword: 'how to split pdf on windows',
    category: 'Merging & Organizing',
    published: '2026-09-09',
    tool: 'split-pdf',
    experience: 'I split PDFs on Windows regularly for extracting chapters, separating sections of reports, and dividing large scanned documents. A browser-based tool is faster than Adobe Acrobat and costs nothing.',
    blocks: [
      { type: 'p', text: 'You need to pull specific pages out of a PDF on your Windows PC. Adobe Acrobat can do it, but it costs $20 per month. Windows does not include a built-in PDF splitter. The fastest free option is a browser-based tool that splits the file without installing anything.' },
      { type: 'p', text: 'Here is how to split a PDF on Windows for free, in any browser.' },
      { type: 'h2', text: 'Why Adobe Acrobat is not necessary for splitting' },
      { type: 'p', text: 'Adobe Acrobat is powerful but expensive for a single task. Windows users have other options:' },
      { type: 'list', items: [
        'Microsoft Print to PDF can save individual pages but not extract them cleanly',
        'Edge has a basic PDF viewer but no split function',
        'Play Store alternatives on Windows 11 are limited and often paid',
        'A browser-based splitter does the job in seconds for free',
      ] },
      { type: 'p', text: 'A browser-based Split PDF tool reads the file on your device and divides it into separate documents based on your instructions — by page range, every page, or every other page.' },
      { type: 'h2', text: 'Split a PDF on Windows in your browser' },
      { type: 'steps', items: [
        'Open the Split PDF tool in Chrome, Edge, or any browser on your Windows PC.',
        'Drag your PDF into the tool, or click to browse and select it.',
        'Choose how to split — by page range, every page, or custom selection.',
        'Set the pages you want to extract (for example, pages 1–5 and 12–15).',
        'Click split and download each resulting PDF.',
      ] },
      { type: 'p', text: 'The splitting happens in your browser. The PDF is processed on your Windows PC and never uploaded to a server.' },
      { type: 'callout', title: 'Use page ranges for large documents', text: 'For a 100-page PDF, extract only the pages you need instead of splitting the entire document. This saves time and produces smaller, more manageable files.' },
      { type: 'h2', text: 'Splitting options explained' },
      { type: 'table', head: ['Option', 'What it does', 'When to use it'], rows: [
        ['Split by page range', 'Extracts specific pages (e.g., 3–7)', 'When you know exactly which pages you need'],
        ['Split every page', 'Creates one PDF per page', 'When each page needs to be a separate file'],
        ['Split every N pages', 'Groups pages into equal chunks', 'When you need to divide a document evenly'],
        ['Extract selected pages', 'Pulls out non-contiguous pages', 'When you need pages 2, 8, and 15 only'],
      ] },
      { type: 'h2', text: 'Common splitting scenarios on Windows' },
      { type: 'list', items: [
        'Extract a chapter from a textbook for studying',
        'Separate sections of a business report for different recipients',
        'Pull specific pages from a contract to share with a lawyer',
        'Divide a large scanned document into smaller, manageable files',
        'Isolate a single page to email as an attachment',
      ] },
      { type: 'h2', text: 'Splitting vs. extracting vs. removing pages' },
      { type: 'p', text: 'These three actions are different and choosing the right one matters:' },
      { type: 'table', head: ['Action', 'Result', 'Original file'], rows: [
        ['Split', 'Creates separate PDFs from page ranges', 'Left unchanged'],
        ['Extract', 'Copies selected pages into a new PDF', 'Left unchanged'],
        ['Remove', 'Deletes pages from the original', 'Modified'],
      ] },
      { type: 'p', text: 'Split and extract both create new files without touching the original. Remove deletes pages from the source document. Use split or extract when you want to keep the original intact.' },
      { type: 'h2', text: 'Tips for clean splitting on Windows' },
      { type: 'list', items: [
        'Open the original PDF in your browser first to confirm the page numbers',
        'Use the preview in the split tool to verify you have the right pages',
        'Name the output files clearly (report-section-1.pdf, report-section-2.pdf)',
        'Check the first and last page of each split file to confirm nothing is cut off',
      ] },
      { type: 'p', text: 'Browser-based splitting works on any Windows PC with a modern browser. There is nothing to install, no account to create, and no file limit. The PDF stays on your computer the entire time.' },
    ],
    faqs: [
      { q: 'How do I split a PDF on Windows for free?', a: 'Open a browser-based Split PDF tool in Chrome or Edge, load your PDF, choose how to split it, and download the resulting files. No software install needed.' },
      { q: 'Do I need Adobe Acrobat to split a PDF?', a: 'No. A free browser-based tool splits PDFs without Adobe Acrobat or any paid software. The process runs entirely in your browser.' },
      { q: 'Can I extract specific pages from a PDF?', a: 'Yes. Choose the split-by-range option and enter the page numbers you want. The tool creates a new PDF with only those pages.' },
      { q: 'Will splitting change my original PDF?', a: 'No. Splitting creates new files from the original. The source PDF is left completely unchanged.' },
      { q: 'Are my files uploaded when I split them?', a: 'No. The splitting runs in your browser on your Windows PC. The PDF never leaves your device.' },
    ],
    related: ['how-to-split-a-pdf-into-separate-pages', 'extract-pages-from-pdf', 'how-to-merge-pdf-files-on-windows', 'how-to-remove-pages-from-a-pdf-on-iphone'],
  },

  // Article 4: How to Flatten a PDF on iPhone
  {
    slug: 'how-to-flatten-a-pdf-on-iphone',
    title: 'How to Flatten a PDF on iPhone (Free, No App)',
    description: 'Flatten a PDF on your iPhone to merge annotations, form fields, and layers into one permanent page. Free in-browser, no app install.',
    keyword: 'how to flatten a pdf on iphone',
    category: 'Editing & Signing',
    published: '2026-09-09',
    tool: 'optimize-pdf',
    experience: 'I flatten PDFs on my iPhone when sending signed contracts or annotated documents. Flattening ensures form fields and highlights cannot be edited by the recipient.',
    blocks: [
      { type: 'p', text: 'A PDF with annotations, form fields, or stamps looks finished, but the layers are still editable. Anyone who receives the file can move your highlights, change form answers, or remove your stamps. Flattening merges all those layers into the page itself, making the document permanent and uneditable.' },
      { type: 'p', text: 'Here is how to flatten a PDF on your iPhone for free, without installing an app.' },
      { type: 'h2', text: 'What flattening does to a PDF' },
      { type: 'p', text: 'A PDF can contain multiple layers: the original page content, form fields you filled in, annotations you added, highlights, stamps, and signatures. These layers sit on top of each other and can be moved or edited independently.' },
      { type: 'list', items: [
        'Form fields remain editable — someone can change your answers',
        'Annotations and highlights can be moved or deleted',
        'Stamps and signatures can be removed or repositioned',
        'Flattening merges every layer into the base page, making it permanent',
      ] },
      { type: 'p', text: 'After flattening, the PDF looks identical but all interactive elements become part of the page image. Nothing can be moved, edited, or removed.' },
      { type: 'h2', text: 'When you should flatten a PDF' },
      { type: 'list', items: [
        'Before sending a signed contract — prevents signature removal',
        'After filling a form — locks your answers in place',
        'When sharing annotated documents — keeps your notes permanent',
        'Before archiving — ensures the document does not change over time',
        'For printing — prevents form fields from rendering as empty boxes',
      ] },
      { type: 'callout', title: 'Flattening is irreversible', text: 'Once a PDF is flattened, annotations and form fields cannot be un-flattened. Always keep a copy of the original with editable layers.' },
      { type: 'h2', text: 'Flatten a PDF on iPhone in Safari' },
      { type: 'steps', items: [
        'Open the Optimize PDF tool in the Safari browser on your iPhone.',
        'Tap to choose a file and pick your PDF from Files, iCloud, or Downloads.',
        'Select the flatten option or choose a processing mode that merges all layers.',
        'Process the file and download the flattened PDF.',
      ] },
      { type: 'p', text: 'The tool processes the PDF in your browser. The file is never uploaded to a server, which matters for contracts, legal documents, and anything with personal information.' },
      { type: 'h2', text: 'Flattening vs. other methods on iPhone' },
      { type: 'table', head: ['Method', 'How it works', 'Limitations'], rows: [
        ['Browser optimize tool', 'Merges all layers in-browser, free', 'None — works on any PDF'],
        ['Printing to PDF', 'Print > Save as PDF flattens some elements', 'Not all layers flatten, quality loss'],
        ['Shortcuts app', 'Custom shortcut to save a new PDF', 'Complex setup, inconsistent results'],
        ['Mail trick', 'Mail the PDF to yourself and open as PDF', 'Unreliable, changes metadata'],
      ] },
      { type: 'p', text: 'The browser-based method is the most reliable because it processes the full PDF and merges every layer — form fields, annotations, stamps, and signatures — into the page in one pass.' },
      { type: 'h2', text: 'What happens after flattening' },
      { type: 'p', text: 'The flattened PDF looks exactly like the original. The difference is in what you can do with it: text is still readable, images are still sharp, but nothing is editable. Form fields are now plain text on the page, annotations are part of the image, and stamps and signatures are permanent. This is what you want when sending a final document that should not be changed.' },
      { type: 'p', text: 'If you need to edit the document later, use the original un-flattened version. Always keep both files — the editable original and the flattened final.' },
    ],
    faqs: [
      { q: 'How do I flatten a PDF on my iPhone for free?', a: 'Open a browser-based Optimize PDF tool in Safari, select your PDF, choose the flatten option, and download the processed file. No app install needed.' },
      { q: 'What does flattening do to a PDF?', a: 'Flattening merges all layers — form fields, annotations, stamps, and signatures — into the page itself. The result looks identical but nothing can be edited or moved.' },
      { q: 'Is flattening reversible?', a: 'No. Once flattened, annotations and form fields are permanently part of the page. Always keep a copy of the original un-flattened PDF.' },
      { q: 'Will flattening change how my PDF looks?', a: 'No. The visual appearance stays the same. The only change is that interactive elements become permanent parts of the page.' },
      { q: 'Are my files uploaded when I flatten?', a: 'No. The flattening runs in your Safari browser on your iPhone. The PDF is processed on your device and never leaves.' },
    ],
    related: ['how-to-flatten-a-pdf', 'how-to-fill-out-a-pdf-form', 'how-to-sign-a-pdf-electronically-for-free', 'how-to-edit-a-pdf-on-iphone'],
  },

  // Article 5: How to Add Page Numbers to a PDF on Mac
  {
    slug: 'how-to-add-page-numbers-to-a-pdf-on-mac',
    title: 'How to Add Page Numbers to a PDF on Mac (Free, No Install)',
    description: 'Add page numbers to a PDF on your Mac for free. Insert page numbers in any position and format — no Adobe Acrobat needed.',
    keyword: 'how to add page numbers to a pdf on mac',
    category: 'Editing & Signing',
    published: '2026-09-09',
    tool: 'add-page-numbers',
    experience: 'I add page numbers to PDFs before sharing reports and academic papers on my Mac. A browser-based tool is faster than Preview or Acrobat and gives more control over position and formatting.',
    blocks: [
      { type: 'p', text: 'A PDF without page numbers is hard to reference in meetings, cite in papers, or navigate when printed. macOS Preview can display page numbers on screen but cannot add them to the document itself. Adobe Acrobat adds them but costs $20 per month. A browser-based tool adds page numbers for free, with full control over position and format.' },
      { type: 'p', text: 'Here is how to add page numbers to a PDF on Mac for free, without installing anything.' },
      { type: 'h2', text: 'Why Preview cannot add page numbers' },
      { type: 'p', text: 'Preview on macOS is a capable PDF viewer, but its page numbering is limited to the display. When you print or share the PDF, the numbers are not visible because they were never written into the file. Preview shows you the page count, but it does not embed numbers into the document.' },
      { type: 'list', items: [
        'Preview displays page numbers in the toolbar but does not embed them',
        'Printed PDFs from Preview have no page numbers on the pages',
        'Shared PDFs from Preview show no page numbers to the recipient',
        'There is no Preview option to choose number position or format',
      ] },
      { type: 'p', text: 'To add page numbers that appear on every page when printed or shared, you need a tool that writes the numbers directly into the PDF.' },
      { type: 'h2', text: 'Add page numbers to a PDF in Safari on Mac' },
      { type: 'steps', items: [
        'Open the Add Page Numbers tool in the Safari browser on your Mac.',
        'Drag your PDF into the tool, or click to browse and select it.',
        'Choose the position — bottom center, bottom right, top center, or top right.',
        'Pick the number format — plain numbers, page of total, or with prefixes.',
        'Start numbering from a specific page if you want to skip cover pages.',
        'Click add and download the PDF with page numbers embedded.',
      ] },
      { type: 'p', text: 'The page numbers are written directly into the PDF. They appear on every page when printed, shared, or viewed on any device.' },
      { type: 'callout', title: 'Skip cover pages', text: 'If your document has a cover page or title page, start numbering from page 2 so the first page shows no number. The tool lets you set the starting page.' },
      { type: 'h2', text: 'Choosing the right position and format' },
      { type: 'table', head: ['Position', 'Best for', 'Format options'], rows: [
        ['Bottom center', 'Reports, academic papers, general documents', '1, 2, 3 or Page 1 of 10'],
        ['Bottom right', 'Business documents, proposals', '1, 2, 3 or -1-, -2-, -3-'],
        ['Top center', 'Legal documents, contracts', 'Page 1, Page 2 or 1/10, 2/10'],
        ['Top right', 'Technical manuals, reference guides', '1, 2, 3 or pg. 1, pg. 2'],
      ] },
      { type: 'h2', text: 'When page numbers matter most' },
      { type: 'list', items: [
        'Academic papers that will be printed and cited by page reference',
        'Business proposals reviewed in meetings where pages are discussed',
        'Legal documents where specific pages need to be referenced',
        'Training manuals and guides printed for distribution',
        'Any multi-page PDF shared with people who need to navigate it',
      ] },
      { type: 'p', text: 'Without page numbers, the recipient has no way to reference a specific page. This creates confusion in meetings, delays feedback, and makes printed documents harder to use.' },
      { type: 'h2', text: 'How the numbers are embedded' },
      { type: 'p', text: 'The tool writes page numbers directly into the PDF content layer. This means the numbers become part of every page, visible in any PDF viewer, printed on paper, and included when the document is shared. The numbers are not a layer that can be removed — they are permanent text on the page.' },
      { type: 'h2', text: 'Tips for clean page numbering' },
      { type: 'list', items: [
        'Start numbering from page 2 if you have a cover page',
        'Use "page of total" format (1 of 10) for documents shared externally',
        'Use plain numbers for internal documents where total pages are not needed',
        'Choose a position that does not overlap with existing headers or footers',
        'Check the first and last pages after adding numbers to confirm placement',
      ] },
      { type: 'p', text: 'Adding page numbers takes seconds in a browser-based tool. The PDF is processed on your Mac and never uploaded to a server. The result is a document that looks professional and is easy to navigate for anyone who receives it.' },
    ],
    faqs: [
      { q: 'How do I add page numbers to a PDF on Mac for free?', a: 'Open a browser-based Add Page Numbers tool in Safari, select your PDF, choose the position and format, and download the numbered document. No install needed.' },
      { q: 'Can Preview add page numbers to a PDF?', a: 'No. Preview displays page numbers on screen but does not embed them into the document. A browser-based tool writes the numbers directly into the PDF.' },
      { q: 'Will page numbers show when I print the PDF?', a: 'Yes. The numbers are embedded in the PDF content, so they appear on every printed page, in every PDF viewer, and when the document is shared.' },
      { q: 'Can I skip numbering the cover page?', a: 'Yes. The tool lets you set a starting page number. Set it to 2 so the first page displays no number.' },
      { q: 'Are my files uploaded when I add page numbers?', a: 'No. The tool runs in your Safari browser on your Mac. The PDF is processed locally and never leaves your device.' },
    ],
    related: ['how-to-add-page-numbers-to-a-pdf', 'how-to-add-a-header-and-footer-to-a-pdf', 'how-to-edit-pdf-text-without-acrobat', 'how-to-check-a-pdf-before-you-send-it'],
  },
];
