import type { BlogPost } from '../types';

export const newPosts4: BlogPost[] = [
  // Article 1: How to Reorder Pages in a PDF
  {
    slug: 'how-to-reorder-pages-in-a-pdf',
    title: 'How to Reorder Pages in a PDF (Free, No Software)',
    description: 'Rearrange PDF pages into the right order in seconds. Free in-browser tool to move, reorder, and fix jumbled pages — no install, no sign-up.',
    keyword: 'how to reorder pages in a pdf',
    category: 'Merging & Organizing',
    published: '2026-08-28',
    updated: '2026-10-04',
    tool: 'organize-pdf',
    blocks: [
      { type: 'p', text: 'It happens to almost everyone. You scan ten pages in the wrong order, export a report with a section out of place, or merge two PDFs and realise the pages came out jumbled. Reordering pages sounds like it should be simple — but many PDF tools hide the option, and desktop editors charge money for what should be a one-click fix.' },
      { type: 'p', text: 'The good news is that you can reorder pages in a PDF for free, right in your browser, without installing anything. Here is how.' },
      { type: 'h2', text: 'Why PDF page order goes wrong' },
      { type: 'list', items: [
        'Scanners and multi-function printers often output pages in the opposite order they were fed',
        'A scanned stapled packet arrives with two pages back to front',
        'Merging multiple PDFs can place files in the wrong sequence',
        'A report gains an appendix that should sit before the summary, not after it',
        'Phone scan apps batch photos out of sequence',
      ] },
      { type: 'callout', title: 'Fix it, do not rescan', text: 'You almost never need to rescan a whole document because a few pages are out of order. Reordering the existing pages keeps the original quality and takes seconds.' },
      { type: 'h2', text: 'Reorder PDF pages in your browser (free)' },
      { type: 'p', text: 'The Organize PDF tool rebuilds your document in whatever page order you type, then hands you the corrected PDF. Nothing is uploaded anywhere, and no account is needed.' },
      { type: 'steps', items: [
        'Open the Organize PDF tool.',
        'Drag your PDF into the upload area, or click to browse and select it.',
        'The order box fills in with the current sequence — 1,2,3,4,5 for a five-page file — and shows the total page count.',
        'Retype the numbers in the order you want, separated by commas, such as 1,3,2,4,5. A preview below the box shows the pages in their new order.',
        'Click Organize PDF, check the result, then download your fixed PDF.',
      ] },
      { type: 'h2', text: 'How to rearrange pages in a PDF: what the order box does' },
      { type: 'p', text: 'Each number is a page of the original file, and the position you write it in is where it lands. That one rule covers moving, reversing and dropping pages:' },
      { type: 'table', head: ['For a 5-page PDF, you type', 'You get'], rows: [
        ['1,3,2,4,5', 'Pages 2 and 3 swapped'],
        ['5,1,2,3,4', 'The last page moved to the front'],
        ['5,4,3,2,1', 'The whole document reversed'],
        ['1,2,4,5', 'Page 3 left out of the new file'],
      ] },
      { type: 'callout', title: 'Every page you leave out is dropped', text: 'The new PDF contains only the numbers in the box. Before you download, check the count shown under the box against the document\'s total pages — if they differ and you did not mean to remove anything, a page number is missing.' },
      { type: 'h2', text: 'Preview the new order before you save' },
      { type: 'p', text: 'Nothing is written until you run the tool, so a wrong number costs nothing: edit the box and the preview updates. The preview strip is your map — the sequence it shows is the sequence that downloads. Your original file is never changed, so if the result is wrong you can simply run it again.' },
      { type: 'h2', text: 'Reordering when you have multiple PDFs' },
      { type: 'p', text: 'The organizer works on one PDF at a time, so if your pages are scattered across several files, merge them first, then reorder the combined document. To reverse a long document — a double-sided scan that came out backwards — type the page numbers from last to first, or follow the reverse page order guide.' },
      { type: 'h2', text: 'Common reordering mistakes to avoid' },
      { type: 'list', items: [
        'Forgetting to recheck the first and last page after exporting from a scanner',
        'Moving a page but leaving its reverse side in the old position when working from scans',
        'Dropping a page by accident because its number was left out of the order box',
        'Not saving a copy of the original before major rearrangements',
      ] },
      { type: 'p', text: 'Keep the untouched original until you have confirmed the new order looks correct. If you change your mind, you can start again rather than hunting for the source files.' },
    ],
    faqs: [
      { q: 'Can I reorder PDF pages for free without software?', a: 'Yes. A browser-based organizer lets you set a new page order and download the result, with no software to install and no account required.' },
      { q: 'Can I move a page to any position in the document?', a: 'Yes. Write its page number wherever it should go in the order box — first, last or anywhere between — and the preview shows the resulting sequence before you download.' },
      { q: 'Does reordering pages change the PDF quality?', a: 'No. Reordering only changes the sequence of the existing pages; the text, images and rotation on each page stay exactly as they were.' },
      { q: 'How do I reorder pages from several PDFs?', a: 'Merge the files into one PDF first, then open the combined file in the organizer and type the order you need. The organizer itself works on one PDF at a time.' },
      { q: 'Can I reverse the entire page order at once?', a: 'Yes — type the page numbers from last to first, such as 10,9,8,7,6,5,4,3,2,1. That fixes a double-sided scan that came out in the wrong order.' },
      { q: 'Are my pages uploaded to a server?', a: 'No. The organization runs locally in your browser, so your PDF never leaves your device.' },
    ],
    related: ['how-to-reverse-page-order-in-a-pdf', 'how-to-insert-a-page-into-an-existing-pdf', 'how-to-merge-pdf-files', 'how-to-split-a-pdf-into-separate-pages', 'how-to-rotate-a-pdf-and-save-it'],
  },

  // Article 5: How to Insert a Page into an Existing PDF
  {
    slug: 'how-to-insert-a-page-into-an-existing-pdf',
    title: 'How to Insert a Page into an Existing PDF (Free)',
    description: 'Add a page into the middle of a PDF before you share it. Free in-browser tool to merge, reorder, and insert pages into any PDF.',
    keyword: 'how to insert a page into an existing pdf',
    category: 'Merging & Organizing',
    published: '2026-08-28',
    tool: 'organize-pdf',
    blocks: [
      { type: 'p', text: 'A document is almost done, then you realise you need to add a terms page, an appendix, or a scanned signature page into the middle — not at the end. Inserting a page into an existing PDF sounds fiddly, but it is straightforward once you know the trick.' },
      { type: 'p', text: 'The cleanest way is to combine the two PDFs and then place the new page where it belongs. You can do all of it for free in your browser.' },
      { type: 'h2', text: 'The easiest approach: merge, then reorder' },
      { type: 'p', text: 'You cannot really "push" a single page into the middle of an existing document the way you can in a word processor. Instead, you merge the extra page in and reposition it. This two-step routine works in any PDF tool and never damages the original content.' },
      { type: 'steps', items: [
        'Open the Merge PDF tool to combine your main document with the page you want to insert.',
        'Add both PDFs. For a single new page, convert it to a PDF first (for example, a JPG or HEIC photo becomes one PDF page).',
        'Merge them into one file.',
        'Open the Organize PDF tool with the merged file.',
        'Drag the inserted page thumbnail into its correct position in the sequence.',
        'Download the finished PDF with the page exactly where you need it.',
      ] },
      { type: 'callout', title: 'Why merge-then-reorder wins', text: 'Merging preserves the full quality of both documents, and reordering is a non-destructive drag-and-drop. You end up with a clean, correctly-sequenced PDF every time.' },
      { type: 'h2', text: 'Inserting a photo or a scan as a page' },
      { type: 'p', text: 'If the page you want to insert is a photo or a scanned image, you first turn it into a PDF page. Convert the image to PDF, then merge and reorder as above. This is how you add a photographed signature page, a diagram, or a scanned insert without losing quality.' },
      { type: 'h2', text: 'Inserting blank pages or duplicates' },
      { type: 'p', text: 'Sometimes what you actually need is a blank page (for formatting or double-sided printing) or a duplicate of an existing page (say, to hand out separately). The organizer lets you duplicate a page or add an empty one, then move it into place — all before you export the final file.' },
      { type: 'h2', text: 'Check the result before you share' },
      { type: 'p', text: 'After inserting and reordering, open the final PDF and flip through it once. Confirm the inserted page is in the right spot and that nothing was accidentally moved. Keep the original files until you are happy, so you can always start over.' },
    ],
    faqs: [
      { q: 'Can I insert a page into the middle of a PDF for free?', a: 'Yes. Merge the extra page into the document, then use an organizer to drag it into position. Both steps are free and run in your browser.' },
      { q: 'Does inserting a page reduce the PDF quality?', a: 'No. Merging and reordering keep the original quality of every page; they only change the file structure, not the content.' },
      { q: 'How do I insert a photo or scan as a page?', a: 'Convert the image to PDF first, then merge it with your document and reorder the inserted page into place.' },
      { q: 'Can I add a blank page or duplicate an existing page?', a: 'Yes. The organizer lets you add a blank page or duplicate an existing one, then move it anywhere in the document.' },
      { q: 'Is my document uploaded to a server when I insert pages?', a: 'No. When done in-browser, the process can run locally so your PDF never leaves your device.' },
    ],
    related: ['extract-pages-from-pdf', 'how-to-reorder-pages-in-a-pdf', 'how-to-add-a-cover-page-to-a-pdf', 'how-to-merge-pdf-files'],
  },
];
