import type { BlogPost } from '../types';

export const newPosts19: BlogPost[] = [
  {
    slug: 'how-to-convert-a-pdf-to-a-png-image',
    title: 'How to Convert a PDF to a PNG Image',
    description: 'Turn a PDF page into a lossless PNG for slides, social posts, presentations and design work. Free, in-browser, no upload, no sign-up.',
    keyword: 'convert a pdf to a png image',
    category: 'Converting',
    published: '2026-09-24',
    tool: 'pdf-to-jpg',
    blocks: [
      { type: 'p', text: 'A PDF page is drawn when it is rendered, which means it is not stored as a picture you can drop into a slide, a design tool or a chat. Converting a PDF to PNG renders every page to a high-resolution image you can use anywhere — one PNG per page, ordered exactly like the document.' },
      { type: 'h2', text: 'When PNG is the right output (and when JPG is better)' },
      { type: 'p', text: 'PNG uses lossless compression, so text edges, line art and diagrams stay crisp with no softness around the letters. That makes it the format for anything with sharp detail you plan to zoom in on or edit further. The trade-off is file size: a PNG of a text-heavy page is noticeably larger than the equivalent JPG, so photocopies, scans and photos of pages come out smaller and look the same in JPG.' },
      {
        type: 'table', head: ['Situation', 'Best format', 'Reason'],
        rows: [
          ['Diagrams, charts, text-heavy pages', 'PNG', 'Lossless edges and letterforms'],
          ['Photographs and photo-heavy scans', 'JPG', 'Much smaller, visually identical'],
          ['Slides for a deck or social post', 'PNG', 'Crisp at every zoom level'],
          ['Print shop proof', 'PNG at high DPI', 'Print-sharp detail'],
        ],
      },
      { type: 'h2', text: 'Turn a PDF page into a PNG, step by step' },
      { type: 'steps', items: [
        'Open the PDF-to-image tool and drop in your PDF.',
        'Set the output format to PNG.',
        'Choose the render density: low for screen and email, high for print.',
        'Download the PNGs.', ],
      },
      { type: 'p', text: 'Every page becomes its own PNG, named in document order. A five-page file gives you five images, so you can keep just the one chart you need and ignore the rest.' },
      { type: 'callout', title: 'About transparent backgrounds', text: 'PDF pages are rendered onto a white background, so the PNG is not transparent. If you need a sticker or logo with an alpha channel, make the source graphic first and combine it at the design stage — a page render cannot carry the blank parts as transparency.' },
      { type: 'h2', text: 'Get a sharper PNG out of a small file' },
      { type: 'list', items: [
        'Pick the high-density render for anything that will be printed or enlarged.',
        'A text page renders far more clearly as PNG than as a heavy JPG at the same size.',
        'A render is a one-way step: vector text becomes a grid of pixels, so choose the density for your largest intended use before you download.',
      ] },
      { type: 'h2', text: 'Keep the PNG small instead' },
      { type: 'p', text: 'For a slide, an email or a thumbnail, the low-density render is plenty: text stays readable and the file stays light. PNG is lossless by design, so the only real lever on size is the rendered resolution — and that is the setting to revisit when a file grows bigger than you expected.' },
    ],
    faqs: [
      { q: 'Does converting a PDF to PNG lower the quality?', a: 'No — PNG is lossless, so the rendered result keeps every pixel. The render density sets how much detail is captured, so choosing the high setting before downloading protects print and enlargement use.' },
      { q: 'Will a PNG keep clickable links or form fields?', a: 'No. A render is a flat picture of the page, so links, bookmarks and interactive form fields are painted in and cannot be clicked afterwards.' },
      { q: 'How many PNGs do I get from a multi-page PDF?', a: 'One PNG per page, named in document order. Convert the whole file then keep only the pages you need, or run a page extract first to convert a single page.' },
      { q: 'Is a PNG from a PDF transparent?', a: 'Not in a page render — pages are drawn onto a white background. Build any cut-out/transparent asset from the source graphic instead.' },
      { q: 'When should I use JPG instead of PNG?', a: 'For photographs and photo-heavy scans, where JPG is far smaller and looks the same. Choose PNG for text, diagrams and line art that need sharp edges.' },
    ],
    related: ['how-to-convert-pdf-to-image-for-printing', 'how-to-convert-pdf-to-jpg-high-quality', 'how-to-convert-png-to-pdf', 'how-to-extract-images-from-a-pdf'],
  },
  {
    slug: 'how-to-tell-if-a-pdf-is-a-scanned-document',
    title: 'How to Tell If a PDF Is a Scanned Document',
    description: 'Quick tests to identify a scanned PDF and one-click OCR to make it searchable. Free, in-browser, no upload, no sign-up.',
    keyword: 'tell if a pdf is a scanned document',
    category: 'Troubleshooting',
    published: '2026-09-24',
    tool: 'ocr-pdf',
    blocks: [
      { type: 'p', text: 'A scanned PDF is a picture of a page. The letters on it are pixels, not characters, which is why you cannot select a word, copy a sentence or search with Ctrl+F — there is simply no text stored in the file. Two PDFs that look identical on screen can behave completely differently, and knowing which kind you are holding decides what you can do next.' },
      { type: 'h2', text: 'The three ten-second tests' },
      { type: 'list', items: [
        'Try to select a word. In a digital PDF, dragging across text highlights individual words and letters. In a scan, the whole page selects like one big picture.',
        'Search with Ctrl+F or Cmd+F for a distinctive word you can see. A real text layer finds it instantly; a picture-only page returns nothing.',
        'Zoom to 300–400 percent. Vector text stays crisp as it zooms, while a scan pixelates like a photograph. This is a useful hint, not proof — building a searchable OCR layer under a scan is exactly why the picture can still look sharp.',
      ] },
      { type: 'p', text: 'One test alone can lie. Searchable scans — an image with an invisible OCR text layer behind it — pass the selection and search tests while still being pictures at heart. The reliable read is the combination: no selectable words, no search results and visible pixelation together mean a scan.' },
      { type: 'h2', text: 'What a scan means for editing and copying' },
      { type: 'p', text: 'If a PDF is a scan, text tools around it fail for the same reason: there are no characters to read. Copying produces nothing, translation returns the file untouched or empty, and an editor cannot touch the letters. The fix in every case is the same — run OCR to add a real text layer.' },
      { type: 'h2', text: 'Make a scanned PDF searchable with OCR' },
      { type: 'steps', items: [
        'Open the OCR tool and drop in your scanned PDF.',
        'Wait while each page is recognised into a hidden text layer.',
        'Download the result — it looks identical, but the words are now real.', ],
      },
      { type: 'p', text: 'After OCR the same tests pass: selection works, Ctrl+F finds words, and copy, translation and editing behave like a digital document. The page image itself is unchanged.' },
      { type: 'callout', title: 'Some scans already have an OCR layer', text: 'Many scanners add a text layer at scan time. That file behaves like a normal document even though it started as a photo of a page — and an old, low-quality OCR engine can leave characters that copy out badly. If your copied text looks like noise, re-recognising the file cleans it up.' },
      { type: 'h2', text: 'When a PDF is mixed' },
      { type: 'p', text: 'Reports and applications often combine digital cover pages with scanned receipts, signed forms or appendices. The tests above give a per-page verdict, so a file that searches fine on page 1 and fails on page 5 is mixed — run OCR and only the image pages are affected, the digital text stays untouched.' },
    ],
    faqs: [
      { q: 'How do I know if a PDF is a scan or real text?', a: 'Try to select a single word and search with Ctrl+F. If you cannot highlight individual words and a word you can see is not found, the page is a picture. Two tests together give a reliable answer.' },
      { q: 'Can a scanned PDF pass the text test anyway?', a: 'Yes. Scans that already have an invisible OCR layer behave like digital documents — and if that layer is poor, copied text comes out garbled. Re-running OCR fixes the layer.' },
      { q: 'What can I do with a scanned PDF once I know?', a: 'Run OCR to add a text layer. The page looks the same but suddenly selection, search, copy, translation and editing all work.' },
      { q: 'Are some pages of my PDF scans and others not?', a: 'Mixed files are common — a digital report with scanned receipts tacked on. Test a few pages, including the attachments area, to map which pages are pictures.' },
      { q: 'Does OCR change how the scan looks?', a: 'No. OCR adds an invisible text layer underneath the page image, so the document still looks exactly like the original scan.' },
    ],
    related: ['how-to-make-a-scanned-pdf-searchable', 'how-to-tell-if-a-pdf-has-been-edited', 'how-to-extract-text-from-scanned-pdf-without-software', 'how-to-copy-text-from-a-scanned-pdf'],
  },
  {
    slug: 'how-to-scan-a-document-in-black-and-white',
    title: 'How to Scan a Document in Black and White',
    description: 'Scan a document in black and white with your phone: the B&W filter gives crisp black text on white paper, even with shadows. Free, in-browser, no sign-up.',
    keyword: 'scan a document in black and white',
    category: 'Converting',
    published: '2026-09-24',
    updated: '2026-10-04',
    tool: 'scan-pdf',
    experience: 'Most of what I scan is printed text: contracts, letters, forms. Black and white is my default for those, and the one time it bit me was a form with a red stamp that vanished into grey. Now I check for colour that carries meaning before I switch.',
    blocks: [
      { type: 'p', text: 'Scanning in black and white collapses the page to dark ink on white paper. The payoff is cleaner text, a smaller file, no grey cast or yellowed paper, and scans that look like they came off an office copier. On a printer you often have to dig through driver settings to find the colour mode. To scan a document in black and white with your phone, it is one tap on the review screen.' },
      { type: 'h2', text: 'How do I scan a document in black and white?' },
      { type: 'p', text: 'Open the Scan PDF tool on your phone and capture the page with the camera, or import a photo of it. On the review screen tap Filters and choose B&W. The page turns into black text on white paper, with shadows removed. Tap “Apply this filter to all” pages for a multi-page document, then Save PDF.' },
      { type: 'steps', items: [
        'Open Scan PDF and capture or import the page.',
        'Tap the thumbnail to open the review screen.',
        'Tap Filters, then B&W.',
        'Apply it to all pages if there are several.',
        'Tap Save PDF and download it.',
      ] },
      { type: 'h2', text: 'Why scan in black and white at all' },
      { type: 'list', items: [
        'Cleaner text. The B&W filter separates ink from paper sharply, which reads better on a phone screen and gives text recognition clearly separated characters.',
        'Smaller files. A page that is almost all white compresses far better than a colour photo of paper, so a long document is easier to email.',
        'Consistent pages. No yellow paper, blue-ish camera tint or grey corners; every page looks the same.',
        'Better printing. Black and white prints crisply on any office printer and does not waste colour toner on a beige background.',
      ] },
      { type: 'h2', text: 'B&W, Grayscale or Light text?' },
      { type: 'p', text: 'The scanner has six filters, and three of them are “not colour”. They do different jobs:' },
      { type: 'table', head: ['Filter', 'What it does', 'Use it for'], rows: [
        ['B&W', 'Crisp black text on white paper; adapts to shadows across the page instead of using one global threshold', 'Printed text, contracts, letters, forms'],
        ['Grayscale', 'Cleans up the lighting and whitens the paper, but keeps the shades of grey', 'Pencil sketches, documents with photos, signatures you want to look natural'],
        ['Light text', 'Pushes faint marks towards black while the paper stays white', 'Faded print, pale thermal receipts, light pencil'],
        ['Auto color', 'The default: evens out the lighting, keeps colour', 'Anything where colour carries meaning'],
      ] },
      { type: 'p', text: 'The filter tiles show a live preview of the current page in each style, so you can compare B&W and Grayscale side by side before choosing. If B&W makes thin strokes break up, raise the brightness slightly or switch to Grayscale; if the text is still too pale, open Adjust and increase the contrast.' },
      { type: 'callout', title: 'The filter is not baked in until you save', text: 'Filters are applied to a copy; the original photo is kept. You can switch a page from B&W back to Auto color, try Grayscale, or undo, as many times as you like before you tap Save PDF. Only the saved file is black and white.' },
      { type: 'h2', text: 'Black and white for a whole document' },
      { type: 'p', text: 'Scan all the pages first. In Document mode, each new page starts on the Auto color filter. Then pick B&W on one page, check that it looks right, and tap “Apply this filter to all” pages. If one page is different, for example a page with a colour chart in the middle of a text contract, switch just that page back to Auto color. Mixed filters in one PDF are fine.' },
      { type: 'h2', text: 'When to keep colour or grayscale instead' },
      { type: 'p', text: 'Anything where colour carries information should not be scanned in black and white: an ID or passport (verification checks look at the photo and security colours), a form with an official red or blue stamp, a highlighted price list, a signature that must visibly be in blue ink, or a chart with a coloured legend. The B&W filter turns all of that into black or white and the meaning disappears. Pencil drawings and very faded originals also do better in Grayscale or Light text, which keep faint detail that a hard black-and-white split would lose.' },
      { type: 'h2', text: 'Converting a PDF you already have to black and white' },
      { type: 'p', text: 'The scanner works on camera shots and images, not on existing PDF files. To turn a colour PDF scan into black and white: convert its pages to JPG images, import those images into the scanner, apply B&W to all pages, and save a new PDF. Tick Recognize text (OCR) when saving, because the old text layer does not carry over through images. For a PDF that was created digitally (not scanned), it is better to export it again from the original application in black and white or to print it in grayscale.' },
      { type: 'h2', text: 'Run this test before you commit' },
      { type: 'p', text: 'After applying B&W, pinch to zoom on the smallest print on the page (a footnote, a page number, a decimal point in an amount). If tiny characters have filled in or broken apart, the page needs Grayscale or a contrast tweak, not B&W. Big headings always look fine; it is the small print that tells you whether the filter is right for that page.' },
    ],
    faqs: [
      { q: 'How do I scan in black and white on my phone?', a: 'Capture the page with a browser-based scanner, open the review screen, tap Filters and choose B&W. Apply it to all pages if needed, then save the PDF.' },
      { q: 'Is a black-and-white scan smaller than a color one?', a: 'Usually, yes. A page of black ink on white paper compresses much better than a colour photo of paper. Choosing the Small file size when saving shrinks it further.' },
      { q: 'What is the difference between black and white and grayscale?', a: 'Black and white separates the page into ink and paper. Grayscale keeps the shades in between. Use B&W for printed text and Grayscale for pencil, photos or faded originals.' },
      { q: 'Does black and white help OCR accuracy?', a: 'Often, on printed text, because the characters are cleanly separated from the background. On very faint originals, Light text or Grayscale may read better, since a hard split can break thin strokes.' },
      { q: 'Should colored stamps or highlights be scanned black and white?', a: 'No. Anything where colour carries information, such as stamps, highlights or a blue-ink signature, should stay in Auto color or at least Grayscale.' },
    ],
    related: ['how-to-scan-a-document-without-a-scanner', 'how-to-scan-documents-to-pdf-with-your-phone', 'how-to-scan-a-receipt-to-pdf', 'how-to-darken-a-scanned-pdf'],
  },
  {
    slug: 'how-to-scan-both-sides-of-a-document-into-one-pdf',
    title: 'How to Scan Both Sides of a Document Into One PDF',
    description: 'Scan both sides of a document into one PDF with your phone: flip each sheet, let it auto-capture, fix the page order, and save one file. Free, no upload.',
    keyword: 'scan both sides of a document into one pdf',
    category: 'Converting',
    published: '2026-09-24',
    updated: '2026-10-04',
    tool: 'scan-pdf',
    experience: 'Double-sided forms are where most of my scanning mistakes used to happen: a back page missing, or every back stuck at the end of the file. Flipping each sheet in place and letting the scanner catch the change is the habit that fixed it.',
    blocks: [
      { type: 'p', text: 'An office printer with a duplex feeder scans both sides of a sheet in one pass. A phone camera sees one side at a time. You can still scan both sides of a document into one PDF without special hardware: capture the front, flip the sheet, capture the back, and keep the pages in front-back order. The result reads exactly like the paper original.' },
      { type: 'h2', text: 'How do I scan both sides of a document into one PDF?' },
      { type: 'p', text: 'Open the Scan PDF tool on your phone and tap Open camera. Capture the front of the first sheet, flip it over in the same spot, and the scanner captures the back. Repeat sheet by sheet so every back follows its front, then tap Save PDF to get one PDF with all the pages in order.' },
      { type: 'steps', items: [
        'Open Scan PDF and tap Open camera.',
        'Capture the front of the sheet.',
        'Flip it in place; the back is captured.',
        'Repeat for every sheet.',
        'Check the order, then Save PDF.',
      ] },
      { type: 'h2', text: 'The sheet-by-sheet method, step by step' },
      { type: 'steps', items: [
        'Open the Scan PDF tool in your phone’s browser, tap Open camera and leave the mode on Document.',
        'Lay the first sheet front side up on a dark surface. When the outline turns green, the front is captured automatically (or tap the shutter).',
        'Flip the sheet over without moving it far. The scanner sees that the page has changed and captures the back once it is steady.',
        'Put the next sheet down, front side up, and repeat. Each front is followed directly by its back, so the order is right by construction.',
        'If a back is blank, just do not flip that sheet; if it gets captured anyway, delete it on the review screen.',
        'Tap the thumbnail at the bottom left to review. Swipe through and confirm the pattern: front, back, front, back.',
        'Tap Save PDF, pick A4 or Letter if it will be printed, and tap Save as PDF.',
      ] },
      { type: 'callout', title: 'Why sheet by sheet beats two passes', text: 'With a phone there is no feeder to speed up, so scanning all the fronts first and all the backs later saves almost no time. It just creates a sorting job at the end. Flipping each sheet in place keeps every back next to its front, and that is the only rule that really matters in a two-sided scan.' },
      { type: 'h2', text: 'Fixing the order if pages end up out of place' },
      { type: 'p', text: 'Maybe you scanned all the fronts and then all the backs, or a page captured twice. Open Reorder on the review screen. Every page appears as a numbered thumbnail with a drag handle in the corner: drag the page by the handle to where it belongs. For a single page that needs to travel far, tap it and use First, Earlier, Later or Last. Delete duplicates with Delete, and if you move something by mistake, the undo button at the top puts it back.' },
      { type: 'table', head: ['What happened', 'Fix'], rows: [
        ['All fronts first, then all backs', 'In Reorder, drag each back to sit right after its front'],
        ['Backs scanned in reverse order', 'Work from the last back: move it after the first front, and so on'],
        ['A page was captured twice', 'Delete the duplicate'],
        ['One side is blurry', 'Retake: the camera reopens and replaces only that page'],
        ['A back page is upside down', 'Rotate it twice (180°)'],
      ] },
      { type: 'h2', text: 'Already have a PDF of the fronts and a PDF of the backs?' },
      { type: 'p', text: 'If a scanner without duplex already gave you two files, one with the odd pages and one with the even pages, you do not need to rescan. Merge the two PDFs and then put the pages in order with an organise or reorder tool, or extract and interleave them. The scanner above is for paper still in your hands.' },
      { type: 'h2', text: 'Special case: an ID card or a small card' },
      { type: 'p', text: 'For an ID card, driving licence or insurance card, the usual requirement is both sides on one page, not two pages. Use ID card mode instead: scan the front, turn the card over and scan the back, and both sides are placed on a single A4 page, like a photocopy. If the form wants two pages instead, use Document mode as described above.' },
      { type: 'h2', text: 'Make the two-sided PDF look consistent' },
      { type: 'list', items: [
        'Pick a filter on one page and tap “Apply this filter to all” pages, so fronts and backs match',
        'Use B&W for plain printed forms, Auto color when there are stamps, signatures in blue ink or coloured logos',
        'If the back shows through thin paper, B&W often removes the faint show-through; raise the contrast slightly in Adjust if needed',
        'Choose A4 or Letter as the page size so every page has the same dimensions when printed double-sided',
      ] },
      { type: 'callout', title: 'Run this check before sending', text: 'Count the sheets in your hand, double it, and compare with the page count shown when the PDF is ready (minus any blank backs you skipped). It takes five seconds and catches the missing back page that otherwise only surfaces when someone asks for it.' },
      { type: 'p', text: 'Everything runs in the browser on your phone: the camera, the reordering and the PDF. Nothing is uploaded, and the scanning session survives a reload, so a long two-sided stack can be done in one sitting without losing work.' },
    ],
    faqs: [
      { q: 'Will my phone scan both sides automatically?', a: 'No. A camera sees one side at a time. Flip each sheet in place after capturing the front; the scanner detects the change and captures the back, so the pages land in front-back order.' },
      { q: 'How do I keep the front and back pages in the right order?', a: 'Scan sheet by sheet: front, flip, back. If the order still goes wrong, open Reorder on the review screen and drag pages by their handles before saving.' },
      { q: 'I scanned all the fronts first, then all the backs. How do I fix it?', a: 'Open Reorder and drag each back to sit directly after its front, or tap a page and use the Earlier and Later buttons. Check page numbers or headers afterwards.' },
      { q: 'How do I scan a double-sided document on a printer without duplex?', a: 'Scan the fronts as one file and the backs as another, then merge the two PDFs and reorder the pages so they alternate. Or scan the sheets with your phone, flipping each one in place.' },
      { q: 'Can I scan an ID card front and back into one PDF?', a: 'Yes. ID card mode puts both sides on one A4 page. If you need them as two pages instead, scan the front and back in Document mode.' },
    ],
    related: ['how-to-scan-multiple-pages-into-one-pdf', 'how-to-combine-scanned-documents-into-one-pdf', 'how-to-scan-an-id-card-to-pdf', 'how-to-reorder-pages-in-a-pdf'],
  },
  {
    slug: 'how-to-translate-a-scanned-pdf',
    title: 'How to Translate a Scanned PDF',
    description: 'Translate a scanned PDF to any language: run OCR first, then translate. Free, in-browser, no upload, no sign-up.',
    keyword: 'translate a scanned pdf',
    category: 'Converting',
    published: '2026-09-24',
    tool: 'ocr-pdf',
    blocks: [
      { type: 'p', text: 'Drag a scanned PDF into most translators and nothing happens: the file comes back untouched or with zero text. That is not a bug — a scan is a picture of a page, and translators can only read characters. A scanned page has no characters until OCR turns the image into text. So translating a scan is always two honest steps: recognise the text, then translate it.' },
      { type: 'h2', text: 'Why translators reject scans' },
      { type: 'p', text: 'A translation engine works by extracting the text layer, sending those words to a model, then returning the translation. When a PDF is a scan, the extraction step finds nothing, because the letters are pixels, not text. Some services quietly return the original; others error out. The fix is identical either way — give the file a real text layer first.' },
      { type: 'h2', text: 'Translate a scan in two steps' },
      { type: 'steps', items: [
        'Run the OCR tool on your scanned PDF to add a text layer. Choose the document language if the tool offers it — it sharpens recognition for non-Latin scripts.',
        'Open the translated PDF in the translate tool with the same approach as a normal document, select the source and target languages, and download the result.', ],
      },
      { type: 'p', text: 'The OCR step is what makes everything after it possible. The recognised PDF selects, copies and searches like a digital document, which is exactly the input the translation step needs.' },
      { type: 'callout', title: 'Verify before you translate', text: 'Translated text inherits every OCR mistake: a misrecognised word becomes a confidently mistranslated word. Copy a paragraph from the recognised file and read it once before translating — catching problems at the cheapest point is what separates a usable translation from a misleading one.' },
      { type: 'h2', text: 'Tips for better recognition on difficult scans' },
      { type: 'list', items: [
        'Tell the OCR step the source language when known — the engine targets the right character set.',
        'A clean, flat, well-lit capture reads far better than a skewed or shadowed photo.',
        'After OCR, spot-check names, numbers and currency before translating them into a final document.',
      ] },
      { type: 'h2', text: 'What the translation step actually sends' },
      { type: 'p', text: 'Unlike every other tool here, the translate tool sends the extracted text to a third-party translation service — that is what produces the translation. The extracted words are the only thing that leaves your device, and this warning is shown in the tool itself. For confidential scans, weight that trade-off before you start.' },
    ],
    faqs: [
      { q: 'Why will Google Translate or my translator not read my scanned PDF?', a: 'Translators read a PDF text layer, and a scan has none — the letters are pixels. Running OCR first creates the layer and the same translator then works normally.' },
      { q: 'Do I have to run OCR before translating a scan?', a: 'Yes. It is the single step that turns a picture of text into text a translation engine can read, and it lets you verify recognition before words are carried into another language.' },
      { q: 'Should I check the OCR output before translating?', a: 'Strongly. A word OCR misreads becomes a confidently mistranslated word. Read a sample first; fixing recognition errors costs nothing compared with fixing them after translation.' },
      { q: 'Can I translate a scan with handwriting or unusual fonts?', a: 'Recognition quality varies with legibility. Clean printed text translates well; heavy or stylised handwriting is harder for any OCR engine. Set the source language for the best result.' },
      { q: 'Does translating a scanned PDF send my file somewhere?', a: 'The OCR step stays fully in your browser. The translation step sends only the extracted text to a translation service to produce the result — the tool warns about this before you run it.' },
    ],
    related: ['how-to-translate-a-pdf', 'how-to-make-a-scanned-pdf-searchable', 'how-to-copy-text-from-a-scanned-pdf', 'how-to-extract-text-from-scanned-pdf-without-software'],
  },
];