import type { BlogPost } from '../types';

export const newPosts17: BlogPost[] = [
  {
    slug: 'how-to-unlock-a-pdf-for-printing',
    title: 'How to Unlock a PDF for Printing (Free, No Upload)',
    description: 'Unlock a PDF that blocks printing for free in your browser — release the restriction on owner-locked files in seconds and know when a real password stands in the way.',
    keyword: 'how to unlock a pdf for printing',
    category: 'Security & Privacy',
    published: '2026-09-24',
    tool: 'unlock-pdf',
    experience: 'A supplier sent me a spec locked against printing, and the client needed a paper copy on the same afternoon. The file opened normally — it just refused to print. That is the situation this article exists for: the file is not asking for a password, it is carrying a permission flag that blocks printing, and rebuilding the document drops the flag.',
    blocks: [
      { type: 'p', text: 'When a PDF refuses to print but opens fine, it is not locked by a password you have to guess. Printing is restricted by a permission inside the file that the reader should be able to release — and that is what unlocking is. How to unlock a PDF for printing comes down to telling an owner-restricted file apart from one truly locked behind a password, then rebuilding the document without the restriction. Both cases are covered below, honestly, including the one where you genuinely cannot unlock it.' },
      { type: 'h2', text: 'What "unlocked for printing" actually means' },
      { type: 'p', text: 'A PDF that opens but blocks printing is protected by an owner password — a flag set by the document\'s creator to stop printing, copying or editing. You are not expected to know that password; the file simply carries the instruction "do not print". Unlocking rebuilds the document so the instruction is gone, and the result prints like any other PDF. The document does not need the password, because the file opens without it.' },
      { type: 'list', items: [
        'The file opens normally — no password prompt — but printing shows "restricted"',
        'The restriction usually covers copy and edit too, not just print',
        'Unlocking rebuilds the file fresh, so the print block simply disappears',
        'If the PDF demands a password before it will open at all, that is a different case — keep reading',
      ] },
      { type: 'h2', text: 'The two kinds of password-protected PDF' },
      { type: 'p', text: 'Both are called "password protected", which is why this gets confusing. The treatment differs completely.' },
      { type: 'table', head: ['Type', 'What you see', 'Can you unlock it?'], rows: [
        ['Owner-restricted (permissions)', 'Opens fine; printing/copying shows "restricted" or greyed out', 'Yes — rebuild the file without the flag, no password needed'],
        ['Password to open (encryption)', 'A password prompt before the document displays', 'Only with the correct password'],
        ['Certified or signed', 'A blue ribbon or certificate badge in the reader', 'No — stripping the seal is tampering'],
      ] },
      { type: 'h2', text: 'Unlock a print-restricted PDF in three steps' },
      { type: 'steps', items: [
        'Open the Unlock PDF tool and add your file.',
        'If it opens without asking for a password, the tool rebuilds it with the print (and copy, edit) restrictions removed.',
        'Download the unlocked PDF and print — the block is gone.',
      ] },
      { type: 'callout', title: 'An unlocked copy is a freshly rebuilt document', text: 'The file is re-rendered page by page at high quality, and a hidden text layer keeps it searchable. Interactive form fields and hyperlinks are flattened in rather than carried over as live objects, so save a copy if you still need the working form.' },
      { type: 'h2', text: 'When you will actually need the password' },
      { type: 'p', text: 'If the file refuses to open until you type a password, there is no honest workaround — the document is encrypted, and unlocking requires that password from whoever created it. The same is true for a certified document sealed by a digital signature: rebuilding it strips another party\'s cryptographic seal, which is tampering, not cleanup. Unlock documents you own, or that you may legitimately modify, and ask for an unsigned or unlocked copy of anything else.' },
      { type: 'h2', text: 'Why the file was print-locked in the first place' },
      { type: 'p', text: 'Restrictions are usually set deliberately — a report meant to be read online, a rate sheet a vendor does not want redistributed — so before removing one, check you are entitled to. Unlocking your own documents, or ones you have permission to change, is routine and legal. Bypassing protection on a file whose owner intends it to stay restricted crosses the line from convenience into circumvention, and it is worth resolving that with the sender first.' },
    ],
    faqs: [
      { q: 'Why does my PDF say printing has been restricted?', a: 'The file carries a permissions flag set by its creator that blocks printing, copying and editing. It is an owner-password restriction, so the document opens fine but refuses to print — and it can be removed by rebuilding the file.' },
      { q: 'Can I unlock a PDF for printing without a password?', a: 'When the file opens without asking for a password, yes. The block is a permission flag rather than real encryption, so rebuilding the document removes it. If the PDF demands a password to open, only that password unlocks it.' },
      { q: 'Will unlocking a PDF lower its quality?', a: 'No. The pages are re-rendered at high resolution and a text layer keeps them searchable. Interactive form fields and links are flattened into the page rather than lost.' },
      { q: 'Does unlocking a print-restricted PDF also remove other restrictions?', a: 'Yes. Copying and editing are usually blocked by the same owner-password flag, so the rebuilt file is free of all of them, not just the print block.' },
      { q: 'Is it legal to unlock a PDF for printing?', a: 'For documents you own or are allowed to modify, generally yes. Circumventing protection on a file the owner intends to stay restricted may be a breach — get permission first.' },
    ],
    related: ['how-to-remove-a-password-from-a-pdf', 'how-to-password-protect-a-pdf', 'how-to-protect-a-pdf-from-copying', 'how-to-sign-a-pdf-without-printing-it'],
  },

  {
    slug: 'how-to-extract-text-from-a-pdf',
    title: 'How to Extract Text From a PDF (Free)',
    description: 'Extract text from a PDF for free — pull the readable text out of an electronic PDF into plain text or Markdown, and know what to do when your PDF is really an image.',
    keyword: 'how to extract text from a pdf',
    category: 'Converting',
    published: '2026-09-24',
    tool: 'pdf-to-markdown',
    experience: 'I pull reference numbers, pricing lines and contract clauses out of supplier PDFs several times a week. The reliable shortcut is a conversion that reads the text layer and hands me clean, re-usable text — and the moment that returns nothing is usually the moment I discover the file is a scan with no text layer at all.',
    blocks: [
      { type: 'p', text: 'Extracting text from a PDF means pulling the words out of the file so you can copy, quote, reuse or search them outside the document. How to extract text from a PDF is, for an electronic PDF, a quick conversion rather than retyping — and for a scan it is a different problem entirely. This article covers both, and tells you honestly when the plain route will not work.' },
      { type: 'h2', text: 'How to extract text from a PDF' },
      { type: 'p', text: 'For a PDF with a real text layer — one created from Word, a design tool, or a printed-to-PDF save — extraction is a single conversion. The tool reads the document and returns its words as re-usable text, in plain text or Markdown, with headings and lists intact. It runs entirely in your browser: no upload, no account, nothing leaves your device.' },
      { type: 'steps', items: [
        'Open the PDF to Markdown tool and add your PDF.',
        'Convert — the text layer is read and returned as Markdown (or plain text).',
        'Copy the output into a document, notes app, or AI tool and edit as needed.',
      ] },
      { type: 'callout', title: 'If you get nothing back, the PDF is a scan', text: 'A scan or photographed document has no text layer — every "text" is pixels in an image. Convert it, get an empty result, and you are holding a scan. That is not a dead end, but it needs OCR first (linked below), not more extraction attempts.' },
      { type: 'h2', text: 'Why the file has no text layer at all' },
      { type: 'p', text: 'The fastest way to see what you are dealing with: select a line of text with your cursor and press Ctrl+C. If a copy results, the file has a text layer and extracts cleanly. If the selection returns nothing, the page is an image — scanned, photographed or flattened on export. Copy-testing a document once tells you which pipeline to use, and it saves a failed conversion.' },
      { type: 'table', head: ['In the PDF', 'What extracts'], rows: [
        ['Paragraphs', 'Clean, run-together-per-line text with paragraph breaks'],
        ['Headings', 'Heading levels detected from size and weight'],
        ['Bulleted and numbered lists', 'Reconstructed as real lists'],
        ['Simple tables', 'Structured rows and columns when the grid is regular'],
        ['Text baked into a scan', 'Nothing — no text layer exists until OCR runs'],
      ] },
      { type: 'h2', text: 'Plain text or Markdown — which should you extract?' },
      { type: 'p', text: 'Both start from the same text layer. Plain text is right when you are pasting into an email, a form or a quick note. Markdown is right when the text will live somewhere structured — documentation, a wiki, a static site — or when you are feeding a document to an AI tool, because headings and lists give the model structure to navigate by. If you only need a few lines, copying from the PDF directly is fastest and needs no conversion at all.' },
      { type: 'h2', text: 'When your PDF is a scan' },
      { type: 'p', text: 'A scanned PDF holds no extractable text until it is run through OCR, which recognizes the letter shapes in the image and writes a searchable text layer into the file. That changes the document itself, and it is the honest route for scans rather than an "extract from image" hack. For one-off copying from a scan, the simplest path is the OCR tool that turns the page into readable, selectable text — the same pipeline the scanned-document posts below explain end to end.' },
      { type: 'h2', text: 'Keep the original file safe' },
      { type: 'p', text: 'Extraction is read-only on its output — the source PDF is never altered. Still, export the result into your system and keep the original where it was. Re-extracting is free, so there is no reason to overwrite anything. If the document is confidential, the same privacy applies throughout: the conversion runs locally, and what you do with the text afterwards — including pasting it into a hosted service — is a separate decision.' },
    ],
    faqs: [
      { q: 'Why can\'t I copy text from my PDF?', a: 'The PDF is probably a scan or a flattened image with no text layer. Select a line and press Ctrl+C; if nothing comes back, run OCR to add a searchable, copyable text layer first.' },
      { q: 'Can I extract text from a scanned PDF?', a: 'Not directly — the words are pixels in an image. OCR rebuilds a text layer so extraction works, which is the correct route for scans.' },
      { q: 'Does extracting text keep the formatting?', a: 'Text yes, styling no. Headings and lists are reconstructed as structure, but precise fonts, spacing and page layout do not survive plain-text output — that is expected for this task.' },
      { q: 'Will tables and columns come out right?', a: 'Simple tables extract as structured rows and columns. Two-column layouts flatten into one column, sometimes with lines interleaved, and merged-cell grids are the hardest case.' },
      { q: 'Is extracting text from a PDF free?', a: 'Yes, the tool runs in your browser with no upload, no account and no charge — your document never leaves your device.' },
    ],
    related: ['how-to-convert-pdf-to-markdown', 'how-to-copy-text-from-a-scanned-pdf', 'how-to-make-a-scanned-pdf-searchable', 'how-to-export-pdf-tables-to-csv'],
  },

  {
    slug: 'how-to-rotate-a-single-page-in-a-pdf',
    title: 'How to Rotate a Single Page in a PDF',
    description: 'Rotate one sideways page in a multi-page PDF without touching the rest — fix only the pages that need it, save the rotation so it sticks, and keep the file organized.',
    keyword: 'how to rotate a single page in a pdf',
    category: 'Merging & Organizing',
    published: '2026-09-24',
    tool: 'rotate-pdf',
    experience: 'Every fused scan I receive has at least one page sideways — usually the reverse of a receipt or a landscape spreadsheet that the feeder captured the wrong way. Rotating the whole file to fix it breaks the forty pages that are already correct, so the per-page route is the only sane one, and it is a two-minute job once you know how to pick the bad pages.',
    blocks: [
      { type: 'p', text: 'One sideways page in a forty-page PDF is a common, annoying problem — and the fix is smaller than most people think. How to rotate a single page in a PDF means choosing just the pages that need correcting and leaving the rest untouched, then saving the rotation so it shows correctly everywhere. Here is the exact way to do it without flattening, re-exporting, or rotating the whole document by accident.' },
      { type: 'h2', text: 'How to rotate one page in a PDF' },
      { type: 'p', text: 'Open the document in a rotation tool, switch from "all pages" to the specific-pages mode, type the pages that are wrong, and apply the rotation. Only those pages change — the rotation is stored inside the file, so it survives closing, sharing and opening in any reader.' },
      { type: 'steps', items: [
        'Open the Rotate PDF tool and add your file.',
        'Choose Specific pages instead of All pages.',
        'Enter the offending page numbers as a list or range, e.g. 4, 7, or 12-14.',
        'Pick the direction — clockwise or counterclockwise 90 degrees, or 180 — and apply.',
        'Download and open the result to confirm only the target pages moved.',
      ] },
      { type: 'callout', title: 'Rotating everything to fix two pages is a classic mistake', text: 'A "rotate all" pass fixes the two sideways pages and breaks the rest. Always work from the specific-pages setting, and double-check by page number before you apply — a wrong range is a faster error to make than people expect.' },
      { type: 'h2', text: 'Which pages usually need rotating?' },
      { type: 'p', text: 'Misorientation is rarely random. Knowing where it comes from means you can predict it instead of checking every page.' },
      { type: 'table', head: ['Where it comes from', 'What to expect'], rows: [
        ['A duplex scanner fed from the wrong tray', 'Alternating pages upside down — often every second page'],
        ['Fusing scanned documents in the wrong order', 'Individual scans sideways, usually the back of a receipt or a photo'],
        ['A landscape spreadsheet exported to PDF', 'One stretched page sideways among portrait pages'],
        ['A photographed page with wrong camera orientation', 'One or two pages at 90 or 270 degrees'],
      ] },
      { type: 'h2', text: 'Will the rotation stay once I close the file?' },
      { type: 'p', text: 'Yes, when the rotation is applied to the document itself rather than just the view. The trap is the rotate button inside a reader, which spins what you see on screen and forgets it the moment you close the tab — that solves nothing for anyone you send the file to. Applying rotation in a tool that saves it into the document is what makes it permanent; the deeper view-versus-saved distinction is covered in the related post below.' },
      { type: 'h2', text: 'Does rotating a page reduce quality or size?' },
      { type: 'p', text: 'No. Rotation is a number stored on the page — 90, 180 or 270 degrees — and nothing is re-rendered. Quality is unchanged and file size barely moves. It is the one page-fix that is entirely lossless, which is a reason to prefer it over re-exporting a document just to correct an orientation.' },
      { type: 'h2', text: 'Fix the page, then finish the document' },
      { type: 'p', text: 'Rotate the stragglers first, then run any remaining cleanup so every step works on pages that are already the right way up: remove blank backs after rotated scans, order the pages once orientation is correct, and only compress at the very end. Doing orientation first means reordering and compression never fight a sideways page again.' },
    ],
    faqs: [
      { q: 'Can I rotate just one page in a PDF?', a: 'Yes. Use a rotation tool in its specific-pages mode, type the page number, and apply the rotation to that page only — everything else in the document is left untouched.' },
      { q: 'How do I rotate a page 180 degrees?', a: 'Upside-down pages take a 180-degree rotation, applied once if the tool offers it, or two passes of 90 degrees. Fed-stack errors usually produce this pattern.' },
      { q: 'Does rotating a single page save permanently?', a: 'Yes, when the rotation is applied to the document and you download the result. Rotation applied to the on-screen view in a reader is discarded when you close the file.' },
      { q: 'Does rotating one page change the file size or quality?', a: 'Essentially no. The rotation is stored as a value on the page, so quality is identical and size changes by a few bytes.' },
      { q: 'Why do alternating pages come out sideways?', a: 'Duplex scanners fed the wrong way rotate every second page. Rotate the odd or even page range rather than fixing each page individually.' },
    ],
    related: ['how-to-rotate-a-pdf-and-save-it', 'how-to-reorder-pages-in-a-pdf', 'how-to-insert-a-page-into-an-existing-pdf', 'how-to-scan-documents-to-pdf-with-your-phone'],
  },

  {
    slug: 'how-to-change-the-font-of-a-pdf',
    title: 'How to Change the Font of a PDF (Free)',
    description: 'Change the font of a PDF for free in your browser — pick a new typeface, size, weight or colour for a text block without moving the layout, and no upload required.',
    keyword: 'how to change the font of a pdf',
    category: 'Editing & Signing',
    published: '2026-09-24',
    tool: 'edit-pdf',
    experience: 'When a template I use was exported with headings in a dated font, I re-purposed it by selecting each heading and switching families rather than rebuilding the whole document in a word processor. The editor re-measures the text as you go, so the layout holds its place — which is exactly what I needed to keep the rest of the page untouched.',
    blocks: [
      { type: 'p', text: 'A PDF lets you change the font of its text afterwards, and it does not require the original file. How to change the font of a PDF is a matter of selecting the text that is wrong and applying a new typeface, size, weight or colour, while the surrounding layout stays in place. There are real limits — scanned pages have no text to re-embed, and the available families are the ones the tool carries — and both are explained here honestly.' },
      { type: 'h2', text: 'How to change the font of a PDF' },
      { type: 'p', text: 'Open the document in the Edit PDF tool, click a line of text so it registers as a block, and pick a new font from the family dropdown in the toolbar. The change applies to that block immediately, the text is measured again so the block resizes cleanly, and you save the finished file. Everything runs in the browser — no upload, no account.' },
      { type: 'steps', items: [
        'Open the Edit PDF tool and add your PDF.',
        'Click the text whose font you want to change — a block toolbar appears.',
        'Choose a font family from the dropdown; the text re-renders at once.',
        'Adjust size, bold or italic, and colour from the same toolbar.',
        'Save and download the updated PDF.',
      ] },
      { type: 'callout', title: 'You pick from the families the tool ships', text: 'The dropdown offers a set of standard families rather than every font ever created. If you need a specific commercial typeface, apply it in the source document and re-export — the editor swaps between its own supported families, honestly and predictably.' },
      { type: 'h2', text: 'What you can change, and how' },
      { type: 'table', head: ['Setting', 'What it does'], rows: [
        ['Font family', 'Swaps the typeface of the selected block'],
        ['Size', 'Scales the text; the block re-measures so it fits'],
        ['Bold / italic', 'Applies the weight or style variant'],
        ['Colour', 'Re-colours the text, including a custom picker'],
        ['Alignment', 'Left, centre or right within the block'],
      ] },
      { type: 'h2', text: 'When the font will not change — scanned pages' },
      { type: 'p', text: 'A scanned or photographed PDF has no text at all, only pixels. Clicking the page does nothing because there is nothing to select, and no font exists to change. The honest fix is to rebuild the page from a source file that has text, or run OCR so the scanned page becomes searchable — but OCR does not turn the image into editable font-changing text either. If the typeface matters, correct it where the document was made and export again.' },
      { type: 'h2', text: 'Does changing the font break the layout?' },
      { type: 'p', text: 'A different font has different widths, so each affected line is re-measured on the spot. Text blocks size themselves to the new characters, which keeps the page in order — but check paragraphs with several lines, since a wider font can re-wrap lines that were tight against an image or a margin. Review once before you download, and change the font of a block before repositioning it, not after.' },
      { type: 'h2', text: 'Why the font still looks wrong in some readers' },
      { type: 'p', text: 'A PDF can reference a font that its reader does not have, and the reader then substitutes its own default — which is why text sometimes appears in a different face than it was saved with. Changing the font makes the document self-describing for the family you picked, but a device short on fonts can still substitute something close. That behaviour on the reader\'s side is separate from the change you made, and expectations around embedding are worth knowing before you ship a file with a tight internal look.' },
    ],
    faqs: [
      { q: 'Can I change the font in a scanned PDF?', a: 'No — a scan has no text, only pixels, so there is no font to change. Correct the typeface in the source file and export the PDF again.' },
      { q: 'Does changing the font move the rest of the page?', a: 'No. Only the selected block is rewritten; the text is re-measured in place and the surrounding layout stays put. Lines flowing tightly against an image can re-wrap, so review once after changing.' },
      { q: 'What fonts can I use?', a: 'The families the editor offers in its dropdown. For a specific commercial typeface you must change it in the source document and re-export.' },
      { q: 'Will the new font stay if I send the PDF?', a: 'Yes, the chosen family is written into the file. Some device readers substitute a default when a font is missing, so verify on the receiving end for a client-facing document.' },
      { q: 'Does changing the font make the text searchable?', a: 'It keeps the text layer intact because the text itself is unchanged — only the typeface is swapped. A scanned page with no text layer still needs OCR.' },
    ],
    related: ['how-to-edit-pdf-text-without-acrobat', 'how-to-fix-fonts-not-displaying-in-a-pdf', 'how-to-add-text-to-a-pdf', 'how-to-make-a-pdf-accessible'],
  },

  {
    slug: 'how-to-highlight-text-in-a-pdf',
    title: 'How to Highlight Text in a PDF (Free)',
    description: 'Highlight text in a PDF for free in your browser — mark important lines in several colours, change or clear the highlight, and keep it when you print or send the file.',
    keyword: 'how to highlight text in a pdf',
    category: 'Editing & Signing',
    published: '2026-09-24',
    tool: 'edit-pdf',
    experience: 'I mark clauses in contracts before meetings, and colour-coding the way I review them has made the difference between skimming and actually tracking what changed between drafts. The task itself is small: click the line, set the marker colour, move on — and knowing it prints when I flatten matters more than most highlighter tutorials admit.',
    blocks: [
      { type: 'p', text: 'Highlighting text in a PDF works like a marker on paper: you colour over the words that matter so they stand out on a skim. How to highlight text in a PDF is, for an electronic document, a matter of selecting a text block and applying a semi-transparent marker colour — and knowing that a highlight is an overlay on the page, which decides whether it prints. Both the how and the caveats are covered here.' },
      { type: 'h2', text: 'How to highlight text in a PDF' },
      { type: 'p', text: 'Open the Edit PDF tool, click the line of text you want to mark so it registers as a block, and tap a highlight colour from the toolbar. The marker appears behind the text instantly, you can change or clear it at any time, and the finished file saves with the highlights baked into the page.' },
      { type: 'steps', items: [
        'Open the Edit PDF tool and add your PDF.',
        'Click the text to highlight — a block toolbar appears.',
        'Choose a highlight colour from the swatches.',
        'Repeat for every section you want to mark; use the minus button to remove a highlight.',
        'Save and download the highlighted PDF.',
      ] },
      { type: 'callout', title: 'A highlight is written into the file, not just the screen', text: 'The marker is applied to the document itself, so it stays visible in other readers and in the downloaded file. That is different from the on-screen-only marking some viewers offer, which vanishes the moment you close the tab.' },
      { type: 'h2', text: 'Build a colour system for real reviews' },
      { type: 'list', items: [
        'Yellow for "check this" and points that need a decision',
        'Green for approved or confirmed content',
        'Red or pink for action items and things that must change',
        'Blue for definitions, terms and references you will return to',
        'One colour per issue type, and a short legend if someone else reviews the file after you',
      ] },
      { type: 'h2', text: 'Does a highlight print and survive when I send the PDF?' },
      { type: 'p', text: 'Highlights written into the page render in other readers and are part of the downloaded file — but whether they appear on a printout depends on the reader\'s settings, since some printers skip page overlays by default. When a highlighted copy must come out exactly as seen, flatten it before printing or sending, and others can no longer move or delete the marks either. The full behaviour of overlays is the annotation question, covered in the related post.' },
      { type: 'h2', text: 'When you cannot highlight — scanned pages' },
      { type: 'p', text: 'A scanned or photographed PDF has no text objects, only pixels, so there is nothing to attach a marker to. The honest route is OCR, which creates a text layer and makes the page searchable and copyable — but OCR does not erect highlightable text-block objects either. If a scan genuinely needs marking, the practical answers are printing and hand-marking, or editing the original document and re-exporting.' },
      { type: 'h2', text: 'Highlight while you read, not after' },
      { type: 'p', text: 'The highest-value use of a highlighter is during the reading itself: mark a clause when it matters, not when you page back. Work in short passes — highlight and move on — then use a clear pass before sending so an accidental mark does not travel with the document. A highlight left where it does not belong reads as carelessness on a document that is going to a client or an authority.' },
    ],
    faqs: [
      { q: 'Does a PDF highlight show when I send the file?', a: 'Yes — highlights written into the document render in other readers and stay in the downloaded file. Whether they also print depends on the reader\'s print settings.' },
      { q: 'Can I change the colour of a highlight afterwards?', a: 'Yes. Select the highlighted block and pick a new colour from the swatches; the marker re-renders immediately. A minus button clears it entirely.' },
      { q: 'Can I highlight text in a scanned PDF?', a: 'No — a scan has pixels but no text objects, so there is nothing to attach a marker to. Edit the original document instead of trying to mark the scan.' },
      { q: 'Will my highlights be visible to the recipient?', a: 'In most readers, yes, and they are baked into the file. Flatten the document if it must print exactly as marked.' },
      { q: 'How do I remove a highlight from a PDF?', a: 'Click the highlighted block and use the clear-highlight button. Removing marks you no longer want is the same two clicks as adding them.' },
    ],
    related: ['how-to-annotate-a-pdf', 'how-to-edit-pdf-text-without-acrobat', 'how-to-print-a-pdf-correctly', 'how-to-make-a-scanned-pdf-searchable'],
  },
];