import type { BlogPost } from '../types';

export const newPosts15: BlogPost[] = [
  {
    slug: 'how-to-scan-a-document-without-a-scanner',
    title: 'How to Scan a Document Without a Scanner (Free)',
    description: 'Scan a document without a scanner for free using just your phone camera and a browser — auto edge detection, straightening, and a clean PDF that never leaves your device.',
    keyword: 'how to scan a document without a scanner',
    category: 'Converting',
    published: '2026-09-19',
    tool: 'scan-pdf',
    experience: 'I sign and send paper documents often enough that I stopped owning a scanner years ago. My phone camera plus an in-browser document scanner that auto-detects the page edges and straightens the shot is the whole answer — no device, no app, no account.',
    blocks: [
      { type: 'p', text: 'You do not need a scanner to scan a document. The camera in your pocket is a scanner already — what a document scanner actually adds is edge detection, perspective correction, and a clean image filter. All of that can run free in your browser today, so a paper page turns into a proper PDF with no hardware at all.' },
      { type: 'p', text: 'Here is how to scan a document without a scanner, in about a minute.' },
      { type: 'h2', text: 'Why your phone camera is already a scanner' },
      { type: 'p', text: 'A flatbed scanner captures a page at a fixed distance and angle, which is why the output looks flat and evenly lit. Holding a phone over a page introduces angle, shadow, and crop problems. A good in-browser scanner fixes those automatically: it outlines the page edges, corrects the perspective so the image is squared up, and applies a filter that removes shadows and background tint.' },
      { type: 'steps', items: [
        'Open the Scan PDF tool in your phone’s browser.',
        'Tap Open camera and allow camera access.',
        'Hold the phone above the page — the detector outlines the edges and captures automatically, or tap the shutter.',
        'On the review screen, rotate or apply a filter (Photo, Magic, B&W, or Gray), then tap Save.',
        'Walk through the remaining pages, then tap Done.',
        'Download the finished multi-page PDF to your device.',
      ] },
      { type: 'callout', title: 'Nothing is uploaded', text: 'The camera feed and pages are processed inside the browser on your device. Your document never crosses the network, so sensitive pages — contracts, ID, bank statements — stay private.' },
      { type: 'h2', text: 'Scanning from a desktop instead' },
      { type: 'p', text: 'If you are at a desktop or laptop, take the pictures with whatever camera is handy (including the one built into the laptop) and pull them into the same tool. Choose images from your device and they become pages of the finished PDF — still processed locally, still free, still no install.' },
      { type: 'h2', text: 'Making the scan look like a flat document' },
      { type: 'list', items: [
        'Place the page on a desk instead of holding it — steadier frames detect faster and straighter',
        'Fill the frame with the page, keeping a small margin around all four edges',
        'Shoot in even light; a page half in shadow will detect slowly and come out patchy',
        'After capture, use the Magic or B&W filter to flatten shadows and boost contrast',
        'Rotate before saving when the detector gets the orientation wrong',
      ] },
      { type: 'h2', text: 'When to scan anyway, versus snapping a photo' },
      { type: 'table', head: ['Kind of document', 'Best approach', 'Why'], rows: [
        ['Single receipt or note', 'Scan tool', 'Copies and flattens in one step'],
        ['Multi-page contract', 'Scan tool, multiple pages', 'One PDF, pages kept in order'],
        ['Handwritten notes', 'Careful photo', 'You likely want the original look preserved'],
        ['Very old, fragile paper', 'Gentle photo' , 'Avoids pressing it against glass'],
      ] },
      { type: 'h2', text: 'After the scan' },
      { type: 'p', text: 'The output is a standard PDF ready to email, upload, or store. If a photo-heavy page comes out large, run the PDF through a compressor before sending; if the text stays faint after a poor shoot, rescan from a flatter angle rather than trying to fix darkness in an editor.' },
    ],
    faqs: [
      { q: 'Can I scan a document without a scanner?', a: 'Yes. Photograph the page with a phone camera and run it through a browser-based scanner that detects the edges, straightens the perspective, and cleans the image up. The result is a proper PDF, processed locally on your device.' },
      { q: 'Is a phone photo good enough to replace a scanner?', a: 'For most documents, yes — provided the shot is steady, well lit, and covers the full page. Edge detection and perspective correction do the rest of the work a flatbed used to do.' },
      { q: 'How do I scan a multi-page document without a scanner?', a: 'Capture each page the same way and let them stack into one document. The scan tool adds every saved page to a single PDF, which you download at the end.' },
      { q: 'Do I need to install an app to scan documents?', a: 'No. A browser-based scanner works from Safari, Chrome, or any modern browser and runs on the device, so there is nothing to install and nothing is uploaded.' },
      { q: 'What is the best way to scan a document without a printer or scanner at home?', a: 'Use a phone camera as the capture device and a browser-based scan tool for edge detection and cleanup. Libraries and copy shops are the fallback if you need archival quality.' },
    ],
    related: ['how-to-scan-documents-to-pdf-with-your-phone', 'how-to-scan-a-document-to-pdf-on-iphone', 'how-to-scan-multiple-pages-into-one-pdf', 'how-to-make-a-scanned-pdf-searchable'],
  },

  {
    slug: 'how-to-sign-a-pdf-without-printing-it',
    title: 'How to Sign a PDF Without Printing It (Free)',
    description: 'Sign a PDF without printing it, for free — type your name, draw a signature, or upload a photo of your handwritten one, all in your browser with no upload and no app.',
    keyword: 'how to sign a pdf without printing it',
    category: 'Editing & Signing',
    published: '2026-09-19',
    tool: 'sign-pdf',
    experience: 'I stopped printing contracts to sign them years ago. An in-browser signing tool that runs on the device, with draw, type, and image options, is how I sign everything now — the whole signature step takes about ten seconds.',
    blocks: [
      { type: 'p', text: 'You never need to print a PDF to sign it. An electronic signature is a signature: type or draw yours (or import a photo of your pen-and-ink one), drop it onto the document, and download the signed PDF. Free, in any browser, with nothing uploaded and no account required.' },
      { type: 'p', text: 'Here is exactly how to sign a PDF without printing it.' },
      { type: 'h2', text: 'The three ways to create a signature' },
      { type: 'p', text: 'A good signing tool gives you three honest options, because a handwritten look and a rapid typed signature serve different situations:' },
      { type: 'table', head: ['Method', 'Best when', 'Result'], rows: [
        ['Draw', 'You are on a phone or tablet', 'Your own handwriting, captured by mouse, finger, or stylus'],
        ['Type', 'You need the fastest route', 'Your name in a clean signature-style font'],
        ['Image', 'You have a signature you want repeated', 'A photo of your real ink signature, applied every time'],
      ] },
      { type: 'h2', text: 'Sign a PDF in your browser' },
      { type: 'steps', items: [
        'Open the Sign PDF tool and upload the document.',
        'Pick how you want to sign: Draw, Type, or Image.',
        'Create the signature — draw in the box, type your name, or upload a picture of your existing signature.',
        'Tap the signature to place it on the signature line, then drag and resize it to fit.',
        'Add the date or a second signature if the document asks for one, then download the signed PDF.',
      ] },
      { type: 'callout', title: 'The signature never leaves your device', text: 'Because signing runs in the browser, your signature image and the document itself are processed locally. Nothing is uploaded to a server, which makes this safe for NDAs, offer letters, and anything with your identity attached.' },
      { type: 'h2', text: 'Do I still need to print if the sender wants a wet signature?' },
      { type: 'p', text: 'Most documents are fine with an electronic signature. When someone specifically requests an ink signature, the image method covers you: sign once with a pen, photograph it, upload the photo, and place it as your signature. The document is still delivered digitally — nothing is printed and mailed.' },
      { type: 'h2', text: 'Making the signature land in the right place' },
      { type: 'list', items: [
        'Zoom into the signature line before placing the signature so you can align it accurately',
        'Place the signature and drag to fine-tune before downloading',
        'Sign in the order the document lists — some forms reject signatures that arrive out of sequence',
        'Resize a typed signature slightly smaller than you think; it renders more elegantly',
        'On a touch device, draw with a stylus or your finger for a smoother line than a mouse gives',
      ] },
      { type: 'h2', text: 'Is an electronic signature legally binding?' },
      { type: 'p', text: 'In most jurisdictions, including the US and EU, an electronic signature on a PDF carries the same legal weight as a handwritten one for everyday agreements such as contracts, consents, and approvals. Always check the specific document or agreement if it has its own signature requirements.' },
    ],
    faqs: [
      { q: 'How do I sign a PDF without printing it?', a: 'Open a signing tool in your browser, upload the PDF, then draw, type, or upload an image of your signature. Place it on the signature line, adjust its size, and download the signed file — no printing at any step.' },
      { q: 'Can I use a picture of my real signature on a PDF?', a: 'Yes. Sign a slip of paper with a pen, photograph or scan it, and upload the image as your signature. It then repeats on every document you sign.' },
      { q: 'Is a typed signature valid on a PDF?', a: 'It is. A typed signature is a simple electronic signature, which is legally valid for most agreements. Some banks and government services may require a handwritten or digital-certificate signature specifically.' },
      { q: 'Do I need an Adobe account to sign a PDF?', a: 'No. A browser-based signing tool works without an account, without an upload, and without any software install.' },
      { q: 'How do I add a signature to a PDF on my phone?', a: 'Open the Sign PDF tool in your phone’s browser, upload the PDF, and draw the signature with your finger or stylus. Place and resize it, then download the signed document.' },
    ],
    related: ['how-to-sign-a-pdf-electronically', 'how-to-sign-a-pdf-electronically-for-free', 'how-to-edit-a-pdf'],
  },

  {
    slug: 'why-cant-i-edit-a-pdf',
    title: "Why Can't I Edit a PDF? (And How to Actually Fix It)",
    description: "Why can't I edit a PDF? Here are the four real reasons — password protection, scanned pages, signed locks, or the wrong app — and how to fix each one for free.",
    keyword: "why can't i edit a pdf",
    category: 'Troubleshooting',
    published: '2026-09-19',
    tool: 'edit-pdf',
    blocks: [
      { type: 'p', text: 'You cannot edit a PDF for one of four reasons: the file is password-protected against editing, the pages are scanned images with no real text behind them, the document has been digitally signed to lock it, or you are viewing it in a reader that cannot edit. All four are common, and all four have a practical fix.' },
      { type: 'p', text: 'Here is how to tell which one is blocking you — and what to do for each.' },
      { type: 'h2', text: 'Find the reason in ten seconds' },
      { type: 'table', head: ['Symptom', 'Most likely cause', 'Fix'], rows: [
        ['“This document is protected / password required”', 'Password or permissions lock', 'Unlock with the password, if you are authorized'],
        ['Editing is allowed but nothing changes when you type', 'Scanned pages with no text layer', 'Run OCR so the text becomes real and editable'],
        ['The file says it is signed and locked', 'Digital signature ' , 'Edit before signing; ask the sender to unsign if allowed'],
        ['Your editor works on other files, not this one', 'Viewer, not an editor', 'Use a real PDF editor in your browser'],
      ] },
      { type: 'h2', text: 'Reason 1: the PDF is password-protected' },
      { type: 'p', text: 'Some PDFs carry an edit or owner password that stops anyone from changing them. If you are the owner (or have the password), remove the restrictions with a PDF unlock tool, saving an unprotected copy, and edit normally. Only do this when you are entitled to — unlocking someone else’s password-protected document without permission is not acceptable.' },
      { type: 'h2', text: 'Reason 2: the pages are scanned images' },
      { type: 'p', text: 'A document that came from a scanner or a phone camera is just a set of pictures. The text you see is not real text — there is nothing for an editor to change. Fix it with OCR (optical character recognition), which reads the printed letters and adds a text layer. After that, the editor can select and rewrite them.' },
      { type: 'h2', text: 'Reason 3: the PDF is digitally signed and locked' },
      { type: 'p', text: 'A digital signature certifies that a document has not been altered since it was signed — so most signed PDFs are locked against edits by design. You cannot reasonably edit a signed agreement without invalidating the signature. If edits are genuinely needed, they should happen before signing, or the other party should send an updated unsigned version.' },
      { type: 'h2', text: 'Reason 4: the wrong app is editing (or not editing)' },
      { type: 'p', text: 'Free viewers — Preview, Edge, Chrome, Google Docs viewer — can add annotations but cannot change existing text, headings, or numbers. An annotation looks like an edit but is a separate layer. For real editing you need a proper PDF editor, and a browser-based one works with no install:' },
      { type: 'steps', items: [
        'Open the Edit PDF tool and upload the file.',
        'Select the existing text to rewrite it, or click where you want to add new text.',
        'Adjust the size, font, and color to match the page.',
        'Make your other changes — numbers, headings, links — then download the edited PDF.',
      ] },
      { type: 'callout', title: 'If your file is still protected after checking these', text: 'Re-download the PDF from the original source rather than a forwarded copy. Senders often lock copies inadvertently; the original is usually the editable one.' },
    ],
    faqs: [
      { q: 'Why is my PDF not letting me edit it?', a: 'Usually one of four things: the file is password-protected against editing, its pages are scanned images with no text layer, it has been digitally signed and locked, or you are working in a viewer that only adds annotations. Match your symptom to the right fix above.' },
      { q: 'Why can’t I edit a PDF I made from Word or Google Docs?', a: 'Word and Google Docs export PDFs with editable text, so those are normally editable with a real PDF editor. If typing does nothing, check for a password lock or try an editor that supports the text layer properly.' },
      { q: 'How do I make a scanned PDF editable?', a: 'Run OCR on the scanned file to add a searchable, selectable text layer. Once the text is real, a standard PDF editor can rewrite it.' },
      { q: 'Can I edit a PDF in Word without converting it?', a: 'Not as a PDF. Word will convert the PDF to its own editable format, which changes the layout and often scrambles design elements. For layout-safe edits, use a PDF editor instead.' },
      { q: 'Why does the PDF say “Protected document”?', a: 'The file has editing or permissions restrictions set by its author. With the password and the author’s permission, you can unlock it and continue editing.' },
    ],
    related: ['how-to-edit-a-pdf-without-adobe', 'how-to-make-a-scanned-pdf-searchable', 'how-to-remove-a-password-from-a-pdf'],
  },

  {
    slug: 'how-to-compress-a-pdf-for-whatsapp',
    title: 'How to Compress a PDF for WhatsApp (Free)',
    description: 'Compress a PDF for WhatsApp for free in your browser — no upload, no app, and no quality loss you will notice. Keep documents shareable even when file size is the blocker.',
    keyword: 'how to compress a pdf for whatsapp',
    category: 'Compressing',
    published: '2026-09-19',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: 'WhatsApp blocks (or silently refuses) PDFs that exceed its file-size limits, and the “Document won’t send / file to large” error appears right when the file is most needed. Compress the PDF in your browser first — free, no upload, no app — and it will send as a document instead of a distorted photo gallery.' },
      { type: 'p', text: 'Here is how to compress a PDF for WhatsApp in under a minute.' },
      { type: 'h2', text: 'WhatsApp’s real file-size limit' },
      { type: 'p', text: 'WhatsApp sends PDFs as a Document, and documents are capped at 16 MB on most platforms (many Android devices allow up to 2 GB for documents). The practical rule: stay under 16 MB and it will share on essentially everything. If a companion video needs sending too, keep in mind videos are shared separately with their own size caps.' },
      { type: 'h2', text: 'Compress the PDF to a target size' },
      { type: 'steps', items: [
        'Open the Compress PDF tool and upload the document.',
        'Set the target size to 16 MB — or lower, like 5 MB, for faster delivery over mobile data.',
        'Check the compression estimate and pick how aggressive to be; the tool warns when text would become unscannable.',
        'Run the compression and download the result.',
        'Send the file through WhatsApp using the document (paperclip) option — not photo/video.',
      ] },
      { type: 'callout', title: 'Nothing is uploaded', text: 'Compression runs locally in your browser. The document never leaves the device, so contracts, invoices, and financial statements stay private while you shrink them.' },
      { type: 'h2', text: 'What actually shrinks a PDF' },
      { type: 'list', items: [
        'Images dominate file size — most of the win comes from recompressing embedded photos',
        'Text-heavy pages compress dramatically without visible loss',
        'A too-aggressive pass rewrites the file as images, making text blurrier and unselectable',
        'Exported presentations and scans compress best; already-optimized files gain little',
      ] },
      { type: 'h2', text: 'Choose the right compression level' },
      { type: 'table', head: ['Situation', 'Target size', 'Expectations'], rows: [
        ['Portrait/photo scans', '16 MB', 'Small visible change, still crisp'],
        ['Contract or invoice in a hurry', '5 MB', 'Clean text, fast send'],
        ['Presentation with big image slides', '2–5 MB', 'Images softened, layout intact'],
        ['Long graphic-heavy doc, still oversized', 'Under 1 MB', 'Writes as images; text no longer selectable'],
      ] },
      { type: 'p', text: 'After compressing, verify the file re-opens cleanly before you send it. Then attach it with the document icon in the chat bar so WhatsApp delivers a real file — recipients can download, open, and even re-share it without degradation.' },
    ],
    faqs: [
      { q: 'How do I compress a PDF for WhatsApp?', a: 'Open a browser-based compressor, upload the PDF, set a target size at or below 16 MB, and download the result. Send the compressed file as a document in WhatsApp rather than a photo — documents keep the file intact.' },
      { q: 'What is the file size limit for PDFs on WhatsApp?', a: 'WhatsApp caps document files at 16 MB on most platforms; many Android devices allow documents up to 2 GB. Keeping the PDF under 16 MB works everywhere.' },
      { q: 'Why does WhatsApp compress my PDF and ruin the quality?', a: 'PDFs sent as photos are converted to an image and crushed. Send the PDF as a Document instead and WhatsApp delivers it unchanged — compress beforehand only if the file itself is too large.' },
      { q: 'Can I compress a PDF without uploading it to a server?', a: 'Yes. A browser-based compressor that runs locally keeps the document on your device, so the file never leaves your computer or phone.' },
      { q: 'How small can I make a PDF for WhatsApp?', a: 'Text-only documents can drop to a few hundred KB. Image-heavy pages settle wherever the photos allow; pushing below a few MB forces them into a blurrier, image-based format.' },
    ],
    related: ['how-to-compress-pdf-for-email-attachment', 'how-to-compress-a-pdf-without-losing-quality', 'how-to-compress-a-scanned-pdf'],
  },

  {
    slug: 'how-to-darken-a-scanned-pdf',
    title: 'How to Darken a Scanned PDF That Is Too Light to Read',
    description: 'Darken a scanned PDF that is too light to read — learn the fastest fixes by re-scanning with a phone and boosting contrast, without installing photo editors.',
    keyword: 'how to darken a scanned pdf too light to read',
    category: 'Troubleshooting',
    published: '2026-09-19',
    tool: 'scan-pdf',
    blocks: [
      { type: 'p', text: 'A scanned PDF that is too light to read usually means the capture was thin or washed out — and the fastest dependable fix is not a photo editor, it is re-capturing with contrast-boosting filters. If the page exists in paper form, one rescan with the right settings fixes the whole class of problem.' },
      { type: 'p', text: 'Here is how to darken a scanned PDF when the text is too light to read.' },
      { type: 'h2', text: 'Why scanned pages come out light' },
      { type: 'list', items: [
        'The scanner or camera was set to lighten the page',
        'Overshadowing during a phone capture produced washed areas',
        'The original print was faint — a light font, a faded dot-matrix page, or a low-toner copy',
        'A brightness/contrast pass in an editor “fixed” the photo side but left the print faded',
      ] },
      { type: 'h2', text: 'The reliable fix: re-capture with a contrast filter' },
      { type: 'p', text: 'When you have the paper, photograph it a second time and let a document scanner apply a high-contrast filter instead of trusting a photo editor. The B&W filter maps the page into crisp black-and-white — faint gray text becomes solid black — and the Magic filter pulls up contrast while keeping tones natural.' },
      { type: 'steps', items: [
        'Lay the page on a flat, evenly lit surface.',
        'Open the Scan PDF tool, allow camera access, and centre the page in the frame.',
        'After capture, switch to the B&W filter and check the preview — grays turn to solid black.',
        'If B&W feels harsh, use Magic for a softer contrast lift.',
        'Rotate if needed, tap Save, and download the darkened PDF.',
      ] },
      { type: 'callout', title: 'No photo editor required', text: 'You do not need to open Photoshop or its free equivalents. The in-browser scan filters apply contrast and turn the page into a readable black-and-white document in the same step that captures it.' },
      { type: 'h2', text: 'Fixes that depend on where the PDF came from' },
      { type: 'table', head: ['Where the PDF started', 'Best fix', 'Notes'], rows: [
        ['Paper document you still have', 'Re-scan with phone + B&W/Magic filter', 'Fastest, best quality'],
        ['Scanner with darkness setting', 'Raise the darkness/brightness in the scan settings', 'Look for a Darkness/Brightness slider in the driver'],
        ['Already digital, faint print', 'Re-render or regenerate from the source if the PDF is converted', 'Editing the image side is cosmetic'],
        ['Only a faded PDF copy exists', 'Use the “Image/Gray” filter on a fresh photograph — source may be unrecoverable', 'Quality capped by the original capture'],
      ] },
      { type: 'h2', text: 'When you only have the digital file' },
      { type: 'p', text: 'If the paper is gone, your options are limited because the faintness is baked into the pixels. Filters that increase contrast and play with brightness can help somewhat, but documents scanned too light rarely recover fully. Go back to a high-quality source if one exists, or accept a lightly improved copy and keep it searchable with OCR.' },
      { type: 'h2', text: 'Preventing light scans next time' },
      { type: 'list', items: [
        'Set the office scanner’s darkness a step higher than default',
        'Photograph pages in even light — no flash pointing at the page',
        'In a scan tool, choose the B&W filter before saving so pages are born dark',
        'Check one page on screen before scanning a long stack',
      ] },
    ],
    faqs: [
      { q: 'How do I darken a scanned PDF that is too light?', a: 'If you still have the paper, re-capture it with a phone camera and apply a high-contrast filter such as B&W — it turns faint gray text into solid black. Raise the darkness setting on a scanner, or regenerate the PDF from its original source when the paper is gone.' },
      { q: 'Can I darken a scanned PDF in Photoshop or free editors?', a: 'You can raise contrast and brightness there, but the film grain and compression are already baked in, so results are limited. Re-scanning with a contrast filter produces cleaner output than editing the scanned image.' },
      { q: 'Why is my scanned PDF coming out so light?', a: 'The scanner or camera was set to lighten the page, the capture was overshadowed, or the original print itself is faint. Increasing darkness on the source and using a B&W filter are the standard fixes.' },
      { q: 'Can I make the text in a scanned PDF darker?', a: 'Yes, the text itself darkens when you raise contrast or apply a black-and-white filter so that faint halftones become solid strokes. Text that is already pasted-in images is harder to fix without a quality source.' },
      { q: 'Is there a way to darken a scanned PDF online without uploading?', a: 'A browser-based scan tool processes the pages on your device, so you can re-capture and darken without any upload to a server.' },
    ],
    related: ['why-is-my-pdf-blurry', 'how-to-scan-documents-to-pdf-with-your-phone', 'how-to-make-a-scanned-pdf-searchable'],
  },

  {
    slug: 'why-does-my-pdf-open-in-word',
    title: 'Why Does My PDF Open in Word? (Fix It in 30 Seconds)',
    description: 'Why does my PDF open in Word instead of a PDF reader? Fix the default app on Windows, Mac, Android, or ChromeOS — and stop Word from mangling your layout.',
    keyword: 'why does my pdf open in word instead of pdf reader',
    category: 'Troubleshooting',
    published: '2026-09-19',
    tool: 'edit-pdf',
    blocks: [
      { type: 'p', text: 'Your PDF opens in Word because Microsoft Word registers itself as the handler for PDF files — most often after an Office update, an “Open with Word” choice that was saved, or a fresh install. When Word grabs PDFs it converts them into editable Office documents, which can shift pages, fonts, and layout the moment you open them.' },
      { type: 'p', text: 'Here is how to make PDFs open in a PDF reader instead — on every device — and what to do if you actually need to edit.' },
      { type: 'h2', text: 'On Windows' },
      { type: 'steps', items: [
        'Right-click the PDF and choose Open with > Choose another app.',
        'Pick a real PDF reader (Microsoft Edge, Adobe, or your browser).',
        'Tick the box “Always use this app to open .pdf files”.',
        'Alternatively go to Settings > Apps > Default apps, type .pdf, and change the handler.',
      ] },
      { type: 'h2', text: 'On Mac' },
      { type: 'steps', items: [
        'Right-click the PDF and choose Get Info.',
        'Open the “Open with” section and choose Preview or your browser.',
        'Click Change All… so every PDF uses the new app.',
      ] },
      { type: 'h2', text: 'On Android and ChromeOS' },
      { type: 'steps', items: [
        'Find the PDF in the Files app and long-press it.',
        'Choose Open with > the PDF reader (PDF Viewer or a browser).',
        'Pick “Always” so future PDFs stop defaulting to an Office app.',
      ] },
      { type: 'h2', text: 'Why Word should not be the default for PDFs' },
      { type: 'p', text: 'Word does not merely display a PDF — it converts its text into a Word document. That is why pages reflow, fonts swap, and graphics drift when you double-click a PDF. For viewing, a reader renders the file exactly as its author laid it out. For editing, a PDF editor changes text in place without converting the file.' },
      { type: 'callout', title: 'Think twice about opening PDFs in Word on purpose', text: 'Converted PDFs lose fidelity. If you truly need to change text, resizing, or content, a real PDF editor preserves the layout — Word conversion is the shortcut that breaks it.' },
      { type: 'h2', text: 'If you actually needed to edit the PDF' },
      { type: 'steps', items: [
        'Keep Word out of the picture for editing — it converts instead of editing.',
        'Open the Edit PDF tool in your browser and upload the file.',
        'Rewrite text, headings, and numbers in place while the layout holds.',
        'Download the edited PDF; PDFs keep opening perfectly in every reader now.',
      ] },
      { type: 'table', head: ['Need', 'Use', 'Result'], rows: [
        ['Just view a PDF', 'PDF reader (Preview, Edge, browser)', 'Accurate rendering, fast open'],
        ['Fill a form or add notes', 'Reader annotations', 'Added layer, original intact'],
        ['Change existing text', 'PDF editor', 'Layout preserved, editable text'],
        ['Convert to Word', 'Word, deliberately', 'Content editable, layout may shift'],
      ] },
    ],
    faqs: [
      { q: 'Why does my PDF file open in Word?', a: 'Word is registered as the default handler for .pdf files, usually after an Office install or an earlier “Open with Word” choice. Change the default app back to a PDF reader on your device in the file association settings.' },
      { q: 'How do I stop PDFs from opening in Microsoft Word?', a: 'On Windows, right-click a PDF, choose Open with > Choose another app, pick your PDF reader, and tick “Always use this app.” On Mac, change the “Open with” app in Get Info and click Change All.' },
      { q: 'Does opening a PDF in Word mess it up?', a: 'It converts the PDF to an editable Word document, so pages and fonts can shift. The original file is not damaged, but you are looking at a conversion — not the PDF itself.' },
      { q: 'Why does Word ask to convert my PDF every time?', a: 'Word is set as the default PDF handler, so it converts on open. Set a proper PDF reader as the default and Word only appears when you deliberately choose it.' },
      { q: 'Is it better to edit a PDF in Word or a PDF editor?', a: 'For layout-preserving edits, a PDF editor. Word converts the document, which reflows pages and replaces fonts — fine for text extraction, poor for a file that must keep its design.' },
    ],
    related: ['how-to-fix-a-pdf-that-opens-blank', 'how-to-edit-a-pdf-without-adobe', 'how-to-fix-a-pdf-that-wont-print'],
  },
];