import type { BlogPost } from '../types';

export const newPosts8: BlogPost[] = [
  // Article 1: How to Convert Word to PDF on Android
  {
    slug: 'how-to-convert-word-to-pdf-on-android',
    title: 'How to Convert Word to PDF on Android (Free, No App)',
    description: 'Turn a Word document into a PDF on your Android phone for free. Convert in Chrome with the Files app or a no-install browser tool.',
    keyword: 'how to convert word to pdf on android',
    category: 'Converting',
    published: '2026-09-03',
    tool: 'word-to-pdf',
    blocks: [
      { type: 'p', text: 'A Word document on your phone needs to become a PDF — for a form, an application, or just so it opens identically on anyone else\u2019s device. Android handles the conversion differently depending on whether the file came from Word, Google Docs, or an email. Here is how to convert Word to PDF on Android for free, without installing an app.' },
      { type: 'h2', text: 'Convert with the Files app (built in)' },
      { type: 'p', text: 'Android\u2019s Files app can export a Word document to PDF directly, which is the fastest option when you just need a file:' },
      { type: 'steps', items: [
        'Open the Files app on your Android phone.',
        'Browse to the .docx file and tap it to preview it.',
        'Tap the share or menu icon and choose Print.',
        'Select "Save as PDF" instead of a printer.',
        'Confirm the pages and tap Save, then pick where to store the PDF.',
      ] },
      { type: 'p', text: 'This keeps the document on your phone and needs no extra software. Layout with simple headings and paragraphs carries over cleanly; very complex formatting sometimes shifts.' },
      { type: 'h2', text: 'Convert in Google Docs (best for cloud files)' },
      { type: 'list', items: [
        'Open the Word file in the Google Docs app or drive.google.com.',
        'Tap the three-dot menu and choose "Save as PDF".',
        'A PDF is downloaded to your phone, precisely matching the Google Docs preview.',
      ] },
      { type: 'p', text: 'Google Docs reflows and re-renders the document, so what you see on screen is what the PDF looks like. For files that live in Drive, this is the most reliable route.' },
      { type: 'h2', text: 'Convert in your browser with font safety' },
      { type: 'p', text: 'If a Word file contains unusual fonts or you want the most faithful conversion, a browser-based Word to PDF tool makes the PDF from the actual document and embeds the fonts:' },
      { type: 'steps', items: [
        'Open the Word to PDF tool in Chrome on your Android.',
        'Tap to choose a file and pick your .docx from Downloads, Drive, or phone storage.',
        'Review the rendered document, then tap convert.',
        'Download the PDF back to your phone and share it.',
      ] },
      { type: 'callout', title: 'Local privacy', text: 'When the conversion runs in your browser tab, the document is processed on your phone rather than uploaded, which matters for contracts, CVs, and anything sensitive.' },
      { type: 'h2', text: 'Word vs. Google Docs vs. browser: which to pick' },
      { type: 'table', head: ['Method', 'Best for', 'Needs account'], rows: [
        ['Files app Print', 'Quick one-off exports, stays offline', 'No'],
        ['Google Docs', 'Documents already in Drive, predictable layout', 'Google account'],
        ['Browser tool', 'Complex formatting and embedded fonts', 'No'],
      ] },
      { type: 'h2', text: 'Check before you send' },
      { type: 'p', text: 'After converting, open the PDF once and flip through it. Confirm tables and columns held their shape, and that any inserted images are in place. A five-second check prevents sending a document that renders differently on the recipient\u2019s computer.' },
    ],
    faqs: [
      { q: 'Can I convert Word to PDF on Android for free?', a: 'Yes — Android\u2019s Files app can print any .docx to PDF, Google Docs can save a Word file as PDF, and a browser-based converter does it in one tap. No app install or subscription required.' },
      { q: 'How do I convert a .docx to PDF without an app?', a: 'Open the file in the Files app, tap the menu, choose Print, then select "Save as PDF". That creates the PDF on your phone with nothing extra installed.' },
      { q: 'Does converting change my Word document?', a: 'No. Conversion creates a new PDF and leaves the original .docx untouched, so you can convert again or edit the Word file later.' },
      { q: 'Why does my Word document look different as a PDF?', a: 'PDF renders a fixed page layout, so fonts, tables, and columns are locked in place. Simple layouts convert identically; very complex formatting can shift and is worth checking before sending.' },
      { q: 'Is my document uploaded to a server when I convert it?', a: 'When you use a local browser converter, no — the document is processed on your phone. The Files app Print and Google Docs saves also keep or use your file as you expect.' },
    ],
    related: ['how-to-convert-word-to-pdf-on-iphone', 'how-to-convert-word-to-pdf-on-mac', 'how-to-convert-pdf-to-word-on-android', 'how-to-make-a-pdf-on-iphone'],
  },

  // Article 2: How to Convert PDF to JPG on Android
  {
    slug: 'how-to-convert-pdf-to-jpg-on-android',
    title: 'How to Convert PDF to JPG on Android (Free, In-Browser)',
    description: 'Turn PDF pages into JPG images on your Android phone for free. Convert one page or all of them in Chrome — no app install.',
    keyword: 'how to convert pdf to jpg on android',
    category: 'Converting',
    published: '2026-09-03',
    tool: 'pdf-to-jpg',
    blocks: [
      { type: 'p', text: 'A PDF page needs to become an image so you can post it, attach it where PDFs are rejected, or paste it into a document. Android can screenshot pages, but you get one blurry page at a time and the result is a rough copy. A dedicated converter turns any page into a clean, high-resolution JPG in seconds.' },
      { type: 'p', text: 'Here is how to convert a PDF to JPG on Android for free, right in Chrome.' },
      { type: 'h2', text: 'Why screenshots are not the answer' },
      { type: 'list', items: [
        'Screenshots render at your screen resolution, so print-quality pages come out soft',
        'Capturing multi-page documents means dozens of screenshots, stitched by hand',
        'Scrolled pages and zoomed views get cropped unpredictably',
        'A converter re-renders the page cleanly at your chosen output quality',
      ] },
      { type: 'callout', title: 'One page or all pages', text: 'A browser-based PDF to JPG tool exports the page you select or the whole document as separate, high-resolution images — no app install and no upload, since it runs on your device.' },
      { type: 'h2', text: 'Convert a PDF to JPG on Android in Chrome' },
      { type: 'steps', items: [
        'Open the PDF to JPG tool in the Chrome browser on your Android phone.',
        'Tap to choose a file and pick your PDF from Downloads, Google Drive, or your phone\u2019s storage.',
        'Choose whether to convert a single page or every page.',
        'Pick the output format and resolution — JPG at a higher DPI for print, lower for web.',
        'Tap convert, then download the JPG images to your phone.',
      ] },
      { type: 'p', text: 'Each page becomes its own .jpg file, named in order so a 20-page document is easy to keep straight when you share or zip them.' },
      { type: 'h2', text: 'Choosing JPG quality and resolution' },
      { type: 'p', text: 'For images that will be emailed or posted, a 100–150 DPI export is plenty and keeps file sizes small. For pages you plan to print, re-import into a document, or enlarge, export at a higher DPI so the text stays sharp. JPG gives small files at the cost of slight compression; if you need perfect edges, an image export at higher quality is the safer pick for line work.' },
      { type: 'h2', text: 'Sharing converted pages' },
      { type: 'p', text: 'Once your pages are JPGs, you can attach them individually to messages and forms. If the form expects exactly one image, combine your pages into a single JPG in a photo editor, or keep them separate and label each file by page number so nothing gets lost.' },
      { type: 'h2', text: 'After converting' },
      { type: 'p', text: 'Your original PDF is never modified, so you can re-export a page at a different quality whenever you need it. If you converted the whole document, keep the source PDF on your phone as the master copy and use the JPGs only where images are required.' },
    ],
    faqs: [
      { q: 'How do I convert a PDF to JPG on Android for free?', a: 'Open a browser-based PDF to JPG tool in Chrome, select your PDF, choose the pages and quality, and download the resulting images. No app install and no account needed.' },
      { q: 'Can I convert only one page of a PDF?', a: 'Yes. The tool lets you pick a single page or export the entire document as separate JPGs.' },
      { q: 'What resolution should I choose?', a: 'For web and email, 100–150 DPI keeps files small. For printing or enlarging, export at a higher DPI so text stays sharp.' },
      { q: 'Does converting a PDF to JPG reduce quality?', a: 'Only as much as the JPG format requires. Choose a higher resolution and quality setting for crisp output; JPG is best for photos and mixed pages, while pure line art may look cleaner re-created from the PDF tools.' },
      { q: 'Is my PDF uploaded when I convert it?', a: 'No. When the conversion runs in the browser, your document is processed on your Android device and never leaves your phone.' },
    ],
    related: ['how-to-convert-pdf-to-jpg-on-iphone', 'how-to-convert-pdf-to-jpg-high-quality', 'how-to-convert-pdf-to-image-for-printing', 'how-to-merge-pdf-files-on-android'],
  },

  // Article 3: How to Compress a PDF on Mac
  {
    slug: 'how-to-compress-a-pdf-on-mac',
    title: 'How to Compress a PDF on Mac (Free, No Install)',
    description: 'Shrink a large PDF on a Mac for free. Set exact levels or hit a size target in your browser — no extra software beyond Preview and Safari.',
    keyword: 'how to compress a pdf on mac',
    category: 'Compressing',
    published: '2026-09-03',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: 'A PDF that refuses to fit an email or an upload form is a familiar Mac problem. Preview can save a smaller version, but its controls are blunt and its savings uneven. A browser-based compressor gives you precise control over how much a file shrinks.' },
      { type: 'p', text: 'Here is how to compress a PDF on a Mac for free, with Preview and with a browser tool.' },
      { type: 'h2', text: 'Compress with Preview (built in)' },
      { type: 'steps', items: [
        'Open the PDF in Preview on your Mac.',
        'Choose File > Export.',
        'Open the Quartz Filter menu and pick Reduce File Size.',
        'Click Save and check the new file size.',
      ] },
      { type: 'p', text: 'Preview\u2019s Reduce File Size is a preset with a fixed lever — it helps, but you cannot choose how aggressively it compresses, and the result can go soft on image-heavy pages. For a quick tidy it is fine; for a specific size target it is unpredictable.' },
      { type: 'callout', title: 'Preview only handles simple files', text: 'If your PDF was heavily edited, contains many images, or was re-saved repeatedly, Preview\u2019s preset often delivers less than you need. A browser compressor re-encodes the whole file from scratch for larger, more even savings.' },
      { type: 'h2', text: 'Compress with a browser tool (precise levels)' },
      { type: 'steps', items: [
        'In Safari or Chrome on your Mac, open the Compress PDF tool.',
        'Drag the PDF from Finder into the tool, or click to browse and select it.',
        'Pick a compression level — light keeps images crisp, heavy makes the smallest file.',
        'Tap compress and check the result size.',
        'Download the smaller PDF back to your Mac.',
      ] },
      { type: 'p', text: 'Because the compression runs in the browser, a sensitive file stays on your Mac instead of being uploaded to a server.' },
      { type: 'h2', text: 'Hitting a specific size limit' },
      { type: 'table', head: ['Limit', 'What to do'], rows: [
        ['Under 10 MB', 'Light compression handles most documents'],
        ['Under 5 MB', 'Choose medium and re-check'],
        ['Under 2 MB', 'Heavy compression, then verify readability'],
        ['Under 1 MB', 'Remove images first, then compress at a heavy level'],
      ] },
      { type: 'h2', text: 'Why is my PDF still too large?' },
      { type: 'list', items: [
        'Full-page scans carry a huge image payload that resists modern compression',
        'Pictures placed at print resolution but displayed small waste megabytes',
        'Repeated editing layers accumulate invisible overhead',
      ] },
      { type: 'p', text: 'If heavy compression is still not enough, the fastest win is usually at the source: remove unneeded pages, delete oversized images, and re-scan documents at lower resolution in grayscale.' },
    ],
    faqs: [
      { q: 'How do I compress a PDF on Mac for free?', a: 'Use Preview\u2019s Export with the Reduce File Size filter for a quick result, or a browser-based compressor in Safari or Chrome for precise levels. Both are free and need no install.' },
      { q: 'Does Preview compress PDFs?', a: 'Yes — File > Export > Quartz Filter > Reduce File Size gives a smaller file, but its single preset gives you no control over how much quality is traded away.' },
      { q: 'Which compression level should I use?', a: 'Start with light for crisp images and text. If the file is still too large, step up to a heavier level and preview the result at 100% zoom before sending it.' },
      { q: 'Is my PDF uploaded to a server when I compress it?', a: 'No. When you use a browser-based compressor, the file is processed on your Mac and never leaves your device.' },
      { q: 'Why did my PDF barely shrink?', a: 'Either it was already optimised, or it is mostly text — text-only PDFs are already small and have little to remove. Large files are image-heavy, which is where compression pays off.' },
    ],
    related: ['how-to-compress-a-pdf-on-iphone', 'how-to-compress-a-pdf-on-windows', 'how-to-reduce-pdf-file-size-on-mac', 'how-to-compress-pdf-for-email-attachment'],
  },

  // Article 4: How to Password Protect a PDF on Android
  {
    slug: 'how-to-password-protect-a-pdf-on-android',
    title: 'How to Password Protect a PDF on Android (Free)',
    description: 'Lock a PDF with a password on your Android phone for free. Add a strong password in Chrome — no app install and no uploads.',
    keyword: 'how to password protect a pdf on android',
    category: 'Security & Privacy',
    published: '2026-09-03',
    tool: 'protect-pdf',
    blocks: [
      { type: 'p', text: 'A report, a contract, or a scan with personal details should not be floating around readable by anyone who receives it. Locking a PDF with a password is the simplest way to keep it safe. Android has no built-in option for this, and many Play Store apps only unlock the feature in a paid tier.' },
      { type: 'p', text: 'Here is how to password protect a PDF on Android for free, right in Chrome.' },
      { type: 'h2', text: 'What password protection actually does' },
      { type: 'list', items: [
        'It encrypts the document so a password is required to open it',
        'It stops casual sharing — the file is useless without the password',
        'It is not the same as editing restrictions, which only limit changes',
      ] },
      { type: 'callout', title: 'Encryption strength', text: 'Modern PDF protection uses strong encryption (AES-256 on recent files), which is why you should forget the password only after a backup — there is no way to recover it.' },
      { type: 'h2', text: 'Password protect a PDF on Android in Chrome' },
      { type: 'steps', items: [
        'Open the Protect PDF tool in the Chrome browser on your Android phone.',
        'Tap to choose a file and pick your PDF from Downloads, Google Drive, or your phone\u2019s storage.',
        'Enter a strong password — several words, at least 12 characters.',
        'Re-enter it to confirm, then tap protect.',
        'Download the locked PDF back to your phone.',
      ] },
      { type: 'p', text: 'The output is a new encrypted file; your original is left untouched. The whole process runs on your phone, so the document never has to be uploaded.' },
      { type: 'h2', text: 'Choosing a password that survives' },
      { type: 'list', items: [
        'Use a phrase of 4–6 unrelated words, not a single dictionary word',
        'Add numbers or symbols if the recipient can handle them',
        'Share the password through a different channel than the file itself',
        'Do not reuse the same password you use for email or other accounts',
      ] },
      { type: 'h2', text: 'Sharing the locked PDF' },
      { type: 'p', text: 'When you send the protected file, text or call the recipient with the password separately. Sending the password in the same email as the file defeats the protection. If you need to revoke access after sharing, you cannot — which is exactly why the password should stay private.' },
      { type: 'h2', text: 'Removing protection later' },
      { type: 'p', text: 'If you no longer need the lock, you can remove the password from the PDF with the password in hand. Keep the original unprotected copy somewhere safe, or commit to storing the password in your password manager.' },
    ],
    faqs: [
      { q: 'Can I password protect a PDF on Android for free?', a: 'Yes. A browser-based Protect PDF tool runs in Chrome with no app install and no account, adding strong encryption to your document in a few taps.' },
      { q: 'Does Android have a built-in PDF password tool?', a: 'No. Android provides no native way to lock a PDF. A browser-based tool adds the feature with nothing to install.' },
      { q: 'What is the best way to share the password?', a: 'Send the file one way and the password another — a text or call, not the same email. That way a stolen attachment does not hand out its own key.' },
      { q: 'Can the password be recovered if I forget it?', a: 'No. Strong PDF encryption has no backdoor. Keep the original unprotected copy, or store the password in your password manager.' },
      { q: 'Does protection change the file layout?', a: 'No. The pages, text, and images are unchanged; protection only wraps the file so a password is required to open it.' },
    ],
    related: ['how-to-password-protect-a-pdf-on-iphone', 'how-to-password-protect-a-pdf-on-windows', 'how-to-remove-a-password-from-a-pdf', 'how-to-protect-a-pdf-from-copying'],
  },

  // Article 5: How to Edit a PDF on Android
  {
    slug: 'how-to-edit-a-pdf-on-android',
    title: 'How to Edit a PDF on Android (Free, In-Browser)',
    description: 'Edit text, images, and pages in a PDF on your Android phone for free in Chrome. No app install, no account, and no uploads.',
    keyword: 'how to edit a pdf on android',
    category: 'Editing & Signing',
    published: '2026-09-03',
    tool: 'edit-pdf',
    blocks: [
      { type: 'p', text: 'A PDF needs a date corrected, a paragraph changed, or an image swapped in — and it arrived on your Android phone. Android\u2019s built-in viewers annotate on top of pages but cannot edit the real content. Many Play Store "PDF editor" apps are subscription-driven and lock the core tools away.' },
      { type: 'p', text: 'Here is how to edit a PDF on Android for free, right in Chrome.' },
      { type: 'h2', text: 'What "editing" means for a PDF' },
      { type: 'list', items: [
        'Editing text — change or retype words that are already in the document',
        'Editing images — move, resize, or replace pictures on a page',
        'Editing pages — add, delete, rotate, or reorder pages',
        'Annotating (adding notes, highlights, shapes) is separate from editing',
      ] },
      { type: 'callout', title: 'Text must be real text', text: 'A PDF created from a scanned page stores text as an image, so it cannot be edited until it is converted or run through OCR. Digitally-created PDFs edit directly.' },
      { type: 'h2', text: 'Edit a PDF on Android in Chrome' },
      { type: 'steps', items: [
        'Open the Edit PDF tool in the Chrome browser on your Android phone.',
        'Tap to choose a file and pick your PDF from Downloads, Google Drive, or your phone\u2019s storage.',
        'Click a text block to retype it, or select an image to move or resize it.',
        'For structure changes, use the page tools to add, delete, or reorder pages.',
        'When it looks right, tap Save and download the edited PDF.',
      ] },
      { type: 'p', text: 'Because editing runs in your browser, your document stays on your phone rather than being uploaded to a server.' },
      { type: 'h2', text: 'Editing text vs. adding text' },
      { type: 'p', text: 'Editing changes words that already exist in the document — they stay in-place and flow with the layout. Adding text drops a new box wherever you place it, useful for filling gaps or adding comments. For a form or a missing field, adding text is the quick fix; for correcting a typo or rewording a paragraph, editing the actual text is what you want.' },
      { type: 'h2', text: 'When editing is not the right tool' },
      { type: 'list', items: [
        'Scanned PDFs need OCR first — convert them or extract the text before editing',
        'Sensitive legal documents are safer with a fresh PDF you control end-to-end',
        'If only the page order is wrong, reorder or rearrange pages instead',
      ] },
      { type: 'h2', text: 'Check the result before sharing' },
      { type: 'p', text: 'Open the saved file once and confirm every change held — reflowed text can push a table off a page, and moved images can cover lines. A quick flip-through beats sending a document that looked fine in the editor but broke on export.' },
    ],
    faqs: [
      { q: 'Can I edit a PDF on Android for free?', a: 'Yes — a browser-based Edit PDF tool runs in Chrome with no app install and no account, letting you retype text, move images, and manage pages.' },
      { q: 'Does Android have a built-in PDF editor?', a: 'No. Android\u2019s viewers annotate over PDFs but cannot change the real text, images, or pages. A browser tool adds full editing with nothing to install.' },
      { q: 'Why can\u2019t I edit the text in my PDF?', a: 'If the PDF is a scan or photo, the text is stored as an image. Convert it or run OCR to turn the pixels into editable characters first.' },
      { q: 'Will editing change the rest of my document?', a: 'Editing reflows the affected area, which can shift other elements. Save a copy before major edits and check the layout of neighbouring pages afterward.' },
      { q: 'Is my document uploaded to a server when I edit it?', a: 'No. When editing runs in your browser, the file is processed on your Android device and never leaves your phone.' },
    ],
    related: ['how-to-edit-a-pdf-on-iphone', 'how-to-edit-a-pdf-on-mac', 'how-to-edit-a-pdf-on-a-chromebook', 'how-to-edit-pdf-text-without-acrobat'],
  },
];