import type { BlogPost } from '../types';

export const newPosts27: BlogPost[] = [
  {
    slug: 'how-to-scan-a-whiteboard-to-pdf',
    title: 'How to Scan a Whiteboard to PDF (Free, No App)',
    description: 'Scan a whiteboard to PDF with your phone: straighten the board, remove glare and grey shadows, keep marker colours. Free, in the browser, nothing uploaded.',
    keyword: 'scan whiteboard to pdf',
    category: 'Converting',
    published: '2026-10-04',
    tool: 'scan-pdf',
    blocks: [
      { type: 'p', text: 'To scan a whiteboard to PDF, you need more than a photo. A photo of a whiteboard is grey, shiny and shot at an angle, and that is why it is hard to read later. A whiteboard scan fixes all three: it straightens the board into a rectangle, turns the grey glare back into white, and makes the marker strokes dark and saturated. You can do it on your phone in the browser — no app, no account — and keep the result as a PDF you can share with everyone who was in the room.' },
      { type: 'h2', text: 'How to scan a whiteboard to PDF' },
      { type: 'p', text: 'Open the Scan PDF tool on your phone, switch the camera to Whiteboard mode and point it at the board. Hold steady until the outline turns green, or tap the shutter. In Review, drag the corners onto the board edges if needed, keep the Whiteboard filter, and save as a PDF.' },
      { type: 'steps', items: [
        'Open Scan PDF on your phone and tap Open camera (allow camera access when the browser asks).',
        'Choose Whiteboard in the mode bar above the shutter.',
        'Stand square to the board, fill most of the screen with it, and keep still until the capture fires — or tap the shutter yourself.',
        'Capture the next board or section the same way; each capture becomes a page.',
        'Tap the thumbnail, check each page, then tap Save PDF and download or share the file.', ],
      },
      { type: 'h2', text: 'What the Whiteboard filter actually does' },
      { type: 'p', text: 'Whiteboards fail as photos for three reasons. The surface is glossy, so ceiling lights leave bright hot spots and the rest of the board looks grey. The light is uneven, so one side is darker than the other. And thin marker strokes lose contrast once the camera averages them with the white around them.' },
      { type: 'p', text: 'The Whiteboard filter estimates how bright the board is in every small region of the picture, then divides that lighting out — so a board that is grey on the left and white on the right comes out evenly white. After that it pushes the light tones to pure white and boosts colour, so red, blue and green markers stay clearly different instead of fading to the same dull grey. It runs on your phone; the photo is not sent anywhere.' },
      { type: 'callout', title: 'Run this test before the meeting ends', text: 'Scan the board once, open the page in Review and zoom in (pinch or double-tap) on the smallest writing. If you can read it there, the PDF will be readable too. If not, step closer and scan the board in two halves — two sharp pages beat one blurry one.' },
      { type: 'h2', text: 'Shooting tips that make the biggest difference' },
      { type: 'list', items: [
        'Stand square to the board. The scanner corrects angle, but a straight-on shot keeps letters on the far side as sharp as the near side.',
        'Move until reflections slide off the writing. A hot spot from a ceiling light can wipe out a word; a small step sideways usually moves it onto blank board.',
        'Turn the flash off. On a glossy board the flash creates exactly the glare you are trying to remove.',
        'For a long board, scan it in sections from left to right, then use Reorder in Review if one ends up out of place.',
        'Capture before anyone erases — you can fix the crop, filter and order later, but you cannot rescan a wiped board.', ],
      },
      { type: 'h2', text: 'What if the board edges are not detected?' },
      { type: 'p', text: 'Edge detection looks for a clear four-sided shape. A board that fills the whole view, sits on a white wall, or has a thin frame can be hard to separate from its surroundings. In that case tap the shutter yourself; if no edges are found, the scanner opens Adjust borders so you can drag the four corners onto the board. Full photo keeps the whole picture, which is often right for a board that fills the frame anyway.' },
      { type: 'h2', text: 'Whiteboard scanner app vs your browser' },
      { type: 'table', head: ['', 'Scan in the browser', 'Typical whiteboard scanner app'], rows: [
        ['Install', 'None', 'App store download'],
        ['Account', 'Not needed', 'Often needed to export or sync'],
        ['Where the photo goes', 'Stays on your phone', 'Often synced to the vendor’s cloud'],
        ['Glare and colour clean-up', 'Whiteboard filter', 'Whiteboard filter'],
        ['Searchable text', 'Optional OCR on the device', 'Varies; often a paid feature'],
        ['Watermark', 'None', 'Common on free tiers'],
      ] },
      { type: 'p', text: 'If your team already lives in an app that files board photos into shared notes, that workflow may suit you. For a one-off — "can someone send round what was on the board?" — opening a page and sending a PDF is quicker than getting everyone to install the same app.' },
      { type: 'h2', text: 'Make the notes searchable' },
      { type: 'p', text: 'When you save, leave "Recognize text (OCR)" switched on. The recognised text is laid invisibly over each page, so you can search the PDF for a word you remember from the meeting and copy it out. Handwriting is the hard case for any OCR: neat block capitals are usually recognised, while fast joined-up writing often is not. The page image is always kept, so nothing is lost when recognition misses a word.' },
      { type: 'p', text: 'To add a decision, an owner or a date before you share the file, open Markup on the page and type it in or highlight the line that matters. If you only need the text, Copy text reads the page and gives you editable text to paste into an email or a ticket.' },
    ],
    faqs: [
      { q: 'How do I scan a whiteboard to PDF without an app?', a: 'Open a browser-based scanner such as Scan PDF on your phone, choose Whiteboard mode, capture the board, check the crop in Review and save as PDF. Nothing needs installing and the photo stays on your phone.' },
      { q: 'How do I remove glare from a whiteboard photo?', a: 'Move sideways until the reflection is off the writing, turn the flash off, then use the Whiteboard filter, which evens out the lighting across the board and turns the grey cast back to white.' },
      { q: 'Can I make whiteboard notes searchable?', a: 'Yes. Save with text recognition (OCR) on and the PDF gets a hidden text layer you can search and copy. Neat printed handwriting is recognised far better than fast cursive.' },
      { q: 'How do I scan a large whiteboard?', a: 'Scan it in sections from left to right so the writing stays sharp, then check the order in Review — each section becomes its own page in the same PDF.' },
    ],
    related: ['how-to-scan-documents-to-pdf-with-your-phone', 'how-to-scan-multiple-pages-into-one-pdf', 'how-to-make-a-scanned-pdf-searchable', 'how-to-straighten-a-crooked-scan-or-photo'],
  },
];
