import type { BlogPost } from '../types';

export const newPosts18: BlogPost[] = [
  {
    slug: 'how-to-convert-a-scanned-pdf-to-a-word-document',
    title: 'How to Convert a Scanned PDF to a Word Document (Free)',
    description: 'Turn a scanned PDF into an editable Word document for free — run OCR so the scan becomes readable, then convert it to DOCX, all in your browser with no upload.',
    keyword: 'how to convert a scanned pdf to a word document',
    category: 'Converting',
    published: '2026-09-24',
    tool: 'pdf-to-word',
    experience: 'When a client sent me a signed contract as a scanned PDF, Word did not edit it, selection did not copy, and Ctrl+F found nothing — because the page was a photograph, not text. The two-step sequence I use every time is: run OCR to build a real text layer, then convert the searchable PDF to Word. It is the difference between a document you can edit and one you can only look at.',
    blocks: [
      { type: 'p', text: 'A scanned PDF looks like text but is actually a page of pictures, so a normal converter has nothing to read. Converting a scanned PDF to a Word document is a two-step job: run OCR first so the scan gains a text layer, then convert that searchable PDF to DOCX. This article walks both steps, shows you the ten-second check that tells you a file is scanned, and covers what to expect from the finished document.' },
      { type: 'h2', text: 'Check first: is the PDF actually scanned?' },
      { type: 'p', text: 'Open the PDF and drag-cursor across a line of text. If it highlights and copies, the file has a text layer and converts straight to Word. If your cursor only draws a box and nothing selects, the page is an image — a scan, a photo, or a document flattened on export. That file needs OCR before it can convert at all, and knowing the difference saves you one failed conversion every time.' },
      { type: 'list', items: [
        'Text selects and copies: a native PDF — convert to Word directly',
        'Selection draws a box and copies nothing: a scan — run OCR first',
        'A blank document comes out of "convert to Word": your file was a scan all along',
      ] },
      { type: 'h2', text: 'How to convert a scanned PDF to Word' },
      { type: 'p', text: 'The sequence is OCR, then convert. Skipping the first step produces an empty document or one image trapped in a single page, because the scanner turned every letter into a picture.' },
      { type: 'steps', items: [
        'Open the OCR PDF tool and add your scanned PDF.',
        'Run OCR — the letters in the images are recognized and written back as a searchable text layer.',
        'Download the searchable PDF.',
        'Open the PDF to Word tool with that file and convert to DOCX.',
        'Open the result in Word and edit normally.',
      ] },
      { type: 'callout', title: 'OCR is not a magic wand', text: 'OCR recognizes letters reliably, but it does not rebuild pixel-perfect layout. Headings, paragraphs and line breaks come through well enough to edit; complex columns, faint scans and form boxes often need a small tidy-up in Word afterwards. That is expected, not a failure.' },
      { type: 'h2', text: 'What the Word document will look like' },
      { type: 'table', head: ['In the scan', 'In the Word document'], rows: [
        ['Plain typed text', 'Editable paragraphs, accurate to the source'],
        ['Headings and bullet lists', 'Recognized and rebuilt as structure'],
        ['Photographs and logos', 'Come across as images'],
        ['Faint, tilted or low-contrast scans', 'Characters can be misread — proofread numbers'],
        ['Form fields and checkboxes', 'Usually flattened artwork, not fields'],
      ] },
      { type: 'h2', text: 'Why the scan quality decides everything' },
      { type: 'p', text: 'A 300-dpi, straight, high-contrast scan converts almost perfectly. A blurred phone photo or a photocopy of a photocopy introduces misreads — the classic ones are 0 and O, 1 and l, and the digits in account numbers. Proofread amounts, dates and identifiers against the original page before you rely on the result, and if characters are wrong, a cleaner rescan beats any amount of post-editing.' },
      { type: 'h2', text: 'When Word itself can open the file' },
      { type: 'p', text: 'Microsoft Word can open a PDF directly and convert it — but for scans it is hit or miss. Word converts the text layer it finds, and a scan has none until OCR runs. The reliable route is still OCR first, then convert, and the whole thing stays in your browser with nothing uploaded and no account.' },
    ],
    faqs: [
      { q: 'Can I convert a scanned PDF to Word without software?', a: 'Yes. Run OCR on the scan so it gains a text layer, then convert the searchable PDF to Word. Both steps happen in the browser with no install and no upload.' },
      { q: 'Why does my scanned PDF convert to an empty Word document?', a: 'Because a scan has no selectable text — the pages are images. OCR has to recognize the letters first; only then does the Word conversion have anything to read.' },
      { q: 'Does the Word document keep the original formatting?', a: 'Text and structure come through well enough to edit, but OCR does not rebuild pixel-perfect layout. Complex columns and faint scans usually need minor tidy-up in Word.' },
      { q: 'How accurate is OCR on a scanned PDF?', a: 'Very good on a clean 300-dpi scan, weaker on blurred or low-contrast pages. Always proofread numbers, dates and IDs — zero/O and one/l are the classic misreads.' },
      { q: 'Can Word open the scanned PDF directly?', a: 'Word converts the text layer it finds, and unsensitized scans have none. OCR first is the reliable path; opening the scan straight in Word usually gives broken or empty output.' },
    ],
    related: ['how-to-convert-pdf-to-word-without-losing-formatting', 'how-to-make-a-scanned-pdf-searchable', 'how-to-copy-text-from-a-scanned-pdf', 'how-to-convert-a-scanned-pdf-to-an-excel-spreadsheet'],
  },

  {
    slug: 'how-to-convert-a-scanned-pdf-to-an-excel-spreadsheet',
    title: 'How to Convert a Scanned PDF to an Excel Spreadsheet (Free)',
    description: 'Turn a scanned PDF into an editable spreadsheet for free — OCR the scan so its tables become real text, then convert the searchable PDF to Excel in your browser.',
    keyword: 'how to convert a scanned pdf to an excel spreadsheet',
    category: 'Converting',
    published: '2026-09-24',
    tool: 'pdf-to-excel',
    experience: 'Bank statements and supplier invoices arrive as scans, and the whole point of the spreadsheet is the grid — dates, descriptions, amounts in their own cells. A plain converter returns nothing because the page is an image, so the dependable sequence is OCR to make the tables real text, then convert the searchable PDF to Excel. Reviewing figures against the scan afterwards is not optional; it is the job.',
    blocks: [
      { type: 'p', text: 'A scanned PDF is a picture of a page, so a plain converter reads no text, no tables and no cells. Converting a scanned PDF to an Excel spreadsheet takes two steps rather than one: OCR first, so the scanned letters and numbers become real selectable text, then a table-aware conversion of the searchable PDF into an XLSX workbook. This article covers the pipeline, why columns survive OCR but not raw copy-paste, and the review routine that catches misread figures.' },
      { type: 'h2', text: 'Convert a scanned PDF to an Excel spreadsheet' },
      { type: 'p', text: 'The order is fixed: recognize, then rebuild. A scan is an image until OCR runs, and an Excel sheet is columns and rows, which table detection rebuilds from the recognized text. Without the OCR step you get an empty workbook or a single picture trapped in a cell.' },
      { type: 'steps', items: [
        'Open the OCR PDF tool and add your scanned PDF.',
        'Run OCR — the characters in the images become a searchable text layer.',
        'Download the searchable PDF.',
        'Open the PDF to Excel tool with that file and convert to XLSX.',
        'Open the workbook and verify figures against the original page.',
      ] },
      { type: 'callout', title: 'Plain text is not a spreadsheet', text: 'Copying an OCR\'d scan and pasting into Excel flattens everything into one column, because the page position data is thrown away. A table-aware conversion maps each value back to its row and column, which is why the OCR-then-convert route keeps the grid.' },
      { type: 'h2', text: 'What converts, and how well' },
      { type: 'table', head: ['Type of scan', 'Result in Excel'], rows: [
        ['Statement or invoice with clean grid', 'Rows and columns rebuild closely to the source'],
        ['Table-heavy report (ledger, price list)', 'Cells land in the right rows, amounts stay numeric'],
        ['Mixed document with paragraphs plus a table', 'The table converts; surrounding prose becomes text cells'],
        ['Merged cells, complex multi-level headers', 'Structure flattens — expect manual rework'],
        ['Blurred or low-contrast page', 'Misread characters; verify and rescan if needed'],
      ] },
      { type: 'h2', text: 'Why scan quality drives accuracy' },
      { type: 'p', text: 'OCR accuracy is decided before the conversion starts. A straight, sharp, 300-dpi scan of a flat page converts well; a photo taken at an angle introduces warped rows and misread digits. The classic failures are zero/O, one/l, commas and decimal points, and any long numeric string — exactly the fields that matter in a statement. If a page reads badly, rescan it flat and straight rather than fixing every cell by hand.' },
      { type: 'h2', text: 'The review routine that catches mistakes' },
      { type: 'list', items: [
        'Foot the column totals against the printed totals on the scan',
        'Scan dates and amounts down each column for impossible values',
        'Check every ID, account and reference number character by character',
        'Look for columns that merged or split where the grid was tight',
        'Compare the header row against the source so a shifted column is caught early',
      ] },
      { type: 'h2', text: 'When to convert to CSV instead' },
      { type: 'p', text: 'If the goal is feeding data into a database or a different system, a CSV export of the same table is often cleaner than a full workbook. The export is text-only and skips Excel formatting quirks. When you need formatting, formulas and sheets, XLSX is the right output; the two conversions share the same OCR-first pipeline.' },
    ],
    faqs: [
      { q: 'Can I convert a scanned PDF to Excel for free?', a: 'Yes. OCR the scan first so the tables become selectable text, then convert the searchable PDF to Excel — both steps run in your browser with no upload and no account.' },
      { q: 'Why does my scanned PDF convert to an empty spreadsheet?', a: 'A scan has no text layer, only pixels, so a plain converter reads nothing. OCR must recognize the letters first; table detection then rebuilds the rows and columns.' },
      { q: 'Will the columns come out in the right cells?', a: 'On a clean scan, mostly yes — table-aware conversion maps each value back to its row and column. Complex merged grids and tight layouts may need manual rework.' },
      { q: 'How accurate is this for bank statements and invoices?', a: 'Accurate enough to work with on a sharp 300-dpi scan, but verify amounts, dates and reference numbers against the original — zero/O and one/l are the classic misreads.' },
      { q: 'Why does copy-paste flatten my table into one column?', a: 'Pasting recognized text drops the page-position data, so rows and columns are lost. A table-aware conversion after OCR keeps the grid intact instead.' },
    ],
    related: ['how-to-convert-pdf-to-excel-with-tables', 'how-to-export-pdf-tables-to-csv', 'how-to-make-a-scanned-pdf-searchable', 'how-to-convert-a-scanned-pdf-to-a-word-document'],
  },

  {
    slug: 'how-to-copy-text-from-a-password-protected-pdf',
    title: 'How to Copy Text from a Password-Protected PDF',
    description: 'Copy text from a password-protected PDF — release a copy-restricted file so selection works again, and know when you genuinely need the password to get in.',
    keyword: 'how to copy text from a password protected pdf',
    category: 'Security & Privacy',
    published: '2026-09-24',
    tool: 'unlock-pdf',
    experience: 'When a scanned-for-quoting PDF blocked Ctrl+C, the first thing I checked was which kind of lock it carried. A file that opens but greys out Copy is carrying a permissions flag — rebuild it and selection works again. A file that will not open without a password is a different problem entirely. Telling those two apart is the whole skill.',
    blocks: [
      { type: 'p', text: 'When copying is greyed out in a PDF, the file is protected in one of two ways — and which one decides everything you can do. Copying text from a password-protected PDF is either a quick release of a permissions restriction or a genuine password requirement, and mixing them up wastes your time. Here is how to tell them apart honestly and copy text from the files you are entitled to use.' },
      { type: 'h2', text: 'The two kinds of protection' },
      { type: 'p', text: 'A file that opens normally but blocks copying is restricted by a permissions flag — it is readable, but the creator disabled copy, print or edit. A file that refuses to open until you type a password is encrypted, and there is no legitimate way through without that password. Only the first kind can be released without asking anyone.' },
      { type: 'table', head: ['What you see', 'What it is', 'Can you copy yet?'], rows: [
        ['Opens fine; Copy is greyed out or does nothing', 'Permissions (owner) restriction', 'Yes — rebuild the file to release it'],
        ['A password prompt before the page displays', 'Password to open (encryption)', 'Only with the correct password'],
        ['Copy returns nothing at all on a visible scan', 'Scanned page with no text layer', 'Run OCR to make the text real first'],
      ] },
      { type: 'h2', text: 'Copy text from a copy-restricted PDF' },
      { type: 'steps', items: [
        'Open the Unlock PDF tool and add your file.',
        'If it opens without asking for a password, the tool rebuilds it with the copy (and print, edit) restrictions removed.',
        'Download the unlocked PDF.',
        'Open it, select the text, and copy as normal.',
      ] },
      { type: 'callout', title: 'Only where you have the right', text: 'Releasing a restriction on a document you own or are allowed to modify is routine. Removing protection from a file the owner deliberately restricted may breach its terms — copy with permission, and ask the sender for an unlocked copy of anything you do not control.' },
      { type: 'h2', text: 'When you will need the password' },
      { type: 'p', text: 'If the file will not open without a password, that password is required — nobody can honestly unlock it for you because the content is cryptographically sealed until it is entered. The same is true of a certified document carrying a digital signature seal; rebuilding it strips the signer\'s seal and flags the file as modified. Treat those cases as "get the password from the owner", not as unlock puzzles.' },
      { type: 'h2', text: 'The scanned file that "copies nothing"' },
      { type: 'p', text: 'A visible page that will not let you select a single letter is often not locked at all — it is scanned, and the words are pixels with no text layer. No unlocking fixes that. Running OCR creates the text layer so selection and copy work, which is a different tool and a different fix entirely.' },
      { type: 'h2', text: 'After unlocking, keep the file tidy' },
      { type: 'p', text: 'Once you have copied what you need, decide what happens to the unlocked copy. The rebuilt file has no restrictions left, so if it should stay protected, re-apply permissions afterwards rather than leaving a wide-open version lying around. And remember the honest version of the whole task: unlocking and copying is for material you are permitted to use, and nothing in the browser removes that responsibility.' },
    ],
    faqs: [
      { q: 'Why can\'t I copy text from a PDF that opens fine?', a: 'The file carries a permissions restriction that disables copying. It is readable but blocked, and rebuilding the document without the restriction makes selection and copy work again.' },
      { q: 'Can I copy text from a password-protected PDF without the password?', a: 'If the restriction is a permissions flag and the file opens, yes — rebuilding it releases the block. If the file demands a password to open, only that password gets in.' },
      { q: 'Why does copying select nothing even though I can see the text?', a: 'Your PDF is probably scanned, not locked. The letters are pixels with no text layer; run OCR so the text becomes real and selectable.' },
      { q: 'Does unlocking a PDF to copy text keep the quality?', a: 'Yes. The pages are re-rendered at high resolution with a hidden text layer that stays searchable; interactive form fields and links are flattened in.' },
      { q: 'Is it legal to copy text from a protected PDF?', a: 'For documents you own or have permission to use, generally yes. Copying protected content you are not entitled to reproduce can breach its terms — get permission first.' },
    ],
    related: ['how-to-unlock-a-pdf-for-printing', 'how-to-remove-a-password-from-a-pdf', 'how-to-protect-a-pdf-from-copying', 'how-to-extract-text-from-a-pdf'],
  },

  {
    slug: 'how-to-make-a-pdf-not-printable',
    title: 'How to Make a PDF Not Printable (Free)',
    description: 'Make a PDF not printable for free — set a no-printing permission flag so conforming readers grey out Print, and understand honestly how far that restriction goes.',
    keyword: 'how to make a pdf not printable',
    category: 'Security & Privacy',
    published: '2026-09-24',
    tool: 'protect-pdf',
    experience: 'Before sending a draft rate card around, I set it so readers can open it but not print a paper copy that later shows up somewhere ugly. The tool flags printing as disallowed and lets me keep it reversible with an owner password. The part I do not promise people: it is a permission flag, and a viewer can ignore it — so I pair the limitation honestly with what it actually defends against.',
    blocks: [
      { type: 'p', text: 'A PDF that cannot be printed is one carrying a printing permission set to "none" — it opens and reads normally, but a conforming reader greys out the Print command. Making a PDF not printable is a permissions change you apply to the file, and it needs the honest caveats: the restriction relies on viewers honouring it, and it will not stop printing-to-file or a camera. Here is exactly what it does, how to apply it, and what it does not do.' },
      { type: 'h2', text: 'Make a PDF not printable' },
      { type: 'p', text: 'Protect the PDF with an owner password, set printing to not allowed, and leave the "password to open" off so anyone can still open the file. Conforming viewers — Acrobat, Preview, the usual browsers — then disable printing for that document.' },
      { type: 'steps', items: [
        'Open the Protect PDF tool and add your file.',
        'Set an owner password — this is the key that protects the permissions, not a password readers type.',
        'Turn printing off in the permissions options (copy and edit can be restricted separately).',
        'Save and download the protected PDF.',
        'Verify in a normal viewer that the Print option is disabled.',
      ] },
      { type: 'callout', title: 'Keep "open with password" off for screen-only files', text: 'A print-restricted draft is still meant to be read. Set only the owner password and the printing block; if you also require a password to open, you have changed a "viewable but not printable" document into a locked one, and recipients will be prompted on every open.' },
      { type: 'h2', text: 'How far the restriction actually goes' },
      { type: 'table', head: ['Threat', 'Does the flag stop it?'], rows: [
        ['Recipient printing with a standard viewer', 'Yes — the Print command is disabled'],
        ['Recipient printing to a PDF or image file', 'Usually, in conforming viewers'],
        ['A non-conforming or specialist editor', 'No — it can ignore the permission flag'],
        ['Photographing the screen', 'No — nothing in a PDF stops a camera'],
      ] },
      { type: 'h2', text: 'What a print flag is, and is not' },
      { type: 'p', text: 'PDF printing permission is a flag that readers honour on an honour system. It is not encryption of the pixels and it is not DRM. A conforming viewer reads "printing is not allowed" and greys out the button; a determined user with the right tool or a phone can always get an image of the screen. That makes a print restriction excellent for stopping casual copies and accidental collisions with a colour printer — use it for that, and do not present it as a security guarantee.' },
      { type: 'h2', text: 'Turn the restriction off again' },
      { type: 'p', text: 'Because the block is reversible with the owner password you set, you can release it later when the draft is approved or the spreadsheet is replaced by a printable version. Rebuilding the file without the owner password removes every flag at once — the same mechanism used to unlock print-restricted PDFs, applied to a file you control.' },
      { type: 'h2', text: 'Pair it with a deterrent for screen copies' },
      { type: 'list', items: [
        'Add a DRAFT or CONFIDENTIAL watermark so any phone photograph is visibly branded',
        'Restrict copying alongside printing when the content is quote-ready',
        'Keep the original unprotected file stored safely for when printing is allowed',
        'Test the protected file in the viewer your recipients will actually use',
      ] },
    ],
    faqs: [
      { q: 'Can I make a PDF not printable for free?', a: 'Yes — set a printing permission flag with the Protect PDF tool. Conforming viewers like Acrobat and Preview then disable the Print command, and the whole process runs in your browser.' },
      { q: 'Does disabling printing really stop people from printing?', a: 'It stops casual printing in conforming viewers by greying out the option. A specialist editor can ignore the flag, and a photograph of the screen is unstoppable — treat it as a deterrent, not a guarantee.' },
      { q: 'Do readers still need a password to open a print-restricted PDF?', a: 'No. Only the owner password is set; recipients open the file normally and simply cannot print. Add a password to open only if you also want to lock viewing.' },
      { q: 'How do I make the PDF printable again?', a: 'Unlock it with the owner password you set. That rebuilds the file without the restrictions, so printing, copying and editing are all allowed again.' },
      { q: 'Will it protect against printing-to-PDF or screenshots?', a: 'Mostly against printing to a file in conforming viewers; not reliably against a determined tool, and not at all against a camera. Add a watermark to deter photographs.' },
    ],
    related: ['how-to-protect-a-pdf-from-copying', 'how-to-restrict-editing-in-a-pdf', 'how-to-unlock-a-pdf-for-printing', 'how-to-password-protect-a-pdf'],
  },

  {
    slug: 'how-to-change-a-pdf-from-portrait-to-landscape',
    title: 'How to Change a PDF from Portrait to Landscape (Free)',
    description: 'Change a PDF from portrait to landscape (or back) for free — rotate the pages a quarter turn so the orientation sticks, and the option for landscape without turning the text.',
    keyword: 'how to change a pdf from portrait to landscape',
    category: 'Editing & Signing',
    published: '2026-09-24',
    tool: 'rotate-pdf',
    experience: 'A presentation deck I inherited had wide slides forced onto portrait pages, cutting off the chart margins when anyone printed. The clean fix was a quarter-turn rotation so every page matched the wide layout it was made for. The distinction that trips people up is "landscape page" versus "text upright on a wider sheet" — one is a rotation, the other is a re-layout, and they are different operations.',
    blocks: [
      { type: 'p', text: 'Changing a PDF from portrait to landscape means turning the pages a quarter turn so they stand on their long edge — a 90-degree rotation written permanently into the file, not a temporary viewing tweak. This article covers the honest yes and no of it: rotation genuinely flips orientation, while "landscape without rotating the text" is a re-layout, not a rotation, and needs a different step. Both are explained so you use the right one.' },
      { type: 'h2', text: 'Change the page orientation permanently' },
      { type: 'p', text: 'Rotate the pages 90 degrees clockwise or counterclockwise with the Rotate PDF tool and save the result. The rotation is stored inside the document, so every device opens it landscape, printout included. Choose specific pages when only some pages should change, and leave the rest alone.' },
      { type: 'steps', items: [
        'Open the Rotate PDF tool and add your file.',
        'Choose all pages, or the specific pages that should go landscape.',
        'Apply a 90-degree rotation in the direction that turns the content upright.',
        'Download the rotated PDF and open it to confirm the orientation.',
      ] },
      { type: 'callout', title: 'Rotating changes the page with the text on it', text: 'A rotation turns the whole page — content and all — by a quarter turn, so text that was upright before across the short edge is now reading across the long edge. If what you actually want is text that stays upright while the sheet gets wider, that is the print-to-PDF method below, not a rotation.' },
      { type: 'h2', text: 'Portrait to landscape: which pages to change' },
      { type: 'table', head: ['Situation', 'What to rotate'], rows: [
        ['A slide deck exported sideways into portrait pages', 'All pages, one direction'],
        ['One wide chart among portrait pages', 'Only the wide pages, read the result first'],
        ['A scan captured in portrait that should be landscape', 'The affected pages only'],
        ['Mixed document that should stay mixed', 'Nothing — forcing orientation breaks wide tables'],
      ] },
      { type: 'h2', text: 'Landscape without rotating the text' },
      { type: 'p', text: 'Sometimes "landscape" means "wider sheet, but the text stays upright" — for a portrait form you want to print across the long edge, for example. Rotation cannot do that, because it turns the content too. The honest method is re-layout: open the PDF, press Ctrl+P or Cmd+P, set the destination to Save as PDF or Print to PDF, choose Landscape under layout, and save. That reflows the content onto a landscape sheet without turning it — at the cost of re-rendering the pages, so check tables and forms afterward.' },
      { type: 'h2', text: 'Why forcing orientation breaks documents' },
      { type: 'p', text: 'A chart made wider than it is tall needs its landscape page to stay that way; rotating it to portrait compresses the labels until they overlap. If a document mixes orientations deliberately, keep it mixed and rotate only the wrong pages — a normalizing pass that flips everything makes a readable deck unreadable. Decide by looking at the content, not by tidiness.' },
      { type: 'h2', text: 'Saved rotation versus view rotation' },
      { type: 'p', text: 'The rotate button inside most readers spins what you see on screen and forgets it when you close the file — that changes nothing for anyone you send the PDF to. A tool that writes the rotation into the document is what makes the portrait-to-landscape change permanent. If a file keeps reopening in the wrong orientation, you were probably looking at the view, not the saved rotation.' },
    ],
    faqs: [
      { q: 'Can I change a PDF from portrait to landscape permanently?', a: 'Yes — rotate the pages 90 degrees and save. The rotation is stored in the file, so every reader and printout shows it landscape.' },
      { q: 'How do I make a PDF landscape without rotating the text?', a: 'Use the print-to-PDF method: in the print dialog set Landscape under layout and save to PDF. That re-lays the content onto a wider sheet instead of turning it.' },
      { q: 'Will changing to landscape reduce quality?', a: 'No — a rotation is stored as a page value and nothing is re-rendered, so quality is unchanged. The print-to-PDF re-layout method re-renders pages, so check those separately.' },
      { q: 'Can I change only some pages to landscape?', a: 'Yes. Choose specific pages in the rotation tool so only the wide pages change and the rest of the document stays as it was.' },
      { q: 'Why does my PDF keep reopening in portrait?', a: 'You probably rotated the view in your reader rather than the document. Apply the rotation in a tool that saves it into the file and download the result.' },
    ],
    related: ['how-to-rotate-a-pdf-and-save-it', 'how-to-rotate-a-single-page-in-a-pdf', 'how-to-change-the-page-size-of-a-pdf', 'how-to-print-a-pdf-correctly'],
  },
];