import type { BlogPost } from '../types';

export const newPosts6: BlogPost[] = [
  // Article 1: How to Convert Word to PDF on Mac
  {
    slug: 'how-to-convert-word-to-pdf-on-mac',
    title: 'How to Convert Word to PDF on Mac (Free, No Office)',
    description: 'Turn a Word (.docx) file into a PDF on a Mac for free. Choose between Pages, Google Docs, and a browser tool that keeps formatting intact.',
    keyword: 'how to convert word to pdf on mac',
    category: 'Converting',
    published: '2026-09-01',
    tool: 'word-to-pdf',
    blocks: [
      { type: 'p', text: 'A résumé, a contract, or a report written in Microsoft Word needs to be sent as a PDF so the formatting holds up on every device. On a Mac you have a few good ways to convert a Word document to PDF, and only one of them needs Microsoft Word at all.' },
      { type: 'p', text: 'Here is how to convert Word to PDF on a Mac for free — with Pages, with Google Docs, or with a browser tool that needs no office software.' },
      { type: 'h2', text: 'Convert a Word file to PDF in Pages' },
      { type: 'p', text: 'Pages is the free word processor that comes with macOS, and it opens Word documents directly. This is often the fastest route because Pages is already on your Mac:' },
      { type: 'steps', items: [
        'Open the .docx file in Pages, either by double-clicking or dragging it onto the Pages icon.',
        'Check that the layout looks right — headings, images, and tables should carry over from Word.',
        'Choose File > Export To > PDF.',
        'Set the image quality and whether to include a password, then click Next.',
        'Name the file, choose where to save it, and click Export.',
      ] },
      { type: 'p', text: 'Pages handles most Word documents cleanly, but complex layouts — tracked changes, macros, or unusual fonts — can shift. In that case, a dedicated converter is the safer choice.' },
      { type: 'h2', text: 'Convert a Word file to PDF in Google Docs' },
      { type: 'p', text: 'If you use Google Drive, you can convert a Word file to PDF without any local software:' },
      { type: 'steps', items: [
        'Upload the .docx file to Google Drive.',
        'Open the file, which Google previews and edits as a Google Doc.',
        'Choose File > Download > PDF Document.',
        'The browser downloads the PDF to your Mac.',
      ] },
      { type: 'p', text: 'Google Docs is free, but it re-renders the document with its own fonts, so the result is not always pixel-identical to the original Word layout.' },
      { type: 'callout', title: 'The most reliable formatting route', text: 'When a document must look exactly as you designed it — in Word, with the fonts you used — a dedicated Word-to-PDF converter reproduces the layout more faithfully than Pages or Google Docs, and it works right in your browser with no office app installed.' },
      { type: 'h2', text: 'Convert a Word file to PDF in your browser' },
      { type: 'p', text: 'A browser-based converter needs no Microsoft Word, no Pages setup, and no Google account. It opens your .docx and builds the PDF to match the source layout:' },
      { type: 'steps', items: [
        'Open the Word to PDF tool in Safari or Chrome on your Mac.',
        'Drag your .docx file from Finder into the tool, or click to browse and select it.',
        'Click convert and wait a moment while the PDF is built on your machine.',
        'Download the finished PDF and open it to confirm the formatting kept its shape.',
      ] },
      { type: 'p', text: 'Because the conversion runs locally in the browser tab, a sensitive document — a resume, a signed agreement, a bank letter — never has to be uploaded to a server.' },
      { type: 'h2', text: 'Why send a PDF instead of the original Word file?' },
      { type: 'p', text: 'A PDF locks in your formatting so the recipient sees exactly what you designed rather than a rearranged version in their own word processor. It is also safer for documents you do not want edited, and nearly every portal, application form, and client prefers PDF.' },
    ],
    faqs: [
      { q: 'Can I convert a Word document to PDF on a Mac for free?', a: 'Yes. Use Pages (built into macOS), Google Docs, or a browser-based Word to PDF converter — none of them require a paid Microsoft Office subscription.' },
      { q: 'Does Pages open Word files correctly?', a: 'Pages opens .docx files and keeps most formatting, but complex layouts with macros or unusual fonts can shift. A dedicated converter reproduces the layout more faithfully.' },
      { q: 'Will converting to PDF change my formatting?', a: 'A dedicated Word to PDF converter preserves headings, images, tables, and fonts better than Pages or Google Docs, which re-render the document with their own defaults.' },
      { q: 'Do I need Microsoft Word to convert to PDF on a Mac?', a: 'No. Pages, Google Docs, and browser-based converters all do it without Word installed.' },
      { q: 'Is my Word document uploaded to a server?', a: 'No. When the conversion runs in your browser, your .docx is processed locally on your Mac and never leaves your device.' },
    ],
    related: ['how-to-convert-word-to-pdf-without-losing-formatting', 'how-to-convert-word-to-pdf-on-iphone', 'how-to-convert-jpg-to-pdf-on-windows', 'how-to-convert-google-docs-to-pdf'],
  },

  // Article 2: How to Convert PDF to Word on Android
  {
    slug: 'how-to-convert-pdf-to-word-on-android',
    title: 'How to Convert PDF to Word on Android (Free, In-Browser)',
    description: 'Turn a PDF into an editable Word document on your Android phone for free. Convert in Chrome with no app install and no account.',
    keyword: 'how to convert pdf to word on android',
    category: 'Converting',
    published: '2026-09-01',
    tool: 'pdf-to-word',
    blocks: [
      { type: 'p', text: 'A contract, a training manual, or a form arrives as a PDF on your Android phone and you need to rewrite part of it in Word. Android has no built-in PDF to Word converter, and the Play Store is full of apps that bury the feature behind a subscription or stamp your output with a watermark. You do not need any of that.' },
      { type: 'p', text: 'Here is how to convert a PDF to Word on Android for free, right in Chrome.' },
      { type: 'h2', text: 'Why Android has no built-in option' },
      { type: 'list', items: [
        'Google\u2019s Files app by Google opens PDFs but cannot convert them to Word',
        'The Android Chrome browser reads PDFs but has no converter',
        'Most "free" PDF apps on the Play Store limit PDF to Word behind paid tiers or add watermarks',
      ] },
      { type: 'callout', title: 'A browser tab is the no-install route', text: 'A browser-based PDF to Word tool runs in Chrome on any Android phone — nothing to download, no account, and your file is processed on the device, so a sensitive document never leaves your phone.' },
      { type: 'h2', text: 'Convert a PDF to Word on Android in Chrome' },
      { type: 'steps', items: [
        'Open the PDF to Word tool in the Chrome browser on your Android phone.',
        'Tap to choose a file and pick your PDF from Downloads, Google Drive, or your phone\u2019s storage.',
        'Select Word as the output format and tap convert.',
        'When it finishes, download the .docx back to your phone.',
        'Open the file in Word, Google Docs, or WPS Office to edit it.',
      ] },
      { type: 'p', text: 'The converted document keeps your text, headings, and basic layout, so you can make changes instead of retyping the whole thing.' },
      { type: 'h2', text: 'Converting scanned PDFs from your Android' },
      { type: 'p', text: 'If your PDF is a scan or a photo of a printed page, its text is stored as an image, not as selectable characters. A converter can only embed that image. For a scanned file, run OCR first to extract the text, then convert the result to Word.' },
      { type: 'h2', text: 'What to check after converting' },
      { type: 'p', text: 'Open the Word file and scroll through it before you rely on it — a table or heading can occasionally shift during conversion. If you need the final document back as a PDF after editing, convert it back when you are ready to send it.' },
    ],
    faqs: [
      { q: 'Can I convert a PDF to Word on my Android for free?', a: 'Yes. A browser-based PDF to Word converter runs in Chrome with no app install and no account, and lets you download an editable Word file.' },
      { q: 'Does Android have a built-in PDF to Word converter?', a: 'No. The Files by Google and Chrome apps open PDFs but cannot convert them to Word. A browser-based tool adds that capability with nothing to install.' },
      { q: 'Why does my converted file show a scanned image instead of text?', a: 'If the PDF is a scan or photo, the text is an image. Run OCR first to extract the text, then convert the result to Word.' },
      { q: 'Where can I edit the converted Word file on Android?', a: 'Open the downloaded .docx in the Word app, Google Docs, WPS Office, or any editor that supports DOCX.' },
      { q: 'Is my PDF uploaded to a server when I convert it?', a: 'No. When the conversion runs in your browser, your document is processed locally on your Android and never leaves your device.' },
    ],
    related: ['how-to-convert-pdf-to-word-without-losing-formatting', 'how-to-convert-pdf-to-word-on-iphone', 'how-to-convert-a-pdf-into-editable-text', 'how-to-copy-text-from-a-scanned-pdf'],
  },

  // Article 3: How to Rotate a PDF on iPhone
  {
    slug: 'how-to-rotate-a-pdf-on-iphone',
    title: 'How to Rotate a PDF on iPhone (Free, No App)',
    description: 'Rotate pages in a PDF on your iPhone for free. Fix a sideways scan or send a portrait page as landscape — right in Safari.',
    keyword: 'how to rotate a pdf on iphone',
    category: 'Editing & Signing',
    published: '2026-09-01',
    tool: 'rotate-pdf',
    blocks: [
      { type: 'p', text: 'A scan comes in sideways, or a document was built wrong and every page is landscape when it should be portrait. On an iPhone, fixing the rotation should be quick — but the stock Files app can only rotate a photo-like preview, not the actual PDF pages. A browser tool can rotate a PDF on your iPhone for free in under a minute.' },
      { type: 'p', text: 'Here is how to rotate a PDF on your iPhone, without installing an app.' },
      { type: 'h2', text: 'Why the built-in options are limited' },
      { type: 'list', items: [
        'The Files app preview rotates the view but does not change the saved PDF pages',
        'Screenshotting a sideways page and rotating the photo does not fix the document itself',
        'Many App Store PDF apps hide page rotation behind premium tiers',
      ] },
      { type: 'callout', title: 'Rotate the real pages, in Safari', text: 'A browser-based Rotate PDF tool changes the live pages in the file itself — so when the recipient opens it, the PDF is correctly oriented on any device. And it runs on your phone, so nothing is uploaded.' },
      { type: 'h2', text: 'Rotate a PDF on iPhone in Safari' },
      { type: 'steps', items: [
        'Open the Rotate PDF tool in Safari on your iPhone.',
        'Tap to choose a file and select your PDF from the Files app, iCloud Drive, or an email attachment saved to Files.',
        'Pick a rotation angle — 90, 180, or 270 degrees.',
        'Optionally choose which pages to rotate (for example, only the sideways page) rather than the whole document.',
        'Tap rotate and download the corrected PDF back to your iPhone.',
      ] },
      { type: 'p', text: 'Rotating 90 degrees turns portrait pages to landscape and back; 180 degrees flips everything upside-down; 270 is the reverse of 90. You can rotate just the pages that need it and leave the rest untouched.' },
      { type: 'h2', text: 'Fixing one sideways page' },
      { type: 'p', text: 'When only a single page in the middle of a document is rotated, select that specific page instead of rotating everything. That keeps the rest of the document exactly as it is while correcting the one page that matters.' },
      { type: 'h2', text: 'Rotating and then adjusting the file' },
      { type: 'p', text: 'Rotating rarely changes file size, so after you straighten a document you can compress, merge, or re-export it normally. If a rotated page still looks cropped, a Crop PDF tool can trim it down after the rotation.' },
    ],
    faqs: [
      { q: 'Can I rotate a PDF on my iPhone for free?', a: 'Yes. A browser-based Rotate PDF tool runs in Safari, turns pages by 90, 180, or 270 degrees, and needs no app install or account.' },
      { q: 'Does the iPhone have a built-in PDF rotator?', a: 'No. The Files app rotates a preview but does not save the rotation into the PDF pages. A browser-based tool actually rotates the pages in the file.' },
      { q: 'Can I rotate only one page of a multi-page PDF?', a: 'Yes. The tool lets you choose specific pages to rotate instead of the whole document.' },
      { q: 'How do I know which angle I need?', a: 'Use 90 degrees to move between portrait and landscape, 180 to flip upside-down, and 270 for the opposite clockwise turn. Preview after rotating to confirm.' },
      { q: 'Does rotating a PDF affect the file size or quality?', a: 'No. Rotating re-orients the pages without re-encoding the content, so quality and file size stay essentially the same.' },
    ],
    related: ['how-to-rotate-a-pdf-and-save-it', 'how-to-crop-a-pdf', 'how-to-reorder-pages-in-a-pdf', 'how-to-split-a-pdf-on-mac'],
  },

  // Article 4: How to Edit a PDF on Mac
  {
    slug: 'how-to-edit-a-pdf-on-mac',
    title: 'How to Edit a PDF on Mac (Free, No Adobe)',
    description: 'Edit text, fix typos, and update numbers in a PDF on a Mac for free. Preview is limited — use a browser editor for real changes.',
    keyword: 'how to edit a pdf on mac',
    category: 'Editing & Signing',
    published: '2026-09-01',
    tool: 'edit-pdf',
    blocks: [
      { type: 'p', text: 'You need to change a date, fix a typo, or update a number in a PDF on your Mac. The built-in Preview app can annotate a document — add text boxes, highlights, notes — but it cannot edit the original words themselves. For real text edits, you need a PDF editor.' },
      { type: 'p', text: 'Here is how to edit a PDF on a Mac for free, without Adobe Acrobat.' },
      { type: 'h2', text: 'What Preview can and cannot do' },
      { type: 'list', items: [
        'Preview can add text boxes, arrows, highlights, and signatures on top of a PDF',
        'Preview cannot change or remove existing words in the document',
        'Scanned pages contain images of text, so Preview treats them as pictures regardless',
      ] },
      { type: 'callout', title: 'Preview edits the page, not the text', text: 'Every tool in Preview\u2019s Markup toolbar places something on top of the page. To change the actual words — "March 5" to "March 8" — you need an editor that modifies the text objects in the file itself.' },
      { type: 'h2', text: 'Edit PDF text on your Mac in the browser' },
      { type: 'steps', items: [
        'Open the Edit PDF tool in Safari or Chrome on your Mac.',
        'Drag your PDF from Finder into the tool, or click to browse and select it.',
        'Click on any text block to edit it — change the wording, fix a typo, or update a number.',
        'Download the edited PDF and confirm your changes saved.',
      ] },
      { type: 'p', text: 'A browser editor changes text directly in the PDF while preserving the surrounding formatting, fonts, and layout. And because it runs locally, a sensitive document stays on your Mac rather than being uploaded to a server.' },
      { type: 'h2', text: 'What you can and cannot edit' },
      { type: 'p', text: 'Direct text editing works on PDFs that were created digitally — files exported from Word, Google Docs, or PDF creators — where text is stored as real, selectable characters. You can change words, headings, dates, and values in those.' },
      { type: 'p', text: 'Scanned PDFs have no text to edit — only pictures of text. For those, run OCR to convert the scan into editable text first, or make the change in the original document and re-export to PDF.' },
      { type: 'h2', text: 'Editing vs. converting to Word and back' },
      { type: 'table', head: ['Method', 'Best for', 'Downside'], rows: [
        ['Direct PDF editing', 'Small, targeted changes in a digital PDF', 'Only works on PDFs with selectable text'],
        ['Convert to Word, edit, convert back', 'Heavy rewrites', 'Reformats layout and can lose fonts'],
        ['OCR, then edit', 'Scanned PDFs', 'Recognition is not always perfect, adds a step'],
      ] },
      { type: 'h2', text: 'Always keep a copy of the original' },
      { type: 'p', text: 'Before you edit, save a copy of the original PDF. Once you download an edited version, the previous text is gone unless you still have the source. Keep the original so you can start over if a change is not what you wanted.' },
    ],
    faqs: [
      { q: 'Can I edit a PDF on a Mac for free?', a: 'Yes. A browser-based Edit PDF tool changes text directly in a digital PDF with no installation and no account. For annotations only, the built-in Preview app is also free.' },
      { q: 'Can Preview edit PDF text?', a: 'No. Preview adds annotations on top of a page but cannot change the original words. A browser-based editor is needed to alter text itself.' },
      { q: 'Why can I not edit a scanned PDF?', a: 'A scan stores text as images, so there are no real characters to change. Run OCR first to convert the scan into editable text.' },
      { q: 'Will editing change my formatting?', a: 'No. Direct PDF editing preserves fonts, spacing, and layout — only the text you change is affected.' },
      { q: 'Is my PDF uploaded to a server when I edit it?', a: 'No. When the editor runs in your browser, your document is processed locally on your Mac and never leaves your device.' },
    ],
    related: ['how-to-edit-a-pdf-on-iphone', 'how-to-edit-a-pdf-on-a-chromebook', 'how-to-edit-pdf-text-without-acrobat', 'how-to-add-text-to-a-pdf'],
  },

  // Article 5: How to Reduce PDF File Size on iPhone
  {
    slug: 'how-to-reduce-pdf-file-size-on-iphone',
    title: 'How to Reduce PDF File Size on iPhone (Free)',
    description: 'Shrink a PDF on your iPhone to make it small enough to email or upload. Compress in Safari — no app install, no quality loss.',
    keyword: 'how to reduce pdf file size on iphone',
    category: 'Compressing',
    published: '2026-09-02',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: 'A PDF that is too large to email, upload, or attach to a form stops you cold on an iPhone — the mail app refuses the attachment, or a portal rejects the file. You do not need to download a compressor app to fix it.' },
      { type: 'p', text: 'Here is how to reduce PDF file size on your iPhone for free, right in Safari.' },
      { type: 'h2', text: 'Your compression options on iPhone' },
      { type: 'list', items: [
        'The Files app has a Quick Action called Optimize File Size that compresses a PDF in one tap',
        'A browser-based compressor in Safari gives you control over how much to shrink the file',
        'Many App Store compressors hide the useful settings behind subscriptions or add watermarks',
      ] },
      { type: 'callout', title: 'Keep quality control in Safari', text: 'The Files Quick Action applies a fixed level of compression with no options. A browser-based tool lets you choose how aggressively to compress and preserves the original, so you can compare before sharing.' },
      { type: 'h2', text: 'Reduce PDF file size on iPhone in Safari' },
      { type: 'steps', items: [
        'Open the Compress PDF tool in Safari on your iPhone.',
        'Tap to choose a file and select your PDF from the Files app or iCloud Drive.',
        'Pick a compression level — light keeps text and images crisp, while heavier compression makes the smallest file.',
        'Tap compress and check the new file size.',
        'Download the smaller PDF back to your device and share it from the Files app.',
      ] },
      { type: 'p', text: 'This works even for a document that arrived as an email attachment: save it to Files first, then open it in the compressor.' },
      { type: 'h2', text: 'Using the built-in Files Quick Action' },
      { type: 'p', text: 'For a very quick fix with no settings, open the Files app, long-press the PDF, tap Quick Actions, then Optimize File Size. It replaces the file with a smaller version and needs no app at all. Because it overwrites the original, duplicate the PDF first if you want to keep the uncompressed copy.' },
      { type: 'h2', text: 'Getting under a specific size limit' },
      { type: 'p', text: 'If a form or email requires, say, under 1 MB, start with light compression and check the result. If it is still too large, step up to a heavier level. Preview the output at 100% zoom before sending to make sure the text is still sharp.' },
      { type: 'h2', text: 'Start small at the source' },
      { type: 'p', text: 'If even strong compression will not get the file small enough, the fastest win is usually at the source: remove unneeded pages, delete large inserted images, and for scanned documents re-scan at lower resolution and in grayscale. Compressing then becomes a final polish instead of a battle.' },
    ],
    faqs: [
      { q: 'How do I reduce PDF file size on my iPhone for free?', a: 'Open a browser-based compressor in Safari, load the PDF, choose a compression level, and download the smaller file. No app installation needed.' },
      { q: 'Does the iPhone have a built-in PDF compressor?', a: 'The Files app includes an Optimize File Size Quick Action that compresses a PDF, though it provides no quality control and overwrites the original.' },
      { q: 'Does compressing a PDF on iPhone lose quality?', a: 'Light compression keeps text and images crisp. Heavier compression can soften scanned images, so preview the result before sending it.' },
      { q: 'Can I compress a PDF that arrived as an email attachment?', a: 'Yes. Save the attachment to the Files app first, then open it in a browser-based compressor to shrink it.' },
      { q: 'Is my PDF uploaded to a server when I compress it?', a: 'No. When the compression runs in your browser, your document is processed locally on your iPhone and never leaves your device.' },
    ],
    related: ['how-to-compress-a-pdf-on-iphone', 'how-to-reduce-pdf-file-size-on-mac', 'how-to-compress-a-pdf-under-1mb', 'how-to-reduce-pdf-file-size-to-100kb'],
  },
];