import type { BlogPost } from '../types';

export const newPosts5: BlogPost[] = [

  // Article 1: How to Merge PDF Files on Mac
  {
    slug: 'how-to-merge-pdf-files-on-mac',
    title: 'How to Merge PDF Files on Mac (Free, No Adobe)',
    description: 'Combine two or more PDFs into one file on a Mac for free. Use Preview or a browser-based merger — no Adobe, no subscription, no uploads.',
    keyword: 'how to merge pdf files on mac',
    category: 'Merging & Organizing',
    published: '2026-09-01',
    tool: 'merge-pdf',
    blocks: [
      { type: 'p', text: 'A PDF that needs to travel together arrives in parts: an emailed contract, a scanned signature page, a report you exported from a spreadsheet. Your Mac ships with Preview, which can combine PDFs — but the process turns painful once you get past two files. Either way, you can merge PDF files on a Mac for free, without Adobe Acrobat or a subscription.' },
      { type: 'p', text: 'Here are the two ways to merge PDF files on a Mac: the built-in Preview method for quick jobs, and a browser-based merger for anything bigger.' },
      { type: 'h2', text: 'The built-in way: merge PDFs with Preview' },
      { type: 'p', text: 'Preview is the PDF tool that comes with macOS, and it can merge two PDFs. It is a manual, drag-and-drop process:' },
      { type: 'steps', items: [
        'Open the first PDF by double-clicking it in Finder.',
        'Choose View > Thumbnails so the page thumbnails appear in the sidebar.',
        'Double-click the second PDF to open it in its own window.',
        'In the second window\u2019s sidebar, select the thumbnails and drag them into the first window\u2019s sidebar at the position you want.',
        'Choose File > Export, name the combined document, and save it.',
      ] },
      { type: 'p', text: 'This is fine for a one-off, two-file merge. The moment you combine three or more documents — or need to re-order pages after the fact — the dragging gets tedious, and it is easy to drop a page in the wrong spot.' },
      { type: 'callout', title: 'Keep the originals until you save', text: 'Preview\u2019s Export writes a new file and leaves your source PDFs untouched, so a mistake is easy to redo. Use Export rather than Save, which would modify the file you opened.' },
      { type: 'h2', text: 'Merge PDFs on a Mac in your browser' },
      { type: 'p', text: 'When you need one clean file from several PDFs, a browser-based merger is faster than Preview and needs no installation:' },
      { type: 'steps', items: [
        'Open the Merge PDF tool in Safari or Chrome on your Mac.',
        'Drag your PDFs from Finder into the tool, or click to browse and select them — you can add as many as you need.',
        'Drag the thumbnails to set the order. The order you see is the order in the final file.',
        'Click Merge and download the combined PDF.',
      ] },
      { type: 'p', text: 'The whole job runs locally in your browser tab. Your documents never have to leave your Mac, which matters when you are combining contracts, payslips, or anything personal.' },
      { type: 'h2', text: 'Does merging reduce the quality of a PDF?' },
      { type: 'p', text: 'No — a correct merge copies each page into the new document without re-encoding it. Text stays selectable, images stay sharp, and links and form fields survive. If a merge returns a PDF where you can no longer select text, the tool rasterised your pages into flat images; switch to one that keeps the PDF structure intact.' },
      { type: 'h2', text: 'Merging scans and images with your PDFs' },
      { type: 'p', text: 'The merge tool expects PDFs. If one of your files is actually a scanned JPG or an iPhone HEIC photo, convert that image into a PDF first, then merge it with the rest — so a photographed signature or diagram sits exactly where it should in the combined document.' },
      { type: 'h2', text: 'Check the result before you send it' },
      { type: 'p', text: 'Once merged, flip through the finished PDF to confirm the pages are in the right order and nothing is missing, and keep the source files until you are sure. If the combined file comes out too large to email, compress it after merging rather than re-doing the whole merge.' },
    ],
    faqs: [
      { q: 'Can I merge PDF files on a Mac for free?', a: 'Yes. Preview (built into macOS) merges two PDFs by dragging thumbnails, and a browser-based merger combines any number of files with no installation and no account.' },
      { q: 'How do I merge PDFs on a Mac without Preview?', a: 'Use a browser-based merger in Safari or Chrome. It accepts all your PDFs at once, lets you reorder them, and produces one file in a single step.' },
      { q: 'Does merging PDFs lose quality on a Mac?', a: 'No. A correct merge copies each page without re-encoding it, so text, images, and links keep their original quality.' },
      { q: 'Can I add scanned images to a merged PDF?', a: 'Yes. Convert a scanned JPG or HEIC photo to a PDF first, then merge it with your other PDFs.' },
      { q: 'Is a merged PDF uploaded to a server?', a: 'No. When the merge runs in your browser, your documents are processed locally on your Mac and never leave your device.' },
    ],
    related: ['how-to-merge-pdf-files', 'how-to-merge-pdf-files-on-windows', 'how-to-combine-scanned-documents-into-one-pdf', 'how-to-create-a-pdf-from-multiple-file-types'],
  },

  // Article 2: How to Sign a PDF on a Chromebook
  {
    slug: 'how-to-sign-a-pdf-on-chromebook',
    title: 'How to Sign a PDF on a Chromebook (Free, In-Browser)',
    description: 'Add your signature to a PDF on a Chromebook for free with no app to install. Draw, type, or upload your signature right in Chrome.',
    keyword: 'how to sign a pdf on chromebook',
    category: 'Editing & Signing',
    published: '2026-09-01',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'A permission slip, a consent form, or an agreement arrives as a PDF on your Chromebook and needs your signature. Chromebooks do not run desktop PDF editors the way Windows or Mac do, and the built-in Chrome PDF viewer cannot sign anything. The good news: signing a PDF on a Chromebook is one of the easiest PDF jobs out there, because everything happens in the browser you already have open.' },
      { type: 'p', text: 'Here is how to sign a PDF on a Chromebook for free, with no apps to install and no account to create.' },
      { type: 'h2', text: 'Why the built-in viewer is not enough' },
      { type: 'list', items: [
        'Chrome\u2019s PDF viewer opens and reads documents but has no signing tool',
        'ChromeOS ships without a bundled PDF editor that adds signatures',
        'Shopping the Play Store for a PDF app usually lands on a subscription or a watermark',
      ] },
      { type: 'callout', title: 'A browser tab is the right tool', text: 'A browser-based signing tool runs in Chrome on any Chromebook — nothing to install, nothing to pay for, and your document is processed on the device itself, so a medical or legal form never leaves your hands.' },
      { type: 'h2', text: 'Sign a PDF on your Chromebook in Chrome' },
      { type: 'steps', items: [
        'Open the Sign PDF tool in the Chrome browser on your Chromebook.',
        'Click to choose a file and pick your PDF from the Files app, Google Drive, or your Downloads folder.',
        'Choose how to sign — draw with your trackpad, touchscreen, or a connected mouse; type your name in a script font; or upload a saved image of your signature.',
        'Drag the signature onto the signature line and size it to fit.',
        'Download the signed PDF to your Downloads folder and send it back.',
      ] },
      { type: 'p', text: 'If the PDF has fillable fields — checkboxes, dropdowns, text boxes — fill those in the same pass before adding your signature, so the whole form is complete in one download.' },
      { type: 'h2', text: 'Is a Chromebook signature legally binding?' },
      { type: 'p', text: 'Yes — electronic signatures carry the same legal weight as handwritten ones under laws like the US ESIGN Act and UETA, as long as you sign with intent. For everyday agreements, consent forms, and approvals, an electronic signature drawn in a browser tool is valid. If a specific document genuinely requires a handwritten signature or a notary, the other party will tell you; sign on paper in that case.' },
      { type: 'h2', text: 'Build a signature you can reuse' },
      { type: 'p', text: 'Rather than redrawing your signature for every form, upload a clear photo of your signature once and reuse it whenever a new PDF needs signing. Straighten and crop the photo before uploading so the background is clean and the pen strokes are dark.' },
      { type: 'h2', text: 'Signing forms that were scanned' },
      { type: 'p', text: 'If the PDF is a scanned page, you sign it the same way — the signature is placed as an image on top of the page and saved into the file. Just position it carefully on the line, because there is no form field to snap it into place.' },
    ],
    faqs: [
      { q: 'Can I sign a PDF on a Chromebook for free?', a: 'Yes. A browser-based signing tool runs in Chrome with no installation, no account, and no charge — draw, type, or upload your signature and download the signed file.' },
      { q: 'Does a Chromebook have a built-in PDF signer?', a: 'No. The built-in Chrome PDF viewer reads documents but cannot add a signature. A browser-based tool adds that capability with nothing to install.' },
      { q: 'Is an electronic signature on a Chromebook legally binding?', a: 'Yes. Under the US ESIGN Act and UETA, electronic signatures are as valid as handwritten ones when you sign with intent.' },
      { q: 'Where does the signed PDF go on my Chromebook?', a: 'It downloads to your Downloads folder, where you can open it in the Files app, attach it to an email, or move it to Google Drive.' },
      { q: 'Can I reuse the same signature on other PDFs?', a: 'Yes. Upload a photo of your signature once and reuse it on any future document you need to sign.' },
    ],
    related: ['how-to-sign-a-pdf-on-windows', 'how-to-edit-a-pdf-on-a-chromebook', 'how-to-sign-a-pdf-electronically-for-free', 'how-to-fill-out-a-pdf-form'],
  },

  // Article 3: How to Convert PDF to JPG on iPhone
  {
    slug: 'how-to-convert-pdf-to-jpg-on-iphone',
    title: 'How to Convert PDF to JPG on iPhone (Free, No App)',
    description: 'Turn PDF pages into JPG images on your iPhone for free in Safari. Export each page as a crisp, shareable photo — no app install.',
    keyword: 'how to convert pdf to jpg on iphone',
    category: 'Converting',
    published: '2026-09-01',
    tool: 'pdf-to-jpg',
    blocks: [
      { type: 'p', text: 'A PDF holds several pages of a document, but sometimes you need just one page as a plain JPG — to post on social media, paste into a message, or edit in Markup. The iPhone has no built-in way to turn a PDF into JPG images, and many "PDF converter" apps bury that feature behind a subscription. You do not need any of that.' },
      { type: 'p', text: 'Here is how to convert a PDF to JPG on your iPhone for free, right in Safari.' },
      { type: 'h2', text: 'Your options on an iPhone' },
      { type: 'list', items: [
        'The Files app can combine JPGs into a PDF but cannot do the reverse',
        'Screenshotting pages one by one is slow and lowers quality',
        'Many App Store converters are free only for a preview, then paywalled',
      ] },
      { type: 'callout', title: 'Safari converts in place', text: 'A browser-based PDF to JPG tool runs in Safari on your iPhone — no app download, no account, and the conversion happens on your device, so the document never has to be uploaded.' },
      { type: 'h2', text: 'Convert a PDF to JPG on iPhone in Safari' },
      { type: 'steps', items: [
        'Open the PDF to JPG tool in Safari on your iPhone.',
        'Tap to choose a file and select your PDF from the Files app, iCloud Drive, or an email attachment you saved to Files.',
        'Pick a format (JPG or PNG) and a quality setting — high for printing, standard for sharing on screen.',
        'Tap convert. Each page of the PDF becomes its own image.',
        'Download the images, which arrive bundled in a ZIP, and open them in the Files app.',
      ] },
      { type: 'p', text: 'From there you can share a single page as a photo, attach it to an email, or open it in Markup for a quick annotation.' },
      { type: 'h2', text: 'Scanned PDFs convert just the same' },
      { type: 'p', text: 'If the PDF is a scan of a printed page, conversion works identically — the scanned page simply becomes a JPG. This is handy for sending one page of a multi-page contract to someone who only needs the last sheet, or for pulling a printed receipt into an expense app as an image.' },
      { type: 'h2', text: 'When to use JPG instead of keeping the PDF' },
      { type: 'table', head: ['Use JPG when', 'Use PDF when'], rows: [
        ['Sharing a single page as a photo', 'Sending the whole document'],
        ['Posting to social media or a chat', 'Submitting forms or portals'],
        ['Editing a page in Markup or a photo app', 'Keeping text selectable and searchable'],
        ['Archiving a photo-like scan', 'Printing or legal archives'],
      ] },
      { type: 'h2', text: 'Getting the quality you need' },
      { type: 'p', text: 'For screen sharing, the standard setting is plenty and keeps the file small. If you plan to print a page or zoom into fine detail, use the high-quality setting instead — text edges stay crisp rather than showing compression artefacts. Test your first conversion at 100% zoom before you choose a setting for the whole run.' },
    ],
    faqs: [
      { q: 'Can I convert a PDF to JPG on my iPhone for free?', a: 'Yes. A browser-based PDF to JPG tool runs in Safari with no app install and no account, exporting each page as an image.' },
      { q: 'Does the iPhone have a built-in PDF to JPG converter?', a: 'No. The Files app converts images into a PDF but not PDFs into images. A browser-based converter is the simplest free route.' },
      { q: 'Will converting a PDF to JPG lose quality?', a: 'The tool renders at a set quality. The high setting is sharp enough for printing; the standard setting is fine for screen sharing. Text edges stay crisp at the high setting.' },
      { q: 'Can I convert only one page of a PDF?', a: 'The converter turns every page into an image. To get a single page only, convert the file and then share just that one image from the downloaded ZIP.' },
      { q: 'Where do the converted images go on my iPhone?', a: 'They download into the Files app, where you can open, rename, or share them like any other image.' },
    ],
    related: ['how-to-convert-pdf-to-jpg-high-quality', 'how-to-convert-pdf-to-image-for-printing', 'how-to-convert-pdf-to-word-on-iphone', 'how-to-convert-a-photo-to-pdf-on-your-phone'],
  },

  // Article 4: How to Password Protect a PDF on iPhone
  {
    slug: 'how-to-password-protect-a-pdf-on-iphone',
    title: 'How to Password Protect a PDF on iPhone (Free)',
    description: 'Lock a PDF with a password on your iPhone for free. Protect contracts and statements in Safari — no app download required.',
    keyword: 'how to password protect a pdf on iphone',
    category: 'Security & Privacy',
    published: '2026-09-02',
    tool: 'protect-pdf',
    blocks: [
      { type: 'p', text: 'A bank statement, a signed contract, or a copy of your passport is about to leave your iPhone as a PDF. Before you hit send, lock it with a password. iOS does not include a way to password protect a PDF — the Files app cannot encrypt — and most PDF apps gate the feature behind a paid plan. A browser tab can do it for free in under a minute.' },
      { type: 'p', text: 'Here is how to password protect a PDF on your iPhone without installing anything.' },
      { type: 'h2', text: 'Why your iPhone has no built-in option' },
      { type: 'list', items: [
        'The Files app opens and shares PDFs but cannot set a password',
        'Printing to PDF on iOS creates a file but does not encrypt it',
        'Most iOS PDF apps offer protection only in a paid tier',
      ] },
      { type: 'callout', title: 'Real encryption, in Safari', text: 'A browser-based Protect PDF tool applies real PDF encryption locally on your iPhone — the same AES-256 strength used for bank documents — with no app download and nothing uploaded to a server.' },
      { type: 'h2', text: 'Password protect a PDF on iPhone in Safari' },
      { type: 'steps', items: [
        'Open the Protect PDF tool in Safari on your iPhone.',
        'Tap to choose a file and select your PDF from the Files app, iCloud Drive, or an email attachment saved to Files.',
        'Type a strong password — at least 12 characters with upper and lower case, numbers, and symbols.',
        'Tap protect and download the encrypted PDF back to your iPhone.',
      ] },
      { type: 'p', text: 'Anyone who opens the file afterwards is asked for the password before they can see the contents — on an iPhone, a Mac, in Adobe Reader, or on a Windows PC — because PDF password protection is part of the format itself.' },
      { type: 'h2', text: 'Share the password separately' },
      { type: 'p', text: 'The password only helps if it does not travel with the file. Send the encrypted PDF by email and the password by text, phone call, or a messaging app — a different channel — and never include the password in the file name.' },
      { type: 'h2', text: 'Choose a password that is strong and memorable' },
      { type: 'p', text: 'Safari offers Password AutoFill, so you can generate the PDF\u2019s password and store it in iCloud Keychain — convenient and safe. For sensitive files, a passphrase of three or four random words is both strong and easy to remember. Avoid single dictionary words, birth years, phone numbers, and the passwords you already use for other accounts.' },
      { type: 'h2', text: 'There is no recovery if you forget it' },
      { type: 'p', text: 'If the password is lost, there is no legitimate way to open the document again — a locked PDF you cannot open is no good to anyone. Keep an unlocked copy of the original somewhere safe in your own storage, and store the password in Keychain or a password manager. Two records: the protected file for sending, the original for yourself.' },
    ],
    faqs: [
      { q: 'Can I password protect a PDF on my iPhone for free?', a: 'Yes. A browser-based Protect PDF tool runs in Safari and applies real AES-256 encryption with no app install, no account, and no upload.' },
      { q: 'Does the iPhone have a built-in PDF password tool?', a: 'No. The Files app cannot encrypt PDFs and iOS offers no native way to set a PDF password. A browser-based tool is the free route.' },
      { q: 'Can the recipient open a protected PDF on any device?', a: 'Yes. Password protection is part of the PDF standard, so the file prompts for the password in Preview on Mac, Adobe Reader, Chrome, and on Windows.' },
      { q: 'What if I forget the PDF password?', a: 'There is no recovery mechanism. Keep an unlocked backup copy of the original document and store the password in iCloud Keychain or a password manager.' },
      { q: 'Is my PDF or password uploaded to a server?', a: 'No. The encryption runs in your browser, so the document and the password are processed on your iPhone and never transmitted.' },
    ],
    related: ['how-to-password-protect-a-pdf', 'how-to-password-protect-a-pdf-without-adobe', 'how-to-remove-a-password-from-a-pdf', 'how-to-share-a-pdf-securely'],
  },

  // Article 5: How to Split a PDF on Mac
  {
    slug: 'how-to-split-a-pdf-on-mac',
    title: 'How to Split a PDF on Mac (Free, No Adobe)',
    description: 'Pull pages out of a PDF on a Mac for free. Extract a page range into its own file in your browser — no Adobe and no install.',
    keyword: 'how to split a pdf on mac',
    category: 'Merging & Organizing',
    published: '2026-09-01',
    tool: 'split-pdf',
    blocks: [
      { type: 'p', text: 'Your Mac holds a 24-page PDF and you need to hand one colleague the first five pages and another the rest — or you just want to pull a single page out of a big document. Splitting is the least obvious PDF task on macOS: Preview can do it, but the process is manual and easy to get wrong. There is a browser route that is simpler and safer.' },
      { type: 'p', text: 'Here is how to split a PDF on a Mac — what Preview can and cannot do, and the one-step browser method.' },
      { type: 'h2', text: 'What Preview can and cannot do' },
      { type: 'p', text: 'Preview has no "split" command. The workaround is to open the PDF, delete every page you do not want, and save what is left as a new file. That works, but it has real limits:' },
      { type: 'list', items: [
        'You must duplicate the file first, or you risk editing the original by accident',
        'Each output file is one filtered selection, so a multi-part split means repeating the whole delete-and-save routine',
        'It is easy to save a half-deleted file if you forget to duplicate before you start',
      ] },
      { type: 'callout', title: 'The safer route is a browser split', text: 'A browser-based Split PDF tool takes a page range you choose, lets you preview exactly those pages, and produces a brand-new file — leaving the original completely untouched.' },
      { type: 'h2', text: 'Split a PDF on your Mac in the browser' },
      { type: 'steps', items: [
        'Open the Split PDF tool in Safari or Chrome on your Mac.',
        'Drag your PDF from Finder into the tool, or click to browse and select it.',
        'Enter the pages for the new file — a single page (9), a range (1-5), or a mixture (1-3, 5, 7-10).',
        'Review the preview to confirm exactly those pages are selected.',
        'Click Split and download the new PDF.',
      ] },
      { type: 'p', text: 'The original file is never modified, so you can run the tool again with different ranges and build as many separate documents as you need — pages 1-5 saved as "Part 1", pages 6-24 as "Part 2", and so on.' },
      { type: 'h2', text: 'Extracting a single page or a few pages' },
      { type: 'p', text: 'To pull one page out of a long document — say page 9 of a 50-page report — enter that single number and you get a one-page PDF ready to email. The output keeps the original page content as real text, so quality stays identical and the extracted pages remain selectable and searchable.' },
      { type: 'h2', text: 'How the Preview manual method compares' },
      { type: 'p', text: 'If you prefer to stay in Preview: open the PDF, choose View > Thumbnails, duplicate the file first, select the unwanted thumbnails and press Delete, then use File > Export to save what remains under a clear name. The browser approach does the same job with less risk of saving a half-deleted file, especially when you split on several ranges.' },
      { type: 'h2', text: 'After you split' },
      { type: 'p', text: 'Name each output file clearly when you download it, and flip through it once to confirm the pages are the ones you meant. If you later need the separate parts back together, you can merge PDFs on the same Mac in a single step.' },
    ],
    faqs: [
      { q: 'Can I split a PDF on a Mac for free?', a: 'Yes. Preview can export selected pages to a new file, and a browser-based Split PDF tool extracts a page range into its own PDF with no installation and no account.' },
      { q: 'Does Preview have a split PDF option?', a: 'There is no direct split command, but you can delete the pages you do not want in a duplicated copy and export the rest as a new PDF. For real control, a browser tool is easier.' },
      { q: 'Does splitting a PDF reduce quality?', a: 'No. The selected pages are copied into a new document without re-encoding, so the text stays sharp, selectable, and searchable.' },
      { q: 'Can I extract non-consecutive pages into one file?', a: 'Yes. Enter ranges like 1-3, 5, 7-10 to pull exactly those pages into a single new PDF in one pass.' },
      { q: 'Will splitting change my original PDF?', a: 'No. The browser tool creates a new file and leaves the original untouched, so you can split on different ranges as many times as you like.' },
    ],
    related: ['how-to-split-a-pdf-into-separate-pages', 'how-to-split-a-pdf-by-file-size', 'how-to-merge-pdf-files-on-mac', 'how-to-delete-pages-from-a-pdf'],
  },

  // Article 1: Word vs PDF — which format to send
  {
    slug: 'word-vs-pdf-which-format-to-send',
    title: 'Word vs PDF: Which Format Should You Send?',
    description: 'Word or PDF? Know when a .docx is expected to be edited and when a locked PDF is safer, so every file you send arrives looking exactly right.',
    keyword: 'word vs pdf which format to send',
    category: 'Troubleshooting',
    published: '2026-09-12',
    blocks: [
      { type: 'p', text: 'You finish a document and reach for Send. Before you attach the file you have to answer one small question that decides the whole experience for the person on the other end: do they get a Word document or a PDF? It sounds trivial, but it is the difference between a quick edit and a hour of formatting suddenly moving around.' },
      { type: 'p', text: 'Here is the short version: send a Word file when the receiver will continue working on it, and send a PDF when the document is final. Now here is why that rule of thumb makes sense.' },
      { type: 'h2', text: 'The short answer' },
      { type: 'p', text: 'A Word document (.docx) is a living file \u2014 it is built for text to be typed, tracked, and changed. A PDF is a finished snapshot; it locks down the layout, the fonts, and the page breaks so it looks the same on every device. If you want the receiver to jump in and refine the text, Word. If you want them to see exactly what you wrote, exactly once, PDF.' },
      { type: 'callout', title: 'When in doubt, ask', text: 'For a document that matters \u2014 a contract, a submission, a brief \u2014 it costs one sentence to ask \u201cdo you need to edit this or just review it?\u201d That answer removes all the guesswork.' },
      { type: 'h2', text: 'What a Word document is good for' },
      { type: 'p', text: 'Word is the right call when the document is still alive. Co-authors can use Track Changes to leave edits a reviewer can accept or reject, margin comments explain why a paragraph changed, and correcting a typo is a double-click away instead of a full resend.' },
      { type: 'list', items: [
        'Real-time collaboration: multiple people edit the same file and see each other\u2019s changes',
        'Track Changes and comments for structured feedback and approvals',
        'Cheap, instant corrections when you (or the receiver) spot a mistake',
        'Easy conversion to templates, mail merges, or future reuse',
      ] },
      { type: 'h2', text: 'What a PDF is good for' },
      { type: 'p', text: 'A PDF is the right call when the document is finished and needs to look finished. Fonts are embedded, so a receiver without your fonts still sees your exact layout. Page breaks stay where you placed them. And because a PDF is not casually editable, a contract or invoice is far less likely to be silently changed.' },
      { type: 'list', items: [
        'Locked layout: the file looks identical on Windows, Mac, phone, and printer',
        'Universal: everyone can open a PDF in a free reader, with or without Word installed',
        'Presentable for sign-offs, submissions, and clients \u2014 nothing is loose',
        'Safe for sensitive pages once protected or signed, so content cannot be amended easily',
      ] },
      { type: 'h2', text: 'Three questions to ask before you hit send' },
      { type: 'steps', items: [
        'Does the receiver need to change the words? If yes, send Word. If they only read, approve, or print, send PDF.',
        'Is this final, signed, or legally meaningful? Send a PDF \u2014 ideally password-protected or signed \u2014 so nobody can quietly alter it.',
        'Does it need to look identical everywhere? Resumes, brochures, and reports go as PDF so spacing and fonts survive the trip.',
      ] },
      { type: 'p', text: 'One warning: a Word document can change appearance dramatically on another machine because the receiver lacks your fonts or uses a different Office version. If the visual result matters more than the ability to edit, PDF wins every time.' },
      { type: 'h2', text: 'Sending a Word file that is too heavy' },
      { type: 'p', text: 'Sometimes a large Word file gets stuck at the inbox \u2014 the doc is full of high-resolution pictures and breezes past email size limits. In that case the fix is to compress or convert cleanly rather than send a broken attachment. Turning a Word file into a PDF often shrinks it noticeably, and a compression pass can shrink a PDF further while keeping the text tidy.' },
      { type: 'p', text: 'The format you send is really a promise about what happens next. Send Word to keep the conversation going. Send PDF to declare the document done.' },
    ],
    faqs: [
      { q: 'When should I send a Word document instead of a PDF?', a: 'Send Word whenever the receiver will continue editing, reviewing with Track Changes, or co-authoring. If they only need to read, print, or approve, a PDF is the safer choice.' },
      { q: 'Why does my Word document look different on other computers?', a: 'Word files depend on the receiver having the same fonts and a compatible Office version. A PDF embeds its fonts and locks the layout, so it looks identical everywhere.' },
      { q: 'Should a resume be a PDF or Word?', a: 'A resume should usually be a PDF so the layout and fonts survive. Send a Word version only when the job posting explicitly requests it, for example for applicant-tracking systems.' },
      { q: 'Is a contract safer as a Word file or a PDF?', a: 'A PDF is safer for a final contract because it is far harder to edit silently. Pair it with a signature and password protection to make changes effectively impossible.' },
      { q: 'How do I make a Word file small enough to email?', a: 'Convert it to PDF, which often recompresses images, and then compress the PDF if needed. A browser-based converter handles both steps without installing software.' },
    ],
    related: ['pdf-vs-pdfa-what-is-the-difference', 'how-to-choose-between-sending-a-pdf-or-a-word-document', 'why-does-my-pdf-look-different-on-another-device', 'how-to-convert-word-to-pdf-without-losing-formatting'],
  },

  // Article 2: Merge vs split a PDF
  {
    slug: 'merge-vs-split-pdf',
    title: 'Merge vs Split a PDF: Which One Do You Need?',
    description: 'Decide whether to merge separate PDFs into one file or split a large PDF into individual pages. Compare both tasks and pick the right free tool.',
    keyword: 'merge vs split pdf',
    category: 'Merging & Organizing',
    published: '2026-09-12',
    tool: 'merge-pdf',
    blocks: [
      { type: 'p', text: 'Practically every PDF task is either combining or dividing. You have three separate invoices that need to be one attachment, or one giant scan that needs to become twelve individual pages. Merging and splitting are opposite operations with the same underlying idea: you decide how many files a document should be.' },
      { type: 'p', text: 'Here is how to tell which one you need, and how to do both without installing software.' },
      { type: 'h2', text: 'The short answer' },
      { type: 'p', text: 'Merge PDFs when several documents belong together \u2014 a contract plus its addendums, a folder of receipts for an expense claim, or the scanned pages of one report. Split a PDF when one file actually contains several documents \u2014 the pages should travel separately, different sections go to different people, or a single large file is simply unwieldy.' },
      { type: 'table', head: ['Task', 'What you do', 'When you do it'], rows: [
        ['Merge', 'Combine two or more PDFs into a single file', 'Invoices, scans, agreements, or any set of files that one reader needs as one bundle'],
        ['Split', 'Break one PDF into page ranges or single pages', 'Sections for different recipients, oversized uploads, or extracting a few pages from a large scan'],
      ] },
      { type: 'callout', title: 'Order is the whole job', text: 'When you merge, the final document is only as good as the page order you configure. Almost every merge mistake is a wrong-it-order problem, so arrange your files before you combine \u2014 and reuse the same order habit when you split by ranges.' },
      { type: 'h2', text: 'When to merge PDFs' },
      { type: 'p', text: 'Merging is for turning a mess of loose files into one clean document. Email attachments have limits and are hard to keep organized; a single combined PDF travels more cleanly, prints in the right order, and gives the reader one thing to open.' },
      { type: 'steps', items: [
        'Open the Merge PDF tool in your browser.',
        'Add all the PDFs you want combined \u2014 drag them in at once or browse to select them.',
        'Drag the files into the order they should appear in the final document.',
        'Combine and download. The result is one PDF with the pages in the order you set.',
      ] },
      { type: 'p', text: 'Merging works best on files that belong together. If you merge unrelated documents, the receiver ends up hunting for the part they need inside one large file \u2014 the exact problem splitting solves.' },
      { type: 'h2', text: 'When to split a PDF' },
      { type: 'p', text: 'Splitting is for breaking a big file into bite-size pieces. Teachers split a worksheet per class, accountants split one month per statement, and anyone with a 100-page scan splits out just the pages they actually need to send.' },
      { type: 'steps', items: [
        'Open the Split PDF tool in your browser.',
        'Upload your PDF, or use the same tool to choose a page range viewer first.',
        'Split by page ranges (for example pages 1\u20134 for one recipient) or extract every page as its own file.',
        'Download the resulting PDFs \u2014 either numbered individual files or the ranges you picked.',
      ] },
      { type: 'h2', text: 'One file or many: pick by audience' },
      { type: 'p', text: 'Think about the person on the receiving end. If one reader needs everything, merge. If different people need different parts \u2014 or an online form only accepts a single small PDF \u2014 split. The same logic covers most decisions: merge by reader, split by destination.' },
      { type: 'p', text: 'Both tasks take under a minute in a browser and run entirely on your device, so the actual pages never leave your computer. Whichever direction your document needs to go, you are just rearranging how the pages are grouped.' },
    ],
    faqs: [
      { q: 'What is the difference between merging and splitting a PDF?', a: 'Merging combines several PDFs into one file. Splitting breaks one PDF into multiple files by page range or single pages. You merge to bundle documents and split to divide them.' },
      { q: 'When should I merge PDF files?', a: 'Merge when several documents belong together \u2014 a contract with addendums, a folder of receipts, or new pages added to an existing report. One reader should get them as a single file.' },
      { q: 'When should I split a PDF?', a: 'Split when one file contains several documents, different sections go to different people, or an upload form demands a small single PDF. Splitting isolates just the pages you need.' },
      { q: 'Can I merge and split PDFs for free?', a: 'Yes. Browser-based merge and split tools run for free with no install and no account. They process the files locally, so your documents never get uploaded to a server.' },
      { q: 'Does merging or splitting change the quality of the pages?', a: 'No. Merging and splitting reassemble existing pages; the text and images inside them are untouched. Quality only changes if you recompress the content, which these tasks do not do.' },
    ],
    related: ['how-to-merge-pdf-files', 'how-to-split-a-pdf-into-separate-pages', 'combine-pdf-files-without-losing-quality', 'how-to-split-a-pdf-by-file-size'],
  },

  // Article 3: Remove a watermark from a PDF
  {
    slug: 'how-to-remove-a-watermark-from-a-pdf',
    title: 'How to Remove a Watermark from a PDF (Honestly, Safely)',
    description: 'A flattened watermark cannot be erased like a layer, but you can safely crop or cover it. Learn the honest, free ways to handle a watermarked PDF.',
    keyword: 'remove watermark from pdf',
    category: 'Security & Privacy',
    published: '2026-09-12',
    tool: 'redact-pdf',
    blocks: [
      { type: 'p', text: 'Automatic \u201cwatermark remover\u201d tools usually make a promise they cannot keep. Most real-world watermarks are flattened into the page as a permanent image or text, so there is no invisible layer to delete. The honest answer depends on what kind of watermark you are looking at, and what you are allowed to do with the document.' },
      { type: 'p', text: 'Here is what actually works, what does not, and how to handle a watermarked PDF without breaking the file.' },
      { type: 'h2', text: 'First: what kind of watermark is it?' },
      { type: 'list', items: [
        'A preview watermark \u2014 usually text like \u201cSAMPLE\u201d or \u201cPREVIEW\u201d diagonally across a free preview version, added by the sender so you download the original instead',
        'A burned-in logo or text \u2014 flattened into every page as part of the page image, which is how most exported watermarks end up',
        'A draggable object \u2014 one that is still a floating element in a PDF editor, which can be selected, moved, or switched off',
      ] },
      { type: 'p', text: 'Only the third type is trivially removable, and even then the PDF editor needs permissions to see it as an object. If the file is flattened \u2014 which exports and scanners almost always produce \u2014 there is nothing behind the watermark to unlayer.' },
      { type: 'h2', text: 'Why a flattened watermark will not just go away' },
      { type: 'p', text: 'A PDF page is a canvas. When a watermark is flattened, its pixels are burnt into that canvas, exactly like ink on paper. No amount of \u201cremoving\u201d finds a clean page underneath, because the watermark is not sitting on top \u2014 it is part of the page. That is why free online \u201cwatermark removers\u201d tend to blur or smear the area rather than restore clean content.' },
      { type: 'callout', title: 'Legal reality check', text: 'If a document was watermarked to prevent copying, removing the watermark to redistribute it may be a breach of the license, contract, or copyright. Removing a watermark from content you do not own is not a formatting trick \u2014 it is a decision with consequences. Only treat documents you are entitled to edit.' },
      { type: 'h2', text: 'The honest ways to handle it' },
      { type: 'h3', text: 'Option 1: Get the original instead' },
      { type: 'p', text: 'Preview watermarks exist precisely to push you toward the paid or registered version. The fastest route to a clean PDF is usually the sender\u2019s download button. If you are entitled to a clean version, generating or asking for it beats every editing workaround.' },
      { type: 'h3', text: 'Option 2: Crop the watermark out' },
      { type: 'p', text: 'If the watermark sits only in a margin \u2014 a corner logo, a footer label \u2014 cropping the page to that region removes it cleanly. The catch is you lose that part of the page. It only makes sense when the watermark lives somewhere you can spare.' },
      { type: 'h3', text: 'Option 3: Cover it with an opaque box (redaction)' },
      { type: 'p', text: 'When the watermark crosses the middle of the page, the practical free answer is to completely erase the affected area by painting over it. Redacting \u2014 which the site\u2019s Redact PDF tool does, leaving the covered rectangles truly gone from the file \u2014 removes not only the watermark but anything hiding under it.' },
      { type: 'h2', text: 'How to cover a watermark for free' },
      { type: 'steps', items: [
        'Open the Redact PDF tool in your browser.',
        'Upload the watermarked PDF.',
        'Draw a rectangle over each watermark, covering it fully.',
        'Apply the redaction so the covered areas are permanently removed.',
        'Download the PDF \u2014 the watermark is gone along with the covered region.',
      ] },
      { type: 'p', text: 'Redacting works and, unlike blur-based \u201cremovers\u201d, it removes the pixels entirely so the result is clean and the protected part cannot be recovered from the file. The trade-off is real: anything beneath the rectangle goes with it.' },
      { type: 'h2', text: 'Avoid \u201cwatermark remover\u201d apps' },
      { type: 'p', text: 'Tools that promise to undo flattened watermarks usually upload your document to their servers, then deliver a blurred, low-quality page. That combination \u2014 your file leaving the machine, and the result being useless \u2014 is the worst of both worlds. If you are entitled to a clean copy, the original is the only good outcome; if you are not, no tool should be doing this for you.' },
      { type: 'p', text: 'Handle the watermarks you are allowed to handle by cropping or redacting locally in the browser, and skip any service that claims to reverse flattening.' },
    ],
    faqs: [
      { q: 'Can a watermark actually be removed from a PDF?', a: 'Only if it is still a floating object the editor can select, which is rare. Most watermarks are flattened into the page image, so they can only be cropped out or covered \u2014 not peeled off.' },
      { q: 'Is it safe to use a free online watermark remover?', a: 'Usually not. Most upload your document to their servers and return a blurred result. Redacting or cropping locally, with the file staying on your device, is safer and gives a cleaner outcome.' },
      { q: 'How do I remove a watermark without losing content?', a: 'You rarely can. If the watermark is in a margin, crop the page. If it crosses the content, redaction removes it but also erases everything under the rectangle. The only loss-free route is the original, unwatermarked version.' },
      { q: 'Is removing a watermark from a PDF legal?', a: 'Only for documents you are entitled to edit. Watermarks are often copyright or license protection, and removing them from someone else\u2019s content to redistribute it can be a breach of terms or law.' },
      { q: 'Why do watermark removers make the text blurry?', a: 'Because there is no clean content behind a flattened watermark, these tools guess and reconstruct the area, which smears the pixels. No software can recover ink that was never there.' },
    ],
    related: ['how-to-add-a-watermark-to-a-pdf', 'how-to-redact-a-pdf-properly', 'how-to-flatten-a-pdf', 'what-personal-data-is-hidden-in-your-pdf'],
  },

  // Article 4: Make a scanned PDF editable
  {
    slug: 'how-to-make-a-scanned-pdf-editable',
    title: 'How to Make a Scanned PDF Editable (Free, With OCR)',
    description: 'Scanned PDFs are just pictures of text. Use OCR to make them searchable and editable in your browser for free, without installing a desktop app.',
    keyword: 'make scanned pdf editable',
    category: 'Converting',
    published: '2026-09-12',
    tool: 'ocr-pdf',
    blocks: [
      { type: 'p', text: 'That 30-page scan of a signed contract is a picture of a document, not a document. You can click every word from here to breakfast and select nothing, because scanning a paper page produces an image, and an image cannot be searched, copied, or typed over. OCR \u2014 optical character recognition \u2014 is the step that turns those pictures of letters back into real, editable text.' },
      { type: 'p', text: 'Here is how to make a scanned PDF editable for free in your browser, and what to expect from the result.' },
      { type: 'h2', text: 'Why a scan is not editable' },
      { type: 'p', text: 'A scanner records light reflected off paper. Every letter becomes colored pixels, stored like a photo. Your computer sees the shape of an \u201cA,\u201d but it has no idea it is the letter A \u2014 so search finds nothing, copy finds nothing, and the text tools of a PDF editor have nothing to letter. Any tool that makes a scan \u201ceditable\u201d has to first recognize the shapes as characters.' },
      { type: 'h2', text: 'What OCR actually does' },
      { type: 'p', text: 'OCR software looks at the pixel shapes, matches them against letterforms, and outputs real text positioned where each character belongs. The invisible text layer then sits on top of the scan image. From that point the document is searchable, selectable, and able to be exported into formats that let you type over it, even though the original image stays in place underneath.' },
      { type: 'callout', title: 'Private by default', text: 'The best free OCR runs directly in your browser \u2014 the scan never leaves your machine, which matters when the text includes names, numbers, or anything confidential. Desktop-installed OCR is just as private; absolutely avoid free online OCR services that demand an upload.' },
      { type: 'h2', text: 'Make a scanned PDF editable in your browser' },
      { type: 'steps', items: [
        'Open the OCR PDF tool in your browser.',
        'Upload your scanned PDF.',
        'Choose the document language, run OCR, and let the tool recognize the text.',
        'Download the result \u2014 a version with searchable, selectable text overlaid on your scan.',
        'Copy, search, or export the text into a Word or PDF editor for further changes.',
      ] },
      { type: 'p', text: 'On a clean digital scan of typed pages, recognition is usually excellent \u2014 the text comes back searchable and accurate enough to copy whole paragraphs. On a blurry photo shot at an angle, expect mistakes; OCR quality tracks the quality of the image you feed it.' },
      { type: 'h2', text: 'Searchable vs. truly editable' },
      { type: 'h3', text: 'Searchable (invisible text layer)' },
      { type: 'p', text: 'This is what OCR typically delivers: the scan stays as an image, but a text layer lets you search, select, and copy. It is ideal for archives and long contracts, because the original page still looks exactly like the paper.' },
      { type: 'h3', text: 'Truly editable (rebuilt text)' },
      { type: 'p', text: 'To change the actual words \u2014 fix a typo, reword a sentence, restructure a paragraph \u2014 export the recognized text into a word processor or an editable PDF editor. You are now working with text, not pixels, so formatting can shift and needs a once-over.' },
      { type: 'h2', text: 'Tips for cleaner OCR results' },
      { type: 'list', items: [
        'Scan at 300 dpi or higher \u2014 more pixels per letter means fewer misreads',
        'Keep pages flat and square; skew and curl confuse recognition',
        'Use grayscale or black-and-white rather than harsh contrast photos',
        'Tell the tool the language \u2014 accented characters and scripts recognize far better when specified',
      ] },
      { type: 'h2', text: 'When OCR is not enough' },
      { type: 'p', text: 'Handwriting, dense tables, and faint carbon copies defeat most OCR. If the output is a mess of wrong words, do not fight it \u2014 a fresh scan at higher quality beats tweaking recognition settings. And if what you really need is a spreadsheet, skip the middle step and convert the tables directly once the text layer exists.' },
      { type: 'p', text: 'Scan first, OCR second, edit third. Recognize the pixels once, and your scan becomes another searchable, workable document in your library.' },
    ],
    faqs: [
      { q: 'Can a scanned PDF be made editable for free?', a: 'Yes. Browser-based OCR tools recognize the text and add a searchable, selectable layer for free. Exporting that text into a Word or PDF editor lets you actually change the words.' },
      { q: 'What is the difference between searchable and editable?', a: 'Searchable means a text layer exists over the scan image so you can search, select, and copy. Truly editable means the text has been rebuilt as characters you can change in a word processor or editor.' },
      { q: 'How accurate is OCR on a scanned document?', a: 'On clean, flat 300-dpi scans of typed text it is usually very accurate. Blurry, skewed, or handwritten pages produce errors, so the quality of the scan largely determines the quality of the text.' },
      { q: 'Is my scanned PDF uploaded when I use a free OCR tool?', a: 'Only if you choose one that uploads. Many free OCR tools run entirely in the browser or on your device, so confidential pages never leave your computer \u2014 prefer those.' },
      { q: 'Can OCR read handwriting?', a: 'Generally poorly. Handwriting recognition is far less reliable than typed text. For handwritten scans, expect to correct the output manually or fall back to comparing the original page.' },
    ],
    related: ['how-to-make-a-scanned-pdf-searchable', 'what-is-ocr-and-how-does-it-work', 'how-to-copy-text-from-a-scanned-pdf', 'how-to-convert-a-scanned-document-to-pdf'],
  },

  // Article 5: Convert JPG to PDF on Android
  {
    slug: 'how-to-convert-jpg-to-pdf-on-android',
    title: 'How to Convert JPG to PDF on Android (Free, In-Browser)',
    description: 'Turn one photo or many JPGs into a single PDF on your Android phone for free. Combine and arrange images right in the browser, no app needed.',
    keyword: 'how to convert jpg to pdf on android',
    category: 'Converting',
    published: '2026-09-12',
    tool: 'jpg-to-pdf',
    blocks: [
      { type: 'p', text: 'A scanned document, a photo of a receipt, or a phone picture of a form \u2014 banks, portals, and application pages keep asking for a PDF when all you have is a JPG. On Android you can turn JPGs into a PDF without installing anything: the file manager handles a single photo, and a browser-based converter combines a whole folder into one proper PDF.' },
      { type: 'p', text: 'Here is how to convert JPG to PDF on Android for free, depending on how many images you need.' },
      { type: 'h2', text: 'Convert a single JPG with the built-in Files app' },
      { type: 'p', text: 'Android\u2019s Files app can turn one image into a PDF in a few taps with no third-party apps. It is perfect for a quick single file:' },
      { type: 'steps', items: [
        'Open the Files app on your Android phone.',
        'Navigate to the image you want, long-press it, and tap the overflow (three-dot) menu.',
        'Choose Print, which opens the system print screen.',
        'Change the Printer to \u201cSave as PDF\u201d and tap the PDF icon to save.',
        'Name the file and confirm \u2014 it is saved as a PDF in your Downloads folder.',
      ] },
      { type: 'p', text: 'This built-in route is handy but limited to one image at a time, and you cannot control the order, page size, or layout. For several photos, a browser-based converter is the better tool.' },
      { type: 'h2', text: 'Convert many JPGs into one PDF in your browser' },
      { type: 'p', text: 'When a folder of receipts or a multi-page scan needs to become a single PDF, open a converter in Chrome on your phone. It combines every image, lets you arrange the order, and downloads one clean file \u2014 no app, no account, and no uploads.' },
      { type: 'steps', items: [
        'Open the JPG to PDF tool in Chrome on your Android phone.',
        'Tap the upload area and pick the images from your gallery or Files, or share them into the tool.',
        'Drag the thumbnails to set the page order \u2014 the order you see is the order in the final PDF.',
        'Choose your page size and whether each image should fit the page.',
        'Convert and download the combined PDF to your Files app.',
      ] },
      { type: 'callout', title: 'Photos are bigger than they look', text: 'A phone camera produces huge JPGs. If you are converting photos of documents rather than the original files, the PDF inherits that bulk \u2014 a quick compression pass after converting keeps the email attachment small.' },
      { type: 'h2', text: 'JPG, PNG, or HEIC on Android' },
      { type: 'p', text: 'Most Android cameras shoot JPG, which converts cleanly. If your images came from an iPhone they may be HEIC, and some older Android tools refuse that format. A converter that accepts HEIC along with JPG and PNG saves you converting files twice.' },
      { type: 'h2', text: 'Keep the order straight' },
      { type: 'p', text: 'The one thing that makes or breaks an image-to-PDF job is order. When you combine several JPGs, arrange the thumbnails before converting \u2014 a receipt folder should run earliest to latest, and a scanned form should read top to bottom. Double-check the thumbnails in the converter before you download.' },
      { type: 'p', text: 'Your Android phone is already enough to produce a tidy PDF from JPGs. Use the built-in Files app for a single quick conversion, and a browser-based tool whenever several images need to become one document.' },
    ],
    faqs: [
      { q: 'How do I convert a JPG to PDF on Android for free?', a: 'Use the Files app\u2019s Print option with \u201cSave as PDF\u201d for a single image, or a browser-based converter to combine many JPGs into one PDF with no app install.' },
      { q: 'Can I combine several JPGs into one PDF on Android?', a: 'Yes. A browser-based JPG to PDF tool lets you select all your images, arrange the order, and download a single combined PDF in one step.' },
      { q: 'Does converting a JPG to PDF lose quality on Android?', a: 'No. The image is placed onto a PDF page at its original resolution, so text and details stay as sharp as the source photo.' },
      { q: 'Why is my JPG to PDF file so large?', a: 'Phone photos are high resolution, so their PDFs inherit the size. Compress the PDF after converting if the file will be emailed or limited to a small upload.' },
      { q: 'Are my photos uploaded when I convert JPG to PDF on Android?', a: 'No. When the conversion runs in your browser, your images are processed locally on your phone and never uploaded to a server.' },
    ],
    related: ['how-to-convert-jpg-to-pdf', 'how-to-convert-a-photo-to-pdf-on-your-phone', 'how-to-convert-jpg-to-pdf-on-windows', 'how-to-combine-images-into-one-pdf'],
  },
];
