import type { BlogPost } from '../types';

export const newPosts11: BlogPost[] = [
  // Article 1: How to Rotate a PDF on Mac
  {
    slug: 'how-to-rotate-a-pdf-on-mac',
    title: 'How to Rotate a PDF on Mac and Save (Free, Preview Tip)',
    description: 'Rotate a PDF page on Mac with Preview or in your browser and save the change for good. Fix sideways pages for free — no Acrobat needed.',
    keyword: 'how to rotate a pdf on mac',
    category: 'Merging & Organizing',
    published: '2026-09-10',
    tool: 'rotate-pdf',
    experience: 'I rotate scanned PDFs on my Mac constantly — flatbed scans always come out sideways. Preview can save rotations, which catches most people out, and a browser tool handles the rest.',
    blocks: [
      { type: 'p', text: 'A scanned PDF opens with the pages turned sideways, or a page is upside-down and you need it fixed before printing or sending. On a Mac you have two free routes: Preview can rotate and save pages directly, and a browser-based tool handles every case Preview cannot.' },
      { type: 'p', text: 'Here is how to rotate a PDF on a Mac for free and keep the rotation.' },
      { type: 'h2', text: 'Rotate and save with Preview (built in)' },
      { type: 'steps', items: [
        'Open the PDF in Preview on your Mac.',
        'Choose the page you want to rotate in the sidebar or thumbnail view.',
        'Click the rotate button in the toolbar, or press Command + R.',
        'Keep rotating until the page faces the right way.',
        'Choose File > Save (Command + S) to keep the rotation permanently.',
      ] },
      { type: 'p', text: 'The key step is File > Save. Many people rotate in Preview, close the window, and lose the change because Preview had only rotated the view. Saving writes the rotation into the file.' },
      { type: 'callout', title: 'Rotate one page or all pages', text: 'Select a single page in the sidebar to rotate just that page. With nothing selected, Command + R rotates every page in the document, which is perfect for a scan that came out uniformly sideways.' },
      { type: 'h2', text: 'Rotate in your browser when Preview is not enough' },
      { type: 'p', text: 'Preview handles single-file rotations well, but a browser-based rotate tool adds flexibility: rotating only certain pages while keeping others, processing multiple files, and writing a clean export in one step.' },
      { type: 'steps', items: [
        'Open the Rotate PDF tool in Safari or Chrome on your Mac.',
        'Drag your PDF into the tool, or click to browse.',
        'Pick the rotation angle — 90° left, 90° right, or 180°.',
        'Apply it to all pages or only the pages you select.',
        'Click rotate and download the corrected PDF.',
      ] },
      { type: 'p', text: 'The tool runs in your browser tab, so the PDF is processed on your Mac and never uploaded.' },
      { type: 'h2', text: 'Mixing portrait and landscape pages' },
      { type: 'p', text: 'Documents with mixed orientations need care. Rotating everything with Command + R ruins correctly-oriented pages. Instead, select only the offending pages in Preview or the browser tool, and rotate them individually. The result keeps portrait pages portrait and landscape pages landscape.' },
      { type: 'h2', text: 'Preview vs. a browser tool' },
      { type: 'table', head: ['Task', 'Preview', 'Browser tool'], rows: [
        ['Rotate and save one file', 'File > Save works', 'Also works'],
        ['Rotate a single page', 'Select in sidebar, then rotate', 'Select the page, then rotate'],
        ['Rotate every page', 'Command + R with nothing selected', 'Apply to all pages'],
        ['Multiple files at once', 'One file at a time', 'Batch several files'],
        ['Keep the original untouched', 'Save overwrites it', 'Creates a new download'],
      ] },
      { type: 'h2', text: 'Check before you print' },
      { type: 'list', items: [
        'Open the saved PDF and confirm the page faces the right way',
        'Verify mixed-orientation pages stayed consistent',
        'When printing, print from the saved copy, not the reopened scan',
        'Keep the original scan until the rotated version is verified',
      ] },
      { type: 'p', text: 'Between Preview\u2019s built-in rotation and a browser-based tool, fixing page orientation on a Mac is free and takes seconds. Save with Preview when you already have the file open, or use a rotate tool when you need finer control.' },
    ],
    faqs: [
      { q: 'How do I rotate a PDF on Mac for free?', a: 'Open the PDF in Preview, rotate with Command + R, then choose File > Save. Or use a browser-based rotate tool for more control. Both are free.' },
      { q: 'Why does Preview lose my rotation when I close it?', a: 'Rotating changes the on-screen view until you save. Choose File > Save (Command + S) after rotating to write the change into the file.' },
      { q: 'Can I rotate just one page in a PDF?', a: 'Yes. In Preview, select that page in the sidebar before rotating. A browser tool lets you pick specific pages too.' },
      { q: 'Do I need Adobe Acrobat to rotate a PDF on Mac?', a: 'No. Preview rotates and saves pages for free, and a browser-based tool adds batch and per-page control without any paid software.' },
      { q: 'Are my files uploaded when I rotate them?', a: 'No. Preview works locally, and a browser-based tool processes the file in your tab. Your PDF never leaves your Mac.' },
    ],
    related: ['how-to-rotate-a-pdf-and-save-it', 'how-to-rotate-a-pdf-on-iphone', 'how-to-rotate-a-pdf-on-android', 'how-to-reverse-page-order-in-a-pdf'],
  },

  // Article 2: How to Convert PDF to Word on Windows
  {
    slug: 'how-to-convert-pdf-to-word-on-windows',
    title: 'How to Convert PDF to Word on Windows (Free, Keep Formatting)',
    description: 'Turn a PDF into an editable Word document on Windows for free. Convert in your browser and keep tables and layout — no Adobe or install.',
    keyword: 'how to convert pdf to word on windows',
    category: 'Converting',
    published: '2026-09-10',
    tool: 'pdf-to-word',
    experience: 'I convert PDFs to Word on Windows to reuse content from reports and quotes. The browser-based route is the only free way to keep tables and layout intact — Word\u2019s built-in PDF opening mangles complex files.',
    blocks: [
      { type: 'p', text: 'A PDF has content you need to edit — a paragraph to reuse, a table to rebuild, or a quote to reprice — but the file is locked. On Windows, Word can try to open a PDF directly, but the result shifts tables, drops fonts, and often looks nothing like the original. A dedicated PDF to Word converter turns the file into a proper document while keeping the layout.' },
      { type: 'p', text: 'Here is how to convert a PDF to Word on Windows for free.' },
      { type: 'h2', text: 'Why Word\u2019s built-in PDF opening is unreliable' },
      { type: 'list', items: [
        'Word attempts to rebuild the page from scratch instead of reading its structure',
        'Tables often lose their column alignment',
        'Custom fonts fall back to substitutes, changing the look',
        'Images can shift position or drop out entirely',
        'Complex multi-column layouts collapse into plain paragraphs',
      ] },
      { type: 'p', text: 'Word\u2019s converter works for simple one-page PDFs, but for anything with tables, columns, or graphics a dedicated converter is far more faithful.' },
      { type: 'h2', text: 'Convert a PDF to Word in your browser' },
      { type: 'steps', items: [
        'Open the PDF to Word tool in Chrome or Edge on your Windows PC.',
        'Drag your PDF into the tool, or click to browse and select it.',
        'Choose the output — Word (.docx) keeps formatting, while other modes extract text.',
        'Click convert and download the .docx file.',
        'Open it in Word and check the layout.',
      ] },
      { type: 'p', text: 'The conversion runs in your browser. Your PDF is processed on your Windows PC and never uploaded to a server.' },
      { type: 'callout', title: 'Scanned PDFs need OCR first', text: 'If the PDF is a scan, the text is an image. Run OCR first to convert it to real characters, then convert the OCR-processed file to Word for an editable document.' },
      { type: 'h2', text: 'What converts well' },
      { type: 'table', head: ['Content', 'Result', 'Fix if needed'], rows: [
        ['Simple text paragraphs', 'Excellent — clean Word paragraphs', 'Rarely anything'],
        ['Tables', 'Good — columns mostly preserved', 'Adjust column widths in Word'],
        ['Images and photos', 'Good — kept in place', 'Resize to fit margins'],
        ['Headers and footers', 'Good — carried over', 'Check page footer alignment'],
        ['Complex magazine-style layouts', 'Fair — elements reflow', 'Clean up manually in Word'],
      ] },
      { type: 'h2', text: 'Cleaning up the converted document' },
      { type: 'p', text: 'After conversion, open the .docx in Word and walk through it. Fix column widths in tables, reapply heading styles, and replace any images that dropped out from the original PDF. Most documents need a few minutes of tidying, not a rebuild.' },
      { type: 'h2', text: 'Tips for the best conversion' },
      { type: 'list', items: [
        'Convert the text-mode claim when spacing is more important than design',
        'Check the preview before downloading when the tool offers one',
        'Keep the original PDF as the reference even after conversion',
        'For editable text without layout, a PDF to text conversion is a clean fallback',
      ] },
      { type: 'p', text: 'Converting a PDF to Word on Windows does not require Adobe. A browser-based tool reads the file on your PC and produces a .docx you can edit in Word, with the formatting preserved.' },
    ],
    faqs: [
      { q: 'How do I convert a PDF to Word on Windows for free?', a: 'Open a browser-based PDF to Word tool in Chrome or Edge, select your PDF, convert, and download the .docx. No install or Adobe subscription needed.' },
      { q: 'Will my tables and layout be preserved?', a: 'A dedicated converter keeps tables, columns, and images largely intact. Complex magazine-style layouts may need minor tidying in Word.' },
      { q: 'Why does Word\u2019s built-in "open PDF" distort my file?', a: 'Word rebuilds PDFs from scratch rather than reading the original structure, so tables misalign and fonts change. A dedicated converter reads the designed layout.' },
      { q: 'Can I convert a scanned PDF to Word?', a: 'Yes, but run OCR first. That turns the image text into real characters so the Word file is actually editable.' },
      { q: 'Are my files uploaded when I convert?', a: 'No. The conversion runs in your browser tab. Your PDF is processed on your Windows PC and never leaves your device.' },
    ],
    related: ['how-to-convert-pdf-to-word-on-mac', 'how-to-convert-pdf-to-word-on-iphone', 'how-to-convert-pdf-to-word-on-android', 'how-to-convert-pdf-to-word-without-losing-formatting'],
  },

  // Article 3: How to Convert PDF to JPG on Windows
  {
    slug: 'how-to-convert-pdf-to-jpg-on-windows',
    title: 'How to Convert PDF to JPG on Windows (Free, All Pages)',
    description: 'Turn PDF pages into JPG images on Windows for free. Convert one page or every page to high-quality images in your browser — no software.',
    keyword: 'how to convert pdf to jpg on windows',
    category: 'Converting',
    published: '2026-09-10',
    tool: 'pdf-to-jpg',
    experience: 'I convert PDF pages to JPGs on Windows when a system only accepts images — expense portals and web forms usually reject PDFs. The browser tool exports every page cleanly, which screenshots never do.',
    blocks: [
      { type: 'p', text: 'A portal, a web form, or a chat app only accepts images, and your document is a PDF. Screenshots give you one blurry, low-resolution page at a time. A dedicated PDF to JPG converter renders each page as a clean, high-quality image on your Windows PC.' },
      { type: 'p', text: 'Here is how to convert a PDF to JPG on Windows for free.' },
      { type: 'h2', text: 'Why screenshots are not the answer' },
      { type: 'list', items: [
        'Screenshots match your screen resolution, so print-quality pages come out soft',
        'Capturing a multi-page PDF means dozens of screenshots, stitched by hand',
        'Scrolled pages get cropped unpredictably',
        'A converter re-renders each page cleanly at the quality you choose',
      ] },
      { type: 'p', text: 'For anything beyond a quick visual, a converter is the reliable path.' },
      { type: 'h2', text: 'Convert a PDF to JPG on Windows in your browser' },
      { type: 'steps', items: [
        'Open the PDF to JPG tool in Chrome or Edge on your Windows PC.',
        'Drag your PDF into the tool, or click to browse and select it.',
        'Choose whether to convert a single page or every page.',
        'Pick the output quality — higher for printing, lower for email and web.',
        'Click convert and download your JPG images.',
      ] },
      { type: 'p', text: 'Each page becomes its own .jpg file, named in order so a 30-page document stays easy to follow. The conversion runs in your browser, so the PDF is processed on your PC and never uploaded.' },
      { type: 'callout', title: 'One page or all pages', text: 'Select one page for a single image, or export the whole document to get every page as a separate JPG. If your form accepts one image only, convert a single page or combine the pages afterward.' },
      { type: 'h2', text: 'Choosing resolution and quality' },
      { type: 'table', head: ['Use', 'Resolution', 'Result'], rows: [
        ['Email or web upload', '100–150 DPI', 'Small files, sharp on screen'],
        ['Archiving or records', '150–200 DPI', 'Good balance of size and clarity'],
        ['Printing the pages', '200–300+ DPI', 'Largest files, cleanest print'],
      ] },
      { type: 'p', text: 'JPG compresses photos and mixed pages well. For pure text or line drawings, a higher quality setting keeps edges crisp; for photos, standard quality keeps files small without visible loss.' },
      { type: 'h2', text: 'Combining pages into one image afterward' },
      { type: 'p', text: 'Some forms want exactly one image. If you exported all pages as separate JPGs, join them in a photo editor or share them as a zip. For two-page documents, lining the pages side by side in an editor usually satisfies single-image uploads.' },
      { type: 'h2', text: 'Keep the PDF as your master copy' },
      { type: 'list', items: [
        'Conversion never modifies the original PDF',
        'Re-export a page at higher quality whenever a portal rejects it',
        'Keep the PDF source for edits and re-conversion',
        'Delete temporary JPGs once the upload is done',
      ] },
      { type: 'p', text: 'A browser-based converter is the fast, free way to get JPGs from a PDF on Windows. It renders clean pages at the quality you choose, works with multi-page documents, and keeps your files on your device.' },
    ],
    faqs: [
      { q: 'How do I convert a PDF to JPG on Windows for free?', a: 'Open a browser-based PDF to JPG tool in Chrome or Edge, select your PDF, choose the pages and quality, and download the images. No software install needed.' },
      { q: 'Can I convert only one page of a PDF?', a: 'Yes. Select the single-page option and the tool exports just that page as a JPG.' },
      { q: 'What resolution should I use?', a: '100–150 DPI for email and web, 200–300+ DPI for printing. Higher DPI gives sharper output but larger files.' },
      { q: 'Will converting reduce image quality?', a: 'Only as much as the JPG format requires. Choose a higher quality setting for crisp output; JPG is best for photos and mixed content.' },
      { q: 'Is my PDF uploaded when I convert it?', a: 'No. The conversion runs in your browser tab. Your PDF is processed on your Windows PC and never leaves your device.' },
    ],
    related: ['how-to-convert-pdf-to-jpg-on-iphone', 'how-to-convert-pdf-to-jpg-on-android', 'how-to-convert-pdf-to-jpg-high-quality', 'how-to-convert-pdf-to-image-for-printing'],
  },

  // Article 4: How to Reduce PDF File Size on Windows
  {
    slug: 'how-to-reduce-pdf-file-size-on-windows',
    title: 'How to Reduce PDF File Size on Windows (Free, No Adobe)',
    description: 'Shrink a large PDF on Windows for free. Compress to an exact size in your browser or print to PDF for a quick trim — no Adobe required.',
    keyword: 'how to reduce pdf file size on windows',
    category: 'Compressing',
    published: '2026-09-10',
    tool: 'compress-pdf',
    experience: 'I shrink PDFs on Windows all the time before emailing them or uploading to portals that cap file sizes. The browser compressor gives exact control, and the Microsoft Print to PDF trick handles quick trims.',
    blocks: [
      { type: 'p', text: 'A PDF is too big to email, a portal rejects it, or it is eating through cloud storage. Windows has no built-in compressor, and Adobe\u2019s tools sit behind a subscription. Two free routes solve it: a browser-based compressor for precise control, and the Microsoft Print to PDF printer for a quick trim.' },
      { type: 'p', text: 'Here is how to reduce PDF file size on Windows for free.' },
      { type: 'h2', text: 'Quick trim: save through Microsoft Print to PDF' },
      { type: 'steps', items: [
        'Open the PDF in your browser or default viewer on Windows.',
        'Press Ctrl + P to open the Print dialog.',
        'Choose Microsoft Print to PDF as the printer.',
        'Click Print and save the new PDF to a different file name.',
        'Check the new file size — it is usually smaller than the original.',
      ] },
      { type: 'p', text: 'This trick re-encodes the document, which removes some hidden overhead. It works well for routine trims but gives you no control over how much it shrinks, and quality loss depends on the viewer.' },
      { type: 'h2', text: 'Precise control: compress in your browser' },
      { type: 'steps', items: [
        'Open the Compress PDF tool in Chrome or Edge on your Windows PC.',
        'Drag your PDF into the tool, or click to browse.',
        'Choose a compression level — light for crisp images, heavy for the smallest file.',
        'Tap compress and check the result size.',
        'Download the smaller PDF and compare it with the original.',
      ] },
      { type: 'p', text: 'The compressor runs in your browser. Your PDF is processed on your Windows PC and never uploaded to a server.' },
      { type: 'callout', title: 'Aim for the right trade-off', text: 'Start with light compression and check the size. Only step up to heavy if the file is still too large. Reading your documents after compression confirms the quality is still acceptable.' },
      { type: 'h2', text: 'Compression levels at a glance' },
      { type: 'table', head: ['Level', 'Typical saving', 'Quality'], rows: [
        ['Light', '20–40%', 'Nearly invisible difference'],
        ['Medium', '40–60%', 'Slight softening on detailed images'],
        ['Heavy', '60–80%', 'Visible on zoom, fine for reading'],
      ] },
      { type: 'p', text: 'Image-heavy PDFs — scans and photo brochures — compress the most because images dominate the file size. Text-only PDFs are already small and gain little.' },
      { type: 'h2', text: 'Hitting a specific limit' },
      { type: 'list', items: [
        'Under 25 MB (most email) — light/medium compression usually enough',
        'Under 10 MB (portals) — medium, then re-check',
        'Under 5 MB (some forms) — heavy if needed',
        'Under 1 MB — remove images first, then compress heavy',
      ] },
      { type: 'p', text: 'If compression alone is not enough, remove blank pages and unneeded images first, or re-scan physical documents at lower resolution in grayscale. Those changes often have a bigger effect than any compressor.' },
      { type: 'h2', text: 'Verify before you send' },
      { type: 'p', text: 'Open the compressed PDF and flip through it. Check tables kept their shape, text is readable, and images have not degraded to an embarrassing level. If it looks wrong, re-compress from the original at a lighter level — your original is never touched.' },
    ],
    faqs: [
      { q: 'How do I reduce PDF file size on Windows for free?', a: 'Print the PDF to Microsoft Print to PDF for a quick trim, or use a browser-based Compress PDF tool for controlled levels. Both cost nothing and need no Adobe.' },
      { q: 'Does compressing a PDF reduce its quality?', a: 'Light compression is nearly invisible; heavy compression softens images but keeps text readable. Choose the level by how much you need to shrink the file.' },
      { q: 'How much smaller will my PDF be?', a: 'Image-heavy PDFs can shrink 40–80% depending on the level. Text-only PDFs are already small and gain little.' },
      { q: 'Can I make a PDF smaller to fit an email limit?', a: 'Yes. Compress to a known level first, then check the size. If it is still over the limit, step up to a heavier level or remove unneeded pages.' },
      { q: 'Is my PDF uploaded when I compress it?', a: 'No. The compression runs in your browser tab. Your PDF is processed on your Windows PC and never leaves your device.' },
    ],
    related: ['how-to-compress-a-pdf-on-windows', 'how-to-reduce-pdf-file-size-on-iphone', 'how-to-reduce-pdf-file-size-on-mac', 'how-to-reduce-pdf-size-without-adobe'],
  },

  // Article 5: How to Remove Pages from a PDF on Android
  {
    slug: 'how-to-remove-pages-from-a-pdf-on-android',
    title: 'How to Remove Pages from a PDF on Android (Free, No App)',
    description: 'Delete unwanted pages from a PDF on your Android phone for free. Remove blank or wrong pages right in Chrome — no app install or uploads.',
    keyword: 'how to remove pages from a pdf on android',
    category: 'Merging & Organizing',
    published: '2026-09-10',
    tool: 'remove-pages',
    experience: 'I remove pages from PDFs on Android to drop blank scans and stray pages before sending. The Chrome-based tool keeps the edit local, which the Play Store editors often push behind a paywall.',
    blocks: [
      { type: 'p', text: 'Your PDF has blank pages, a duplicated page, or a page you never meant to include. Android\u2019s built-in viewer can display the file but cannot delete pages from it, and the Play Store editors usually hide that feature behind a subscription. A browser-based tool removes pages for free, right in Chrome.' },
      { type: 'p', text: 'Here is how to remove pages from a PDF on Android without installing anything.' },
      { type: 'h2', text: 'Why removing pages is not the same as hiding them' },
      { type: 'list', items: [
        'Marking a page "do not print" does not remove it from the file',
        'Blacking out content still leaves the page present',
        'Removal physically deletes the page, so the file truly shrinks',
        'The resulting PDF is smaller and contains only what you keep',
      ] },
      { type: 'p', text: 'Removing pages actually rebuilds the document without them. Page numbers renumber, file size drops, and the recipient only gets what you intend to share.' },
      { type: 'h2', text: 'Remove pages from a PDF on Android in Chrome' },
      { type: 'steps', items: [
        'Open the Remove Pages tool in the Chrome browser on your Android phone.',
        'Tap to choose a file and pick your PDF from Downloads, Google Drive, or phone storage.',
        'Select the pages to delete — tap each one, or enter a range like 3–5.',
        'Review the remaining pages in the preview.',
        'Click remove and download the updated PDF.',
      ] },
      { type: 'p', text: 'The removal runs in your browser. Your PDF is processed on your Android phone and never uploaded to a server.' },
      { type: 'callout', title: 'Keep a backup of the full file', text: 'Deletion cannot be undone. Save or keep the original PDF somewhere until you are sure you want it gone, since your phone will only hold the version you download.' },
      { type: 'h2', text: 'Spotting pages worth removing' },
      { type: 'table', head: ['Page type', 'Why remove it', 'Tip'], rows: [
        ['Blank pages', 'Adds size, looks unprofessional', 'Preview before deleting to confirm it is blank'],
        ['Duplicated pages', 'Confuses recipients', 'Delete the repeat copy only'],
        ['Cover or signature pages', 'Not needed for this recipient', 'Keep if the document needs the cover'],
        ['Private content', 'Should not be shared', 'Remove, or redact instead of delete'],
      ] },
      { type: 'h2', text: 'Removing vs. redacting' },
      { type: 'p', text: 'If a page contains private details you simply do not want in circulation, removing it deletes the whole page. If a page remains but has one sensitive block — an address or a bank number — use redaction to black out just that area while keeping the rest of the page.' },
      { type: 'h2', text: 'Check the result before you send' },
      { type: 'list', items: [
        'Open the updated PDF and scroll through every page',
        'Confirm the pages you deleted are actually gone',
        'Check the page count dropped by the expected number',
        'Rename the file so it is clear this is the trimmed version',
      ] },
      { type: 'p', text: 'A browser-based tool is the free, simple way to remove pages from a PDF on Android. The job runs entirely on your phone, so your document never leaves your device.' },
    ],
    faqs: [
      { q: 'Can I remove pages from a PDF on Android for free?', a: 'Yes. Open a browser-based Remove Pages tool in Chrome, select the pages to delete, and download the trimmed file. No app install needed.' },
      { q: 'Does Android have a built-in PDF page remover?', a: 'No. Android\u2019s viewer displays PDFs but cannot delete pages. A browser-based tool adds the feature with nothing to install.' },
      { q: 'Can I remove a range of pages at once?', a: 'Yes. Enter a range like 3–5 and all pages in that span are deleted together.' },
      { q: 'Is removing pages the same as deleting the original?', a: 'No. The tool creates a new trimmed PDF and leaves your original file unchanged. You choose which one to keep.' },
      { q: 'Are my files uploaded when I remove pages?', a: 'No. The removal runs in your Chrome browser on your phone. Your PDF is processed locally and never leaves your device.' },
    ],
    related: ['how-to-remove-pages-from-a-pdf-on-iphone', 'how-to-delete-pages-from-a-pdf', 'how-to-remove-blank-pages-from-a-pdf', 'how-to-merge-pdf-files-on-android'],
  },
];