import type { BlogPost } from '../types';

export const newPosts5: BlogPost[] = [
  // Article 1: How to Merge PDF Files on Mac
  {
    slug: 'how-to-merge-pdf-files-on-mac',
    title: 'How to Merge PDF Files on Mac (Free, No Adobe)',
    description: 'Combine two or more PDFs into one file on a Mac for free. Use Preview or a browser-based merger — no Adobe, no subscription, no uploads.',
    keyword: 'how to merge pdf files on mac',
    category: 'Merging & Organizing',
    published: '2026-09-01',
    tool: 'merge-pdf',
    blocks: [
      { type: 'p', text: 'A PDF that needs to travel together arrives in parts: an emailed contract, a scanned signature page, a report you exported from a spreadsheet. Your Mac ships with Preview, which can combine PDFs — but the process turns painful once you get past two files. Either way, you can merge PDF files on a Mac for free, without Adobe Acrobat or a subscription.' },
      { type: 'p', text: 'Here are the two ways to merge PDF files on a Mac: the built-in Preview method for quick jobs, and a browser-based merger for anything bigger.' },
      { type: 'h2', text: 'The built-in way: merge PDFs with Preview' },
      { type: 'p', text: 'Preview is the PDF tool that comes with macOS, and it can merge two PDFs. It is a manual, drag-and-drop process:' },
      { type: 'steps', items: [
        'Open the first PDF by double-clicking it in Finder.',
        'Choose View > Thumbnails so the page thumbnails appear in the sidebar.',
        'Double-click the second PDF to open it in its own window.',
        'In the second window\u2019s sidebar, select the thumbnails and drag them into the first window\u2019s sidebar at the position you want.',
        'Choose File > Export, name the combined document, and save it.',
      ] },
      { type: 'p', text: 'This is fine for a one-off, two-file merge. The moment you combine three or more documents — or need to re-order pages after the fact — the dragging gets tedious, and it is easy to drop a page in the wrong spot.' },
      { type: 'callout', title: 'Keep the originals until you save', text: 'Preview\u2019s Export writes a new file and leaves your source PDFs untouched, so a mistake is easy to redo. Use Export rather than Save, which would modify the file you opened.' },
      { type: 'h2', text: 'Merge PDFs on a Mac in your browser' },
      { type: 'p', text: 'When you need one clean file from several PDFs, a browser-based merger is faster than Preview and needs no installation:' },
      { type: 'steps', items: [
        'Open the Merge PDF tool in Safari or Chrome on your Mac.',
        'Drag your PDFs from Finder into the tool, or click to browse and select them — you can add as many as you need.',
        'Drag the thumbnails to set the order. The order you see is the order in the final file.',
        'Click Merge and download the combined PDF.',
      ] },
      { type: 'p', text: 'The whole job runs locally in your browser tab. Your documents never have to leave your Mac, which matters when you are combining contracts, payslips, or anything personal.' },
      { type: 'h2', text: 'Does merging reduce the quality of a PDF?' },
      { type: 'p', text: 'No — a correct merge copies each page into the new document without re-encoding it. Text stays selectable, images stay sharp, and links and form fields survive. If a merge returns a PDF where you can no longer select text, the tool rasterised your pages into flat images; switch to one that keeps the PDF structure intact.' },
      { type: 'h2', text: 'Merging scans and images with your PDFs' },
      { type: 'p', text: 'The merge tool expects PDFs. If one of your files is actually a scanned JPG or an iPhone HEIC photo, convert that image into a PDF first, then merge it with the rest — so a photographed signature or diagram sits exactly where it should in the combined document.' },
      { type: 'h2', text: 'Check the result before you send it' },
      { type: 'p', text: 'Once merged, flip through the finished PDF to confirm the pages are in the right order and nothing is missing, and keep the source files until you are sure. If the combined file comes out too large to email, compress it after merging rather than re-doing the whole merge.' },
    ],
    faqs: [
      { q: 'Can I merge PDF files on a Mac for free?', a: 'Yes. Preview (built into macOS) merges two PDFs by dragging thumbnails, and a browser-based merger combines any number of files with no installation and no account.' },
      { q: 'How do I merge PDFs on a Mac without Preview?', a: 'Use a browser-based merger in Safari or Chrome. It accepts all your PDFs at once, lets you reorder them, and produces one file in a single step.' },
      { q: 'Does merging PDFs lose quality on a Mac?', a: 'No. A correct merge copies each page without re-encoding it, so text, images, and links keep their original quality.' },
      { q: 'Can I add scanned images to a merged PDF?', a: 'Yes. Convert a scanned JPG or HEIC photo to a PDF first, then merge it with your other PDFs.' },
      { q: 'Is a merged PDF uploaded to a server?', a: 'No. When the merge runs in your browser, your documents are processed locally on your Mac and never leave your device.' },
    ],
    related: ['how-to-merge-pdf-files', 'how-to-merge-pdf-files-on-windows', 'how-to-combine-scanned-documents-into-one-pdf', 'how-to-create-a-pdf-from-multiple-file-types'],
  },

  // Article 2: How to Sign a PDF on a Chromebook
  {
    slug: 'how-to-sign-a-pdf-on-chromebook',
    title: 'How to Sign a PDF on a Chromebook (Free, In-Browser)',
    description: 'Add your signature to a PDF on a Chromebook for free with no app to install. Draw, type, or upload your signature right in Chrome.',
    keyword: 'how to sign a pdf on chromebook',
    category: 'Editing & Signing',
    published: '2026-09-01',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'A permission slip, a consent form, or an agreement arrives as a PDF on your Chromebook and needs your signature. Chromebooks do not run desktop PDF editors the way Windows or Mac do, and the built-in Chrome PDF viewer cannot sign anything. The good news: signing a PDF on a Chromebook is one of the easiest PDF jobs out there, because everything happens in the browser you already have open.' },
      { type: 'p', text: 'Here is how to sign a PDF on a Chromebook for free, with no apps to install and no account to create.' },
      { type: 'h2', text: 'Why the built-in viewer is not enough' },
      { type: 'list', items: [
        'Chrome\u2019s PDF viewer opens and reads documents but has no signing tool',
        'ChromeOS ships without a bundled PDF editor that adds signatures',
        'Shopping the Play Store for a PDF app usually lands on a subscription or a watermark',
      ] },
      { type: 'callout', title: 'A browser tab is the right tool', text: 'A browser-based signing tool runs in Chrome on any Chromebook — nothing to install, nothing to pay for, and your document is processed on the device itself, so a medical or legal form never leaves your hands.' },
      { type: 'h2', text: 'Sign a PDF on your Chromebook in Chrome' },
      { type: 'steps', items: [
        'Open the Sign PDF tool in the Chrome browser on your Chromebook.',
        'Click to choose a file and pick your PDF from the Files app, Google Drive, or your Downloads folder.',
        'Choose how to sign — draw with your trackpad, touchscreen, or a connected mouse; type your name in a script font; or upload a saved image of your signature.',
        'Drag the signature onto the signature line and size it to fit.',
        'Download the signed PDF to your Downloads folder and send it back.',
      ] },
      { type: 'p', text: 'If the PDF has fillable fields — checkboxes, dropdowns, text boxes — fill those in the same pass before adding your signature, so the whole form is complete in one download.' },
      { type: 'h2', text: 'Is a Chromebook signature legally binding?' },
      { type: 'p', text: 'Yes — electronic signatures carry the same legal weight as handwritten ones under laws like the US ESIGN Act and UETA, as long as you sign with intent. For everyday agreements, consent forms, and approvals, an electronic signature drawn in a browser tool is valid. If a specific document genuinely requires a handwritten signature or a notary, the other party will tell you; sign on paper in that case.' },
      { type: 'h2', text: 'Build a signature you can reuse' },
      { type: 'p', text: 'Rather than redrawing your signature for every form, upload a clear photo of your signature once and reuse it whenever a new PDF needs signing. Straighten and crop the photo before uploading so the background is clean and the pen strokes are dark.' },
      { type: 'h2', text: 'Signing forms that were scanned' },
      { type: 'p', text: 'If the PDF is a scanned page, you sign it the same way — the signature is placed as an image on top of the page and saved into the file. Just position it carefully on the line, because there is no form field to snap it into place.' },
    ],
    faqs: [
      { q: 'Can I sign a PDF on a Chromebook for free?', a: 'Yes. A browser-based signing tool runs in Chrome with no installation, no account, and no charge — draw, type, or upload your signature and download the signed file.' },
      { q: 'Does a Chromebook have a built-in PDF signer?', a: 'No. The built-in Chrome PDF viewer reads documents but cannot add a signature. A browser-based tool adds that capability with nothing to install.' },
      { q: 'Is an electronic signature on a Chromebook legally binding?', a: 'Yes. Under the US ESIGN Act and UETA, electronic signatures are as valid as handwritten ones when you sign with intent.' },
      { q: 'Where does the signed PDF go on my Chromebook?', a: 'It downloads to your Downloads folder, where you can open it in the Files app, attach it to an email, or move it to Google Drive.' },
      { q: 'Can I reuse the same signature on other PDFs?', a: 'Yes. Upload a photo of your signature once and reuse it on any future document you need to sign.' },
    ],
    related: ['how-to-sign-a-pdf-on-windows', 'how-to-edit-a-pdf-on-a-chromebook', 'how-to-sign-a-pdf-electronically-for-free', 'how-to-fill-out-a-pdf-form'],
  },

  // Article 3: How to Convert PDF to JPG on iPhone
  {
    slug: 'how-to-convert-pdf-to-jpg-on-iphone',
    title: 'How to Convert PDF to JPG on iPhone (Free, No App)',
    description: 'Turn PDF pages into JPG images on your iPhone for free in Safari. Export each page as a crisp, shareable photo — no app install.',
    keyword: 'how to convert pdf to jpg on iphone',
    category: 'Converting',
    published: '2026-09-01',
    tool: 'pdf-to-jpg',
    blocks: [
      { type: 'p', text: 'A PDF holds several pages of a document, but sometimes you need just one page as a plain JPG — to post on social media, paste into a message, or edit in Markup. The iPhone has no built-in way to turn a PDF into JPG images, and many "PDF converter" apps bury that feature behind a subscription. You do not need any of that.' },
      { type: 'p', text: 'Here is how to convert a PDF to JPG on your iPhone for free, right in Safari.' },
      { type: 'h2', text: 'Your options on an iPhone' },
      { type: 'list', items: [
        'The Files app can combine JPGs into a PDF but cannot do the reverse',
        'Screenshotting pages one by one is slow and lowers quality',
        'Many App Store converters are free only for a preview, then paywalled',
      ] },
      { type: 'callout', title: 'Safari converts in place', text: 'A browser-based PDF to JPG tool runs in Safari on your iPhone — no app download, no account, and the conversion happens on your device, so the document never has to be uploaded.' },
      { type: 'h2', text: 'Convert a PDF to JPG on iPhone in Safari' },
      { type: 'steps', items: [
        'Open the PDF to JPG tool in Safari on your iPhone.',
        'Tap to choose a file and select your PDF from the Files app, iCloud Drive, or an email attachment you saved to Files.',
        'Pick a format (JPG or PNG) and a quality setting — high for printing, standard for sharing on screen.',
        'Tap convert. Each page of the PDF becomes its own image.',
        'Download the images, which arrive bundled in a ZIP, and open them in the Files app.',
      ] },
      { type: 'p', text: 'From there you can share a single page as a photo, attach it to an email, or open it in Markup for a quick annotation.' },
      { type: 'h2', text: 'Scanned PDFs convert just the same' },
      { type: 'p', text: 'If the PDF is a scan of a printed page, conversion works identically — the scanned page simply becomes a JPG. This is handy for sending one page of a multi-page contract to someone who only needs the last sheet, or for pulling a printed receipt into an expense app as an image.' },
      { type: 'h2', text: 'When to use JPG instead of keeping the PDF' },
      { type: 'table', head: ['Use JPG when', 'Use PDF when'], rows: [
        ['Sharing a single page as a photo', 'Sending the whole document'],
        ['Posting to social media or a chat', 'Submitting forms or portals'],
        ['Editing a page in Markup or a photo app', 'Keeping text selectable and searchable'],
        ['Archiving a photo-like scan', 'Printing or legal archives'],
      ] },
      { type: 'h2', text: 'Getting the quality you need' },
      { type: 'p', text: 'For screen sharing, the standard setting is plenty and keeps the file small. If you plan to print a page or zoom into fine detail, use the high-quality setting instead — text edges stay crisp rather than showing compression artefacts. Test your first conversion at 100% zoom before you choose a setting for the whole run.' },
    ],
    faqs: [
      { q: 'Can I convert a PDF to JPG on my iPhone for free?', a: 'Yes. A browser-based PDF to JPG tool runs in Safari with no app install and no account, exporting each page as an image.' },
      { q: 'Does the iPhone have a built-in PDF to JPG converter?', a: 'No. The Files app converts images into a PDF but not PDFs into images. A browser-based converter is the simplest free route.' },
      { q: 'Will converting a PDF to JPG lose quality?', a: 'The tool renders at a set quality. The high setting is sharp enough for printing; the standard setting is fine for screen sharing. Text edges stay crisp at the high setting.' },
      { q: 'Can I convert only one page of a PDF?', a: 'The converter turns every page into an image. To get a single page only, convert the file and then share just that one image from the downloaded ZIP.' },
      { q: 'Where do the converted images go on my iPhone?', a: 'They download into the Files app, where you can open, rename, or share them like any other image.' },
    ],
    related: ['how-to-convert-pdf-to-jpg-high-quality', 'how-to-convert-pdf-to-image-for-printing', 'how-to-convert-pdf-to-word-on-iphone', 'how-to-convert-a-photo-to-pdf-on-your-phone'],
  },

  // Article 4: How to Password Protect a PDF on iPhone
  {
    slug: 'how-to-password-protect-a-pdf-on-iphone',
    title: 'How to Password Protect a PDF on iPhone (Free)',
    description: 'Lock a PDF with a password on your iPhone for free. Protect contracts and statements in Safari — no app download required.',
    keyword: 'how to password protect a pdf on iphone',
    category: 'Security & Privacy',
    published: '2026-09-02',
    tool: 'protect-pdf',
    blocks: [
      { type: 'p', text: 'A bank statement, a signed contract, or a copy of your passport is about to leave your iPhone as a PDF. Before you hit send, lock it with a password. iOS does not include a way to password protect a PDF — the Files app cannot encrypt — and most PDF apps gate the feature behind a paid plan. A browser tab can do it for free in under a minute.' },
      { type: 'p', text: 'Here is how to password protect a PDF on your iPhone without installing anything.' },
      { type: 'h2', text: 'Why your iPhone has no built-in option' },
      { type: 'list', items: [
        'The Files app opens and shares PDFs but cannot set a password',
        'Printing to PDF on iOS creates a file but does not encrypt it',
        'Most iOS PDF apps offer protection only in a paid tier',
      ] },
      { type: 'callout', title: 'Real encryption, in Safari', text: 'A browser-based Protect PDF tool applies real PDF encryption locally on your iPhone — the same AES-256 strength used for bank documents — with no app download and nothing uploaded to a server.' },
      { type: 'h2', text: 'Password protect a PDF on iPhone in Safari' },
      { type: 'steps', items: [
        'Open the Protect PDF tool in Safari on your iPhone.',
        'Tap to choose a file and select your PDF from the Files app, iCloud Drive, or an email attachment saved to Files.',
        'Type a strong password — at least 12 characters with upper and lower case, numbers, and symbols.',
        'Tap protect and download the encrypted PDF back to your iPhone.',
      ] },
      { type: 'p', text: 'Anyone who opens the file afterwards is asked for the password before they can see the contents — on an iPhone, a Mac, in Adobe Reader, or on a Windows PC — because PDF password protection is part of the format itself.' },
      { type: 'h2', text: 'Share the password separately' },
      { type: 'p', text: 'The password only helps if it does not travel with the file. Send the encrypted PDF by email and the password by text, phone call, or a messaging app — a different channel — and never include the password in the file name.' },
      { type: 'h2', text: 'Choose a password that is strong and memorable' },
      { type: 'p', text: 'Safari offers Password AutoFill, so you can generate the PDF\u2019s password and store it in iCloud Keychain — convenient and safe. For sensitive files, a passphrase of three or four random words is both strong and easy to remember. Avoid single dictionary words, birth years, phone numbers, and the passwords you already use for other accounts.' },
      { type: 'h2', text: 'There is no recovery if you forget it' },
      { type: 'p', text: 'If the password is lost, there is no legitimate way to open the document again — a locked PDF you cannot open is no good to anyone. Keep an unlocked copy of the original somewhere safe in your own storage, and store the password in Keychain or a password manager. Two records: the protected file for sending, the original for yourself.' },
    ],
    faqs: [
      { q: 'Can I password protect a PDF on my iPhone for free?', a: 'Yes. A browser-based Protect PDF tool runs in Safari and applies real AES-256 encryption with no app install, no account, and no upload.' },
      { q: 'Does the iPhone have a built-in PDF password tool?', a: 'No. The Files app cannot encrypt PDFs and iOS offers no native way to set a PDF password. A browser-based tool is the free route.' },
      { q: 'Can the recipient open a protected PDF on any device?', a: 'Yes. Password protection is part of the PDF standard, so the file prompts for the password in Preview on Mac, Adobe Reader, Chrome, and on Windows.' },
      { q: 'What if I forget the PDF password?', a: 'There is no recovery mechanism. Keep an unlocked backup copy of the original document and store the password in iCloud Keychain or a password manager.' },
      { q: 'Is my PDF or password uploaded to a server?', a: 'No. The encryption runs in your browser, so the document and the password are processed on your iPhone and never transmitted.' },
    ],
    related: ['how-to-password-protect-a-pdf', 'how-to-password-protect-a-pdf-without-adobe', 'how-to-remove-a-password-from-a-pdf', 'how-to-share-a-pdf-securely'],
  },

  // Article 5: How to Split a PDF on Mac
  {
    slug: 'how-to-split-a-pdf-on-mac',
    title: 'How to Split a PDF on Mac (Free, No Adobe)',
    description: 'Pull pages out of a PDF on a Mac for free. Extract a page range into its own file in your browser — no Adobe and no install.',
    keyword: 'how to split a pdf on mac',
    category: 'Merging & Organizing',
    published: '2026-09-01',
    tool: 'split-pdf',
    blocks: [
      { type: 'p', text: 'Your Mac holds a 24-page PDF and you need to hand one colleague the first five pages and another the rest — or you just want to pull a single page out of a big document. Splitting is the least obvious PDF task on macOS: Preview can do it, but the process is manual and easy to get wrong. There is a browser route that is simpler and safer.' },
      { type: 'p', text: 'Here is how to split a PDF on a Mac — what Preview can and cannot do, and the one-step browser method.' },
      { type: 'h2', text: 'What Preview can and cannot do' },
      { type: 'p', text: 'Preview has no "split" command. The workaround is to open the PDF, delete every page you do not want, and save what is left as a new file. That works, but it has real limits:' },
      { type: 'list', items: [
        'You must duplicate the file first, or you risk editing the original by accident',
        'Each output file is one filtered selection, so a multi-part split means repeating the whole delete-and-save routine',
        'It is easy to save a half-deleted file if you forget to duplicate before you start',
      ] },
      { type: 'callout', title: 'The safer route is a browser split', text: 'A browser-based Split PDF tool takes a page range you choose, lets you preview exactly those pages, and produces a brand-new file — leaving the original completely untouched.' },
      { type: 'h2', text: 'Split a PDF on your Mac in the browser' },
      { type: 'steps', items: [
        'Open the Split PDF tool in Safari or Chrome on your Mac.',
        'Drag your PDF from Finder into the tool, or click to browse and select it.',
        'Enter the pages for the new file — a single page (9), a range (1-5), or a mixture (1-3, 5, 7-10).',
        'Review the preview to confirm exactly those pages are selected.',
        'Click Split and download the new PDF.',
      ] },
      { type: 'p', text: 'The original file is never modified, so you can run the tool again with different ranges and build as many separate documents as you need — pages 1-5 saved as "Part 1", pages 6-24 as "Part 2", and so on.' },
      { type: 'h2', text: 'Extracting a single page or a few pages' },
      { type: 'p', text: 'To pull one page out of a long document — say page 9 of a 50-page report — enter that single number and you get a one-page PDF ready to email. The output keeps the original page content as real text, so quality stays identical and the extracted pages remain selectable and searchable.' },
      { type: 'h2', text: 'How the Preview manual method compares' },
      { type: 'p', text: 'If you prefer to stay in Preview: open the PDF, choose View > Thumbnails, duplicate the file first, select the unwanted thumbnails and press Delete, then use File > Export to save what remains under a clear name. The browser approach does the same job with less risk of saving a half-deleted file, especially when you split on several ranges.' },
      { type: 'h2', text: 'After you split' },
      { type: 'p', text: 'Name each output file clearly when you download it, and flip through it once to confirm the pages are the ones you meant. If you later need the separate parts back together, you can merge PDFs on the same Mac in a single step.' },
    ],
    faqs: [
      { q: 'Can I split a PDF on a Mac for free?', a: 'Yes. Preview can export selected pages to a new file, and a browser-based Split PDF tool extracts a page range into its own PDF with no installation and no account.' },
      { q: 'Does Preview have a split PDF option?', a: 'There is no direct split command, but you can delete the pages you do not want in a duplicated copy and export the rest as a new PDF. For real control, a browser tool is easier.' },
      { q: 'Does splitting a PDF reduce quality?', a: 'No. The selected pages are copied into a new document without re-encoding, so the text stays sharp, selectable, and searchable.' },
      { q: 'Can I extract non-consecutive pages into one file?', a: 'Yes. Enter ranges like 1-3, 5, 7-10 to pull exactly those pages into a single new PDF in one pass.' },
      { q: 'Will splitting change my original PDF?', a: 'No. The browser tool creates a new file and leaves the original untouched, so you can split on different ranges as many times as you like.' },
    ],
    related: ['how-to-split-a-pdf-into-separate-pages', 'how-to-split-a-pdf-by-file-size', 'how-to-merge-pdf-files-on-mac', 'how-to-extract-pages-from-pdf'],
  },
];