import type { BlogPost } from '../types';

export const newPosts12: BlogPost[] = [
  // Article 1: How to Split a PDF on a Chromebook
  {
    slug: 'how-to-split-a-pdf-on-chromebook',
    title: 'How to Split a PDF on a Chromebook (Free, No App)',
    description: 'Split a PDF into separate pages on a Chromebook for free. Extract a page range or one file per page in Chrome, with no app install or uploads.',
    keyword: 'how to split a pdf on chromebook',
    category: 'Merging & Organizing',
    published: '2026-09-15',
    tool: 'split-pdf',
    experience: 'I split PDFs on Chromebooks when I pull chapters out of ebooks and booklets for students. Chrome\u2019s print dialog can grab one page range at a time, but a browser tool splits an entire document in a single pass.',
    blocks: [
      { type: 'p', text: 'A PDF on your Chromebook needs to be broken apart, whether it is a chapter from an ebook, a specific set of pages from a manual, or one file per page for sharing. ChromeOS has no built-in splitter, Google Drive\u2019s viewer cannot do it, and the Acrobat app from the Play Store hides the split feature behind a paid subscription. A browser-based tool runs in Chrome and splits the file for free, with nothing to install.' },
      { type: 'p', text: 'Here is how to split a PDF on a Chromebook for free, right in Chrome.' },
      { type: 'h2', text: 'Why Chromebooks have no built-in splitter' },
      { type: 'list', items: [
        'The Files app displays and organises files but cannot edit PDF page structure',
        'Google Drive\u2019s PDF viewer shows pages but has no split or extract option',
        'The Android Acrobat app on a Chromebook requires a paid subscription to split files',
        'The browser print dialog is the only built-in workaround, and it handles one page range at a time',
      ] },
      { type: 'p', text: 'The print-dialog trick is worth knowing: open the PDF in Chrome, press Ctrl + P, confirm the destination is \u201cSave as PDF\u201d, enter the page range you want in the Pages field, and click Save. It extracts that range cleanly, but you repeat the whole process for every additional range.' },
      { type: 'h2', text: 'Split a PDF on a Chromebook in Chrome' },
      { type: 'steps', items: [
        'Open the Split PDF tool in Chrome on your Chromebook.',
        'Drag your PDF into the tool, or click to browse and select it from Downloads or Google Drive.',
        'Pick how to split: a specific page range, chunks of a set number of pages, or every page as its own file.',
        'Enter the pages you want (for example, 5\u201312).',
        'Click split and download the new PDFs, or the ZIP that holds them all.',
      ] },
      { type: 'p', text: 'The split runs in Chrome itself, so the file is processed on your Chromebook and never uploaded anywhere.' },
      { type: 'callout', title: 'One tool for every split type', text: 'Print-to-PDF only handles a single page range at a time. A splitter tool adds chunking and one-file-per-page in the same pass, and it writes every result straight to your Downloads folder.' },
      { type: 'h2', text: 'Which split option should you use?' },
      { type: 'table', head: ['Split type', 'What it does', 'Best for'], rows: [
        ['Page range', 'Extracts a specific set of pages, e.g. 5\u201312', 'Pulling a chapter or a section out of a document'],
        ['Every page', 'One PDF per page', 'Sending each page as its own file'],
        ['Chunks', 'Every N pages becomes a file, e.g. every 10 pages', 'Breaking a long file into equal parts'],
        ['Selected pages', 'Extracts non-contiguous pages, e.g. 2, 6, 9', 'Grabbing scattered pages only'],
      ] },
      { type: 'h2', text: 'Check the output before you share' },
      { type: 'list', items: [
        'Open each split file in Chrome to confirm it holds the right pages',
        'Verify the first and last pages are complete and not cut off',
        'Keep file names in order when you split into many files',
        'Clear out the ZIP from Downloads once you have unzipped what you need',
      ] },
      { type: 'p', text: 'Splitting a PDF on a Chromebook is a browser job. The print dialog covers a one-off page range, and a dedicated split tool handles chunking, every page, and selected pages in a single pass, with nothing to download and no uploads.' },
    ],
    faqs: [
      { q: 'Can I split a PDF on a Chromebook for free?', a: 'Yes. Open a browser-based Split PDF tool in Chrome, select your PDF, pick the pages or ranges, and download the extracted files. The print dialog can also grab a single page range.' },
      { q: 'How do I extract pages from a PDF without an app?', a: 'Open the PDF in Chrome, press Ctrl + P, set the destination to Save as PDF, enter the page numbers you want in the Pages field, and click Save. Repeat the process for each range you need.' },
      { q: 'Can Google Drive split a PDF?', a: 'No. Drive\u2019s PDF viewer displays pages but cannot split, extract, or reorder them. You need a browser-based tool instead.' },
      { q: 'Does splitting change my original PDF?', a: 'No. Splitting creates new PDFs from the source file and leaves your original untouched.' },
      { q: 'Are my files uploaded when I split them?', a: 'No. The tool runs in your Chrome browser. Your PDF is processed locally on your Chromebook and never leaves the device.' },
    ],
    related: ['how-to-merge-pdf-files-on-chromebook', 'how-to-split-a-pdf-on-android', 'how-to-split-a-pdf-on-iphone', 'how-to-reverse-page-order-in-a-pdf'],
  },

  // Article 2: How to Convert PDF to JPG on a Chromebook
  {
    slug: 'how-to-convert-pdf-to-jpg-on-chromebook',
    title: 'How to Convert PDF to JPG on a Chromebook (Free, No App)',
    description: 'Turn PDF pages into JPG images on your Chromebook for free. Convert one page or all pages in Chrome and download crisp images, no app needed.',
    keyword: 'how to convert pdf to jpg on chromebook',
    category: 'Converting',
    published: '2026-09-15',
    tool: 'pdf-to-jpg',
    experience: 'I convert PDFs to JPG on Chromebooks when I need a page of a scanned book as an image for slides or a thumbnail. The Files app cannot export images, so a browser converter does the job in a single pass.',
    blocks: [
      { type: 'p', text: 'A page of a PDF needs to become a JPG for a slide, a thumbnail, a website, or an attachment that only accepts images. On a Chromebook there is no built-in way: the Files app cannot export PDF pages as images, and Chrome\u2019s print option only writes PDFs. A browser-based converter renders each page as a JPG and saves the images to your Downloads folder.' },
      { type: 'p', text: 'Here is how to convert a PDF to JPG on a Chromebook for free.' },
      { type: 'h2', text: 'Why Chromebooks cannot convert to images natively' },
      { type: 'list', items: [
        'The Files app displays PDFs but has no export-to-image option',
        'Chrome\u2019s print dialog and \u201cSave as PDF\u201d can only produce PDFs',
        'Google Drive\u2019s viewers have no image-conversion feature',
        'Play Store converters that work often limit conversions or add watermarks',
      ] },
      { type: 'p', text: 'The one built-in workaround, screenshotting pages one at a time, produces low-resolution images and is painfully slow for anything longer than a single page.' },
      { type: 'h2', text: 'Convert a PDF to JPG on a Chromebook in Chrome' },
      { type: 'steps', items: [
        'Open the PDF to JPG tool in Chrome on your Chromebook.',
        'Drag the PDF into the tool, or click to browse and select it from Downloads or Google Drive.',
        'Choose the image quality (or DPI) at which the pages should be rendered.',
        'Click convert, and every page is turned into a JPG.',
        'Download the images; multiple files arrive as a ZIP you can open in the Files app.',
      ] },
      { type: 'p', text: 'The conversion runs in Chrome itself. Your PDF is processed on your Chromebook and never uploaded to a server.' },
      { type: 'callout', title: 'One page or every page', text: 'Need only one page? Most converters let you pick a specific page before converting, so you get a single JPG instead of a folder full of images.' },
      { type: 'h2', text: 'Choosing the right quality' },
      { type: 'p', text: 'The key setting is the DPI, or resolution, at which each page is rendered. For on-screen use, a moderate resolution keeps files small and fast to load, which suits slides and websites. For printing or zooming into fine text, a higher resolution keeps every letter readable. Higher resolution means bigger files, so match the setting to where the image is going.' },
      { type: 'table', head: ['Purpose', 'Resolution', 'Result'], rows: [
        ['Slides and social media', 'Standard', 'Small, quick-loading JPGs'],
        ['Web use and email', 'Standard', 'Clear at normal sizes'],
        ['Printing or archiving', 'High', 'Sharp text and fine details'],
        ['Full-page thumbnails', 'Low', 'The smallest possible files'],
      ] },
      { type: 'h2', text: 'JPG vs. JPEG: the same format' },
      { type: 'p', text: 'JPG and JPEG are exactly the same image format; only the file extension differs. Whether your pages come out as .jpg or .jpeg files, they open everywhere and behave identically. If a website or system insists on one extension, simply rename the file.' },
      { type: 'h2', text: 'Check your images before sending' },
      { type: 'list', items: [
        'Open each JPG in the Chromebook Gallery app and confirm the page rendered fully',
        'Check text-heavy pages are sharp where it matters',
        'Confirm the last page of the document is not cut off',
        'Unzip the download and delete the ZIP once the images are safe',
      ] },
      { type: 'p', text: 'Converting a PDF to JPG on a Chromebook takes seconds with a browser tool. There is nothing to install and no account to create, and the whole conversion happens locally, so pick a resolution, render the pages, and download clean JPGs straight from Chrome.' },
    ],
    faqs: [
      { q: 'Can I convert a PDF to JPG on a Chromebook for free?', a: 'Yes. A browser-based PDF to JPG tool in Chrome renders every page as a JPG and downloads the images. Nothing to install or sign up for.' },
      { q: 'Can Google Drive turn a PDF into a JPG?', a: 'No. Drive\u2019s viewer and the Files app have no image-conversion feature. A browser converter is the standard free route.' },
      { q: 'Will converting reduce the quality of my PDF?', a: 'Only if you choose a low resolution. Pick a higher resolution to keep text sharp; the files will be larger, but the pages stay crisp.' },
      { q: 'How do I convert just one page of a PDF?', a: 'Select that page before converting, using the page picker if the tool offers one, so the output is a single JPG instead of one image per page.' },
      { q: 'Are my files uploaded when I convert them?', a: 'No. The conversion runs in your Chrome browser. Your PDF is processed locally on your Chromebook and never leaves your device.' },
    ],
    related: ['how-to-convert-pdf-to-jpg-on-windows', 'how-to-convert-pdf-to-jpg-on-android', 'how-to-edit-a-pdf-on-a-chromebook', 'how-to-compress-pdf-on-chromebook'],
  },

  // Article 3: How to Convert Word to PDF on Windows
  {
    slug: 'how-to-convert-word-to-pdf-on-windows',
    title: 'How to Convert Word to PDF on Windows (Free, No Office)',
    description: 'Turn a Word document into a PDF on Windows for free. Use Word\u2019s export, the built-in PDF printer, or your browser, with no Adobe needed.',
    keyword: 'how to convert word to pdf on windows',
    category: 'Converting',
    published: '2026-09-15',
    tool: 'word-to-pdf',
    experience: 'I convert Word files to PDF on Windows all the time, usually for documents that arrive when Office is not installed. Word\u2019s own export is cleanest when you have it, and a browser tool covers every other case for free.',
    blocks: [
      { type: 'p', text: 'A .docx needs to become a PDF for a resume, a report, or a document that has to open identically for everyone. On Windows you have built-in options, such as Word\u2019s export and the Print to PDF printer, and a browser tool covers the case where Office is not installed at all.' },
      { type: 'p', text: 'Here is how to convert a Word document to PDF on Windows for free.' },
      { type: 'h2', text: 'Convert with Word (built in)' },
      { type: 'steps', items: [
        'Open the document in Word on your Windows PC.',
        'Choose File > Save As, or Save a Copy if AutoSave is on.',
        'In the Save as type dropdown, select PDF.',
        'Click Save, and Word writes a PDF that keeps the layout.',
      ] },
      { type: 'p', text: 'Word\u2019s own export is the cleanest conversion because the program that made the document does the job. File > Export > Create PDF/XPS produces the same result.' },
      { type: 'callout', title: 'No Word installed?', text: 'Word for the web can open the file and export a PDF for free, or you can convert the .docx directly in a browser tool, which needs no Office at all.' },
      { type: 'h2', text: 'Convert any file with Microsoft Print to PDF' },
      { type: 'steps', items: [
        'Open the document in any program that can print it, such as Word, Notepad, or your browser.',
        'Press Ctrl + P to open the print dialog.',
        'Choose Microsoft Print to PDF as the printer.',
        'Adjust the pages and layout, then click Print.',
        'Pick a name and location, and the PDF is created.',
      ] },
      { type: 'p', text: 'Print to PDF is built into Windows 10 and 11 and works from any application. It is the fastest option when the document is already open and you just need a PDF copy.' },
      { type: 'h2', text: 'Convert a DOCX in your browser without Office' },
      { type: 'p', text: 'When you receive a Word file but do not have Office, or you want a conversion that runs locally and keeps the formatting, a browser-based tool turns the .docx into a PDF with no install:' },
      { type: 'steps', items: [
        'Open the Word to PDF tool in Chrome or Edge on your Windows PC.',
        'Drag the .docx file into the tool, or click to browse.',
        'Check the conversion preview if one is shown.',
        'Click convert and download the PDF.',
      ] },
      { type: 'p', text: 'The conversion happens in your browser tab. The document is processed on your Windows PC and not uploaded to a server.' },
      { type: 'h2', text: 'Three routes compared' },
      { type: 'table', head: ['Route', 'Needs Office?', 'Best for'], rows: [
        ['Word File > Save As', 'Yes', 'Cleanest quality when you have Word'],
        ['Microsoft Print to PDF', 'No', 'Converting from any app in one step'],
        ['Browser DOCX converter', 'No', 'No Office installed, layout preserved'],
      ] },
      { type: 'h2', text: 'Check the result before you send' },
      { type: 'list', items: [
        'Open the PDF and compare it with the original Word document',
        'Confirm tables, images, and headings stayed in place',
        'Check that fonts render the way you set them',
        'Send the PDF, not the .docx, when the layout must not change',
      ] },
      { type: 'p', text: 'Converting Word to PDF on Windows never requires Adobe or an install. Word exports the file when you have it, Print to PDF handles any document, and a browser tool covers the rest, keeping the whole workflow free.' },
    ],
    faqs: [
      { q: 'How do I convert a Word document to PDF on Windows for free?', a: 'Open it in Word and use File > Save As with the PDF type, or press Ctrl + P and choose Microsoft Print to PDF. If you have no Office, convert the .docx in a browser tool.' },
      { q: 'What is the difference between Save As PDF and Print to PDF?', a: 'Save As writes the PDF directly from Word and preserves the file structure. Print to PDF sends the document through the print pipeline, which is fine for most files but can differ slightly from the on-screen layout.' },
      { q: 'Can I convert a DOCX to PDF without Microsoft Word?', a: 'Yes. Word for the web exports PDFs for free, and a browser-based Word to PDF tool converts the file directly with no Office or install required.' },
      { q: 'Do I need Adobe Acrobat to create a PDF from Word?', a: 'No. Windows includes everything you need: Word\u2019s export and the Microsoft Print to PDF printer. Acrobat is only a paid alternative.' },
      { q: 'Are my files uploaded when I convert them in a browser tool?', a: 'No. The conversion runs in your browser tab on your Windows PC. Your document never leaves your device.' },
    ],
    related: ['how-to-convert-word-to-pdf-on-mac', 'how-to-convert-word-to-pdf-on-android', 'how-to-convert-pdf-to-word-on-windows', 'how-to-convert-word-to-pdf-without-losing-formatting'],
  },

  // Article 4: How to Crop a PDF on iPhone
  {
    slug: 'how-to-crop-a-pdf-on-iphone',
    title: 'How to Crop a PDF on iPhone (Free, In-Browser)',
    description: 'Crop the pages of a PDF on your iPhone for free. Trim unwanted margins or cut a scan down to size in Safari, with no app install required.',
    keyword: 'how to crop a pdf on iphone',
    category: 'Editing & Signing',
    published: '2026-09-15',
    tool: 'crop-pdf',
    experience: 'I crop PDFs on my iPhone to trim blank margins off receipts and cut scanned pages down to size before sending. The built-in Files editor can crop a single page on recent iOS versions, and a Safari-based tool handles whole documents.',
    blocks: [
      { type: 'p', text: 'A PDF page has an extra margin, a blank strip, or a border you want removed before printing or sending. Cropping trims the page down to the area you keep. On an iPhone you have two free routes: the built-in Files editor on recent iOS versions, and a browser-based crop tool that works on any iPhone.' },
      { type: 'p', text: 'Here is how to crop a PDF on an iPhone for free.' },
      { type: 'h2', text: 'Crop a PDF in the Files app (iOS 26 and later)' },
      { type: 'steps', items: [
        'Open the Files app on your iPhone and find the PDF.',
        'Tap the PDF to open it in the built-in viewer.',
        'Tap the edit button in the toolbar to enter the page editor.',
        'Drag the handles around the part of the page you want to keep.',
        'Tap Crop, then save the PDF.',
      ] },
      { type: 'p', text: 'This is the true built-in option, but it crops one page at a time and is only available on iOS versions that include the page-editing tools. For trimming the margins across a whole document, a browser tool is much faster.' },
      { type: 'h2', text: 'Crop a PDF in Safari' },
      { type: 'steps', items: [
        'Open the Crop PDF tool in the Safari browser on your iPhone.',
        'Tap to choose the PDF from Files, iCloud Drive, or Downloads.',
        'Choose the crop amount, either uniform margins or a custom amount for each edge.',
        'Apply the crop and download the trimmed PDF.',
      ] },
      { type: 'p', text: 'The tool runs in your browser tab. Your PDF is processed on your iPhone and never uploaded to a server.' },
      { type: 'callout', title: 'Crop is not the same as resize', text: 'Cropping removes parts of the page, such as margins, borders, or blank strips. Resizing scales the whole page down to a smaller size. For trimming, crop; for fitting a page on a smaller sheet, resize.' },
      { type: 'h2', text: 'When cropping makes sense' },
      { type: 'list', items: [
        'Removing a white margin so printed pages waste less space',
        'Trimming blank strips left by a flatbed scan',
        'Cutting a page of a book down to the text block for an excerpt',
        'Removing a header, footer, or border from copies of a form',
      ] },
      { type: 'h2', text: 'Crop all pages or only some' },
      { type: 'table', head: ['Crop type', 'What it does', 'When to use it'], rows: [
        ['Uniform margin', 'Trims the same amount on each edge', 'Whole documents with consistent margins'],
        ['Custom edges', 'Different trim on left, right, top, and bottom', 'Pages with an uneven border'],
        ['Selected pages only', 'Crops only the pages you pick', 'A document with a few oversized pages'],
      ] },
      { type: 'h2', text: 'Check the trimmed PDF' },
      { type: 'list', items: [
        'Open the result and scroll through each page',
        'Confirm no important content was cut at the edges',
        'Check the crop is even if you applied a uniform margin',
        'Keep the original PDF until the cropped copy is verified',
      ] },
      { type: 'p', text: 'Cropping a PDF on an iPhone is free either way. The Files app handles a single page on recent iOS, and a Safari-based crop tool trims whole documents without an app. Either way, everything stays on your phone.' },
    ],
    faqs: [
      { q: 'Can I crop a PDF on an iPhone for free?', a: 'Yes. On iOS 26 and later, the Files app can crop a page with its built-in editor, and a browser-based Crop PDF tool in Safari trims pages without any app.' },
      { q: 'How do I crop a PDF without an app?', a: 'Open the PDF in the Files app, tap the edit button in the toolbar, frame the area you want with the selection handles, and tap Crop. Or open a crop tool in Safari.' },
      { q: 'What is the difference between cropping and resizing?', a: 'Cropping removes part of the page. Resizing scales the whole page down to a smaller size without removing any content.' },
      { q: 'Can I crop all pages of a PDF at once?', a: 'Yes, with a Safari-based crop tool that applies a uniform trim to every page, or a margin amount you set yourself.' },
      { q: 'Are my files uploaded when I crop them?', a: 'No. The cropping runs in your browser tab. Your PDF is processed on your iPhone and never leaves your device.' },
    ],
    related: ['how-to-crop-a-pdf', 'how-to-edit-a-pdf-on-iphone', 'how-to-remove-pages-from-a-pdf-on-iphone', 'how-to-rotate-a-pdf-on-iphone'],
  },

  // Article 5: How to Add a Watermark to a PDF on iPhone
  {
    slug: 'how-to-add-a-watermark-to-a-pdf-on-iphone',
    title: 'How to Add a Watermark to a PDF on iPhone (Free)',
    description: 'Add a text or image watermark to a PDF on your iPhone for free. Stamp draft or confidential pages in Safari, with no app install required.',
    keyword: 'how to add a watermark to a pdf on iphone',
    category: 'Editing & Signing',
    published: '2026-09-15',
    tool: 'add-watermark',
    experience: 'I watermark PDFs on my iPhone before sending client samples and draft contracts, stamping pages so they clearly read SAMPLE or DRAFT. iPhone has no built-in watermark feature, so a Safari-based tool is the free answer.',
    blocks: [
      { type: 'p', text: 'A document needs its status marked across every page, such as DRAFT, CONFIDENTIAL, or your logo on a sample file. That is what a watermark does, and on an iPhone there is no built-in way to add one across a whole PDF. A browser-based tool stamps text or an image on every page for free, with no app install.' },
      { type: 'p', text: 'Here is how to add a watermark to a PDF on an iPhone.' },
      { type: 'h2', text: 'Why the iPhone has no built-in watermark tool' },
      { type: 'list', items: [
        'The Markup tools can add a single text box, but not repeat it across every page',
        'The Files and Books apps cannot apply watermarks to PDFs',
        'App Store watermark apps are almost all paid subscriptions or limited trials',
      ] },
      { type: 'p', text: 'Markup is fine for a one-off handwritten note on a single page. For a watermark that repeats on every page of a document, you need a dedicated tool.' },
      { type: 'h2', text: 'Add a watermark in Safari' },
      { type: 'steps', items: [
        'Open the Add Watermark tool in the Safari browser on your iPhone.',
        'Tap to choose the PDF from Files, iCloud Drive, or Downloads.',
        'Type the watermark text, such as DRAFT or CONFIDENTIAL, or upload a logo image.',
        'Set the size, opacity, and position of the watermark.',
        'Choose which pages it covers, all of them or a specific range.',
        'Download the watermarked PDF.',
      ] },
      { type: 'p', text: 'The tool runs in your browser tab. Your PDF is processed on your iPhone and not uploaded anywhere.' },
      { type: 'callout', title: 'Diagonal or tiled watermarks', text: 'Most converters let you rotate the watermark into the diagonal that classic stamp marks use, and tile a small logo in a repeating pattern across the page for stronger protection.' },
      { type: 'h2', text: 'Text vs. image watermarks' },
      { type: 'table', head: ['Watermark', 'Best for', 'Notes'], rows: [
        ['Text (DRAFT, CONFIDENTIAL)', 'Marking document status', 'Simple, clear, and easy to read'],
        ['Your name or company', 'Claiming ownership', 'Readable, and light opacity works best'],
        ['Logo or image', 'Branding documents', 'A transparent-background image looks best'],
        ['Tiled pattern', 'Discouraging redistribution', 'Repeats the mark across the full page'],
      ] },
      { type: 'h2', text: 'Settings worth getting right' },
      { type: 'list', items: [
        'Opacity: a light mark keeps content readable, while a heavy mark hides text beneath it',
        'Size: a watermark should be noticeable but not cover the document',
        'Pages: place DRAFT on every page, or only on the cover',
        'Rotation: diagonal placement matches the typical stamp style',
      ] },
      { type: 'p', text: 'A watermark does not stop a determined reader from copying text, but it clearly communicates status and ownership, which is exactly what draft and sample files need. Combine it with password protection for confidential documents.' },
      { type: 'h2', text: 'Check before you send' },
      { type: 'list', items: [
        'Open the watermarked PDF and flip through all pages',
        'Confirm the watermark appears on the pages you selected',
        'Check it is positioned where it does not hide key text',
        'Send the marked file when the recipient should see the status',
      ] },
      { type: 'p', text: 'Adding a watermark to a PDF on an iPhone does not require an app or a subscription. A Safari-based tool stamps text or an image across your pages in seconds, fully on-device.' },
    ],
    faqs: [
      { q: 'How do I add a watermark to a PDF on my iPhone for free?', a: 'Open a browser-based Add Watermark tool in Safari, choose your PDF, type the watermark text or upload a logo, set the size and opacity, and download the stamped file.' },
      { q: 'Can I watermark a PDF without an app?', a: 'Yes. Markup can add a single text box on one page, but for a watermark on every page you need a Safari-based tool, which requires no app install.' },
      { q: 'Can I use a logo as a watermark on my iPhone?', a: 'Yes. Choose the image option in a watermark tool and select a logo from your Photos. A PNG with a transparent background looks best.' },
      { q: 'Does a watermark make the document unreadable?', a: 'No. Set the opacity low enough that the text stays readable. Light watermarks warn about status, while heavy ones obscure content.' },
      { q: 'Are my files uploaded when I add a watermark?', a: 'No. The tool runs in your Safari browser tab. Your PDF is processed on your iPhone and never leaves your device.' },
    ],
    related: ['how-to-add-a-watermark-to-a-pdf', 'how-to-sign-a-pdf-on-iphone', 'how-to-password-protect-a-pdf-on-iphone', 'how-to-redact-a-pdf-properly'],
  },
];