import type { BlogPost } from '../types';

export const newPosts25: BlogPost[] = [
  {
    slug: 'how-to-add-an-image-to-a-pdf',
    title: 'Add an Image to a PDF and Drag It Anywhere',
    description: 'Add an image to a PDF free — insert a photo, logo or picture, then drag it anywhere on the page and resize it. In your browser, nothing uploaded.',
    keyword: 'add image to pdf',
    category: 'Editing & Signing',
    published: '2026-09-30',
    tool: 'edit-pdf',
    blocks: [
      { type: 'p', text: 'The request arrives in a few guises — "add image to pdf", "insert picture into pdf", "put a photo on a pdf", the German "bild in pdf einfügen" or the Spanish "agregar imagen a pdf". All of them mean the same useful thing: place a picture on a page of a PDF and be able to move it where it belongs. The Edit PDF tool does exactly that in the browser, with nothing uploaded.' },
      { type: 'h2', text: 'Why add a picture to a PDF' },
      { type: 'list', items: [
        'A company logo or stamp on a letter, invoice or quote before it is sent.',
        'A screenshot dropped into a report to illustrate a step or an error.',
        'A photo added to an application form that expects images inline.',
        'A hand-drawn signature or mark saved as an image and placed where it signs the page.',
      ] },
      { type: 'h2', text: 'Add an image to your PDF, step by step' },
      { type: 'steps', items: [
        'Open the Edit PDF tool and add your PDF document.',
        'Click Add image and choose a PNG or a JPEG picture from your files.',
        'The picture appears on the current page, centred and ready to move.',
        'Drag it anywhere you want it, drag the corner handle to resize it, then download the finished PDF.', ],
      },
      { type: 'callout', title: 'PNG for sharp edges, JPEG for photos', text: 'PNG keeps crisp edges, which suits logos, stamps and text in a picture. JPEG is the everyday format for photographs. Both work; the choice is about how clean the edges need to be.' },
      { type: 'h2', text: 'Move and resize it freely' },
      { type: 'p', text: 'Placing is not final. The image stays live until you download: drag it to any position on the page, pull the corner handle to grow or shrink it, and use the arrow keys for a pixel-precise nudge. Alignment guides appear while you drag, so lines up against the page edge or against neighbouring text line up neatly instead of by eye.' },
      { type: 'h2', text: 'The image, replaced or removed, anytime' },
      { type: 'p', text: 'Select the picture and the bar offers Replace, to swap in a different photo or logo at the same spot, and Remove, to drop it back off the page. A wrong picture is a two-second fix, not a redo of the document.' },
      { type: 'h2', text: 'Pictures and text on the same page' },
      { type: 'p', text: 'The editor stacks its capabilities: click any line of the document to edit that text, click Add text to write new lines, and add or move images on the same page. A letter that needs a logo, body copy and a signature line can be finished in one pass and downloaded as one PDF.' },
      { type: 'h2', text: 'Free, private and everywhere' },
      { type: 'p', text: 'Everything runs in your browser, so the PDF and the picture never leave your device. It is free, requires no account, and works from Windows, Mac, iPhone and Android — the German "bild in pdf einfügen" search reaches the same tool as the English one.' },
    ],
    faqs: [
      { q: 'Can I move a picture anywhere on the PDF page?', a: 'Yes. After adding the image it is live: drag it to any position on the page, and alignment guides help it sit neatly against the edges or next to text.' },
      { q: 'How do I resize the image I added?', a: 'Select the picture and drag the corner handle to grow or shrink it, or use the arrow keys for fine positioning. The size you leave it at is the size that downloads.' },
      { q: 'Which image files can I add?', a: 'PNG and JPEG pictures are accepted. PNG suits logos, stamps and graphics with sharp edges; JPEG suits photographs.' },
      { q: 'Will the image stay sharp in the finished PDF?', a: 'Yes — the picture is embedded as it is, without re-compression, so its quality is preserved in the file you download.' },
      { q: 'Can I swap the picture after placing it?', a: 'Select the image and choose Replace to drop in a different PNG or JPEG in the same position and size, without redoing the rest of the page.' },
      { q: 'What does "bild in pdf einfügen" mean?', a: 'It is the German phrase for adding an image to a PDF — the same operation as "add image to pdf". The tool is language-neutral and handles documents in any language identically.' },
    ],
    related: ['how-to-edit-a-pdf-without-adobe', 'how-to-add-text-to-a-pdf', 'how-to-add-a-seal-or-stamp-image-to-a-pdf', 'how-to-add-initials-to-a-pdf'],
  },
  {
    slug: 'how-to-convert-pdf-to-powerpoint-online',
    title: 'Convert PDF to PowerPoint Online Free: PDF to PPT',
    description: 'Convert a PDF to PowerPoint online free — turn PDF pages into editable PPTX slides in your browser. No install, no upload, no sign-up.',
    keyword: 'convert pdf to powerpoint online free',
    category: 'Converting',
    published: '2026-09-30',
    tool: 'pdf-to-powerpoint',
    blocks: [
      { type: 'p', text: 'Search phrasings differ — "convert pdf to powerpoint online free", "pdf to ppt", "pdf to pptx", "convert pdf to slides", the German "pdf zu powerpoint" or the Indonesian "pdf ke ppt" — but the need is constant: take pages that live in a PDF and get them back as slides you can edit in PowerPoint. The PDF to PowerPoint tool does that in your browser with nothing uploaded.' },
      { type: 'h2', text: 'When PDF pages need to become slides' },
      { type: 'list', items: [
        'A presentation was exported to PDF for delivery and you now need the source-like file to update it.',
        'A report, one page per section, works better as slides for a meeting than as a scrolling document.',
        'Someone else\'s deck arrived as a PDF and you want to restyle the text in PowerPoint.',
      ] },
      { type: 'h2', text: 'Convert a PDF to PowerPoint, step by step' },
      { type: 'steps', items: [
        'Open the PDF to PowerPoint tool and drop in your PDF.',
        'Each page of the PDF becomes a slide in a PowerPoint (.pptx) file.',
        'Text from the PDF arrives as real, selectable text — not pictures of words.',
        'Download the file and open it in PowerPoint, Google Slides or Keynote.', ],
      },
      { type: 'p', text: 'Because it is a genuine .pptx, you can edit titles, reword bullets, move boxes and re-skin the deck afterwards — the normal PowerPoint toolset applies.' },
      { type: 'callout', title: 'Scanned pages are images first', text: 'A page that is a photograph of a document contains no text to convert, so it arrives as a slide that is mostly a picture. Run OCR first to turn the scan into real text, then convert to slides.' },
      { type: 'h2', text: 'What carries over into the slides' },
      { type: 'list', items: [
        'Headings, paragraphs and bullet text become editable text boxes.',
        'Photos and illustrations keep their places on the slide.',
        'Tables and simple diagrams come through as arranged objects.',
        'Elaborate multi-column or vector-heavy layouts convert as a faithful approximation that may need a tidy.',
      ] },
      { type: 'h2', text: 'Why convert in the browser at all' },
      { type: 'p', text: 'No PowerPoint, no plug-in and no conversion server sees the file — the whole job runs on your device. That makes it suitable for draft decks that are not ready to circulate, and it works from a phone or a borrowed computer as easily as from a desktop.' },
    ],
    faqs: [
      { q: 'Does the text become editable in PowerPoint?', a: 'Yes — the PDF\'s text is converted into real, editable text so you can reword, restyle and rearrange it in PowerPoint, Google Slides or Keynote.' },
      { q: 'Can I convert a scanned PDF to PowerPoint?', a: 'A scan is a picture until OCR adds a text layer. Run OCR on the scan first, then the recognised pages convert into editable slides.' },
      { q: 'What does "pdf ke ppt" or "pdf zu powerpoint" mean?', a: 'They are the Indonesian and German ways of saying "convert pdf to powerpoint". Both describe the same conversion, and the tool handles documents in any language.' },
      { q: 'Will the original layouts stay intact?', a: 'Mostly — pages become slides with text, images and tables in place. Very dense or multi-column designs come across as a close, editable approximation that usually needs a light tidy-up.' },
      { q: 'Is the conversion free on a phone?', a: 'Yes. The tool runs in any modern browser, iPhone and Android included, with no upload and no sign-up.' },
      { q: 'Do I need PowerPoint installed to convert?', a: 'No. The tool reads the PDF directly in your browser and produces the .pptx file; you only need PowerPoint or an equivalent app to open and edit the result.' },
    ],
    related: ['how-to-convert-pdf-to-word-without-losing-formatting', 'how-to-keep-slides-from-getting-cut-off-when-converting-to-pdf', 'how-to-create-a-pdf-from-multiple-file-types', 'how-to-convert-word-to-pdf-on-windows'],
  },
  {
    slug: 'how-to-rotate-a-pdf-page-online',
    title: 'Rotate PDF Pages Online Free at 90, 180 or 270 Degrees',
    description: 'Rotate a PDF page online free — turn a single page or the whole file by 90°, 180° or 270° and save it permanently. In your browser, nothing uploaded.',
    keyword: 'rotate pdf page online',
    category: 'Merging & Organizing',
    published: '2026-09-30',
    tool: 'rotate-pdf',
    blocks: [
      { type: 'p', text: 'Whether the query is "rotate pdf page online", "rotate pdf permanently", the German "pdf drehen" or the Spanish "rotar pdf", the task is the same: a page is sideways and it has to sit upright in the finished file — for good, not just for viewing. The Rotate PDF tool turns pages by 90°, 180° or 270° and saves the rotation into the PDF you download.' },
      { type: 'h2', text: 'Why pages end up sideways' },
      { type: 'list', items: [
        'A phone photo was scanned or turned into a PDF without straightening it first.',
        'A document mixes portrait and landscape pages, and the scanner read them all as one orientation.',
        'A file from an online converter came out upside down or rotated by half a turn.',
      ] },
      { type: 'h2', text: 'Rotate a PDF page, step by step' },
      { type: 'steps', items: [
        'Open the Rotate PDF tool and drop in your PDF.',
        'Choose the angle — 90°, 180° or 270°.',
        'Apply it to every page, or enter specific pages such as 2, 5-7 to rotate only some of them.',
        'Download the PDF with the rotation saved in the file.', ],
      },
      { type: 'p', text: 'The rotation is permanent in the output, so opening the file in any reader later shows the page the right way up — no half-screen workarounds needed.' },
      { type: 'callout', title: 'Rotate one page, not the whole file', text: 'A scanned package often has a single portrait page sitting inside an otherwise landscape document. Rotate that one page by 90° and leave the rest untouched — the finished file reads naturally from cover to cover.' },
      { type: 'h2', text: 'Choosing the right angle' },
      { type: 'list', items: [
        '90° fixes a page that is sideways — try it one way, and if it lands upside down instead, the 180° or the other quarter turn has it.',
        '180° flips an upside-down page upright without changing its width-to-height shape.',
        '270° is the other quarter turn for pages converted the opposite way round.',
      ] },
      { type: 'h2', text: 'Rotating changes the whole page' },
      { type: 'p', text: 'The rotation turns everything the page holds — text, images, tables — through the same angle as one unit. It does not re-flow paragraphs or re-wrap lines; the page is simply displayed and printed at the new orientation, which is exactly the fix a sideways page needs.' },
      { type: 'h2', text: 'After the rotation: tidy the document' },
      { type: 'p', text: 'Rotating is often one step in a longer job. Reorder the corrected pages with the Organize PDF tool, or split the upright file into its clean sections — the PDF stays fully usable through the rest of the workflow.' },
    ],
    faqs: [
      { q: 'Can I rotate just a single page in my PDF?', a: 'Yes — instead of the whole file, type the page number (such as 2) or a range (5-7) and only those pages turn by the angle you chose.' },
      { q: 'Is the rotation saved permanently?', a: 'Yes. The tool writes the rotation into the PDF you download, so every reader and printer shows the pages upright from then on.' },
      { q: 'Which angles can I rotate by?', a: '90°, 180° and 270° — the three orientations that fix a sideways, upside-down or re-oriented page. There is no free-angle option.' },
      { q: 'Does rotating reduce quality?', a: 'No. The pages are re-oriented without re-rendering the content, so the rotated PDF keeps the same sharpness and file weight as the original.' },
      { q: 'What does "pdf drehen" or "rotar pdf" mean?', a: 'They are the German and Spanish phrases for rotating a PDF — the same operation as "rotate pdf page online". The tool handles documents in any language.' },
      { q: 'Will the text be re-flowed when I rotate?', a: 'No — the whole page turns as a unit, so text, images and tables rotate together exactly as they stood, just at the new orientation.' },
    ],
    related: ['how-to-rotate-a-pdf-and-save-it', 'how-to-rotate-a-single-page-in-a-pdf', 'how-to-change-a-pdf-from-portrait-to-landscape', 'how-to-tell-if-a-pdf-has-been-edited'],
  },
  {
    slug: 'how-to-repair-a-broken-pdf-online',
    title: 'Repair a Broken or Corrupted PDF Online Free',
    description: 'Repair a broken or corrupted PDF online free — fix truncated files and damaged structure in your browser with no upload. Try repair before you give up.',
    keyword: 'repair pdf online',
    category: 'Troubleshooting',
    published: '2026-09-30',
    tool: 'repair-pdf',
    blocks: [
      { type: 'p', text: 'Under its different phrasings — "repair corrupted pdf", "fix broken pdf", "pdf reparieren" in German — sit the same moment: a file that used to open will not, and a reader shows an ominous error. The Repair PDF tool goes to work on the file\'s structure on your device, rebuilding the parts that let a reader find its pages. It is often enough to bring a stubborn file back.' },
      { type: 'h2', text: 'Why PDFs break in the first place' },
      { type: 'list', items: [
        'A download or upload that stopped halfway left the file truncated.',
        'A converter or print-to-PDF crashed before writing the trailer and cross-reference data.',
        'A file was saved from an email attachment or transfer that corrupted some bytes.',
      ] },
      { type: 'h2', text: 'Repair a PDF, step by step' },
      { type: 'steps', items: [
        'Open the Repair PDF tool and drop in the file that will not open.',
        'The tool rebuilds the document\'s structural data — the numbers that tell a reader where the pages are.',
        'Download the repaired copy and open it in any PDF reader.',
        'If it opens, re-run a size check and a quick visual pass before trusting it with the job it was meant for.', ],
      },
      { type: 'callout', title: 'Repair recovers what survived', text: 'A fixed PDF contains every page that made it safely into the original file. A page that was never written because the download stopped too early cannot be invented back — repair rescues, it does not create. So compare the recovered file with what you expected before you rely on it.' },
      { type: 'h2', text: 'When repair is not the answer' },
      { type: 'list', items: [
        'A file whose name ends in .pdf but is really a Word or scan file — rename or re-export it properly instead.',
        'An interrupted download: finish the download rather than repairing the half that arrived.',
        'A damaged source document: re-export the PDF from the original Word, Excel or design file.',
      ] },
      { type: 'h2', text: 'Preventing the breakage next time' },
      { type: 'list', items: [
        'Let downloads and uploads complete before moving the file.',
        'Export rather than print-to-PDF when a converter is available.',
        'Keep the source document, so a repaired or re-exported PDF can always be regenerated.',
      ] },
      { type: 'h2', text: 'Private by design' },
      { type: 'p', text: 'The repair runs entirely in your browser, so a file carrying personal or work data is rebuilt on your own device rather than shipped to a repair server — the German "pdf reparieren" request is handled the same, in any language, on Windows, Mac, iPhone or Android.' },
    ],
    faqs: [
      { q: 'Can I repair a corrupted PDF for free?', a: 'Yes — the Repair PDF tool is free, works in your browser with no account, and restores the structural data readers need to open the file.' },
      { q: 'Will repair recover every page?', a: 'Every page that survived into the file is recovered. Pages that were never written because a download stopped early cannot be recreated, so compare the result with what you expected.' },
      { q: 'What does "pdf reparieren" mean?', a: 'It is German for repairing a PDF — the same operation as "repair pdf online". The tool is language-neutral and handles any document.' },
      { q: 'My PDF will not open at all — can repair help?', a: 'Often yes, when the file is structurally damaged. Drop it into the tool and try the repair once; if it cannot rebuild the structure, re-export or re-download the file at the source.' },
      { q: 'Is repairing the same as converting?', a: 'No. Repair rebuilds a broken PDF\'s internal structure so it opens again; converting changes format. Run repair on a file you want to rescue, then convert if you also need a different format.' },
      { q: 'Is my PDF uploaded when I repair it?', a: 'No. The repair runs entirely in your browser and the file never leaves your device.' },
    ],
    related: ['how-to-repair-a-corrupted-pdf', 'how-to-fix-a-pdf-that-wont-print', 'why-cant-i-edit-a-pdf', 'is-it-safe-to-use-online-pdf-tools'],
  },
  {
    slug: 'how-to-unlock-a-password-protected-pdf',
    title: 'Unlock a Password-Protected PDF Online Free (Your Own File)',
    description: 'Unlock a password-protected PDF online free — when you know the password, remove the lock in your browser. No upload, no sign-up. Your own files only.',
    keyword: 'unlock pdf password',
    category: 'Security & Privacy',
    published: '2026-09-30',
    tool: 'unlock-pdf',
    blocks: [
      { type: 'p', text: 'The phrasings all point one way — "unlock pdf", "remove pdf password", "pdf password entfernen" in German, "quitar contraseña pdf" in Spanish. Legitimate use of the Unlock PDF tool is simple and specific: the file is yours, you know the password, and you want a copy that opens without typing it every time. The tool removes the lock in your browser, with nothing uploaded.' },
      { type: 'h2', text: 'Two kinds of PDF locks' },
      { type: 'list', items: [
        'An open (user) password stops the file opening until it is entered — the lock everyone pictures.',
        'A permissions lock restricts what can be done with an already-open file, such as printing or copying text, even though it opens without a password.',
      ] },
      { type: 'p', text: 'Both kinds live in the file\'s security settings, and unlocking removes the password and permissions restrictions from a fresh copy you download.' },
      { type: 'h2', text: 'Unlock a PDF you own, step by step' },
      { type: 'steps', items: [
        'Open the Unlock PDF tool and add your PDF.',
        'Enter the password the file was protected with — or leave the field empty if the file only carried a permissions lock that lets it open freely.',
        'The tool writes a copy of the file with the security removed.',
        'Download the unlocked PDF and keep it somewhere private.', ],
      },
      { type: 'callout', title: 'Only files you own or have permission for', text: 'Removing a password lock is a tool for your own documents — an invoice you protected, a contract you locked before sending, a report from your own system. Unlocking a file that is not yours without permission is not what this tool is for, and the file should stay private to you either way.' },
      { type: 'h2', text: 'If you forgot the password' },
      { type: 'list', items: [
        'Try the password you would naturally use for the document type — work, personal or mail-related passes.',
        'Regenerate the file from its source: re-export the Word, Excel or design file with no password.',
        'Ask whoever set the password, if the file came from someone else.',
      ] },
      { type: 'h2', text: 'Put a lock back on after unlocking' },
      { type: 'p', text: 'Unlocking is often one half of a workflow. Re-protect the copy afterwards with the Protect PDF tool to choose a fresh password, or tidy the file first with Edit PDF and then lock the finished version. The file is yours to manage.' },
      { type: 'h2', text: 'Private and free' },
      { type: 'p', text: 'The unlock runs entirely in your browser, so nothing about the file — its password, its contents or even its existence — crosses a server. It is free, needs no account, and works on Windows, Mac, iPhone and Android alike.' },
    ],
    faqs: [
      { q: 'Can I unlock a PDF without knowing the password?', a: 'Only for a file you own or are authorised to modify, and even then the legal route is to hold the password or regenerate the file from its source. The tool removes the lock when you provide the password.' },
      { q: 'What is the difference between an open password and a permissions lock?', a: 'An open password stops the file opening at all. A permissions lock lets the file open but restricts actions like printing or copying text. Both are removed from the unlocked copy.' },
      { q: 'Is unlocking my own PDF legal?', a: 'Removing password protection from a document you created or own is entirely legitimate — the tool exists for exactly that, and the unlocked copy stays on your device.' },
      { q: 'Will unlocking change the quality of my PDF?', a: 'No. Unlocking writes a fresh copy with the security removed; the pages, text and images are unchanged.' },
      { q: 'What does "pdf password entfernen" mean?', a: 'It is German for removing a PDF password — the same operation as "unlock pdf password". The tool is language-neutral and any document works identically.' },
      { q: 'How do I lock the PDF again afterwards?', a: 'Use the Protect PDF tool to add a new password to the finished file — a fresh lock on a copy that now opens and edits the way you want.' },
    ],
    related: ['how-to-remove-a-password-from-a-pdf', 'how-to-password-protect-a-pdf-without-adobe', 'how-to-protect-a-pdf-from-copying', 'is-it-safe-to-use-online-pdf-tools'],
  },
];