import type { BlogPost } from '../types';

export const newPosts: BlogPost[] = [
  // Article 1: How to Compress a PDF Without Losing Quality
  {
    slug: 'how-to-compress-a-pdf-without-losing-quality',
    title: 'How to Compress a PDF Without Losing Quality (2026 Guide)',
    description: 'Reduce PDF file size by up to 80% without visible quality loss. Free, browser-based compression that keeps your text crisp and images sharp.',
    keyword: 'compress pdf without losing quality',
    category: 'Compressing',
    published: '2026-08-25',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: 'A PDF that is too large to email, upload to a portal, or store efficiently is a problem everyone hits eventually. The good news: modern compression can shrink a ten-megabyte document to under two megabytes without any visible change in quality.' },
      { type: 'p', text: 'This guide explains what compression actually does to a PDF, why the quality usually survives, and exactly how to compress your file in a browser without installing anything.' },
      { type: 'h2', text: 'Why PDFs get so large in the first place' },
      { type: 'p', text: 'Most large PDFs are large because of images. A single high-resolution scan can easily be five megabytes. A presentation with twenty screenshots pushes past fifteen. The text in a PDF is already compact — a hundred-page report with no images is rarely more than a few hundred kilobytes.' },
      { type: 'p', text: 'Understanding this tells you where compression works best: anything image-heavy shrinks dramatically, while text-only files compress modestly.' },
      { type: 'h2', text: 'How compression preserves quality' },
      { type: 'p', text: 'Quality-preserving compression targets the parts of a PDF you will never miss:' },
      { type: 'list', items: [
        'Down-sampling images from 300 DPI to 150 DPI — the threshold where human eyes stop noticing a difference on screen',
        'Re-encoding images at JPEG quality 70 — visually identical at normal viewing distances',
        'Removing unused metadata, thumbnails, and embedded edit history',
        'Subsetting fonts so only the characters actually used are embedded',
        'Flattening transparent layers that add file size without visual value',
      ] },
      { type: 'callout', title: 'The 150 DPI rule', text: 'For anything viewed on screen or printed on a standard office printer, 150 DPI is indistinguishable from 300 DPI. This single adjustment typically accounts for sixty to eighty percent of the file size reduction.' },
      { type: 'h2', text: 'Compress a PDF in the browser — step by step' },
      { type: 'steps', items: [
        'Open the Compress PDF tool. Everything runs on your machine — no upload happens.',
        'Drop your PDF into the tool or click to browse for it.',
        'Pick a compression level. "Recommended" targets 150 DPI and works for most documents. Use "High" for the smallest possible file.',
        'Click Compress. Processing takes a few seconds depending on file size.',
        'Download the compressed file. Compare it to the original before sending.',
      ] },
      { type: 'h2', text: 'What compression level should you choose?' },
      { type: 'table', head: ['Level', 'Best for', 'Typical reduction', 'Quality impact'], rows: [
        ['Recommended', 'Screen viewing, email, general use', '60-80%', 'None visible'],
        ['High', 'Web uploads with size limits, archiving', '75-90%', 'Mild on photos at 100% zoom'],
        ['Low', 'Print-ready files, legal documents', '20-40%', 'None'],
      ] },
      { type: 'h2', text: 'How to verify quality after compression' },
      { type: 'steps', items: [
        'Open both the original and compressed PDFs side by side.',
        'Select text on both — it should be equally selectable in each.',
        'Zoom to 200% on an image in the compressed file. Look for softness or blocky artifacts.',
        'Compare file sizes. A 70% reduction on a photo-heavy PDF is normal; a 95% reduction usually means images were removed entirely.',
      ] },
      { type: 'h2', text: 'When compression is not enough' },
      { type: 'p', text: 'If your file is still too large after compression, the content itself is the issue. A three-hundred-page scanned report at 300 DPI is genuinely large. Options at that point include:' },
      { type: 'list', items: [
        'Splitting the PDF into logical sections and sharing only the part the recipient needs',
        'Re-scanning at 150 DPI if you still have the originals',
        'Using OCR to replace scanned images with searchable text where possible',
      ] },
      { type: 'h2', text: 'Why browser compression is better than upload-based tools' },
      { type: 'p', text: 'Traditional online compressors send your file to a server, compress it there, and return a download link. For a recipe PDF that is fine. For a financial statement, a medical record or a signed contract, it means someone else has a copy of your document for however long their servers retain it.' },
      { type: 'p', text: 'A browser-based tool never transmits your file. The compression code runs in your tab, the compressed file appears in your downloads, and nothing crosses the network. You can verify this by opening your browser developer tools and watching for upload requests — there will be none.' },
    ],
    faqs: [
      { q: 'Will compressing a PDF reduce its quality?', a: 'Visibly, no — at the Recommended compression level. Images are technically re-encoded, but the result is indistinguishable from the original for screen viewing and standard printing.' },
      { q: 'How much smaller will my PDF get?', a: 'It depends on content. Photo-heavy PDFs shrink 60-80%. Text-only PDFs shrink 10-30%. Scanned documents can shrink up to 90%.' },
      { q: 'Can I compress a password-protected PDF?', a: 'You need to unlock it first. Password-protected PDFs cannot be read by compression tools until the password is removed.' },
      { q: 'Is compressed PDF quality good enough for printing?', a: 'At the Low compression level, yes — images stay at original resolution. At Recommended, printing is fine for everyday documents. For professional print shops, use Low or skip compression entirely.' },
      { q: 'Does compression remove text or links?', a: 'No. Compression only affects images, unused metadata, and embedded resources. Text, links, bookmarks, and form fields are preserved.' },
    ],
    related: ['how-to-compress-pdf-for-email-attachment', 'how-to-reduce-pdf-file-size-to-100kb', 'combine-pdf-files-without-losing-quality'],
  },

  // Article 2: How to Sign a PDF Electronically for Free
  {
    slug: 'how-to-sign-a-pdf-electronically-for-free',
    title: 'How to Sign a PDF Electronically for Free (No Adobe, No Signup)',
    description: 'Add a legally valid electronic signature to any PDF in your browser. Draw, type, or upload your signature — no account, no software, no cost.',
    keyword: 'sign pdf electronically free',
    category: 'Editing & Signing',
    published: '2026-08-25',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'You have a PDF that needs your signature. You do not have Adobe Acrobat. You do not want to create an account. You need it done in the next two minutes.' },
      { type: 'p', text: 'Electronic signatures are legally valid in every US state and across the EU. The tool that creates them is irrelevant — what matters is that you signed with intent. Here is how to do it for free, in your browser, without installing anything.' },
      { type: 'h2', text: 'Sign a PDF in under sixty seconds' },
      { type: 'steps', items: [
        'Open the Sign PDF tool. Nothing is uploaded — the work happens on your machine.',
        'Drop your PDF into the tool or click to find it.',
        'Draw your signature with your mouse or trackpad, type your name and pick a script font, or upload a PNG image of your handwritten signature.',
        'Click on the document where the signature should go. Drag to position it and use the corners to resize.',
        'Download the signed PDF. The signature is embedded permanently in the file.',
      ] },
      { type: 'h2', text: 'Three ways to create your signature' },
      { type: 'table', head: ['Method', 'Best for', 'How it looks'], rows: [
        ['Draw', 'Most people — quick and personal', 'Your actual handwriting, captured by mouse or finger'],
        ['Type', 'Formal documents, clean appearance', 'Professional script font derived from your name'],
        ['Upload', 'Repeat use of an existing signature', 'A photo of your real signature, cropped and placed'],
      ] },
      { type: 'h2', text: 'Are electronic signatures legally valid?' },
      { type: 'p', text: 'Yes. In the United States, the ESIGN Act and UETA confirm that electronic signatures carry the same legal weight as handwritten ones for virtually all documents. In the EU, eIDAS classifies them as Simple Electronic Signatures, valid for contracts, agreements, and forms.' },
      { type: 'p', text: 'The key requirement is intent: you must have meant to sign. The software used to create the signature is not a factor. A signature drawn in a free browser tool is the same legal class as one drawn in Adobe Acrobat Pro.' },
      { type: 'callout', title: 'For most everyday documents, a simple electronic signature is sufficient', text: 'Contracts, NDAs, leases, expense reports, and approval forms all accept simple e-signatures. Only regulated industries like pharmaceuticals or government procurement typically require certificate-based digital signatures with timestamping.' },
      { type: 'h2', text: 'Signing on a phone' },
      { type: 'p', text: 'The same browser-based tool works on iPhone and Android. Open it in Safari or Chrome, load your PDF, draw your signature with your finger, and download the signed file. The experience is identical to desktop — no app installation needed.' },
      { type: 'h2', text: 'What happens to the signature after you sign' },
      { type: 'p', text: 'The signature is flattened into the PDF — it becomes part of the page content, like an image printed onto the document. This means:' },
      { type: 'list', items: [
        'The recipient can see it in any PDF reader',
        'It cannot be moved or edited after download',
        'It survives printing, emailing, and re-saving',
        'It does not require the recipient to have any special software',
      ] },
      { type: 'h2', text: 'Signing multiple pages or multiple documents' },
      { type: 'p', text: 'For documents that need your signature on several pages, place it once and note the position. You can then sign the same PDF again on additional pages, or use the tool repeatedly across separate files. There is no limit on how many times you can use a free signing tool.' },
      { type: 'h2', text: 'Why free signing tools are as good as paid ones' },
      { type: 'p', text: 'The signature is the same regardless of what created it. A rectangle with your name in a script font, placed on the correct line of a PDF, is what the recipient sees whether you used a free tool or a forty-dollar-a-month subscription. The paid tools add workflow features — audit trails, multi-party routing, template libraries — but the signature itself is identical.' },
    ],
    faqs: [
      { q: 'Is a free electronic signature legally binding?', a: 'Yes. Legal validity depends on intent and authentication, not on which software created the signature. Free tools produce the same legal class of signature as paid ones.' },
      { q: 'Can I sign a PDF on my iPhone without an app?', a: 'Yes. Open the Sign PDF tool in Safari, draw your signature with your finger, place it on the document, and download the signed file. No app installation required.' },
      { q: 'Does the recipient need special software to see my signature?', a: 'No. The signature is embedded in the PDF and visible in any PDF reader, including free ones like Preview on Mac and Chrome on any device.' },
      { q: 'Can I use the same signature on multiple documents?', a: 'Yes. Draw or upload your signature once, and use it across as many documents as you need. There is no per-document limit.' },
      { q: 'What if I need to sign a password-protected PDF?', a: 'Unlock the PDF first using an unlock tool, then sign it. Password-protected files cannot be edited until the password is removed.' },
    ],
    related: ['how-to-add-a-handwritten-signature-to-a-pdf', 'how-to-fill-out-a-pdf-form', 'how-to-redact-a-pdf-properly'],
  },

  // Article 3: How to Convert JPG to PDF Without Losing Quality
  {
    slug: 'how-to-convert-jpg-to-pdf-without-losing-quality',
    title: 'How to Convert JPG to PDF Without Losing Quality (Free Online)',
    description: 'Turn images into crisp, print-ready PDFs in your browser. Supports multiple JPGs, maintains original resolution, and requires no signup.',
    keyword: 'convert jpg to pdf without losing quality',
    category: 'Converting',
    published: '2026-08-25',
    tool: 'jpg-to-pdf',
    blocks: [
      { type: 'p', text: 'Converting a JPG to a PDF should not make your image look worse. If the result is blurrier, smaller, or oddly cropped, the tool compressed or re-sampled the image during conversion. A correct conversion wraps your image in a PDF container without touching the pixel data.' },
      { type: 'p', text: 'Here is how to do it properly, what to check afterward, and how to handle multi-image conversions.' },
      { type: 'h2', text: 'Convert a JPG to PDF in three steps' },
      { type: 'steps', items: [
        'Open the JPG to PDF tool. The conversion runs in your browser — no upload.',
        'Drag in one or more JPG files. Each image becomes a page in the resulting PDF.',
        'Download the PDF. Your images are embedded at their original resolution.',
      ] },
      { type: 'h2', text: 'Why quality is preserved during conversion' },
      { type: 'p', text: 'A PDF is a container format. When a JPG goes into a PDF, the image data is copied as-is into a PDF page. No re-encoding happens unless the tool chooses to compress the image again — which a well-built tool does not do.' },
      { type: 'p', text: 'This is the same principle as putting a photograph into a frame. The frame changes how you view it, not what the photograph looks like.' },
      { type: 'callout', title: 'The quality test', text: 'Open your original JPG and the resulting PDF side by side. Zoom to 200% on the same detail. If the PDF version is softer or blockier, the tool re-compressed your image. Use a different tool.' },
      { type: 'h2', text: 'Converting multiple JPGs into one PDF' },
      { type: 'p', text: 'If you have several images — pages of a scanned document, photos of receipts, screenshots of a conversation — you can combine them into a single PDF in one step:' },
      { type: 'steps', items: [
        'Load all the JPGs into the converter at once.',
        'Drag them into the order you want. The first image becomes page one.',
        'Convert. The result is a multi-page PDF where each image is one page.',
      ] },
      { type: 'h2', text: 'Page size and orientation' },
      { type: 'p', text: 'By default, the converter fits each image to a standard page size (usually A4 or US Letter). This means:' },
      { type: 'list', items: [
        'Landscape images get landscape pages',
        'Portrait images get portrait pages',
        'Images that do not match the page ratio get white borders',
      ] },
      { type: 'p', text: 'If you need the PDF page to match the exact pixel dimensions of your image — for example, when printing a photograph at its native aspect ratio — check for an option to use the image dimensions as the page size.' },
      { type: 'h2', text: 'When to use PDF instead of JPG' },
      { type: 'table', head: ['Use JPG when', 'Use PDF when'], rows: [
        ['Sharing a single photo', 'Sending multiple images as one document'],
        ['Posting on social media', 'Printing documents at a shop'],
        ['Web graphics and thumbnails', 'Submitting official paperwork'],
        ['Emailing one image', 'Archiving scanned records'],
      ] },
      { type: 'h2', text: 'PDF vs. keeping images as JPGs' },
      { type: 'p', text: 'A PDF with embedded images is larger than the sum of the individual JPGs, because PDF adds structural overhead. The trade-off is worth it when you need pages in order, a consistent viewer experience, or print-ready output. For web use where file size matters, JPGs are usually better.' },
      { type: 'h2', text: 'Converting on a phone' },
      { type: 'p', text: 'The browser-based converter works on iPhone and Android. Take a photo, open the tool in Safari or Chrome, load the image, and download the PDF. For converting multiple photos, select them all at once from your camera roll.' },
    ],
    faqs: [
      { q: 'Does converting JPG to PDF reduce image quality?', a: 'No — a proper conversion embeds the original JPG data into the PDF without re-compressing it. The image is pixel-identical to the original.' },
      { q: 'How do I combine multiple images into one PDF?', a: 'Load all your JPGs into the converter, arrange them in order, and convert. Each image becomes one page in the resulting PDF.' },
      { q: 'Can I convert a PNG to PDF the same way?', a: 'Yes. PNG to PDF works identically — the image data is embedded without quality loss. The same is true for GIF, BMP, and TIFF images.' },
      { q: 'Will the PDF look the same on every device?', a: 'Yes. That is the core purpose of PDF — to present content identically regardless of the device, operating system, or software viewing it.' },
      { q: 'Can I convert a JPG to a fillable PDF form?', a: 'Not directly. JPG to PDF creates a flat, non-editable page. To create fillable forms, you need a PDF editor that supports form fields.' },
    ],
    related: ['how-to-convert-jpg-to-pdf', 'how-to-convert-pdf-to-jpg-high-quality', 'how-to-convert-a-photo-to-pdf-on-your-phone'],
  },

  // Article 4: How to Password Protect a PDF Without Adobe
  {
    slug: 'how-to-password-protect-a-pdf-without-adobe',
    title: 'How to Password Protect a PDF Without Adobe (Free Method)',
    description: 'Add password protection to any PDF in your browser. No Adobe Acrobat, no account, no file upload. Your document stays on your device.',
    keyword: 'password protect pdf without adobe',
    category: 'Security & Privacy',
    published: '2026-08-25',
    tool: 'protect-pdf',
    blocks: [
      { type: 'p', text: 'You have a PDF that should not be opened by just anyone — a tax return, a contract, a medical document. Adding a password takes seconds and requires no paid software.' },
      { type: 'p', text: 'Here is how to encrypt a PDF with a password in your browser, what kind of protection you actually get, and what to do if you forget the password later.' },
      { type: 'h2', text: 'Protect a PDF with a password in four steps' },
      { type: 'steps', items: [
        'Open the Protect PDF tool. Your file stays on your device — nothing is uploaded.',
        'Drop your PDF into the tool.',
        'Enter a strong password. Mix uppercase, lowercase, numbers, and symbols.',
        'Click Protect. The encrypted PDF downloads to your device.',
      ] },
      { type: 'h2', text: 'What password protection actually does' },
      { type: 'p', text: 'PDF encryption scrambles the file contents so that a reader needs the password to decode them. There are two levels of protection:' },
      { type: 'table', head: ['Protection type', 'What it prevents', 'Who sets it'], rows: [
        ['Open password', 'Opening the file at all', 'You — the sender'],
        ['Permission password', 'Editing, printing, or copying without the password', 'You — the sender'],
      ] },
      { type: 'p', text: 'An open password is the most common choice for sensitive documents. The file simply will not open without it. A permission password lets anyone view the document but prevents modification — useful for shared reports or templates.' },
      { type: 'callout', title: 'A password is not bulletproof', text: 'Password protection prevents casual access. It does not prevent someone with technical skill from removing the password. For documents that require true confidentiality, combine password protection with secure delivery — send the password through a different channel than the file.' },
      { type: 'h2', text: 'Choosing a strong password' },
      { type: 'p', text: 'A strong password for a PDF is the same as a strong password for anything:' },
      { type: 'list', items: [
        'At least twelve characters long',
        'A mix of uppercase, lowercase, numbers, and symbols',
        'Not a word found in a dictionary',
        'Not a date, phone number, or name',
        'Different from passwords you use elsewhere',
      ] },
      { type: 'p', text: 'A passphrase like "correct-horse-battery-staple" is both strong and memorable. Avoid "password123" — it will keep out a toddler but not much else.' },
      { type: 'h2', text: 'What happens if you forget the password' },
      { type: 'p', text: 'This is the critical question, and the answer is blunt: there is no recovery mechanism built into PDF encryption. If you forget the open password, the file is gone. There is no "forgot password" link, no back door, and no legitimate tool that can crack a strong password in a useful timeframe.' },
      { type: 'p', text: 'This is also the feature, not a bug — it is what makes the protection meaningful. Treat the password the same way you would treat a key to a safe deposit box.' },
      { type: 'h2', text: 'Removing a password you no longer need' },
      { type: 'p', text: 'If you protected a PDF and later decide the password is no longer necessary, an unlock tool can remove it — but only if you know the current password. You cannot strip a password from a file you cannot open.' },
      { type: 'h2', text: 'Protecting PDFs on a phone' },
      { type: 'p', text: 'The browser-based tool works on iPhone and Android. Load the PDF in Safari or Chrome, set the password, and download the encrypted file. The process is identical to desktop.' },
    ],
    faqs: [
      { q: 'Is password-protected PDF encryption secure?', a: 'Yes — modern PDF encryption uses AES-256, the same standard used by banks and governments. A strong password makes brute-force attacks impractical.' },
      { q: 'Can someone remove the password from my PDF?', a: 'Only if they know the password. Without it, removing encryption from a properly protected PDF is not feasible with current technology.' },
      { q: 'What if I forget the password to my own PDF?', a: 'There is no recovery mechanism. The file is permanently inaccessible without the password. Always store the password somewhere safe.' },
      { q: 'Can I protect a PDF that is already password-protected?', a: 'You need to unlock it first, then re-protect it with a new or different password.' },
      { q: 'Does password protection increase file size?', a: 'Negligibly. Encryption adds a small amount of metadata but does not meaningfully change the file size.' },
    ],
    related: ['how-to-remove-a-password-from-a-pdf', 'how-to-redact-a-pdf-properly', 'is-it-safe-to-use-online-pdf-tools'],
  },

  // Article 5: How to Edit PDF Text Without Acrobat
  {
    slug: 'how-to-edit-pdf-text-without-acrobat',
    title: 'How to Edit PDF Text Without Acrobat (Free Browser Method)',
    description: 'Change text, fix typos, and update numbers in a PDF without Adobe Acrobat. Works in any browser with no signup and no file upload.',
    keyword: 'edit pdf text without acrobat',
    category: 'Editing & Signing',
    published: '2026-08-25',
    tool: 'edit-pdf',
    blocks: [
      { type: 'p', text: 'You need to change a date, fix a typo, or update a number in a PDF. You do not have Adobe Acrobat. You do not want to convert the file to Word, edit it there, and convert back — that breaks formatting and loses fonts.' },
      { type: 'p', text: 'There is a way to edit PDF text directly, in your browser, without installing anything. Here is how it works and when to use it.' },
      { type: 'h2', text: 'Edit PDF text in four steps' },
      { type: 'steps', items: [
        'Open the Edit PDF tool. The file stays on your device — nothing uploads.',
        'Drop your PDF into the tool.',
        'Click on any text block to edit it. Change what you need.',
        'Download the edited PDF. The changes are saved directly into the file.',
      ] },
      { type: 'h2', text: 'What you can edit' },
      { type: 'p', text: 'Direct text editing works on PDFs that were created digitally — documents exported from Word, Google Docs, or PDF creation software. In these files, the text is stored as real text objects that the editor can modify:' },
      { type: 'list', items: [
        'Paragraphs and body text',
        'Headings and titles',
        'Numbers in tables and forms',
        'Dates, names, and other specific values',
        'Labels and captions',
      ] },
      { type: 'h2', text: 'What you cannot edit' },
      { type: 'p', text: 'Scanned PDFs — files created by scanning paper documents — contain images of text rather than actual text. You cannot click on a scanned page and change a word, because there is no word there to change — only pixels that look like a word.' },
      { type: 'p', text: 'For scanned documents, you have two options:' },
      { type: 'list', items: [
        'Run OCR to convert the scanned images into selectable, searchable text, then edit the recognized text',
        'Use the original source document if you still have it, edit there, and re-export to PDF',
      ] },
      { type: 'callout', title: 'How to tell if your PDF has editable text', text: 'Open the PDF and try to select a word with your cursor. If the word highlights and you can copy it, the text is real and editable. If your cursor draws a rectangle over the word instead, the page is a scanned image.' },
      { type: 'h2', text: 'Editing vs. converting to Word and back' },
      { type: 'table', head: ['Method', 'Pros', 'Cons'], rows: [
        ['Direct PDF editing', 'Keeps formatting, fonts, and layout intact', 'Works on digitally-created PDFs only'],
        ['Convert to Word, edit, convert back', 'Works on any PDF', 'Breaks formatting, loses fonts, changes page layout'],
        ['OCR then edit', 'Makes scanned text editable', 'Recognition is not always perfect, adds a step'],
      ] },
      { type: 'h2', text: 'Editing on a phone' },
      { type: 'p', text: 'The browser-based editor works on iPhone and Android, though tapping small text blocks with a finger is less precise than clicking with a mouse. For quick changes — updating a date, fixing a name — it works well. For extensive editing, a desktop is easier.' },
      { type: 'h2', text: 'Saving and versioning' },
      { type: 'p', text: 'Always keep the original PDF before editing. Save your edited version with a new name or in a different folder. PDF editing is not undoable once you close the tool — if you make a mistake and save over the original, the original is gone.' },
      { type: 'h2', text: 'When to edit vs. when to recreate' },
      { type: 'p', text: 'Direct editing is the right choice for small, targeted changes — fixing a typo, updating a figure, correcting a date. If you need to rewrite entire sections, change the layout, or restructure the document, it is usually faster to edit the original source file and re-export to PDF.' },
    ],
    faqs: [
      { q: 'Can I edit any PDF without Adobe Acrobat?', a: 'Any digitally-created PDF with selectable text can be edited in a browser. Scanned PDFs need OCR first. Password-protected PDFs need to be unlocked before editing.' },
      { q: 'Will editing a PDF change its formatting?', a: 'Direct editing preserves the original formatting. The font, spacing, and layout remain as they were — only the text you change is affected.' },
      { q: 'Can I edit text in a scanned PDF?', a: 'Not directly. Run OCR first to convert the scanned images into editable text, then edit the recognized text. OCR accuracy depends on scan quality.' },
      { q: 'Does editing a PDF work on my phone?', a: 'Yes. The browser-based editor works on iPhone and Android. Quick edits are straightforward; extensive editing is easier on a desktop.' },
      { q: 'Can I undo edits after downloading?', a: 'No. Once you download the edited PDF, the changes are final. Always keep the original file before editing so you can start over if needed.' },
    ],
    related: ['how-to-add-text-to-a-pdf', 'how-to-fill-out-a-pdf-form', 'how-to-redact-a-pdf-properly'],
  },
];
