import type { BlogPost } from '../types';

export const newPosts13: BlogPost[] = [

  // Article 4: How to Convert Word to PDF on a Chromebook
  {
    slug: 'how-to-convert-word-to-pdf-on-chromebook',
    title: 'How to Convert Word to PDF on a Chromebook (Free, No Office)',
    description: 'Convert Word to PDF on your Chromebook for free — with Google Docs, the built-in save-as-PDF, or a browser tool, and no Office install needed.',
    keyword: 'how to convert word to pdf on chromebook',
    category: 'Converting',
    published: '2026-09-18',
    tool: 'word-to-pdf',
    experience: 'I convert Word documents to PDF on Chromebooks for students who hand in essays from Google Docs. The Docs export keeps their formatting exact, and a browser converter handles the docx files that Docs sometimes renders a little differently.',
    blocks: [
      { type: 'p', text: 'You wrote a report in Word and now it has to go out as a PDF so the layout opens identically on the reader\u2019s device. A Chromebook has no Microsoft Office, but you can still convert a Word document to PDF for free — no install and no sign-up.' },
      { type: 'p', text: 'Here is how to convert Word to PDF on a Chromebook, three ways.' },
      { type: 'h2', text: 'Convert a Word document with Google Docs' },
      { type: 'p', text: 'If you can get the file into Google Docs, its export creates a clean PDF. Docs opens .docx files directly:' },
      { type: 'steps', items: [
        'Go to docs.google.com and sign in with your Google account.',
        'Open the upload menu (the folder icon in the file picker) and import the .docx document.',
        'Click File, then Download, then PDF Document (.pdf).',
        'Open the PDF from your Downloads folder to check the layout.',
      ] },
      { type: 'p', text: 'Docs preserves headings, images, and most formatting well, which is why it is the first option on a Chromebook.' },
      { type: 'h2', text: 'Use the built-in print dialog' },
      { type: 'p', text: 'Every Chromebook includes a printer called Save as PDF. Any app that can print can use it, which makes it a simple two-key shortcut:' },
      { type: 'steps', items: [
        'Open the Word document in an app that displays it — Word on the web, Google Docs, or a viewer.',
        'Press Ctrl + P to open the print dialog.',
        'In Destination, choose Save as PDF.',
        'Click Save; the PDF lands in your Downloads folder.',
      ] },
      { type: 'p', text: 'This route always produces a PDF, and it works for spreadsheets and slides too.' },
      { type: 'h2', text: 'Convert any .docx with a browser tool' },
      { type: 'p', text: 'When a document does not open cleanly in Docs, a browser-based converter turns the file into a PDF in one step. It runs in Chrome and processes the file on the Chromebook:' },
      { type: 'steps', items: [
        'Open the Word to PDF tool in Chrome on your Chromebook.',
        'Drag the document into the tool, or click to browse and select it from Downloads or Google Drive.',
        'Confirm Word as the input and click convert.',
        'Download the PDF and check it before sending.',
      ] },
      { type: 'h2', text: 'Which method should you use?' },
      { type: 'table', head: ['Method', 'Best for', 'Trade-off'], rows: [
        ['Google Docs export', 'Documents you already keep in Drive', 'Keeps a copy in your Google account'],
        ['Print dialog (Ctrl + P)', 'A quick convert in any app', 'Only prints what the app shows'],
        ['Browser converter', 'Sensitive or unusual .docx files', 'Runs entirely on the Chromebook with no upload'],
      ] },
      { type: 'callout', title: 'Sensitive documents stay local', text: 'Google Docs stores your document in your Google account by design. If you would rather not upload the file to Google, a browser-based converter processes it locally on the Chromebook instead — nothing crosses the network.' },
      { type: 'h2', text: 'Check the layout before you send it' },
      { type: 'p', text: 'Open the PDF once and confirm tables, images, and headings landed where they should. Most documents convert cleanly, and a 30-second look beats a recipient telling you a table split across pages.' },
    ],
    faqs: [
      { q: 'Can I convert a Word document to PDF on a Chromebook for free?', a: 'Yes. Google Docs can export a .docx as a PDF, the built-in print dialog saves any printable file as a PDF, and a browser-based converter handles the rest — all free.' },
      { q: 'Does a Chromebook have Word to PDF built in?', a: 'It has no Microsoft Office, but the ChromeOS print dialog includes a built-in Save as PDF printer that turns printable documents into PDFs.' },
      { q: 'How do I convert a .docx to PDF without Microsoft Word?', a: 'Open the document in Google Docs and choose File, Download, PDF Document, or press Ctrl + P and pick Save as PDF as the destination.' },
      { q: 'Will my formatting stay intact when I convert?', a: 'Usually yes. Headings, images, and tables transfer cleanly, though complex layouts are worth a quick check in the finished PDF.' },
      { q: 'Are my documents uploaded when I convert them?', a: 'Google Docs keeps a copy in your Drive by design. A browser-based converter processes the file locally on your Chromebook and never uploads it.' },
    ],
    related: ['how-to-convert-word-to-pdf-on-windows', 'how-to-convert-word-to-pdf-without-losing-formatting', 'how-to-convert-google-docs-to-pdf', 'how-to-compress-pdf-on-chromebook'],
  },

  // Article 5: How to Print to PDF on a Chromebook
  {
    slug: 'how-to-print-to-pdf-on-chromebook',
    title: 'How to Print to PDF on a Chromebook (Free, Built-In)',
    description: 'Print to PDF on a Chromebook for free with the built-in dialog — save any web page or document as a PDF in seconds, with no apps or extensions.',
    keyword: 'how to print to pdf on chromebook',
    category: 'Converting',
    published: '2026-09-18',
    tool: 'compress-pdf',
    experience: 'I use Chromebook print-to-PDF for everything from saving web receipts to converting emails and grading rubrics into clean files. The built-in Save as PDF destination has shipped in ChromeOS for years and needs nothing installed.',
    blocks: [
      { type: 'p', text: 'Need a clean PDF of a web page, a receipt, an email, or a document — without a printer? Every Chromebook can print to PDF out of the box. The Save as PDF printer has been built into ChromeOS for years and turns anything printable into a PDF in seconds.' },
      { type: 'p', text: 'Here is how to print to PDF on a Chromebook for free, with nothing to install.' },
      { type: 'h2', text: 'Print to PDF from any app' },
      { type: 'steps', items: [
        'Open the page, document, or image you want to save.',
        'Press Ctrl + P to open the print dialog.',
        'In Destination, choose Save as PDF.',
        'Adjust the options — paper size, orientation, margins, and colour — then click Save.',
        'Open the PDF from your Downloads folder to check the result.',
      ] },
      { type: 'p', text: 'The file is printed to no printer at all: ChromeOS writes it straight to your Downloads folder as a PDF.' },
      { type: 'h2', text: 'Save a web page as a PDF' },
      { type: 'p', text: 'The same shortcut works in Chrome for any webpage. Enable Background graphics in the print options when the page has a coloured background or image-heavy design — otherwise those are stripped out. Pages with long content save as a multi-page PDF automatically.' },
      { type: 'h2', text: 'Convert Google Docs, Sheets, or Slides to PDF' },
      { type: 'p', text: 'Printing to PDF also covers Google documents. Open the file in Google Docs, Sheets, or Slides, press Ctrl + P, pick Save as PDF, and the file lands in Downloads with the layout intact.' },
      { type: 'h2', text: 'What print-to-PDF is good at — and not' },
      { type: 'list', items: [
        'Great for: web pages, Google documents, images, and anything any app can print',
        'Not for: combining several documents into one file, or removing pages afterwards — you get exactly what you printed',
        'Not for: editing. A PDF you create this way is a faithful snapshot; change the source and print again',
      ] },
      { type: 'callout', title: 'Already merged or trimmed', text: 'Need one PDF containing two files, or only some pages of a printed file? A browser-based merge or split tool runs in Chrome and finishes those jobs without installing anything.' },
      { type: 'h2', text: 'Shrink the result if it is too big' },
      { type: 'p', text: 'A web page with many images can come out surprisingly large — sometimes too large to attach to an email. Open the printed PDF in a browser-based compressor, pick a compression level, and download the smaller version before sharing.' },
      { type: 'p', text: 'Print to PDF is the fastest free way to create a PDF on a Chromebook. It is built in, saves directly to Downloads, and covers web pages, documents, and images — with a quick compress when the output runs large.' },
    ],
    faqs: [
      { q: 'How do I save something as a PDF on my Chromebook?', a: 'Press Ctrl + P, choose Save as PDF as the destination, and click Save. The PDF is written to your Downloads folder and needs no printer or app.' },
      { q: 'Do I need a printer to print to PDF on a Chromebook?', a: 'No. Save as PDF is a virtual printer built into ChromeOS; it creates a file instead of printing paper.' },
      { q: 'How do I save a whole web page as a PDF?', a: 'Open the page in Chrome, press Ctrl + P, choose Save as PDF, and click Save. Enable Background graphics in the options to keep colours and images.' },
      { q: 'Can I save a Google Doc as a PDF?', a: 'Yes. Open the document, press Ctrl + P, pick Save as PDF, and the layout is preserved in the PDF saved to Downloads.' },
      { q: 'Where do my PDFs get saved?', a: 'To your Downloads folder by default — the one shown in the Files app — where you can move, rename, or share them.' },
      { q: 'Is anything uploaded when I print to PDF?', a: 'No. Printing to PDF runs entirely on the Chromebook; the file is created locally from what is on your screen.' },
    ],
    related: ['how-to-convert-a-web-page-to-pdf', 'how-to-convert-google-docs-to-pdf', 'how-to-compress-pdf-on-chromebook', 'how-to-split-a-pdf-on-chromebook'],
  },
];
