import type { BlogPost } from '../types';

export const newPosts21: BlogPost[] = [
  {
    slug: 'how-to-italicize-text-in-a-pdf',
    title: 'How to Italicize Text in a PDF',
    description: 'Italicize text in a PDF with a free in-browser editor. Select any real text line, toggle italic, download. No upload, no sign-up.',
    keyword: 'italicize text in a pdf',
    category: 'Editing & Signing',
    published: '2026-09-24',
    tool: 'edit-pdf',
    blocks: [
      { type: 'p', text: 'PDFs are built to look exactly the same everywhere, which is why you cannot just triple-click a line and restyle it like you would in a word processor. To italicize existing text you need an editor that recognises the characters on the page, lets you switch on italic for the line you picked, and re-renders it — which is exactly what the Edit PDF tool does, entirely in your browser.' },
      { type: 'h2', text: 'What can be italicized in a PDF' },
      { type: 'list', items: [
        'Real characters — the normal case for PDFs exported from Word, PowerPoint or a design tool — select cleanly and italicize with one click.',
        'A scan, a photo or a page exported as an image is a picture with no characters inside, so there is nothing to italicize until you add a text layer with OCR.',
        'Italic applies to the whole text line you select, not to a single letter inside it, and not to the entire document at once.',
      ] },
      { type: 'h2', text: 'Italicize text in a PDF, step by step' },
      { type: 'steps', items: [
        'Open the Edit PDF tool and drop in your file.',
        'Click directly on the line of text you want to italicize.',
        'In the format bar, press the italic button — it toggles the style on and off, so you can compare before you commit.',
        'Adjust the line position if the new style changes how it sits, then download the updated PDF.', ],
      },
      { type: 'p', text: 'Because the page re-renders instantly, you can see the italicized line beside its neighbours and check that titles still stand out from body copy before you save.' },
      { type: 'callout', title: 'A scanned page will not italicize', text: 'If clicking a line does nothing, the text is almost certainly a picture. Run the OCR tool first to build a real text layer over the scan; the recognised lines will then behave like normal text and accept the italic style.' },
      { type: 'h2', text: 'Using italic without muddying the layout' },
      { type: 'list', items: [
        'Use italic sparingly — a word, a book title, a term — the same way you would on paper. A whole page in italic is harder to read, not easier.',
        'Keep one style per level: italic for emphasis inside body copy, bold for headings, so the hierarchy stays obvious.',
        'Slanted text takes slightly more horizontal room; if an italicized line pushes into the margin or a neighbour, drag it back or trim the wording.',
      ] },
      { type: 'h2', text: 'When to fix the source instead' },
      { type: 'p', text: 'For a one-off need — a resume you are tweaking, a header line you want to flag — editing the PDF is the fastest route. If you will keep revising the document, make the italic change in the original file and export again; rebuilding the same PDF edit repeatedly is slow work.' },
    ],
    faqs: [
      { q: 'Can I italicize a single word inside a paragraph?', a: 'The Italic button applies to the whole text line you select. To italicize one word, retype or restructure the line so that word stands alone, or use the style in the source document and re-export.' },
      { q: 'Why will a line not italicize?', a: 'The text is probably a picture. Scanned pages, photos and flattened exports contain no characters, so there is no editable text — run OCR on a scan to add a text layer first.' },
      { q: 'Does italicizing change the font or size?', a: 'No. The italic toggle only slants the existing letterforms; the font family and size are untouched, so the line keeps its place in the layout.' },
      { q: 'Can italic be removed again?', a: 'Yes. Select the line and press the italic button again to toggle the style back off, or restore an earlier version if you prefer to start over.' },
    ],
    related: ['how-to-bold-text-in-a-pdf', 'how-to-change-the-font-of-a-pdf', 'how-to-make-text-bigger-in-a-pdf', 'how-to-edit-a-pdf-without-adobe'],
  },
  {
    slug: 'how-to-move-text-in-a-pdf',
    title: 'How to Move Text in a PDF',
    description: 'Move text in a PDF to fix layout and alignment. Drag any editable text line to a new spot in your browser. Free, private, no upload.',
    keyword: 'move text in a pdf',
    category: 'Editing & Signing',
    published: '2026-09-24',
    tool: 'edit-pdf',
    blocks: [
      { type: 'p', text: 'A PDF is a fixed-layout document: every line has a stored position on the page, and a viewer draws it there every time. That is exactly why moving text in a PDF is an edit rather than a formatting change — you are changing the stored position of a real text line. The Edit PDF tool lets you do that by dragging the line to a new place in the browser.' },
      { type: 'h2', text: 'Why text sits where it does' },
      { type: 'p', text: 'Whoever created the PDF decided the layout once, at export time. Words, lines and images were placed on a virtual page and the viewer is told to keep them there forever. So there is no automatic re-layout: when you move a line, the other content does not flow around it the way it would in a Word document. The layout is yours to arrange, line by line.' },
      { type: 'h2', text: 'Move text in a PDF, step by step' },
      { type: 'steps', items: [
        'Open the Edit PDF tool and drop in your file.',
        'Click the line of text you want to reposition to select it.',
        'Drag the line to its new spot — alignment guides appear as you move so you can line it up with the rest of the page.',
        'Use the left, centre and right align buttons in the format bar to settle the line horizontally, then download.', ],
      },
      { type: 'p', text: 'The dragged line snaps cleanly where you drop it and the page re-renders live, so you can confirm the new position reads well against the surrounding content before you save.' },
      { type: 'callout', title: 'Moving a line leaves a gap', text: 'Because nothing reflows, the space the line used to occupy stays empty, and the moved text can overlap content beneath it. Plan the move so the line lands in blank space — shuffling several lines works, but it is a sequence of deliberate moves, not automatic re-layout.' },
      { type: 'h2', text: 'Aligning moved text precisely' },
      { type: 'list', items: [
        'Centre or right-align a heading relative to its block using the alignment buttons, rather than nudging it by eye.',
        'Watch the alignment guides while dragging — they light up when your line lines up with headings and margins on the page.',
        'Enlarge your view when fine-tuning; a two-pixel offset is invisible at page width but obvious in a printed copy.',
      ] },
      { type: 'h2', text: 'When moving will not help' },
      { type: 'p', text: 'For a big re-arrangement — new section order, a whole page rebuilt — a PDF is the wrong tool; make the change in the source document and export again. And a scanned page, being a picture, has no text to drag: run OCR first to add editable text, then reposition the recognised lines.' },
    ],
    faqs: [
      { q: 'Will the rest of the text move around my changed line?', a: 'No. A PDF is fixed-layout, so only the line you drag changes position; the surrounding text stays exactly where the exporter put it. You end up with your line plus the original layout.' },
      { q: 'How do I move text without it overlapping other content?', a: 'Drag the line into blank space and watch the alignment guides — they help you line up with existing margins and headings. If the line overlaps something underneath, pick a clearer spot or nudge it into a gap.' },
      { q: 'Can I move text on a scanned page?', a: 'Only after OCR. A scan stores the letters as a picture, so run the OCR tool first to create a text layer; the recognised lines can then be dragged like normal text.' },
      { q: 'What if I need a large rearrangement, not a small move?', a: 'Fix the layout in the original document and export again. Dragging many lines in a PDF is possible but slow, and the fixed-layout format makes big reshuffles error-prone.' },
      { q: 'Does moving text change how the PDF prints?', a: 'No — moving a line changes its stored position, which is exactly what a printer draws, so the printed page matches the on-screen result.' },
    ],
    related: ['how-to-change-the-text-color-in-a-pdf', 'how-to-make-text-bigger-in-a-pdf', 'how-to-add-text-to-a-pdf', 'how-to-edit-a-pdf-without-adobe'],
  },
  {
    slug: 'how-to-remove-text-from-a-pdf',
    title: 'How to Remove Text from a PDF',
    description: 'Remove unwanted text from a PDF — typos, stale labels, leftover OCR lines — with a free editor. Delete or restore any change. No upload.',
    keyword: 'remove text from a pdf',
    category: 'Editing & Signing',
    published: '2026-09-24',
    tool: 'edit-pdf',
    blocks: [
      { type: 'p', text: 'Removing text from a PDF sounds harder than it is. Each real text line in the file is an object the page draws, and an editor that recognises those objects can simply stop drawing the one you pick. The Edit PDF tool deletes a selected line in one click — and if you change your mind, you can restore your last change before saving.' },
      { type: 'h2', text: 'Deleting text is cleanup, not redaction' },
      { type: 'p', text: 'There are two very different reasons to make text disappear, and they need different tools. Removing a stale phone number, a typo, or a leftover line of OCR junk is cleanup. Hiding a name or account number from a confidential document so that it cannot be recovered is redaction, and redaction needs its own careful workflow because the goal is the permanent, irreversible removal of sensitive data — not a tidy page.' },
      { type: 'list', items: [
        'Cleanup: delete a selected line of text; the page redraws without it and your change is saved when you download.',
        'Redaction: for sensitive content, follow a proper redaction process so the underlying information cannot be dug out of the file.',
      ] },
      { type: 'h2', text: 'Remove text from a PDF, step by step' },
      { type: 'steps', items: [
        'Open the Edit PDF tool and drop in your file.',
        'Click the line of text you want to remove — it becomes a selectable text block.',
        'Press delete on the block; the page re-renders instantly without the line.',
        'If you deleted the wrong thing, restore the change before moving on, then download the finished PDF.', ],
      },
      { type: 'p', text: 'Because each line is a separate object, removing several lines works one at a time, and you can delete just a headline while keeping the paragraph underneath it untouched.' },
      { type: 'callout', title: 'What stays behind after a delete', text: 'Deleting a text line removes the characters; it does not repaint the surrounding background. A white area where the line used to sit is normal, and images or decorations behind the text remain as they were. If you need content truly unrecoverable, that is a redaction job, not a delete.' },
      { type: 'h2', text: 'Removing text on a scan or photo' },
      { type: 'p', text: 'A scanned page has no text layer, so there are no characters to select — the letters are part of a picture. To remove recognisable text from a scan you can run OCR to add a text layer and delete the recognised lines, or crop or cover the region as part of an image edit. Photo-realistic pages follow the same rule.' },
      { type: 'h2', text: 'Keep the result clean' },
      { type: 'list', items: [
        'Remove whole lines rather than retyping partial ones, so spacing does not drift mid-paragraph.',
        'Re-read the page after deleting — a removed heading can leave an empty section that reads oddly.',
        'Delete the smallest fragment that solves the problem; the more you cut, the more the fixed layout shows the gaps.',
      ] },
    ],
    faqs: [
      { q: 'Can I delete just one word or letter?', a: 'The delete button removes the selected text block, which is usually a full line. To remove a single word, edit the line, delete the word from it, or replace the line with corrected text.' },
      { q: 'What is the difference between deleting and redacting?', a: 'Deleting is cleanup — removing a line so the page reads better. Redaction is a security process for sensitive information that must be irretrievable. For confidential data, use a redaction workflow rather than a plain delete.' },
      { q: 'Will removing text leave a blank space?', a: 'Yes. Because the page does not reflow, the area the text occupied becomes blank and anything behind the text remains. That is expected behaviour for a fixed-layout file.' },
      { q: 'Can I undo a deletion if I change my mind?', a: 'Yes — the editor tracks your change, and a deleted block can be restored before you download. Once you save and close that session, re-editing is the way to fix the page.' },
      { q: 'Why can I not select text on a scanned page?', a: 'A scan is a picture with no text layer, so there are no characters to click. Run OCR first to add editable text, then delete the recognised lines you want gone.' },
    ],
    related: ['how-to-redact-a-pdf-properly', 'how-to-permanently-remove-text-from-a-pdf', 'how-to-edit-a-pdf-without-adobe', 'how-to-remove-a-watermark-from-a-pdf'],
  },
  {
    slug: 'how-to-add-initials-to-a-pdf',
    title: 'How to Add Initials to a PDF',
    description: 'Add your initials to a PDF contract or form in the browser. Type, draw or upload initials and place them on every page — free, never uploaded.',
    keyword: 'add initials to a pdf',
    category: 'Editing & Signing',
    published: '2026-09-24',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'Contracts and forms routinely ask for your initials in small boxes or on short lines, alongside a full signature at the end. Your initials are a lightweight mark that says you reviewed that page. The Sign PDF tool lets you create an initials mark — typed, drawn or uploaded — place it on the pages that call for it, and download the finished PDF, entirely in the browser.' },
      { type: 'h2', text: 'Initials are not a signature' },
      { type: 'p', text: 'A signature means you agree to the whole document; initials confirm you saw and accepted a specific page, section or amendment. That is why multi-page agreements often want your initials on every page — it makes it harder for anyone to claim pages were added or swapped after the fact. For the document to be binding you still need your full signature on the signature page alongside the initials.' },
      { type: 'h2', text: 'Add your initials to a PDF, step by step' },
      { type: 'steps', items: [
        'Open the Sign PDF tool and drop in your file.',
        'Pick the page that carries the initial box or line — the tool works page by page.',
        'Choose to type your initials, draw them, or upload a small image of your handwritten initials; set a clean, compact style and size.',
        'Place the initials on the line or box, resize them to fit, then repeat on every other page that asks for them before downloading.', ],
      },
      { type: 'p', text: 'Because initials sit in small spaces, the result looks best when the mark is short and neat. Typed initials in a simple style are the most consistent option, while uploading a transparent PNG of your handwritten initials keeps the set looking personal and authentic.' },
      { type: 'callout', title: 'Machine-printed initials are still valid', text: 'Electronic initials carry the same weight as handwritten ones when placed with the intent to authenticate — under the US E-SIGN Act, UETA and the EU\'s eIDAS rules, a simple electronic mark signed with intent is enforceable. The legal key is intent, not penmanship.' },
      { type: 'h2', text: 'Making the set look tidy' },
      { type: 'list', items: [
        'Use the same style and size on every initial line so the document looks uniform rather than patched together.',
        'Zoom in before placing — at full-page zoom a small initial is easy to drop off the line.',
        'Work through the document page by page and do not skip the middle pages; an incomplete set is the most common reason a contract comes back.',
      ] },
      { type: 'h2', text: 'Drawing or uploading instead of typing' },
      { type: 'p', text: 'If you have a touchscreen or stylus, the draw mode captures your actual motion. An uploaded image of your handwritten initials (a transparent PNG) gives the most authentic result if you want the marks to match your pen signature. Behind each option sits the same flow: create once, place on every line, download.' },
    ],
    faqs: [
      { q: 'Do initials have the same legal weight as a signature?', a: 'No. Initials confirm page-level review, while a signature means you agree to the whole document. Most contracts want initials on the pages and a full signature at the end — both are recognised electronically under E-SIGN, UETA and eIDAS.' },
      { q: 'Can I put initials on several pages at once?', a: 'The sign tool places markers per page. Create your initials mark once, then place it on each page that requires it — the same mark, resized to fit each line.' },
      { q: 'What is the cleanest way to type initials?', a: 'Typing is the most consistent option: short, neat marks in a simple style, the same on every page. For a personal touch, upload a transparent PNG of your handwritten initials instead.' },
      { q: 'Is it really private to initial a PDF this way?', a: 'Yes. The tool runs entirely in your browser — the file is processed in place and never uploaded, so a sensitive contract stays on your device until you download and send it yourself.' },
      { q: 'I missed a page. Can I add initials later?', a: 'Yes — reopen the file in the Sign PDF tool, place your initials on the missed page, and download a new copy. Just make sure the added page matches the rest of the set.' },
    ],
    related: ['how-to-sign-a-pdf-electronically-for-free', 'how-to-sign-a-pdf-without-printing-it', 'how-to-fill-out-a-pdf-form', 'how-to-add-a-handwritten-signature-to-a-pdf'],
  },
  {
    slug: 'how-to-add-a-seal-or-stamp-image-to-a-pdf',
    title: 'How to Add a Seal or Stamp Image to a PDF',
    description: 'Add a seal or stamp image to a PDF for an official look. Upload a transparent PNG, size it, place it per page. Free, in-browser, private.',
    keyword: 'add a seal or stamp image to a pdf',
    category: 'Editing & Signing',
    published: '2026-09-24',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'A round official seal, a company stamp, an approval mark — adding an image like these to a finished PDF is a common finishing step before a document goes out. The Sign PDF tool treats an image exactly like a signature: you upload the stamp file, place it on the page, size it, and download the result. No digital signature certificate is involved — it is a visual mark on the page.' },
      { type: 'h2', text: 'What a stamp image actually is' },
      { type: 'p', text: 'An image stamp is a picture drawn over the page. Your uploaded PNG or JPG is placed at a position you choose, scaled to a size that suits the document, on the page you select. It behaves like a rubber stamp laid on the paper — it covers what is below it, so place it over a clear area of the page.' },
      { type: 'h2', text: 'Add a seal or stamp to a PDF, step by step' },
      { type: 'steps', items: [
        'Open the Sign PDF tool and drop in your file.',
        'Choose the image option and upload your seal or stamp as a PNG.',
        'Adjust the size with the scale control so the stamp fits its spot without dominating the page.',
        'Place the stamp where you want it on the current page, then repeat on any other pages that need it before downloading.', ],
      },
      { type: 'p', text: 'Because each placement is on a specific page, the same stamp can sit on page one and on an approval page later in the document — you just drop it in both places with the same image file.' },
      { type: 'callout', title: 'A transparent PNG beats a JPEG here', text: 'A PNG with a transparent background lets the page show through around the seal, exactly like a real embossed stamp. A JPEG is always a rectangle, so you get white corners floating over the document. If your stamp has white in the image, cut it to a transparent PNG first.' },
      { type: 'h2', text: 'Preparing a clean stamp image' },
      { type: 'list', items: [
        'Use a PNG with transparency so only the seal itself covers the page.',
        'Export at a sensible resolution — a massive scan becomes pixel-heavy when shrunk; aim for the size it will print at.',
        'Keep the file lightweight; a small image places instantly and keeps the PDF lean.',
      ] },
      { type: 'h2', text: 'One page, every page, or a watermark?' },
      { type: 'p', text: 'Stamps and seals are page-level marks, so place them where they belong — usually the cover, an approval page, or a certification line. For continuous background branding such as a corner logo or DRAFT label across every page, a watermark is the right tool instead, because it repeats for you. A hand-placed seal is about a specific official spot, which is exactly where the stamp belongs.' },
    ],
    faqs: [
      { q: 'Does an image stamp make the PDF legally official?', a: 'A placed image is a visual mark on the page — it does not carry the cryptographic proof or verification process of a notary. It works for brand presence and internal approval; an officially notarized stamp requires the notary\'s own physical or digital notarization process.' },
      { q: 'Will the stamp look boxy or pixelated?', a: 'Only if the source has a background or too little resolution. Use a transparent PNG, size it with the scale control, and export at the size it will print at — then it reads like a real seal.' },
      { q: 'Can I put the same stamp on several pages?', a: 'Yes. Upload the image once, then place it on each page that needs the mark, sizing each placement to fit. The tool works page by page.' },
      { q: 'What is the difference from a watermark?', a: 'A watermark is applied automatically to every page for continuous branding. A stamp is placed by hand at a specific spot on specific pages — an official corner, an approval block, a cover page.' },
      { q: 'Can I remove a stamp I placed by mistake?', a: 'Re-run the flow: reopen the file the same way and place the corrected stamp, or re-export from your last good download. Placement is part of the page you save.' },
    ],
    related: ['how-to-add-a-watermark-to-a-pdf', 'how-to-add-a-handwritten-signature-to-a-pdf', 'how-to-sign-a-pdf-electronically-for-free', 'how-to-flatten-a-pdf'],
  },
];