import type { BlogPost } from '../types';

export const newPosts20: BlogPost[] = [
  {
    slug: 'how-to-change-the-text-color-in-a-pdf',
    title: 'How to Change the Text Color in a PDF',
    description: 'Change the color of text in a PDF with a free online editor. Select a line, pick a color, download. No upload, no sign-up.',
    keyword: 'change the text color in a pdf',
    category: 'Editing & Signing',
    published: '2026-09-24',
    tool: 'edit-pdf',
    blocks: [
      { type: 'p', text: 'PDFs intentionally resist editing — the text on a page could have been drawn by any tool, which is why a PDF viewer never lets you retype it or recolor it. To change the color of existing text you need an editor that recognises the characters on the page as editable text, lets you pick a color, and re-renders the line. That is exactly how the Edit PDF tool works, and it all happens in the browser.' },
      { type: 'h2', text: 'What you can recolour — and what you cannot' },
      { type: 'list', items: [
        'Text stored as real characters (the normal case for documents converted from Word, PowerPoint or a designer) is clickable and recolourable.',
        'Text that is actually a picture — a scan, a photograph, or a page exported as an image — has no characters to select and cannot be recoloured directly.',
        'Colour edits apply to the text line you select, not to a single letter, and not to the whole document in one click.',
      ] },
      { type: 'h2', text: 'Change the color of PDF text, step by step' },
      { type: 'steps', items: [
        'Open the Edit PDF tool and drop in your file.',
        'Click directly on the line of text whose color you want to change.',
        'In the format bar that appears, open the color picker and choose a new color, or use the preset swatches.',
        'Continue editing other lines or download the updated PDF.', ],
      },
      { type: 'p', text: 'The page re-renders with the new color instantly, so you can compare shades before you download and try again if a color reads wrong on screen.' },
      { type: 'callout', title: 'When a line will not select', text: 'If clicking a line does nothing, it is usually a scan or a picture — the page is a photo, so there are no characters to edit. Run the OCR tool first to add a text layer, then come back and recolor. The same applies to pages where a layout tool flattened everything into curves.' },
      { type: 'h2', text: 'Making text stand out without changing the file' },
      { type: 'p', text: 'Recolouring existing text permanently changes the document, which is right when you are finalising a draft. For notes that only you will see, or feedback you will not keep, a highlight overlay is reversible and safer — the same edit workflow can add highlighted marks without touching the original letterforms.' },
      { type: 'h2', text: 'Keep the result consistent' },
      { type: 'list', items: [
        'Use one accent color across headings and another for body copy so the change looks intentional.',
        'Check contrast before you print: dark gray body text on white prints well, while light gray can vanish on paper and on old screens.',
        'If you plan to reuse the same color scheme, convert the result back to its source format and change it there — editing in the original tool is always cheaper than editing a PDF.',
      ] },
    ],
    faqs: [
      { q: 'Can I change the color of just one word in a PDF?', a: 'Color edits apply to the text line you select. To recolor a single word, you can edit the line, retype just that word separately, or delete the line and add fresh text in the color you need.' },
      { q: 'Why can I not change the color of some PDF text?', a: 'The text is probably a picture — a scanned page, a photo, or a flattened export has no characters to recolor. Running OCR on a scan creates a text layer that the editor can then recolor.' },
      { q: 'Will changing text color affect the rest of the page?', a: 'No. A color change applies only to the selected text line, so headings, spacing and the other lines stay exactly as they were.' },
      { q: 'Does recolouring text change the font or size?', a: 'No — the color picker only touches color. Font, size and layout stay untouched, which is the point of fixing just the shade.' },
      { q: 'Is this really free and private?', a: 'Yes. The editor runs entirely in your browser and never uploads your file, so changing a text color costs nothing and your document never leaves your device.' },
    ],
    related: ['how-to-change-the-font-of-a-pdf', 'how-to-highlight-text-in-a-pdf', 'how-to-make-text-bigger-in-a-pdf', 'how-to-bold-text-in-a-pdf'],
  },
  {
    slug: 'how-to-make-text-bigger-in-a-pdf',
    title: 'How to Make Text Bigger in a PDF',
    description: 'Enlarge text in a PDF for easier reading and printing. Adjust any text line\'s font size in your browser. Free, no upload, no sign-up.',
    keyword: 'make text bigger in a pdf',
    category: 'Editing & Signing',
    published: '2026-09-24',
    tool: 'edit-pdf',
    blocks: [
      { type: 'p', text: 'Zooming a PDF in your viewer only makes the on-screen view bigger — the file itself is unchanged, so anyone you send it to still sees tiny text. Making text permanently bigger means editing the font size inside the PDF, which needs an editor that recognises the characters and can re-render them at a new size. The Edit PDF tool does exactly that in the browser.' },
      { type: 'h2', text: 'Zooming is not the same as resizing' },
      { type: 'list', items: [
        'Ctrl+ or Cmd+ zooms your view. Anyone opening the file later still sees the original tiny text.',
        'Editing the font size changes the stored document, so the bigger text travels with the file and prints bigger too.',
        'Resizing applies line by line, not to whole pages or every paragraph at once.',
      ] },
      { type: 'h2', text: 'Make PDF text bigger, step by step' },
      { type: 'steps', items: [
        'Open the Edit PDF tool and drop in your file.',
        'Click the line of text you want to enlarge.',
        'In the format bar, raise the font size (the type-in field accepts values from 4 up to 96).',
        'Drag the line to tidy its position if it now sits differently, then download.', ],
      },
      { type: 'p', text: 'Enlarging a line can push it past the width of its text block. The edit view shows you immediately, so you can drag the block back into place or reduce the size a notch until it fits.' },
      { type: 'callout', title: 'Big text on a scanned page', text: 'A scan is a picture, so there are no characters to enlarge. Run OCR first to give the page a real text layer, then the same edit view will let you resize the recognised lines. Genuine photographs have no text at all and stay as they are.' },
      { type: 'h2', text: 'Readability checklist' },
      { type: 'list', items: [
        'Body copy at roughly 12–14 pt reads comfortably on paper and on phones; headings scale up from there.',
        'If enlarging several headings, apply the same size to each so the hierarchy stays consistent.',
        'Bigger text usually needs more line spacing — if a paragraph looks cramped after resizing, re-check the page in the tool before downloading.',
      ] },
      { type: 'h2', text: 'When to enlarge in the source instead' },
      { type: 'p', text: 'For a one-off handout, editing the PDF is the fastest route. For a document you will keep revising, make the change in the original Word or presentation file and export again — redoing single lines in a PDF across many revisions is slow work.' },
    ],
    faqs: [
      { q: 'Does Ctrl+ or Cmd+ zoom actually make the text bigger?', a: 'No. Zoom only enlarges your view on screen. To make text bigger in the file itself you must edit the font size, which changes what everyone sees when they open or print the PDF.' },
      { q: 'What is the largest size I can set?', a: 'The font-size field accepts values from 4 up to 96. Beyond that range you would rebuild the page in the source document rather than edit the PDF.' },
      { q: 'What if the bigger text overlaps other content?', a: 'Select the enlarged line and drag it back into place — the edit view shows the live layout. If it still does not fit, step the size down slightly until it clears the neighbouring lines.' },
      { q: 'Can I enlarge text in a scanned PDF?', a: 'Only after OCR. A scan stores letters as a picture, so run the OCR tool to add a text layer; the recognised lines of text then behave like normal, resizable text.' },
      { q: 'Will resizing one line reflow the entire page?', a: 'No. Each line is edited independently, so only the lines you change are affected — the rest of the layout stays exactly as it was.' },
    ],
    related: ['how-to-change-the-font-of-a-pdf', 'how-to-change-the-text-color-in-a-pdf', 'how-to-add-text-to-a-pdf', 'how-to-fix-fonts-not-displaying-in-a-pdf'],
  },
  {
    slug: 'how-to-bold-text-in-a-pdf',
    title: 'How to Bold Text in a PDF',
    description: 'Bold text in a PDF to make key names and headings stand out. Edit any text line in your browser. Free, no upload, no sign-up.',
    keyword: 'bold text in a pdf',
    category: 'Editing & Signing',
    published: '2026-09-24',
    tool: 'edit-pdf',
    blocks: [
      { type: 'p', text: 'Bolding is the fastest way to make a phrase leap off a page — a client name, a price, a warning. In a PDF you cannot just select-and-bold like in Word, because the file is designed to be read, not edited. The Edit PDF tool lets you select the text line, flip the bold setting, and download a document where the emphasis is now part of the file.' },
      { type: 'h2', text: 'Bold works on real text, not pictures' },
      { type: 'list', items: [
        'Any line that is stored as characters can be toggled bold or back to regular.',
        'A scanned page or a flattened export has no characters, so bold cannot touch it until OCR adds a text layer.',
        'Retyped-over or overlay text contributes to the bold look too — the editor re-renders the whole line at the new weight.',
      ] },
      { type: 'h2', text: 'Bold text in a PDF, step by step' },
      { type: 'steps', items: [
        'Open the Edit PDF tool and drop in your file.',
        'Click the line you want to emphasise.',
        'Tap the bold button in the format bar; tap it again to switch the same line back to regular.',
        'Download the PDF with the emphasis baked in.', ],
      },
      { type: 'p', text: 'Because the change is applied to the stored text line, the bold survives being emailed, printed, and opened on any device — it is no longer a viewing trick.' },
      { type: 'callout', title: 'When bold looks weak', text: 'If a bolded line does not look appreciably heavier, the font used in the PDF has no bold design, so the editor falls back to a simulated weight. The reliable fix is to switch that line to a font that ships a true bold — then pick bold again.' },
      { type: 'h2', text: 'Emphasis that survives editing' },
      { type: 'p', text: 'Bold in the PDF is permanent styling on that line, so it holds even before you flatten or finalise. If you later need to change the wording or add more emphasis, select the line again — the editor re-renders it the same way.' },
      { type: 'h2', text: 'Bolding a whole document' },
      { type: 'p', text: 'Bold applies line by line, which is right for highlighting a paragraph but slow for making an entire report bold. For whole-document changes, convert the PDF to Word, apply formatting there, then export back to PDF — a dedicated word processor handles bulk styling far more sensibly than any PDF editor.' },
    ],
    faqs: [
      { q: 'Why does my bold text not look bold?', a: 'The font inside the PDF may lack a bold design, so the editor uses a simulated weight that some screens render lightly. Switching the line to a font with a true bold face fixes the look.' },
      { q: 'Can I bold text in a scanned PDF?', a: 'Not directly. A scan stores letters as a picture. Run OCR first to create a text layer, then select and bold the recognised lines in the editor.' },
      { q: 'Can I undo bold or revert a line to regular?', a: 'Yes. Select the same line and tap the bold button again to toggle it back to regular before you download.' },
      { q: 'Does bolding change the rest of the page layout?', a: 'No — bold applies to the selected line only. Page structure, other lines and spacing stay exactly as they were.' },
      { q: 'Can I bold everything in the file at once?', a: 'Bold works line by line. To make a whole document bold, convert it to Word, apply the formatting there and export back to PDF.' },
    ],
    related: ['how-to-change-the-font-of-a-pdf', 'how-to-highlight-text-in-a-pdf', 'how-to-change-the-text-color-in-a-pdf', 'how-to-center-text-in-a-pdf'],
  },
  {
    slug: 'how-to-center-text-in-a-pdf',
    title: 'How to Center Text in a PDF',
    description: 'Center titles, headings and short labels in a PDF right in your browser. Align any text line or drag it into place. Free, no upload.',
    keyword: 'center text in a pdf',
    category: 'Editing & Signing',
    published: '2026-09-24',
    tool: 'edit-pdf',
    blocks: [
      { type: 'p', text: 'Titles, section headings and short statements are meant to sit in the middle of the page, but PDFs arrive from every source with text glued to the left edge. Centering has two honest parts: switching the line so its letters centre inside the line box, and moving the line so the box itself sits mid-page. The Edit PDF tool does both live in the browser.' },
      { type: 'h2', text: 'Two kinds of centering' },
      { type: 'list', items: [
        'Horizontal alignment centres the letters within the width of the text line — the fix for a left-justified title.',
        'Positioning centres the entire text line on the page, which you reach by dragging the line into place with the alignment guides.',
        'Only lines stored as real characters respond to either; a scan is a picture and needs OCR before any of this works.',
      ] },
      { type: 'h2', text: 'Center a heading, step by step' },
      { type: 'steps', items: [
        'Open the Edit PDF tool and drop in your file.',
        'Click the title or line you want to center.',
        'Choose centre alignment in the format bar so the letters centre inside the line.',
        'Drag the line so the box sits visually mid-page, guided by the on-page alignment guides.',
        'Download the PDF.', ],
      },
      { type: 'p', text: 'The page preview updates as you work, so you can nudge a title until it looks optically balanced — which often differs from mathematically centered by a few pixels once ascenders and capitals are involved.' },
      { type: 'callout', title: 'Scans and flattened pages', text: 'If clicking a heading does not select it, the page is a picture. Run the OCR tool to add a text layer and the same centering controls will then work on the recognised lines. Images and shapes cannot be centered by text controls at all.' },
      { type: 'h2', text: 'Centering across multiple pages' },
      { type: 'p', text: 'Each line is centered independently. For a consistent set of chapter titles, center and position the first one, note where it sits, then apply the same alignment and position to the matching titles on the other pages so the book or report looks deliberate rather than accidental.' },
      { type: 'h2', text: 'When left-aligned is the right call' },
      { type: 'p', text: 'Centering works best for short headings and labels. Long paragraphs centred look amateurish and tire the eyes — body copy should stay aligned to one edge, and headings centered. When in doubt, center the titles and keep the prose left-aligned.' },
    ],
    faqs: [
      { q: 'Why is there no center option for my text?', a: 'Clicking a line selects it as editable text only when the PDF stores real characters. For a scanned or flattened line, run OCR first to add a text layer, then the alignment controls appear on selection.' },
      { q: 'How do I center the whole text line, not just the letters?', a: 'Line alignment centres the letters inside the line box. To position the box on the page, select the line and drag it until the alignment guides show it sitting mid-page.' },
      { q: 'Can I vertically center text on the page?', a: 'There is no auto vertical-centre button, but you can drag the selected line to the vertical middle using the guides and the live page preview for a clean optical result.' },
      { q: 'Does centering a heading change the body text?', a: 'No. Alignment applies to the single selected line, so surrounding paragraphs and spacing are untouched.' },
      { q: 'Can I center text in a fillable form field?', a: 'Interactive form fields often hide their alignment settings. If the field will not recentre, delete the entry and add a fresh text line centered over the field instead.' },
    ],
    related: ['how-to-change-the-text-color-in-a-pdf', 'how-to-add-text-to-a-pdf', 'how-to-bold-text-in-a-pdf', 'how-to-make-text-bigger-in-a-pdf'],
  },
  {
    slug: 'how-to-remove-page-numbers-from-a-pdf',
    title: 'How to Remove Page Numbers from a PDF',
    description: 'Delete page numbers from a PDF by removing the text or cropping the margin. Free in-browser tools, no upload, no sign-up.',
    keyword: 'remove page numbers from a pdf',
    category: 'Editing & Signing',
    published: '2026-09-24',
    tool: 'edit-pdf',
    blocks: [
      { type: 'p', text: 'Page numbers arrive embedded in files from every source — a downloaded report, a scanned contract, a shareholder deck — and you often need a clean version without them. The right method depends only on one thing: whether the numbers are real text or part of a scanned picture. Both cases are solvable in the browser with no upload.' },
      { type: 'h2', text: 'Method 1 — numbers stored as text' },
      { type: 'steps', items: [
        'Open the Edit PDF tool and drop in your file.',
        'Click on the page number so the line of text is selected.',
        'Choose delete — the number is removed, and the rest of the header or footer stays if the digits shared a line with other text.',
        'Repeat for the pages you want, then download.', ],
      },
      { type: 'p', text: 'Because the numbers are real characters, they delete cleanly with nothing left behind — no white boxes, no smudges, just the page without the digit.' },
      { type: 'h2', text: 'Method 2 — numbers burned into a scan' },
      { type: 'steps', items: [
        'For a scanned page the number is pixels, so no text tool can select it.',
        'Open the Crop tool instead and trim the margin that carries the page numbers.',
        'Set the crop to apply to every page so the result is consistent, then download.', ],
      },
      { type: 'p', text: 'This is the honest white-space route: by cutting the strip where the numbers live, the crop removes them and a neat trim usually improves the page too.' },
      { type: 'callout', title: 'Choose the method by the page, not the tool', text: 'Text numbers delete with the editor; image numbers crop out. A mixed file is fine — handle each page with the method its content allows. And deleting the digit never changes the other page content, so headers with a company name or a footer note keep those intact when you only remove the number.' },
      { type: 'h2', text: 'Removing numbers from only some pages' },
      { type: 'p', text: 'Both tools edit or crop page by page, so you can leave numbering on the back pages and strip it from the cover or the appendix. For a document where the numbers matter elsewhere, that selective control is exactly what you need.' },
      { type: 'h2', text: 'Add fresh numbering afterwards' },
      { type: 'p', text: 'Once the old numbers are gone, the Add Page Numbers tool lets you insert clean new ones with the format and position you choose — handy when a downloaded template has numbers in the wrong place or style. Note that new numbering applies across the pages you select rather than skipping a cover automatically.' },
    ],
    faqs: [
      { q: 'Can I remove page numbers that are part of a scan?', a: 'Yes, with the crop route. A scanned number is pixels, so it cannot be selected as text — trimming the margin that contains it removes it from every page cleanly.' },
      { q: 'Will deleting a page number remove the whole header or footer?', a: 'Only the line you delete is removed. If the page number shares a line with other header content, delete just the digits and the text beside them stays.' },
      { q: 'Can I remove numbers from only the first page?', a: 'Yes. Editing works page by page, so select and delete the number on the cover alone, or restrict any crop to that page, leaving the rest of the numbering untouched.' },
      { q: 'What if the page number will not select in the editor?', a: 'That is the sign of a scanned or flattened page. Switch to the crop method and trim the margin where the number sits — it does not need to be selectable.' },
      { q: 'Can I add new page numbers after removing the old ones?', a: 'Yes. The Add Page Numbers tool inserts fresh numbering with your chosen format and position once the old ones are gone.' },
    ],
    related: ['how-to-add-page-numbers-to-a-pdf', 'how-to-crop-a-pdf', 'how-to-black-out-text-in-a-pdf', 'how-to-remove-blank-pages-from-a-pdf'],
  },
];