import type { BlogPost } from '../types';

export const newPosts2: BlogPost[] = [
  // Article 1: How to Convert Google Docs to PDF
  {
    slug: 'how-to-convert-google-docs-to-pdf',
    title: 'How to Convert Google Docs to PDF (Free, No Software Needed)',
    description: 'Export any Google Doc as a perfectly formatted PDF in seconds. Free browser method that preserves fonts, images, and layout without installing anything.',
    keyword: 'how to convert google docs to pdf',
    category: 'Converting',
    published: '2026-08-26',
    tool: 'word-to-pdf',
    blocks: [
      { type: 'p', text: 'A Google Doc looks great in the browser, but the moment you need to email it, print it, or hand it to someone who does not use Google, you need a PDF. The conversion is built into Google Docs — but there are several ways to do it, and they do not all produce the same result.' },
      { type: 'p', text: 'Here is every method to convert a Google Doc to PDF, which one to use in each situation, and how to make sure the output looks exactly like your document.' },
      { type: 'h2', text: 'Method 1: Download as PDF (fastest)' },
      { type: 'steps', items: [
        'Open your Google Doc.',
        'Click File in the top menu.',
        'Hover over Download.',
        'Click PDF Document (.pdf).',
        'The PDF downloads to your default Downloads folder, named after your document.',
      ] },
      { type: 'p', text: 'This is the method to use ninety percent of the time. It produces a PDF that is visually identical to your document — same fonts, same images, same page breaks, same headers and footers.' },
      { type: 'h2', text: 'Method 2: Email as PDF attachment' },
      { type: 'steps', items: [
        'Open your Google Doc.',
        'Click File, then Email this file.',
        'In the Attach as dropdown, select PDF.',
        'Enter the recipient, subject, and message.',
        'Click Send. The PDF is attached directly from Google Docs to Gmail.',
      ] },
      { type: 'p', text: 'This saves a step when you know the PDF is going to someone via email. The conversion happens server-side and the result is identical to the download method.' },
      { type: 'h2', text: 'Method 3: Print to PDF (browser method)' },
      { type: 'steps', items: [
        'Press Ctrl+P on Windows or Cmd+P on Mac.',
        'In the print destination, choose Save as PDF.',
        'Adjust orientation, margins, or page range if needed.',
        'Click Save and choose where to store the file.',
      ] },
      { type: 'p', text: 'This method works from any browser and gives you control over margins and page ranges before saving. It is useful when you want to exclude certain pages or change the layout slightly.' },
      { type: 'callout', title: 'When to use each method', text: 'Use Download for the quickest result. Use Email when sending directly to someone. Use Print when you need to adjust margins, page range, or orientation before saving.' },
      { type: 'h2', text: 'What the PDF preserves from your Google Doc' },
      { type: 'list', items: [
        'All text formatting — bold, italic, headings, lists, and tables',
        'Images, charts, and embedded drawings',
        'Headers, footers, and page numbers',
        'Page breaks and section breaks',
        'Comments and suggestions are stripped — the PDF shows only the final content',
      ] },
      { type: 'h2', text: 'Converting on iPhone or Android' },
      { type: 'p', text: 'The Google Docs mobile app supports PDF export directly:' },
      { type: 'steps', items: [
        'Open the Google Docs app and open your document.',
        'Tap the three-dot menu in the top right.',
        'Tap Share and export.',
        'Tap Save as, then select PDF Document.',
        'The PDF opens in a preview. Save it to your files or share it directly.',
      ] },
      { type: 'h2', text: 'Converting multiple Google Docs at once' },
      { type: 'p', text: 'Google Drive lets you batch-export multiple documents as PDFs:' },
      { type: 'steps', items: [
        'Open Google Drive.',
        'Select multiple Docs files by holding Ctrl or Cmd and clicking each one.',
        'Right-click and choose Download.',
        'Drive compresses them into a single ZIP file containing each document as a PDF.',
      ] },
      { type: 'p', text: 'For more than a handful of documents, this is significantly faster than downloading each one individually.' },
      { type: 'h2', text: 'Converting Google Docs that contain tables and charts' },
      { type: 'p', text: 'Tables and charts in Google Docs export cleanly to PDF. Embedded Google Sheets charts maintain their visual appearance. However, interactive elements like dropdowns, checkboxes, and smart chips are flattened into static content — which is usually what you want in a PDF.' },
      { type: 'h2', text: 'Using a PDF tool for further processing' },
      { type: 'p', text: 'Once your Google Doc is a PDF, you can use additional tools to compress it for email, password-protect it for sharing, merge it with other PDFs, or add page numbers for a professional presentation. These steps take seconds and require no software installation.' },
    ],
    faqs: [
      { q: 'Can I convert a Google Doc to PDF without a Google account?', a: 'No. You need to be signed in to access and export the document. However, the person viewing a shared link does not need an account.' },
      { q: 'Does the PDF look exactly like my Google Doc?', a: 'Yes. Google uses its own PDF export engine, so the output is visually identical to what you see in the editor — same fonts, images, layout, and formatting.' },
      { q: 'Can I convert a Google Doc to PDF on my phone?', a: 'Yes. Open the Google Docs app, tap the three-dot menu, select Share and export, then Save as PDF Document.' },
      { q: 'How do I convert multiple Google Docs to PDF at once?', a: 'Select multiple files in Google Drive, right-click, and choose Download. Drive exports them all as PDFs inside a single ZIP file.' },
      { q: 'Will comments and suggestions appear in the PDF?', a: 'No. The PDF shows only the final content. Comments, suggestions, and edit history are stripped during export.' },
    ],
    related: ['how-to-convert-word-to-pdf', 'how-to-convert-images-to-pdf', 'how-to-compress-a-pdf-without-losing-quality'],
  },

  // Article 2: How to Share Large PDF Files via Email
  {
    slug: 'how-to-share-large-pdf-files-via-email',
    title: 'How to Share Large PDF Files via Email (When Attachments Are Too Big)',
    description: 'Email a PDF of any size without hitting attachment limits. Free methods to share large PDFs via link, compression, or splitting — no account needed.',
    keyword: 'how to share large pdf files via email',
    category: 'Merging & Organizing',
    published: '2026-08-26',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: 'You have a fifty-megabyte PDF and an email client with a twenty-five-megabyte attachment limit. The file will not send. You could compress it, split it, or upload it somewhere and send a link instead. Which approach works best depends on the file, the recipient, and what you need to preserve.' },
      { type: 'p', text: 'Here are four methods to share large PDFs via email, ranked from simplest to most flexible.' },
      { type: 'h2', text: 'Method 1: Compress the PDF to fit the limit' },
      { type: 'p', text: 'If your PDF is between twenty-five and fifty megabytes, compression is usually the fastest fix. Reducing image resolution from 300 DPI to 150 DPI typically cuts file size by sixty to eighty percent with no visible quality loss for screen viewing.' },
      { type: 'steps', items: [
        'Open the Compress PDF tool in your browser.',
        'Drop your PDF into the tool.',
        'Pick a compression level. "Recommended" works for most documents.',
        'Download the compressed file and attach it to your email.',
      ] },
      { type: 'callout', title: 'When compression is enough', text: 'If your PDF is under fifty megabytes and image-heavy, compression will almost always bring it under the twenty-five megabyte email limit without any visible quality loss.' },
      { type: 'h2', text: 'Method 2: Split the PDF into smaller parts' },
      { type: 'p', text: 'When compression alone is not enough, or when you only need to share a portion of the document, splitting the PDF into smaller files lets you send each part as a separate attachment.' },
      { type: 'steps', items: [
        'Open the Split PDF tool.',
        'Drop your PDF into the tool.',
        'Choose how to split — by page range, every N pages, or by section.',
        'Download the individual files and attach them to separate emails.',
      ] },
      { type: 'p', text: 'Tell the recipient which email contains which pages, or send them in a single email with multiple attachments if the combined size fits.' },
      { type: 'h2', text: 'Method 3: Share via a download link' },
      { type: 'p', text: 'For PDFs that remain too large even after compression, uploading the file and sharing a link avoids attachment limits entirely. Several free services let you upload a PDF and generate a shareable link with no account required.' },
      { type: 'table', head: ['Service', 'Free limit', 'Account needed', 'Link expires'], rows: [
        ['WeTransfer', '2 GB', 'No', '7 days'],
        ['Google Drive', '15 GB', 'Yes (Google)', 'Until you delete'],
        ['Dropbox', '2 GB', 'Yes', 'Until you delete'],
        ['TransferNow', '5 GB', 'No', '7 days'],
      ] },
      { type: 'p', text: 'Upload the file, copy the link, and paste it into your email. The recipient clicks the link and downloads the PDF — no special software required.' },
      { type: 'h2', text: 'Method 4: Compress and split together' },
      { type: 'p', text: 'For very large PDFs — scanned documents, photo-heavy reports, multi-hundred-page files — combining compression with splitting gives the best results:' },
      { type: 'steps', items: [
        'Compress the PDF first to reduce overall size.',
        'If it is still over the attachment limit, split it into sections.',
        'Send each section as a separate email attachment.',
      ] },
      { type: 'p', text: 'This approach keeps everything as direct email attachments rather than relying on external links, which some recipients prefer for security reasons.' },
      { type: 'h2', text: 'Email attachment limits by provider' },
      { type: 'table', head: ['Provider', 'Attachment limit', 'Workaround'], rows: [
        ['Gmail', '25 MB', 'Google Drive link for larger files'],
        ['Outlook / Hotmail', '20 MB', 'OneDrive link for larger files'],
        ['Yahoo Mail', '25 MB', 'Compress or use a sharing service'],
        ['Apple Mail (iCloud)', '20 MB', 'Mail Drop for files up to 5 GB'],
        ['ProtonMail', '25 MB', 'Proton Drive link for larger files'],
      ] },
      { type: 'h2', text: 'Which method to choose' },
      { type: 'list', items: [
        'Under 50 MB — compress the PDF. It will almost always fit.',
        '50 MB to 200 MB — compress first, then split if still too large.',
        'Over 200 MB — upload and share a link. Compression alone will not help.',
        'Recurring large files — set up a cloud folder and email the link.',
      ] },
      { type: 'h2', text: 'Sharing large PDFs on a phone' },
      { type: 'p', text: 'All the methods above work on iPhone and Android. Compress the PDF in your mobile browser, split it using a browser-based tool, or upload to WeTransfer or Google Drive from your phone and share the link via email or messaging apps.' },
    ],
    faqs: [
      { q: 'What is the maximum PDF file size I can email?', a: 'It depends on your email provider. Gmail and Yahoo allow 25 MB, Outlook allows 20 MB. For larger files, compress the PDF or share it via a link instead.' },
      { q: 'Will compressing a PDF reduce its quality?', a: 'At the recommended compression level, quality reduction is not visible for screen viewing or standard printing. Images are technically re-encoded but look identical at normal viewing distances.' },
      { q: 'Can I split a PDF and send the parts in one email?', a: 'Yes, as long as the combined size of all attachments stays under your provider limit. If not, send each part in a separate email.' },
      { q: 'Is sharing via a download link secure?', a: 'Link-based sharing is as secure as the service you use. For sensitive documents, choose a service that offers password protection or encryption on the shared link.' },
      { q: 'How do I know if my PDF will fit as an attachment?', a: 'Right-click the file and check its size. If it is under 20 MB, it will fit in any email client. If it is between 20 and 25 MB, it will fit in Gmail but not Outlook.' },
    ],
    related: ['how-to-compress-a-pdf-without-losing-quality', 'how-to-reduce-pdf-file-size-for-email', 'how-to-split-a-pdf'],
  },

  // Article 3: How to Combine Images into One PDF
  {
    slug: 'how-to-combine-images-into-one-pdf',
    title: 'How to Combine Images into One PDF (JPG, PNG, Any Format)',
    description: 'Merge multiple images — photos, scans, screenshots — into a single PDF in your browser. Free, no signup, and works with JPG, PNG, and more.',
    keyword: 'how to combine images into one pdf',
    category: 'Merging & Organizing',
    published: '2026-08-26',
    tool: 'jpg-to-pdf',
    blocks: [
      { type: 'p', text: 'You have ten photos of receipts, five scanned pages, or a set of screenshots that need to become a single document. Sending them as individual image files is messy — some get lost, the order gets scrambled, and the recipient has to open each one separately.' },
      { type: 'p', text: 'Combining images into one PDF gives you a single, ordered file that opens identically on every device. Here is how to do it in your browser in seconds.' },
      { type: 'h2', text: 'Combine images into a PDF in three steps' },
      { type: 'steps', items: [
        'Open the JPG to PDF tool in your browser.',
        'Drag in all your images. They can be JPG, PNG, or a mix of formats.',
        'Arrange them in the order you want. The first image becomes page one.',
        'Click Convert. The result is a multi-page PDF with one image per page.',
      ] },
      { type: 'p', text: 'The conversion runs entirely in your browser — no files are uploaded to any server. The original image quality is preserved because the image data is embedded into the PDF without re-encoding.' },
      { type: 'h2', text: 'Supported image formats' },
      { type: 'table', head: ['Format', 'Works?', 'Notes'], rows: [
        ['JPG / JPEG', 'Yes', 'Most common format for photos and scans'],
        ['PNG', 'Yes', 'Best for screenshots and images with transparency'],
        ['GIF', 'Yes', 'Static frames are embedded; animation is lost'],
        ['BMP', 'Yes', 'Large file size — consider converting to JPG first'],
        ['TIFF', 'Yes', 'Common in professional scanning'],
        ['HEIC', 'Yes', 'iPhone photo format — converted automatically'],
      ] },
      { type: 'h2', text: 'How to order the images correctly' },
      { type: 'p', text: 'The order you add images is the order they appear as pages. If your images are named with numbers — scan_01.jpg, scan_02.jpg, and so on — sort them by name before uploading. Most file browsers let you sort by name with a single click.' },
      { type: 'p', text: 'If you need to rearrange after adding them, drag and drop the thumbnails within the tool to set the correct page order before converting.' },
      { type: 'callout', title: 'Naming tip', text: 'If your images are not numbered, rename them before combining: 01_front.jpg, 02_page2.jpg, 03_back.jpg. This ensures the PDF pages are in the right order even if the tool does not offer drag-and-drop reordering.' },
      { type: 'h2', text: 'Page size and orientation' },
      { type: 'p', text: 'By default, each image is fitted to a standard page size — usually A4 or US Letter. This means:' },
      { type: 'list', items: [
        'Landscape images get landscape pages automatically',
        'Portrait images get portrait pages',
        'Images that do not match the page ratio get white borders',
        'Very small images may appear centered with large white margins',
      ] },
      { type: 'p', text: 'If you need the PDF page to exactly match the pixel dimensions of your image — for example, when printing a photograph at its native aspect ratio — check for an option to use image dimensions as the page size.' },
      { type: 'h2', text: 'Combining images on iPhone or Android' },
      { type: 'p', text: 'The browser-based tool works on mobile devices. Open it in Safari or Chrome, select images from your camera roll or file manager, arrange them, and download the PDF. The process is identical to desktop.' },
      { type: 'p', text: 'On iPhone, you can select multiple photos directly from the Photos app. On Android, select multiple images from your gallery or file manager.' },
      { type: 'h2', text: 'When to use PDF instead of sending images directly' },
      { type: 'list', items: [
        'When you need images in a specific order — PDFs enforce page sequence',
        'When submitting to a form or portal that requires PDF',
        'When printing — a PDF with images prints as a document, not as separate files',
        'When archiving — a single PDF is easier to store and search than dozens of image files',
        'When emailing — one attachment is cleaner than twenty',
      ] },
      { type: 'h2', text: 'PDF file size after combining images' },
      { type: 'p', text: 'The resulting PDF is approximately the sum of all the individual image files, plus a small amount of PDF overhead. If the combined file is too large, compress it after combining to reduce size without losing visible quality.' },
    ],
    faqs: [
      { q: 'Can I combine JPG and PNG images in the same PDF?', a: 'Yes. The tool handles mixed formats — each image is converted and embedded regardless of its original format.' },
      { q: 'Does combining images into a PDF reduce their quality?', a: 'No. The images are embedded into the PDF at their original resolution. No re-compression happens during conversion.' },
      { q: 'How many images can I combine into one PDF?', a: 'There is no hard limit. The practical limit depends on your browser memory — most browsers handle hundreds of images without issue.' },
      { q: 'Can I rearrange the page order after converting?', a: 'Not within the JPG to PDF tool. Rearrange the images before converting. If you need to reorder after, use an Organize PDF tool.' },
      { q: 'Will the PDF look the same on every device?', a: 'Yes. That is the core purpose of PDF — to present content identically regardless of the device, operating system, or software viewing it.' },
    ],
    related: ['how-to-convert-jpg-to-pdf-without-losing-quality', 'how-to-convert-images-to-pdf', 'how-to-merge-pdf-files'],
  },

  // Article 4: How to Extract Text from a Scanned PDF Without Software
  {
    slug: 'how-to-extract-text-from-scanned-pdf-without-software',
    title: 'How to Extract Text from a Scanned PDF Without Software (Free OCR)',
    description: 'Copy text from scanned PDFs and images for free using browser-based OCR. No Adobe, no installation, no account — just paste your file and extract.',
    keyword: 'how to extract text from scanned pdf without software',
    category: 'Converting',
    published: '2026-08-26',
    tool: 'ocr-pdf',
    blocks: [
      { type: 'p', text: 'You have a scanned document — a contract, a receipt, a page from a book — and you need the text out of it. You select the text, nothing happens. You try to copy it, and you get an image instead. That is because scanned PDFs contain pictures of text, not actual text characters.' },
      { type: 'p', text: 'OCR — Optical Character Recognition — is the technology that reads the images and converts them into selectable, copyable text. Here is how to use it for free in your browser, without installing any software.' },
      { type: 'h2', text: 'Extract text from a scanned PDF in four steps' },
      { type: 'steps', items: [
        'Open the OCR PDF tool in your browser.',
        'Drop your scanned PDF into the tool.',
        'Click Extract. The tool recognizes text in each page.',
        'Copy the extracted text or download the searchable PDF.',
      ] },
      { type: 'p', text: 'The OCR runs in your browser — no file upload to any server. Your document stays on your device throughout the process.' },
      { type: 'h2', text: 'What OCR does and does not do' },
      { type: 'list', items: [
        'Converts images of text into real, selectable text characters',
        'Makes the text searchable within the PDF',
        'Enables copy-paste from the document',
        'Preserves the original layout and formatting',
        'Works on any language the OCR engine supports',
      ] },
      { type: 'callout', title: 'OCR accuracy depends on scan quality', text: 'Clean, high-resolution scans produce near-perfect recognition. Low-resolution or blurry scans may have errors — typically in special characters, handwritten text, or unusual fonts. Always proofread the output.' },
      { type: 'h2', text: 'When you need OCR' },
      { type: 'table', head: ['Scenario', 'Do you need OCR?'], rows: [
        ['Scanned paper document', 'Yes — the text is an image'],
        ['PDF exported from a word processor', 'No — text is already real'],
        ['Photo of a document taken with your phone', 'Yes — it is an image'],
        ['PDF created by scanning and OCR was applied', 'No — text is already recognized'],
        ['Screenshot containing text', 'Yes — it is an image'],
      ] },
      { type: 'h2', text: 'How to tell if a PDF has real text or images of text' },
      { type: 'steps', items: [
        'Open the PDF in any viewer.',
        'Try to select a word with your cursor.',
        'If the word highlights and you can copy it, the text is real — no OCR needed.',
        'If your cursor draws a selection box over the word instead, the page is an image — OCR is required.',
      ] },
      { type: 'h2', text: 'Extracting text on a phone' },
      { type: 'p', text: 'The browser-based OCR tool works on iPhone and Android. Take a photo of a document, open the tool in Safari or Chrome, load the image or PDF, and extract the text. The recognized text can be copied directly to your clipboard or downloaded as a text file.' },
      { type: 'h2', text: 'What to do after extracting text' },
      { type: 'p', text: 'Once the text is extracted, you can:' },
      { type: 'list', items: [
        'Copy and paste it into a document, email, or note',
        'Search within the PDF for specific words or phrases',
        'Edit the text using a PDF editor',
        'Translate the content into another language',
        'Use the searchable PDF as a reference document',
      ] },
      { type: 'h2', text: 'Why browser-based OCR is better than downloadable software' },
      { type: 'p', text: 'Traditional OCR software requires installation, often costs money, and may send your documents to external servers for processing. Browser-based OCR runs entirely on your machine — nothing uploads, nothing installs, and nothing costs anything.' },
      { type: 'p', text: 'For occasional use — extracting a page or two from a scanned document — browser-based OCR is faster, safer, and simpler than installing dedicated software.' },
    ],
    faqs: [
      { q: 'How accurate is browser-based OCR?', a: 'For clean, high-resolution scans of printed text, accuracy is typically 95-99%. Handwritten text, low-resolution scans, and unusual fonts may produce more errors.' },
      { q: 'Does OCR work on handwritten text?', a: 'It depends on the handwriting. Printed handwriting with clear letterforms is often recognized well. Cursive or messy handwriting may produce significant errors.' },
      { q: 'Can I extract text from a specific page only?', a: 'Yes. Most OCR tools let you process specific pages or page ranges instead of the entire document.' },
      { q: 'Will OCR change the appearance of my PDF?', a: 'OCR adds a text layer behind the images — the visual appearance does not change. The text becomes selectable and searchable while the document looks exactly the same.' },
      { q: 'Does OCR work on non-English text?', a: 'Yes. Modern OCR engines support dozens of languages. Select the correct language before processing for the best accuracy.' },
    ],
    related: ['how-to-edit-pdf-text-without-acrobat', 'how-to-convert-pdf-to-word', 'how-to-add-text-to-a-pdf'],
  },

  // Article 5: How to Make a PDF on iPhone
  {
    slug: 'how-to-make-a-pdf-on-iphone',
    title: 'How to Make a PDF on iPhone (5 Free Methods, No App Needed)',
    description: 'Create PDFs directly on your iPhone from photos, web pages, documents, and more. Free methods using built-in iOS tools — no app installation required.',
    keyword: 'how to make a pdf on iphone',
    category: 'Converting',
    published: '2026-08-26',
    tool: 'word-to-pdf',
    blocks: [
      { type: 'p', text: 'Your iPhone can create PDFs from almost anything — a web page, a photo, a document, or a note — without installing a single app. iOS has built-in PDF creation that most people never discover because it hides behind the Share button.' },
      { type: 'p', text: 'Here are five ways to create PDFs on your iPhone, each for a different type of content.' },
      { type: 'h2', text: 'Method 1: Save a web page as PDF' },
      { type: 'steps', items: [
        'Open Safari and navigate to the page you want to save.',
        'Tap the Share button (the square with an arrow).',
        'Scroll down and tap Print.',
        'Pinch outward on the print preview to expand it to full screen.',
        'Tap the Share button again in the top right.',
        'Tap Save to Files or choose an app to share it.',
      ] },
      { type: 'p', text: 'The result is a PDF of the entire web page, including images and formatting. This works for articles, recipes, confirmation pages, and any content you want to preserve exactly as it appears.' },
      { type: 'h2', text: 'Method 2: Convert a photo to PDF' },
      { type: 'steps', items: [
        'Open the Photos app and select one or more photos.',
        'Tap the Share button.',
        'Tap Print.',
        'Pinch outward on the print preview.',
        'Tap the Share button and choose Save to Files.',
      ] },
      { type: 'p', text: 'Selecting multiple photos creates a multi-page PDF with one photo per page. This is useful for turning receipt photos, document scans, or a series of images into a single file.' },
      { type: 'callout', title: 'Quick tip', text: 'If you scan documents with the Notes app, they are already PDFs. Open Notes, tap the scanned document, tap the share button, and save or send it directly.' },
      { type: 'h2', text: 'Method 3: Create a PDF from a document' },
      { type: 'p', text: 'If you have a document in Google Docs, Microsoft Word, or another app, most of them offer direct PDF export:' },
      { type: 'list', items: [
        'Google Docs: open the document, tap the three-dot menu, tap Share and export, then Save as PDF',
        'Microsoft Word: open the document, tap the three-dot menu, tap Share as PDF',
        'Apple Pages: open the document, tap the three-dot menu, tap Export, then choose PDF',
        'Dropbox: open the file, tap the three-dot menu, tap Export, then PDF',
      ] },
      { type: 'h2', text: 'Method 4: Create a PDF from a note or email' },
      { type: 'steps', items: [
        'Open the Notes app or Mail app.',
        'Open the note or email you want to save as PDF.',
        'Tap the Share button.',
        'Tap Print to open the print preview.',
        'Pinch outward to expand to full screen.',
        'Tap Share and choose Save to Files.',
      ] },
      { type: 'p', text: 'This converts any content that can be printed into a PDF. It is especially useful for saving emails with attachments, confirmation messages, or important conversations.' },
      { type: 'h2', text: 'Method 5: Create a PDF from a blank page' },
      { type: 'p', text: 'If you need to create a PDF from scratch — a blank form, a quick note, or a template:' },
      { type: 'steps', items: [
        'Open the Notes app.',
        'Create a new note.',
        'Type your content.',
        'Tap the Share button, then tap Print.',
        'Pinch outward on the preview.',
        'Tap Share and Save to Files as PDF.',
      ] },
      { type: 'p', text: 'For more complex PDFs — forms with fields, styled documents, or multi-page layouts — use a browser-based PDF tool that runs on your iPhone without installing anything.' },
      { type: 'h2', text: 'Where PDFs are saved on iPhone' },
      { type: 'p', text: 'When you save a PDF, it goes to the Files app by default. You can choose a specific folder, save it to iCloud Drive, or save it to a third-party storage app. The PDF is also available in the Files app recent files list for quick access.' },
      { type: 'h2', text: 'Sharing PDFs from iPhone' },
      { type: 'p', text: 'Once created, share the PDF via AirDrop, email, messaging apps, or upload it to cloud storage. The PDF is a standard file that can be opened on any device — the recipient does not need an iPhone.' },
    ],
    faqs: [
      { q: 'Do I need to install an app to create PDFs on iPhone?', a: 'No. iOS has built-in PDF creation through the Share and Print functions. No third-party app is required for basic PDF creation.' },
      { q: 'Can I create a PDF from a photo on my iPhone?', a: 'Yes. Open the photo in the Photos app, tap Share, tap Print, pinch outward on the preview, and save the result as a PDF.' },
      { q: 'How do I save a web page as a PDF on iPhone?', a: 'Open the page in Safari, tap Share, tap Print, pinch outward to expand the preview, then tap Share again and save to Files.' },
      { q: 'Can I combine multiple photos into one PDF on iPhone?', a: 'Yes. Select multiple photos in the Photos app, tap Share, then Print. The print preview becomes a multi-page PDF with one photo per page.' },
      { q: 'Where do PDFs saved on iPhone go?', a: 'They go to the Files app. You can choose a specific folder or save to iCloud Drive when prompted.' },
    ],
    related: ['how-to-convert-jpg-to-pdf-without-losing-quality', 'how-to-convert-google-docs-to-pdf', 'how-to-combine-images-into-one-pdf'],
  },
];
