import type { BlogPost } from '../types';

export const newPosts14: BlogPost[] = [
  // Article 1: Scan documents to PDF with your phone
  {
    slug: 'how-to-scan-documents-to-pdf-with-your-phone',
    title: 'How to Scan Documents to PDF With Your Phone (Free)',
    description: 'Scan documents to PDF with your phone for free, right in your browser — auto-detects each page, straightens it, and saves a multi-page PDF on your device.',
    keyword: 'how to scan documents to pdf with your phone',
    category: 'Converting',
    published: '2026-09-19',
    updated: '2026-10-04',
    tool: 'scan-pdf',
    experience: 'I scan contracts, receipts, and signed pages into PDFs from my phone several times a week. The camera tool that auto-detects and straightens the page before it captures is what turned scanning from a chore into a two-second habit for me.',
    blocks: [
      { type: 'p', text: 'A document needs to become a PDF and the only thing near you is a phone. That is enough. A modern phone camera produces a perfectly good scan, and you can scan documents to PDF with your phone for free inside the browser, without installing a scanner app or signing up anywhere.' },
      { type: 'p', text: 'Here is the whole process, from the first page to a PDF you can send, plus the fixes for the things that usually go wrong.' },
      { type: 'h2', text: 'How do I scan a document to PDF with my phone?' },
      { type: 'p', text: 'Open a browser-based scanner such as Scan PDF on your phone and allow camera access. Hold the phone over the page: it finds the page edges and captures automatically when you hold steady. Turn to the next page and it captures again. Then review, tap Save PDF and download one multi-page PDF.' },
      { type: 'steps', items: [
        'Open Scan PDF in your phone’s browser and tap Open camera.',
        'Allow camera access when the browser asks.',
        'Hold the phone over the page until it captures by itself.',
        'Turn the page; the next one is captured too.',
        'Tap the thumbnail to review, then Save PDF.',
      ] },
      { type: 'h2', text: 'What a good phone scan needs' },
      { type: 'p', text: 'A scanner app does three things a plain photo does not. It detects the edges of the page so the picture is cropped tight. It straightens the perspective so a page shot at an angle becomes a flat rectangle. And it evens out the lighting so the paper looks white instead of grey with a shadow across one corner. Scan PDF does all three in the browser, which is why the result reads like a document and not like a photo of one.' },
      { type: 'h2', text: 'Scan a document step by step' },
      { type: 'steps', items: [
        'Open the Scan PDF tool in your phone’s browser and tap Open camera. Permission is asked once; most browsers remember it.',
        'Leave the mode on Document (the mode bar above the shutter also has Book, ID card, Business card and Whiteboard).',
        'Lay the page on a flat surface that contrasts with it and hold the phone above it, roughly parallel. An amber outline appears when the page is found and turns green when it is steady.',
        'With Auto capture on, the shutter ring fills and the page is taken by itself. Tap the shutter whenever you want to take it yourself.',
        'Put the next page in the same place. The scanner notices the page has changed and captures again, so you can work through a stack without touching the screen.',
        'Tap the thumbnail at the bottom left to open the review screen. Swipe between pages, and use Crop, Rotate or Filters on any page that needs it.',
        'Tap Save PDF, set the file name, page size and file size, and tap Save as PDF. Then Download PDF, or Share to send it from your phone.',
      ] },
      { type: 'callout', title: 'Nothing leaves your phone', text: 'The camera feed, the edge detection, the filters and the PDF itself are all processed on the device. Your contract or bank letter never crosses the network. Even text recognition runs locally: the language model downloads once, and the page images stay with you.' },
      { type: 'h2', text: 'Tips that make auto-detection work first time' },
      { type: 'list', items: [
        'Put the page on a desk rather than holding it in your hand. A steady page is captured faster and straighter.',
        'Use a background that contrasts with the paper: white paper on a dark table is ideal, white on white is the worst case.',
        'Keep the whole page in the frame with a small margin around all four edges.',
        'If the status line says it is too dark, add light. Where your browser exposes the phone’s flash, a flash button appears at the top of the camera.',
        'Tap the screen on the text to focus there if the picture looks soft (on phones whose browser supports it).',
        'If the outline will not settle, tap the shutter yourself. If no edges were found at all, the crop screen opens straight away so you can drag the corners into place.',
      ] },
      { type: 'h2', text: 'Fix pages on the review screen' },
      { type: 'p', text: 'Every page stays editable until you save, and edits are never destructive: the original photo is kept, so you can change your mind. These are the tools that matter most:' },
      { type: 'table', head: ['Problem', 'Tool', 'What it does'], rows: [
        ['Edge cut off or background showing', 'Crop', 'Drag corners or whole edges, with a magnifier; Auto-detect finds the page again'],
        ['Page sideways or upside down', 'Rotate', 'Turns the page 90° per tap'],
        ['Grey paper, shadows, faded print', 'Filters', 'Auto color, Original, Light text, Grayscale, B&W and Whiteboard, with an apply-to-all button'],
        ['Slightly too dark or flat', 'Adjust', 'Brightness and contrast sliders'],
        ['Thumb or coffee stain in the shot', 'Cleanup', 'Brush over it to erase it'],
        ['Need to sign or annotate', 'Markup', 'Pen, highlighter, text and a drawn signature'],
        ['Blurry page', 'Retake', 'Reopens the camera and replaces just that page'],
      ] },
      { type: 'p', text: 'Made a mistake? The undo button at the top steps back through your recent changes, and Revert puts one page back to how it was captured.' },
      { type: 'h2', text: 'Choose the right save settings' },
      { type: 'list', items: [
        'Page size: Fit page keeps each page at its own shape; A4 or Letter gives a uniform document that prints cleanly. Legal and landscape sizes are there too.',
        'File size: High, Medium or Small. Medium is the default and is fine for email; Small is for upload portals with tight limits.',
        'Recognize text (OCR): makes the PDF searchable and lets you copy text out of it. Pick the document language from the list.',
        'Protect with a password: for anything sensitive you are about to email.',
        'Format: switch to JPG if the recipient wants images instead of a PDF; several pages come as a .zip.',
      ] },
      { type: 'h2', text: 'Scanning several pages into one PDF' },
      { type: 'p', text: 'Do not create a PDF per page. Keep the camera open and feed it pages; every capture is added to the same document and the counter on the thumbnail shows how many you have. If the pages end up out of order, open Reorder on the review screen and drag them by their handles. When you save, the whole stack becomes one multi-page PDF.' },
      { type: 'callout', title: 'Interrupted? Your pages are still there', text: 'The working session is kept in your browser on the phone, so a reload, a phone call or a closed tab does not lose the pages you already scanned. Saved PDFs also appear under Recent scans on the tool page, stored only on that device.' },
      { type: 'h2', text: 'After the scan' },
      { type: 'p', text: 'The finished PDF is ready to email, upload to a portal or store in the cloud straight from your phone. If it is still too big, rescan or re-save with File size set to Small first: that keeps the text layer from OCR intact, while a heavy compression pass afterwards can turn the pages back into plain images.' },
    ],
    faqs: [
      { q: 'How do I scan a document to PDF with my phone for free?', a: 'Open a browser-based scanner on your phone, allow camera access, and hold the phone over the page until it captures automatically. Review the pages, tap Save PDF and download the file. No app and no sign-up are needed.' },
      { q: 'Is phone scanning good enough for official documents?', a: 'Yes for most purposes, if the photo is sharp, evenly lit and straightened. The scanner crops and perspective-corrects the page and evens out the lighting, so the result reads like a flat scan.' },
      { q: 'Can I scan several pages into one PDF?', a: 'Yes. Keep the camera open and turn the pages; each capture joins the same document, and you save them all as one multi-page PDF.' },
      { q: 'Do I have to install a scanner app?', a: 'No. The scanner runs in your phone’s browser. The camera feed and images are processed on the device, so nothing is uploaded.' },
      { q: 'Why does the scanner sometimes not detect my page?', a: 'Low light, glare, or a page on a background of the same colour. Put the page on a darker surface in even light and hold still, or tap the shutter and adjust the corners on the crop screen.' },
    ],
    related: ['how-to-scan-a-document-to-pdf-on-iphone', 'how-to-scan-multiple-pages-into-one-pdf', 'how-to-make-a-scanned-pdf-searchable', 'how-to-compress-a-scanned-pdf'],
  },

  // Article 2: Scan a document to PDF on iPhone
  {
    slug: 'how-to-scan-a-document-to-pdf-on-iphone',
    title: 'How to Scan a Document to PDF on iPhone (Free)',
    description: 'Scan a document to PDF on iPhone for free without an app: use the Files or Notes scanner, or a Safari scanner with auto page detection and OCR.',
    keyword: 'how to scan a document to pdf on iphone',
    category: 'Converting',
    published: '2026-09-19',
    updated: '2026-10-04',
    tool: 'scan-pdf',
    experience: 'I scan documents to PDF on my iPhone when forms and contracts arrive on paper. The built-in scanner handles quick jobs, and I use an in-browser scanner when I want a searchable PDF, a password, an ID card on one page, or a book split into pages.',
    blocks: [
      { type: 'p', text: 'A paper document needs to become a PDF and you have an iPhone in your pocket. That is a complete workflow. You can scan a document to PDF on iPhone for free in two ways: with the scanner Apple builds into the Files and Notes apps, or with a browser-based scanner in Safari that runs entirely on the phone.' },
      { type: 'h2', text: 'How do I scan a document to PDF on my iPhone?' },
      { type: 'p', text: 'Open the Files app, tap the More button (three dots) and choose Scan Documents. Hold the iPhone over the page; it detects the edges and captures automatically. Scan the remaining pages, tap Save, and the PDF lands in the folder you were in. The Notes app has the same scanner.' },
      { type: 'steps', items: [
        'Open Files and go to the folder you want.',
        'Tap the More button, then Scan Documents.',
        'Hold the iPhone over each page.',
        'Tap Save: the PDF is saved in that folder.',
      ] },
      { type: 'h2', text: 'Scan with the built-in Notes app' },
      { type: 'p', text: 'Notes uses the same scanner but keeps the scan inside a note first, which is handy if you want it alongside other notes:' },
      { type: 'steps', items: [
        'Open Notes and start a new note.',
        'Tap the camera or attachment (paperclip) icon in the toolbar, depending on your iOS version, then Scan Documents.',
        'Hold the iPhone over the page. The scanner frames it and captures when it is steady.',
        'Keep scanning pages; each is added to the same document. Tap Save.',
        'Open the scan in the note, tap Share and choose Save to Files to get a standalone PDF, or send it directly.',
      ] },
      { type: 'p', text: 'Apple’s scanner is quick and automatic, and it is the best zero-setup option for a simple document. Where it runs out is the specialised jobs: there is no password option at save time, no way to put both sides of an ID card on one page, and no automatic split of a book spread into separate pages.' },
      { type: 'h2', text: 'Scan in Safari with auto page detection' },
      { type: 'p', text: 'For those jobs, the Scan PDF tool runs in Safari (or Chrome) on your iPhone with no install:' },
      { type: 'steps', items: [
        'Open the Scan PDF tool in Safari and tap Open camera. Allow camera access when Safari asks.',
        'Pick a mode above the shutter: Document for ordinary pages, Book to split an open book into left and right pages, ID card for front and back on one page, Business card, or Whiteboard.',
        'Hold the iPhone over the page. The outline turns green when it is steady and the page is captured automatically; tap the shutter to take it yourself.',
        'Turn to the next page; it is captured too. The counter on the thumbnail shows your page count.',
        'Tap the thumbnail to review. Crop with a magnifier, rotate, change the filter, add a signature with Markup, or drag pages into order with Reorder.',
        'Tap Save PDF. Name the file, choose a page size (A4, Letter and others), switch on Recognize text (OCR) for a searchable PDF, and add a password if needed.',
        'Tap Save as PDF, then Share and choose Save to Files, or send it by Mail or Messages.',
      ] },
      { type: 'callout', title: 'Everything happens on your iPhone', text: 'The browser scanner processes the camera feed and the pages locally. Nothing is uploaded to a server. Text recognition also runs on the phone; it downloads its language model once, a few megabytes, the first time you use it.' },
      { type: 'h2', text: 'Which scanner should you use?' },
      { type: 'table', head: ['Need', 'Use', 'Why'], rows: [
        ['Quick scan straight into a folder', 'Files app', 'Zero setup, saves a PDF directly in Files'],
        ['Scan kept with your notes', 'Notes app', 'The scan lives inside the note'],
        ['Searchable PDF you can copy text from', 'Safari scanner', 'OCR on the device, with a language choice'],
        ['Front and back of an ID on one page', 'Safari scanner', 'ID card mode lays both sides on one A4 page'],
        ['Book or bound report', 'Safari scanner', 'Book mode splits each spread into two pages'],
        ['Password before you email it', 'Safari scanner', 'Protect with a password on the save screen'],
      ] },
      { type: 'h2', text: 'iPhone-specific tips' },
      { type: 'list', items: [
        'If Safari never asks for the camera, check Settings > Apps > Safari > Camera (Settings > Safari > Camera on older iOS) and set it to Ask or Allow.',
        'Photos you already took can be imported from the camera screen’s Photos button; HEIC images are supported and get the same edge detection and straightening.',
        'A phone call or a locked screen does not lose your work. The scanning session is kept in the browser and comes back when you reopen the page.',
        'Saved PDFs are listed under Recent scans on the tool page, stored only in Safari on this iPhone.',
      ] },
      { type: 'h2', text: 'Make the result smaller if needed' },
      { type: 'p', text: 'A scan of a dense page can be a few megabytes, which is over some upload limits. In the Safari scanner, choose File size Small when saving; it keeps text readable and keeps the OCR text layer. With the Files or Notes scanner, compress the PDF afterwards in your browser.' },
    ],
    faqs: [
      { q: 'How do I scan a document to PDF with an iPhone for free?', a: 'Open the Files app, tap the More button and choose Scan Documents, or use Scan Documents in Notes. Scan the pages and save; Files saves a PDF directly. A Safari-based scanner does the same with OCR, passwords and more modes.' },
      { q: 'Where does the iPhone scanner save scans?', a: 'Files saves the PDF in the folder you scanned from. Notes keeps it inside the note; use Share and Save to Files to get a standalone PDF.' },
      { q: 'Can I scan multiple pages into one PDF on iPhone?', a: 'Yes. Keep scanning and every page joins the same document, in both the Apple scanner and the browser scanner.' },
      { q: 'Can I make a scanned PDF searchable on iPhone?', a: 'Yes. In the Safari scanner, switch on Recognize text (OCR) when saving and choose the document language. The text recognition runs on the iPhone.' },
      { q: 'Is my scan uploaded anywhere?', a: 'The Safari scanner processes everything on the iPhone with no upload. Scans saved with the Files or Notes app follow your iCloud settings for those apps.' },
    ],
    related: ['how-to-scan-documents-to-pdf-with-your-phone', 'how-to-make-a-scanned-pdf-searchable', 'how-to-sign-a-pdf-on-iphone', 'how-to-compress-a-scanned-pdf'],
  },

  // Article 3: Scan multiple pages into one PDF
  {
    slug: 'how-to-scan-multiple-pages-into-one-pdf',
    title: 'How to Scan Multiple Pages Into One PDF (Free)',
    description: 'Scan multiple pages into one PDF for free: auto-capture each page as you turn it, reorder and fix pages, then save a single multi-page PDF from your phone.',
    keyword: 'how to scan multiple pages into one pdf',
    category: 'Converting',
    published: '2026-09-19',
    updated: '2026-10-04',
    tool: 'scan-pdf',
    experience: 'I scan multi-page agreements and book chapters to PDF from my phone rather than walking to a copier. Keeping the camera open and letting the tool auto-capture page after page into a single file is the workflow I actually use week in, week out.',
    blocks: [
      { type: 'p', text: 'A contract is twenty pages. A mortgage file is forty. A separate PDF for each page defeats the point: a multi-page document should come out as one PDF you can email, file or sign as one object. You can scan multiple pages into one PDF with your phone, for free, without extra apps, and without a merge step afterwards.' },
      { type: 'h2', text: 'How do I scan multiple pages into one PDF?' },
      { type: 'p', text: 'Open the Scan PDF tool on your phone and tap Open camera. Hold the first page under the camera until it captures, then swap in the next page; the scanner notices the change and captures again. Repeat for every page, review them, and tap Save PDF to get one multi-page PDF.' },
      { type: 'steps', items: [
        'Open Scan PDF and tap Open camera.',
        'Let the first page capture automatically.',
        'Swap in the next page; it captures again.',
        'Tap the thumbnail to review and reorder.',
        'Tap Save PDF to save all pages as one file.',
      ] },
      { type: 'h2', text: 'Scan all the pages in one session' },
      { type: 'p', text: 'The trick is not to save after every page. Every capture goes into the same working document, so the whole stack becomes one file at the end. Here is the detailed version:' },
      { type: 'steps', items: [
        'Open the Scan PDF tool in your phone’s browser and tap Open camera. Leave the mode on Document.',
        'Put the first page flat on a dark surface. When the outline turns green, the page is captured by itself (Auto capture is on by default). The counter on the thumbnail at the bottom left goes up by one.',
        'Lift the page away and put the next one in exactly the same spot. Once the view has changed, the scanner re-arms and captures the new page when it is steady. You do not need to touch the screen between pages.',
        'Keep going until the stack is done. If a page is a double-sided sheet, flip it and capture the back straight after the front.',
        'Tap the thumbnail to open the review screen and swipe through the pages. Fix anything crooked, sideways or dim (see below).',
        'Tap Save PDF, check the name, page size and file size, and tap Save as PDF. Download it or share it from the phone.',
      ] },
      { type: 'callout', title: 'One pass, one file', text: 'Because every page is captured into the same session, there is no separate merge step afterwards. The session is also stored in the browser on your phone, so a reload or a closed tab halfway through a forty-page file does not lose the pages you already have.' },
      { type: 'h2', text: 'Auto capture or the shutter?' },
      { type: 'p', text: 'For a clean stack of printed pages, leave Auto capture on and just feed pages; it takes a couple of seconds per page. Turn Auto capture off with the button at the top of the camera when the scanner keeps firing too early, for example on a cluttered desk or with glossy pages that reflect light. Then the outline still shows you what it found, and you tap the shutter when you are ready. If a capture finds no page edges at all, the crop screen opens immediately so you can set the corners by hand.' },
      { type: 'h2', text: 'Scanning a bound document or a book' },
      { type: 'p', text: 'For a stapled report you can unbind, scan sheets one by one. For anything you cannot take apart, switch to Book mode: line the spine up with the dashed centre line, and each shot of an open spread is split into a left page and a right page, in reading order. A 200-page book becomes 100 shots instead of 200.' },
      { type: 'h2', text: 'Put the pages in the right order' },
      { type: 'p', text: 'The order you capture pages in is the order they appear in the PDF, but you can change it before saving. On the review screen, open Reorder: every page appears as a thumbnail with a drag handle in its corner. Drag a page by its handle to its new position. On a long document it is often quicker to tap a page and use the First, Earlier, Later and Last buttons.' },
      { type: 'h2', text: 'Fix individual pages without rescanning the whole stack' },
      { type: 'table', head: ['Problem', 'Fix on the review screen'], rows: [
        ['One page is blurry', 'Retake: the camera opens and the new shot replaces only that page'],
        ['A page came out sideways', 'Rotate'],
        ['Edge cut off or desk visible', 'Crop: drag the corners, or tap Auto-detect'],
        ['Pages look different from each other', 'Pick a filter and tap “Apply this filter to all” pages'],
        ['A blank or duplicate page', 'Delete'],
        ['You changed something by mistake', 'Undo at the top, or Revert for that page'],
      ] },
      { type: 'h2', text: 'Keep the file size in check' },
      { type: 'p', text: 'A thirty-page scan adds up quickly. Set the size when you save instead of compressing later: File size has High, Medium (the default, good for email) and Small (for upload portals with tight limits). The size is shown when the PDF is ready, so you can save again at a smaller setting if it is still too large. Two more things help: the B&W filter for plain text pages, and A4 or Letter page size so every page has the same dimensions.' },
      { type: 'h2', text: 'Make it searchable while you are at it' },
      { type: 'p', text: 'A forty-page scan you cannot search is painful to use. Leave Recognize text (OCR) ticked on the save screen and choose the document language. Text recognition runs on your phone and adds a hidden text layer to every page, so you can search the PDF for a name or clause and copy text out of it. It takes longer on long documents, so plug in the phone for a big file.' },
      { type: 'callout', title: 'Run this check before sending', text: 'Open the saved PDF and look at the page count first, then flip through the thumbnails. Missing pages and duplicates are the two mistakes that actually happen with auto-capture, and both are obvious in a thumbnail view and invisible in an email preview.' },
    ],
    faqs: [
      { q: 'How do I scan multiple pages into one PDF?', a: 'Open a browser-based scanner, keep the camera open and feed it pages one after another. Every capture joins the same document, which you save once as a single multi-page PDF.' },
      { q: 'Can I scan a 20-page document as one PDF on my phone?', a: 'Yes. As long as the pages are captured in the same session, they all go into the same file. The session survives a reload, so a long document is safe to do in one sitting.' },
      { q: 'Do I need to merge the pages afterwards?', a: 'No. Pages scanned in the same session are already one PDF. A merge step is only needed when you have several separate PDF files to combine.' },
      { q: 'How do I change the page order before saving?', a: 'Open Reorder on the review screen and drag pages by their handles, or tap a page and use the First, Earlier, Later and Last buttons.' },
      { q: 'Why is my multi-page PDF so large?', a: 'Each page is an image. Save with File size set to Small or Medium, use the B&W filter for text pages, and the file shrinks considerably while staying readable.' },
    ],
    related: ['how-to-merge-pdf-files', 'how-to-combine-scanned-documents-into-one-pdf', 'how-to-scan-documents-to-pdf-with-your-phone', 'how-to-reverse-page-order-in-a-pdf'],
  },

  // Article 4: Scan a receipt to PDF
  {
    slug: 'how-to-scan-a-receipt-to-pdf',
    title: 'How to Scan a Receipt to PDF (Free)',
    description: 'Scan a receipt to PDF for free on your phone: auto-detection crops the edges, the Light text filter rescues faded thermal print, nothing is uploaded.',
    keyword: 'how to scan a receipt to pdf',
    category: 'Converting',
    published: '2026-09-19',
    updated: '2026-10-04',
    tool: 'scan-pdf',
    experience: 'I scan receipts to PDF for expense claims and tax files instead of hoarding paper. Thermal receipts fade within months, so turning them into a PDF the day you get them is the only copy that actually survives.',
    blocks: [
      { type: 'p', text: 'Receipts are the paper documents most likely to be lost, and the most likely to fade, because most are printed on thermal paper. Scanning a receipt to PDF the day you get it gives you a permanent, legible copy for your expense tool, your accountant or your tax folder.' },
      { type: 'h2', text: 'How do I scan a receipt to PDF?' },
      { type: 'p', text: 'Lay the receipt flat on a dark surface, open the Scan PDF tool on your phone and hold the camera over it. It detects the receipt’s edges, crops away the table and captures automatically. On the review screen pick the Light text or B&W filter so the print is crisp, then save it as a PDF.' },
      { type: 'steps', items: [
        'Flatten the receipt on a dark surface.',
        'Open Scan PDF and tap Open camera.',
        'Hold the phone over it until it captures.',
        'Choose the Light text or B&W filter.',
        'Tap Save PDF and download it.',
      ] },
      { type: 'h2', text: 'Scan a receipt step by step' },
      { type: 'steps', items: [
        'Smooth the receipt flat. Curled thermal paper casts shadows over the amounts; a few seconds under a book helps.',
        'Lay it on a contrasting surface: a white receipt on a dark desk is ideal.',
        'Open the Scan PDF tool on your phone, tap Open camera and leave the mode on Document.',
        'Hold the phone over the receipt so the whole strip fits with a small margin. When the outline turns green, it is captured automatically; or tap the shutter.',
        'Tap the thumbnail at the bottom left to review. Rotate it if it came in sideways.',
        'Tap Filters and compare Light text and B&W on the preview tiles (see below for which one to pick).',
        'Tap Save PDF, give the file a useful name such as the date and the shop, and tap Save as PDF. Download it or share it to your expenses app or email.',
      ] },
      { type: 'p', text: 'Receipts are long and narrow, which is exactly what edge detection is for. It crops away the desk and straightens the strip, so the result is a tight, readable document instead of a photo of crumpled paper on a table.' },
      { type: 'h2', text: 'Light text or B&W: which filter for a receipt?' },
      { type: 'table', head: ['Receipt', 'Best filter', 'Why'], rows: [
        ['Fresh, dark print', 'B&W', 'Clean black text on white paper, smallest file'],
        ['Faded or pale grey thermal print', 'Light text', 'Pushes faint print towards black while the paper stays white'],
        ['Coloured logo or stamp that matters', 'Auto color', 'Evens out the lighting but keeps the colour'],
        ['Glossy receipt with glare', 'Grayscale', 'Keeps tonal detail where a hard threshold would lose it'],
      ] },
      { type: 'p', text: 'If the text is still slightly faint after picking a filter, open Adjust and pull the contrast up a little. The filter preview tiles update for the current page, so you can compare before you choose.' },
      { type: 'h2', text: 'Rescuing a receipt that has almost faded' },
      { type: 'p', text: 'Thermal print fades from heat, light and contact with plastic wallets. Scan in bright, even light: daylight from a window is better than an overhead bulb that creates a glare stripe across glossy paper. Use the Light text filter, then raise the contrast in Adjust. If your browser exposes the phone’s flash, it can help on a matte receipt, but on glossy thermal paper it usually creates a hot spot right over the total. A receipt you thought was unreadable often comes back well enough for an expense claim.' },
      { type: 'callout', title: 'Batch a whole week of receipts', text: 'Keep the camera open and swap receipts one after another in the same spot; the scanner notices each new receipt and captures it. On the review screen, pick a filter on one receipt and tap “Apply this filter to all” pages. A weekly expense claim becomes one multi-page PDF instead of a folder of photos.' },
      { type: 'h2', text: 'Very long receipts' },
      { type: 'p', text: 'A supermarket receipt can be longer than the camera can capture sharply in one shot. Fold it in half and scan each half as its own page, top half first, or capture the top and bottom separately with a little overlap. Do not shoot it from so far away that the line items become unreadable; two sharp pages beat one blurry one.' },
      { type: 'h2', text: 'Make the PDF useful for your accountant' },
      { type: 'list', items: [
        'Check that the date, total, VAT or tax amount and card digits are readable before saving; zoom in on the review screen with a pinch or a double tap',
        'Leave Recognize text (OCR) on when saving so you can search your receipts for a shop name or an amount later',
        'Use File size Small for receipts; they stay readable and many expense tools have upload limits',
        'Name the file with the date and merchant, for example “2026-10-04 Office supplies”, so the folder sorts itself',
      ] },
      { type: 'callout', title: 'Receipts stay on your phone', text: 'The scanner runs in your browser. The receipt images, the text recognition and the PDF are all processed on the device and nothing is uploaded. Saved PDFs are listed under Recent scans on the tool page, stored only on that phone.' },
    ],
    faqs: [
      { q: 'How do I scan a receipt to PDF with my phone?', a: 'Lay the receipt flat on a dark surface, open a browser-based scanner, and let it capture after detecting the edges. Pick the Light text or B&W filter on the review screen, then save it as a PDF.' },
      { q: 'Why do thermal receipts fade and how does PDF help?', a: 'Thermal paper uses a heat-sensitive coating that fades with heat, light and time. Scanning the receipt the day you receive it captures the text permanently in a PDF.' },
      { q: 'Can I scan multiple receipts into one PDF?', a: 'Yes. Keep the camera open and swap receipts one after another; each one becomes a page of the same document, which you save as one PDF.' },
      { q: 'How do I make a faint receipt readable?', a: 'Scan it in bright, even light, choose the Light text filter, and raise the contrast in Adjust. That pushes faded print towards black while keeping the paper white.' },
      { q: 'Are my receipts uploaded anywhere?', a: 'No. The scanner runs in your browser, so the images and the PDF are processed on your device.' },
    ],
    related: ['how-to-scan-documents-to-pdf-with-your-phone', 'how-to-convert-a-photo-to-pdf-on-your-phone', 'how-to-compress-a-scanned-pdf', 'how-to-combine-scanned-documents-into-one-pdf'],
  },

  // Article 5: Straighten a crooked scan or photo
  {
    slug: 'how-to-straighten-a-crooked-scan-or-photo',
    title: 'How to Straighten a Crooked Scan or Photo of a Document',
    description: 'Straighten a crooked scan or photo of a document for free — auto-detected edges and perspective correction flatten angled pages into clean, square PDFs.',
    keyword: 'how to straighten a crooked scan or photo',
    category: 'Troubleshooting',
    published: '2026-09-19',
    updated: '2026-10-04',
    tool: 'scan-pdf',
    experience: 'I rarely take a photo of a document perfectly square. Straightening used to mean a manual transform in a photo editor; now a scanner’s edge detection crops and perspective-corrects the page in one step, and I know the common reasons why that step sometimes fails.',
    blocks: [
      { type: 'p', text: 'You photographed a document at an angle because desks and hands are rarely square. The photo shows a trapezoid: the edges lean, the text tapers, and it does not read like a document. A scanner that detects the four corners of the page and applies a perspective correction turns that slanted photo into a flat, square page, whether you shoot it live or fix a photo you already took.' },
      { type: 'h2', text: 'How do I straighten a crooked scan or photo?' },
      { type: 'p', text: 'Open the Scan PDF tool and either capture the page with the camera or import the crooked photo. The tool finds the page’s four corners and warps the image into a flat rectangle. If a corner is off, open Crop and drag it to the paper’s real corner, then rotate if needed and save as a PDF or JPG.' },
      { type: 'steps', items: [
        'Open Scan PDF; capture the page or import the photo.',
        'Let it detect the page corners.',
        'Open Crop and drag any corner that is off.',
        'Rotate if the page is sideways.',
        'Save as PDF or JPG.',
      ] },
      { type: 'h2', text: 'Straighten a photo you already took' },
      { type: 'p', text: 'This is the most common case: the crooked photo is already in your camera roll. You do not need to retake it.' },
      { type: 'steps', items: [
        'Open the Scan PDF tool. On a phone, tap Import from photos; on a computer, tap Import photos. HEIC photos from an iPhone work too.',
        'Pick the photo. The tool looks for the page edges in it automatically and straightens the page it finds.',
        'Open the page on the review screen. If the page fills the result neatly, you are done.',
        'If the result still shows some desk, or a corner of the page is cut off, tap Crop. Drag each corner handle onto the real corner of the paper; a magnifier appears beside your finger so you can place it exactly. You can also drag a whole edge at once.',
        'Lost? Tap Auto-detect in the crop screen to let the tool find the page again.',
        'Tap Rotate if the page is sideways, then Save PDF. Choose JPG in the save screen if you want a straightened image instead of a PDF.',
      ] },
      { type: 'h2', text: 'Straighten while you scan' },
      { type: 'p', text: 'With the live camera, the work happens before you even see the result. Point the phone at the angled page and an outline follows the paper’s real edges, not the edges of the screen. It turns from amber to green when it is steady and captures. The saved page is already cropped and flattened. If no page edges were found at all, the crop screen opens straight away so you can set the corners yourself.' },
      { type: 'p', text: 'The warp is not just a crop. The scanner maps the four corners onto a rectangle, so text that leans away from you is rebuilt as if the page had been lying flat on a scanner bed.' },
      { type: 'h2', text: 'When detection fails, do this' },
      { type: 'table', head: ['Problem', 'Cause', 'Fix'], rows: [
        ['No outline appears', 'Too little light, or a page on a background of the same colour', 'Add light, or slide a dark sheet under the page'],
        ['Outline grabs part of the table', 'Page blends into a white background', 'Use a darker surface, or drag the corners in Crop'],
        ['Outline keeps wobbling', 'Camera shake', 'Rest your elbows on the table, or turn Auto capture off and tap the shutter'],
        ['Corners are cut off', 'Page extends past the frame', 'Pull back until a margin surrounds all four corners'],
        ['Result is flat but text looks stretched', 'Photo taken from a very low angle', 'Retake from above the page; the Retake button replaces just that page'],
        ['Imported photo was not straightened', 'No clear page edges in the photo', 'Set the four corners manually in Crop'],
      ] },
      { type: 'callout', title: 'Filters are not straightening', text: 'Auto color, B&W, Light text and the other filters change tone, not geometry. Straightening comes from the corner positions. Fix the crop first, then pick a filter to clean up the shadows that an angled shot usually brings with it.' },
      { type: 'h2', text: 'Why steady and high beats clever' },
      { type: 'p', text: 'Perspective correction is dramatic when the page is close and only slightly tilted, and weakest when the photo is taken from a grazing angle. At a steep angle, the far edge of the page is captured with far fewer pixels than the near edge, so after straightening the far lines look softer. No software can put back detail the camera never captured. Hold the phone roughly parallel to the page, and you get a PDF that looks like it came off a flatbed.' },
      { type: 'h2', text: 'Already have a crooked PDF?' },
      { type: 'p', text: 'The scanner works on images, not on existing PDF files. If a page in a PDF is simply rotated by 90 or 180 degrees, use a rotate tool. If it is skewed or has a wide border, crop the PDF, or export the page as a JPG, run that image through the scanner and save it again.' },
    ],
    faqs: [
      { q: 'How do I straighten a scanned or photographed page for free?', a: 'Use a scanner that detects the page’s four corners and applies perspective correction. It crops to the page and warps it into a flat rectangle, all in the browser with no app. Drag the corners in Crop if detection misses.' },
      { q: 'Can I straighten a photo I already took?', a: 'Yes. Import the photo into the scanner and it runs the same edge detection and perspective correction over it. HEIC photos from an iPhone are supported.' },
      { q: 'What does perspective correction actually do?', a: 'It maps the page’s four corners onto a rectangle, so the angled photo is rebuilt as if the document were facing the camera straight on. Lines and text stop leaning.' },
      { q: 'Why does the detector sometimes not find the page?', a: 'Low light, low contrast against the desk, glare, or corners outside the frame. Even light, a darker background and a margin around the page fix most cases; otherwise set the corners by hand.' },
      { q: 'Does the B&W filter straighten my page?', a: 'No. Filters change tone and contrast only. Straightening comes from the corner positions, so fix the crop first and apply a filter afterwards.' },
    ],
    related: ['how-to-rotate-a-pdf-and-save-it', 'how-to-scan-documents-to-pdf-with-your-phone', 'how-to-crop-a-pdf', 'how-to-tell-if-a-pdf-has-been-edited'],
  },
];