import type { BlogPost } from '../types';

export const newPosts7: BlogPost[] = [
  // Article 1: How to Convert PDF to Word on Mac
  {
    slug: 'how-to-convert-pdf-to-word-on-mac',
    title: 'How to Convert PDF to Word on Mac (Free, No Adobe)',
    description: 'Turn a PDF into an editable Word document on a Mac for free. Convert in your browser with Preview, Word, or a no-install tool.',
    keyword: 'how to convert pdf to word on mac',
    category: 'Converting',
    published: '2026-09-01',
    tool: 'pdf-to-word',
    blocks: [
      { type: 'p', text: 'A contract, a study guide, or a report arrives as a PDF on your Mac and you need to edit the words in Word. The free Preview app cannot do that — it only annotates pages on top of the content. To get an editable Word document you have a few good options on a Mac, and only one of them requires Microsoft Word at all.' },
      { type: 'p', text: 'Here is how to convert a PDF to Word on a Mac for free, with Preview, with Word, or with a browser tool that needs no install.' },
      { type: 'h2', text: 'What Preview can and cannot do' },
      { type: 'list', items: [
        'Preview opens any PDF and lets you highlight, add notes, or type on top of it',
        'Preview cannot export a PDF as an editable Word file',
        'The iPad and some Apple converters use OCR, but Preview on a Mac keeps the text as-is',
      ] },
      { type: 'p', text: 'So for real editing, you need to convert. The method you choose depends on whether the PDF was created digitally or scanned.' },
      { type: 'h2', text: 'Convert a PDF to Word in Microsoft Word (text PDFs)' },
      { type: 'steps', items: [
        'Open Microsoft Word on your Mac.',
        'Choose File > Open and select your PDF.',
        'Word shows a message that it will convert the PDF into an editable document — click OK.',
        'Review the result and fix any layout that shifted.',
        'Save as a Word document.',
      ] },
      { type: 'p', text: 'This works well on digitally-created PDFs with selectable text and basic layouts, and it needs no extra converter. Its downside: complex documents with tables, columns, or custom fonts can come out rearranged.' },
      { type: 'h2', text: 'Convert a PDF to Word in your browser' },
      { type: 'p', text: 'A browser-based converter gives you a clean Word file with no Mac software install and more predictable results:' },
      { type: 'steps', items: [
        'Open the PDF to Word tool in Safari or Chrome on your Mac.',
        'Drag your PDF from Finder into the tool, or click to browse and select it.',
        'Select Word as the output format and click convert.',
        'Download the .docx file back to your Mac.',
        'Open it in Word, Pages, or Google Docs to edit.',
      ] },
      { type: 'p', text: 'Because the conversion runs locally in the browser tab, a sensitive contract stays on your Mac rather than being uploaded to a server.' },
      { type: 'callout', title: 'Scanned PDFs need OCR first', text: 'If your PDF is a scan or a photo, its text is an image, not selectable characters. A converter can only embed that image. Run OCR first to extract the text, then convert the result to Word.' },
      { type: 'h2', text: 'Editing vs. retyping' },
      { type: 'p', text: 'Converting saves you from retyping whole documents. For small tweaks — fixing a date, a name, or a paragraph — conversion is worth it. For messy scans or highly styled layouts, it can sometimes be faster to rebuild the document from the original source file and export that to PDF instead.' },
    ],
    faqs: [
      { q: 'Can I convert a PDF to Word on a Mac for free?', a: 'Yes. Use Microsoft Word\u2019s built-in PDF opening, or a browser-based PDF to Word tool that needs no install and no account.' },
      { q: 'Can Preview convert a PDF to Word?', a: 'No. Preview annotates pages but cannot export a PDF as an editable Word file. You need a converter.' },
      { q: 'Does converting change the formatting?', a: 'It can. Simple text documents convert cleanly, while complex layouts with tables, columns, or custom fonts may shift. Review and fix the result after converting.' },
      { q: 'Why does my scanned PDF not convert to text?', a: 'Because a scan stores text as an image. Run OCR first to turn the scan into selectable text, then convert it to Word.' },
      { q: 'Is my PDF uploaded to a server when I convert it?', a: 'No. When the conversion runs in your browser, your document is processed locally on your Mac and never leaves your device.' },
    ],
    related: ['how-to-convert-pdf-to-word-on-iphone', 'how-to-convert-pdf-to-word-on-android', 'how-to-convert-pdf-to-word-without-losing-formatting', 'how-to-copy-text-from-a-scanned-pdf'],
  },

  // Article 2: How to Split a PDF on iPhone
  {
    slug: 'how-to-split-a-pdf-on-iphone',
    title: 'How to Split a PDF on iPhone (Free, No App)',
    description: 'Split a PDF on your iPhone for free. Pull selected pages into a new file right in Safari — no app install and no uploads.',
    keyword: 'how to split a pdf on iphone',
    category: 'Merging & Organizing',
    published: '2026-09-01',
    tool: 'split-pdf',
    blocks: [
      { type: 'p', text: 'A 20-page document sits on your iPhone and you need only the pages that matter — or you need to hand a colleague just the pages they asked for. The iPhone has no built-in way to split a PDF, and many "PDF" apps lock the feature behind a subscription or add a watermark. You do not need any of that.' },
      { type: 'p', text: 'Here is how to split a PDF on your iPhone for free, right in Safari.' },
      { type: 'h2', text: 'Why your iPhone has no built-in option' },
      { type: 'list', items: [
        'The Files app opens and shares PDFs but cannot split them',
        'Screenshotting pages one by one is slow and lowers quality',
        'Most App Store PDF apps split only in a paid tier',
      ] },
      { type: 'callout', title: 'Split in Safari, nothing to install', text: 'A browser-based Split PDF tool runs in Safari on your iPhone and builds a new file from the pages you choose. It runs on your device, so the document never has to be uploaded.' },
      { type: 'h2', text: 'Split a PDF on iPhone in Safari' },
      { type: 'steps', items: [
        'Open the Split PDF tool in Safari on your iPhone.',
        'Tap to choose a file and select your PDF from the Files app, iCloud Drive, or an email attachment saved to Files.',
        'Enter the pages for the new file — a single page (9), a range (1-5), or a mixture (1-3, 5, 7-10).',
        'Review the preview to confirm exactly those pages are selected.',
        'Tap Split and download the new PDF back to your iPhone.',
      ] },
      { type: 'p', text: 'The original file is never changed, so you can run the tool again with different ranges and build as many separate documents as you need.' },
      { type: 'h2', text: 'Extracting a single page from a long PDF' },
      { type: 'p', text: 'To pull one page out of a large file — say page 9 of a 50-page report — enter that single number and you get a one-page PDF ready to email. The output keeps the original page as real text, so it stays sharp, selectable, and searchable.' },
      { type: 'h2', text: 'Splitting a PDF sent by email' },
      { type: 'p', text: 'If the PDF arrived as an email attachment, save it to the Files app first, then open it in the split tool. From there you can split it and send each result back out through Mail or a messaging app.' },
      { type: 'h2', text: 'After you split' },
      { type: 'p', text: 'Name each output file clearly when you download it and flip through it once to confirm the pages are the ones you meant. If you later want the separate parts back together, merge PDFs on the same iPhone in a single step.' },
    ],
    faqs: [
      { q: 'Can I split a PDF on my iPhone for free?', a: 'Yes. A browser-based Split PDF tool runs in Safari with no app install, no account, and no charge — enter the pages you want and download a new file.' },
      { q: 'Does the iPhone have a built-in PDF splitter?', a: 'No. The Files app can open and share PDFs but not split them. A browser-based tool adds that capability with nothing to install.' },
      { q: 'Can I extract non-consecutive pages into one file?', a: 'Yes. Enter ranges like 1-3, 5, 7-10 to pull exactly those pages into a single new PDF in one pass.' },
      { q: 'Will splitting change my original PDF?', a: 'No. The tool creates a new file and leaves the original untouched, so you can split on different ranges as many times as you like.' },
      { q: 'Does splitting reduce quality?', a: 'No. The selected pages are copied into a new document without re-encoding, so the text stays sharp, selectable, and searchable.' },
    ],
    related: ['how-to-split-a-pdf-on-mac', 'how-to-split-a-pdf-into-separate-pages', 'how-to-merge-pdf-files-on-iphone', 'how-to-delete-pages-from-a-pdf'],
  },

  // Article 3: How to Compress a PDF on Android
  {
    slug: 'how-to-compress-a-pdf-on-android',
    title: 'How to Compress a PDF on Android (Free, In-Browser)',
    description: 'Shrink a large PDF on your Android phone for free in Chrome. Reduce email and upload size with no app install and no account.',
    keyword: 'how to compress a pdf on android',
    category: 'Compressing',
    published: '2026-09-01',
    tool: 'compress-pdf',
    blocks: [
      { type: 'p', text: 'A PDF that is too large to attach, upload, or share stops you cold on an Android phone — an email bounces, a portal rejects the file, or it fills your storage. Android has no built-in compressor, and many Play Store apps hide the useful features behind subscriptions or add watermarks. You do not need any of them.' },
      { type: 'p', text: 'Here is how to compress a PDF on Android for free, right in Chrome.' },
      { type: 'h2', text: 'Your compression options on Android' },
      { type: 'list', items: [
        'Android has no built-in PDF compressor like some platforms',
        'The Files app by Google opens PDFs but cannot shrink them',
        'Many "free" Play Store compressors limit you to a watermark or a paid tier',
      ] },
      { type: 'callout', title: 'Compress in the browser, in control', text: 'A browser-based compressor runs in Chrome on any Android phone and lets you choose how much to shrink the file. Your document is processed on the device itself, so nothing has to be uploaded.' },
      { type: 'h2', text: 'Compress a PDF on Android in Chrome' },
      { type: 'steps', items: [
        'Open the Compress PDF tool in the Chrome browser on your Android phone.',
        'Tap to choose a file and pick your PDF from Downloads, Google Drive, or your phone\u2019s storage.',
        'Pick a compression level — light keeps text and images crisp, while heavier compression makes the smallest file.',
        'Tap compress and check the new file size.',
        'Download the smaller PDF back to your phone and share it.',
      ] },
      { type: 'p', text: 'This works even for a document that arrived as an email attachment: save it to Files, then open it in the compressor.' },
      { type: 'h2', text: 'Getting under a specific size limit' },
      { type: 'p', text: 'If a form or email requires, say, under 1 MB, start with light compression and check the result. If it is still too large, step up to a heavier level. Preview the output at 100% zoom before sending to make sure the text is still sharp.' },
      { type: 'h2', text: 'Why is my PDF so large in the first place?' },
      { type: 'list', items: [
        'Scans saved at high resolution carry a huge image payload',
        'Full-colour photos and graphics resist compression',
        'Multiple embedded fonts and objects add overhead',
        'Exporting from email, Office, or a scanner can leave heavy settings on',
      ] },
      { type: 'h2', text: 'Start small at the source' },
      { type: 'p', text: 'If even strong compression will not get the file small enough, the fastest win is usually at the source: remove unneeded pages, delete large inserted images, and for scanned documents re-scan at lower resolution and in grayscale. Compressing then becomes a final polish instead of a battle.' },
    ],
    faqs: [
      { q: 'How do I compress a PDF on Android for free?', a: 'Open a browser-based compressor in Chrome, upload the PDF, choose a compression level, and download the smaller file. No app install and no account needed.' },
      { q: 'Does Android have a built-in PDF compressor?', a: 'No. Android includes no native compressor, and the Files app by Google opens but cannot shrink PDFs.' },
      { q: 'Does compressing a PDF on Android lose quality?', a: 'Light compression keeps text and images crisp. Heavier compression can soften scanned images, so always preview the result before sending it.' },
      { q: 'Can I compress a PDF that arrived as an email attachment?', a: 'Yes. Save the attachment to the Files app first, then open it in a browser-based compressor to shrink it.' },
      { q: 'Is my PDF uploaded to a server when I compress it?', a: 'No. When the compression runs in your browser, your document is processed locally on your Android and never leaves your device.' },
    ],
    related: ['how-to-compress-a-pdf-on-iphone', 'how-to-compress-a-pdf-on-windows', 'how-to-compress-a-pdf-without-losing-quality', 'how-to-reduce-pdf-file-size-on-iphone'],
  },

  // Article 4: How to Rotate a PDF on Android
  {
    slug: 'how-to-rotate-a-pdf-on-android',
    title: 'How to Rotate a PDF on Android (Free, In-Browser)',
    description: 'Rotate pages in a PDF on Android for free. Fix a sideways scan or reorient a page in Chrome — no app install and no uploads.',
    keyword: 'how to rotate a pdf on android',
    category: 'Editing & Signing',
    published: '2026-09-01',
    tool: 'rotate-pdf',
    blocks: [
      { type: 'p', text: 'A scanned page comes in sideways, or a whole document was built the wrong way around. On an Android phone, fixing the rotation should be quick — but the built-in PDF viewers generally rotate the view only, not the real pages in the file. A browser tool can rotate a PDF on Android for free in under a minute.' },
      { type: 'p', text: 'Here is how to rotate a PDF on your Android phone, without installing an app.' },
      { type: 'h2', text: 'Why the built-in options are limited' },
      { type: 'list', items: [
        'Chrome\u2019s PDF viewer rotates the preview visually but does not change the saved pages',
        'Google\u2019s Files app can rotate photos, not the pages inside a PDF',
        'Many Play Store PDF apps hide rotation behind premium tiers',
      ] },
      { type: 'callout', title: 'Rotate the real pages, in Chrome', text: 'A browser-based Rotate PDF tool changes the pages in the file itself — so when the recipient opens it, the PDF is correctly oriented on any device. And it runs on your phone, so nothing is uploaded.' },
      { type: 'h2', text: 'Rotate a PDF on Android in Chrome' },
      { type: 'steps', items: [
        'Open the Rotate PDF tool in the Chrome browser on your Android phone.',
        'Tap to choose a file and pick your PDF from Downloads, Google Drive, or your phone\u2019s storage.',
        'Pick a rotation angle — 90, 180, or 270 degrees.',
        'Optionally choose which pages to rotate (for example, only the sideways page) rather than the whole document.',
        'Tap rotate and download the corrected PDF back to your phone.',
      ] },
      { type: 'p', text: 'Rotating 90 degrees turns portrait pages to landscape and back; 180 degrees flips everything upside-down; 270 is the reverse of 90. You can rotate just the pages that need it and leave the rest untouched.' },
      { type: 'h2', text: 'Fixing one sideways page' },
      { type: 'p', text: 'When only a single page in the middle of a document is rotated, select that specific page instead of rotating everything. That keeps the rest of the document exactly as it is while correcting the one page that matters.' },
      { type: 'h2', text: 'Rotating and then adjusting the file' },
      { type: 'p', text: 'Rotating rarely changes file size, so after you straighten a document you can compress, merge, or re-export it normally. If a rotated page still looks cropped, a Crop PDF tool can trim it down after the rotation.' },
    ],
    faqs: [
      { q: 'Can I rotate a PDF on Android for free?', a: 'Yes. A browser-based Rotate PDF tool runs in Chrome, turns pages by 90, 180, or 270 degrees, and needs no app install or account.' },
      { q: 'Does Android have a built-in PDF rotator?', a: 'No. Chrome\u2019s viewer rotates the preview but not the saved pages. A browser-based tool actually rotates the pages in the file.' },
      { q: 'Can I rotate only one page of a multi-page PDF?', a: 'Yes. The tool lets you choose specific pages to rotate instead of the whole document.' },
      { q: 'How do I know which angle I need?', a: 'Use 90 degrees to move between portrait and landscape, 180 to flip upside-down, and 270 for the opposite clockwise turn. Preview after rotating to confirm.' },
      { q: 'Does rotating affect file size or quality?', a: 'No. Rotating re-orients the pages without re-encoding the content, so quality and file size stay essentially the same.' },
    ],
    related: ['how-to-rotate-a-pdf-on-iphone', 'how-to-rotate-a-pdf-and-save-it', 'how-to-crop-a-pdf', 'how-to-reorder-pages-in-a-pdf'],
  },

  // Article 5: How to Remove Pages from a PDF on iPhone
  {
    slug: 'how-to-remove-pages-from-a-pdf-on-iphone',
    title: 'How to Remove Pages from a PDF on iPhone (Free)',
    description: 'Delete unwanted pages from a PDF on your iPhone for free in Safari. Remove a stray page or a whole section — no app install.',
    keyword: 'how to remove pages from pdf on iphone',
    category: 'Merging & Organizing',
    published: '2026-09-02',
    tool: 'remove-pages',
    blocks: [
      { type: 'p', text: 'A PDF arrives on your iPhone with an extra blank page, a stray scan, or a section you should not share. Sending a private page to the wrong person — or a half-empty file full of blanks — looks bad. The iPhone has no built-in way to delete pages from a PDF, and many apps bury it behind a subscription.' },
      { type: 'p', text: 'Here is how to remove pages from a PDF on your iPhone for free, right in Safari.' },
      { type: 'h2', text: 'Why your iPhone has no built-in option' },
      { type: 'list', items: [
        'The Files app opens and shares PDFs but cannot delete pages from inside them',
        'Printing the PDF and scanning back a trimmed version is slow and loses quality',
        'Most App Store PDF apps limit page deletion to a paid tier',
      ] },
      { type: 'callout', title: 'Delete pages in Safari, nothing to install', text: 'A browser-based Remove Pages tool builds a new PDF that skips the pages you choose. It runs on your device, so your document never has to be uploaded.' },
      { type: 'h2', text: 'Remove pages from a PDF on iPhone in Safari' },
      { type: 'steps', items: [
        'Open the Remove Pages tool in Safari on your iPhone.',
        'Tap to choose a file and select your PDF from the Files app, iCloud Drive, or an email attachment saved to Files.',
        'Enter the page numbers to delete — a single page (9), a range (1-3), or a mixture (1-3, 5, 7-10).',
        'Review the preview to confirm the right pages will be removed.',
        'Tap Remove and download the cleaned-up PDF back to your iPhone.',
      ] },
      { type: 'p', text: 'The original file is never changed, so if you make a mistake you can start over with the untouched original.' },
      { type: 'h2', text: 'Removing blank pages' },
      { type: 'p', text: 'Blank pages are the most common thing people want gone. Open the tool, preview the document to find which pages are empty, and enter those page numbers. The remaining pages keep their original quality and readability.' },
      { type: 'h2', text: 'Removing a page before you send it' },
      { type: 'p', text: 'If a PDF contains a page you should not share — a stray note, a different document, a page of private details — delete it before sending. Double-check the preview to confirm the page is gone, since the recipient will see only the trimmed file.' },
      { type: 'h2', text: 'After you remove pages' },
      { type: 'p', text: 'Name the trimmed PDF clearly and flip through it once to confirm nothing you need was removed. If the document ends up much smaller, there is no need to compress it further; if it still includes many pages, keep the original as a backup in your own storage.' },
    ],
    faqs: [
      { q: 'Can I delete pages from a PDF on my iPhone for free?', a: 'Yes. A browser-based Remove Pages tool runs in Safari with no app install and no account — enter the pages to delete and download a new file.' },
      { q: 'Does the iPhone have a built-in way to remove PDF pages?', a: 'No. The Files app opens and shares PDFs but cannot delete pages inside them. A browser-based tool adds that capability with nothing to install.' },
      { q: 'Can I remove multiple pages at once?', a: 'Yes. You can list several pages, ranges, or a mix (for example, 3, 5-7, 12) to delete them all in one pass.' },
      { q: 'Will removing pages change my original PDF?', a: 'No. The tool creates a new file and leaves the original untouched, so you can undo a mistake by starting over.' },
      { q: 'Does deleting pages reduce quality?', a: 'No. The remaining pages are copied without re-encoding, so their text and images stay sharp and selectable.' },
    ],
    related: ['how-to-delete-pages-from-a-pdf', 'how-to-split-a-pdf-on-iphone', 'how-to-remove-blank-pages-from-a-pdf', 'how-to-split-a-pdf-into-separate-pages'],
  },
];