import type { BlogPost } from '../types';

export const newPosts22: BlogPost[] = [
  {
    slug: 'how-to-sign-a-pdf-on-iphone',
    title: 'How to Sign a PDF on iPhone',
    description: 'Sign a PDF on your iPhone in the browser — no app to install. Open the file, draw or type your signature, place it, save. Free and private.',
    keyword: 'sign a pdf on iphone',
    category: 'Editing & Signing',
    published: '2026-09-24',
    tool: 'sign-pdf',
    blocks: [
      { type: 'p', text: 'Signing a PDF on an iPhone is a thing "in the moment" — a contract that has to go back at lunchtime, a permission form before the school run. You can do it with no app and no account: the Sign PDF tool runs in Safari, uploads nothing, and lets you draw your signature with a finger, then save the signed file straight back to your iPhone.' },
      { type: 'h2', text: 'The built-in option: Markup' },
      { type: 'p', text: 'Before anything else, the free option you already own: open the PDF in the Files app, tap the Markup icon (a pen tip in a circle), tap the plus button, choose Signature, draw it, then drag it into place and tap Done. Markup stores your signature for reuse. It is extremely fast for a one-off — and that is also its limit. There is no typed signature, no choice of signature style, no initials workflow, and no control over placement beyond dragging the mark around.' },
      { type: 'h2', text: 'Sign a PDF in Safari, step by step' },
      { type: 'steps', items: [
        'If the PDF arrived in Mail or WhatsApp, save it to Files first — tap the attachment, tap Share, then Save to Files.',
        'Open Safari and go to the Sign PDF tool.',
        'Tap the upload area; iOS opens the Files picker, where you can reach Downloads, iCloud Drive and any file you saved.',
        'Draw your signature with your finger on the pad (or switch to typing your name, or uploading an image), place it on the line, and download the signed PDF back to Files.', ],
      },
      { type: 'p', text: 'Everything happens in the browser tab. The file is processed on your iPhone rather than sent somewhere, so an NDA or a mortgage amendment does not cross a third-party server before it is signed.' },
      { type: 'callout', title: 'When you only need a quick tick', text: 'For a single signature with nothing else to add, Markup in Files is the fastest route — two taps. For a document with initials, a typed signature, or careful placement on several pages, use the Sign flow in Safari instead, which gives you each of those options properly.' },
      { type: 'h2', text: 'Signatures that stick' },
      { type: 'list', items: [
        'A finger-drawn signature looks natural; a typed one looks tidy and consistent if your penmanship is a wobble.',
        'Place the signature on the line, then pinch to resize so it sits in proportion to the page.',
        'Once you download, sign and send the file back through the same app it arrived in — reply with the attachment attached.',
      ] },
      { type: 'h2', text: 'Is an on-screen signature legally valid?' },
      { type: 'p', text: 'Yes, for the everyday "I agree" that most documents need. Under the US E-SIGN Act, UETA and the EU\'s eIDAS regulation, an electronic signature made with intent to sign is treated like a handwritten one. If a document specifically demands a digital signature backed by a verified certificate, a dedicated signing service is required — an image of your pen marks on the page will not substitute for that.' },
    ],
    faqs: [
      { q: 'Do I need to install an app to sign a PDF on my iPhone?', a: 'No. The Sign PDF tool runs in Safari — nothing to install, no account, no App Store access needed. It uses the standard file picker to open your PDF and can save the signed result back to Files.' },
      { q: 'How do I open a PDF attachment to sign it?', a: 'Tap the attachment in Mail or Messages, use Share > Save to Files, then pick that file inside the tool\'s upload dialog. iOS browsers open PDFs from the file picker, so saving to Files is the reliable route.' },
      { q: 'Can I type my signature instead of drawing it?', a: 'Yes. Switch from draw to the typed option and enter your name; you can pick a font and size. Typing is the practical choice when a tidy, repeatable signature matters.' },
      { q: 'Is signing this way secure?', a: 'The document is processed locally in your browser and nothing is uploaded. Your file only goes where you choose — back into Files, then to the person you send it to.' },
      { q: 'Is a signed PDF from my iPhone legally binding?', a: 'For ordinary business and personal documents, yes — E-SIGN, UETA and eIDAS recognise electronic signatures made with intent. A certificate-backed digital signature is a different, stronger requirement and is not what this flow provides.' },
    ],
    related: ['how-to-sign-a-pdf-without-printing-it', 'how-to-add-initials-to-a-pdf', 'how-to-sign-a-pdf-electronically', 'how-to-scan-a-document-to-pdf-on-iphone'],
  },
  {
    slug: 'how-to-start-page-numbers-at-a-specific-number-in-a-pdf',
    title: 'How to Start Page Numbers at a Specific Number in a PDF',
    description: 'Start page numbers at a specific number in a PDF — continue a sequence from a previous file or set an opening value. Free, in-browser, no upload.',
    keyword: 'start page numbers at a specific number in a pdf',
    category: 'Editing & Signing',
    published: '2026-09-24',
    tool: 'add-page-numbers',
    blocks: [
      { type: 'p', text: 'Not every document starts its numbering at page 1. An appendix continues where the main report left off, a section of a manual resumes at a page someone else already claimed, and a file split into parts keeps one running sequence across all of them. The Add Page Numbers tool has a Start Numbering At field precisely for this: you type the value the sequence should begin with, and the pages number upward from there.' },
      { type: 'h2', text: 'When a starting number matters' },
      { type: 'list', items: [
        'A multi-section report where each section is a separate PDF file but the page count runs across the whole document.',
        'An appendix or annex that continues the numbering of the main body rather than restarting at 1.',
        'A set of merged files for a client who expects one continuous sequence from the first page to the last.',
      ] },
      { type: 'h2', text: 'Set a custom starting number, step by step' },
      { type: 'steps', items: [
        'Open the Add Page Numbers tool and drop in your file.',
        'Choose where the numbers sit — bottom centre is the usual default, with left, right and top positions available.',
        'Pick a format such as "1" or "Page X of Y".',
        'Set Start Numbering At to the value you want (for example 26, to continue a document whose previous part ended on 25), then process and download.', ],
      },
      { type: 'p', text: 'The sequence begins on the first page of the file with the value you entered and counts steadily from there, so page 1 displays 26, page 2 displays 27, and so on across the whole document.' },
      { type: 'callout', title: 'Numbering a cover page differently', text: 'This tool numbers every page, starting its sequence on page 1. If you need the cover or title page to stay unnumbered while the body starts at page 1, the honest workaround is to number the file without the cover first — extract the opening pages off, number the rest, then combine the pieces back in the correct order.' },
      { type: 'h2', text: 'Continuing a sequence across several files' },
      { type: 'p', text: 'Merging chapter files back into one document also gives you a single sequence, and you can keep that numbering intact. The practical pattern is: decide the final order, merge so the content sits in the right sequence, then add page numbers over the combined file with the start value you want — one pass, one consistent footer.' },
      { type: 'h2', text: 'Check the result before you send it' },
      { type: 'list', items: [
        'Open the numbered PDF and confirm the first page shows the start value you chose.',
        'Verify the sequence runs consecutively with no skipped or repeated numbers across the document.',
        'If you later insert pages, renumber the whole file so the sequence stays correct rather than patching individual pages.',
      ] },
    ],
    faqs: [
      { q: 'Can I start PDF page numbers at any value?', a: 'Yes — the Start Numbering At field accepts whatever value you need, such as 12, 26 or 100. The first page of the file shows that number and every following page counts up from it.' },
      { q: 'Can I leave the cover page unnumbered?', a: 'This tool numbers every page from page 1. To keep a cover unnumbered, extract the opening pages to a separate file, number the rest, then combine everything back into one PDF in order.' },
      { q: 'How do I continue numbering from a previous file?', a: 'Note the page number the last file ended on, then set Start Numbering At to the next value — for example 26 after a file that ended on page 25 — and run the tool on the new file.' },
      { q: 'Do custom-start numbers work with "Page X of Y" format?', a: 'Yes. The starting value applies to the X (the current page), while Y counts the real number of pages in the file, giving output such as "Page 26 of 34".' },
      { q: 'Will the numbers overwrite an existing footer?', a: 'Numbering stamps the position you choose, so a footer already containing numbers would end up with both. If your file already has numbered footers, remove them first, then add your sequence.' },
    ],
    related: ['how-to-add-page-numbers-to-a-pdf', 'how-to-add-a-header-and-footer-to-a-pdf', 'how-to-remove-page-numbers-from-a-pdf', 'how-to-reverse-page-order-in-a-pdf'],
  },
  {
    slug: 'how-to-scan-an-id-card-to-pdf',
    title: 'How to Scan an ID Card to PDF (Front and Back, One Page)',
    description: 'Scan an ID card to PDF with your phone: front and back on one A4 page, like a photocopy. Free, in your browser, nothing uploaded. Ready for KYC and HR forms.',
    keyword: 'scan an id card to pdf',
    category: 'Converting',
    published: '2026-09-24',
    updated: '2026-10-04',
    tool: 'scan-pdf',
    experience: 'I have sent ID copies to landlords, banks and new employers more times than I can count. The submissions that bounced were never about resolution; they were a missing back side, a glare stripe across the photo, or two loose image files when the form wanted one page. That is what this guide is built around.',
    blocks: [
      { type: 'p', text: 'Tenancy applications, bank onboarding, employer right-to-work checks, KYC portals: almost all of them want a copy of your ID with the front and the back, usually on a single page that looks like a photocopy. You can scan an ID card to PDF in exactly that format with your phone. The Scan PDF tool has an ID card mode that captures the front, then the back, and lays both sides on one A4 page. It runs in the browser and nothing is uploaded.' },
      { type: 'h2', text: 'How to scan the front and back of an ID card on one page' },
      { type: 'p', text: 'Open the Scan PDF tool on your phone, switch the camera to ID card mode, and capture the front of the card. When the screen says to turn the card over, capture the back. Both sides are placed one above the other on a single A4 page, which you save as a one-page PDF.' },
      { type: 'steps', items: [
        'Open Scan PDF and tap Open camera.',
        'Choose ID card in the mode bar above the shutter.',
        'Scan the front of the card.',
        'Turn the card over and scan the back.',
        'Tap Save PDF, then Save as PDF and Download.',
      ] },
      { type: 'h2', text: 'Scan an ID card to PDF, step by step' },
      { type: 'p', text: 'Here is the full walk-through, with the details that decide whether a verification desk accepts the copy on the first try.' },
      { type: 'steps', items: [
        'Open the Scan PDF tool in your phone’s browser (Safari, Chrome or any modern browser) and tap Open camera. Allow camera access when the browser asks.',
        'In the mode bar above the shutter, tap ID card. A dashed card-shaped frame appears and the status line reads “Scan the front of the card”.',
        'Lay the card flat on a dark, plain surface and hold the phone over it. The outline turns amber when the card is found and green when it is steady; with Auto capture on, the shot is taken by itself. You can also tap the shutter.',
        'The status changes to “Now turn the card over and scan the back”. Flip the card in the same spot and capture it the same way.',
        'Tap the thumbnail at the bottom left to review. You will see one page with the front at the top and the back underneath, each cropped and straightened.',
        'Tap Save PDF, check the file name, pick A4 as the page size if the page will be printed, and tap Save as PDF. Then Download PDF, or Share to send it straight to email or a messaging app.',
      ] },
      { type: 'callout', title: 'Only need the front?', text: 'Some cards, like a membership card or a driving licence where the portal only asks for the photo side, have nothing useful on the back. After the front is captured, tap “Front only — skip the back” and the page is saved with just the front, still laid out on an A4 sheet.' },
      { type: 'h2', text: 'One page or two pages: which do they want?' },
      { type: 'p', text: 'Read the form before you scan. “A copy of both sides” on a paper form or a printed application usually means the photocopy look: both sides on one sheet. Upload portals that have separate “front” and “back” boxes want two separate files or two pages. The tool can do either.' },
      { type: 'table', head: ['What the form asks for', 'Mode to use', 'What you get'], rows: [
        ['Copy of both sides on one page', 'ID card', 'One A4 page, front above back'],
        ['Front and back as two pages of one PDF', 'Document', 'Capture the front, then the back: a two-page PDF'],
        ['Separate front and back uploads', 'Document, then export as JPG', 'Two JPG images in a .zip, one per side'],
        ['Front only', 'ID card, then “Front only”', 'One A4 page with only the front'],
      ] },
      { type: 'h2', text: 'The printer alternative: ID Copy' },
      { type: 'p', text: 'If you are standing next to an office multifunction printer, look for a button called ID Copy, ID Card Copy or Card Copy (HP, Ricoh, Canon, Brother and Toshiba all have a version). You place the front face down on the glass, press Start, flip the card when prompted, and the machine prints both sides on one sheet. It works well, but most models only produce paper. To get a PDF you then need a scan-to-email or scan-to-folder version of the feature, which not every printer has. A phone in ID card mode gets you the PDF directly.' },
      { type: 'h2', text: 'Printing the page and checking the size' },
      { type: 'p', text: 'The two sides are laid out in the proportions of a standard bank-card-sized ID (85.6 × 54 mm) on an A4 sheet, so a printout looks like a photocopy, not a full-page blow-up of your face. Whatever page size you pick when saving, an ID page is always saved on A4 at real size; print it at 100% or “Actual size” rather than “Fit to page”.' },
      { type: 'callout', title: 'Run this test before you hand it in', text: 'Print the page once and lay your real card on top of the printed front. It should match the card exactly: ID card pages are saved on an A4 sheet with no margin, so the card prints at its real 85.6 mm width. Print at 100% ("Actual size"), not "Fit to page", or the printer will shrink it.' },
      { type: 'h2', text: 'Getting a clean capture of a shiny card' },
      { type: 'list', items: [
        'Use a dark, matte background such as a desk, a notebook cover or a jumper. Edge detection needs contrast, and a white card on a white table is the most common reason the outline never appears.',
        'Kill the glare. Laminated cards reflect overhead lights straight back into the lens. Move so the light is to the side, and leave the flash off: on a glossy card it creates a hot spot over the photo.',
        'If the status says the scene is too dark, add light from a window or a lamp rather than holding the phone closer.',
        'Tap the screen on the card’s text to focus there, where your browser supports it, before the shot is taken.',
        'Fill the dashed frame. A card that is tiny in the frame gives a soft, low-detail copy.',
      ] },
      { type: 'h2', text: 'Fixing one side without starting over' },
      { type: 'p', text: 'If the back came out crooked, open Crop on the review screen. For an ID page the crop editor has Front and Back tabs, so you can drag the corners of just one side; a magnifier shows exactly where your finger is, and Auto-detect finds the card edges again. If a side is unusable, tap Retake: on an ID page it reopens the camera in ID card mode and asks for the front and then the back again, replacing the page in place.' },
      { type: 'h2', text: 'Colour, filters and privacy' },
      { type: 'p', text: 'ID card mode starts with the Auto color filter, which evens out lighting and whitens the background while keeping the card in colour. That is the right choice for almost every verification process. Avoid B&W for IDs: some checks reject copies where the photo has been reduced to black and white, and the holograms and security colours are part of what the reviewer looks at. If a portal complains that the image looks processed, switch the page to Original.' },
      { type: 'p', text: 'Everything happens on your phone: the camera feed, the cropping, the layout and the PDF. Nothing is uploaded. If you are emailing the copy, tick “Protect with a password” on the save screen so the attachment cannot be opened without it, and send the password by a different channel. One honest note: the finished PDF is also kept in Recent scans in this browser on this device. On a shared or borrowed phone, delete it from Recent scans when you are done.' },
      { type: 'h2', text: 'Already have photos of both sides?' },
      { type: 'p', text: 'Photos from your gallery can be imported, and each one gets the same automatic edge detection and straightening. But imported photos come in as normal pages, one per photo, not as a combined ID layout. That gives you a two-page PDF, which many portals accept. If the form needs both sides on one page, scan the physical card again in ID card mode.' },
    ],
    faqs: [
      { q: 'How do I scan both sides of my ID card on one page?', a: 'Open the Scan PDF tool on your phone, choose ID card mode, scan the front, turn the card over and scan the back. Both sides are placed on one A4 page, which you save as a one-page PDF.' },
      { q: 'How do I copy the front and back of an ID on one page with a printer?', a: 'Use the printer’s ID Copy (or ID Card Copy) function: put the front face down on the glass, press Start, flip the card when prompted and press Start again. Most printers output paper only, so for a PDF a phone scan in ID card mode is quicker.' },
      { q: 'Can I scan an ID card with my phone instead of a scanner?', a: 'Yes. A phone camera with automatic edge detection and straightening produces a clean, readable copy. Use even light, a dark background and no glare on the photo.' },
      { q: 'Is it safe to scan my ID in a browser?', a: 'With this tool the image is processed on your phone and never uploaded. You can also add a password to the PDF before sending it. A copy is kept in Recent scans on that device, which you can delete.' },
      { q: 'What if the form wants the front and back as separate pages or files?', a: 'Use Document mode instead and capture the front and then the back. That gives a two-page PDF, or two JPG images if you choose JPG on the save screen.' },
    ],
    related: ['how-to-scan-documents-to-pdf-with-your-phone', 'how-to-scan-both-sides-of-a-document-into-one-pdf', 'how-to-combine-images-into-one-pdf', 'how-to-scan-a-receipt-to-pdf'],
  },
  {
    slug: 'how-to-extract-odd-or-even-pages-from-a-pdf',
    title: 'How to Extract Odd or Even Pages from a PDF',
    description: 'Extract only the odd or even pages of a PDF to fix a two-sided scan or print double-sided by hand. Free, in-browser, completely private.',
    keyword: 'extract odd or even pages from a pdf',
    category: 'Merging & Organizing',
    published: '2026-09-24',
    tool: 'extract-pages',
    blocks: [
      { type: 'p', text: 'Odd and even pages get separated for one of two reasons: a printer that only does one side at a time (print the odd pages, flip the paper, print the even pages), or a scanner without a two-sided feeder that grabbed all the fronts in one pass and all the backs in another. The Extract Pages tool can pull just the pages you want into a new PDF, so either job becomes a clean two-file workflow.' },
      { type: 'h2', text: 'How odd and even are counted' },
      { type: 'p', text: 'Pages are numbered by physical order in the file: page 1 is odd, page 2 is even, and so on. If the document starts with a cover, the cover is page 1 — which shifts what counts as odd from that point on. When you type the list for an odd set, you are picking pages 1, 3, 5, 7 and so on as they actually sit in the file.' },
      { type: 'h2', text: 'Extract the odd or even pages, step by step' },
      { type: 'steps', items: [
        'Open the Extract Pages tool and drop in your PDF.',
        'For the odd set, enter the alternating list — for example 1, 3, 5, 7 — and check the live preview highlights the pages you mean.',
        'Download the odd file, then re-open the tool and enter the even list (2, 4, 6, ...) for the second file.',
        'Keep both files handy: they are the two halves of the document.', ],
      },
      { type: 'p', text: 'The page list also accepts ranges such as 1-20, so you can isolate a section first, then split that section into its odd and even halves without touching the rest of the document.' },
      { type: 'callout', title: 'It is a typed list, not a magic button', text: 'The Extract tool reads the exact pages you type, so the "odd" file is a list you write yourself (1, 3, 5...). For a few dozen pages that is quick and easy to verify against the preview. If you do this constantly on very long documents, a parity button would do that for you — this workflow needs your list typed in the box.' },
      { type: 'h2', text: 'Reassembling a two-sided scan' },
      { type: 'p', text: 'When a flatbed scanner ran the fronts and backs in two passes, the classic fix is: extract the odd pages (the fronts) into one file and the even pages (the backs) into another, then put them back into reading order. One caution — back-sides scanned after flipping a stack often come out reversed, so check the order of the even set and reverse it if needed, then merge the two files alternating page by page.' },
      { type: 'h2', text: 'Printing double-sided by hand' },
      { type: 'list', items: [
        'Print the odd file first, one page per sheet.',
        'Take the printed stack and reload it into the tray facing the way your printer needs (check one test page).',
        'Print the even file on the backs, then collate if the printer leaves them in reverse order.',
      ] },
    ],
    faqs: [
      { q: 'What counts as an odd page?', a: 'Odd pages are the pages in the file at positions 1, 3, 5, 7 and so on — physical page order, not printed numbers. If page one is a cover, the cover is odd.' },
      { q: 'Can I extract odd pages into one file and even into another?', a: 'Yes. Run the Extract tool twice — once with the odd list (1, 3, 5...) and once with the even list (2, 4, 6...) — and download the two new PDFs.' },
      { q: 'How do I fix a two-sided scan that came out jumbled?', a: 'Extract the fronts and backs into two files, check whether the back set is reversed (flipping a stack reverses it), reverse it if so, then merge the two files so pages alternate front, back, front, back.' },
      { q: 'Can I extract a page range only?', a: 'Yes — the page box accepts ranges like 1-20 as well as individual pages, so you can pull a section first and then split that section into odd and even.' },
      { q: 'Is the extracted file the full original quality?', a: 'Yes. Extracted pages are copied into a new PDF without re-encoding or re-rendering, so text and images keep their original quality and size.' },
    ],
    related: ['how-to-split-a-pdf-into-separate-pages', 'extract-pages-from-pdf', 'how-to-reverse-page-order-in-a-pdf', 'how-to-merge-pdf-files'],
  },
  {
    slug: 'how-to-keep-slides-from-getting-cut-off-when-converting-to-pdf',
    title: 'How to Keep Slides from Getting Cut Off When Converting to PDF',
    description: 'Stop PowerPoint slides from being cut off at the edges when converting to PDF. Render each slide to its own page instead. Free, no upload.',
    keyword: 'keep slides from getting cut off when converting powerpoint to pdf',
    category: 'Converting',
    published: '2026-09-24',
    tool: 'powerpoint-to-pdf',
    blocks: [
      { type: 'p', text: 'A slide that reaches the top or bottom edge of the export is the classic PowerPoint-to-PDF headache: you designed to the edge, the PDF crops it, and footer text vanishes. The usual culprit is not the file — it is a printer driver. PowerPoint\'s export sends slides through the print pipeline, and printer drivers add their own unremovable margins, clipping anything that extends into them. The fix is a renderer that draws each slide on a page the size of the slide itself, edge and all.' },
      { type: 'h2', text: 'Why PowerPoint\'s own export crops slides' },
      { type: 'list', items: [
        'PowerPoint exports via the system printer driver, and most printers have hardware margins (roughly a quarter to half an inch) that cannot be removed.',
        'A widescreen slide scaled down onto letter paper can leave content clipped at the sides after the fit.',
        '"Scale to fit paper" and "Frame slides" options in the export dialog each contribute their own rounding and clipping.',
      ] },
      { type: 'h2', text: 'Convert without cut-off, step by step' },
      { type: 'steps', items: [
        'Open the PowerPoint to PDF tool and drop in your .pptx file.',
        'Watch the render progress as each slide is drawn onto its own page.',
        'Download the PDF and check the first and last slides — the edges that used to disappear now stay on the page.', ],
      },
      { type: 'p', text: 'Instead of running through a printer, the converter builds the PDF directly: each slide becomes a page matching the slide\'s own size and shape, with text drawn in its real position and automatically tightened inside its box when a line would overflow — the same behaviour PowerPoint calls Autofit. Because there is no printer driver in the loop, there are no margins to clip against and nothing to cut off at the boundary.' },
      { type: 'callout', title: 'The honest limits of a re-render', text: 'The converter redraws the slide\'s text and shapes rather than photographing PowerPoint, so it is clean for standard decks. Strikingly custom effects, video embeds or exotic transitions are not part of a PDF anyway — the static slide still comes through, but check one page before you trust the whole deck. Animations and sound are never preserved in PDF export by any tool.' },
      { type: 'h2', text: 'Checks that catch cut-off before it bites' },
      { type: 'list', items: [
        'Fold a ruler of your PDF to the slide edge in your viewer and confirm text at the boundary is visible.',
        'Look at the slide where the footer or date used to vanish — that is the page that fails first.',
        'If a specific shape still clips after conversion, pull it slightly inside the slide edge in the original file and re-export.',
      ] },
      { type: 'h2', text: 'If you must export from PowerPoint itself' },
      { type: 'p', text: 'When PowerPoint is the only option: use File > Export > Create PDF/XPS and set Slide Size to "Actual size", uncheck Frame slides, and make sure any printer picked is a zero-margin virtual printer such as Print to PDF rather than a physical driver. Those settings exist precisely to fight the margins described above.' },
    ],
    faqs: [
      { q: 'Why is the bottom of my PowerPoint slide missing in the PDF?', a: 'PowerPoint exports through the print pipeline, and printer drivers add unremovable margins that clip content near the slide edge. A converter that renders each slide on a slide-sized page has no such margins to crop against.' },
      { q: 'Does the conversion carry over animations and videos?', a: 'No. PDF export flattens slides to static pages by design, so animations, sounds and video do not survive — in any PDF converter, including PowerPoint\'s own export.' },
      { q: 'Will text be resized or clipped inside text boxes?', a: 'Text is drawn at its real size and position; if it would overflow a shape\'s box it is tightened automatically, the same way PowerPoint\'s Autofit shrinks overflowing text so nothing is cut off.' },
      { q: 'My slide is 16:9. Does the PDF page match it?', a: 'Yes. Each slide becomes a page sized to the slide\'s own dimensions, so a widescreen slide stays widescreen and nothing is re-framed or cropped to fit letter paper.' },
      { q: 'What if one edge is still clipped after converting?', a: 'Check whether the shape genuinely touches the slide edge in PowerPoint — objects dragged into the gray area outside the slide are always cut in export. Pull it inward in the source, then re-convert.' },
    ],
    related: ['how-to-convert-powerpoint-to-pdf', 'how-to-convert-word-to-pdf-without-losing-formatting', 'how-to-fix-a-pdf-that-wont-print', 'how-to-change-the-page-size-of-a-pdf'],
  },
];