import type { BlogPost } from '../types';

export const newPosts19: BlogPost[] = [
  {
    slug: 'how-to-convert-a-pdf-to-a-png-image',
    title: 'How to Convert a PDF to a PNG Image',
    description: 'Turn a PDF page into a lossless PNG for slides, social posts, presentations and design work. Free, in-browser, no upload, no sign-up.',
    keyword: 'convert a pdf to a png image',
    category: 'Converting',
    published: '2026-09-24',
    tool: 'pdf-to-jpg',
    blocks: [
      { type: 'p', text: 'A PDF page is drawn when it is rendered, which means it is not stored as a picture you can drop into a slide, a design tool or a chat. Converting a PDF to PNG renders every page to a high-resolution image you can use anywhere — one PNG per page, ordered exactly like the document.' },
      { type: 'h2', text: 'When PNG is the right output (and when JPG is better)' },
      { type: 'p', text: 'PNG uses lossless compression, so text edges, line art and diagrams stay crisp with no softness around the letters. That makes it the format for anything with sharp detail you plan to zoom in on or edit further. The trade-off is file size: a PNG of a text-heavy page is noticeably larger than the equivalent JPG, so photocopies, scans and photos of pages come out smaller and look the same in JPG.' },
      {
        type: 'table', head: ['Situation', 'Best format', 'Reason'],
        rows: [
          ['Diagrams, charts, text-heavy pages', 'PNG', 'Lossless edges and letterforms'],
          ['Photographs and photo-heavy scans', 'JPG', 'Much smaller, visually identical'],
          ['Slides for a deck or social post', 'PNG', 'Crisp at every zoom level'],
          ['Print shop proof', 'PNG at high DPI', 'Print-sharp detail'],
        ],
      },
      { type: 'h2', text: 'Turn a PDF page into a PNG, step by step' },
      { type: 'steps', items: [
        'Open the PDF-to-image tool and drop in your PDF.',
        'Set the output format to PNG.',
        'Choose the render density: low for screen and email, high for print.',
        'Download the PNGs.', ],
      },
      { type: 'p', text: 'Every page becomes its own PNG, named in document order. A five-page file gives you five images, so you can keep just the one chart you need and ignore the rest.' },
      { type: 'callout', title: 'About transparent backgrounds', text: 'PDF pages are rendered onto a white background, so the PNG is not transparent. If you need a sticker or logo with an alpha channel, make the source graphic first and combine it at the design stage — a page render cannot carry the blank parts as transparency.' },
      { type: 'h2', text: 'Get a sharper PNG out of a small file' },
      { type: 'list', items: [
        'Pick the high-density render for anything that will be printed or enlarged.',
        'A text page renders far more clearly as PNG than as a heavy JPG at the same size.',
        'A render is a one-way step: vector text becomes a grid of pixels, so choose the density for your largest intended use before you download.',
      ] },
      { type: 'h2', text: 'Keep the PNG small instead' },
      { type: 'p', text: 'For a slide, an email or a thumbnail, the low-density render is plenty: text stays readable and the file stays light. PNG is lossless by design, so the only real lever on size is the rendered resolution — and that is the setting to revisit when a file grows bigger than you expected.' },
    ],
    faqs: [
      { q: 'Does converting a PDF to PNG lower the quality?', a: 'No — PNG is lossless, so the rendered result keeps every pixel. The render density sets how much detail is captured, so choosing the high setting before downloading protects print and enlargement use.' },
      { q: 'Will a PNG keep clickable links or form fields?', a: 'No. A render is a flat picture of the page, so links, bookmarks and interactive form fields are painted in and cannot be clicked afterwards.' },
      { q: 'How many PNGs do I get from a multi-page PDF?', a: 'One PNG per page, named in document order. Convert the whole file then keep only the pages you need, or run a page extract first to convert a single page.' },
      { q: 'Is a PNG from a PDF transparent?', a: 'Not in a page render — pages are drawn onto a white background. Build any cut-out/transparent asset from the source graphic instead.' },
      { q: 'When should I use JPG instead of PNG?', a: 'For photographs and photo-heavy scans, where JPG is far smaller and looks the same. Choose PNG for text, diagrams and line art that need sharp edges.' },
    ],
    related: ['how-to-convert-pdf-to-image-for-printing', 'how-to-convert-pdf-to-jpg-high-quality', 'how-to-convert-png-to-pdf', 'how-to-extract-images-from-a-pdf'],
  },
  {
    slug: 'how-to-tell-if-a-pdf-is-a-scanned-document',
    title: 'How to Tell If a PDF Is a Scanned Document',
    description: 'Quick tests to identify a scanned PDF and one-click OCR to make it searchable. Free, in-browser, no upload, no sign-up.',
    keyword: 'tell if a pdf is a scanned document',
    category: 'Troubleshooting',
    published: '2026-09-24',
    tool: 'ocr-pdf',
    blocks: [
      { type: 'p', text: 'A scanned PDF is a picture of a page. The letters on it are pixels, not characters, which is why you cannot select a word, copy a sentence or search with Ctrl+F — there is simply no text stored in the file. Two PDFs that look identical on screen can behave completely differently, and knowing which kind you are holding decides what you can do next.' },
      { type: 'h2', text: 'The three ten-second tests' },
      { type: 'list', items: [
        'Try to select a word. In a digital PDF, dragging across text highlights individual words and letters. In a scan, the whole page selects like one big picture.',
        'Search with Ctrl+F or Cmd+F for a distinctive word you can see. A real text layer finds it instantly; a picture-only page returns nothing.',
        'Zoom to 300–400 percent. Vector text stays crisp as it zooms, while a scan pixelates like a photograph. This is a useful hint, not proof — building a searchable OCR layer under a scan is exactly why the picture can still look sharp.',
      ] },
      { type: 'p', text: 'One test alone can lie. Searchable scans — an image with an invisible OCR text layer behind it — pass the selection and search tests while still being pictures at heart. The reliable read is the combination: no selectable words, no search results and visible pixelation together mean a scan.' },
      { type: 'h2', text: 'What a scan means for editing and copying' },
      { type: 'p', text: 'If a PDF is a scan, text tools around it fail for the same reason: there are no characters to read. Copying produces nothing, translation returns the file untouched or empty, and an editor cannot touch the letters. The fix in every case is the same — run OCR to add a real text layer.' },
      { type: 'h2', text: 'Make a scanned PDF searchable with OCR' },
      { type: 'steps', items: [
        'Open the OCR tool and drop in your scanned PDF.',
        'Wait while each page is recognised into a hidden text layer.',
        'Download the result — it looks identical, but the words are now real.', ],
      },
      { type: 'p', text: 'After OCR the same tests pass: selection works, Ctrl+F finds words, and copy, translation and editing behave like a digital document. The page image itself is unchanged.' },
      { type: 'callout', title: 'Some scans already have an OCR layer', text: 'Many scanners add a text layer at scan time. That file behaves like a normal document even though it started as a photo of a page — and an old, low-quality OCR engine can leave characters that copy out badly. If your copied text looks like noise, re-recognising the file cleans it up.' },
      { type: 'h2', text: 'When a PDF is mixed' },
      { type: 'p', text: 'Reports and applications often combine digital cover pages with scanned receipts, signed forms or appendices. The tests above give a per-page verdict, so a file that searches fine on page 1 and fails on page 5 is mixed — run OCR and only the image pages are affected, the digital text stays untouched.' },
    ],
    faqs: [
      { q: 'How do I know if a PDF is a scan or real text?', a: 'Try to select a single word and search with Ctrl+F. If you cannot highlight individual words and a word you can see is not found, the page is a picture. Two tests together give a reliable answer.' },
      { q: 'Can a scanned PDF pass the text test anyway?', a: 'Yes. Scans that already have an invisible OCR layer behave like digital documents — and if that layer is poor, copied text comes out garbled. Re-running OCR fixes the layer.' },
      { q: 'What can I do with a scanned PDF once I know?', a: 'Run OCR to add a text layer. The page looks the same but suddenly selection, search, copy, translation and editing all work.' },
      { q: 'Are some pages of my PDF scans and others not?', a: 'Mixed files are common — a digital report with scanned receipts tacked on. Test a few pages, including the attachments area, to map which pages are pictures.' },
      { q: 'Does OCR change how the scan looks?', a: 'No. OCR adds an invisible text layer underneath the page image, so the document still looks exactly like the original scan.' },
    ],
    related: ['how-to-make-a-scanned-pdf-searchable', 'how-to-tell-if-a-pdf-has-been-edited', 'how-to-extract-text-from-scanned-pdf-without-software', 'how-to-copy-text-from-a-scanned-pdf'],
  },
  {
    slug: 'how-to-scan-a-document-in-black-and-white',
    title: 'How to Scan a Document in Black and White',
    description: 'Capture a clean black-and-white scan of any paper page with your phone and save a small, crisp PDF. Free, in-browser, no sign-up.',
    keyword: 'scan a document in black and white',
    category: 'Converting',
    published: '2026-09-24',
    tool: 'scan-pdf',
    blocks: [
      { type: 'p', text: 'Scanning in black and white — monochrome, not grayscale — collapses every shade to ink or white. The payoff is a dramatically smaller file, cleaner text that OCR reads more accurately, and scans that feel formal for receipts, contracts and forms. Many printers and scanners make you dig through driver settings to get true black and white. Your phone can do it in one tap.' },
      { type: 'h2', text: 'Why scan in black and white at all' },
      { type: 'list', items: [
        'Tiny file sizes. Every page is just dark and light, so a whole contract fits in an email as easily as a short photo.',
        'Sharper letters. High-contrast text is easier for OCR and for any reader on a phone screen.',
        'Consistent documents. No color tint, shadows or crayon marks turning an otherwise serious page into a photo.',
      ] },
      { type: 'p', text: 'Grayscale keeps the gray steps in between, which suits pencil sketches or faded documents. True black and white is the right choice when the page is mostly printed text or ink.' },
      { type: 'h2', text: 'Scan with your phone camera' },
      { type: 'steps', items: [
        'Open the document scanner and capture the page, or grab it from your photo library.',
        'At the review step, apply the Black & White (B&W) filter.',
        'Confirm the scan, keep snapping pages or save, then download the PDF.', ],
      },
      { type: 'p', text: 'The filter is applied while capturing, so the file saves in black and white from the start — no second editing tool between you and the download.' },
      { type: 'callout', title: 'Black and white is a capture-time choice', text: 'The scan tool photographs and converts at capture, so it is designed for paper pages in front of you. A PDF that already exists as a color file is a different job: export it, save it with the filter on the way in, or re-print — there is no honest way to strip existing color out of a document you have not scanned.' },
      { type: 'h2', text: 'When to choose colored or grayscale instead' },
      { type: 'p', text: 'Anything where color carries information — a passport page, a form with official stamps, a highlighted price list — must stay in color, because black and white throws that information away. Faded or pencil originals live happily in grayscale, which keeps faint detail that a black-and-white threshold would erase.' },
    ],
    faqs: [
      { q: 'Is a black-and-white scan smaller than a color one?', a: 'Yes, often dramatically. Every page is only ink and white instead of millions of shades, so files shrink and still print cleanly.' },
      { q: 'Does black and white help OCR accuracy?', a: 'Usually. High-contrast text gives the OCR engine sharply separated characters to read, which reduces errors on typical printed documents.' },
      { q: 'What is the difference from grayscale?', a: 'Grayscale keeps the gray steps between white and black; black and white is two tones only. Use grayscale for pencil or faded originals and black and white for printed text and ink.' },
      { q: 'Can I convert a PDF I already have to black and white?', a: 'The scanner applies black and white while capturing a page, so it fits originals in front of you. An existing color PDF is better re-exported from its source or printed and rescanned.' },
      { q: 'Should colored stamps or highlights be scanned black and white?', a: 'No — anything where color carries information, like stamps, flags or highlights, should be scanned in color or grayscale so the detail is not lost.' },
    ],
    related: ['how-to-scan-a-document-without-a-scanner', 'how-to-scan-documents-to-pdf-with-your-phone', 'how-to-scan-a-receipt-to-pdf', 'how-to-darken-a-scanned-pdf'],
  },
  {
    slug: 'how-to-scan-both-sides-of-a-document-into-one-pdf',
    title: 'How to Scan Both Sides of a Document Into One PDF',
    description: 'Capture front and back of a two-sided document into a single PDF with your phone. Free, in-browser, no upload.',
    keyword: 'scan both sides of a document into one pdf',
    category: 'Converting',
    published: '2026-09-24',
    tool: 'scan-pdf',
    blocks: [
      { type: 'p', text: 'An office printer with a duplex feeder scans both sides of a sheet in a single pass — but most of us hold two-sided documents in our hands in front of a phone. You do not need special hardware to get a clean two-sided PDF: capture both faces, keep the pairs in order, and save one combined file that reads front, back, front, back.' },
      { type: 'h2', text: 'The two-pass method, done right' },
      { type: 'list', items: [
        'Capture the front of the first sheet, then immediately the back of that same sheet, and keep repeating sheet by sheet. Adjacent pairs stay correct by construction.',
        'If you prefer batch passes, shoot all the fronts first and all the backs second — then reorder the stacks so every back sits right behind its front.',
        'Flipping a whole stack in a feeder reverses the order of the backs, which is exactly why re-viewing the sequence matters before you save.',
      ] },
      { type: 'p', text: 'Batch passes save repositioning time, but they reintroduce order problems. Sheet-by-sheet capture is the safest habit for a two-page form, an ID card, or any short document where order is the whole point.' },
      { type: 'h2', text: 'Combine the sides into one PDF' },
      { type: 'steps', items: [
        'Open the document scanner and capture each side as you go.',
        'Use the reorder controls so the pages run front, back, front, back — never two fronts or two backs in a row.',
        'Set a page size if your document needs one, then save and download the single PDF.', ],
      },
      { type: 'p', text: 'The preview panel is your safety net. When every second thumbnail is the same sheet with the writing flipped, the file is correct before it leaves your device.' },
      { type: 'callout', title: 'Reading order is the only real rule', text: 'A two-sided scan is just a sequence of faces. The tool captures and saves whatever order you land on, so the entire method reduces to keeping each back directly behind its front — then the resulting PDF reads exactly like the paper original.' },
      { type: 'h2', text: 'What to do with long stacks' },
      { type: 'p', text: 'For a twenty-page job, capture the whole front stack, then the whole back stack, then interleave. With a phone that means flipping the document once as a block and shooting the reverse pass, exactly like a feeder would — then using the reorder view to weave the two stacks into one sequence. Spot-check page numbers or headers after interleaving, because a missed pair is easy to catch in the thumbnails and hard to spot in the final file.' },
    ],
    faqs: [
      { q: 'Will my phone scan both sides automatically?', a: 'No — a single camera captures one face at a time. The free method is two passes: shoot the front and back of each sheet, then keep them adjacent so the combined PDF reads correctly.' },
      { q: 'Why is it best to capture the front and back one sheet at a time?', a: 'Adjacent pairs stay correct by construction, so a short document needs no reordering afterwards. Batch passes are faster for long stacks but reintroduce ordering work.' },
      { q: 'How do I keep the order right in one combined file?', a: 'Check the thumbnail grid before saving and use the reorder controls so every back sits directly behind its front — front, back, front, back.' },
      { q: 'I scanned the full front side first, then all backs. How do I fix the order?', a: 'That is expected for feeder flipping. Use the reorder view to interleave the two stacks into one sequence, and verify with page headers or numbers after.' },
      { q: 'Can I scan an ID card front and back into one PDF?', a: 'Yes — capture each face and keep the two back to back in the preview. The result is a single two-page PDF of the card.' },
    ],
    related: ['how-to-scan-multiple-pages-into-one-pdf', 'how-to-combine-scanned-documents-into-one-pdf', 'how-to-scan-a-book-into-a-pdf', 'how-to-reorder-pages-in-a-pdf'],
  },
  {
    slug: 'how-to-translate-a-scanned-pdf',
    title: 'How to Translate a Scanned PDF',
    description: 'Translate a scanned PDF to any language: run OCR first, then translate. Free, in-browser, no upload, no sign-up.',
    keyword: 'translate a scanned pdf',
    category: 'Converting',
    published: '2026-09-24',
    tool: 'ocr-pdf',
    blocks: [
      { type: 'p', text: 'Drag a scanned PDF into most translators and nothing happens: the file comes back untouched or with zero text. That is not a bug — a scan is a picture of a page, and translators can only read characters. A scanned page has no characters until OCR turns the image into text. So translating a scan is always two honest steps: recognise the text, then translate it.' },
      { type: 'h2', text: 'Why translators reject scans' },
      { type: 'p', text: 'A translation engine works by extracting the text layer, sending those words to a model, then returning the translation. When a PDF is a scan, the extraction step finds nothing, because the letters are pixels, not text. Some services quietly return the original; others error out. The fix is identical either way — give the file a real text layer first.' },
      { type: 'h2', text: 'Translate a scan in two steps' },
      { type: 'steps', items: [
        'Run the OCR tool on your scanned PDF to add a text layer. Choose the document language if the tool offers it — it sharpens recognition for non-Latin scripts.',
        'Open the translated PDF in the translate tool with the same approach as a normal document, select the source and target languages, and download the result.', ],
      },
      { type: 'p', text: 'The OCR step is what makes everything after it possible. The recognised PDF selects, copies and searches like a digital document, which is exactly the input the translation step needs.' },
      { type: 'callout', title: 'Verify before you translate', text: 'Translated text inherits every OCR mistake: a misrecognised word becomes a confidently mistranslated word. Copy a paragraph from the recognised file and read it once before translating — catching problems at the cheapest point is what separates a usable translation from a misleading one.' },
      { type: 'h2', text: 'Tips for better recognition on difficult scans' },
      { type: 'list', items: [
        'Tell the OCR step the source language when known — the engine targets the right character set.',
        'A clean, flat, well-lit capture reads far better than a skewed or shadowed photo.',
        'After OCR, spot-check names, numbers and currency before translating them into a final document.',
      ] },
      { type: 'h2', text: 'What the translation step actually sends' },
      { type: 'p', text: 'Unlike every other tool here, the translate tool sends the extracted text to a third-party translation service — that is what produces the translation. The extracted words are the only thing that leaves your device, and this warning is shown in the tool itself. For confidential scans, weight that trade-off before you start.' },
    ],
    faqs: [
      { q: 'Why will Google Translate or my translator not read my scanned PDF?', a: 'Translators read a PDF text layer, and a scan has none — the letters are pixels. Running OCR first creates the layer and the same translator then works normally.' },
      { q: 'Do I have to run OCR before translating a scan?', a: 'Yes. It is the single step that turns a picture of text into text a translation engine can read, and it lets you verify recognition before words are carried into another language.' },
      { q: 'Should I check the OCR output before translating?', a: 'Strongly. A word OCR misreads becomes a confidently mistranslated word. Read a sample first; fixing recognition errors costs nothing compared with fixing them after translation.' },
      { q: 'Can I translate a scan with handwriting or unusual fonts?', a: 'Recognition quality varies with legibility. Clean printed text translates well; heavy or stylised handwriting is harder for any OCR engine. Set the source language for the best result.' },
      { q: 'Does translating a scanned PDF send my file somewhere?', a: 'The OCR step stays fully in your browser. The translation step sends only the extracted text to a translation service to produce the result — the tool warns about this before you run it.' },
    ],
    related: ['how-to-translate-a-pdf', 'how-to-make-a-scanned-pdf-searchable', 'how-to-copy-text-from-a-scanned-pdf', 'how-to-extract-text-from-scanned-pdf-without-software'],
  },
];