import type { BlogPost } from '../types';

export const organizingPosts: BlogPost[] = [
  {
    slug: 'how-to-delete-pages-from-a-pdf',
    title: 'How to Delete Pages From a PDF',
    description: 'Remove unwanted pages from a PDF in seconds — blank scans, duplicate copies, or a page you should never have included. No software needed.',
    keyword: 'how to delete pages from a pdf',
    category: 'Merging & Organizing',
    published: '2026-03-02',
    tool: 'remove-pages',
    blocks: [
      { type: 'p', text: 'Deleting pages from a PDF keeps the document intact and drops the pages you name. It is the fix for a duplex scan full of blank backs, a fax cover sheet nobody needs, or an internal page that should not go to the client.' },
      { type: 'h2', text: 'How to remove pages' },
      { type: 'steps', items: [
        'Open Remove Pages and add your PDF.',
        'Enter the pages to delete — a single number, a range like 14-18, or a list such as 2, 7, 20-22.',
        'Check the preview so you are deleting the pages you meant to delete.',
        'Download the trimmed file. Your original stays untouched on disk.',
      ] },
      { type: 'callout', title: 'Page numbers shift as you delete', text: 'If you delete pages one at a time, every deletion renumbers what follows. Always list all the pages you want gone in a single operation, using the numbering of the original file.' },
      { type: 'h2', text: 'Finding the blank pages in a scan' },
      { type: 'p', text: 'A duplex scanner produces a back side for every sheet, so a stack of single-sided pages comes out with a blank between each one. Those pages are rarely truly white — they usually carry scanner noise, a faint shadow of the printing on the other side, or a grey edge where the sheet did not sit square.' },
      { type: 'p', text: 'The practical approach is to page through the file at thumbnail size, which makes the blanks obvious at a glance, and write down their numbers as you go. On an evenly duplexed batch they are simply all the even pages.' },
      { type: 'h2', text: 'Deleting a page is not the same as redacting it' },
      { type: 'p', text: 'This is the mistake that causes real damage. Removing a page takes the page out of the document — but if what you were trying to hide also appears on a page you kept, it is still there in full.' },
      { type: 'list', items: [
        'Delete a page when the whole page is irrelevant or wrong.',
        'Redact when specific information on a page you need to keep must not be readable.',
        'Never rely on deleting one copy of something that appears in several places.',
      ] },
      { type: 'h2', text: 'Does deleting pages shrink the file?' },
      { type: 'p', text: 'Usually, but not proportionally. The images and fonts that were only used by the deleted pages go with them, so cutting image-heavy scans can save a lot. Cutting text pages from a document whose bulk is one embedded font barely moves the needle, because that font is still needed by the pages you kept.' },
      { type: 'p', text: 'If the file is still too big after trimming, compress it as a separate step.' },
      { type: 'h2', text: 'What breaks when pages disappear' },
      { type: 'table', head: ['Element', 'Effect'], rows: [
        ['Links pointing to a deleted page', 'Stop working — the target no longer exists'],
        ['Bookmarks for deleted sections', 'Usually removed or left pointing nowhere'],
        ['Printed page numbers in footers', 'Stay as they were — the document will skip numbers'],
        ['Digital signature', 'Invalidated, because the file has changed'],
      ] },
      { type: 'p', text: 'If skipped page numbers look wrong in the finished document, strip the old numbering and add fresh page numbers after the deletion.' },
    ],
    faqs: [
      { q: 'Can I undo deleting a page from a PDF?', a: 'Not within the file itself, but your original is never modified — the tool writes a new document. Re-open the original and start again.' },
      { q: 'How do I delete the last page of a PDF?', a: 'Enter its number. If you do not know the page count, the tool displays it once your file loads, and open-ended ranges like 40- will take everything from page 40 onward.' },
      { q: 'Can I delete pages from a password-protected PDF?', a: 'Only after unlocking it. The tool needs to read the page structure, which encryption prevents until the password is removed.' },
      { q: 'Will the recipient know pages were removed?', a: 'There is nothing marked in the file, but printed page numbers in headers or footers will skip. Renumber the pages if that matters.' },
    ],
    related: ['how-to-remove-blank-pages-from-a-pdf', 'extract-pages-from-pdf', 'how-to-redact-a-pdf-properly'],
  },

  {
    slug: 'how-to-rotate-a-pdf-and-save-it',
    title: 'How to Rotate a PDF and Save It Permanently',
    description: 'Rotate sideways or upside-down PDF pages and save the rotation so it sticks — including why the view in your reader sometimes resets.',
    keyword: 'how to rotate a pdf and save it',
    category: 'Merging & Organizing',
    published: '2026-04-08',
    tool: 'rotate-pdf',
    blocks: [
      { type: 'p', text: 'Almost everyone has hit this: you rotate a sideways page in your PDF reader, it looks right, you close the file, and the next time you open it the page is sideways again.' },
      { type: 'p', text: 'That is the difference between rotating the view and rotating the document. Only one of them survives being sent to someone else.' },
      { type: 'h2', text: 'View rotation versus saved rotation' },
      { type: 'p', text: 'Most readers offer a rotate button that spins the page on screen without changing the file. It is a convenience for reading, and it is discarded the moment you close the document. Saved rotation writes a rotation value into the page itself, so every reader on every device shows it the way you left it.' },
      { type: 'p', text: 'If you are fixing a page for your own benefit, view rotation is fine. If you are sending the file to anyone, you need the saved kind.' },
      { type: 'h2', text: 'How to rotate and actually save it' },
      { type: 'steps', items: [
        'Open the Rotate PDF tool and add your file.',
        'Rotate the pages that need it — all of them, or just the ones that are wrong.',
        'Download the rotated PDF. The rotation is now part of the document.',
        'Re-open the downloaded file to confirm the pages come up the right way.',
      ] },
      { type: 'h2', text: 'Rotating some pages but not others' },
      { type: 'p', text: 'Mixed orientation is normal in real documents. A report with a landscape chart on page 9 and a landscape appendix at the back should keep those pages landscape while the rest stay portrait.' },
      { type: 'p', text: 'Rotate the specific pages rather than the whole file. Rotating everything to fix two pages breaks the other forty.' },
      { type: 'callout', title: 'Landscape content, portrait page', text: 'A page can be portrait-shaped while the content printed on it runs sideways. Rotating the page makes the text upright but leaves you with a tall page containing sideways-shaped content. Some documents genuinely need to be read sideways — check whether rotating actually improves it.' },
      { type: 'h2', text: 'Why scans come out sideways' },
      { type: 'list', items: [
        'The page was fed into the scanner in landscape and captured as-is.',
        'The scanner auto-rotated based on detected text and got it wrong — common with forms and tables.',
        'A photographed page carried camera orientation metadata that the conversion ignored.',
        'A landscape spreadsheet was exported to a portrait page.',
      ] },
      { type: 'p', text: 'None of these are recoverable by a setting after the fact; you rotate the pages and move on.' },
      { type: 'h2', text: 'Does rotating affect quality or size?' },
      { type: 'p', text: 'No. Rotation is a number stored on the page — 90, 180 or 270 degrees. Nothing is re-rendered, so quality is identical and the file size is unchanged to within a few bytes.' },
    ],
    faqs: [
      { q: 'Why does my PDF keep opening sideways after I rotate it?', a: 'You rotated the view rather than the document. The view rotation is not written to the file. Use a tool that saves the rotation into the PDF and download the result.' },
      { q: 'Can I rotate a single page in a PDF?', a: 'Yes. Choose the page and rotate only that one — the rest of the document is left alone.' },
      { q: 'How do I rotate a PDF 180 degrees?', a: 'Apply 90 degrees twice, or pick 180 directly if the tool offers it. Upside-down pages usually come from a stack fed in the wrong way.' },
      { q: 'Does rotating a PDF lose quality?', a: 'No. It changes a rotation value on the page rather than re-drawing the content.' },
    ],
    related: ['how-to-rearrange-pages-in-a-pdf', 'how-to-combine-scanned-documents-into-one-pdf', 'why-is-my-pdf-blurry'],
  },

  {
    slug: 'how-to-combine-scanned-documents-into-one-pdf',
    title: 'How to Combine Scanned Documents Into One PDF',
    description: 'Turn a pile of scans and photographed pages into a single, tidy PDF — in the right order, the right way up, and a sensible size.',
    keyword: 'combine scanned documents into one pdf',
    category: 'Merging & Organizing',
    published: '2026-04-22',
    tool: 'merge-pdf',
    blocks: [
      { type: 'p', text: 'Scanning rarely produces the file you actually want. You end up with a folder of separate PDFs, some photographed pages, a few blanks and at least one page sideways. Here is the order of operations that turns that into one clean document.' },
      { type: 'h2', text: 'The sequence that works' },
      { type: 'steps', items: [
        'Convert any photos to PDF first, so everything you are working with is the same format.',
        'Rotate the pages that came out sideways, page by page rather than in bulk.',
        'Remove blank pages, especially the backs produced by duplex scanning.',
        'Merge everything, dragging the files into the correct reading order before you run it.',
        'Run OCR if you need the text to be searchable.',
        'Compress last, once you know the document is otherwise finished.',
      ] },
      { type: 'callout', title: 'Compress last, always', text: 'Every other step is lossless. Compression is the one that discards image detail. Doing it at the end means you compress once, rather than degrading the same pages repeatedly.' },
      { type: 'h2', text: 'Getting photographed pages to look like scans' },
      { type: 'p', text: 'Phone photos of documents come out with the page at a slight angle, uneven lighting and a background of desk. Most phone scanning apps will crop to the page edges and flatten the perspective before you export — use that mode rather than the plain camera, because no PDF tool can recover a page edge that was never captured square.' },
      { type: 'p', text: 'If you already have plain photos, convert them anyway and accept the result. A slightly crooked page is legible; a re-photographed one costs you an afternoon.' },
      { type: 'h2', text: 'Why scanned PDFs get so large' },
      { type: 'p', text: 'A scan is a full-page photograph. At 300 DPI in colour, one A4 page is several megapixels, and a thirty-page document easily passes 50 MB. Two settings do most of the damage:' },
      { type: 'table', head: ['Setting', 'Effect on size'], rows: [
        ['Colour instead of greyscale', 'Roughly triples the data for a black-and-white original'],
        ['600 DPI instead of 300', 'Roughly quadruples it, with no visible gain for printed text'],
        ['Lossless output instead of JPEG', 'Can multiply size several times over'],
      ] },
      { type: 'p', text: 'For ordinary printed text, 300 DPI greyscale is the sweet spot. If the scans already exist at higher settings, compression will bring them down.' },
      { type: 'h2', text: 'Making the finished document searchable' },
      { type: 'p', text: 'A merged scan is a stack of pictures. Searching it finds nothing, because there is no text in the file — only images of text. Running OCR reads the images and adds an invisible text layer underneath, so the document becomes searchable and copyable while looking exactly the same.' },
      { type: 'p', text: 'OCR is worth doing on anything you might need to find again: contracts, receipts, correspondence, anything going into an archive.' },
    ],
    faqs: [
      { q: 'How do I combine scans that are separate PDF files?', a: 'Merge them. Convert any images to PDF first so every input is the same format, then drag the files into reading order before merging.' },
      { q: 'Should I OCR before or after merging?', a: 'After. One OCR pass over the finished document is faster than OCRing each fragment, and it produces one consistent text layer.' },
      { q: 'My scanned PDF is 80 MB. Is that normal?', a: 'For colour scans at high DPI, yes. Compress the finished file — scanned documents typically shrink by 60–90% with no visible difference on printed text.' },
      { q: 'Can I fix a crooked scan?', a: 'Only by rescanning. Rotation corrects 90-degree steps, not the two-degree skew of a page that went through the feeder at an angle.' },
    ],
    related: ['how-to-merge-pdf-files', 'how-to-make-a-scanned-pdf-searchable', 'how-to-compress-a-scanned-pdf'],
  },

  {
    slug: 'how-to-remove-blank-pages-from-a-pdf',
    title: 'How to Remove Blank Pages From a PDF',
    description: 'Strip the empty pages out of a scanned or exported PDF — how to find them, why they exist, and how to delete them all in one pass.',
    keyword: 'remove blank pages from pdf',
    category: 'Merging & Organizing',
    published: '2026-05-05',
    tool: 'remove-pages',
    blocks: [
      { type: 'p', text: 'Blank pages are the tax on duplex scanning. Feed twenty single-sided sheets through a two-sided scanner and you get a forty-page PDF, half of it empty. They waste paper when printed, pad the file, and make the document look careless.' },
      { type: 'h2', text: 'Where blank pages come from' },
      { type: 'list', items: [
        'Duplex scanning of single-sided originals — every other page is the back of a sheet.',
        'Word documents with a section break that pushes an empty page to the end.',
        'Slide decks exported with hidden or placeholder slides included.',
        'Chapter breaks that force each section to start on a right-hand page.',
        'Separator sheets deliberately inserted between documents in a batch scan.',
      ] },
      { type: 'h2', text: 'Finding them quickly' },
      { type: 'steps', items: [
        'Open the document and switch your reader to a thumbnail or grid view.',
        'Scan down the grid — blanks stand out immediately at that size.',
        'Note every blank page number as you go. On an evenly duplexed scan they will all be even.',
        'Delete them in a single Remove Pages operation using the original numbering.',
      ] },
      { type: 'callout', title: 'Scanned blanks are not empty', text: 'A blank page from a scanner usually carries faint noise, a shadow of the print on the reverse, or a grey edge. That is why automatic blank detection sometimes misses them, and why a quick visual pass is more reliable than trusting a threshold.' },
      { type: 'h2', text: 'Delete them all at once' },
      { type: 'p', text: 'Removing pages one at a time renumbers the document after each deletion, which is exactly how people end up deleting page 12 twice and losing something real. List every blank page in one go, using the numbering of the file as it currently stands, and run a single operation.' },
      { type: 'h2', text: 'How much space you get back' },
      { type: 'p', text: 'On a scanned document, a lot — those blank pages are full-page images like any other, often a megabyte each. On a text document exported from Word, almost nothing, because an empty page carries essentially no content. Remove them for tidiness there, not for size.' },
      { type: 'h2', text: 'Preventing them next time' },
      { type: 'p', text: 'At the scanner, switch to single-sided mode when your originals are single-sided, or turn on blank-page skipping if the hardware offers it. In Word, turn on paragraph marks and delete the stray empty paragraphs or section break at the end of the document before you export.' },
    ],
    faqs: [
      { q: 'Is there an automatic way to remove blank pages?', a: 'Some tools attempt it by measuring how much ink is on a page, but scanner noise fools the threshold in both directions. On a document that matters, a thumbnail pass takes a minute and is right.' },
      { q: 'Will removing blank pages reduce my file size?', a: 'Substantially for scans, where each blank is still a full-page image. Barely at all for documents exported from a word processor.' },
      { q: 'How do I stop my scanner producing blank pages?', a: 'Set it to single-sided for single-sided originals, or enable its blank-page detection. It is a scanner setting rather than something to fix in the PDF each time.' },
      { q: 'My blank page will not delete — why?', a: 'Check you are using the page position rather than a printed page number, and that the document is not password protected, which blocks structural edits until it is unlocked.' },
    ],
    related: ['how-to-delete-pages-from-a-pdf', 'how-to-combine-scanned-documents-into-one-pdf', 'how-to-compress-a-scanned-pdf'],
  },

  {
    slug: 'how-to-reverse-page-order-in-a-pdf',
    title: 'How to Reverse the Page Order in a PDF',
    description: 'Flip a back-to-front PDF the right way round in one action — plus how to tell a simple reversal from a duplex scan that needs interleaving.',
    keyword: 'reverse page order in pdf',
    category: 'Merging & Organizing',
    published: '2026-05-19',
    tool: 'organize-pdf',
    blocks: [
      { type: 'p', text: 'A reversed PDF is the signature of a sheet feeder that pulls from the bottom of the stack. Every page is captured correctly; they are simply in the opposite order. One operation fixes the whole document.' },
      { type: 'h2', text: 'Reverse the order' },
      { type: 'steps', items: [
        'Open Organize PDF and add the file.',
        'Choose reverse order rather than dragging pages individually.',
        'Check the first and last pages — the old last page should now be page one.',
        'Download the corrected file.',
      ] },
      { type: 'p', text: 'On a hundred-page scan this is the difference between one click and an afternoon of dragging thumbnails.' },
      { type: 'h2', text: 'Check it is really a simple reversal' },
      { type: 'p', text: 'Before reversing, look at three or four pages spread through the document. If the sequence runs cleanly backwards — last, second-to-last, and so on — a reversal is the right fix.' },
      { type: 'p', text: 'If instead the odd pages run forwards and the even pages run backwards, you have a duplex scan where the second pass went through in the opposite direction. Reversing that will not fix it; the two halves have to be interleaved, which means separating the odd and even pages, reversing one set, and merging them back together alternately.' },
      { type: 'callout', title: 'The duplex-reversed pattern', text: 'Fronts in order 1, 3, 5, 7 and backs in order 8, 6, 4, 2 is the classic signature. Split the odd and even pages into two files, reverse the one that runs backwards, then interleave them.' },
      { type: 'h2', text: 'Reversing part of a document' },
      { type: 'p', text: 'When only one section is inverted — an appendix, or one document inside a batch scan — do not reverse the whole file. Extract that range into its own PDF, reverse it, then merge it back into position. It is three steps instead of one, but it leaves the rest of the document alone.' },
      { type: 'h2', text: 'What reversing does not touch' },
      { type: 'p', text: 'Page content is unchanged, so quality and file size stay the same. Printed page numbers stay printed where they are, which means a reversed document will count downwards on the page even though it now reads in the right order. Renumber if that matters.' },
    ],
    faqs: [
      { q: 'Why did my scanner produce the pages backwards?', a: 'Because the feeder took sheets from the bottom of the stack, capturing the last page first. Some scanners have a setting for this; otherwise reverse the file afterwards.' },
      { q: 'Can I reverse only some pages?', a: 'Not in a single reverse action. Extract the range you need flipped, reverse that file, and merge it back into place.' },
      { q: 'Does reversing lose quality?', a: 'No. Only the page order changes; the pages themselves are copied as they are.' },
      { q: 'My duplex scan is half reversed. What now?', a: 'Split into odd and even pages, reverse whichever set runs backwards, then merge them back together alternately.' },
    ],
    related: ['how-to-rearrange-pages-in-a-pdf', 'how-to-split-a-pdf-into-separate-pages', 'how-to-combine-scanned-documents-into-one-pdf'],
  },

  {
    slug: 'how-to-split-a-pdf-by-file-size',
    title: 'How to Split a PDF by File Size',
    description: 'Break an oversized PDF into pieces that fit an email or upload limit — how to work out the split points and when to compress instead.',
    keyword: 'split pdf by file size',
    category: 'Merging & Organizing',
    published: '2026-06-30',
    tool: 'split-pdf',
    blocks: [
      { type: 'p', text: 'Some limits cannot be argued with: a 25 MB email attachment cap, a portal that rejects anything over 10 MB, a filing system with a hard ceiling. When a document is over the line, you either make it smaller or you cut it into pieces.' },
      { type: 'h2', text: 'Try compression first' },
      { type: 'p', text: 'A split document is worse for the reader — several files to keep track of, in the right order, opened separately. If compression gets you under the limit, that is the better answer, and on scanned documents it usually does: reductions of 60–90% are routine, because scans are images and images compress hard.' },
      { type: 'p', text: 'Split when the file is genuinely large after compression, or when the pieces are naturally separate documents anyway.' },
      { type: 'h2', text: 'Working out where to cut' },
      { type: 'steps', items: [
        'Note the file size and the page count.',
        'Divide to get a rough size per page — a 60 MB, 120-page file averages 0.5 MB a page.',
        'Divide the limit by that figure and take a margin. For a 10 MB cap at 0.5 MB a page, aim for 16 pages rather than 20.',
        'Split by those ranges, then check the actual sizes of the results.',
        'Adjust and re-split if one part came out over. Pages are rarely uniform in size.',
      ] },
      { type: 'callout', title: 'Averages lie on mixed documents', text: 'A report with ten photo pages and a hundred text pages does not split evenly. The photo-heavy chunk will be several times the size of a text chunk with the same page count. Check every output, not just the first.' },
      { type: 'h2', text: 'Split at meaningful boundaries where you can' },
      { type: 'p', text: 'Cutting a document mid-sentence to hit a size target makes it hard to read. Where the content has natural joints — chapters, sections, individual invoices in a batch — split there and accept slightly uneven file sizes. Name the parts clearly, and say in your covering message how many there are and in what order.' },
      { type: 'h2', text: 'Better alternatives to splitting' },
      { type: 'table', head: ['Option', 'When it is the right call'], rows: [
        ['Compress the PDF', 'Almost always worth trying first, especially for scans'],
        ['Share a link instead', 'When the recipient can accept a cloud link'],
        ['Send only the pages needed', 'When the recipient asked for one section, not the whole pack'],
        ['Split into parts', 'When the limit is hard and the whole document must go'],
      ] },
      { type: 'p', text: 'Extracting the pages someone actually asked for is frequently the real answer. A twelve-page extract beats four numbered parts of a hundred-page document that nobody will read in full.' },
    ],
    faqs: [
      { q: 'Can I split a PDF into equal file sizes automatically?', a: 'Not precisely, because pages vary enormously in size. Estimate from the average, split by page ranges, then check and adjust.' },
      { q: 'What is the usual email attachment limit?', a: 'Gmail and Outlook both cap at around 25 MB, and many corporate servers are stricter — 10 MB is a common internal limit. Aim comfortably under whichever applies.' },
      { q: 'Do the split parts add up to the original size?', a: 'They usually total slightly more, because each part carries its own copy of the fonts its pages use.' },
      { q: 'Is compressing better than splitting?', a: 'Nearly always, for the reader. One file that opens is better than four that have to be reassembled mentally.' },
    ],
    related: ['how-to-compress-pdf-for-email-attachment', 'how-to-split-a-pdf-into-separate-pages', 'how-to-compress-a-pdf-without-losing-quality'],
  },
];
