import type { BlogPost } from '../types';

export const securityPosts: BlogPost[] = [
  {
    slug: 'how-to-password-protect-a-pdf',
    title: 'How to Password Protect a PDF',
    description: 'Add a password to a PDF so only the people you choose can open it — including how to pick a password and how to get it to the recipient safely.',
    keyword: 'how to password protect a pdf',
    category: 'Security & Privacy',
    published: '2026-02-21',
    updated: '2026-08-14',
    tool: 'protect-pdf',
    blocks: [
      { type: 'p', text: 'Password protection encrypts the contents of a PDF. Without the password the file is unreadable — not hidden, not restricted, genuinely encrypted. It is the right control for a payslip, a contract or a medical record sent by email.' },
      { type: 'h2', text: 'Protect a PDF' },
      { type: 'steps', items: [
        'Open the Protect PDF tool and add your file.',
        'Set a password. Make it a real one, not "1234".',
        'Download the protected file.',
        'Test it by opening the download — you should be asked for the password.',
      ] },
      { type: 'h2', text: 'Two kinds of password' },
      { type: 'table', head: ['Type', 'What it does', 'How strong'], rows: [
        ['User password (open password)', 'Required to open the document at all', 'Real encryption — the content is unreadable without it'],
        ['Owner password (permissions)', 'Restricts printing, copying or editing', 'Advisory — readers choose to honour it'],
      ] },
      { type: 'p', text: 'The distinction matters enormously. An open password means the bytes are encrypted. A permissions password means the file is readable and merely asks software to behave; anything that ignores the request has full access. If the content is genuinely confidential, use an open password.' },
      { type: 'callout', title: 'Never send the password in the same email', text: 'A protected file and its password in one message is a locked door with the key taped to it. Send the file by email and the password by text, phone or a separate channel.' },
      { type: 'h2', text: 'Choosing a password' },
      { type: 'list', items: [
        'Long beats complicated. Four unrelated words are stronger and easier to relay than "P@ssw0rd!".',
        'Do not reuse a password you use anywhere else — this one gets shared.',
        'Avoid anything the recipient could guess from the document: a surname, an invoice number, a date of birth.',
        'Write it down somewhere you will find it. A protected PDF whose password is lost is gone.',
      ] },
      { type: 'h2', text: 'What encryption does not do' },
      { type: 'p', text: 'It protects the file in transit and at rest. It does not stop the recipient forwarding it, printing it, screenshotting it or removing the password once they have opened it. Encryption controls who can open the document, not what an authorised reader does next.' },
      { type: 'h2', text: 'If you lose the password' },
      { type: 'p', text: 'There is no recovery. Strong encryption without the key is exactly as intended: unreadable. Keep an unprotected original somewhere secure, or record the password properly.' },
    ],
    faqs: [
      { q: 'Can a password-protected PDF be cracked?', a: 'A short or common password can be guessed by brute force. A long passphrase with modern encryption is not realistically breakable.' },
      { q: 'What is the difference between the two password types?', a: 'The open password encrypts the file. The permissions password only asks readers to restrict actions, and can be ignored.' },
      { q: 'Can I remove the password later?', a: 'Yes, if you know it. Unlock the file and save an unprotected copy.' },
      { q: 'Does protection stop someone forwarding the file?', a: 'No. Anyone with the password can open, forward and share it.' },
      { q: 'Will the recipient need special software?', a: 'No. Every mainstream PDF reader prompts for the password.' },
    ],
    related: ['how-to-remove-a-password-from-a-pdf', 'pdf-encryption-explained', 'how-to-share-a-pdf-securely'],
  },

  {
    slug: 'how-to-remove-a-password-from-a-pdf',
    title: 'How to Remove a Password From a PDF',
    description: 'Take the password off a PDF you have the right to open, so you can merge, edit or archive it without typing it every time.',
    keyword: 'remove password from pdf',
    category: 'Security & Privacy',
    published: '2026-03-12',
    tool: 'unlock-pdf',
    blocks: [
      { type: 'p', text: 'Bank statements, payslips and insurance documents commonly arrive encrypted. Once you have opened one and want to file it, merge it or search it, retyping the password every single time becomes a genuine nuisance.' },
      { type: 'h2', text: 'Remove the password' },
      { type: 'steps', items: [
        'Open the Unlock PDF tool and add the file.',
        'Enter the password you already use to open it.',
        'Download the unprotected copy.',
        'Store it somewhere appropriately secure — it is now readable by anyone who has it.',
      ] },
      { type: 'callout', title: 'This needs the password', text: 'Removing protection means decrypting with the correct key. A tool that promises to open a PDF whose password you do not know is either wrong about what it does or attacking a permissions setting rather than encryption.' },
      { type: 'h2', text: 'The two things "locked" can mean' },
      { type: 'table', head: ['Symptom', 'What it is', 'What is possible'], rows: [
        ['A password is requested on opening', 'Encrypted with a user password', 'Enter the password to remove it'],
        ['Opens fine, but printing or copying is greyed out', 'A permissions restriction', 'Removable without any password'],
      ] },
      { type: 'p', text: 'The second case is not encryption. The document is fully readable; a flag simply asks software to disable some actions, and the flag can be cleared. That is why removing a print restriction is trivial and removing an open password is not.' },
      { type: 'h2', text: 'When it is legitimate' },
      { type: 'p', text: 'Removing protection from your own documents — your statements, your payslips, files you were sent and are entitled to keep — is ordinary document management. Removing it from someone else\'s confidential file, or circumventing protection to redistribute a document you licensed, is not, and in many places is unlawful.' },
      { type: 'p', text: 'The practical test: were you given the password because you are meant to read this? Then decrypting your own copy for your own filing is fine.' },
      { type: 'h2', text: 'Do it locally' },
      { type: 'p', text: 'Password removal means handing over both a confidential document and the password that opens it. Doing that on a server is a poor trade for convenience. A browser-based tool does the decryption on your own machine, so neither the file nor the password is transmitted.' },
      { type: 'h2', text: 'Afterwards' },
      { type: 'p', text: 'The unlocked copy has no protection at all. If it is going into cloud storage or a shared drive, make sure that location is itself secured — you have moved the protection from the file to wherever you put it.' },
    ],
    faqs: [
      { q: 'Can I remove a password I do not know?', a: 'Not from an encrypted PDF. Permissions restrictions on an unencrypted file are a different matter and can be cleared.' },
      { q: 'Is it legal to remove a PDF password?', a: 'For your own documents, yes. Circumventing protection on material you are not entitled to access is not.' },
      { q: 'Does unlocking change the content?', a: 'No. It writes the same document without encryption.' },
      { q: 'Why can I not merge or edit an encrypted PDF?', a: 'Because the tool cannot read the page structure until it is decrypted. Unlock first.' },
    ],
    related: ['how-to-password-protect-a-pdf', 'pdf-encryption-explained', 'how-to-restrict-editing-in-a-pdf'],
  },

  {
    slug: 'how-to-redact-a-pdf-properly',
    title: 'How to Redact a PDF Properly (Not Just Cover It Up)',
    description: 'Black boxes over text are not redaction — the words are still in the file. Here is how real redaction works and how to verify it worked.',
    keyword: 'how to redact a pdf',
    category: 'Security & Privacy',
    published: '2026-02-28',
    updated: '2026-08-20',
    tool: 'redact-pdf',
    blocks: [
      { type: 'p', text: 'Failed redaction has exposed witness names, unredacted settlement figures and classified passages in court filings, and it happens the same way every time: someone drew a black rectangle over the text and saved the file.' },
      { type: 'h2', text: 'Why a black box is not redaction' },
      { type: 'p', text: 'A PDF page is a stack of drawing instructions. Adding a filled rectangle adds one more instruction on top. The text instruction underneath is untouched — it is simply covered, the way a sheet of paper over a screen covers what is displayed.' },
      { type: 'p', text: 'Select the area and copy it, and the clipboard contains the words. Extract the text and they are all there. Delete the rectangle and the page reads normally again.' },
      { type: 'callout', title: 'The copy-paste test', text: 'Open your redacted PDF, select across a blacked-out passage, and paste it into a text editor. If anything appears, the redaction failed. Do this before sending — every time.' },
      { type: 'h2', text: 'What real redaction does' },
      { type: 'p', text: 'Proper redaction removes the underlying content rather than hiding it. The text instructions inside the marked area are deleted and the region is filled, so there is nothing left to recover — no copy-paste, no extraction, no undo.' },
      { type: 'h2', text: 'How to redact' },
      { type: 'steps', items: [
        'Open the Redact PDF tool and add your document.',
        'Drag a box over each passage that must be removed, working from the page preview.',
        'Cover the whole passage — partial redaction leaves fragments that are often enough to reconstruct the rest.',
        'Apply the redaction and download the result.',
        'Verify: copy from the redacted areas and confirm nothing comes back.',
      ] },
      { type: 'h2', text: 'What people forget to redact' },
      { type: 'list', items: [
        'The same name appearing in a header or footer on every page.',
        'Document metadata — author, title and subject fields often name the person.',
        'Bookmarks and the outline, which can restate a redacted heading.',
        'File attachments embedded in the PDF.',
        'Comments and annotations left by reviewers.',
        'A filename that gives away exactly what you redacted inside.',
      ] },
      { type: 'p', text: 'Strip the metadata as a separate step. It is invisible in the reader and trivially readable by anyone who looks.' },
      { type: 'h2', text: 'Redacting scans' },
      { type: 'p', text: 'A scanned page has no text objects to remove, so covering the area does destroy the information in the image. But if the document has been through OCR, there is an invisible text layer — and that layer still contains the words. Verify with copy-paste exactly as you would on a digital document.' },
      { type: 'h2', text: 'Before you send it' },
      { type: 'steps', items: [
        'Copy from every redacted area and confirm nothing is returned.',
        'Search the document for the name or number you removed.',
        'Check the metadata.',
        'Check headers, footers and bookmarks.',
        'Have a second person look, if the stakes justify it.',
      ] },
    ],
    faqs: [
      { q: 'Is drawing a black box enough?', a: 'No. The text remains in the file and can be copied out. This is the single most common cause of accidental disclosure.' },
      { q: 'Can redaction be undone?', a: 'Not when it is done properly — the content is deleted rather than hidden. Keep the original if you need it.' },
      { q: 'Does redaction remove metadata?', a: 'Not automatically. Clear the metadata separately.' },
      { q: 'How do I redact a scanned document?', a: 'The image area is genuinely destroyed by the redaction. If the file has an OCR text layer, check that too — the words may still be there.' },
      { q: 'How do I verify a redaction?', a: 'Copy from the redacted area, and search the document for the removed term. Both should come back empty.' },
    ],
    related: ['how-to-permanently-remove-text-from-a-pdf', 'how-to-remove-metadata-from-a-pdf', 'how-to-black-out-text-in-a-pdf'],
  },

  {
    slug: 'how-to-black-out-text-in-a-pdf',
    title: 'How to Black Out Text in a PDF So It Cannot Be Recovered',
    description: 'Hiding text and removing text look identical on screen and are completely different in the file. Here is how to do the one that actually works.',
    keyword: 'black out text in pdf',
    category: 'Security & Privacy',
    published: '2026-04-12',
    tool: 'redact-pdf',
    blocks: [
      { type: 'p', text: 'Blacking out text is one of those tasks where the obvious method — draw a black rectangle — produces something that looks exactly like the correct result and offers none of the protection.' },
      { type: 'h2', text: 'The two methods, side by side' },
      { type: 'table', head: ['Method', 'On screen', 'In the file'], rows: [
        ['Draw a black shape', 'Text is hidden', 'Text is intact and copyable'],
        ['Redact', 'Text is hidden', 'Text is deleted'],
      ] },
      { type: 'p', text: 'They are visually indistinguishable, which is precisely why the mistake keeps being made by people who are being careful.' },
      { type: 'h2', text: 'Do it properly' },
      { type: 'steps', items: [
        'Open the Redact PDF tool and add your file.',
        'Drag a box over each passage to remove. Work visually from the page — no coordinates to type.',
        'Extend each box slightly beyond the text so no partial characters survive at the edges.',
        'Apply and download.',
        'Test by copying from the blacked-out regions.',
      ] },
      { type: 'callout', title: 'Redact the pattern, not the instance', text: 'A name usually appears more than once — in the body, in a header, in a signature block, in the metadata. Search the document for every occurrence before you decide you are finished.' },
      { type: 'h2', text: 'Beyond the black boxes' },
      { type: 'p', text: 'Two things routinely survive an otherwise careful redaction.' },
      { type: 'p', text: 'The first is metadata: author, title, subject and producer fields, none of them visible on the page and all of them readable in one click. A document redacted to anonymise its author frequently names the author in its properties.' },
      { type: 'p', text: 'The second is the shape of what you removed. A redaction box exactly as wide as a name narrows the possibilities considerably, and in a short list it can identify the person outright. Where that matters, redact a uniform region rather than a tightly fitted one.' },
      { type: 'h2', text: 'Print and rescan: the crude fallback' },
      { type: 'p', text: 'Printing a document, blacking out passages with a marker, and scanning the result destroys the information completely — there is no digital layer left to recover. It is ugly, it produces a large image-only file, and for a genuinely high-stakes disclosure it is unimpeachable.' },
      { type: 'p', text: 'Use it when the consequences of failure are severe. For everything else, proper redaction plus verification is the right balance.' },
    ],
    faqs: [
      { q: 'Can someone recover text under a black box?', a: 'Yes, trivially — by copying it, or by deleting the shape. Only redaction removes the content.' },
      { q: 'Does exporting to an image make it safe?', a: 'It removes the text layer, so yes for the visible page — but the file becomes unsearchable, much larger, and unreadable by screen readers.' },
      { q: 'Should the box be exactly the width of the text?', a: 'Prefer a uniform width. The length of a redaction can itself reveal what was removed.' },
      { q: 'What about the metadata?', a: 'Clear it separately. It is not touched by redacting the pages.' },
    ],
    related: ['how-to-redact-a-pdf-properly', 'how-to-remove-metadata-from-a-pdf', 'how-to-permanently-remove-text-from-a-pdf'],
  },

  {
    slug: 'how-to-permanently-remove-text-from-a-pdf',
    title: 'How to Permanently Remove Text From a PDF',
    description: 'Delete words, paragraphs or whole passages from a PDF so they cannot be recovered — and how to confirm they are actually gone.',
    keyword: 'permanently remove text from pdf',
    category: 'Security & Privacy',
    published: '2026-04-26',
    tool: 'redact-pdf',
    blocks: [
      { type: 'p', text: 'There is a real difference between text you cannot see and text that is not there. Everything about handling confidential documents depends on knowing which one you have produced.' },
      { type: 'h2', text: 'Things that do not remove text' },
      { type: 'list', items: [
        'Covering it with a black or white rectangle — still in the content stream.',
        'Setting the text colour to match the background — still there, still copyable.',
        'Placing an opaque image over it — the text is underneath.',
        'Flattening the document — merges the covering shape in, leaves the text.',
        'Cropping the page — hides content outside the visible area without deleting it.',
      ] },
      { type: 'p', text: 'Cropping deserves particular attention because it feels so final. A cropped page has a smaller visible area and exactly the same content; changing the crop box back reveals everything.' },
      { type: 'h2', text: 'What does remove it' },
      { type: 'steps', items: [
        'Redact — the only operation that deletes the underlying text objects.',
        'Delete the whole page, when everything on it can go.',
        'Rebuild the document without the passage, if you have the source file.',
        'Print and rescan, which leaves no digital layer at all.',
      ] },
      { type: 'callout', title: 'Verify by searching', text: 'After removing text, search the finished document for a distinctive word from the passage. Copy from the area too. Two checks, ten seconds, and they are the difference between a redaction and an incident.' },
      { type: 'h2', text: 'The places text hides' },
      { type: 'table', head: ['Location', 'Visible in a reader?', 'Recoverable?'], rows: [
        ['Page content stream', 'Yes', 'Yes, unless redacted'],
        ['Document metadata', 'No', 'Yes, in one click'],
        ['Bookmarks and outline', 'In the sidebar', 'Yes'],
        ['Annotations and comments', 'Sometimes', 'Yes'],
        ['Embedded attachments', 'No', 'Yes'],
        ['Incremental save history', 'No', 'Yes, with the right tools'],
      ] },
      { type: 'p', text: 'That last row is the subtle one. PDFs can be saved incrementally, appending changes rather than rewriting the file — which means an earlier, unredacted version may still be inside the same document. Saving as a fresh file rather than appending eliminates it, and a proper redaction tool rewrites the file rather than appending to it.' },
      { type: 'h2', text: 'A workflow that holds up' },
      { type: 'steps', items: [
        'Redact every occurrence of the sensitive content.',
        'Strip the document metadata.',
        'Remove bookmarks and annotations that restate it.',
        'Save as a new file rather than saving over the original.',
        'Search and copy-test the result.',
        'Rename the file so the name itself gives nothing away.',
      ] },
    ],
    faqs: [
      { q: 'Does cropping remove content?', a: 'No. It changes what is displayed. The content outside the crop is still in the file.' },
      { q: 'Can deleted text be recovered from a PDF?', a: 'If it was hidden rather than deleted, yes. If it was properly redacted and the file rewritten, no.' },
      { q: 'What about earlier saved versions inside the file?', a: 'Incremental saves can retain them. Saving as a new file discards the history.' },
      { q: 'Is print-and-rescan overkill?', a: 'For most work, yes. For a disclosure where failure is unacceptable, it is the only method with no digital layer to leak.' },
    ],
    related: ['how-to-redact-a-pdf-properly', 'how-to-remove-metadata-from-a-pdf', 'how-to-black-out-text-in-a-pdf'],
  },

  {
    slug: 'how-to-remove-metadata-from-a-pdf',
    title: 'How to Remove Metadata From a PDF',
    description: 'Your name, your software and your file path may be inside every PDF you send. Here is what is stored, how to see it, and how to strip it.',
    keyword: 'remove metadata from pdf',
    category: 'Security & Privacy',
    published: '2026-05-10',
    tool: 'optimize-pdf',
    blocks: [
      { type: 'p', text: 'Every PDF carries a block of information about itself that never appears on any page. Most people have never looked at it, and it is one click away for anyone who receives the file.' },
      { type: 'h2', text: 'What is in there' },
      { type: 'table', head: ['Field', 'Typically contains'], rows: [
        ['Author', 'Your name, or your computer\'s account name'],
        ['Title', 'Often the original filename, including drafts and codenames'],
        ['Subject and Keywords', 'Whatever the author typed, sometimes internal terms'],
        ['Creator', 'The application that made the document'],
        ['Producer', 'The library or tool that wrote the PDF'],
        ['Created and Modified', 'Timestamps, which reveal working patterns'],
        ['XMP packet', 'Sometimes editing history and file paths'],
      ] },
      { type: 'p', text: 'The awkward ones are Title and the XMP packet. A document titled "offer-v3-lowball" tells the recipient something you did not intend to say, and a file path can expose a client name, a matter number or an internal folder structure.' },
      { type: 'h2', text: 'See what yours says' },
      { type: 'steps', items: [
        'Open the PDF in any reader.',
        'Find document properties — File → Properties in most desktop readers.',
        'Read the Description tab.',
        'Look at the Advanced or Custom tab too, where XMP data appears.',
      ] },
      { type: 'callout', title: 'Check before you send, not after', text: 'Metadata travels with the file to everyone who receives it and to anyone they forward it to. It is a thirty-second check on any document leaving your organisation.' },
      { type: 'h2', text: 'Strip it' },
      { type: 'steps', items: [
        'Open the Optimize PDF tool and add your file.',
        'Run it with metadata removal enabled.',
        'Re-open the result and check the properties are now empty.',
      ] },
      { type: 'p', text: 'Doing this locally matters more here than almost anywhere else: the whole point is that you do not want this information distributed, and uploading the file to strip it distributes it.' },
      { type: 'h2', text: 'When you should keep it' },
      { type: 'p', text: 'Metadata is not always a liability. Archives depend on it; PDF/A requires structured metadata by design; a published report benefits from a proper title and author, and search engines use both. Strip it for confidential correspondence and disclosures, curate it for published documents.' },
      { type: 'h2', text: 'The rest of the invisible content' },
      { type: 'list', items: [
        'Annotations and comments left by reviewers.',
        'Bookmarks naming sections that were later cut.',
        'Embedded file attachments.',
        'Form field values that no longer display.',
        'Earlier revisions retained by incremental saving.',
      ] },
      { type: 'p', text: 'A full clean-up pass handles these together, which is why "optimise" is the operation that removes metadata rather than a dedicated metadata tool.' },
    ],
    faqs: [
      { q: 'Can the recipient see who created my PDF?', a: 'Usually, yes — the Author field is one click away in any reader.' },
      { q: 'Does redacting remove metadata?', a: 'No. Page content and document metadata are separate; strip them as separate steps.' },
      { q: 'Is metadata used by search engines?', a: 'Yes. Title and description influence how a PDF appears in results, which is a reason to curate it on published files.' },
      { q: 'Can metadata be recovered after stripping?', a: 'Not from the cleaned file. Anyone holding an earlier copy still has it.' },
    ],
    related: ['how-to-redact-a-pdf-properly', 'what-personal-data-is-hidden-in-your-pdf', 'how-to-share-a-pdf-securely'],
  },

  {
    slug: 'is-it-safe-to-use-online-pdf-tools',
    title: 'Is It Safe to Use Online PDF Tools?',
    description: 'Some online PDF tools upload your documents to a server; some never transmit them at all. How to tell which you are using, and how to check.',
    keyword: 'are online pdf tools safe',
    category: 'Security & Privacy',
    published: '2026-03-30',
    updated: '2026-08-16',
    tool: 'merge-pdf',
    blocks: [
      { type: 'p', text: 'It is a fair question and the honest answer is: it depends entirely on where the work happens. Two websites that look identical can treat your document in completely different ways.' },
      { type: 'h2', text: 'The two architectures' },
      { type: 'table', head: ['', 'Server-side', 'Browser-side'], rows: [
        ['Your file is', 'Uploaded to a server', 'Read locally by the page'],
        ['Processing happens', 'On their machines', 'On yours'],
        ['They could retain it', 'Yes', 'No — they never receive it'],
        ['Works offline', 'No', 'Yes, once loaded'],
        ['Limited by', 'Their upload cap', 'Your device memory'],
      ] },
      { type: 'p', text: 'Server-side is not inherently disreputable — it is how most tools were built, and it handles very large files well. It does mean your document is in someone else\'s custody, governed by a retention policy you have to take on trust.' },
      { type: 'h2', text: 'How to tell which one you are using' },
      { type: 'steps', items: [
        'Open developer tools with F12, or Cmd+Option+I on a Mac.',
        'Go to the Network tab and clear it.',
        'Process a file.',
        'Look for a large POST request. That is your document going out.',
        'For certainty, disconnect from the internet after the page loads. If the tool still works, nothing was uploaded.',
      ] },
      { type: 'callout', title: 'The offline test settles it', text: 'A privacy policy is a promise; completing the job with the network off is a demonstration. It is the one check that cannot be spun.' },
      { type: 'h2', text: 'Questions worth asking about an uploading tool' },
      { type: 'list', items: [
        'How long are files retained, and is deletion verifiable?',
        'Which jurisdiction are the servers in?',
        'Is the connection encrypted end to end, and is storage encrypted at rest?',
        'Who has access internally?',
        'Are documents used to train anything?',
      ] },
      { type: 'p', text: 'Reputable services answer these clearly. A tool with no privacy policy at all is answering by omission.' },
      { type: 'h2', text: 'What genuinely should not be uploaded' },
      { type: 'p', text: 'Client files under professional privilege. Medical records. Anything covered by an NDA. Identity documents. Financial statements with account numbers. Not because a specific service is untrustworthy, but because you generally cannot obtain permission to hand these to a third party, and you rarely have to.' },
      { type: 'h2', text: 'The trade-off, stated plainly' },
      { type: 'p', text: 'Local processing costs you speed on very large files and the first page load is bigger. In exchange, the document never leaves your device. For most jobs the performance difference is imperceptible and the privacy difference is absolute.' },
    ],
    faqs: [
      { q: 'Are free PDF tools safe?', a: 'Free says nothing about safety. What matters is whether the file is uploaded, and what happens to it if it is.' },
      { q: 'How do I check whether a tool uploads my file?', a: 'Watch the Network tab in developer tools, or simply disconnect from the internet and see whether it still works.' },
      { q: 'Is a tool with HTTPS safe?', a: 'HTTPS protects the file in transit. It says nothing about what happens once it arrives.' },
      { q: 'Can browser-based tools handle large files?', a: 'Up to the limits of your device memory. Very large jobs are where server-side tools have a real advantage.' },
    ],
    related: ['merge-pdf-without-uploading-files', 'how-to-share-a-pdf-securely', 'what-personal-data-is-hidden-in-your-pdf'],
  },
];
