import type { BlogPost } from '../types';

export const securityPosts2: BlogPost[] = [
  {
    slug: 'how-to-add-a-watermark-to-a-pdf',
    title: 'How to Add a Watermark to a PDF',
    description: 'Stamp DRAFT, CONFIDENTIAL or a recipient name across every page — how to make it readable without obscuring the document underneath.',
    keyword: 'how to add a watermark to a pdf',
    category: 'Security & Privacy',
    published: '2026-05-24',
    tool: 'add-watermark',
    blocks: [
      { type: 'p', text: 'A watermark states what a document is before anyone reads a word of it: a draft, a copy, confidential, issued to a named person. It is a labelling device, not a security control, and it is very good at the job it actually does.' },
      { type: 'h2', text: 'Add a watermark' },
      { type: 'steps', items: [
        'Open the Add Watermark tool and add your PDF.',
        'Type the text — DRAFT, CONFIDENTIAL, a name, a date.',
        'Set the angle, size and opacity. Diagonal at low opacity is the convention for a reason.',
        'Preview it over a text-heavy page, not the title page.',
        'Apply and download.',
      ] },
      { type: 'h2', text: 'Getting the settings right' },
      { type: 'table', head: ['Setting', 'Recommended', 'Why'], rows: [
        ['Opacity', '10–20%', 'Legible as a label, transparent enough to read through'],
        ['Angle', '45 degrees', 'Crosses the text without following any line of it'],
        ['Size', 'Roughly half the page width', 'Unmistakable without swamping the content'],
        ['Colour', 'Mid grey', 'Neutral in print and on screen'],
        ['Position', 'Centred', 'Cannot be cropped off the edge'],
      ] },
      { type: 'callout', title: 'Test it on the busiest page', text: 'A watermark that looks subtle over a title page can make a dense table unreadable. Check the page with the most on it before you commit.' },
      { type: 'h2', text: 'What a watermark does and does not do' },
      { type: 'p', text: 'It communicates status, discourages casual misuse, and — when it carries a recipient name — makes a leaked copy traceable back to who was given it. That last use is the one with real teeth, because people behave differently with a document that has their own name across it.' },
      { type: 'p', text: 'It does not prevent copying, printing, editing or redistribution. Anyone determined can remove it, particularly from a digital PDF where it is simply another object on the page. Treat it as a label, not a lock.' },
      { type: 'h2', text: 'Watermarking each recipient differently' },
      { type: 'p', text: 'For circulating a sensitive draft, generate one copy per recipient with their name and the date on it. It costs a few minutes, it changes how the document is handled, and if it does leak you know which copy it was.' },
      { type: 'h2', text: 'Removing one' },
      { type: 'p', text: 'On a document you own — a draft becoming final, a template you are reusing — go back to the source and export again without it. Removing a watermark from someone else\'s document to obscure its provenance is a different matter, and usually a licensing or copyright breach.' },
    ],
    faqs: [
      { q: 'Does a watermark stop people copying my PDF?', a: 'No. It labels the document; it does not restrict any action.' },
      { q: 'What opacity should I use?', a: '10–20%. Above 30% the document becomes hard to read; below 10% the watermark stops registering.' },
      { q: 'Can I watermark only some pages?', a: 'Yes, though for a status label it is usually clearer on every page.' },
      { q: 'Can a watermark be removed?', a: 'From a digital PDF, by someone determined — it is an object on the page like any other.' },
    ],
    related: ['how-to-protect-a-pdf-from-copying', 'how-to-share-a-pdf-securely', 'how-to-add-a-header-and-footer-to-a-pdf'],
  },

  {
    slug: 'pdf-encryption-explained',
    title: 'PDF Encryption Explained: What Actually Protects Your File',
    description: 'AES-256, RC4, user and owner passwords, permission flags — what each one really does, and which of them provide genuine protection.',
    keyword: 'pdf encryption explained',
    category: 'Security & Privacy',
    published: '2026-06-07',
    tool: 'protect-pdf',
    blocks: [
      { type: 'p', text: 'PDF security is a stack of features with very different strengths, presented in most software as one dialogue. Knowing which parts are cryptography and which are politeness is the whole subject.' },
      { type: 'h2', text: 'The two passwords' },
      { type: 'p', text: 'A user password encrypts the document. Without it, the contents are ciphertext — no software can display them, because there is nothing to display until the key is supplied. This is real protection.' },
      { type: 'p', text: 'An owner password sets permission flags: no printing, no copying, no editing. The document is not encrypted against the reader at all; it is fully readable, and a flag politely asks software to disable certain actions. Compliant readers honour it. Anything else does not have to.' },
      { type: 'table', head: ['Control', 'Mechanism', 'Real protection?'], rows: [
        ['User password', 'Encryption', 'Yes, with a strong password'],
        ['Owner password', 'Permission flags', 'No — advisory only'],
        ['No printing', 'Flag', 'No'],
        ['No copying', 'Flag', 'No'],
        ['No editing', 'Flag', 'No'],
      ] },
      { type: 'h2', text: 'The encryption algorithms' },
      { type: 'list', items: [
        'RC4 40-bit — from the 1990s, broken, present only in very old files.',
        'RC4 128-bit — obsolete and not considered secure.',
        'AES-128 — still sound in practice.',
        'AES-256 — the current standard and what any modern tool should produce.',
      ] },
      { type: 'p', text: 'If you are creating protection today, AES-256 is the only sensible choice. If you are relying on protection someone applied a decade ago, it may be considerably weaker than it looks.' },
      { type: 'callout', title: 'The password is the weak point, not the algorithm', text: 'AES-256 with the password "Summer2026" is not secure — the attack is on the password, not the cipher. Four unrelated words beat any amount of punctuation-substitution.' },
      { type: 'h2', text: 'What encryption cannot do' },
      { type: 'p', text: 'It controls who can open the file. It has nothing to say about what an authorised reader does afterwards: they can forward it, print it, photograph the screen, or strip the protection from their own copy. Any claim that a PDF can be prevented from being shared after opening is describing DRM, which needs separate infrastructure and is not what a password does.' },
      { type: 'h2', text: 'Choosing the right control' },
      { type: 'table', head: ['Goal', 'Use'], rows: [
        ['Only certain people may read this', 'User password with AES-256'],
        ['Signal that this should not be edited', 'Permission flags, understood as advisory'],
        ['Prove the document has not been altered', 'A digital signature, not encryption'],
        ['Trace a leaked copy', 'Per-recipient watermarking'],
      ] },
    ],
    faqs: [
      { q: 'Is PDF encryption secure?', a: 'AES-256 with a strong password is. Permission flags are not encryption and offer no real protection.' },
      { q: 'Can PDF encryption be broken?', a: 'Not the modern cipher. Weak passwords and obsolete RC4 encryption both can be.' },
      { q: 'Why can some tools remove a PDF password without knowing it?', a: 'Because they are clearing permission flags on an unencrypted file, not decrypting anything.' },
      { q: 'Does encryption stop editing?', a: 'It stops opening. Anyone who can open the file can edit their copy.' },
    ],
    related: ['how-to-password-protect-a-pdf', 'how-to-restrict-editing-in-a-pdf', 'how-to-remove-a-password-from-a-pdf'],
  },

  {
    slug: 'how-to-share-a-pdf-securely',
    title: 'How to Share a PDF Securely',
    description: 'Sending a confidential document by email is riskier than most people assume. Practical steps that fit real workflows, ranked by how much they help.',
    keyword: 'how to share a pdf securely',
    category: 'Security & Privacy',
    published: '2026-06-21',
    tool: 'protect-pdf',
    blocks: [
      { type: 'p', text: 'Most confidential documents leak through ordinary carelessness rather than attack: sent to the wrong address, forwarded onward, left in an inbox for a decade, or handed to a website in order to be compressed.' },
      { type: 'h2', text: 'Before you send anything' },
      { type: 'steps', items: [
        'Send only what is needed — extract the relevant pages rather than the whole pack.',
        'Redact anything the recipient should not see, and verify it.',
        'Strip the metadata, which routinely names the author and the file path.',
        'Check the filename does not itself disclose something.',
        'Check the recipient address character by character. Autocomplete is the leading cause of misdirected documents.',
      ] },
      { type: 'h2', text: 'Choosing how to send it' },
      { type: 'table', head: ['Method', 'Protection', 'Practicality'], rows: [
        ['Plain email attachment', 'Very little', 'Universal'],
        ['Password-protected PDF by email', 'Good, if the password goes separately', 'Universal'],
        ['Cloud link to a named person', 'Good — revocable, and access is logged', 'Very good'],
        ['Cloud link with "anyone with the link"', 'Weak — the link is the credential', 'Very good'],
        ['Secure file transfer service', 'Strong', 'Needs the recipient to cooperate'],
        ['Encrypted archive', 'Good', 'Awkward on phones'],
      ] },
      { type: 'callout', title: 'Separate the file from the key', text: 'Password and document in the same email is theatre. Send the file by email and the password by text or phone, and the two would have to be compromised independently.' },
      { type: 'h2', text: 'The advantage of a revocable link' },
      { type: 'p', text: 'An attachment is permanent — once sent, it exists in someone else\'s mailbox forever and is beyond your reach. A link shared with a named account can be revoked, expired, and audited, and if you sent it to the wrong person you can withdraw access before it is opened.' },
      { type: 'p', text: 'The caveat is the "anyone with the link" setting, which turns the URL into the password and is regularly indexed, forwarded and pasted into tickets.' },
      { type: 'h2', text: 'Preparing the document itself' },
      { type: 'p', text: 'If you are compressing, converting or redacting before sending, do it locally. Uploading a confidential file to a third-party tool in order to prepare it for secure delivery undoes the point of the exercise — and it is easy to check whether a tool uploads.' },
      { type: 'h2', text: 'After it has gone' },
      { type: 'list', items: [
        'Note what you sent, to whom, and when.',
        'Set an expiry on links rather than leaving them open indefinitely.',
        'Review shared-link permissions periodically; they accumulate.',
        'If you send to the wrong person, revoke immediately and say so — speed matters more than embarrassment.',
      ] },
    ],
    faqs: [
      { q: 'Is emailing a PDF secure?', a: 'Transport is usually encrypted, but the file sits readable in mailboxes at both ends indefinitely. For confidential material, protect the file or use a link.' },
      { q: 'Password protection or a cloud link?', a: 'A link to a named person is stronger, because access can be revoked and audited. A password is more universal.' },
      { q: 'How should I send the password?', a: 'By a different channel — text or phone. Never in the same email as the file.' },
      { q: 'Is a link with "anyone can view" safe?', a: 'Only as safe as the link, which will be forwarded. Restrict to named accounts for anything sensitive.' },
    ],
    related: ['how-to-password-protect-a-pdf', 'is-it-safe-to-use-online-pdf-tools', 'how-to-remove-metadata-from-a-pdf'],
  },

  {
    slug: 'how-to-restrict-editing-in-a-pdf',
    title: 'How to Restrict Editing in a PDF',
    description: 'Stop a PDF being casually altered — what permission settings actually achieve, and the three approaches that provide genuine assurance.',
    keyword: 'restrict editing in pdf',
    category: 'Security & Privacy',
    published: '2026-07-05',
    tool: 'protect-pdf',
    blocks: [
      { type: 'p', text: '"Make this uneditable" is a reasonable request with an awkward answer: PDF permission settings ask software not to allow editing, and any software may decline the request.' },
      { type: 'h2', text: 'What permission flags do' },
      { type: 'p', text: 'Setting an owner password writes flags into the document — no editing, no copying, no printing. Compliant readers grey out those functions. The file itself is not encrypted against the reader, and a tool that ignores the flags has complete access.' },
      { type: 'p', text: 'They are still worth setting. They stop accidental edits, they make intent explicit, and most people use compliant software. They are a fence, not a wall.' },
      { type: 'h2', text: 'The three approaches that do more' },
      { type: 'h3', text: 'Flatten the document' },
      { type: 'p', text: 'Merging form fields and annotations into the page removes the easy edit paths. Someone can still alter the page content with the right tool, but the casual "click and type" route is gone.' },
      { type: 'h3', text: 'Sign it digitally' },
      { type: 'p', text: 'A digital signature does not prevent editing — it detects it. Any change breaks the cryptographic seal and the reader displays a warning. For contracts and filings this is the meaningful control: you cannot stop alteration, but you can make it undeniable.' },
      { type: 'h3', text: 'Encrypt it' },
      { type: 'p', text: 'A user password stops anyone opening the document without the key. It does not restrict what a key holder does, but it does control who gets that far.' },
      { type: 'table', head: ['Goal', 'Best control'], rows: [
        ['Prevent accidental edits', 'Permission flags plus flattening'],
        ['Prove the document is unaltered', 'Digital signature'],
        ['Control who can read it', 'User password'],
        ['Prevent all copying and forwarding', 'Not achievable with PDF alone'],
      ] },
      { type: 'callout', title: 'Nothing stops a screenshot', text: 'Any document a person can read, they can photograph. Every restriction is about raising effort and establishing accountability, not about making content impossible to capture.' },
      { type: 'h2', text: 'What to do in practice' },
      { type: 'steps', items: [
        'Flatten form fields and annotations so nothing is casually editable.',
        'Apply permission restrictions to signal intent.',
        'Sign the document if alteration would matter.',
        'Encrypt it if only certain people should read it.',
        'Keep the authoritative original yourself — the strongest control of all.',
      ] },
      { type: 'h2', text: 'Setting expectations with the recipient' },
      { type: 'p', text: 'The most effective control is frequently not technical. Saying plainly which version is authoritative, that changes must come back as comments rather than edits, and that you will circulate any revision yourself, resolves most of what restrictions are reaching for.' },
      { type: 'p', text: 'Combine it with a footer stating the version and date, so any copy in circulation identifies itself. When someone quotes a clause from an old draft, the version marker settles the question in one line.' },
      { type: 'h2', text: 'Keeping the authoritative copy' },
      { type: 'p', text: 'Whatever protection you apply, the copy you hold is the one that matters. Keep the original somewhere you control, note what you sent and to whom, and treat every distributed copy as a snapshot rather than as the document. That framing is more robust than any flag in the file.' },
    ],
    faqs: [
      { q: 'Can I make a PDF completely uneditable?', a: 'No. You can make editing inconvenient and detectable, which is what the available controls achieve.' },
      { q: 'Do permission passwords work?', a: 'Compliant readers honour them; other software ignores them. Useful against accident, not against intent.' },
      { q: 'Is a digital signature better?', a: 'For proving integrity, yes — it makes any change visible to the recipient.' },
      { q: 'Does converting to images stop editing?', a: 'It makes text editing hard and destroys searchability, accessibility and file size. Rarely a good trade.' },
    ],
    related: ['pdf-encryption-explained', 'how-to-flatten-a-pdf', 'how-to-tell-if-a-pdf-has-been-edited'],
  },

  {
    slug: 'how-to-tell-if-a-pdf-has-been-edited',
    title: 'How to Tell If a PDF Has Been Edited',
    description: 'Checks that reveal whether a document has been altered — metadata, digital signatures, incremental save history and visual inconsistencies.',
    keyword: 'how to tell if a pdf has been edited',
    category: 'Security & Privacy',
    published: '2026-07-19',
    tool: 'compare-pdf',
    blocks: [
      { type: 'p', text: 'This comes up in disputes, in due diligence and in fraud checks: is this invoice, contract or certificate the document it claims to be?' },
      { type: 'h2', text: 'Start with the metadata' },
      { type: 'steps', items: [
        'Open document properties in any reader.',
        'Compare the creation and modification dates. A modification date later than creation means the file was saved again.',
        'Look at Producer. A document supposedly generated by an accounting system that reports a PDF editor as its producer is worth a question.',
        'Check for two different tools listed as Creator and Producer, which often indicates a document that was made in one place and altered in another.',
      ] },
      { type: 'p', text: 'None of this is proof. Metadata can be edited, and many legitimate workflows re-save a document. It tells you where to look.' },
      { type: 'h2', text: 'Check for a digital signature' },
      { type: 'p', text: 'This is the only conclusive test. A signed PDF carries a cryptographic hash of its contents; any subsequent change breaks it, and every mainstream reader reports the signature as invalid. A valid signature is strong evidence the document is exactly as signed.' },
      { type: 'p', text: 'Most documents are not signed, which is why the other checks exist.' },
      { type: 'callout', title: 'Incremental saves leave a trail', text: 'PDFs can be saved by appending changes rather than rewriting. A file with several appended revisions has an edit history inside it, and forensic tools can recover earlier states — including text that was later covered over.' },
      { type: 'h2', text: 'Visual inconsistencies' },
      { type: 'list', items: [
        'A number or name in a slightly different font or weight from its neighbours.',
        'Text baselines that do not align across a line.',
        'A patch of background that is a marginally different white, where something was covered.',
        'Spacing around one figure that differs from the rest of the column.',
        'A page whose dimensions differ from the others, suggesting a replacement.',
      ] },
      { type: 'p', text: 'Zooming to 400% on a suspect figure is remarkably effective. Altered text rarely matches the original rendering exactly.' },
      { type: 'h2', text: 'Compare against a known copy' },
      { type: 'p', text: 'If you have the original — from the issuer, from an archive, from your own records — a comparison tool will show you every difference directly. That is faster and far more reliable than inference from metadata.' },
      { type: 'h2', text: 'The limits' },
      { type: 'p', text: 'A careful alteration on an unsigned document, saved as a fresh file with cleaned metadata, can be undetectable from the file alone. When it matters, verify with the issuer rather than with the document. For a formal dispute, a forensic examiner has tools and standing that a reader does not.' },
    ],
    faqs: [
      { q: 'Does the modification date prove editing?', a: 'It shows the file was saved again, which happens for innocent reasons too. It is a prompt to look further, not proof.' },
      { q: 'Can metadata be faked?', a: 'Yes, easily. Treat it as an indicator rather than evidence.' },
      { q: 'What is the most reliable check?', a: 'A digital signature. If it validates, the content is exactly as signed.' },
      { q: 'Can editing be detected on a scanned PDF?', a: 'Sometimes, through compression inconsistencies around an altered region. It is a forensic job rather than a desktop one.' },
    ],
    related: ['how-to-compare-two-pdfs', 'how-to-restrict-editing-in-a-pdf', 'electronic-signature-vs-digital-signature'],
  },

  {
    slug: 'what-personal-data-is-hidden-in-your-pdf',
    title: 'What Personal Data Is Hidden in Your PDF',
    description: 'PDFs carry information that never appears on a page — names, file paths, timestamps, revisions and attachments. Here is how to find and remove it.',
    keyword: 'hidden data in pdf',
    category: 'Security & Privacy',
    published: '2026-08-02',
    tool: 'optimize-pdf',
    blocks: [
      { type: 'p', text: 'What you see when you open a PDF is the page content. The file contains a good deal more, and none of it is difficult for a recipient to reach.' },
      { type: 'h2', text: 'Where information hides' },
      { type: 'table', head: ['Location', 'What it can reveal'], rows: [
        ['Document metadata', 'Author name, original title, software, timestamps'],
        ['XMP packet', 'Editing history, sometimes full file paths'],
        ['Annotations', 'Reviewer comments and internal discussion'],
        ['Bookmarks', 'Section names from an earlier draft'],
        ['Form fields', 'Values that no longer display on the page'],
        ['Attachments', 'Entire files embedded inside the PDF'],
        ['Incremental saves', 'Earlier versions of the document'],
        ['Hidden layers', 'Content that is present but not displayed'],
        ['Content outside the crop', 'Anything cropped away rather than deleted'],
      ] },
      { type: 'p', text: 'The last two are the ones that cause incidents. Cropping and hiding both remove content from view without removing it from the file.' },
      { type: 'h2', text: 'Real ways this goes wrong' },
      { type: 'list', items: [
        'A tender submission whose Author field names a competitor, because the template was reused.',
        'A file path revealing a client name in a folder structure: /Clients/Acme-Litigation/.',
        'Review comments left in a document sent to the subject of those comments.',
        'A cropped page still containing the personal details that were cropped away.',
        'A bookmark naming a section that was cut from the final version.',
      ] },
      { type: 'callout', title: 'Check any document that leaves your organisation', text: 'Open the properties, look at the annotations, check the bookmarks. It takes half a minute and it is the difference between a routine send and an incident report.' },
      { type: 'h2', text: 'Cleaning a document properly' },
      { type: 'steps', items: [
        'Redact anything sensitive on the pages, and verify by copy-paste.',
        'Strip the metadata.',
        'Remove annotations and comments.',
        'Remove bookmarks that name removed content.',
        'Flatten form fields so no stored values remain.',
        'Remove embedded attachments unless they belong there.',
        'Save as a new file so no incremental history survives.',
        'Rename the file so its name discloses nothing.',
      ] },
      { type: 'h2', text: 'And do it locally' },
      { type: 'p', text: 'Uploading a document to a website in order to remove the private information from it is a contradiction worth noticing. Tools that process in your browser never receive the file, which is the appropriate property for this particular job.' },
    ],
    faqs: [
      { q: 'Can a recipient see my name in a PDF?', a: 'Usually — the Author field is visible in document properties in any reader.' },
      { q: 'Does cropping remove content?', a: 'No. It changes the visible area. The cropped content is still in the file.' },
      { q: 'How do I remove everything hidden at once?', a: 'A full optimisation pass with metadata removal covers most of it. Redaction, flattening and attachment removal are separate deliberate steps.' },
      { q: 'Is this a GDPR issue?', a: 'It can be. Personal data in metadata is still personal data, and disclosing it unintentionally is still disclosure.' },
    ],
    related: ['how-to-remove-metadata-from-a-pdf', 'how-to-redact-a-pdf-properly', 'how-to-share-a-pdf-securely'],
  },

  {
    slug: 'how-to-protect-a-pdf-from-copying',
    title: 'How to Stop People Copying Text From Your PDF',
    description: 'What the "no copying" setting really does, why it is easy to bypass, and the approaches that offer meaningful protection instead.',
    keyword: 'protect pdf from copying',
    category: 'Security & Privacy',
    published: '2026-08-13',
    tool: 'protect-pdf',
    blocks: [
      { type: 'p', text: 'PDF has a permission flag that says "copying not allowed". It is worth understanding exactly what that flag is before deciding how much to rely on it.' },
      { type: 'h2', text: 'What the copy restriction is' },
      { type: 'p', text: 'It is a boolean stored in the document, protected by an owner password. Compliant readers see it and disable text selection. The document is not encrypted; the text sits in the file exactly as it would otherwise, and anything that does not consult the flag can read it directly.' },
      { type: 'p', text: 'So the restriction stops a reader in Acrobat from selecting a paragraph, and stops nobody from extracting the text with a script.' },
      { type: 'h2', text: 'Ways around it, in ascending order of effort' },
      { type: 'list', items: [
        'Open the file in a reader that ignores permission flags.',
        'Remove the flag — it takes seconds and needs no password.',
        'Extract the text programmatically.',
        'Screenshot the pages and run OCR.',
        'Photograph the screen.',
      ] },
      { type: 'p', text: 'The last option defeats every technical control that has ever existed, which is the fundamental limit here: a document a person can read is a document a person can copy.' },
      { type: 'callout', title: 'The honest framing', text: 'You cannot stop copying. You can raise the effort required, and you can make unauthorised copies traceable. Those are different goals from prevention and both are achievable.' },
      { type: 'h2', text: 'What actually helps' },
      { type: 'table', head: ['Approach', 'What it achieves'], rows: [
        ['Permission flags', 'Stops casual copying by ordinary readers'],
        ['Per-recipient watermarks', 'Makes a leaked copy traceable to who received it'],
        ['User password', 'Controls who can open it at all'],
        ['Sending only what is needed', 'Limits the exposure whatever happens'],
        ['A licence or NDA', 'Makes misuse actionable — often the real deterrent'],
        ['Rendering pages as images', 'Blocks text extraction, at a heavy cost'],
      ] },
      { type: 'h2', text: 'Why image-only PDFs are a poor answer' },
      { type: 'p', text: 'Converting pages to images does prevent text selection. It also makes the document unsearchable, inaccessible to screen readers, several times larger, and blurry when zoomed — and OCR reverses it in about a minute. You lose a great deal to buy a delay.' },
      { type: 'h2', text: 'A proportionate approach' },
      { type: 'p', text: 'Set the permission flags, because they cost nothing and stop the casual case. Watermark each recipient\'s copy, because accountability changes behaviour. Put the terms in writing. And accept that a determined reader will copy the text — plan for what happens then rather than pretending it cannot.' },
    ],
    faqs: [
      { q: 'Can I stop text being copied from my PDF?', a: 'Not reliably. The flag stops casual copying in compliant readers and nothing more.' },
      { q: 'Does converting to images work?', a: 'It blocks selection until someone runs OCR, and it costs you search, accessibility and file size in the meantime.' },
      { q: 'What about DRM?', a: 'Proper DRM requires a licence server and specific reader software, and works only within that ecosystem. It is a different product from a PDF password.' },
      { q: 'Is watermarking useful?', a: 'Very. A per-recipient watermark makes leaks traceable, which deters more effectively than any flag.' },
    ],
    related: ['how-to-add-a-watermark-to-a-pdf', 'pdf-encryption-explained', 'how-to-restrict-editing-in-a-pdf'],
  },
];
