import type { BlogPost } from '../types';

export const troubleshootingPosts2: BlogPost[] = [
  {
    slug: 'pdf-vs-pdfa-what-is-the-difference',
    title: 'PDF vs PDF/A: What Is the Difference?',
    description: 'PDF/A is PDF with the unpredictable parts removed. What is restricted, why archives insist on it, and when you need it.',
    keyword: 'pdf vs pdfa',
    category: 'Troubleshooting',
    published: '2026-07-11',
    tool: 'pdf-to-pdfa',
    blocks: [
      { type: 'p', text: 'PDF/A is not a different format so much as a promise about a PDF: that everything needed to display it correctly is inside the file, and that nothing in it depends on the outside world.' },
      { type: 'h2', text: 'What PDF/A forbids' },
      { type: 'table', head: ['Feature', 'Standard PDF', 'PDF/A'], rows: [
        ['Fonts referenced but not embedded', 'Allowed', 'Forbidden'],
        ['Encryption', 'Allowed', 'Forbidden'],
        ['JavaScript', 'Allowed', 'Forbidden'],
        ['Audio and video', 'Allowed', 'Forbidden'],
        ['External content references', 'Allowed', 'Forbidden'],
        ['Device-dependent colour', 'Allowed', 'Forbidden'],
        ['Structured XMP metadata', 'Optional', 'Required'],
      ] },
      { type: 'p', text: 'Every restriction addresses the same risk: something that renders correctly today because of the environment, and will not render correctly in twenty years when the environment has changed.' },
      { type: 'h2', text: 'Why encryption is banned' },
      { type: 'p', text: 'It surprises people that an archival format forbids protection. The reasoning is that an archive exists to be readable. A password that is lost — and over decades, it will be — makes the document permanently inaccessible, which defeats the entire purpose. Protect the repository, not the file.' },
      { type: 'h2', text: 'The conformance levels' },
      { type: 'list', items: [
        'PDF/A-1b — appearance is preserved. The baseline.',
        'PDF/A-1a — appearance plus tagged structure and reading order, for accessibility.',
        'PDF/A-2 — adds JPEG 2000, transparency and PDF/A attachments.',
        'PDF/A-3 — adds arbitrary attachments, used by e-invoicing standards.',
        'PDF/A-4 — the current revision, simplified and based on PDF 2.0.',
      ] },
      { type: 'callout', title: 'Ask which level is required', text: 'Requirements often say only "PDF/A". Where the answer determines whether a filing is accepted, ask — the difference between 1b and 1a is substantial work.' },
      { type: 'h2', text: 'When you need it' },
      { type: 'p', text: 'Court filings, government submissions, national archives, academic deposits, regulated records retention and long-term corporate archives. If a body has a retention obligation measured in decades, it will usually specify PDF/A.' },
      { type: 'p', text: 'For everyday documents it adds file size and removes flexibility for no benefit. Use it where longevity is the requirement, not by default.' },
      { type: 'h2', text: 'Converting' },
      { type: 'p', text: 'Conversion embeds fonts, fixes the colour handling and writes the metadata. Expect the file to grow. Run OCR first on any scan — an archival file containing unsearchable images meets the standard and fails the purpose.' },
      { type: 'h2', text: 'How to tell what you have' },
      { type: 'p', text: 'Most readers display a notice when a document declares PDF/A conformance, and the conformance level is recorded in the document metadata. If you need certainty — for a filing that will be rejected otherwise — a validator checks the file against the standard properly rather than trusting the declaration.' },
      { type: 'p', text: 'A file can claim conformance and fail validation, usually because it was converted by a tool that wrote the metadata without enforcing every rule. Where acceptance depends on it, validate rather than assume.' },
      { type: 'h2', text: 'Keeping both copies' },
      { type: 'p', text: 'The archival copy and the working copy have different jobs. Keep the PDF/A version in the archive, where it will still open in twenty years, and keep the original for everyday use — smaller, editable, and free of the constraints. Storing only the archival version is a common mistake that makes routine work harder for no benefit.' },
    ],
    faqs: [
      { q: 'Can I open a PDF/A in a normal reader?', a: 'Yes. It is an ordinary PDF that satisfies extra constraints.' },
      { q: 'Is PDF/A better than PDF?', a: 'Better for archiving. Worse for everything else, because of the restrictions.' },
      { q: 'Can I password-protect a PDF/A?', a: 'No. Encryption is forbidden by the standard.' },
      { q: 'Does converting change the appearance?', a: 'It should not. Transparency effects may be flattened when converting to the older levels.' },
    ],
    related: ['how-to-convert-pdf-to-pdfa-for-archiving', 'how-to-fix-fonts-not-displaying-in-a-pdf', 'what-is-a-pdf-file'],
  },

  {
    slug: 'how-to-compare-two-pdfs',
    title: 'How to Compare Two PDFs and Find What Changed',
    description: 'Spot the differences between two versions of a contract or report — what a comparison tool can catch, and what still needs a human.',
    keyword: 'how to compare two pdfs',
    category: 'Troubleshooting',
    published: '2026-07-25',
    tool: 'compare-pdf',
    blocks: [
      { type: 'p', text: 'Someone returns a contract "with a few small changes". Reading forty pages twice to find them is a poor use of an afternoon, and it is exactly the kind of task where the eye reliably skips the one change that matters.' },
      { type: 'h2', text: 'Compare two files' },
      { type: 'steps', items: [
        'Open the Compare PDF tool and add both versions.',
        'Put them in order — the original first, the revised second.',
        'Run the comparison. Differences are reported page by page.',
        'Review each one and decide whether it was expected.',
      ] },
      { type: 'h2', text: 'Two kinds of comparison' },
      { type: 'table', head: ['Type', 'Finds', 'Misses'], rows: [
        ['Text comparison', 'Added, removed and altered wording', 'Formatting and layout changes'],
        ['Visual comparison', 'Anything that looks different, including formatting', 'Reflows the whole page when one word changes'],
      ] },
      { type: 'p', text: 'Text comparison is the one you want for contracts. Visual comparison is better for design work, where a moved logo matters as much as a changed word.' },
      { type: 'callout', title: 'Watch for the small changes', text: 'The dangerous edit is never a rewritten clause — you would notice. It is "30 days" becoming "60 days", "shall" becoming "may", or a decimal point moving. Read every reported difference, however trivial it looks.' },
      { type: 'h2', text: 'What comparison cannot tell you' },
      { type: 'list', items: [
        'Whether a change was authorised, or merely present.',
        'Which version is the one that was agreed.',
        'What changed in a scan, unless both files have been through OCR.',
        'Whether an apparent difference is just a reflow after a font substitution.',
      ] },
      { type: 'p', text: 'That last one causes a lot of noise. If a font was substituted, the text wraps differently and the comparison reports differences on every page. Convert both files consistently before comparing, or use a text-based comparison that ignores position.' },
      { type: 'h2', text: 'Comparing scans' },
      { type: 'p', text: 'Two scans of the same document are never pixel-identical — the paper sat differently, the exposure varied. Visual comparison reports differences everywhere. Run OCR on both and compare the text instead, accepting that recognition errors will produce some false positives of their own.' },
      { type: 'h2', text: 'Doing it properly on an important document' },
      { type: 'steps', items: [
        'Compare the text and read every difference.',
        'Check the page count and the section numbering.',
        'Check the schedules and annexes, which is where changes hide.',
        'Confirm the signature blocks and dates are unchanged.',
        'Ask the other side to summarise their changes, and check that against what you found.',
      ] },
    ],
    faqs: [
      { q: 'Can I compare a scanned PDF to a digital one?', a: 'Only after OCR on the scan, and expect some noise from recognition differences.' },
      { q: 'Why does everything show as different?', a: 'Usually a font substitution reflowing the text. Compare text rather than appearance.' },
      { q: 'Does comparison find formatting changes?', a: 'Visual comparison does. Text comparison only reports wording.' },
      { q: 'Can I rely on it for a contract?', a: 'As a first pass, yes. It finds what you would miss; you still have to judge what the differences mean.' },
    ],
    related: ['how-to-tell-if-a-pdf-has-been-edited', 'how-to-check-a-pdf-before-you-send-it', 'how-to-sign-a-contract-and-send-it-back'],
  },

  {
    slug: 'how-to-summarize-a-long-pdf',
    title: 'How to Summarise a Long PDF',
    description: 'Get through a 200-page report without reading all of it — what to extract, how to structure it, and what a summary will always miss.',
    keyword: 'how to summarize a long pdf',
    category: 'Troubleshooting',
    published: '2026-08-06',
    tool: 'ai-summarizer',
    blocks: [
      { type: 'p', text: 'Long documents arrive faster than anyone can read them. A summary is not a substitute for reading the parts that matter — it is a way of finding out which parts those are.' },
      { type: 'h2', text: 'Summarise a PDF' },
      { type: 'steps', items: [
        'Open the AI Summarizer and add your document.',
        'Let it extract the text and produce a summary.',
        'Read the summary to locate the sections that matter to you.',
        'Read those sections properly in the original.',
      ] },
      { type: 'h2', text: 'Summarise a section, not the whole thing' },
      { type: 'p', text: 'A summary of 200 pages is necessarily shallow — it has to compress everything equally, so nothing gets attention. Extract the chapter or section you care about and summarise that instead. Ten pages summarised into a paragraph is genuinely useful; two hundred pages summarised into a paragraph is a table of contents with extra words.' },
      { type: 'callout', title: 'Scans need OCR first', text: 'If the pages are images there is no text to summarise. Run OCR, then summarise the result.' },
      { type: 'h2', text: 'What summaries reliably miss' },
      { type: 'list', items: [
        'Qualifications and exceptions, which are exactly where the risk lives.',
        'Numbers in tables, which rarely survive summarisation intact.',
        'The significance of something absent — a summary cannot report what is not there.',
        'Tone and emphasis in a document where those carry meaning.',
        'Cross-references between distant sections.',
      ] },
      { type: 'p', text: 'For a contract, a regulatory filing or anything with legal consequence, treat a summary strictly as a navigation aid. The obligation is in the text.' },
      { type: 'h2', text: 'Using the document with an AI tool yourself' },
      { type: 'p', text: 'Converting to Markdown first produces a much better result than pasting raw extracted text: headings and lists survive, so the model can be asked about a named section rather than about an undifferentiated wall of prose.' },
      { type: 'h2', text: 'Privacy' },
      { type: 'p', text: 'Summarisation that runs on a server sends the document to it. For a published report that is irrelevant; for a client file or an unreleased set of accounts, it is a disclosure. Check where the processing happens before you summarise anything confidential — and note that this is a separate question from where the file was converted.' },
      { type: 'h2', text: 'A workflow for a long report' },
      { type: 'steps', items: [
        'Read the contents page and the executive summary — often the whole answer.',
        'Summarise to find where your topic is discussed.',
        'Extract those pages into their own file.',
        'Read them properly.',
        'Search the full document for key terms to catch anything the summary skipped.',
      ] },
    ],
    faqs: [
      { q: 'How accurate are AI summaries?', a: 'Good at capturing the main argument, unreliable on specifics — figures, dates and conditions. Verify anything you will act on.' },
      { q: 'Can I summarise a scanned document?', a: 'After OCR. Without it there is no text to work from.' },
      { q: 'Is my document uploaded when I summarise it?', a: 'It depends on the tool. Server-based summarisation transmits the text; check before using it on anything confidential.' },
      { q: 'What length should a summary be?', a: 'Long enough to be useful — a paragraph per major section beats one paragraph for a whole report.' },
    ],
    related: ['how-to-convert-pdf-to-markdown', 'extract-pages-from-pdf', 'is-it-safe-to-use-online-pdf-tools'],
  },

  {
    slug: 'how-to-translate-a-pdf',
    title: 'How to Translate a PDF',
    description: 'Translate a document while keeping it readable — the options, what happens to the layout, and the privacy question nobody asks.',
    keyword: 'how to translate a pdf',
    category: 'Troubleshooting',
    published: '2026-08-09',
    tool: 'translate-pdf',
    blocks: [
      { type: 'p', text: 'Translating a PDF is two problems: translating the words, and putting them back on a page where the text is now a different length.' },
      { type: 'h2', text: 'Translate a document' },
      { type: 'steps', items: [
        'Open the Translate PDF tool and add your file.',
        'Choose the source and target languages.',
        'Translate, and read the result before relying on it.',
      ] },
      { type: 'h2', text: 'The layout problem' },
      { type: 'p', text: 'German runs roughly 30% longer than English; Chinese is considerably shorter. Text that fitted its box no longer does, or leaves a gap. Because a PDF has fixed positions rather than flowing paragraphs, there is no reflow to absorb the difference — something has to overflow, shrink or be truncated.' },
      { type: 'p', text: 'That is why translated PDFs so often look slightly wrong. It is a property of the format, not a failure of the translation.' },
      { type: 'callout', title: 'Translation sends your text somewhere', text: 'Machine translation of any quality runs on a remote service. Whatever tool you use, the text of your document is transmitted to it. For a public report that is fine; for a contract or a medical record it is a disclosure decision, and one worth making deliberately.' },
      { type: 'h2', text: 'What machine translation is good and bad at' },
      { type: 'table', head: ['Content', 'Quality'], rows: [
        ['Everyday prose between major languages', 'Very good'],
        ['Technical documentation', 'Good, with terminology drift'],
        ['Legal text', 'Risky — terms of art rarely map cleanly'],
        ['Medical text', 'Risky, and consequential'],
        ['Marketing copy', 'Literal; the tone does not survive'],
        ['Tables of figures', 'The numbers survive; the headings may not'],
      ] },
      { type: 'h2', text: 'When it needs a human' },
      { type: 'p', text: 'Anything with legal effect, anything where a mistranslation carries safety consequences, and anything being published under your name. Machine translation is excellent for understanding a document you received; it is not a substitute for a professional translator on a document you are issuing.' },
      { type: 'h2', text: 'Getting a better result' },
      { type: 'list', items: [
        'OCR scans first — there is nothing to translate in an image.',
        'Translate section by section for a long document, so you can check as you go.',
        'Keep the original alongside the translation, and say which is authoritative.',
        'Have a native speaker review anything published.',
        'For a document you control, translate the source and re-export rather than translating the PDF.',
      ] },
      { type: 'p', text: 'That last point is the real answer whenever it is available. Translating the Word file and exporting again gives you a properly laid out document instead of a patched one.' },
    ],
    faqs: [
      { q: 'Does translation preserve the layout?', a: 'Approximately. Text length changes and PDF positions are fixed, so overflow and gaps are normal.' },
      { q: 'Is my document sent to a server?', a: 'Yes — machine translation runs remotely. Consider that before translating confidential material.' },
      { q: 'Can I translate a scanned PDF?', a: 'Run OCR first, then translate. Recognition errors will propagate into the translation.' },
      { q: 'Is machine translation good enough for contracts?', a: 'For understanding one, often. For issuing one, no — use a professional translator.' },
    ],
    related: ['how-to-make-a-scanned-pdf-searchable', 'is-it-safe-to-use-online-pdf-tools', 'how-to-summarize-a-long-pdf'],
  },

  {
    slug: 'what-is-a-pdf-file',
    title: 'What Is a PDF File, and Why Does It Behave Like That?',
    description: 'A plain explanation of what a PDF actually contains — which makes almost every frustrating thing about PDFs suddenly make sense.',
    keyword: 'what is a pdf file',
    category: 'Troubleshooting',
    published: '2026-08-17',
    tool: 'merge-pdf',
    blocks: [
      { type: 'p', text: 'PDF stands for Portable Document Format, published by Adobe in 1993 and an open ISO standard since 2008. Understanding one thing about how it works explains nearly every complaint people have about it.' },
      { type: 'h2', text: 'The one thing to know' },
      { type: 'p', text: 'A PDF describes where marks go on a page. Not paragraphs, not headings, not tables — glyphs at coordinates, lines between points, images in rectangles. It is a description of a printed page rather than a document in the sense a word processor means.' },
      { type: 'p', text: 'That design achieves the goal it was built for: the page looks the same everywhere, on any device, in any year. Everything people find frustrating follows from the same decision.' },
      { type: 'h2', text: 'Why PDFs behave the way they do' },
      { type: 'table', head: ['Complaint', 'Explanation'], rows: [
        ['Text is hard to edit', 'There are no paragraphs to re-flow, only glyphs at fixed positions'],
        ['It does not adapt to a phone screen', 'The page has a fixed size by design'],
        ['Copied text comes out jumbled', 'Text is extracted in drawing order, not reading order'],
        ['Tables lose their structure', 'There is no table object — a table is text that happens to line up'],
        ['Scanned PDFs are unsearchable', 'They contain pictures of text, not text'],
        ['File sizes vary wildly', 'A page can be a few instructions or a 25-megapixel photograph'],
      ] },
      { type: 'h2', text: 'What is inside the file' },
      { type: 'list', items: [
        'Objects: pages, fonts, images, and the drawing instructions for each page.',
        'A cross-reference table saying where every object is — damage this and the file will not open.',
        'A page tree defining the order pages appear in.',
        'Metadata: author, title, creation date, producing software.',
        'Optionally: annotations, form fields, bookmarks, attachments, encryption and digital signatures.',
      ] },
      { type: 'callout', title: 'The two kinds of PDF', text: 'A digital PDF, exported from software, contains real text you can select and search. A scanned PDF contains photographs of pages. They look identical and behave completely differently, and the difference explains most confusion about what a PDF can do.' },
      { type: 'h2', text: 'What PDFs are genuinely good at' },
      { type: 'p', text: 'Fixed appearance across every device and decade. Print fidelity. Embedded fonts. Digital signatures. Broad support — every operating system opens one without extra software. For a document that must be reproduced exactly, nothing else comes close.' },
      { type: 'h2', text: 'What they are bad at' },
      { type: 'p', text: 'Reading on a phone, being edited, holding structured data, and accessibility unless deliberately tagged. If your content will mostly be read on screens and needs to be updated, an HTML page is a better home for it — and you can still offer the PDF for people who want to print or file it.' },
    ],
    faqs: [
      { q: 'Why can I not edit PDF text easily?', a: 'Because the format stores positioned glyphs rather than flowing paragraphs. There is no text flow to re-wrap.' },
      { q: 'Are all PDFs the same?', a: 'No. Digital PDFs contain real text; scanned ones contain images. Everything you can do with a file depends on which it is.' },
      { q: 'Is PDF proprietary?', a: 'It has been an open ISO standard since 2008 and can be implemented by anyone.' },
      { q: 'Why are PDFs bad on phones?', a: 'The page size is fixed by design, so text cannot reflow to a narrow screen.' },
    ],
    related: ['pdf-vs-pdfa-what-is-the-difference', 'why-is-my-pdf-so-large', 'how-to-choose-between-sending-a-pdf-or-a-word-document'],
  },

  {
    slug: 'how-to-print-a-pdf-correctly',
    title: 'How to Print a PDF Correctly',
    description: 'Fix the print problems that waste paper — wrong scale, cut-off margins, missing form data, and pages that come out in the wrong order.',
    keyword: 'how to print a pdf correctly',
    category: 'Troubleshooting',
    published: '2026-07-27',
    tool: 'rotate-pdf',
    blocks: [
      { type: 'p', text: 'Most PDF printing problems come from four settings, and knowing which one to reach for saves the ritual of printing a test page, finding it wrong, and printing another.' },
      { type: 'h2', text: 'The four settings that matter' },
      { type: 'table', head: ['Setting', 'What it fixes'], rows: [
        ['Scale: Fit to printable area', 'Content cut off at the edges'],
        ['Scale: Actual size', 'Documents that must print at exact dimensions'],
        ['Orientation: Auto', 'Landscape pages in a portrait document'],
        ['Print as image', 'Pages that will not render or print corrupted'],
      ] },
      { type: 'p', text: 'Fit to printable area is the right default. Printers cannot print to the very edge of the paper, so a document designed to fill an A4 page loses a few millimetres all round unless it is scaled slightly.' },
      { type: 'h2', text: 'Common problems' },
      { type: 'h3', text: 'The edges are cut off' },
      { type: 'p', text: 'Set the scale to fit the printable area. If the document was designed with bleed for commercial printing, this is expected and a home printer cannot reproduce it.' },
      { type: 'h3', text: 'Everything is tiny in the middle of the page' },
      { type: 'p', text: 'The document page size does not match the paper — usually A4 content on US Letter or the reverse. Set the paper size correctly rather than letting it scale.' },
      { type: 'h3', text: 'Form answers do not print' },
      { type: 'p', text: 'Field appearances are not being generated. Flatten the document and the values become part of the page.' },
      { type: 'h3', text: 'Annotations do not print' },
      { type: 'p', text: 'Enable "Document and markups" in the print dialogue, or flatten the annotations first.' },
      { type: 'h3', text: 'Pages come out in the wrong order' },
      { type: 'p', text: 'Reverse order printing is on, or the printer stacks face-up. It is a printer setting rather than a document problem.' },
      { type: 'callout', title: 'Print one page first', text: 'On a long document, print page 1 and check it before sending eighty pages. It costs one sheet and saves the whole stack.' },
      { type: 'h2', text: 'Double-sided printing' },
      { type: 'p', text: 'Choose long-edge binding for portrait documents and short-edge for landscape — the wrong one prints every second page upside down. If your printer has no duplex mode, print the odd pages, reload, and print the even pages in reverse.' },
      { type: 'h2', text: 'Booklets and multiple pages per sheet' },
      { type: 'p', text: 'Multiple pages per sheet is the easy way to halve paper use on a document you only need to read. Booklet printing reorders pages so a folded stack reads correctly — useful, and worth testing on four pages before committing to sixty.' },
    ],
    faqs: [
      { q: 'Why does my PDF print smaller than it should?', a: 'The paper size does not match the document, or scaling is set to fit. Set the paper size correctly and choose actual size.' },
      { q: 'Why do my form entries not print?', a: 'Field appearances are not rendering. Flatten the document first.' },
      { q: 'What is "print as image"?', a: 'It rasterises each page before sending it. Slower and lower quality, but it works when normal printing fails.' },
      { q: 'How do I print double-sided without a duplex printer?', a: 'Print odd pages, reload the stack, then print even pages in reverse order.' },
    ],
    related: ['how-to-fix-a-pdf-that-wont-print', 'why-is-my-pdf-blurry', 'how-to-flatten-a-pdf'],
  },
];
