import type { BlogPost } from '../types';

export const troubleshootingPosts4: BlogPost[] = [
  {
    slug: 'how-to-fix-a-pdf-that-opens-blank',
    title: 'How to Fix a PDF That Opens Blank',
    description: 'The document opens, the page count is right, and every page is empty. Here are the causes and how to get the content back.',
    keyword: 'pdf opens blank',
    category: 'Troubleshooting',
    published: '2026-08-21',
    tool: 'repair-pdf',
    blocks: [
      { type: 'p', text: 'A blank PDF is different from one that will not open, and it is usually better news: the file structure is sound enough for the reader to count the pages, which means most of it is intact.' },
      { type: 'h2', text: 'Establish what you are looking at' },
      { type: 'steps', items: [
        'Check the page count. Correct page count with blank pages points at rendering rather than corruption.',
        'Check the file size. A large file with blank pages contains content that is not being drawn.',
        'Open it in a browser. Chrome and Firefox render many documents that desktop readers refuse.',
        'Try to select text on a blank page — if text highlights, the content is there and invisible.',
      ] },
      { type: 'h2', text: 'The likely causes' },
      { type: 'h3', text: 'A reader that cannot render it' },
      { type: 'p', text: 'The most common by far. An older reader faced with newer transparency, layer or font constructs draws nothing rather than approximating. Updating the reader, or opening the file in a browser, fixes it.' },
      { type: 'h3', text: 'Hidden layers' },
      { type: 'p', text: 'A document with optional content groups can have layers turned off. The content is present and not displayed. Look for a layers panel in your reader and enable everything.' },
      { type: 'h3', text: 'Form fields that have not rendered' },
      { type: 'p', text: 'If the document is a form and the page looks empty apart from lines, the field appearances have not been generated. Flattening the document draws the values permanently into the page.' },
      { type: 'h3', text: 'White text or a covering shape' },
      { type: 'p', text: 'Rare and worth checking: select all on a blank page and see whether anything highlights. Text set to white on white is invisible and entirely present.' },
      { type: 'h3', text: 'The pages really are blank' },
      { type: 'p', text: 'An export that failed, a scanner that fed nothing, or a document generated with no content. The file size tells you — a genuinely empty ten-page PDF is a few kilobytes.' },
      { type: 'callout', title: 'File size is the fastest diagnostic', text: 'A 12 MB PDF showing blank pages certainly contains something. A 4 KB one probably does not. Check that before troubleshooting anything else.' },
      { type: 'h2', text: 'What to try' },
      { type: 'list', items: [
        'Open it in a browser.',
        'Update your reader.',
        'Turn on all layers, if there is a layers panel.',
        'Flatten the document, if it is a form.',
        'Run a repair to rebuild the structure.',
        'Ask the sender to re-export and flatten before sending.',
      ] },
      { type: 'h2', text: 'If you are producing documents that do this' },
      { type: 'p', text: 'Flatten forms before distributing them, avoid relying on optional content layers, and check the output in a second reader. Blank pages at the recipient\'s end are almost always something that could have been caught by opening the file once in a different viewer.' },
    ],
    faqs: [
      { q: 'Why is my PDF blank in Acrobat but fine in Chrome?', a: 'The browser renderer supports something your desktop reader does not, or the reader needs updating. The file is fine.' },
      { q: 'My form is blank when the recipient opens it. Why?', a: 'Field appearances did not render. Flatten the document before sending.' },
      { q: 'Can a repair fix blank pages?', a: 'Sometimes, when the structure is damaged. It cannot add content that is not in the file.' },
      { q: 'How do I know whether the pages are really empty?', a: 'Check the file size and try to select text. A large file with nothing selectable is content that is not being drawn.' },
    ],
    related: ['how-to-repair-a-corrupted-pdf', 'pdf-wont-open-how-to-fix-it', 'how-to-flatten-a-pdf'],
  },

  {
    slug: 'how-to-check-a-pdf-before-you-send-it',
    title: 'How to Check a PDF Before You Send It',
    description: 'A two-minute checklist that catches the things that embarrass people — hidden data, failed redactions, missing fonts and wrong page order.',
    keyword: 'check pdf before sending',
    category: 'Troubleshooting',
    published: '2026-08-18',
    tool: 'optimize-pdf',
    blocks: [
      { type: 'p', text: 'Almost every PDF incident — the leaked name, the blank form, the wrong version — would have been caught by two minutes of checking. Here is what to look at.' },
      { type: 'h2', text: 'Content' },
      { type: 'steps', items: [
        'Check the page count matches what you intend to send.',
        'Page through the whole document rather than the first page.',
        'Confirm the pages are in the right order.',
        'Check nothing internal survived — draft watermarks, working columns, reviewer comments.',
        'Confirm this is the final version, not the draft with a similar filename.',
      ] },
      { type: 'h2', text: 'Anything you removed' },
      { type: 'steps', items: [
        'Copy text from every redacted area — nothing should come back.',
        'Search the document for the name or number you redacted.',
        'Check headers and footers, which repeat on every page and are routinely missed.',
        'Check the bookmarks, which can restate a removed section.',
      ] },
      { type: 'h2', text: 'Hidden data' },
      { type: 'list', items: [
        'Open document properties and read the Author, Title and Subject fields.',
        'Check for annotations and comments.',
        'Check for embedded attachments.',
        'Check the filename itself does not disclose something.',
      ] },
      { type: 'callout', title: 'The Title field is the one that catches people', text: 'It usually holds the original filename. "offer-v3-final-lowball.docx" sitting in the properties of a document you carefully redacted is a bad way to end a negotiation.' },
      { type: 'h2', text: 'Rendering' },
      { type: 'steps', items: [
        'Check the Fonts tab — everything should be embedded.',
        'Open the file in a second reader, ideally a browser.',
        'Check it on a phone if the recipient may read it there.',
        'Print one page if it will be printed.',
      ] },
      { type: 'h2', text: 'Delivery' },
      { type: 'list', items: [
        'Check the file size against the recipient\'s likely limit.',
        'Give the file a name that identifies it: subject, party and date.',
        'Check the recipient address character by character.',
        'Say in the message what is attached and what you expect back.',
      ] },
      { type: 'h2', text: 'When it matters most' },
      { type: 'p', text: 'Run the full list on anything going outside your organisation, anything with legal effect, anything you have redacted, and anything being published. For an internal draft to a colleague, the content checks are enough.' },
      { type: 'h2', text: 'Build the checks into how you work' },
      { type: 'p', text: 'A checklist you have to remember is a checklist you will skip on the day you are busy. The checks that survive are the ones attached to a step you already take: renaming the file, attaching it, writing the covering message.' },
      { type: 'p', text: 'Two habits carry most of the value. Always open the finished file from your downloads folder before attaching it — that one action catches wrong versions, blank forms and failed exports. And always write the covering message before attaching, so you are forced to describe what you are sending and notice when the description does not match the file.' },
      { type: 'p', text: 'For teams, agree a short standard: naming convention, metadata cleared, second reader check on anything external. Written down once, it stops being something each person decides individually under time pressure.' },
    ],
    faqs: [
      { q: 'What gets missed most often?', a: 'Document metadata, and text under black boxes that were never real redactions.' },
      { q: 'How do I check whether a redaction worked?', a: 'Copy from the redacted area and search the document for the removed term. Both should return nothing.' },
      { q: 'Why check in a second reader?', a: 'Because rendering differs between them. What looks right in yours may not in the recipient\'s.' },
      { q: 'Is this necessary every time?', a: 'For external, legal or published documents, yes. For internal drafts, the content checks suffice.' },
    ],
    related: ['what-personal-data-is-hidden-in-your-pdf', 'how-to-redact-a-pdf-properly', 'why-does-my-pdf-look-different-on-another-device'],
  },

  {
    slug: 'how-to-make-a-pdf-accessible',
    title: 'How to Make a PDF Accessible',
    description: 'What makes a PDF usable with a screen reader, why most PDFs are not, and the practical steps that make the biggest difference.',
    keyword: 'how to make a pdf accessible',
    category: 'Troubleshooting',
    published: '2026-08-12',
    tool: 'ocr-pdf',
    blocks: [
      { type: 'p', text: 'A PDF describes where marks go on a page. A screen reader needs to know what those marks mean — this is a heading, this is a table cell, this image shows a chart. Bridging that gap is what accessibility work on a PDF consists of.' },
      { type: 'h2', text: 'What an accessible PDF has' },
      { type: 'list', items: [
        'Real text rather than images of text.',
        'Tags marking headings, paragraphs, lists and tables as what they are.',
        'A defined reading order, so content is announced in the right sequence.',
        'Alternative text on every meaningful image.',
        'Table headers identified so cells can be related to them.',
        'A document language set, so the correct pronunciation is used.',
        'A document title, which is what a screen reader announces first.',
        'Sufficient colour contrast, and meaning not carried by colour alone.',
      ] },
      { type: 'h2', text: 'The single biggest problem' },
      { type: 'p', text: 'Scanned documents. A screen reader encountering a scan finds no text at all and announces nothing. The user has an empty document. Running OCR is the single highest-impact accessibility improvement available for most archives, and it takes one pass.' },
      { type: 'callout', title: 'OCR is the floor, not the ceiling', text: 'OCR makes text available. It does not create heading structure or reading order. It moves a document from unusable to readable, which is a large step and not the whole journey.' },
      { type: 'h2', text: 'Fix it at the source' },
      { type: 'p', text: 'Tagging is far easier to get right in the authoring tool than to add afterwards. In Word, use the built-in heading styles rather than manually formatting large bold text, use real lists and real tables, add alt text to images, and export with "document structure tags for accessibility" enabled. The tags carry through into the PDF automatically.' },
      { type: 'p', text: 'Retro-fitting tags to an untagged PDF is genuinely laborious work, which is why doing it in the source is worth insisting on.' },
      { type: 'h2', text: 'A practical order of work' },
      { type: 'steps', items: [
        'OCR anything scanned.',
        'Set the document title and language in the properties.',
        'Re-export from the source with tagging enabled, where you have the source.',
        'Add alternative text to images.',
        'Check the reading order, particularly on multi-column pages.',
        'Test with an actual screen reader rather than only a checker.',
      ] },
      { type: 'h2', text: 'Consider whether it should be a PDF' },
      { type: 'p', text: 'For content that will be read on screen, an HTML page is more accessible by default: it reflows, it carries semantic structure natively, and assistive technology handles it far better. Publish the page and offer the PDF for people who want to print or file it. That single decision solves more accessibility problems than any amount of remediation.' },
    ],
    faqs: [
      { q: 'Are scanned PDFs accessible?', a: 'No. Without OCR a screen reader finds nothing at all.' },
      { q: 'Does OCR make a PDF accessible?', a: 'It makes the text available, which is the biggest step. Structure, reading order and alt text still need attention.' },
      { q: 'What is PDF/UA?', a: 'The accessibility standard for PDF, specifying tagging and structure requirements in detail.' },
      { q: 'Is HTML better than PDF for accessibility?', a: 'Generally yes — it reflows and carries semantics natively. Publish HTML and offer the PDF alongside.' },
    ],
    related: ['how-to-make-a-scanned-pdf-searchable', 'how-to-convert-pdf-to-pdfa-for-archiving', 'how-to-choose-between-sending-a-pdf-or-a-word-document'],
  },

  {
    slug: 'how-to-choose-between-sending-a-pdf-or-a-word-document',
    title: 'Should You Send a PDF or a Word Document?',
    description: 'The choice affects how your document is read, edited and trusted. A straightforward guide to picking the right one.',
    keyword: 'pdf or word document',
    category: 'Troubleshooting',
    published: '2026-08-07',
    tool: 'word-to-pdf',
    blocks: [
      { type: 'p', text: 'The decision is really about one question: do you want the recipient to change this document?' },
      { type: 'h2', text: 'Send a PDF when' },
      { type: 'list', items: [
        'The document is final and should not be altered.',
        'The layout matters and must look the same for everyone.',
        'You do not know what software the recipient has.',
        'It will be printed.',
        'It carries a signature.',
        'It is going into an archive or a filing system.',
      ] },
      { type: 'h2', text: 'Send a Word document when' },
      { type: 'list', items: [
        'You want comments, tracked changes or edits back.',
        'It is a template someone will fill in.',
        'It is a draft being worked on collaboratively.',
        'The recipient has asked for an editable copy.',
        'The content will be reused in another document.',
      ] },
      { type: 'h2', text: 'The differences that matter' },
      { type: 'table', head: ['', 'PDF', 'Word'], rows: [
        ['Looks the same everywhere', 'Yes', 'No — depends on fonts and version'],
        ['Easy to edit', 'No', 'Yes'],
        ['Opens without special software', 'Yes', 'Usually, with caveats'],
        ['Good on a phone', 'No — fixed page size', 'Better, it reflows'],
        ['Carries tracked changes', 'No', 'Yes'],
        ['Can be signed', 'Yes', 'Not meaningfully'],
        ['Reveals editing history', 'Only metadata', 'Sometimes considerably more'],
      ] },
      { type: 'callout', title: 'Word files carry more than you think', text: 'Tracked changes, deleted text, comments and author names can all travel with a .docx. Sending an editable file to a counterparty has disclosed negotiating positions more than once. Convert to PDF and the history goes with the conversion.' },
      { type: 'h2', text: 'The common mistake' },
      { type: 'p', text: 'Sending a Word file because it is what you were working in, when the recipient has no reason to edit it. The result is a document that looks different on their screen, can be changed without your knowledge, and may carry your revision history. Converting takes seconds.' },
      { type: 'h2', text: 'When to send both' },
      { type: 'p', text: 'Contracts under negotiation are the classic case: the PDF is the version of record, the Word file is what the other side marks up. Say clearly which is which, and make sure the two match before you send them.' },
      { type: 'h2', text: 'What to do when you are asked for the wrong one' },
      { type: 'p', text: 'Requests for an editable copy are worth a moment\'s thought rather than an automatic yes. Ask what they intend to change. If the answer is "we need to mark up the clauses", send the Word file — that is what it is for. If the answer is "so we can fill in our details", a PDF form is a better instrument, because it constrains what can be altered.' },
      { type: 'p', text: 'If you do send an editable copy, clean it first: accept or reject every tracked change, delete the comments, and check the author fields in the document properties. A .docx carries more of its own history than most people realise, and the recipient sees all of it.' },
      { type: 'h2', text: 'Other formats worth considering' },
      { type: 'list', items: [
        'HTML, for content that will be read on screen and updated over time.',
        'CSV, when what you are really sending is data rather than a document.',
        'Markdown, for text destined for a wiki, a repository or an AI tool.',
      ] },
    ],
    faqs: [
      { q: 'Is a PDF more professional?', a: 'For a finished document, generally — it arrives as intended and cannot be casually altered.' },
      { q: 'Can the recipient edit a PDF?', a: 'With effort. It is not a security control, but it is enough friction to prevent casual changes.' },
      { q: 'Why not always send PDF?', a: 'Because sometimes you want edits back. A PDF makes collaboration harder, which is the point of it.' },
      { q: 'Do Word files really carry hidden history?', a: 'They can — tracked changes, comments, author names and deleted text. Check before sending one externally.' },
    ],
    related: ['how-to-convert-word-to-pdf-without-losing-formatting', 'what-is-a-pdf-file', 'how-to-check-a-pdf-before-you-send-it'],
  },

  {
    slug: 'how-to-organize-a-large-pdf-library',
    title: 'How to Organise a Large PDF Library',
    description: 'Naming, foldering and OCR conventions that make a few thousand documents findable — and the habits that keep them that way.',
    keyword: 'organize pdf files',
    category: 'Troubleshooting',
    published: '2026-08-05',
    tool: 'ocr-pdf',
    blocks: [
      { type: 'p', text: 'A folder holding four thousand PDFs named "scan_0043.pdf" and "document (2).pdf" is not an archive. It is a place documents go to become unfindable.' },
      { type: 'h2', text: 'Naming is most of the work' },
      { type: 'p', text: 'A good filename answers three questions: when, what, and who. Put the date first in ISO format so files sort chronologically on their own.' },
      { type: 'table', head: ['Pattern', 'Example'], rows: [
        ['YYYY-MM-DD-subject-party', '2026-03-14-invoice-northwind.pdf'],
        ['YYYY-MM-subject', '2026-03-bank-statement.pdf'],
        ['party-type-YYYY-MM-DD', 'acme-agreement-2026-03-14.pdf'],
      ] },
      { type: 'p', text: 'Pick one and use it everywhere. An inconsistent convention is only marginally better than none, because you cannot predict what to search for.' },
      { type: 'callout', title: 'Dates first, in ISO format', text: '2026-03-14 sorts correctly as text; 14/03/2026 does not. This one habit makes every folder chronological without any tooling.' },
      { type: 'h2', text: 'OCR everything' },
      { type: 'p', text: 'This is the difference between a library you can search and one you can only browse. A scanned document without a text layer cannot be found by content — not by your operating system\'s search, not by your document manager, not by anything. Running OCR over an archive once, as a batch, transforms it permanently.' },
      { type: 'h2', text: 'Folders: shallow and obvious' },
      { type: 'list', items: [
        'Two or three levels at most — deep hierarchies get abandoned.',
        'Organise by the thing you look for first: client, year, or document type.',
        'Keep an inbox folder for unfiled documents, and empty it weekly.',
        'Do not create a folder for a single file.',
        'Be consistent about singular and plural, and about capitalisation.',
      ] },
      { type: 'h2', text: 'Habits that keep it working' },
      { type: 'steps', items: [
        'Rename a file when it arrives, not later. Later never comes.',
        'OCR scans as part of filing them, not as a project you will do one day.',
        'Merge related documents into one file — an invoice and its receipt belong together.',
        'Compress large scans at filing time.',
        'Review the inbox folder weekly.',
      ] },
      { type: 'h2', text: 'Backups' },
      { type: 'p', text: 'An organised archive that exists in one place is one failure away from nothing. Three copies, two kinds of storage, one of them off-site is the conventional rule and it is conventional because it works. Test a restore occasionally — a backup nobody has ever restored from is a hypothesis.' },
    ],
    faqs: [
      { q: 'What is the best filename format?', a: 'Date first in ISO format, then subject, then party. It sorts correctly and describes the file.' },
      { q: 'Should I use folders or tags?', a: 'Folders are universal and survive moving between systems. Tags are more flexible and tend not to travel.' },
      { q: 'Do I really need to OCR everything?', a: 'If you want to find documents by content, yes. It is the difference between searching and browsing.' },
      { q: 'How do I fix a library that is already a mess?', a: 'Work backwards from the most recent, batch OCR everything, and rename as you go. Set the convention first so you only do it once.' },
    ],
    related: ['how-to-make-a-scanned-pdf-searchable', 'how-to-batch-process-pdf-files', 'how-to-compress-a-scanned-pdf'],
  },
];
