import type { BlogPost } from '../types';

export const troubleshootingPosts: BlogPost[] = [
  {
    slug: 'how-to-repair-a-corrupted-pdf',
    title: 'How to Repair a Corrupted PDF',
    description: 'What "the file is damaged" actually means, which kinds of damage are recoverable, and the steps that get a broken PDF open again.',
    keyword: 'how to repair a corrupted pdf',
    category: 'Troubleshooting',
    published: '2026-03-01',
    tool: 'repair-pdf',
    blocks: [
      { type: 'p', text: 'A PDF that will not open is usually not as broken as the error message suggests. Most damage is to the index rather than the content, and an index can be rebuilt.' },
      { type: 'h2', text: 'Try repairing it' },
      { type: 'steps', items: [
        'Open the Repair PDF tool and add the file.',
        'Run the repair. The document structure is rebuilt from whatever objects can be located.',
        'Open the result and check the page count against what you expect.',
        'Page through it — partial recovery is common and worth knowing about before you rely on it.',
      ] },
      { type: 'h2', text: 'What is actually broken' },
      { type: 'table', head: ['Problem', 'Recoverable?'], rows: [
        ['Damaged cross-reference table', 'Usually yes — this is the common case'],
        ['Missing or malformed trailer', 'Often, by scanning the file for objects'],
        ['Corrupted individual objects', 'Partially — those pages may be lost'],
        ['Truncated download', 'Whatever arrived; the rest is simply not there'],
        ['Wrong file type renamed .pdf', 'No — it was never a PDF'],
        ['Encrypted with an unknown password', 'Not damage; you need the password'],
      ] },
      { type: 'p', text: 'The cross-reference table is a map of where every object lives in the file. Damage it and a reader cannot find anything, even though the content is entirely intact — which is why rebuilding the map so often restores the whole document.' },
      { type: 'callout', title: 'A truncated file is not repairable', text: 'If the download stopped halfway, the missing bytes do not exist anywhere. Repair can recover the pages that arrived. The rest requires downloading it again.' },
      { type: 'h2', text: 'Before assuming corruption' },
      { type: 'steps', items: [
        'Try a different reader — Chrome, Firefox and Preview are all more tolerant than some desktop applications.',
        'Check the file size. A few hundred bytes means the download failed rather than the file being damaged.',
        'Download it again, if it came from the web or an email.',
        'Check it is really a PDF — open it in a text editor and look for %PDF in the first line.',
        'Try it on another device, to rule out one broken installation.',
      ] },
      { type: 'p', text: 'A surprising number of "corrupted" PDFs are simply files a particular reader dislikes.' },
      { type: 'h2', text: 'How PDFs get damaged' },
      { type: 'list', items: [
        'Interrupted downloads and transfers.',
        'A USB drive removed while writing.',
        'Failing storage media.',
        'Software crashing mid-save.',
        'Cloud sync conflicts producing a half-written file.',
        'Email systems mangling an attachment in transit.',
      ] },
      { type: 'h2', text: 'If repair does not work' },
      { type: 'p', text: 'Check for other copies before doing anything drastic: your email sent folder, the cloud drive\'s version history, a backup, the person who sent it. Cloud storage keeps previous versions for weeks and this is exactly what that feature is for. An earlier copy that opens is worth more than any amount of forensic recovery.' },
    ],
    faqs: [
      { q: 'Can every corrupted PDF be repaired?', a: 'No. Index damage usually can be. Missing data cannot be recreated.' },
      { q: 'Why does my PDF open in Chrome but not Acrobat?', a: 'Browsers are more forgiving of malformed structure. It confirms the content is intact, which is good news.' },
      { q: 'Will repair recover everything?', a: 'Often, but partial recovery happens. Check the page count and read through before relying on it.' },
      { q: 'Can I recover a PDF that never finished downloading?', a: 'Only the part that arrived. Download it again.' },
    ],
    related: ['pdf-wont-open-how-to-fix-it', 'how-to-fix-a-pdf-that-opens-blank', 'why-does-my-pdf-look-different-on-another-device'],
  },

  {
    slug: 'pdf-wont-open-how-to-fix-it',
    title: 'PDF Will Not Open? Here Is How to Fix It',
    description: 'Work through the causes in order — reader problems, download failures, encryption and genuine corruption — and get the document open.',
    keyword: 'pdf wont open',
    category: 'Troubleshooting',
    published: '2026-03-28',
    tool: 'repair-pdf',
    blocks: [
      { type: 'p', text: 'A PDF that will not open has half a dozen possible causes, and they are quick to eliminate in the right order. Start with the cheapest checks.' },
      { type: 'h2', text: 'Work through these in order' },
      { type: 'steps', items: [
        'Open it in a browser. Drag the file into a Chrome or Firefox tab. If it opens, the file is fine and your reader is the problem.',
        'Check the file size. A few hundred bytes means the download failed.',
        'Download it again from the source.',
        'Try it on a different device, to rule out a broken installation.',
        'Check whether a password is being requested — that is not a fault.',
        'Run a repair if it still will not open anywhere.',
      ] },
      { type: 'h2', text: 'What the error messages mean' },
      { type: 'table', head: ['Message', 'Usually means'], rows: [
        ['"The file is damaged and could not be repaired"', 'Structural damage — try a repair tool, which is more persistent than a reader'],
        ['"This file cannot be opened because it is not a supported format"', 'It is not a PDF, whatever the extension says'],
        ['"Password required"', 'Encrypted. You need the password; nothing is broken'],
        ['"Insufficient data for an image"', 'Truncated download'],
        ['A blank window with no error', 'It opened; the pages may be empty or the content failed to render'],
      ] },
      { type: 'callout', title: 'Check it is really a PDF', text: 'Open the file in a text editor. A real PDF starts with %PDF-1.x. If you see HTML, you downloaded an error page. If you see something else entirely, the extension is wrong.' },
      { type: 'h2', text: 'The HTML error page trap' },
      { type: 'p', text: 'This is more common than it sounds. A download link expires or requires a login, the server returns an error page, and the browser saves it with the .pdf name you asked for. The file is a few kilobytes and contains a web page. No PDF tool will ever open it — you need a working link.' },
      { type: 'h2', text: 'Reader problems' },
      { type: 'p', text: 'If the file opens in a browser but not your usual reader, the reader is at fault. Update it, restart it, and clear its cache if it has one. Corporate installations with security plugins are a frequent source of this — a file that opens everywhere else and not on your work laptop is usually policy rather than corruption.' },
      { type: 'h2', text: 'Before you give up' },
      { type: 'list', items: [
        'Check your email sent folder for the copy you sent someone.',
        'Check cloud storage version history — it keeps previous versions for weeks.',
        'Ask the sender to resend it.',
        'Check your backups.',
      ] },
    ],
    faqs: [
      { q: 'Why does my PDF open on my phone but not my computer?', a: 'Different renderers have different tolerances. It confirms the file is fine and points at your desktop reader.' },
      { q: 'My PDF is 2KB. What happened?', a: 'The download failed, or you saved an error page. Download it again.' },
      { q: 'Can a PDF contain a virus?', a: 'PDFs can carry scripts and have been used as an attack vector. Keep your reader updated and be cautious with unexpected attachments.' },
      { q: 'What is the most reliable PDF reader?', a: 'For simply opening files, browser viewers are unusually robust. They are the right first test.' },
    ],
    related: ['how-to-repair-a-corrupted-pdf', 'how-to-fix-a-pdf-that-opens-blank', 'how-to-remove-a-password-from-a-pdf'],
  },

  {
    slug: 'why-is-my-pdf-blurry',
    title: 'Why Is My PDF Blurry? (And How to Fix It)',
    description: 'Blurry PDFs come from four causes, and only some are fixable. How to tell which you have and what to do about each.',
    keyword: 'why is my pdf blurry',
    category: 'Troubleshooting',
    published: '2026-04-16',
    tool: 'pdf-to-jpg',
    blocks: [
      { type: 'p', text: 'The first thing to establish is whether the blur is in the file or in how you are looking at it. That takes one test.' },
      { type: 'h2', text: 'The diagnostic' },
      { type: 'p', text: 'Try to select a line of text with your cursor.' },
      { type: 'table', head: ['Result', 'Meaning'], rows: [
        ['Text highlights, still looks soft', 'A rendering issue — the text is vector and should be sharp'],
        ['A rectangle is drawn instead', 'It is an image; the blur is baked in'],
      ] },
      { type: 'p', text: 'Real text in a PDF is stored as outlines and renders sharply at any zoom. If it does not, the problem is your viewer, not the file.' },
      { type: 'h2', text: 'The four causes' },
      { type: 'h3', text: 'A low-resolution scan' },
      { type: 'p', text: 'Scanned below 200 DPI, the characters were captured blurry. Nothing recovers detail that was never captured — the only fix is rescanning at 300 DPI.' },
      { type: 'h3', text: 'Over-compression' },
      { type: 'p', text: 'Aggressive compression downsamples images and re-encodes them heavily. If you still have the original, compress it again at a lighter setting. If not, the damage is permanent.' },
      { type: 'h3', text: 'Rasterised text' },
      { type: 'p', text: 'Some tools convert pages to images during merging, converting or "flattening". Text that was crisp becomes pixels. Redo the operation with a tool that preserves text.' },
      { type: 'h3', text: 'Viewer rendering' },
      { type: 'p', text: 'Some readers render at a fixed resolution and scale the result, which looks soft at certain zoom levels. Zoom to exactly 100%, or open the file in a different reader — if it is sharp there, the file was always fine.' },
      { type: 'callout', title: 'Enlarging never adds detail', text: 'Rendering a 72 DPI scan at 600 DPI produces a bigger file containing the same blur. Resolution is limited by what was captured, not by what you ask for on the way out.' },
      { type: 'h2', text: 'Blurry when printed' },
      { type: 'list', items: [
        'The source images are below 300 DPI — the usual cause.',
        'The print dialogue is scaling the page, softening everything.',
        'Draft or economy print mode is on.',
        '"Print as image" is enabled in the advanced settings, which rasterises everything.',
      ] },
      { type: 'h2', text: 'Preventing it' },
      { type: 'p', text: 'Scan at 300 DPI. Compress once, at the end. Use tools that keep text as text. Keep the original of anything you compress — that single habit turns most of these problems from permanent into inconvenient.' },
    ],
    faqs: [
      { q: 'Can I sharpen a blurry PDF?', a: 'Not meaningfully. Sharpening filters increase contrast at edges; they do not restore detail that was never there.' },
      { q: 'Why does it look fine on screen but print blurry?', a: 'Screens need far less resolution than print. Images that look fine at 150 DPI on a monitor are soft on paper.' },
      { q: 'Why did my PDF get blurry after compressing?', a: 'Compression downsamples and re-encodes images. Compress the original again at a lighter setting.' },
      { q: 'Is a blurry scan fixable?', a: 'Only by rescanning at a higher resolution.' },
    ],
    related: ['how-to-compress-a-pdf-without-losing-quality', 'how-to-convert-pdf-to-jpg-high-quality', 'how-to-print-a-pdf-correctly'],
  },

  {
    slug: 'how-to-fix-fonts-not-displaying-in-a-pdf',
    title: 'How to Fix Fonts Not Displaying Correctly in a PDF',
    description: 'Boxes instead of letters, substituted typefaces and shifted layouts all come from one cause: fonts that were not embedded.',
    keyword: 'pdf font problems',
    category: 'Troubleshooting',
    published: '2026-05-14',
    tool: 'pdf-to-pdfa',
    blocks: [
      { type: 'p', text: 'A PDF can either carry its fonts inside it or simply name them and hope the reader has them. Almost every font problem you will ever see comes from the second case.' },
      { type: 'h2', text: 'What you see when a font is missing' },
      { type: 'list', items: [
        'Empty rectangles, or "tofu", where characters should be.',
        'A different typeface, usually a generic serif.',
        'Text spilling out of its box, or overlapping the text below.',
        'Correct letters but wrong spacing, because the substitute has different widths.',
        'Missing accented characters or symbols while plain text renders normally.',
      ] },
      { type: 'h2', text: 'Check whether the fonts are embedded' },
      { type: 'steps', items: [
        'Open document properties in your reader.',
        'Find the Fonts tab.',
        'Look at each font. "Embedded" or "Embedded Subset" is what you want.',
        'Any font listed without that marker depends on the reader having it installed.',
      ] },
      { type: 'callout', title: 'Fix it at the source', text: 'A PDF missing its fonts cannot have them added back with the original letterforms — the outlines are not in the file. Re-export from the source document with font embedding enabled.' },
      { type: 'h2', text: 'Fixing it' },
      { type: 'h3', text: 'If you have the source document' },
      { type: 'p', text: 'Turn on font embedding and export again. In Word it is under Options → Save → Embed fonts in the file. Most design tools embed by default. This is the correct fix and the only one that reproduces the original exactly.' },
      { type: 'h3', text: 'If you only have the PDF' },
      { type: 'p', text: 'Converting to PDF/A forces embedding of whatever the renderer can resolve, which stabilises the document — though if the original font is genuinely unavailable, a substitute gets embedded rather than the real thing. It stops the document changing from machine to machine, which is usually what you actually need.' },
      { type: 'h3', text: 'If it is only on your machine' },
      { type: 'p', text: 'Install the font, or update your reader. If the document displays correctly for everyone else, the file is fine.' },
      { type: 'h2', text: 'Why it matters more than it looks' },
      { type: 'p', text: 'Font substitution changes letter widths, which changes line wrapping, which changes page breaks. A contract that was ten pages when signed can be eleven pages on someone else\'s screen, with clauses on different pages. For anything where the pagination is referenced, embedding is not cosmetic.' },
      { type: 'h2', text: 'Preventing it' },
      { type: 'list', items: [
        'Always embed fonts when exporting.',
        'Prefer common families for documents that will be handled by many tools.',
        'Check the Fonts tab before distributing anything important.',
        'Use PDF/A for archival copies, where embedding is mandatory.',
      ] },
    ],
    faqs: [
      { q: 'Why do I see boxes instead of letters?', a: 'The font is not embedded and your reader has no substitute containing those characters — common with non-Latin scripts.' },
      { q: 'Can I add fonts to an existing PDF?', a: 'Not the original outlines. Re-export from the source, or convert to PDF/A to embed a substitute and stop the document shifting.' },
      { q: 'Does everyone see the same substitution?', a: 'No. Each reader substitutes from what it has, which is why the document looks different everywhere.' },
      { q: 'Does embedding increase file size?', a: 'Yes, though subsetting keeps only the characters used, which limits the cost considerably.' },
    ],
    related: ['how-to-convert-word-to-pdf-without-losing-formatting', 'why-does-my-pdf-look-different-on-another-device', 'how-to-convert-pdf-to-pdfa-for-archiving'],
  },

  {
    slug: 'how-to-make-a-scanned-pdf-searchable',
    title: 'How to Make a Scanned PDF Searchable',
    description: 'Turn a stack of page images into a document you can search, copy from and index — what OCR does, and how to get good results.',
    keyword: 'make scanned pdf searchable',
    category: 'Troubleshooting',
    published: '2026-04-01',
    updated: '2026-08-10',
    tool: 'ocr-pdf',
    blocks: [
      { type: 'p', text: 'An unsearchable archive is a filing cabinet. Everything is in there and finding anything requires knowing where you put it. OCR is what turns a scanned collection into something you can actually query.' },
      { type: 'h2', text: 'Make a scan searchable' },
      { type: 'steps', items: [
        'Open the OCR tool and add your scanned PDF.',
        'Run it. Each page image is analysed and recognised text is written invisibly over it.',
        'Download the result and search for a word you know is in the document.',
        'Spot-check the recognition on a page with numbers or names.',
      ] },
      { type: 'h2', text: 'What the text layer is' },
      { type: 'p', text: 'The scanned image stays exactly as it was. The recognised characters are placed on top, invisibly, each positioned over the word it was read from. The page looks identical; selecting text highlights in the right place; searching finds words; a screen reader can read it.' },
      { type: 'p', text: 'This is why OCR does not degrade a scan. It adds rather than replaces.' },
      { type: 'callout', title: 'Do it before compressing', text: 'Recognition accuracy depends on image quality. OCR the clean scan, then compress — image compression does not touch a text layer.' },
      { type: 'h2', text: 'Getting good accuracy' },
      { type: 'table', head: ['Factor', 'Target'], rows: [
        ['Resolution', '300 DPI — below 200 accuracy falls sharply'],
        ['Skew', 'Straight; even a few degrees hurts line segmentation'],
        ['Contrast', 'Clean black on white; faint originals lose thin strokes'],
        ['Colour mode', 'Greyscale is fine and smaller than colour'],
        ['Text type', 'Printed. Handwriting is generally not recognised'],
      ] },
      { type: 'h2', text: 'What it will get wrong' },
      { type: 'p', text: 'Confusions between similar shapes — 0 and O, 1 and l, 5 and S, rn and m. In prose these are visible and harmless; in a column of figures or a reference number they are invisible and consequential. Check anything numeric against the image.' },
      { type: 'h2', text: 'Why it is worth doing on everything you archive' },
      { type: 'list', items: [
        'You can find documents by content instead of by filename.',
        'Text can be copied instead of retyped.',
        'Screen readers can read the document, which is often a legal requirement.',
        'The document can be converted to Word or Markdown.',
        'Search indexes can crawl it — including your own desktop search.',
      ] },
      { type: 'p', text: 'A scan without OCR is a document you have kept but cannot use.' },
    ],
    faqs: [
      { q: 'Does OCR change how my scan looks?', a: 'No. The image is untouched; the text layer is invisible.' },
      { q: 'How accurate is it?', a: 'Very high on clean 300 DPI print. Poor on faint, skewed or handwritten material.' },
      { q: 'Can OCR read handwriting?', a: 'Generally no. It is built for printed characters.' },
      { q: 'Should I OCR before or after compressing?', a: 'Before. Compression degrades the image the recognition depends on.' },
      { q: 'Does OCR work in other languages?', a: 'Yes, with the right language data selected. Recognition is much worse with the wrong language set.' },
    ],
    related: ['what-is-ocr-and-how-does-it-work', 'how-to-copy-text-from-a-scanned-pdf', 'how-to-compress-a-scanned-pdf'],
  },
];
