import type { BlogPost } from '../types';

export const troubleshootingPosts3: BlogPost[] = [

  {
    slug: 'how-to-work-with-pdfs-offline',
    title: 'How to Work With PDFs Offline',
    description: 'Edit, merge and convert PDFs with no internet connection — on a plane, on a secure network, or when you simply do not want files leaving the device.',
    keyword: 'work with pdfs offline',
    category: 'Troubleshooting',
    published: '2026-08-15',
    tool: 'merge-pdf',
    blocks: [
      { type: 'p', text: 'Working offline is sometimes a constraint and sometimes a choice. On a plane it is imposed; on a secure network it is policy; with a client file it is a decision you make deliberately.' },
      { type: 'h2', text: 'Browser tools work offline once loaded' },
      { type: 'p', text: 'A tool that processes files in your browser needs the network only to deliver the page. After that, the code is running on your machine and the work is local. Load the page while you have a connection, and it keeps working when you lose one.' },
      { type: 'p', text: 'This is also the cleanest proof that nothing is being uploaded: a tool that completes the job with the network off could not have transmitted your file.' },
      { type: 'h2', text: 'Preparing for a flight' },
      { type: 'steps', items: [
        'Open the tools you expect to need while you still have a connection.',
        'Leave those tabs open — do not close and reopen them.',
        'Have your files on the device rather than in cloud storage.',
        'Test one operation before you disconnect.',
      ] },
      { type: 'callout', title: 'Do not reload the tab', text: 'Reloading fetches the page again, which fails without a connection. Leave the tab as it is and it will keep working.' },
      { type: 'h2', text: 'What cannot work offline' },
      { type: 'table', head: ['Task', 'Offline?'], rows: [
        ['Merge, split, rotate, reorder', 'Yes'],
        ['Compress and optimise', 'Yes'],
        ['Convert between formats', 'Yes'],
        ['Sign, redact, watermark', 'Yes'],
        ['OCR', 'Yes, when the recognition runs locally'],
        ['Translate', 'No — machine translation is a remote service'],
        ['AI summarisation', 'Depends on where the model runs'],
      ] },
      { type: 'p', text: 'The rule is straightforward: anything that manipulates the file can be done locally; anything that needs a language model or a translation engine generally cannot.' },
      { type: 'h2', text: 'On restricted networks' },
      { type: 'p', text: 'Corporate policies frequently forbid uploading documents to external services, which rules out most online PDF tools. Local processing sidesteps the objection entirely — nothing crosses the network boundary. If you need to make that case to a security team, a Network tab recording showing zero uploads during an operation is the evidence to bring.' },
      { type: 'h2', text: 'Desktop alternatives' },
      { type: 'p', text: 'Preview on macOS, LibreOffice Draw, and command-line tools all work without a connection by definition. They are the right answer for recurring offline work; browser tools are better for the job in front of you.' },
    ],
    faqs: [
      { q: 'Do browser PDF tools work without internet?', a: 'Once the page has loaded, yes — the processing happens locally. Do not reload the tab.' },
      { q: 'How can I prove a tool is not uploading my file?', a: 'Disconnect after the page loads and run the operation. If it completes, nothing was transmitted.' },
      { q: 'Can I OCR offline?', a: 'Yes, when the recognition engine runs in the browser rather than on a server.' },
      { q: 'Why can I not translate offline?', a: 'Machine translation runs on remote infrastructure. There is no local equivalent of comparable quality.' },
    ],
    related: ['merge-pdf-without-uploading-files', 'is-it-safe-to-use-online-pdf-tools', 'best-free-pdf-tools-without-sign-up'],
  },

  {
    slug: 'how-to-fix-a-pdf-that-wont-print',
    title: 'How to Fix a PDF That Will Not Print',
    description: 'Work through the causes in order — permissions, printer drivers, rendering failures and corrupted spool jobs — and get the document printed.',
    keyword: 'pdf wont print',
    category: 'Troubleshooting',
    published: '2026-07-29',
    tool: 'unlock-pdf',
    blocks: [
      { type: 'p', text: 'A PDF that opens fine and refuses to print has a small number of causes. Work through them in order and one of them is the answer.' },
      { type: 'h2', text: 'Check these in sequence' },
      { type: 'steps', items: [
        'Print a different document. If nothing prints, the printer is the problem, not the PDF.',
        'Check document properties for printing permission — the file may be restricted.',
        'Try a different reader. Browsers print PDFs reliably and are a good test.',
        'Enable "print as image" in the advanced print settings.',
        'Print one page rather than the whole document, to find whether one page is at fault.',
        'Clear the print queue and restart the print spooler.',
      ] },
      { type: 'h2', text: 'Printing restrictions' },
      { type: 'p', text: 'A PDF can carry a flag asking readers to disable printing. Document properties will show printing as "Not Allowed". This is an advisory restriction rather than encryption, and it can be removed from a document you are entitled to print — though if you received it from someone else with that restriction deliberately set, it is worth asking rather than circumventing.' },
      { type: 'h2', text: 'What "print as image" does' },
      { type: 'p', text: 'It renders each page to a bitmap on your computer and sends that to the printer, instead of sending the page description for the printer to interpret. It is slower and slightly lower quality, and it works when the printer\'s own interpreter is choking on something — a complex transparency, an unusual font, a malformed object.' },
      { type: 'callout', title: 'One bad page, whole job fails', text: 'A single problematic page can stop an entire print job with no useful error. Printing page by page finds it quickly, and you can then handle that one page differently.' },
      { type: 'h2', text: 'Other things that stop a print' },
      { type: 'list', items: [
        'A stuck job at the front of the queue blocking everything behind it.',
        'A driver that needs updating, particularly after an operating system upgrade.',
        'Insufficient printer memory on an older network device faced with a large page.',
        'A corrupted PDF that renders on screen but fails when interpreted for print.',
        'A network printer that has silently gone offline.',
      ] },
      { type: 'h2', text: 'The reliable fallback' },
      { type: 'p', text: 'Convert the pages to images at 300 DPI and print those. It bypasses every rendering issue at once. Quality is slightly lower and the job is larger, and when you need the document on paper today it works.' },
    ],
    faqs: [
      { q: 'Why does my PDF say printing is not allowed?', a: 'A permission restriction is set in the document. It can be removed from a file you are entitled to print.' },
      { q: 'What does "print as image" do?', a: 'Renders pages to bitmaps on your computer before sending them, bypassing printer-side rendering problems.' },
      { q: 'Why does only one page fail?', a: 'That page contains something the printer cannot interpret. Print it as an image separately.' },
      { q: 'The job disappears from the queue with no error. Why?', a: 'Usually a driver problem. Update the driver, or print through a browser instead.' },
    ],
    related: ['how-to-print-a-pdf-correctly', 'how-to-remove-a-password-from-a-pdf', 'how-to-repair-a-corrupted-pdf'],
  },

  {
    slug: 'why-are-my-pdf-images-not-showing',
    title: 'Why Are Images Not Showing in My PDF?',
    description: 'Blank boxes, missing logos and grey rectangles where pictures should be — the causes, and how to get the images back.',
    keyword: 'pdf images not showing',
    category: 'Troubleshooting',
    published: '2026-08-19',
    tool: 'repair-pdf',
    blocks: [
      { type: 'p', text: 'Images that fail to display in a PDF look like corruption and usually are not. There are five likely causes and they are quick to distinguish.' },
      { type: 'h2', text: 'One: the reader is set not to show them' },
      { type: 'p', text: 'Some readers have an option to suppress images for speed, and some corporate builds enable it by default. Check the display preferences first — it takes ten seconds and it explains a surprising share of cases.' },
      { type: 'h2', text: 'Two: an unsupported image encoding' },
      { type: 'p', text: 'JPEG 2000 and some CCITT variants are not handled by every renderer. The page draws, the image slot stays empty. Opening the file in a different reader confirms it immediately: if the picture appears elsewhere, the file is fine.' },
      { type: 'h2', text: 'Three: the image was never embedded' },
      { type: 'p', text: 'A PDF can reference an external file rather than embedding it. This is rare and always a mistake for a distributed document — the image exists on the author\'s machine and nowhere else. There is no fix except asking for a corrected file.' },
      { type: 'h2', text: 'Four: transparency handling' },
      { type: 'p', text: 'An image with a soft mask or an unusual blend mode can render as a black or white rectangle in a renderer that does not support it. Common with logos placed with transparency.' },
      { type: 'h2', text: 'Five: genuine damage' },
      { type: 'p', text: 'If the image data itself is corrupted, the page renders with a gap. A repair pass may recover it; if the bytes are gone, they are gone.' },
      { type: 'callout', title: 'Try a browser first', text: 'Drag the file into Chrome or Firefox. Browser renderers are robust and support a wide range of encodings. If the images appear there, the document is fine and your reader is the problem.' },
      { type: 'h2', text: 'What to do' },
      { type: 'steps', items: [
        'Open it in a browser to establish whether the file or the reader is at fault.',
        'Check your reader\'s image display setting.',
        'Update the reader.',
        'Run a repair if it fails everywhere.',
        'Ask the sender to re-export, embedding all images.',
      ] },
      { type: 'h2', text: 'If you are producing the document' },
      { type: 'p', text: 'Embed every image, avoid exotic encodings for anything widely distributed, and flatten transparency where you can. Then open the result in a browser and a desktop reader before sending — the same two-viewer check that catches most rendering surprises.' },
    ],
    faqs: [
      { q: 'Why do images show in Chrome but not Acrobat?', a: 'Different renderers support different encodings. It confirms the file is intact.' },
      { q: 'Can missing images be recovered?', a: 'If the data is in the file, a repair may restore them. If the image was never embedded, no.' },
      { q: 'Why is there a black box where the logo should be?', a: 'Transparency that the renderer cannot handle. Flatten it when producing the file.' },
      { q: 'How do I stop this happening in documents I create?', a: 'Embed all images, use common encodings, and check the output in two different readers.' },
    ],
    related: ['how-to-repair-a-corrupted-pdf', 'why-does-my-pdf-look-different-on-another-device', 'how-to-extract-images-from-a-pdf'],
  },
];
