import type { BlogPost } from '../types';

export const troubleshootingPosts4: BlogPost[] = [
  {
    slug: 'how-to-fix-a-pdf-that-opens-blank',
    title: 'How to Fix a PDF That Opens Blank',
    description: 'The document opens, the page count is right, and every page is empty. Here are the causes and how to get the content back.',
    keyword: 'pdf opens blank',
    category: 'Troubleshooting',
    published: '2026-08-21',
    tool: 'repair-pdf',
    blocks: [
      { type: 'p', text: 'A blank PDF is different from one that will not open, and it is usually better news: the file structure is sound enough for the reader to count the pages, which means most of it is intact.' },
      { type: 'h2', text: 'Establish what you are looking at' },
      { type: 'steps', items: [
        'Check the page count. Correct page count with blank pages points at rendering rather than corruption.',
        'Check the file size. A large file with blank pages contains content that is not being drawn.',
        'Open it in a browser. Chrome and Firefox render many documents that desktop readers refuse.',
        'Try to select text on a blank page — if text highlights, the content is there and invisible.',
      ] },
      { type: 'h2', text: 'The likely causes' },
      { type: 'h3', text: 'A reader that cannot render it' },
      { type: 'p', text: 'The most common by far. An older reader faced with newer transparency, layer or font constructs draws nothing rather than approximating. Updating the reader, or opening the file in a browser, fixes it.' },
      { type: 'h3', text: 'Hidden layers' },
      { type: 'p', text: 'A document with optional content groups can have layers turned off. The content is present and not displayed. Look for a layers panel in your reader and enable everything.' },
      { type: 'h3', text: 'Form fields that have not rendered' },
      { type: 'p', text: 'If the document is a form and the page looks empty apart from lines, the field appearances have not been generated. Flattening the document draws the values permanently into the page.' },
      { type: 'h3', text: 'White text or a covering shape' },
      { type: 'p', text: 'Rare and worth checking: select all on a blank page and see whether anything highlights. Text set to white on white is invisible and entirely present.' },
      { type: 'h3', text: 'The pages really are blank' },
      { type: 'p', text: 'An export that failed, a scanner that fed nothing, or a document generated with no content. The file size tells you — a genuinely empty ten-page PDF is a few kilobytes.' },
      { type: 'callout', title: 'File size is the fastest diagnostic', text: 'A 12 MB PDF showing blank pages certainly contains something. A 4 KB one probably does not. Check that before troubleshooting anything else.' },
      { type: 'h2', text: 'What to try' },
      { type: 'list', items: [
        'Open it in a browser.',
        'Update your reader.',
        'Turn on all layers, if there is a layers panel.',
        'Flatten the document, if it is a form.',
        'Run a repair to rebuild the structure.',
        'Ask the sender to re-export and flatten before sending.',
      ] },
      { type: 'h2', text: 'If you are producing documents that do this' },
      { type: 'p', text: 'Flatten forms before distributing them, avoid relying on optional content layers, and check the output in a second reader. Blank pages at the recipient\'s end are almost always something that could have been caught by opening the file once in a different viewer.' },
    ],
    faqs: [
      { q: 'Why is my PDF blank in Acrobat but fine in Chrome?', a: 'The browser renderer supports something your desktop reader does not, or the reader needs updating. The file is fine.' },
      { q: 'My form is blank when the recipient opens it. Why?', a: 'Field appearances did not render. Flatten the document before sending.' },
      { q: 'Can a repair fix blank pages?', a: 'Sometimes, when the structure is damaged. It cannot add content that is not in the file.' },
      { q: 'How do I know whether the pages are really empty?', a: 'Check the file size and try to select text. A large file with nothing selectable is content that is not being drawn.' },
    ],
    related: ['how-to-repair-a-corrupted-pdf', 'pdf-wont-open-how-to-fix-it', 'how-to-flatten-a-pdf'],
  },

  {
    slug: 'how-to-check-a-pdf-before-you-send-it',
    title: 'How to Check a PDF Before You Send It',
    description: 'A two-minute checklist that catches the things that embarrass people — hidden data, failed redactions, missing fonts and wrong page order.',
    keyword: 'check pdf before sending',
    category: 'Troubleshooting',
    published: '2026-08-18',
    tool: 'optimize-pdf',
    blocks: [
      { type: 'p', text: 'Almost every PDF incident — the leaked name, the blank form, the wrong version — would have been caught by two minutes of checking. Here is what to look at.' },
      { type: 'h2', text: 'Content' },
      { type: 'steps', items: [
        'Check the page count matches what you intend to send.',
        'Page through the whole document rather than the first page.',
        'Confirm the pages are in the right order.',
        'Check nothing internal survived — draft watermarks, working columns, reviewer comments.',
        'Confirm this is the final version, not the draft with a similar filename.',
      ] },
      { type: 'h2', text: 'Anything you removed' },
      { type: 'steps', items: [
        'Copy text from every redacted area — nothing should come back.',
        'Search the document for the name or number you redacted.',
        'Check headers and footers, which repeat on every page and are routinely missed.',
        'Check the bookmarks, which can restate a removed section.',
      ] },
      { type: 'h2', text: 'Hidden data' },
      { type: 'list', items: [
        'Open document properties and read the Author, Title and Subject fields.',
        'Check for annotations and comments.',
        'Check for embedded attachments.',
        'Check the filename itself does not disclose something.',
      ] },
      { type: 'callout', title: 'The Title field is the one that catches people', text: 'It usually holds the original filename. "offer-v3-final-lowball.docx" sitting in the properties of a document you carefully redacted is a bad way to end a negotiation.' },
      { type: 'h2', text: 'Rendering' },
      { type: 'steps', items: [
        'Check the Fonts tab — everything should be embedded.',
        'Open the file in a second reader, ideally a browser.',
        'Check it on a phone if the recipient may read it there.',
        'Print one page if it will be printed.',
      ] },
      { type: 'h2', text: 'Delivery' },
      { type: 'list', items: [
        'Check the file size against the recipient\'s likely limit.',
        'Give the file a name that identifies it: subject, party and date.',
        'Check the recipient address character by character.',
        'Say in the message what is attached and what you expect back.',
      ] },
      { type: 'h2', text: 'When it matters most' },
      { type: 'p', text: 'Run the full list on anything going outside your organisation, anything with legal effect, anything you have redacted, and anything being published. For an internal draft to a colleague, the content checks are enough.' },
      { type: 'h2', text: 'Build the checks into how you work' },
      { type: 'p', text: 'A checklist you have to remember is a checklist you will skip on the day you are busy. The checks that survive are the ones attached to a step you already take: renaming the file, attaching it, writing the covering message.' },
      { type: 'p', text: 'Two habits carry most of the value. Always open the finished file from your downloads folder before attaching it — that one action catches wrong versions, blank forms and failed exports. And always write the covering message before attaching, so you are forced to describe what you are sending and notice when the description does not match the file.' },
      { type: 'p', text: 'For teams, agree a short standard: naming convention, metadata cleared, second reader check on anything external. Written down once, it stops being something each person decides individually under time pressure.' },
    ],
    faqs: [
      { q: 'What gets missed most often?', a: 'Document metadata, and text under black boxes that were never real redactions.' },
      { q: 'How do I check whether a redaction worked?', a: 'Copy from the redacted area and search the document for the removed term. Both should return nothing.' },
      { q: 'Why check in a second reader?', a: 'Because rendering differs between them. What looks right in yours may not in the recipient\'s.' },
      { q: 'Is this necessary every time?', a: 'For external, legal or published documents, yes. For internal drafts, the content checks suffice.' },
    ],
    related: ['what-personal-data-is-hidden-in-your-pdf', 'how-to-redact-a-pdf-properly', 'why-does-my-pdf-look-different-on-another-device'],
  },

  {
    slug: 'how-to-make-a-pdf-accessible',
    title: 'How to Make a PDF Accessible',
    description: 'What makes a PDF usable with a screen reader, why most PDFs are not, and the practical steps that make the biggest difference.',
    keyword: 'how to make a pdf accessible',
    category: 'Troubleshooting',
    published: '2026-08-12',
    tool: 'ocr-pdf',
    blocks: [
      { type: 'p', text: 'A PDF describes where marks go on a page. A screen reader needs to know what those marks mean — this is a heading, this is a table cell, this image shows a chart. Bridging that gap is what accessibility work on a PDF consists of.' },
      { type: 'h2', text: 'What an accessible PDF has' },
      { type: 'list', items: [
        'Real text rather than images of text.',
        'Tags marking headings, paragraphs, lists and tables as what they are.',
        'A defined reading order, so content is announced in the right sequence.',
        'Alternative text on every meaningful image.',
        'Table headers identified so cells can be related to them.',
        'A document language set, so the correct pronunciation is used.',
        'A document title, which is what a screen reader announces first.',
        'Sufficient colour contrast, and meaning not carried by colour alone.',
      ] },
      { type: 'h2', text: 'The single biggest problem' },
      { type: 'p', text: 'Scanned documents. A screen reader encountering a scan finds no text at all and announces nothing. The user has an empty document. Running OCR is the single highest-impact accessibility improvement available for most archives, and it takes one pass.' },
      { type: 'callout', title: 'OCR is the floor, not the ceiling', text: 'OCR makes text available. It does not create heading structure or reading order. It moves a document from unusable to readable, which is a large step and not the whole journey.' },
      { type: 'h2', text: 'Fix it at the source' },
      { type: 'p', text: 'Tagging is far easier to get right in the authoring tool than to add afterwards. In Word, use the built-in heading styles rather than manually formatting large bold text, use real lists and real tables, add alt text to images, and export with "document structure tags for accessibility" enabled. The tags carry through into the PDF automatically.' },
      { type: 'p', text: 'Retro-fitting tags to an untagged PDF is genuinely laborious work, which is why doing it in the source is worth insisting on.' },
      { type: 'h2', text: 'A practical order of work' },
      { type: 'steps', items: [
        'OCR anything scanned.',
        'Set the document title and language in the properties.',
        'Re-export from the source with tagging enabled, where you have the source.',
        'Add alternative text to images.',
        'Check the reading order, particularly on multi-column pages.',
        'Test with an actual screen reader rather than only a checker.',
      ] },
      { type: 'h2', text: 'Consider whether it should be a PDF' },
      { type: 'p', text: 'For content that will be read on screen, an HTML page is more accessible by default: it reflows, it carries semantic structure natively, and assistive technology handles it far better. Publish the page and offer the PDF for people who want to print or file it. That single decision solves more accessibility problems than any amount of remediation.' },
    ],
    faqs: [
      { q: 'Are scanned PDFs accessible?', a: 'No. Without OCR a screen reader finds nothing at all.' },
      { q: 'Does OCR make a PDF accessible?', a: 'It makes the text available, which is the biggest step. Structure, reading order and alt text still need attention.' },
      { q: 'What is PDF/UA?', a: 'The accessibility standard for PDF, specifying tagging and structure requirements in detail.' },
      { q: 'Is HTML better than PDF for accessibility?', a: 'Generally yes — it reflows and carries semantics natively. Publish HTML and offer the PDF alongside.' },
    ],
    related: ['how-to-make-a-scanned-pdf-searchable', 'how-to-convert-pdf-to-pdfa-for-archiving', 'how-to-choose-between-sending-a-pdf-or-a-word-document'],
  },
];
