import type { BlogPost } from '../types';

export const troubleshootingPosts3: BlogPost[] = [
  {
    slug: 'pdf-page-sizes-explained',
    title: 'PDF Page Sizes Explained: A4, Letter, Legal and the Rest',
    description: 'Why your document prints with odd margins, what the difference between A4 and Letter costs you, and how to fix a mixed-size PDF.',
    keyword: 'pdf page sizes',
    category: 'Troubleshooting',
    published: '2026-07-13',
    tool: 'crop-pdf',
    blocks: [
      { type: 'p', text: 'Page size is the invisible cause behind a lot of printing frustration. A document that prints beautifully in London comes out with a white band in Chicago, and nothing in the file looks wrong.' },
      { type: 'h2', text: 'The sizes you will meet' },
      { type: 'table', head: ['Name', 'Millimetres', 'Inches', 'Used in'], rows: [
        ['A4', '210 × 297', '8.27 × 11.69', 'Most of the world'],
        ['US Letter', '216 × 279', '8.5 × 11', 'North America'],
        ['US Legal', '216 × 356', '8.5 × 14', 'North American legal work'],
        ['A3', '297 × 420', '11.69 × 16.54', 'Plans and posters'],
        ['A5', '148 × 210', '5.83 × 8.27', 'Booklets and leaflets'],
        ['Tabloid', '279 × 432', '11 × 17', 'North American large format'],
      ] },
      { type: 'p', text: 'A4 and Letter are close enough to be confusing and different enough to matter: Letter is 6mm wider and 18mm shorter. Print A4 content on Letter and the bottom is at risk; print Letter on A4 and you get a band of white at the foot.' },
      { type: 'h2', text: 'The A series has a useful property' },
      { type: 'p', text: 'Every A size is exactly half the one before it, folded across the long edge. A4 is half of A3, A5 is half of A4, and the proportions stay identical — which is why scaling between them is clean and why "two A5 pages on one A4 sheet" works perfectly. US sizes have no such relationship, which is why booklet printing there is fiddlier.' },
      { type: 'callout', title: 'A PDF can mix sizes freely', text: 'Page size is stored per page, so an A4 report can contain an A3 foldout and a Letter-sized invoice. Readers handle it; printers are less happy, and a mixed-size document is worth normalising before printing.' },
      { type: 'h2', text: 'Checking what you have' },
      { type: 'p', text: 'Document properties report the page size — usually of the first page, which is why a mixed document can look consistent when it is not. Page through a long merged pack and look for pages that render at a different width; that is where the print problems will be.' },
      { type: 'h2', text: 'Fixing a mixed-size document' },
      { type: 'list', items: [
        'Print with scale-to-fit, which is the simplest answer and slightly resizes some pages.',
        'Crop the oversized pages down to a consistent visible size.',
        'Regenerate the outlying pages at the right size from their source.',
        'Accept it, if the document is for screen reading only.',
      ] },
      { type: 'h2', text: 'Choosing a size when creating a document' },
      { type: 'p', text: 'Use the standard of your primary audience: A4 outside North America, Letter inside it. For an international readership, A4 is the safer default — a Letter document printed on A4 loses nothing, whereas an A4 document printed on Letter risks the bottom margin.' },
    ],
    faqs: [
      { q: 'What is the difference between A4 and Letter?', a: 'Letter is 6mm wider and 18mm shorter. Enough to cause margin problems in both directions.' },
      { q: 'Can one PDF have different page sizes?', a: 'Yes — size is stored per page. Readers cope; printers prefer consistency.' },
      { q: 'How do I change a PDF page size?', a: 'Crop it down, or scale during printing. Changing the size without altering the content means cropping or padding.' },
      { q: 'Which should I use for international documents?', a: 'A4. It is the more widely used standard and prints acceptably on Letter.' },
    ],
    related: ['how-to-print-a-pdf-correctly', 'how-to-crop-a-pdf', 'how-to-convert-jpg-to-pdf'],
  },

  {
    slug: 'best-free-pdf-tools-without-sign-up',
    title: 'The Best Free PDF Tools That Do Not Need a Sign-Up',
    description: 'What to look for in a free PDF tool, the limits that are usually hidden until the last step, and how to check where your file is processed.',
    keyword: 'free pdf tools no sign up',
    category: 'Troubleshooting',
    published: '2026-08-01',
    tool: 'merge-pdf',
    blocks: [
      { type: 'p', text: '"Free" covers a lot of business models, and most of them reveal themselves at the download button. Knowing what to check before you invest ten minutes in a document saves the annoyance.' },
      { type: 'h2', text: 'The limits that appear at the end' },
      { type: 'list', items: [
        'A watermark on the output, removable for a subscription.',
        'A cap of two or three files a day, counted by cookie.',
        'A page or file-size limit not stated until processing finishes.',
        'An account required to download the result you have already produced.',
        'The genuinely useful settings reserved for the paid tier.',
      ] },
      { type: 'p', text: 'None of these are dishonest — they are how a free tier funds a paid one — but they are usually disclosed late, which is the part worth anticipating.' },
      { type: 'h2', text: 'What actually matters when choosing' },
      { type: 'table', head: ['Criterion', 'Why it matters'], rows: [
        ['Where processing happens', 'Determines whether your file is uploaded at all'],
        ['Watermarks', 'A watermarked output is unusable for most real work'],
        ['Daily limits', 'You will hit them on the day you are busiest'],
        ['Account requirement', 'A sign-up wall is a cost, just not a monetary one'],
        ['Output quality', 'Rasterised text is a common shortcut in free tools'],
        ['Privacy policy', 'Absence of one is itself informative'],
      ] },
      { type: 'callout', title: 'Test with a document you do not care about', text: 'Run a throwaway file through first. You will find out about the watermark, the sign-up wall and the quality before you have committed anything real.' },
      { type: 'h2', text: 'Server-side or browser-side' },
      { type: 'p', text: 'This is the difference that matters most and is almost never advertised. A tool that processes in your browser never receives your file; a tool that uploads has it. Check by opening developer tools and watching the Network tab, or simply by disconnecting from the internet after the page loads and seeing whether the tool still works.' },
      { type: 'h2', text: 'Free desktop options worth knowing' },
      { type: 'list', items: [
        'Preview on macOS — pages, annotations, signatures, basic compression.',
        'Browser PDF viewers — form filling, signatures and printing to PDF.',
        'LibreOffice Draw — direct PDF editing, with variable layout results.',
        'Command-line tools — complete control, and a real learning curve.',
      ] },
      { type: 'h2', text: 'When paying is right' },
      { type: 'p', text: 'Prepress and colour management, accessibility remediation at scale, complex form building, certificate-based signing infrastructure. Professional tools earn their price on professional problems. Merging two files and adding a signature is not one.' },
    ],
    faqs: [
      { q: 'Are free PDF tools safe?', a: 'It depends entirely on whether they upload. A browser-based tool that processes locally is as safe as opening the file yourself.' },
      { q: 'Why do some free tools add watermarks?', a: 'To make the free tier unsuitable for professional use and drive subscriptions. Look for tools that do not.' },
      { q: 'Do I need Acrobat?', a: 'For prepress, accessibility work and complex forms, yes. For everyday page operations, no.' },
      { q: 'How do I know if a tool uploads my file?', a: 'Watch the Network tab in developer tools, or disconnect from the internet and see whether it still works.' },
    ],
    related: ['is-it-safe-to-use-online-pdf-tools', 'how-to-work-with-pdfs-offline', 'how-to-edit-a-pdf-without-adobe'],
  },

  {
    slug: 'how-to-work-with-pdfs-offline',
    title: 'How to Work With PDFs Offline',
    description: 'Edit, merge and convert PDFs with no internet connection — on a plane, on a secure network, or when you simply do not want files leaving the device.',
    keyword: 'work with pdfs offline',
    category: 'Troubleshooting',
    published: '2026-08-15',
    tool: 'merge-pdf',
    blocks: [
      { type: 'p', text: 'Working offline is sometimes a constraint and sometimes a choice. On a plane it is imposed; on a secure network it is policy; with a client file it is a decision you make deliberately.' },
      { type: 'h2', text: 'Browser tools work offline once loaded' },
      { type: 'p', text: 'A tool that processes files in your browser needs the network only to deliver the page. After that, the code is running on your machine and the work is local. Load the page while you have a connection, and it keeps working when you lose one.' },
      { type: 'p', text: 'This is also the cleanest proof that nothing is being uploaded: a tool that completes the job with the network off could not have transmitted your file.' },
      { type: 'h2', text: 'Preparing for a flight' },
      { type: 'steps', items: [
        'Open the tools you expect to need while you still have a connection.',
        'Leave those tabs open — do not close and reopen them.',
        'Have your files on the device rather than in cloud storage.',
        'Test one operation before you disconnect.',
      ] },
      { type: 'callout', title: 'Do not reload the tab', text: 'Reloading fetches the page again, which fails without a connection. Leave the tab as it is and it will keep working.' },
      { type: 'h2', text: 'What cannot work offline' },
      { type: 'table', head: ['Task', 'Offline?'], rows: [
        ['Merge, split, rotate, reorder', 'Yes'],
        ['Compress and optimise', 'Yes'],
        ['Convert between formats', 'Yes'],
        ['Sign, redact, watermark', 'Yes'],
        ['OCR', 'Yes, when the recognition runs locally'],
        ['Translate', 'No — machine translation is a remote service'],
        ['AI summarisation', 'Depends on where the model runs'],
      ] },
      { type: 'p', text: 'The rule is straightforward: anything that manipulates the file can be done locally; anything that needs a language model or a translation engine generally cannot.' },
      { type: 'h2', text: 'On restricted networks' },
      { type: 'p', text: 'Corporate policies frequently forbid uploading documents to external services, which rules out most online PDF tools. Local processing sidesteps the objection entirely — nothing crosses the network boundary. If you need to make that case to a security team, a Network tab recording showing zero uploads during an operation is the evidence to bring.' },
      { type: 'h2', text: 'Desktop alternatives' },
      { type: 'p', text: 'Preview on macOS, LibreOffice Draw, and command-line tools all work without a connection by definition. They are the right answer for recurring offline work; browser tools are better for the job in front of you.' },
    ],
    faqs: [
      { q: 'Do browser PDF tools work without internet?', a: 'Once the page has loaded, yes — the processing happens locally. Do not reload the tab.' },
      { q: 'How can I prove a tool is not uploading my file?', a: 'Disconnect after the page loads and run the operation. If it completes, nothing was transmitted.' },
      { q: 'Can I OCR offline?', a: 'Yes, when the recognition engine runs in the browser rather than on a server.' },
      { q: 'Why can I not translate offline?', a: 'Machine translation runs on remote infrastructure. There is no local equivalent of comparable quality.' },
    ],
    related: ['merge-pdf-without-uploading-files', 'is-it-safe-to-use-online-pdf-tools', 'best-free-pdf-tools-without-sign-up'],
  },

  {
    slug: 'why-does-my-pdf-look-different-on-another-device',
    title: 'Why Does My PDF Look Different on Another Device?',
    description: 'PDFs are meant to look identical everywhere. When they do not, it is one of five causes — and four of them are fixable.',
    keyword: 'pdf looks different on another device',
    category: 'Troubleshooting',
    published: '2026-07-15',
    tool: 'pdf-to-pdfa',
    blocks: [
      { type: 'p', text: 'Fixed appearance is the entire promise of the format, so a PDF that renders differently on another machine is a genuine failure rather than a quirk. It is usually one of five things.' },
      { type: 'h2', text: 'One: fonts were not embedded' },
      { type: 'p', text: 'By far the most common cause. The document names a font, the other machine does not have it, and something else is substituted — with different letter widths, so lines wrap differently and page breaks move. Check the Fonts tab in document properties; anything not marked embedded is a liability.' },
      { type: 'h2', text: 'Two: the reader renders differently' },
      { type: 'p', text: 'Every reader has its own rendering engine. Anti-aliasing, hinting and transparency handling all vary, so text weight and shading can differ subtly between Acrobat, Preview, Chrome and a phone viewer. The layout is the same; the texture is not.' },
      { type: 'h2', text: 'Three: colour handling' },
      { type: 'p', text: 'A document authored in CMYK for print, or one without an embedded colour profile, is interpreted by each device according to its own settings. Colours shift, sometimes considerably. Embedding a colour profile fixes it.' },
      { type: 'h2', text: 'Four: transparency flattening' },
      { type: 'p', text: 'Drop shadows, soft masks and overlapping transparent objects are handled differently by different renderers. Older engines flatten them, sometimes producing visible seams or boxes where the effect was smooth.' },
      { type: 'h2', text: 'Five: it is a scan' },
      { type: 'p', text: 'A scanned page is an image, and images are scaled by the display. On a low-resolution screen a 300 DPI scan is downsampled on the fly, which can look softer or sharper depending on the algorithm.' },
      { type: 'callout', title: 'Test before you distribute', text: 'Open anything important in a browser, a desktop reader and on a phone before sending it. Three viewers catch nearly every rendering surprise.' },
      { type: 'h2', text: 'Making a document render consistently' },
      { type: 'steps', items: [
        'Embed all fonts when exporting.',
        'Embed a colour profile, or author in RGB for screen documents.',
        'Flatten transparency yourself if the document uses heavy effects.',
        'Convert to PDF/A, which enforces embedding and explicit colour.',
        'Check it in at least two readers before sending.',
      ] },
      { type: 'h2', text: 'When the difference matters' },
      { type: 'p', text: 'Font substitution changes pagination, and pagination matters in contracts, filings and anything with cross-references to page numbers. A document that is ten pages for you and eleven for the counterparty is a real problem, not a cosmetic one.' },
    ],
    faqs: [
      { q: 'Why do the fonts change on another computer?', a: 'They were not embedded, so the reader substituted something else.' },
      { q: 'Why does my page count differ?', a: 'Substituted fonts have different widths, so text reflows and pushes content onto another page.' },
      { q: 'Do colours really change between devices?', a: 'Yes, without an embedded profile. Screens and print interpret unmanaged colour differently.' },
      { q: 'How do I guarantee consistency?', a: 'Embed fonts and a colour profile, or convert to PDF/A, which requires both.' },
    ],
    related: ['how-to-fix-fonts-not-displaying-in-a-pdf', 'how-to-convert-pdf-to-pdfa-for-archiving', 'how-to-check-a-pdf-before-you-send-it'],
  },

  {
    slug: 'how-to-fix-a-pdf-that-wont-print',
    title: 'How to Fix a PDF That Will Not Print',
    description: 'Work through the causes in order — permissions, printer drivers, rendering failures and corrupted spool jobs — and get the document printed.',
    keyword: 'pdf wont print',
    category: 'Troubleshooting',
    published: '2026-07-29',
    tool: 'unlock-pdf',
    blocks: [
      { type: 'p', text: 'A PDF that opens fine and refuses to print has a small number of causes. Work through them in order and one of them is the answer.' },
      { type: 'h2', text: 'Check these in sequence' },
      { type: 'steps', items: [
        'Print a different document. If nothing prints, the printer is the problem, not the PDF.',
        'Check document properties for printing permission — the file may be restricted.',
        'Try a different reader. Browsers print PDFs reliably and are a good test.',
        'Enable "print as image" in the advanced print settings.',
        'Print one page rather than the whole document, to find whether one page is at fault.',
        'Clear the print queue and restart the print spooler.',
      ] },
      { type: 'h2', text: 'Printing restrictions' },
      { type: 'p', text: 'A PDF can carry a flag asking readers to disable printing. Document properties will show printing as "Not Allowed". This is an advisory restriction rather than encryption, and it can be removed from a document you are entitled to print — though if you received it from someone else with that restriction deliberately set, it is worth asking rather than circumventing.' },
      { type: 'h2', text: 'What "print as image" does' },
      { type: 'p', text: 'It renders each page to a bitmap on your computer and sends that to the printer, instead of sending the page description for the printer to interpret. It is slower and slightly lower quality, and it works when the printer\'s own interpreter is choking on something — a complex transparency, an unusual font, a malformed object.' },
      { type: 'callout', title: 'One bad page, whole job fails', text: 'A single problematic page can stop an entire print job with no useful error. Printing page by page finds it quickly, and you can then handle that one page differently.' },
      { type: 'h2', text: 'Other things that stop a print' },
      { type: 'list', items: [
        'A stuck job at the front of the queue blocking everything behind it.',
        'A driver that needs updating, particularly after an operating system upgrade.',
        'Insufficient printer memory on an older network device faced with a large page.',
        'A corrupted PDF that renders on screen but fails when interpreted for print.',
        'A network printer that has silently gone offline.',
      ] },
      { type: 'h2', text: 'The reliable fallback' },
      { type: 'p', text: 'Convert the pages to images at 300 DPI and print those. It bypasses every rendering issue at once. Quality is slightly lower and the job is larger, and when you need the document on paper today it works.' },
    ],
    faqs: [
      { q: 'Why does my PDF say printing is not allowed?', a: 'A permission restriction is set in the document. It can be removed from a file you are entitled to print.' },
      { q: 'What does "print as image" do?', a: 'Renders pages to bitmaps on your computer before sending them, bypassing printer-side rendering problems.' },
      { q: 'Why does only one page fail?', a: 'That page contains something the printer cannot interpret. Print it as an image separately.' },
      { q: 'The job disappears from the queue with no error. Why?', a: 'Usually a driver problem. Update the driver, or print through a browser instead.' },
    ],
    related: ['how-to-print-a-pdf-correctly', 'how-to-remove-a-password-from-a-pdf', 'how-to-repair-a-corrupted-pdf'],
  },

  {
    slug: 'why-are-my-pdf-images-not-showing',
    title: 'Why Are Images Not Showing in My PDF?',
    description: 'Blank boxes, missing logos and grey rectangles where pictures should be — the causes, and how to get the images back.',
    keyword: 'pdf images not showing',
    category: 'Troubleshooting',
    published: '2026-08-19',
    tool: 'repair-pdf',
    blocks: [
      { type: 'p', text: 'Images that fail to display in a PDF look like corruption and usually are not. There are five likely causes and they are quick to distinguish.' },
      { type: 'h2', text: 'One: the reader is set not to show them' },
      { type: 'p', text: 'Some readers have an option to suppress images for speed, and some corporate builds enable it by default. Check the display preferences first — it takes ten seconds and it explains a surprising share of cases.' },
      { type: 'h2', text: 'Two: an unsupported image encoding' },
      { type: 'p', text: 'JPEG 2000 and some CCITT variants are not handled by every renderer. The page draws, the image slot stays empty. Opening the file in a different reader confirms it immediately: if the picture appears elsewhere, the file is fine.' },
      { type: 'h2', text: 'Three: the image was never embedded' },
      { type: 'p', text: 'A PDF can reference an external file rather than embedding it. This is rare and always a mistake for a distributed document — the image exists on the author\'s machine and nowhere else. There is no fix except asking for a corrected file.' },
      { type: 'h2', text: 'Four: transparency handling' },
      { type: 'p', text: 'An image with a soft mask or an unusual blend mode can render as a black or white rectangle in a renderer that does not support it. Common with logos placed with transparency.' },
      { type: 'h2', text: 'Five: genuine damage' },
      { type: 'p', text: 'If the image data itself is corrupted, the page renders with a gap. A repair pass may recover it; if the bytes are gone, they are gone.' },
      { type: 'callout', title: 'Try a browser first', text: 'Drag the file into Chrome or Firefox. Browser renderers are robust and support a wide range of encodings. If the images appear there, the document is fine and your reader is the problem.' },
      { type: 'h2', text: 'What to do' },
      { type: 'steps', items: [
        'Open it in a browser to establish whether the file or the reader is at fault.',
        'Check your reader\'s image display setting.',
        'Update the reader.',
        'Run a repair if it fails everywhere.',
        'Ask the sender to re-export, embedding all images.',
      ] },
      { type: 'h2', text: 'If you are producing the document' },
      { type: 'p', text: 'Embed every image, avoid exotic encodings for anything widely distributed, and flatten transparency where you can. Then open the result in a browser and a desktop reader before sending — the same two-viewer check that catches most rendering surprises.' },
    ],
    faqs: [
      { q: 'Why do images show in Chrome but not Acrobat?', a: 'Different renderers support different encodings. It confirms the file is intact.' },
      { q: 'Can missing images be recovered?', a: 'If the data is in the file, a repair may restore them. If the image was never embedded, no.' },
      { q: 'Why is there a black box where the logo should be?', a: 'Transparency that the renderer cannot handle. Flatten it when producing the file.' },
      { q: 'How do I stop this happening in documents I create?', a: 'Embed all images, use common encodings, and check the output in two different readers.' },
    ],
    related: ['how-to-repair-a-corrupted-pdf', 'why-does-my-pdf-look-different-on-another-device', 'how-to-extract-images-from-a-pdf'],
  },
];
